### ISSUE TITLE
Stuck when getting out of the seat.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10073]
As i see, the problem is a fixed point of exit and not exit to "seat from %coord"
![20181119231445_1](https://user-images.githubusercontent.com/4980243/48732663-4e011500-ec51-11e8-9ebf-e2bcec084389.jpg)
![20181119231448_1](https://user-images.githubusercontent.com/4980243/48732666-4fcad880-ec51-11e8-831d-762b7ef94165.jpg)
![20181119231505_1](https://user-images.githubusercontent.com/4980243/48732668-51949c00-ec51-11e8-8088-995c30c778c6.jpg)

**Comment by SlayksWood** [comment]
Now you can only get stuck in buildings that are 2 blocks high. Because you appear on the chair.
![image](https://user-images.githubusercontent.com/45708377/66981486-8d7fed80-f0bc-11e9-9546-206141d5d8ef.png)
![image](https://user-images.githubusercontent.com/45708377/66981461-793bf080-f0bc-11e9-8865-6a744de72395.png)
