### ISSUE TITLE
Master: species, tortoise has green color like plant.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10241]
![default](https://user-images.githubusercontent.com/4980243/49695092-8176f580-fba6-11e8-8e4d-0f58f5ee4393.png)

**Comment by Spydarlee** [comment]
Hey @johnkslg, would you mind clarifying the expected behaviour here, please? I realise I'm not actually sure what green/blue are supposed to represent generally!

But this bug seems to be related to the fact that other animals have a specific Carcass item (blue background) whereas a Tortoise only produces generic Raw Meat (green background).

Although I'm not sure where the above screenshot actually comes from and why they all look like generic Raw meat here (did the animal-specific icons and carcass naming go in recently, perhaps?)

If so, do we want to add a 'Tortoise Carcass' item, or is this already working as expected?

![image](https://user-images.githubusercontent.com/553695/54129447-2acbc280-4406-11e9-9b45-3eb68f79c2d6.png)
