### ISSUE TITLE
Corrupted saves / issues with property claims 

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#1025]
little info on this here, but something i heard about while listening in on other community hosted servers. Server seems to crash and then property claims get broken  and save refuses to load .. it seems that the saves are broken also for all backups . only solution right now seems to open the save file and deleting the property claim

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1324/5-3-pumpjack-inside-of-cart-crashes-server-upon-loading-of-server

**Comment by shortybsd** [comment]
Found the problem, it is the carts in the property claims. I looked at that data file and there are hundreds of carts all within the file. Abyssal and I tried to replicate all the new changes on my server to see what would crash it. It has to be the carts. I do know there will be a lot of mad people upon logging in to find their claims all gone. Any type of editor or a way to delete all carts via a command?

**Comment by Aether42** [comment]
Just wondering if this could be related to another issue with Carts and deeds. Everytime I use hammer to deconstruct cart, and then re-place it, it generates a new deeditem. Not sure how the code handles this, but I literally have dozens of deeds from the same 2 carts.
I'm not familiar with how the code for that works; but I was thinking that if the deconstruction of the cart object was not 'clean' (in that it doesn't remove the associated deeditem) then who know's what else is left behind? even though the cart disappears from the game world, there could be dozens of 'phantom' cart items left in RAM like memory leaks interacting with code in unexpected ways.
Also, deeditems for carts and properties seem like similar objects. (if not the same base object/prototype)/ If one of the 'phantom' carts wound up occupying same area of memory that was supposed to be used by land deed: maybe it then would have unexpected properties or methods, which could cause a crash until the data for those properties was deleted?

That is just my stab-in-the-dark at trying to explain to myself what might be going on based upon my limited knowledge. I'm sure the experts will have better ideas, but I thought I'd share my theory, on the off chance it helps someone look somewhere they might not have otherwise thought of.

**Comment by MarjieAVolk** [comment]
I believe all of these issues with cart deeds are fixed in 5.5.  Thanks for all the details and ideas!
