### ISSUE TITLE
Feature: preventing Admin Abuse

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10308]
(Yes, i know - this is more suggestion, but i see too many crying posts about AA...)
1) All admin actions need to be stored in separate logfile. Commands, devtool using, etc. (It's help to server owners on servers with multiple administrators.)
2) "Show admin actions" server option. All admin actions stored in special chat channel, if enabled, this channel visible to everyone's. (if not enabled - channel visible to another admins\server owner).
3) Add a permission manager, for example by defining groups to which you can assign commands that are allowed to be executed by members of this group. Then make it possible to add players to those groups so they can only access the commands that they have been permitted to.

**Comment by D3nnis3n** [comment]
Need this for official servers anyway. I'm totally against point 2, though. That's ark survival bs.

Also we need the possibility to give different people different access to different commands. (Probably add this to your issue :))

**Comment by DragonSupremacy** [comment]
I agree with the added logging, as currently there's very little in terms of actual logging besides chat. However as D3nnis3n said, I don't see the point to #2. People should be able to work on a trust basis instead of punishing people for not showing admin actions for any number of reasons.

I can see #3 working out rather nicely with demographics, as currently I need to use a 3rd party mod to gain this sort of functionality. Much like how my server operates right now, it'd open the doors for the public to not have to assign multiple admins for administrative purposes, but to have a single admin/server owner who delegates part of his toolset to staff members in order to assist with the day-to-day happenings on a server, i.e. helping people who manage to get stuck, and so on.

**Comment by D3nnis3n** [comment]
As a transparency option you can include it. But i'd not want people to see if its enabled or loose points due to it. We do not activate this, because it's none of the players business which actions we do on our server. And we do have a very transparent one, but we announce things on discord to stop people from debating shit on the server.

**Comment by elfl0rd** [comment]
> As a transparency option you can include it. But i'd not want people to see if its enabled or loose points due to it.

Okay, agree.

**Comment by elfl0rd** [comment]
Hmm... Now need more settings :D 
![default](https://user-images.githubusercontent.com/4980243/51072934-897cf600-167a-11e9-95c5-8aeab4e87eb5.png)

**Comment by D3nnis3n** [comment]
Which merge request was this in?
Is there configuration for turning off?

**Comment by D3nnis3n** [comment]
Best option would be to be able to configure to whom its shown:

0 = log only, 1 = log and admins, 2 = everyone on the server

**Comment by elfl0rd** [comment]
don't know, i just saw it :D

**Comment by D3nnis3n** [comment]
Yeh, that one is even better.

**Comment by elfl0rd** [comment]
Addition, failed commands need to be stored in separate chat and logfile (main channel\logfile can be easilly spammed to hide real commands)
