### ISSUE TITLE
User don't see server

### ISSUE THREAD

**Issue by MrYoshii** [StrangeLoopGames/EcoIssues#10344]
ok sice yesterday all my users report that the server is offline.  Now only the server shows online if they downgrade to 0.7.8.5 then the server is online but shows its on version 0.7.8.6  and if they update to 0.7.8.6 they can join again. until server or client restart.

**Comment by pamduncan** [comment]
There was a problem with 7.8.6 where it was not saving the GUID whenever you restarted so your links that people had saved were no longer good or would connect after the server restarted.  This was posted for everyone in the discord announcements channel:  

mirasraelYesterday at 12:47 AM
Eco Server 0.8.6 was re-released both on Steam and SLG S3

No need to update client, it is just a server change. 
This release fixes problem with saving ID and Passport to Network.eco. It should be saved to preserve server identity, but for some reason it didn't. This identity used for Favorites, Recent, Continue.

#### For server admins
If you don't want to lose your server identity after update (before update it did change after each restart), you have to before server restart do following:
1. Add your server to favorites (it it isn't yet);
2. Open %APPDATA%\..\LocalLow\Strange Loop Games\Eco\favorites.eco
3. Find your server by Description:
i.e.
{"Description":"test server","UniqueIdentifier":4320634472491774956,"Id":"ea1112b5-78e6-5021-8dff-85433f120ace","Address":"5.149.219.38","GamePort":35047}

4. Copy and save "Id" value (ea1112b5-78e6-5021-8dff-85433f120ace in this example)
5. Now stop your server
6. Open Configs/Network.eco
7. Add "ID": "<saved server id>" option:
i.e.
{
  "PublicServer": true,
  "Password": "",
  "Description": "test server",
  "ID": "ea1112b5-78e6-5021-8dff-85433f120ace"
}
8. Start server, it will automatically generate Passport.

You only need to perform it once and only if you want to save old links. Otherwise this server will just generate new identifier.

Sorry for all inconveniences.(edited)

NEW MESSAGES
mirasraelYesterday at 9:59 PM
I know, you likes more re-releases of 0.7.8.6. Here you are!
Funny thing, yesterday with re-release of 0.7.8.6 we was surprised that it actually now writes server ID to Network.eco file, but... didn't read from it. It resulted in generating (and saving! all right!) new server ID every time. Now it seems fixed.

_____________________________

You can also just have everyone remove the link they have in favorites by anticking the server or they can delete the favorites and recent and continued files in the %appdata% and then search for your server again *after you updated so the GUID will work and save correctly in the link.  They can also connect by direct connect and the  make the link in current the new favorite and they will find your server and connect to it

**Comment by D3nnis3n** [comment]
Did this fix your problem?

**Comment by D3nnis3n** [comment]
No answer to Information request in 14 days, reopen if issue persists.
