### ISSUE TITLE
Master: clay and dirt particles - too shiny.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10354]
![default](https://user-images.githubusercontent.com/4980243/50176181-c5d56480-030f-11e9-89ea-6c829e9c8301.png)
![20181219202017_1](https://user-images.githubusercontent.com/4980243/50236494-9c7a0e80-03cb-11e9-913f-8493501aa53d.jpg)

**Comment by D3nnis3n** [comment]
@keegan-o Intended?

**Comment by keegan-o** [comment]
It's not intended for it to look like this... the main reason this looks bad is because realtime reflections is turned off in graphics settings. Will at least tone it down if I can't figure out how to make something smooth look better, because we should be able to have stuff this smooth without it looking like that...

**Comment by keegan-o** [comment]
Looks alright now with and without reflections I think.
