### ISSUE TITLE
(suggestion maybe) removing stump not provide resources.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10430]
New players miss removing stumps due "no resources gathered" since require lot of calorie to remove. I think adding some resources to stump (e.g. 1-2 log or maybe 10-20 Wood Pulp) will be good.

In addition, a new seedling appears after a while and aside, interaction between the destruction of the stump and the new seedling has arrived is absolutely not obvious.

**Comment by D3nnis3n** [comment]
I'm pretty sure we wanted to do that.

**Comment by Quadbro** [comment]
but there is cool, from ecological point of view, you must to choose: "hard and clean" vs "easy, but dirty". Such changes will transform eco more into just survival game).... Just my thoughts

**Comment by Quadbro** [comment]
Sorry guys, misunderstood you, yes, i agree with stumps and resources

**Comment by Deantwo** [comment]
Could make the stump turn into a seedling right after removing it to make it more clear.

I do however like the idea of it being a no-gain chore too, because it leads to people having to agree on laws about it if they wanna prevent it.

**Comment by Deantwo** [comment]
As for the tree stumps I am not sure. It does feel weird to get nothing at all from removing them, and players will keep complaining about that forever.
But this is mostly because the benefit from removing them isn't instantly apperant. When the tree stump is removed, new trees fan grow.
This creates some interesting debates about how in incentives people to remove them, which is part of what the game is about.

_Originally posted by @Deantwo in https://github.com/StrangeLoopGames/EcoIssues/issues/11242#issuecomment-462168364_

**Comment by elfl0rd** [comment]
I think stump is need rework.
After changes you got high quantity of saplings\tree seeds, and you don't really need remove stump to new trees.
Maybe something like "blocking radius" (in %number% radius nearby stump new trees cannot be planted\appears.)

**Comment by Deantwo** [comment]
It at least has to be clear to the player that removing the stump does something. Blocking when attempting to plant new trees could work. But don't tree stumps already count as being a tree in the plot and therefore cause negative health for growing trees?

But giving players 4-5 wood pulp wouldn't be too horrible, as long as it isn't actually too advantageous to do it.

**Comment by D3nnis3n** [comment]
Tree stumps now give wood pulp.
