### ISSUE TITLE
Master: road tool should only be craftable with basic engineering

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10502]
![default](https://user-images.githubusercontent.com/4980243/50668475-3c40ba80-0fd0-11e9-868a-3e43ae78ee20.png)

**Comment by elfl0rd** [comment]
@craig-jong nope
![default](https://user-images.githubusercontent.com/4980243/50829869-f2046400-1356-11e9-9216-5909e3b30fc3.png)

**Comment by johnkslg** [comment]
Not fixed according to GDragon

**Comment by craig-jong** [comment]
Basic engineering being required to fix the road tool isn't currently out of line with how things are for the other tools - it's actually exactly how the rest of the tools work. I fixed the road tool requiring the wrong material, so it IS repairable.

The actual bug is the fact that the tool doesn't require Basic Engineering to craft (currently requires hewing), but requires it to be repaired. Since dirt ramp also requires no skill to craft, if we move the road tool -> basic engineering, it would also make sense for dirt ramp to follow this change.

If we remove the repair requirement entirely, then we should also remove the repair restrictions for the rest of the tools.

**Comment by elfl0rd** [comment]
why? if you can craft - you can repair.
It's strange, i think crafting is harder then repairing.
