### ISSUE TITLE
0.5.3 [Nutrition, Realism] Being able to hold a metric ton of food in your stomach

### ISSUE THREAD

**Issue by AkibaNiashomi** [StrangeLoopGames/EcoIssues#1051]
Currently my stomach is holding:
- Tallow (x4)
- Hucleberries (x54)
- Charred Meat (x19)
- Wheat (x14)
- Charred Camas Bulb (x19)
- Wheat Porridge (x3)
- Campfire Roast (x7)

![nutrition bug](https://cloud.githubusercontent.com/assets/25452139/22458100/3d524cd6-e79b-11e6-920d-9eb3fb6c8c96.png)

I will not go through the process of calculating the mass of this enormous pile of food, but it stands to reason that having almost 10 kilogrammes worth of charred meat in your belly would make for a pretty bad stomach ache!

Suggestion:
Change calories to an over-time gain by having food in your stomach, and put a weight limit on stomach contents. This way calories will also be more realistic, and you will have to care about weight/calorie ratio as well as nutrition.

**Comment by yesod-github** [comment]
Perhaps also have the player vomit should reach over this stomach threshold.

**Comment by NafenX** [comment]
I feel like it's set this way so that the food you eat still gives bonuses for a whole day, you don't have to log in every few hours to make sure your stomach hasn't become empty and therefore your skill points per day gone to zero.

I would like to see a server-side 'Metabolism' setting which defines how long food stays in your stomach though. Then a server admin can decide how active he wants his players on the server, or just deter plays who log in only to eat a stomach full of food and then log out.
