### ISSUE TITLE
Duplicating content in bug report.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#10545]
Client generated bug reports have duplicate "Actual behavior:" into "Do you have mods installed? Does issue happen when no mods are installed?:"
![default](https://user-images.githubusercontent.com/4980243/50781581-c893fb80-12b6-11e9-8567-676b1ce9e7aa.png)
![default](https://user-images.githubusercontent.com/4980243/50781598-d5b0ea80-12b6-11e9-87a3-6905c26e344a.png)

e.g. happens on 

> Connection Failed

https://github.com/StrangeLoopGames/EcoIssues/issues/10497

Looks partially refer to https://github.com/StrangeLoopGames/EcoIssues/issues/10012

And maybe question about mods need to be added into client bugreport interface?

**Comment by Deantwo** [comment]
Maybe just add a checkbox for "Do you have mods installed"?

**Comment by redwyre** [comment]
If they report the bug through the game, should we be able to get the actual mod list?

**Comment by Deantwo** [comment]
Auto-filling out a list of mods would be wonderful indeed. However in most cases it is only interesting to know rather or not there are any mods at all, and if so does the bug still exists without the mods. Since bugs caused by mods is not something we want to worry about here.

Auto-filling a mod list likely isn't that easy though, since it require the client to know the names of all installed server mods, and those names need to be forwarded to the client either as part of the error message or before the error occur.

But auto detecting the presence of mods and then just saying there were mods would be useful.
