### ISSUE TITLE
Alpha for plants not being set by growth curve correctly

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10599]
![image](https://user-images.githubusercontent.com/3536496/50922328-1ca9f780-13ff-11e9-815b-4ad7fdaef334.png)

**Comment by keegan-o** [comment]
This has been frustrating me for some time and I just confirmed that the alpha growth does not work as it should. The material for the plant's cutoff value (which is supposed to be over-ridden by the growth curve completely) affects the plant alpha in Unity editor, and in-game:

With nothing in the alpha growth changed, only changing the material's 'Alpha cutoff' value:
Set to 0:

![image](https://user-images.githubusercontent.com/14983165/50993811-66621300-14cf-11e9-8c99-7ce80373767b.png)

Set to 1:
![image](https://user-images.githubusercontent.com/14983165/50993879-8c87b300-14cf-11e9-8172-cd9b629d2a72.png)

**Comment by keegan-o** [comment]
It's not a matter of always setting the plant cutoff value to some reasonable thing either, because here is a 100% maturity switchgrass with the cutoff set to the reasonable default of 0.5, and still the top of the texture is not visible:

![image](https://user-images.githubusercontent.com/14983165/50994077-22bbd900-14d0-11e9-9fb6-5699503dcdc5.png)

**Comment by keegan-o** [comment]
That texture (in the polluted to) is set to this, with the grey at 70/70/70, 
![image](https://user-images.githubusercontent.com/14983165/50994204-80e8bc00-14d0-11e9-80c4-ae7d6124bc7e.png)
And the alpha growth curve for the last third of growth goes up all the way to above .9
