### ISSUE TITLE
Tree debris is not targetable

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#10707]
![image](https://user-images.githubusercontent.com/3536496/51291752-126a9900-19bd-11e9-9ae9-6a53e74ba5f3.png)

**Comment by elfl0rd** [comment]
not at all... but happens :(
![default](https://user-images.githubusercontent.com/4980243/51317589-06d4ac00-1a69-11e9-8703-0d0867f11cb4.png)
![default](https://user-images.githubusercontent.com/4980243/51317599-118f4100-1a69-11e9-9c21-c3035922b849.png)
More happens if debris on <= ground lvl from stump

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/51352163-a857ff80-1a61-11e9-8dfe-c24366210d9f.png)
Sized up coliders on all tree debris to be like Palm, should be fine now hopefully.

**Comment by elfl0rd** [comment]
Not fixed, maybe different issue.
happens after restart too.
https://youtu.be/RpdIN01uj-A

**Comment by keegan-o** [comment]
Eric mentioned that this was a code problem, un-assigning myself.
