### ISSUE TITLE
Bloomery has House Benefits that offer no benefits

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#10793]
![image](https://user-images.githubusercontent.com/431728/51471240-e3d82e00-1dc1-11e9-963b-737a582c75dc.png)

**Comment by elfl0rd** [comment]
"industrial", intenden as i know :)

**Comment by elfl0rd** [comment]
Ofc, this to change room type onty "industrial" to remove all skillpoints gain from it.

But i agree, this description is not clear.

**Comment by redwyre** [comment]
I'm not sure what you're saying, but this is from the recipe, not an existing object in a room - so it will always give you 0 skill no matter what room type you put it in.

**Comment by elfl0rd** [comment]
make any room, (kitchen, bedroom, general, etc...) and place bloomery too.
now this room counts as industrial and not provide SP.

**Comment by craig-jong** [comment]
As far as I know, this is intended. Industrial rooms always give zero and override non-industrial rooms. I *could* remove it from the bloomery since the bloomery is generally placed outside anyway, but this keeps it more consistent with the other industrial objects.

If the tooltip is confusing, that might be a different issue.
