### ISSUE TITLE
Long term re-factor of block meshes to prevent sparkles between meshes. 

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#10804]
Noticed more sparkles in the daytime and megasparkles at night recently
![megasparkles](https://user-images.githubusercontent.com/774628/51505997-c2b21600-1d9e-11e9-8217-03bf00a9e1bc.gif)

**Comment by metachronism** [comment]
they are no longer mega but @keegan-o has to adjust meshes to get rid of them for real

**Comment by keegan-o** [comment]
Switching this to semi-high priority and removing from 8.1, because this is a sort of long-running refactor as far as the meshes go-- I will find time to work on this as we go but it involves refactoring art for somewhere between hundreds and thousands of meshes. Some sets will be refactored but others are due for replacement, so it'd be a waste of time to go through all of them at once right now. The other thing is of course I will be more rigorous with any new block meshes as we go to avoid this.
