### ISSUE TITLE
World gets progressively worse lag over the course of several hours until server restart.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#10931]

**Comment by mirasrael** [comment]
Seems streamers issue was already fixed by Eric. 
I tested with my actors framework and started test server with 50 diggers (once in 2 seconds they dig and put back dirt).
When I tried on old version (without his laws optimization) I wasn't able to login
with hanging on "Entering World" message. I checked threads and most of them was busy with rendering law's DisplayString.
Then I updated version (to version with optimizations) and was able to login without problems. 
But now I still eventually see disconnect sign. Continue investigation...
But it works with 50 players!!!

**Comment by mirasrael** [comment]
Should be fixed in https://github.com/StrangeLoopGames/Eco/pull/3905

**Comment by metachronism** [comment]
there are probably other issues, but the main one was figured out
