### ISSUE TITLE
Pumps don't work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11033]
Tried /spawnsewage several times, did pick up and replace the pumps, the generator and the pipes - no output, therefore no crafting and no sewage.

![pump](https://user-images.githubusercontent.com/25908592/52163435-35e25300-26e2-11e9-9fd8-48b50b296cad.png)

**Comment by Sekor2600** [comment]
Hi did test /spawnsewage and the pump only pump Water when you have a crafting in the Liquidcrafter. 
![grafik](https://user-images.githubusercontent.com/37456949/52168979-846b0e00-2731-11e9-8680-726b120bdac5.png)

When you cut the Pipe between the Table and the Pump, the water runs without problems and pumps have output.
![grafik](https://user-images.githubusercontent.com/37456949/52168958-51c11580-2731-11e9-8417-8ad01537d56e.png)

But when you block the Pipe the Pump has no Output. I think the outcome is blocked because of the table.
