### ISSUE TITLE
8.0.0 Linux Server takes 2-3 hours to start up on 6km world.

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#11145]
On version 8.0.0 the server is taking a very long time to start up.

It takes 43 mins just to reach the 'ticking' stage, then a further 1-2 hours to complete ticking on each start up.

For comparison on v0.7.2.5 (old version I know) with a 9km world it took 10 mins to start up on the same dedibox.

**Comment by pamduncan** [comment]
Linux serverfs always have taken a long time rtp build worlds and that is why anything over 140X140 was recommenced to be done on a windows box and then moved over until that did not work any longer.  That is a very large world and right now even windows is not handing a 300X300 worlds and we are having people rebuild to a max of 200X200 as llinux is using same files I suspect it is same bug  I recommend for now sticking with 200X200 s=especially since anything over 4KM2 is really a waste

**Comment by mirasrael** [comment]
Linux servers are not officially supported.

**Comment by mirasrael** [comment]
@Yorkforce can you attach your save file if this issue is still actual for you?

**Comment by D3nnis3n** [comment]
Closing this issue as no response was given.
