### ISSUE TITLE
Chopping stumps doesnt give you XP

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11148]

**Comment by elfl0rd** [comment]
:D https://github.com/StrangeLoopGames/EcoIssues/issues/10430

**Comment by Deantwo** [comment]
I am not sure tree stumps should give XP or resources. It does feel weird to get nothing at all from removing them, and players will keep complaining about that forever.
But this is mostly because the benefit from removing them isn't instantly apperant. When the tree stump is removed, new trees can grow.
This creates some interesting debates about how in incentives people to remove them, which is part of what the game is about.

_Originally posted by @Deantwo in https://github.com/StrangeLoopGames/EcoIssues/issues/11242#issuecomment-462168364_

**Comment by craig-jong** [comment]
Stumps now give minor amounts of pulp configurable through the organisms files. I'm not going to have them give experience for now and we'll look into changing how tree seed density affects gameplay.
