### ISSUE TITLE
Unlimited Buy order Bug

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11140]
When you sell an amount of items to a player and he is not having enough room OR has set a limit for his buyings that is higher than available space for this amount you'll get the amount of money for the amount you wanted to sell while you only have transferred him the amount he could still take.

Example:
Selling 40 Logs. Player has room for 20. A log costs a dollar.
You sell the player 40 logs, he gets only 20 but you get 40 dollar.

Chat also confirms the sale of the 40 logs.

**Comment by pattimayo** [comment]
you can buy more than you have room for and be charged without receiving.

example: I attempt to buy 30 hewn logs, forget to link cart inventory, i only get 15 that i can carry, i am still charged for 30.

**Comment by iForby** [comment]
This also happens when a player fails to link their vehicle inventory to the store, when attempting to purchase more than the max-carry of the item:
IE: Buying 40 mortared stone will only give the player a max of 15, but charge them for the whole 40. Only work around is linking vehicle inventory.

I had players from my server provide screenshots.
I understand it's fixed, but sharing screenshot just in case.
![download](https://user-images.githubusercontent.com/47337255/52539756-bc84d900-2d4f-11e9-9df5-a9e0d8ed14f4.jpg)

**Comment by mirasrael** [comment]
Was fixed in 8.0.1
