### ISSUE TITLE
Pickaxe icon is shown when choosing logging specialty talent.

### ISSUE THREAD

**Issue by seccombew** [StrangeLoopGames/EcoIssues#11149]
![image](https://user-images.githubusercontent.com/12839021/52438640-9d2b4900-2ace-11e9-85ca-1aae6eaf1039.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/53202861-70058d00-35dc-11e9-99df-3f748f758283.png)
Right now the pickaxe is just what is used to denote 'tool'

**Comment by keegan-o** [comment]
So this would require a few new icons to fix-- I do think that's the best option though, given that I don't think we want the pickax to be a prominent symbol in our game. Lowering priority though because it's creating content, not fixing a bug.

**Comment by keegan-o** [comment]
@RobertMangano See if you can come up with an icon for those talent groups that represents tools generically rather than one specific tool-- could be a silhouette of a couple tools together. Replace the two icons in the top row of UI_Icons_01 sheet that you see used in my comment above, no Unity work needed.

**Comment by RobertMangano** [comment]
added icons and checked in
