### ISSUE TITLE
World Generation Error & Random Disconnects 

### ISSUE THREAD

**Issue by Nmnx** [StrangeLoopGames/EcoIssues#11165]
Hi,

Im running a Server since a Month and im not sure whats going on with the New Server Version. 

#### 1. Random Disconnects

We have around 15-30 players at once online on a new generated Vanilla 6km² World since Patch release and we encounter some random Disconnects throughout the day in. Im not sure if its the Serverhardware which is causing this (Too Low Performance) or if its a bug in the new version. It happens like 2-5 Times an hour and kicks out most of our players at once. Some people wont get disconnected but i dont know why. Its like 1-5 Players who stay online and 15-20 who are getting disconnected. I was watching the Serverload but it was always around 50% CPU without any Peaks and enough Ram left. After a restart we had around 30% CPU Load with ~20 Players online. It happens with around 10 Players online too and didnt happend with Our first 2 Worlds on Version 7.8
We are Hosting on a 6 Core Windows V Server with 16GB Ram 

#### 2. World Generation Error

After Upgrading to the 8.0.0 release Version on the Bleeding Edge Channel  i started to get an Error Message  while Generating Worlds from 0.5m² - 6m²  just 1 second before the Server UI would Pop-Up:

`Error 606: Unknown Error Code
   bei Open.Nat.SoapClient.GetXmlDocument(String response)
   bei Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Open.Nat.StreamExtensions.<TimeoutAfter>d__7'1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Open.Nat.UpnpNatDevice.<CreatePortMapAsync>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Eco.Plugins.Networking.UPnPMapper.<CreateAsync>d__3.MoveNext()`

 It first prevented me from Starting the Server and saving World while on Bleeding Edge Release Version but after Downloading the "Official Release" it was starting and i was able to save the world. When i start this world it keeps showing the Error Message again. I tested it on my Server and local and both are showing the same Error Message. A friend of mine generated the World simultaniously with me which is now our active World and got another Error Message i think it was Error Code 403 after generation finished and right before the ServerUi showed up but the World is running fine now without showing any errors on Startup again. The Unknown Error code still appears on both my local machine and my server while creating worlds

#### 3. Some Questions

I would like to ask some Questions about the Eco Server because i cant find much ressources yet and would be very happy if you could Answer some of them:

- Which Server Settings Can Tweak the Server for better Perfomance or how to tweak a server for high population (e.G. does the Client refresh Rate affect performance and if yes how much?)

- How much does World size impact on Performance ( like 2km² Compared to 6km² or 9km²)

- I would like to use some Graphics included in the Art Pack for my Eco Community Website - Is it allowed to use them or can i may ask for permission to use those Graphics? They would fit perfectly :)

- Which Server Settings would you recommend for a high population Server with like 50+ simultaniously Online at Peaks?

Thanks for making this great Game and if you need some more information regarding the Bugs feel free to ask but i think i got all informations there :)

**Comment by pamduncan** [comment]
Have you made sure that you have the most current worldgenerator.eco?  The one that is downloaded in the game is, like most of the configs in that folder outdated and its expected that everyone knows to go into the server UI and use and save it and get the most current version.  many of those issues i have seen with people installing the game and not updating the config files and letting and old worldgenerator build the world.  You should really update all configs as many changed this time and things moved around like spawnlocation and useexactspawnlocation moved from Users,eco to Worldgenerator.eco.  If you did not have a new worldgenerator and have the coords posted there it uses the default of 0,0,0 which seems to have something to do with the disconnect isse,  0,0,0 is a troublesome coord for placement or logging in and we notices that as people logged in on 0,0,0 and placed tents down the move objects that ended up there the more problems with people logging in even if they had been on before and move elsewhere.  We do know from past versions that if you placed something on 0,0,0 or near it like a truck or a stockpile;e etc your would then have issues logging in wherever you were.  The servers that set the spawn location to other coordinates and went and cleared off everything at 0,0,0 have stopped having as many issues .  These servers had no problem at first with few people on and not much in that area but after a day then even people that had been able to log on with issue were having problems.  Some found that they did not even have the config that had the setting of spawn location in it and had to get an updated one to help with the issue and get people logging on other then at 0,0,0.  I think the devs need to make the default something other that 0,0,0 so that those that do not set it are not logging in that spot as that is the worst place on the map to log in or even stand around :)

I don't know if this is the total reason for the disconnecting at 90% when logging in but we have managed to take many servers from everyone have that problem to curing it for about 70% of the people.

Also make sure you have UPnPenabled (in network,eco) set correctly,  If behind a NAT you want that enabled but if not (usually the case of a server host with in a datacentuyre) you want that disabled,  that has helped with many disconnection issues tht have no other cause and the server also throwing a non crashing exception with a sockets issue cause the server cannot find a UPnP device (which is true if your hosted or in a  data center or if your router does not have UPnP at all or has it disabled.  If you have that enabled, or have not see the updated Network.eco then its enabled by default so you need to determine the status of UPnP for your server.

**Comment by kuse-de** [comment]
Yes, i downloaded the Server multiple Times with Steam and from your Website and every Clean Installation throws the Same Errors. Setting UPnP to disabled didnt resolve any issues with disconnects  but good to know that its better to disable it. 

Our Players are also reporting Vanishing Wooden Carts but i think there is already a case open for that.
A Server restart brings them back.

I attached a Screenshot with disconnecting Players - We had like 20 Players online at this time and some got kicked and some not, the Server isnt completly restarting or something its just kicking out most of the players in random time periods 

![20190208131548_1](https://user-images.githubusercontent.com/1517214/52498963-91c54400-2bda-11e9-8172-b7ce20308d58.jpg)

**Comment by D3nnis3n** [comment]
The disconnect issue often happens on overloaded servers and we have other reports open for that. Please note that you use a map size way over maximum recommended size of 4km2 in a Version still having performance issues ans with higher system requirements. Having 50 players in that is likely going to fail.

The upnp error is nothing you need to care about, it tries to open ports with the new Feature but fails, were still working on that.

As there is no real bug left, i'm closing this issue.

As for your questions:
1. There really is nothing you could do to easily optimise, make sure to use realistic world sizes and fitting Hardware for your Player Count. A 8700k is needed for around 35 players.

2. Higher world size dramatically increases RAM and moderately CPU usage.

3. Not sure in that, send me an email to dennis@strangeloopgames.com

4. Not quite sure what you mean with that?

**Comment by kuse-de** [comment]
Hi,

thanks for your response, i was able to resolve the issue with dc's today by upgrading the server hardware and i will use a smaller world next time - 4km² should be by far enough anyway.
 
4. I mean if there are some settings that you can change to decrase ram and cpu load for worlds with 50 or more players online at the same time but i think using the recommended world size next time and the new server hardware should deal good with increasing playernumbers.

**Comment by D3nnis3n** [comment]
No, there are no such settings.

**Comment by kuse-de** [comment]
Okay thanks :)
