### ISSUE TITLE
Specialization LVL-UP messages overlap animals while hunting.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11186]
Maybe you got more XP from kill but 0 from hit?
![20190208123946_1](https://user-images.githubusercontent.com/4980243/52493998-e1593f00-2bdd-11e9-9e9b-3b5d72c38fd4.jpg)

**Comment by eliotcougar** [comment]
Not sure what the issue is, but in general it's annoying when the popup appears when you do something with crafting or inventory, because the popup covers the screen in a way that it steals focus, cannot be click-through or dismissed... So, you have to wait until the animation plays before you can continue whatever you've been doing... It's intrusive...

**Comment by elfl0rd** [comment]
why you close? This is still as issue...
With @eliotcougar case - it can be fixed if eco show lvlup message after player close all windows.
With my case - you can change hunting XP.

Also you can move LVLUP messages from center of screen and from top layer.

**Comment by johnkslg** [comment]
Perhaps we move it?

**Comment by johnkslg** [comment]
Just move it up slightly

**Comment by eliotcougar** [comment]
> Just move it up slightly

Yes, above the targeting cursor, and below the UI, so that it doesn't interfere with actions one might perform when it appears...
