### ISSUE TITLE
Ping not work for LAN servers with "remote addr" specified.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11218]
(without configuring "reverse NAT")
![unknown](https://user-images.githubusercontent.com/4980243/52519405-f4b2eb80-2c6b-11e9-995f-cfc7858d28ca.png)

**Comment by pamduncan** [comment]
This would be an issue for  a LAN server that was only created as a LAN and no ports were forwarded.  Even if the remoteAddresss is set if there are not open ports and the firewalls do not allow communication through its very possible that they cannot get a ping.  We have had several people come to support having this issue but they were only playing with a LAN group  and had not need for a internet connection as no one was coming in via the Internet.  Once the firewall permissions were set and EnableUpNP was set they were able to see a ping.  In a few cases port 2999 need firewall access (still not sure if that port is still used consistently for master) and in some cases the ports did need to be open for a ping to work,  I was told that the oping is server to master so that would assume dome port or network mapping was in place foe a ping to read anything

**Comment by metachronism** [comment]
@mirasrael ping in general doesnt seem to work at all for LAN servers, and also the time it takes for a server to show up under the LAN listing is very very long, they should always be basically instant
