### ISSUE TITLE
Breaking "middle debris" and chop "tree trunk" - is not provide XP for speciality.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11242]

**Comment by Deantwo** [comment]
I agree that chopping up a tree trunk should provide some XP.

As for the tree stumps I am not sure. It does feel weird to get nothing at all from removing them, and players will keep complaining about that forever.
But this is mostly because the benefit from removing them isn't instantly appearant. When the tree stump is removed, new trees fan grow.
This creates some interesting debates about how in incentives people to remove them, which is part of what the game is about.

**Comment by elfl0rd** [comment]
About stump - https://github.com/StrangeLoopGames/EcoIssues/issues/10430
(maybe really low XP + resources?)
