### ISSUE TITLE
EXPLOIT: duplicate carriable items using stockpile

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11244]
as i see, it's "by design"
In any case, if you can bupass stockpile\prevent stockpile from load - you can interact with items in stockpile like items in open world.
e.g. you can grab items from.
(stockpile not loaded)
![20190210152937_1](https://user-images.githubusercontent.com/4980243/52539351-4489d380-2d8e-11e9-852c-008fa27c6ea5.jpg)
(after load)
![20190210153243_1](https://user-images.githubusercontent.com/4980243/52539363-57040d00-2d8e-11e9-983e-9d250cbbcfae.jpg)
Then move something inside stockpile - viola,
you get items and in stockpile items not disappears.

**Comment by Spydarlee** [comment]
Just copying over some notes on https://github.com/StrangeLoopGames/EcoIssues/issues/10294

Maybe we should dynamically resize the stockpile collider to ensure it always fits everything in? That would also help with the linked issue because the popup would appear relative to the highest block in the stockpile, rather than at an arbitrarily high point like it does now!

**Comment by elfl0rd** [comment]
It's not help if stockpile not loaded...

**Comment by Spydarlee** [comment]
Oh yeah, I see. What causes a stockpile to not load? Is that just another bug, or a timing issue or something?

**Comment by elfl0rd** [comment]
e.g. fast driving (you can reach stockpile instead of worldobjects loaded)
periodically happens with 0 crossing, periodically happens with "strange" iteraction ways - skidsteer (https://github.com/StrangeLoopGames/EcoIssues/issues/8130), touch block trouch angle (https://github.com/StrangeLoopGames/EcoIssues/issues/10953) etc...

**Comment by mirasrael** [comment]
@Quadbro you fix doesn't fixes this issue. It happens when stockpile loaded after blocks.
