### ISSUE TITLE
Direct Transfer tax is broken

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11271]
The amount of tax does show in the transfer UI, but is the not deducted and the chat shows "0 tax".

**Comment by Quadbro** [comment]
that only can happen when you transferring to treasury

**Comment by D3nnis3n** [comment]
Happens on Transfer between main account and additional created account. Treasury bot involved.

**Comment by JamesTalon** [comment]
Can confirm, will happen when transferring to another account. If you click Transfer before clicking anywhere else after filling out the amount field, it will send the money tax-free (First image). Clicking elsewhere updates the taxes as expected otherwise (Second image).
![image](https://user-images.githubusercontent.com/38748529/52922062-d85a2300-32eb-11e9-97e2-83c970807ecb.png)
![image](https://user-images.githubusercontent.com/38748529/52922066-df813100-32eb-11e9-811c-41d398f7df2e.png)
