### ISSUE TITLE
Various world objects pipe ports not functional! (Steam Engine, Cement Kiln, Froth Flotation Cell)

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11385]
(this is strange, at this stage water pump available.)

**Comment by keegan-o** [comment]
Time to fix this! It has the port ready and everything. Steam Engine should need water hooked up to operate.

**Comment by keegan-o** [comment]
Cement Kiln also needs a water supply with no sewage output. 
![image](https://user-images.githubusercontent.com/14983165/70952093-1f06cf80-201a-11ea-9636-a78f111c4540.png)

**Comment by keegan-o** [comment]
Froth floatation cell should have water input, sewage output, and wet tailings output.

**Comment by Sekor2600** [comment]
Advanced masorytable only water for cooling

**Comment by elfl0rd** [comment]
Look for "Solar panels" technically it is solar tower - it needs water for function.
But output clear water too.

**Comment by elfl0rd** [comment]
Please remove water input from cement kiln, in real life, in any case - kiln feeds dried raw materials.
water used in mixing or\and crushing stages.

**Comment by keegan-o** [comment]
Some of these are fixed, some are not. Cement kiln having water I am fine with until we represent the need for water in cement production elsewhere in Eco. (It is also sometimes used in clinker cooling I think, even if not directly in the kiln. You can bet anywhere running a cement kiln *needs* water supply in case of an overheating or other accident, too. This issue is too old and convoluted, we'll make new ones for needed updates to ports. Steam Engine and Froth Floatation are covered by other issues.
