### ISSUE TITLE
Compost fertilizer - too OP

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#11380]
recipe is too easy (even at the 1 level)
fertilizer is too OP
as result... my farmer hate it.
![default](https://user-images.githubusercontent.com/4980243/52918199-92aa5400-3305-11e9-85a9-40d95c880e8e.png)

**Comment by pamduncan** [comment]
I think even if the fertilizer was made more difficult it would still be too OP since so many massive amounts of it are created and instantly...at water and waste and immediate have compost.  Anyone out there that makes compost knows that decent compost can take months and months to have good compost that has any really usable value and is not just icky waste products.  Maybe instead of instantaneously producing compost there would be an  period while the muck became compost and could be moved for processing.  Then you have to consider what you want to do with the compost.  Many people do find that simple compost in a flower garden is just fine but depending on what you need the compost for and what the land needs that the compost is to replace you would have certain recipes to work out .. different composting and different methods would produce different compos=ts many of which are often combined to make what you want for composting.  You could really end up on a deep dive when it comes to composting and natural organic growth media (skipping fertilizers at that is a whole other story and while organic may not be anything but all chemical).  Suffice to say that what you put into be compost for spring is usually put up as early as the summer before or longer and not something quickly made or producing more then the some total of the parts that go into it.  Maybe I am doing something wrong but I am getting way more compose out then what is going in and true compost would be less than what is going in at least mass wise as a good portion is broken down.  In real life I can put up 100 pounds of cuttings and leaf for dry compost and by the time int ready I have less than 20 pounds.  that is not quite what is happening in my in game Eco compost production.  I seem to be putting in very little and getting a WHOLE lot

**Comment by WeaselDog** [comment]
Part of the issue is a Blast Furnace smelting ore would produce toxic tailing waste that is not usable for compost, nor should it go into a traditional sewage system. A sewage system for other types of water would probably end up producing less.
