### ISSUE TITLE
Revisit CO2

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11397]
Plant density in 8.0 has changed a lot, making CO2 a much less a danger.

Example for a 4km² world:

PPM Reduction by plants until 8.0: - 60
PPM Reduction by plants as of 8.0: - 450

**Comment by WeaselDog** [comment]
The issues with CO2 are 100% related to trees. The reason this issue started in 8.0 was Ceiba trees.

The average tree is equal to 200 Shrubs/400 Grass.
Oak/Ceiba/Redwood are equal to 400 Shrubs/800 Grass.

These two bugs are the main cause of CO2 issue:
https://github.com/StrangeLoopGames/EcoIssues/issues/5930
https://github.com/StrangeLoopGames/EcoIssues/issues/12975


Cutting Oak trees significantly increases CO2 absorption from plants because they multiple when you cut them.
Giant Ceiba farms are huge CO2 sinks, plus they spread naturally more than they should.
It is why the issue started in 8.0 and worsened when plants were moved into AutoGen folder.

You can test it if you remove the CO2 absorption from Oak & Ceiba.

**Comment by mirasrael** [comment]
CO2 reduction from trees decreased roughly in 25 times.

**Comment by mirasrael** [comment]
Previously it incorrectly multiplied number of trees in area on the area size for CO2 consumption calculation (and the area was 25m2). Now it correctly calculates CO2 reduction just per tree.
