### ISSUE TITLE
If the skill window reaches the right edge, tooltips overlap the professions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#11395]
![image](https://user-images.githubusercontent.com/3536496/52961674-80fa9800-3369-11e9-81e7-22e664a53a9f.png)
It should appear within the skills window in that case.

**Comment by Spydarlee** [comment]
Just had a quick look at/think about this and I think it would be a much bigger task to do this vs. fixing the original overlap issues because:

- The tooltip UI only knows about the element its displaying info for, not neighbouring elements (i.e. other skills in this list) so doesn't try to avoid obscuring anything else. 
- For this particular UI the entire big blue button can be hovered over to trigger the tooltip, not just the text. So the tooltip doesn't know to only avoid the text, and it tries to avoid being inside the blue button too.
- So this might require a bespoke solution for this particular UI and/or a more complex set of rules for determining position (respecting only certain parts of the UI, e.g. text, plus neighbours, etc.)

Would you mind chucking a priority on this one @johnkslg and I'll revisit later on as appropriate?

**Comment by johnkslg** [comment]
I actually coded this before, so that the tooltip would appear on the inside-edge of dialogs:
https://github.com/StrangeLoopGames/Eco/pull/3853/files
Some subsequent change affected this. Can you see what happened and restore that behavior? 
There's generally lots of empty space on the right side of the dialog, so its better to display it on the inner-edge when that is the case.

**Comment by johnkslg** [comment]
Keeping this one with Karn since hes done work on it already
