### ISSUE TITLE
Game crashes while gaming 0.8.0.3

### ISSUE THREAD

**Issue by Yclee0206** [StrangeLoopGames/EcoIssues#11441]
I am only able to play for about 5 minutes or so until the game crashes, and sometimes have to physically shut down the laptop because the laptop does not respond at all (black screen). During the 5 minutes of play time I get, I am only able to move very slowly.

After doing #11125 Mirasrael workaround, it didn't crash for a longer time, but whether that was the reason for the longer playtime, I do not know.

Windows 10 Home
Intel Core i3-5005U
Intel(R) HD Graphics 5500
4.00 GB RAM

[output_log.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2888886/output_log.txt)

**Comment by Yclee0206** [comment]
Did the memory test as recommended here #11346 , and nothing was bad. And seems different from his issue, as I am always able to play in game limitedly for several minutes, until either the program crashes, or sometimes the laptop too.

Changing graphic configuration (10% render for example) does not help either. Also, the animals seem to move very slow, similar to my speed too.

**Comment by Yclee0206** [comment]
I know my hardware isn't good, but I don't think it should be crashing. I verified that I had at least 200 MB of RAM left when the game crashed.

**Comment by Yclee0206** [comment]
Additional info: after updating to 0.8.4, i can't get enter the game at all. It always crashes while entering world. Different error message:

igdusc64.dll caused an Access Violation (0xc0000005)
  in module igdusc64.dll at 0033:c401d300.

**Comment by pamduncan** [comment]
I have been seeing this issue on 8.0 + versions with Intel graphics although they are usually right on the borderline of meeting minimal requirements.  We stumbled over this in the cases of systems that had Intel Graphics chips sets on the motherboard (aka onboard graphics) as well as also having a NVida or AMD GPU and assumed since theri GPU more then met the requirements that they should not be getting the graphics errors they were both seeing visually, FPS issues they were experiencing where FPS would jump to 80-100% and cause crashes and also both Eco and WIndows error logs pointing to graphics errors.  

Running DxDiag we found in quite a few that the onboard Intel Graphics were the default graphics and it appeared that maybe Eco was using the default graphics instead of looking for a specific GPU.  In these cases simply setting the GPU that they wanted used as the default for the computer solved there issue and some issues on other games.

Intel Graphics can also be confusing as we are very used to say a 560 being a lesser card then a 760 or a 960 so when we see the minimum Intel HD Graphics set to 500 and the chipset listed on the motherboard as a HD 7000  It is not always that the higher number chip set is the better one for what you are trying to use it for so you really need to do a bit of an investigation and comparison between the  graphics recommend to st lt best for what you need the graphics to do.   It's not weird to find a Intel Chip Set with a lower number installed on a system that is supposedly a 'gamer's rig' and a chip set with a higher number on a system for business and scientific usage and calculation that really has no 3D graphics needs so its always worth  checking out what Intel says a chip set is best used for.

**Comment by redwyre** [comment]
This is graphics driver issue, please make sure you are using the latest driver: https://github.com/StrangeLoopGames/EcoIssues/wiki/Update-video-drivers#intel

**Comment by redwyre** [comment]
Actually, looking at the log you're running out of memory, and because you're using integrated graphics your memory is shared between the CPU and the GPU.

Unfortunately, it looks like you aren't going to be able to play Eco 0.8.0.x, but we are working on performance for 0.8.1. But you would have a much better chance if you can upgrade to 8GB of RAM.

**Comment by redwyre** [comment]
We have release Eco 0.8.1.0 which has a number of performance improvements, give it a go and let me know if it's better.

**Comment by Yclee0206** [comment]
Thank you for the performance update! The issue has thankfully been fixed since update 8.0.6.
