### ISSUE TITLE
Pitch should be mortar

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11479]

**Comment by elfl0rd** [comment]
Also some more information "why pitch is mortar". We are using pitch in recipes requires mortar (bricks, roads, _mortared_ stones...), but not "real" pitches. In this behavior, naming mortar as pitch - really confusing players.

Especially since we do not yet have ships that may require pitch. And maybe later there will be a new recipe with a new item.

As I understand it, this change requires a full replacement of the original ingredient (internal resource name) rather than a simple rename while retaining pitchitem.

**Comment by Conchipedia** [comment]
If this is just a rename then put this information into the the description (as i would think most **old** player would appreciate this help and it wouldn't confuse new players)
Example: **Mortar (prevoiusly know as pitch)**

**Comment by craig-jong** [comment]
this is not a localization issue (at least not on the surface, but I understand its annoying to translate).

It's called pitch as a legacy thing and it can be changed, but it's a little bit more annoying than just string change. Shouldn't be too hard, though.

**Comment by WeaselDog** [comment]
Mortar is now the item and Pitch is the tag
