### ISSUE TITLE
[0.8.0.4] Converting world to new format...

### ISSUE THREAD

**Issue by Litonius** [StrangeLoopGames/EcoIssues#11498]
-Have a world that was made in 8.0.3
-Load it up in 8.0.4 and get the "converting world" message
-Have it finish and get a connection error
-logs state "[23:21:10.610] [1] [ Info] [Eco] Caught exception when trying to dump a prior exception: Exception of type 'System.OutOfMemoryException' was thrown."
-loops back to main menu and never loads the world

**Comment by Litonius** [comment]
So this "bug" is due to the conversion process using EcoServer32.exe by default, and if you have this issue the workaround is to check the "Configs" folder and ensure "Storage.eco" has the proper name of your world, then launch EcoServer.exe as admin and let it convert your world; then you can close it and relaunch the game and load your world as per normal. I'll leave this tracker here in case it has use, but you can close it/etc as needed.

**Comment by redwyre** [comment]
I've put the work around instructions in https://github.com/StrangeLoopGames/EcoIssues/wiki/Work-around:-Converting-world-to-new-format-crashing-in-0.8.0.4

**Comment by redwyre** [comment]
@Litonius Would you be able to upload a copy of your world from your backups before the update?

**Comment by metachronism** [comment]
Issue is world conversion uses too much memory.  Should be easy to just adjust this, also @mirasrael recent change to serializer might have already made this possible

**Comment by johnkslg** [comment]
Extra notes:
This got disabled for today's hotfix, but we need to revive it for the next fix as it give 40% mem savings.

Since migration is the problem, we can skip it for this case and force load the 64 bit version. So when starting a server:

If the world is from a prior version, always load 64 bit
If the world is from current version or later, dynamically choose 32 or 64 bit based on the save
If the world is brand new, start 32 bit if the size can handle it (and since theres no size option in the client-started worlds, always do 32 bit there)

**Comment by mirasrael** [comment]
Already fixed in 8.2
