### ISSUE TITLE
Failed to load server - newest version

### ISSUE THREAD

**Issue by JAGGANOT** [StrangeLoopGames/EcoIssues#11536]
Hi after the last Safe of the World the server crashd and is not longer startable          log/dump

[dump.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2919905/dump.txt)

savegame 
https://1drv.ms/u/s!AiWVzbLtAg3X5gYZODOsMQhSlYeG

**Comment by Deantwo** [comment]
Why can we even remove demographics?

**Comment by pamduncan** [comment]
Did you add any laws in 8.0.4  either before the update and maybe even before a reboot was done on that version before the update was added?  If so have you tried going back to the last backup in 8.0.4 that you were able to successfully reboot the server?  You may lose some playtime (joys of early access) but this is getting servers with this issue up and running again and on 8.0.5.  The other work around is more painful and requires deleting the whole law folder from the world save (make backups) and then rewriting laws when the servers back up - we have only had to do that once but on a new server that had put in about 20 laws prior to the update and they had just created the world so that was not a major loss of play time and they could have just done a new world but wanted to keep the fe things they had started.  In all other cases a roll back to the last save that rebooted successfully while on 8.0.4 has fixed it.  Interestingly I have others repeating that they had used the same law with demographics and updated to 8.0.5 without issue but had rebooted and run on 8.0.4 for a while before updating,  Not sure if that really makes a difference or is coincidence.  IF it does make a difference you could always try loading the last backup before update and running it on 8.0.4 and then update again and see if that makes any difference

**Comment by BlazeGuy2** [comment]
Fix should appear in the next hotfix
