### ISSUE TITLE
USER ISSUE: Duplication glitch using Stockpiles

### ISSUE THREAD

**Issue by gamerpaddy** [StrangeLoopGames/EcoIssues#11549]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Stand behind Hewnlogs / Mortared stone(floor type blocks), walk to the edge so your cursor is looking at a stockpile but only slightly, it has to be between the edge and the stockpile

you are able to pick up blocks like theyre stacked on the ground
put them back into the stockpile once picked up

**pics:**
Too far left:
https://i.imgur.com/5UixT7g.jpg
Too far right:
https://i.imgur.com/AH3RfDl.jpg
perfect glitch zone (depends, most time its a few pixels):
https://i.imgur.com/suS2psC.jpg

**Expected behavior:**
no duping

**Actual behavior:**
actually dupes the items

**Do you have mods installed? Does issue happen when no mods are installed?:**
no mods, playing on a vanilla multiplayer server

in addition, it also allow to add/remove/dig blocks few meters away that you normally cant reach.

**Comment by SlayksWood** [comment]
There is another possibility:
You can make the item just lay in the stockpile (but in fact it is not in stockpile). For example, put a stockpile near the mountain of stone (let's say Shale) and start to mine it. When a stone falls into a stockpile, take another type of stone (let's say Gneise) and move it to the stockpile. Now, when you place a cursor to Shale (which is actually not in stockpile), you can pick up a Gneise. But it turns out that the Gneise remains in the stockpile and you get a new Gneise. So you can get endless resources.

Video that shows how to reproduce 
https://drive.google.com/file/d/1cPfJVxXNJhLyhI1dPCX5rwWZ368Ak1JO/view?usp=sharing

**Comment by Quadbro** [comment]
tested your cases, and them are all caused by same issue, and there is even simpler way to reproduce, you just need a special angle on one stockpile...
![image](https://user-images.githubusercontent.com/6802030/54874365-804b9a80-4e1c-11e9-8b51-00c528eda153.png)
