### ISSUE TITLE
USER ISSUE: Generated World Not Random

### ISSUE THREAD

**Issue by Nadia--** [StrangeLoopGames/EcoIssues#11565]
**Version:** 0.8.0.5 beta

**Steps to Reproduce:**
Create new world
Check "generate random world"
Did this twice (on different days)

**Expected behavior:**
Different worlds are generated

**Actual behavior:**
Identical worlds are generated

**Do you have mods installed? Does issue happen when no mods are installed?:**
No mods (afaik)

**Comment by Litonius** [comment]
This is due to the seed being saved in the WorldGenerator.eco file.
If you wish to remove the current seed and have one be generated, located "Steam\steamapps\common\Eco\Eco_Data\Server\Configs" folder and under here the "WorldGenerator.eco" make a backup and save it on your PC, then open the non-backup in Notepad++. Near the top there's a line called "seed" and a string of numbers, simply remove that entire line and make a new world. (You can also save the seed if you like it :) you can also edit the seed to a random number and be your own generator.

Example of the top of the file: 

  "$id": "1",
  "Seed": 123456789,
  "Dimensions": {
    "x": 140,
    "y": 140

Example of it without the seed:

  "$id": "1",
  "Dimensions": {
    "x": 72,
    "y": 72

**Comment by Quadbro** [comment]
yes, you need to remove seed to make it random, there is no issue here. Thank's, @Litonius!

**Comment by D3nnis3n** [comment]
You should not need to remove the seed in a config file, when you only created worlds through the ingame feature, that is totally bad usability. I reopened therefore, to check if that can be improved.
