### ISSUE TITLE
Deed book?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#1159]
Could we get a separate inventory for deeds?

**Comment by SeanAtr0n** [comment]
Another option, add UI for combining/separating vehicle deeds... within vehicle deed UI.

Vehicle deeds can already support multiple vehicles, just need to add RPCs for that. (and make sure hammering vehicles does the right thing)

**Comment by sr3ka** [comment]
Or have the ability to put deeds and skills books in the bookcase.....

**Comment by NafenX** [comment]
This is one suggestion I thought of the other day but hadn't gotten a forum account till now. I think having a place so we can always have our deeds with us would be lovely since you never know when you will need to rescue your cart or give permissions to somebody, also having something like a Seed Bag for seeds because of the same reason

**Comment by CompactDisc** [comment]
Another useful feature could be to have color coded deeds, having the item icon show the color of the plot of land. And for carts, the type of cart.

**Comment by ShinSpitfire** [comment]
I love this idea. Call it "Book of the Deed".

**Comment by MarjieAVolk** [comment]
Added in 7.6 (not the release today, but the next major release after that)
