### ISSUE TITLE
USER ISSUE: sweeping hands mining perk stoped working

### ISSUE THREAD

**Issue by drakota185** [StrangeLoopGames/EcoIssues#11641]
**Version:** 0.8.0.6 beta

**Steps to Reproduce:**
tried picking up all simileir rock types

**Expected behavior:**
it should pick up all simielr raocks types

**Actual behavior:**
it picked up rocks 1 at a tim

**Do you have mods installed? Does issue happen when no mods are installed?:**
it picked up rocks 1 at a tim

**Comment by Urbautz** [comment]
I can confirm that issue.

**Comment by Naxos84** [comment]
I can confirm. worked in the version before.

**Comment by excedra** [comment]
I can confirm this to. /noskills admin command and re-skilling seems not to fix this in existing worlds.

**Comment by braxton33** [comment]
This issue is partially fixed with 0.8.0.7.
You can now pick up up to 15 items at the time (though sometimes it's as low as 8 or 9.)
However it still will not pick up the full 20 at once even when you're inches from a loose ore of the same time. (My testing was done in a pile of about 50 loose granite pieces all mined post-patch.)
