### ISSUE TITLE
Excavator cannot place dirt

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11687]
It says right click to place but on clicking right click, nothing happens.

**Comment by Rycoviac** [comment]
Can't confirm this on my side on 0.8.0.7 playing on a server.
Put dirt in excavator, switched to the slot with dirt with my mousewheel, rightclick, placed dirt on ground. Emptied the rest of the excavator into a truck, moved the shovel of the excavator to the dirt, picked it up and again, can place the dirt even without having it selected since it is the only ressource now in the excavator.

**Comment by Rycoviac** [comment]
Oh... it was a Dev making this issue... nevermind...

**Comment by SeanAtr0n** [comment]
couldn't reproduce this so far, any more info?
