### ISSUE TITLE
[0.8.1.2] Lavish Talent wrong calculation

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#11978]
[0.8.1.2] 
no mods

related to #11330

Lavish Talent doesn`t work
**Steps**
1. Take tailoring
2. Place tailoting table in the room tier1 
3. Check resources requirement
4. Level up to 7
5. Take talant Lavish

**Expected result**
- tier requirement 1
- resources requirement decrease (if level 1 cloth has 7 fibers - 50% decrease, after leveling to 7 it has 3 - 80% decrease, and there is no additional 10% from talent) )

**Actual result**
No bonuses from talent

before leveling
![bandicam 2019-04-11 16-06-14-968](https://user-images.githubusercontent.com/27898520/55954232-9e682600-5c77-11e9-8cf1-436cc097b759.jpg)
![bandicam 2019-04-11 16-06-19-416](https://user-images.githubusercontent.com/27898520/55954239-a031e980-5c77-11e9-955e-ccd3cecf3930.jpg)
![bandicam 2019-04-11 16-06-25-952](https://user-images.githubusercontent.com/27898520/55954242-a1fbad00-5c77-11e9-8089-eeada64624f4.jpg)

After leveling
![bandicam 2019-04-11 16-10-21-586](https://user-images.githubusercontent.com/27898520/55954258-aa53e800-5c77-11e9-9e59-cc0ef69aa3ce.jpg)
![bandicam 2019-04-11 16-10-39-690](https://user-images.githubusercontent.com/27898520/55954265-acb64200-5c77-11e9-9b6a-939e9c3f0e2b.jpg)
![bandicam 2019-04-11 16-10-42-754](https://user-images.githubusercontent.com/27898520/55954266-ae800580-5c77-11e9-9375-85d4fea08154.jpg)

**Comment by craig-jong** [comment]
This is probably due to the table not updating its recipes unless the room gets changed.

**Comment by mirasrael** [comment]
@craig-jong I fixed room requirements update, but it seems problem is much deeper.
1. CarpentryTable room requirements affected by *Hewing Skill*, just because it requires Hewing skill to craft this. So if you have Hewing Lavish Talent then it will apply to Tailoring table (!!!). It also true for Butchery, Fishery, Real Estate, Tailoring and Wainwright tables. I guess this requirement should be evaluated from table crafting skill, but instead should have own skill(s) associated.
2. I didn't find any reference to TailoringLavishResourcesTalent as well as to any other LavishResourcesTalent. So seems it just no used and you will just have increased room requirements without any benefits.

**Comment by mirasrael** [comment]
I fixed all mentioned above issues. More details in pull request.

**Comment by mirasrael** [comment]
It was decide to push to 8.2.

**Comment by D3nnis3n** [comment]
@mirasrael I don't see a linked pull request, is this fixed in staging right now? Please close, then.

**Comment by beastyn** [comment]
fixed in 8.2
