### ISSUE TITLE
[0.8.1.2] You can pick up ramp using shovel.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#11980]
Copied from here: #11384.
0.8.1.2 still an issue.

**Comment by Quadbro** [comment]
there is not an issue now, ramp is dirt on pickup, you cannot pick up it by hammer. So when you trying to pick it up with shovel - only one piece is allowed, you need to move dirt somewhere and pick up anouther part

**Comment by mirasrael** [comment]
Problem still exists. Actually problem is:
- you can only install whole ramp;
- then you can accidentally remove one piece with shovel;
- you can't repair ramp unless fully remove it and place again.
So expected behavior is to remove it like you place it (whole ramp with hammer) or allow to build ramp by single blocks.

**Comment by SlayksWood** [comment]
After all changes in 8.2 with ramp You can take only full Dirt ramp.
![image](https://user-images.githubusercontent.com/45708377/58802170-284bc400-8615-11e9-839b-15b391a03c0f.png)
![image](https://user-images.githubusercontent.com/45708377/58802175-2b46b480-8615-11e9-9ccf-36c968294658.png)
Seems fixed.
