### ISSUE TITLE
Chat Vanishing Issue

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#11991]
Resetted my server today, noticed chat messages are randomly vanishing shortly after posting. This is bad. Also general behaves weird. If i tick off any of the other chat tabs all general chat is gone, despite i have general activated until i activate or deactivate another chat channel.

Chat is actually really broken right now. I'll give that high cause it's so extremely enerving.

**Comment by beastyn** [comment]
Chat behaves strange in general. Maybe its just easier to remake it? 

1) By default all channels are on. When you swichoff any channel you won`t see anything for some time, and then chat will apear again. Or won`t. But even if it will, who wants to wait?
![bandicam 2019-04-12 12-32-36-946](https://user-images.githubusercontent.com/27898520/56019920-51d82580-5d1f-11e9-83a1-f08096173b58.jpg)
![bandicam 2019-04-12 12-32-46-704](https://user-images.githubusercontent.com/27898520/56019925-543a7f80-5d1f-11e9-8fbf-e99f265ef83f.jpg)
![bandicam 2019-04-12 12-33-39-069](https://user-images.githubusercontent.com/27898520/56019930-569cd980-5d1f-11e9-8297-fe4cc233f8d7.jpg)

2) If you switch off general, nothing happens, but if you switch it on again  - everything will disappear.
And won`t show anything until you switch off-on some other channel

3) Something wrong with history loading. When you try to scroll up it will do this very sharp, trying to load history. And if you scroll dow it will still try to load history.
And font will became bold.
And you won`t understand if you reach the bottom, because time mark will became strange

![bandicam 2019-04-12 12-48-24-802](https://user-images.githubusercontent.com/27898520/56020767-54d41580-5d21-11e9-982b-3fef9f380150.jpg)

About messages vanishing
I was able to see it with warning messages (red ones) and with receiving messages.
They are just popping up and disappearing.

![bandicam 2019-04-12 12-53-18-459](https://user-images.githubusercontent.com/27898520/56021221-53efb380-5d22-11e9-95de-6c3ded90773a.jpg)
![bandicam 2019-04-12 12-53-41-169](https://user-images.githubusercontent.com/27898520/56021225-56520d80-5d22-11e9-8044-1f87167dd9b9.jpg)







About

**Comment by D3nnis3n** [comment]
For me actual chat messages vanish. This chat is totally unusable. I'd actually give it critical because it's extremely broken. Someone should focus on this.

**Comment by D3nnis3n** [comment]
Also, private messages are regularily not shown in general chat.

**Comment by mirasrael** [comment]
@beastyn Does this problem persist on master?

**Comment by mirasrael** [comment]
I actually fixed issue with switching between channels. And now you can't close active channel. Also fixed rendering for old messages (with timestamp).
@beastyn I'm not clear about "time mask became strange", but anyway I guess we have separate issues created, because there are many things in chat to fix, but they all at different priority level.

**Comment by D3nnis3n** [comment]
Vanishing Chat messages fixed, top? Thats the part i considered of everything.

**Comment by mirasrael** [comment]
If it is same problem as @beastyn described then yes. I didn't have any other cases with vanishing messages

**Comment by beastyn** [comment]
@mirasrael We`vw cought issue with dissapearing messages today

My chat log was opened. I saw for a moment the message number 3 but then it has dessapeared
![bandicam 2019-04-15 17-58-10-515](https://user-images.githubusercontent.com/27898520/56134571-49dee680-5fa8-11e9-8c8b-bb18d89b3a20.jpg)

**Comment by mirasrael** [comment]
I was able to reproduce the issue.
You can just find a source of temp messages (like Workbench with active work orders which you can't remove). Then just repeat following as many times as needed as fast as possible:
1. Write message
2. Try to remove table (to get temp message)
3. Go to step 1.
You will get vanished messages really soon.
