### ISSUE TITLE
[0.8.1.3] Glitch fake plants

### ISSUE THREAD

**Issue by criptonauta** [StrangeLoopGames/EcoIssues#12014]
v 0.8.1.2 beta

Problem: When using Ceiba as fake plant in round pot, tree remains after Pot is removed.

Steps:

1 Place a pot
2 Use ceiba seed on pot
3 Remove Seed
4 Remove Pot

![Capturar](https://user-images.githubusercontent.com/6478038/56086032-2ab34e00-5e1c-11e9-99d2-21a260bcce2e.PNG)

I have relogged and it persists

![Capturar1](https://user-images.githubusercontent.com/6478038/56086046-6817db80-5e1c-11e9-8432-61d62ae80459.PNG)

**Comment by SlayksWood** [comment]
I managed to reproduce only this way:
1. Place a pot.
2. Use ceiba seed on pot.
![image](https://user-images.githubusercontent.com/45708377/56288682-ec71a380-6127-11e9-8c06-1f3551ed5901.png)
3. Reload.
4. Remove Seed.
![image](https://user-images.githubusercontent.com/45708377/56288857-4b371d00-6128-11e9-9645-02708b565fd5.png)
5. Use tomato seed on pot.
![image](https://user-images.githubusercontent.com/45708377/56288911-6dc93600-6128-11e9-8216-0a11889fa055.png)
6. Reload.
7. Remove Seed.
8.  Use pumpkin seed on pot.
![image](https://user-images.githubusercontent.com/45708377/56289080-cbf61900-6128-11e9-88fb-3c17ab313a07.png)
8. Reload.
9. Remove pot.
![image](https://user-images.githubusercontent.com/45708377/56289259-2f804680-6129-11e9-8c46-9b33ab1703c4.png)

**Comment by Spydarlee** [comment]
Cannot reproduce this on latest (master 9.0) as you can no longer pick plant pots up without taking their contents out first.

**Comment by SlayksWood** [comment]
Still an issue

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/79201579-f9ab9600-7e40-11ea-8aee-0b7ff933668e.png)

**Comment by johnkslg** [comment]
Pretty janky and easy to trigger, worth looking at

**Comment by BlameTheSystem** [comment]
Hi, 

Just had this occur on a 0.8.3.3 Beta server. I have not posted the logs as it only shows backups and admin commands and has not caused a crash. This was reported to me by one of the server players. I have tried removing it with the dev tool, it will let me select it and highlights the plant, but will not let me smite it. I have asked the player to re log and it still persists even after a server restart. Some players cannot see these bushes. The plant appeared for me after a pot was placed under the plant.

The steps the player carried out to cause the issue was:
how did this start? did you place a plant pot there then seeds or did it just start to appear?
- Pot+seeds
- Then I wanted to move it
- Removed seeds then pot
- Plant remained

The first screenshot seems to show multiple plants, however I can only see 1 plant in this spot and cannot see the plant in the second screenshot.
![382310_screenshots_20200427000318_1](https://user-images.githubusercontent.com/43051590/80322440-21c1ce80-881d-11ea-8348-e41c43010588.jpg)
![unknown (1)](https://user-images.githubusercontent.com/43051590/80322443-238b9200-881d-11ea-97b8-fafcacd332cd.png)

If you need anymore info please let me know.
