### ISSUE TITLE
[0.8.1.3] Stockpiles Tutorial 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12085]
For the next after Stockpiles Tutorial need 10 Logs.
Stockpiles Tutorial requires me to put 10 Logs in it.
But I can put 5 Logs, pick up them and put them in the stoсkpile again. Tutorial completed.
![image](https://user-images.githubusercontent.com/45708377/56506161-4efee100-6526-11e9-89c9-14b4ab010fe7.png)

**Comment by SlayksWood** [comment]
0.8.2.0 staging-6 I put 5 Logs one time and Tutorial complete

**Comment by SlayksWood** [comment]
0.8.2.0 staging-15-n-2 I put 5 time by one Log and Tutorial complete. Also you can put 1 Log, pick up it and repeat 4 times and tutorial will complete.

**Comment by gzatravkin** [comment]
This issue is very minor but it's difficult to make clean fix (for example if rule is achieve 10 in stockpile, you may need to put more in case of active projects).

User anyway can skip tutorial if he want, so there are no exploit in it. 

Closing (comments from https://github.com/StrangeLoopGames/Eco/pull/6558)

**Comment by SlayksWood** [comment]
We do not take this bug into account. But you are needed now to place 5 logs instead of 10. Can you fix at least this one?
