### ISSUE TITLE
[8.2 beta] Weird acting Waste Filter

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#12169]
The waste filter also has water at the outlet when the input is disconnected or the filter is turned off
![grafik](https://user-images.githubusercontent.com/37456949/57146089-d2d98880-6dc4-11e9-8661-eeb25ca3ca36.png)
And the Wastefilter need no Power to work
![grafik](https://user-images.githubusercontent.com/37456949/57146323-5a26fc00-6dc5-11e9-8651-91dbfcdd13a2.png)

**Comment by beastyn** [comment]
Seems to be fixed in last stagings
![bandicam 2019-05-27 09-44-17-753](https://user-images.githubusercontent.com/27898520/58396062-84867500-8064-11e9-9b3e-5f22e316df2e.jpg)
![bandicam 2019-05-27 09-44-39-553](https://user-images.githubusercontent.com/27898520/58396066-87816580-8064-11e9-8ef9-430c662f7269.jpg)
