### ISSUE TITLE
[0.8.2 staging -3] Black rects appear when digging

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12201]
I suppose this one is related to PR 4144

Now, when you are digging firstly you will see black rects
![bandicam 2019-05-07 14-13-44-782](https://user-images.githubusercontent.com/27898520/57288177-716e2e00-70d2-11e9-8bb0-5a25ceb30641.jpg)

Everything now have black rects )
![bandicam 2019-05-07 14-16-11-350](https://user-images.githubusercontent.com/27898520/57288480-f8bba180-70d2-11e9-8027-e8388d8eec87.jpg)
![bandicam 2019-05-07 14-17-35-771](https://user-images.githubusercontent.com/27898520/57288484-fa856500-70d2-11e9-8082-ca0450addccb.jpg)

@metachronism @SeanAtr0n 
Can this black-buggie-booggie-thing has affection on the problem with slow chunk updating and lasting meshes #12168?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/57304900-ccab1b00-70e8-11e9-84e9-480fa305b57f.png)

**Comment by SlayksWood** [comment]
![2019 05 07 Black Hole](https://user-images.githubusercontent.com/45708377/57306294-3e846400-70eb-11e9-8185-d2397c5233ef.gif)

**Comment by SeanAtr0n** [comment]
probably need Player.log for these cases, looks like the chunk failed to build

**Comment by SlayksWood** [comment]
0.8.2.0 staging-14-n still an issue. But the behavior has changed a little.
Due to the update of the chunks, now the black background does not freeze during normal actions. But this is still possible if you use the / level command. But while digging it can still be seen. 
First, the block disappears, then the black background disappears. Because of this, black background flashes.
Slow-mo:
![2019 05 27 BackGround](https://user-images.githubusercontent.com/45708377/58397834-5f413900-805b-11e9-9a87-98ed95ea45e1.gif)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3221980/Player.log)

**Comment by SeanAtr0n** [comment]
this ties in w/ the work @mirasrael is doing on chunk optimizations so reassigning... ideally the main terrain mesh should change at the same time as the shadow mesh

**Comment by mirasrael** [comment]
Can we push it to 9.0, because I'm planning global chunks rework and this problem can't be solved easy way in current implementation?

**Comment by mirasrael** [comment]
It is actually old issue, previously it blinked with just empty space. Because now it happens rarely enough and there are planned rework for chunks in 8.3 moved it to 8.3.

**Comment by mirasrael** [comment]
Is it still an issue? @SlayksWood

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Staging-1951.

I'm not encountering this issue or any form of missing assets no matter how destructive I try to dig blocks, mine, and such.

Resolution: Closing.
Will keep an eye on this ticket and will reopen if the issue presents itself again.
