### ISSUE TITLE
[0.8.2 staging-10-n] Owner changing doesn't remove previous owner bank account

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12361]
**Steps**
1. Make a store
2. Unclaim deed
3. Let someone claim it
**Expected**
New owner can see realted to him info. Such as a bank account.

**Actual**
New owner can use your bank account 

![bandicam 2019-05-20 17-16-47-454](https://user-images.githubusercontent.com/27898520/58024214-20772480-7b2b-11e9-80f3-c6a566882986.jpg)

**Comment by johnkslg** [comment]
Pushing to 9

**Comment by beastyn** [comment]
Some additions. Problem is common for every deed that was sold. This deed will have previous owner's bank account in Credit tab by default. Like in #12312

**Comment by beastyn** [comment]
Check after #17031

**Comment by SlayksWood** [comment]
Hm, I still have some problem, So I still can use another player account, I can't select it, but it doesn't refresh. So step to reproduce:
- player 1 place store and claim it:
- add something to sale/ bying:
![image](https://user-images.githubusercontent.com/45708377/87403615-bf7b9d00-c5c5-11ea-87f1-49d391f68cfd.png)
- transfer ownership to another player:
![image](https://user-images.githubusercontent.com/45708377/87403739-efc33b80-c5c5-11ea-99c6-1d44f7a6ded0.png)
- another player open store and he has the same saling/bying list:
![image](https://user-images.githubusercontent.com/45708377/87403921-2436f780-c5c6-11ea-87c8-2642df19b1c2.png)
- if another player open credit tab he'll see that he used first player account:
![image](https://user-images.githubusercontent.com/45708377/87404126-65c7a280-c5c6-11ea-84af-75a7c990f9af.png)
So people still can exploit it.
But you can refresh it to DEVQA account, because user'll exploit it too: place store in one claim and change ownership to another player. Sold him a lot of useless items in this store.

I have 2 solution to it:

- [ ] If store change owner than it should reset persistent data

- [ ] Prevent change ownership without the consent of the other player. It will look like:
- first player select change ownership like we currently have.
- but it will not change it immediatly.
- second player should have some notification where he can click yes/no. Maybe click for some link that open ConfirmBox.

**Comment by johnkslg** [comment]
You can make components listen to a new WorldObject.OnOwnerChange and then update anything accordingly (bank accounts etc)
