### ISSUE TITLE
 problem with crafting experience calculation

### ISSUE THREAD

**Issue by Keranara** [StrangeLoopGames/EcoIssues#12394]
problem only with craft where more 1 ingredient.
If we put just part of ingredient (for example for bricks it will be mortar) and go to dig clay, then put clay when part of progress bar will be filled we get instantly few bricks but experience for craft will be gain only like for 1 item.

Attaching video with example this issue: https://www.youtube.com/watch?v=N0r__cRvcjY

steps.
profession exp is 0
exp for creation brick is 50
start project on 10 bricks and put 40 mortar for project
waiting for filling progress bar
put second part ingridient 25 clay.
instantly getted 6 clay and getted 50 exp (must be 300 exp because 6*50=300)

**Comment by SlayksWood** [comment]
Step to reproduce:
- start 50 shale bricks
- add shales and mortars
![image](https://user-images.githubusercontent.com/45708377/59252309-82134600-8c34-11e9-8f29-71b6d06f5102.png)
- finish craft without clay
![image](https://user-images.githubusercontent.com/45708377/59252405-b5ee6b80-8c34-11e9-940e-8f1030461c87.png)
- add 50 clay. I have 162,9/1875 exp in Bricklaying. After craft I should have 162,9 + 18,1*50 = 1067,9/1875 exp
![image](https://user-images.githubusercontent.com/45708377/59252449-c56db480-8c34-11e9-8493-8000ed8ac9a2.png)
- start craft with clay. I immediately get a lot of bricks and experience for 1 unit. 
Time is recalculated and it is shown that you need to craft 4 bricks.
![image](https://user-images.githubusercontent.com/45708377/59252707-504eaf00-8c35-11e9-8af7-e5ac586e7a4b.png)
- When craft is finished I have 253,5 exp instead 1067,9. I got 5 times experience instead of 50.
![image](https://user-images.githubusercontent.com/45708377/59252920-c94e0680-8c35-11e9-861f-8f109d102a61.png)
