### ISSUE TITLE
Fish traps don't collide in water. Part on land.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12416]
You can dig whole fish trap in water: 
![image](https://user-images.githubusercontent.com/45708377/58407449-76405500-8074-11e9-8035-1600c8a99c93.png)

You can dig part of fish trap on the land:
![image](https://user-images.githubusercontent.com/45708377/58407204-e9959700-8073-11e9-9088-2cbd5b07fd6b.png)

**Comment by MazonDel** [comment]
After some examination it seems the issue is that when you place the fish trap it correctly sets those world-blocks as being occupied by the fish trap, but then a moment later it fills in the space with the water blocks which don't know that there is a fish trap there, so when you attempt to place dirt, it just sees an "empty" water block instead of the trap.

**Comment by mirasrael** [comment]
Just realize it somehow works for Pipes :-D
https://github.com/StrangeLoopGames/EcoIssues/issues/18043
Can you check this?
