### ISSUE TITLE
RequireAuthentication

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12443]
John has reverted your RequireAuthentication change, as the web team needs it to be in release builds, this makes the bug with steam users being displayed as long hashes as well as the consequences of this being re-existant.

John proposed a way for internal config settings only accessible by staff, but in any case this issue should be open to track the issues that arise with it. And given the impact and the non-reversibility, it's a high priority one.

**Comment by mirasrael** [comment]
Assigned to 9.0, because change was reverted in `master`, still active in 8.2. Because web team need it only to be able to make REST queries without auth we will make alternative solution for this (available in Release). It will be possible to add custom persistent `Auth Token` which may be used by REST API calls. It also may be used for another user automation tools.
