### ISSUE TITLE
[0.8.2.0 staging-16-n] Forgotten talents

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#12470]
Fisherman: Hunting
Aggressive Angler: Hunting
Diver: SelfImprovement
Sprinter: SelfImprovement
Loggers Luck:Logging
No description, no functioning. It is necessary to make them so that there is a choice in Hunting, Logging and so that there is a working talent at level 3  in Self Improvement

**Comment by SlayksWood** [comment]
https://github.com/StrangeLoopGames/EcoSuggestions/issues/927

**Comment by TheOvermind** [comment]
### **Hunter**
This is a hard one. To be able to get Fishing tables, you need to give uses to them. I mean, in the current state of the game once you got a Campfire specialization it becomes useless (Until you can make Hydrocolloids, and i think it's easier with other things).
Anyway, here's my 2 cents (Implying Fish is useful)
- **Fisherman**: Doubles the yield of harvest of the Fish Trap.
- **Aggressive Angler**: Since Hunting for animals uses Arrows, Fishing should use Bait. This trait could allow you to not use it, tho.
Sidenote: Fishing doesn't give Hunting XP.

### Logging
Debris ARE the worst part of logging. I don't think anything would be more useful than that, but i guess that if got another logger with you... The mining perk could work.
**~~Loggers Luck~~ Sweeping Hands**: Picking up logs also attempts to pick up logs in an area.

### SelfImprovement
I will comment on the Linked issue.

**Comment by IcedForge** [comment]
Closing this as resolved, after a lengthy discussion we came up with some good designs i think will work well.
