### ISSUE TITLE
 [0.8.2.0 staging 1001] rounding / multiplier error

### ISSUE THREAD

**Issue by Sobaton** [StrangeLoopGames/EcoIssues#12540]
Step to reproduce:
(mortaring skill ist level 8)
At a Masonry Table, increase the number of items to be crafted to be 100. (normaly u need 1.2 Sandstone to grind 1 Sand) but the game round it to 121 not 120 
![grafik](https://user-images.githubusercontent.com/48158779/59515911-776ce100-8ec0-11e9-90c4-8dcc06d22e4f.png)

if you increase the number  of items to be crafted to 1000 it is correct
![grafik](https://user-images.githubusercontent.com/48158779/59515928-85bafd00-8ec0-11e9-917a-8ddfe3e5024b.png)

**Comment by SlayksWood** [comment]
Were fixes rounding, but the recipes with wrong rounding still remained. I will add all encountered errors with rounding here.

**Comment by Sobaton** [comment]
i test now all Tables whit max skill and found some more rounding / multiplier errors:
Masnory Table:
Grind Granite To Sand
Grind Sandstone

Backery Oven:
Baked Roast (Raw Roast)
Bread (Yeast and Flour)
Camas Bread (Yeast)

Kilm:
Glass
Tallow Lamp (Clay)

Anvil:
Iron Pipe

Sawmill:
Saw Boards

Screw Press:
Iron Plate

Lathe:
Iron Axle
Screws

Shaper:
Gear

Electric Machinist Table:
Servo (Fiberglass & Circuit)

Electronics Assembly:
Circuit (Substrate)
Electric Wall Lamp (Steel)
Fiberglass (Glass)
Robotic Assembly Line (Electric Motor)

Electric Planer:
Steel Gear (Steel & Epoxy)

Robotic Assembly Line:
Advanced Combustion Engine (Radiator)
Framed Glass Door (Framed Glass)

Rolling Mill:
Flat Steel (Steel & Epoxy)

Bloomery:
ok
Workbench:
ok
Mill:
ok
Cast Iron Stove:
ok
Stove:
ok
Machinist Table:
ok
Assemnbly Line:
ok
Cement Kiln:
ok
Electric Stamping Press:
ok
Electric Lathe:
ok
Oil Refinery:
ok
Pump Jack:
ok
Laboratory:
ok

Mint/Bank/Currency Exchange/Registrar/Treasury/Computer Lab
out of controll

**Comment by mshocklee** [comment]
V 0.8.2.4
Masonry Level 7
Grind Sandstone tooltip says it uses 1.08 Sandstone
At Masonry Table:
Queue up 025 Sand, uses 28 Sandstone instead of 27
Queue up 050 Sand, uses 55 Sandstone instead of 54
Queue up 075 Sand, APPROPRIATELY uses 81 Sandstone
Queue up 100 Sand, uses 109 Sandstone instead of 108
Queue up 125 Sand, APPROPRIATELY uses 135 Sandstone
Queue up 150 Sand, APPROPRIATELY uses 162 Sandstone
Queue up 175 Sand, APPROPRIATELY uses 189 Sandstone
Queue up 200 Sand, uses 217 Sandstone instead of 216

**Comment by mshocklee** [comment]
Is this the same rounding error as the currency?

**Comment by Valares** [comment]
This bug still appears in the Version 0.8.3.1. Not sure if it's fixed in the dev version, I'll probably check it on the weekend.

Also, be aware that 
> Queue up 075 Sand, APPROPRIATELY uses 81 Sandstone

is not true (at least not for Version 0.8.3.0 and 0.8.3.1), as it **states** the correct amount, but actually **consumes 1 more**.
![Bug Eco](https://user-images.githubusercontent.com/20939239/71100069-a25c2880-21b4-11ea-98a3-fc0f67ac3b39.png)
The same is true for smelting Sand at the Kiln into Glass, and I guess for all the other ones listed too.

**Comment by SlayksWood** [comment]
Need check after changing in craft

**Comment by mirasrael** [comment]
@SlayksWood can you check this and said if it is actual?

**Comment by SlayksWood** [comment]
Still an issue:
- place carpentry and add Basicupgrade4:
![image](https://user-images.githubusercontent.com/45708377/74430956-fc086880-4e6e-11ea-8f88-88849956fa5c.png)
- change to 100 in Hewn Log recipe.
![image](https://user-images.githubusercontent.com/45708377/74430787-a764ed80-4e6e-11ea-91e3-5e5da9135bd9.png)

**Comment by SlayksWood** [comment]
Seems fixed
