### ISSUE TITLE
[8.2.0] Korean translation not showing properly

### ISSUE THREAD

**Issue by gomsoop** [StrangeLoopGames/EcoIssues#12571]
Hi, I'm the proofreader for Korean in Crowdin. (Hizzgom in discord)

I updated to 8.2.0 and found out that the translations are not applying right. First at the discord channel, I found two errors that stops loading the translation.

" {0:time} left to vote." in German String
"Bricklaying is an advancement in masonry and can provide an excellent building material for communities. Level by crafting related recipes." in Japanese String

Before fixing these strings, cloth items in my backpack was showing in English. After deleting two translated strings, items showed normally again in Korean.

However, in 8.2.0, one of the tutorial, which is Finding Foods, is showing English descriptions. When play in 8.1.0 just yesterday, it was in Korean. I think two strings above is messing the whole loading up of translations. I will put issues on Crowdin also.

**Comment by gomsoop** [comment]
Two strings (German and Japanese) had included \n inside the translations. I think this is why it caused error. Fixed in crowdin.

**Comment by D3nnis3n** [comment]
Finding Food Tutorial was changed from 8.1 to 8.2. Are you sure you already translated the new one?

**Comment by gomsoop** [comment]
> Finding Food Tutorial was changed from 8.1 to 8.2. Are you sure you already translated the new one?

Yes. I translated and approved into Korean 100%.

**Comment by Spydarlee** [comment]
Ah, sorry about that @gomsoop but it looks like a few new strings (~30) were added or changed since 8.1.0, so the 100% completion on Crowdin doesn't exactly match up with what's in the game.

I've uploaded the new strings to Crowdin (including new text for Finding Foods) now, so if you want to translate those I can import them into the game later this week and get them into 8.2.2.

(I'm also working on a much bigger localization update which includes hundreds of new strings, but those are for 9.0 so I will hold off on uploading those to Crowdin until we've got the 8.2+ translations sorted.)

**Comment by gomsoop** [comment]
@Spydarlee Done! :)

**Comment by Spydarlee** [comment]
Brilliant, thanks! These should go in soon and hopefully be in the next build.

![image](https://user-images.githubusercontent.com/553695/59853151-36654880-9368-11e9-8854-d07fd8f23e69.png)
