### ISSUE TITLE
Hashset fails when trying to insert null if you delete users from storage file

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12622]
To repro: 
Take a world save, open it, delete the users, run the server.

**Comment by mirasrael** [comment]
@johnkslg How do you want to have it fixed? We have many references to user across the system and many objects will just become invalid without user (like creator, owner etc). Only safe way to remove user this way is to not have references to user from another entities (i.e. scope everything user-specific under a user), make every creator reference a string instead of user reference and expect to not have matching user. But it is very big refactoring.

**Comment by johnkslg** [comment]
You're right, we can just not support this.
