### ISSUE TITLE
Glitched truck that cannot be freed and shows the world upside down

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#12658]
Never had that before 8.2.4:
![truck1](https://user-images.githubusercontent.com/25908592/60215374-c07d4780-9867-11e9-9cc2-c8765b5e17e4.png)
![paint2](https://user-images.githubusercontent.com/25908592/60215432-e4d92400-9867-11e9-82d1-4199031ad39d.png)

**Comment by SlayksWood** [comment]
I do not quite understand what is the problem here? If the truck turned upside down and you get into it, the picture will be turned upside down. And I do not quite understand about the freed of the truck. Do it Pick up and place impossible?
![image](https://user-images.githubusercontent.com/45708377/60244893-141d7e80-98c4-11e9-85cf-4005adc3d337.png)
![image](https://user-images.githubusercontent.com/45708377/60244908-1bdd2300-98c4-11e9-91de-7e90ca53f2f4.png)

**Comment by D3nnis3n** [comment]
Trucks used to turn around when you get into them, they could not glitch in the ground before. At least in 1.5 years i've never seen such a situation and i've rescued hundred of trucks that have been falling over.

**Comment by mirasrael** [comment]
I added /unstuckvehicle command which should help in such cases.

**Comment by D3nnis3n** [comment]
Perfect solution.

**Comment by SlayksWood** [comment]
Need to be careful.
On a flat surface:
![2019 07 03 Unstuck vehicle](https://user-images.githubusercontent.com/45708377/60582414-6dd4eb80-9d91-11e9-9021-8a31b0557241.gif)
not flat surface:
![2019 07 03 Unstuck vehicle 2](https://user-images.githubusercontent.com/45708377/60582874-52b6ab80-9d92-11e9-9e87-d7dfa7b75bda.gif)

**Comment by mirasrael** [comment]
It doesn't move truck from it's position to avoid abuse, only changes rotation, but you can select best rotation you want, because it always respawns perpendicular to you.
