### ISSUE TITLE
Add Admin Command for Citizenship

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#12663]
Could you make it so that admins are automatically made Citizens and/or add a Admin command so the admin can claim citizenship when they need it.  Many server owners/admins would like to be able to implement laws when they start their server and cannot as they are not yet citizens.  A server owner/admin should be able to be a citizen of their world from the start so it would be nice if "admin" carried citizenship with it.  If not and some would rather that granting /admin not also grant citizenship for those who are not server owners then a way to grant citizenship to the owner by a in-game command separate from the /admin command (although I realize then any admin could use that)  then adding them to a "citizen" variable in the Users,eco config would be another possibility.

**Comment by D3nnis3n** [comment]
Actually change the default demographics to be:
you are a citizen if
- you are a admin or
- you playtime .... blablabla (just like now)

**Comment by SlayksWood** [comment]
@D3nnis3n 
I don't quite agree. I want to play on equal terms with everyone. But I, as a dev, have the same privileges as the admin. Changing the law in this way will give me the opportunity to create the laws too. It must be taken in fix.

**Comment by D3nnis3n** [comment]
Afaik that is not true. While devs do have admin rights, they are not considered admins. With my work account for example i'm NOT excluded from tax laws that dont tax admins, as long as i didnt specifically add the work account to the servers admin list.

But even if that would be the case, we just need to make sure that devs do not count as admins, even though they have rights.

**Comment by Praefator** [comment]
@D3nnis3n perhaps working with one of the mod authors for a permission group system could work in that regard? I remember having to separately add you to a permission group when you were recording my server video during the tail end of 8.0, which is when I used Pradoxzon's GroupManager. I emailed JohnK something to that regard in terms of matchmaking as well when I sent my 9.0 feedback mail.

**Comment by WeaselDog** [comment]
This is fixed by new demographic system.

**Comment by WeaselDog** [comment]
By default Everyone can make laws, but let me explain process for what admin would do to pass laws or even recreate the old citizenship law.

Basic admin stuff:
- Place Capitol and ratify Constitution
- Place Court and/or any civic building for anything you want to make changes to
- Pass as many laws as you want

How to recreate Citizenship law:
- Use Census Bureau to create "Voter" demographic below
- Create "Standard Election" process with default template except change Voters to "Voter" demographic
- Amend constitution articles to use "Voter" instead of "Everyone" and "Standard Election" instead of "Basic Election"

![VotersDemo](https://user-images.githubusercontent.com/47330823/70378603-2a9a1e00-18d7-11ea-95d0-812dd47ee915.png)

**Comment by D3nnis3n** [comment]
Considered fixed then.
