### ISSUE TITLE
Tier 2 Room Lowered to 1.99 After Adding Iron Pipes

### ISSUE THREAD

**Issue by mshocklee** [StrangeLoopGames/EcoIssues#12730]
I've created a fully enclosed room entirely made of Tier 2 materials (glass, lumber, lumber door). It previously showed as a calculated tier value of 2. I removed a glass window, and added two iron pipes which are also Tier 2. This has lowered the calculated tier value to 1.99. If I remove the two pipes, add back the glass, then pull out a few blocks and put them back to reset the room calculation, it will not go back to Tier 2.

![ECO_0 8 2 7_TierIssue](https://user-images.githubusercontent.com/10479775/60907335-e844b600-a23e-11e9-8783-6db42be37055.png)

No mods.

**Comment by SlayksWood** [comment]
I can't reproduce. Iron pipe gave me Tier 2.
![image](https://user-images.githubusercontent.com/45708377/60944998-1257b000-a2f3-11e9-91ba-ccd3f58466f0.png)

**Comment by SlayksWood** [comment]
@mshocklee 
Can you provide save files? and room coordinate?

**Comment by mirasrael** [comment]
@mshocklee Which game version are you running?

**Comment by mshocklee** [comment]
0.8.2.7

**Comment by mshocklee** [comment]
Unfortunately, not my server so I do not have access to files.

**Comment by mshocklee** [comment]
> 
> 
> I can't reproduce. Iron pipe gave me Tier 2.
> ![image](https://user-images.githubusercontent.com/45708377/60944998-1257b000-a2f3-11e9-91ba-ccd3f58466f0.png)
> It looks like there is an empty block somewhere.

The room was previously full Tier 2. It was definitely fully enclosed. The only time it wasn't fully enclosed was when I removed one glass window to replace it with a pipe leading outside before I realized the cast iron stove did not actually need pipes to function.

**Comment by mshocklee** [comment]
Server: pulseCore Increased Skill Gain Active Admins
Coordinates: (392,67,814)

**Comment by SlayksWood** [comment]
It's due to a new rules for calculating a room (when empty corners reduce Room Tier). If the room is square, then everything is quite simple. But if the room is made like you have to be careful. This corner:
![image](https://user-images.githubusercontent.com/45708377/61198529-1153c380-a6e3-11e9-8eef-3d49cc6d62ec.png)
Visually, it looks good, but behind him is empty blocks
You need to place 3 more blocks on the reverse side to fix the room.
![image](https://user-images.githubusercontent.com/45708377/61198571-43fdbc00-a6e3-11e9-96f5-d58a41528a13.png)

**Comment by mshocklee** [comment]
Wow. That was the issue. It didn't affect the room below it, so I didn't realize the spot was there.
