### ISSUE TITLE
USER ISSUE: Cannot Harvest Bunch Grass

### ISSUE THREAD

**Issue by chickenswag101** [StrangeLoopGames/EcoIssues#12755]
**Version:** 0.8.2.8 beta

**Steps to Reproduce:**
1. Get a Scythe
2. Hold Scythe and try to highlight the plant
3. Try to Harvest it but it didn't highlight or get picked up

**Expected behavior:**
It should have highlighted and been picked up

**Actual behavior:**
Instead nothing happened.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Yes I do have mods and it still happens when no mods are installed.

**Comment by SlayksWood** [comment]
@chickenswag101 
Can you no harvest all bunchgrasses in world or just a certain bush?
It was fixed in the latest version. Now I have no problems with harvesting of this grass.
Please provide log and if possibly save files (with coordinate of not harvesting bunchgrass).
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and here  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by chickenswag101** [comment]
ok so i wasn't able to harvest any bunchgrass in the world but i fixed the problem easily by verifying the files in steam. i guess steam didnt update that for me before or something.
