### ISSUE TITLE
[0.8.2] Workbench Stone Exploit

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#12751]
Someone explained an exploit to me:

![StoneExploit](https://user-images.githubusercontent.com/47330823/61175700-a8484080-a568-11e9-974a-4f9fe0c61b14.png)

You use a workbench to make a large queue for for Stone and then remove the storage it goes into.
There are similar exploits to this all based on having large maximum queue size.

**Comment by WeaselDog** [comment]
I misunderstood what he was saying, it is not related to the storage. It is when you remove the block under the workbench that is the exploit.

**Comment by Yorkforce** [comment]
What should happen is the single item that is being crafted at the time should only take out what it needs from storage to craft that single item, that would close this exploit right up and prevent the mass deletion of resources which kinda defeats the purpose of storage management and claims.

For example, you queue up 100 sandstone to sand that takes 3 sandstone per sand. Instead of taking all the sandstone for all 100 sand straight away, it should take out 3 only until 1 sand has been crafted, then another 3 and so on.

**Comment by WeaselDog** [comment]
No longer issue with new crafting system and Arrastra
