### ISSUE TITLE
[0.8.3 staging 1061] Shadow remastering

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#12839]
We need to revise shadows for materials. With some materials they look bad (/time 10 for repro)
Also they are are pretty sharp and dark in general.
![bandicam 2019-08-02 11-15-06-375](https://user-images.githubusercontent.com/27898520/62367012-e9b58580-b541-11e9-9466-d73a7f41bf18.jpg)
![bandicam 2019-08-02 11-06-20-004](https://user-images.githubusercontent.com/27898520/62367023-f20dc080-b541-11e9-855a-73c89e54180a.jpg)

**Comment by beastyn** [comment]
merge #3748

**Comment by keegan-o** [comment]
The shadows look like this because they are not using the meshes, they are using colliders-- not sure what I could do about it, I think the system is flawed but I'll let @mirasrael decide if there is anything he'd like to try to improve it. I think if it's possible it'd be nice for it to be a setting exposed for players to turn on to improve perf if they need at the sacrifice of shadow quality, perhaps limiting it to lower shadow quality otherwise so that the mis-matches are less sharp.

**Comment by mirasrael** [comment]
I already changed shadows to use same mesh as rendered. Shouldn't be a problem now. @keegan-o can you check?

**Comment by beastyn** [comment]
looks better, but still has these harp things (it doesn't even look like a shadow)
