### ISSUE TITLE
USER ISSUE: Item Dissapears

### ISSUE THREAD

**Issue by Possemaster** [StrangeLoopGames/EcoIssues#12834]
**Version:** 0.8.2.9 beta

**Steps to Reproduce:**
Put a Torch in the "Storage" slot of the Torch Stand instead of the Power slot will detroy the Torch. It vanishes

**Expected behavior:**
Or not being able to place into the storgae slot of the Torchstand or used it as fuel

**Actual behavior:**
Detroyed the Torch

**Do you have mods installed? Does issue happen when no mods are installed?:**
Detroyed the Torch

**Comment by SlayksWood** [comment]
If you put torch in storage of torch stand it will be add to fuel. Its intended behavior.
![image](https://user-images.githubusercontent.com/45708377/62346125-9e798380-b4fd-11e9-9f4f-b20d3c80ec32.png)
You have an inscription that says that it is for fuel supply. It's done so that you can add torches from another storage, and it isn't necessary add from your inventory.
![image](https://user-images.githubusercontent.com/45708377/62346222-fd3efd00-b4fd-11e9-9887-12842683df68.png)
