### ISSUE TITLE
Minimap Feedback Round 1

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12928]
**Minimized form**
![image](https://user-images.githubusercontent.com/3536496/63389797-bd7f6e80-c361-11e9-8293-94450993374d.png)
- [x] Need to add the slider piece to the background data (the property is being covered)
- [x] That glare isnt quite working. Needs to be a lot more subtle and have more than just the glare indicating its glass. Looks like a bug.  
- [x] Text should not be shown in minmap: johnkford, the property name, is below and cutoff.  My name is on there.
- [x] The player icon is way way too big here.

**Maximized Form**
![image](https://user-images.githubusercontent.com/3536496/63389860-f15a9400-c361-11e9-870e-5e9d8204908f.png)
- [x] Make it fill the entire screen with no borders. Stop rendering the world to improve on performance.
- [x] Close button should look like a minimize button, and should either be in bottom right, like it is on the popup menu. Clicking that should return it to whichever view you were last in, popped out or slotted.
- [x]  This tiny setting button looks really weird. It's too small, and doesnt look like it indicates a pull up menu.  Also, use 'quadout' easetype, not 'quadinout', feels a lot slicker. And reduce open time. 
![image](https://user-images.githubusercontent.com/3536496/63389904-1c44e800-c362-11e9-83a8-26c60ffb944f.png)

**Setting Panel**
![image](https://user-images.githubusercontent.com/3536496/63389938-44cce200-c362-11e9-8317-d23aa6f3a08a.png)
- [x] The headings should have a different background than the items to select, or just remove the background from the checkboxes completely.
- [x] Margins are sloppy here. 
Arrow overlaps:
![image](https://user-images.githubusercontent.com/3536496/63390021-7645ad80-c362-11e9-8ca9-e1983ffed7c8.png)

Text is not left-aligned, and text goes outside the backgrounds:
 ![image](https://user-images.githubusercontent.com/3536496/63390032-7e055200-c362-11e9-856f-28695e738a3d.png)

Highlights expand past item:
![image](https://user-images.githubusercontent.com/3536496/63390099-b86eef00-c362-11e9-8a62-0dee46696e96.png)

This panel should have no scrollbars unless its completely filled the screen, and the scroll bar should be associated with the entire panel, not a subsection (as its in 'Camera' here)

The  The margins should be better.  This panel should be larger so there's no sub-scroll bars (ideally it resizes to have
- [x] These menus are functioning like tabs, but are actually an expandable hierarchy, yet dont support that design properly.  IE, I cant expand both camera and settings.  Change the design to be selected tabs, which can be chosen by icon, and an insta-tooltip shows the name of them.

- [x] Closing maximized map with settings open gave me this: 
![image](https://user-images.githubusercontent.com/3536496/63390174-ff5ce480-c362-11e9-9bef-ddf83f6763f1.png)

**Popped Out View**
- [x] Popping out the map put it off screen. It should default to something nice (top right corner), and clamp so its top movement bar is never unselectable (but you can still drag it off the screen)
![image](https://user-images.githubusercontent.com/3536496/63390197-0edc2d80-c363-11e9-8ec5-1872772372c5.png)
- [x] Not all edges were not grabbable for resizing.
- [x] On the bottom left: 
![image](https://user-images.githubusercontent.com/3536496/63390249-4f3bab80-c363-11e9-83ba-e640c01c8e01.png)
This looks like a button, but its too small if it is, and clicking it does nothing anyway. 
- [x] Menu dropped down past the edge of the screen and I couldnt close it:
![image](https://user-images.githubusercontent.com/3536496/63390292-73978800-c363-11e9-9889-3e22f205dce1.png)
Should keep the close button on the edge of the window, and make it drop up.
- [x] Need to do soemthing with this empty space
![image](https://user-images.githubusercontent.com/3536496/63390351-a5105380-c363-11e9-8c14-575d9898dc9b.png)

- [x] Somehow through a combination of expanding and minimizing and popping it out, my minimap disappeared for good:
![image](https://user-images.githubusercontent.com/3536496/63390509-44cde180-c364-11e9-88e3-e5b92d654414.png)

**Comment by johnkslg** [comment]
- [ ] Border of window should meet the edges of the screen.
![image](https://user-images.githubusercontent.com/3536496/63555513-16800b80-c4f6-11e9-81c4-ac53cbd55006.png)
- [ ] There's a one frame pop when you minimize the minimap. 
![animx](https://user-images.githubusercontent.com/3536496/63555564-45967d00-c4f6-11e9-98ed-6e7e5306c2b9.gif)
Make the highlight less obtrusive, and make other parts of the window look like there is glass there.
- [ ] I popped out the minimap window after changing resolution and it was missing.  Make sure to clamp the window to the screen edges on first-open so its always visible.

**Comment by SlayksWood** [comment]
@johnkslg 
Have some suggestions for improvement:
1. We don't need 2 buttons: Which one will be opened by hotkey? or 2 hotkey will be added? Or  hotkey will no at all?
![image](https://user-images.githubusercontent.com/45708377/63836291-f6cb6600-c981-11e9-8926-842d0d53f0b1.png)
We can add only one button. Another change we can add at opened map. For example near "Close/Hide" button we can add "Resize" button to swith from fullscreen map to windowed map.
![image](https://user-images.githubusercontent.com/45708377/63837062-6d1c9800-c983-11e9-8418-611aa91a0bc3.png)
2. I think you will not agree, but I still want to offer: Separate the concept of minimap and map.
Minimap is:
![image](https://user-images.githubusercontent.com/45708377/63837555-5aef2980-c984-11e9-9102-268855d8c0e2.png)
 Map is:
![image](https://user-images.githubusercontent.com/45708377/63837867-f2547c80-c984-11e9-9d39-a248c7b44266.png)
Why when we open Map, Minimap closes?
For me ideal will be so:
![image](https://user-images.githubusercontent.com/45708377/63837858-ebc60500-c984-11e9-8a6f-bcb9199d79d4.png)
At least it is necessary to remove the change in the UI when you open Map: #12971. 
May be it should be as:
![image](https://user-images.githubusercontent.com/45708377/63838458-0f3d7f80-c986-11e9-80db-8af54448b861.png)

**Comment by johnkslg** [comment]
> We don't need 2 buttons: Which one will be opened by hotkey? or 2 hotkey will be added? Or hotkey will no at all?

I'm imagining players will play as follows:
- They will always have the minimap visible somewhere on the screen: either popped out, or 'docked' in the bottom right.
- Occasionally, they will want to see a max size view, so they can get a really good look at something. This is true regardless of where they usually keep the minimap on the screen, and so we should make it easy to 'get a really good look, then revert to where I usually keep my minimap'.  Previously, you'd have to stretch out your popped out minimap to do it, *and* stretch it back to where it used to be.  Now you can just toggle full-screen.

The hotkey should be to toggle full-screen off and on.  We dont need a hot key for the pop-out/dock, thats more a setup stage where the player gets the screen looking how they like, then doesnt have to touch it.

**Comment by SlayksWood** [comment]
1. Let me give you an example of a hype game now - World of Warcraft Classic.
In WoW Classic, the Map works in much the same way you want to do: If you open it, it opens in full screen. But the Map in actual WoW hasn't behave like this. And many players installed the addon, because few people like that something takes up the full screen.
2. I'm not saying that one should not do so. I just ask you to add an extra feature. Maybe someone will like it. But for me it's uncomfortable how it plannes to work. I think I'm not alone. And I want to make it customizable so that every player can customize for themselves.
3. The minimap at bottom right is good. But its size can't be adjusted separately. The game has a very tightly bound interface. I can’t configure anything separately. Therefore, I can’t make a minimap comfortable for me. I play on scaling 75%. More precisely, I suppose I played. With new chats, a minimap, I will have to increase my interface  to use it. 
![image](https://user-images.githubusercontent.com/45708377/64586230-5b37ed80-d3a4-11e9-882e-760f5f5e16a1.png)
Therefore, discarding the map that was in 8.3.0 (not full screen) I will probably have to increase my interface.
4. Try the tutorial "World view" with such map. You constantly have to open the map not in full screen, i.e. use the mouse.
![image](https://user-images.githubusercontent.com/45708377/64586547-46a82500-d3a5-11e9-9722-179934511d77.png)
![image](https://user-images.githubusercontent.com/45708377/64586520-309a6480-d3a5-11e9-9647-f16c14c70c8b.png)

If people have more options, there will be more happy. You can do as you want, but I think it's need to add an alternative opportunity. If the player wants, he will change it.
It can be done as I described above. If not, at least add the ability to bind a non-full-screen map to the hotkey. (And leave the ability to remove the full-sized map from the hotkey)

**Comment by johnkslg** [comment]
@SlayksWood can you try out changes in next master and update suggestions into a new bug? So we can close this one out. Thanks!
