### ISSUE TITLE
Expandable popups

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#12979]
![image](https://user-images.githubusercontent.com/3536496/63817283-8294b200-c8f0-11e9-8e89-a172fa556713.png)

Make popups expand horizontally if desired, and use a scroll box when too long

**Comment by serpopov** [comment]
Don't do the tooltip clamp, I am handling it

**Comment by MarkZaytsev** [comment]
I made dialog to stretch to the longest line of the text. I don't think we need scroll with such settings anymore. Since stretching solves the issue of the tall text. 
One thing is bothering me, how long text can be? It seems there is no out-of-the-box solution to limit max width of the text element in unity canvas system.
But I assume we will not encounter such issue, so may be there is no need for extra work.
![Image)](https://user-images.githubusercontent.com/50739566/80569221-a7629b80-8a22-11ea-85b0-3e6163e35828.jpg)

**Comment by johnkslg** [comment]
It's likely we'll get lines that go past the width of the screen, we should cap line length at some reasonable number (x characters)

**Comment by MarkZaytsev** [comment]
Done

**Comment by SlayksWood** [comment]
Expandable box is good, but need to set minimum size. Skip tutorials seems not good now:
![image](https://user-images.githubusercontent.com/45708377/80944367-1577db80-8df2-11ea-9d42-a74646404cf5.png)
