### ISSUE TITLE
Information at Steam and SLG site about non-supported Familing Sharing

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13223]
#12797 
Duplicate issue. I will add the same comment there

I suggest to a tag on Steam that says "Requires agreement to a 3-rd party EULA: [ECO EULA] and in the EULA it says you only get one Eco account per Steam purchase. There could also be a tag that says "Requires 3rd Party Account: SLG Account"

_Originally posted by @WeaselDog in https://github.com/StrangeLoopGames/EcoIssues/issues/13222#issuecomment-536339543_

**Comment by Crafter213** [comment]
Family sharing is a great feature on steam. People can buy a game together, so they have to pay only half the amount (but play only half the time as well).

It would be better, if the issue about cloning the game’s license would be fixed and family sharing was allowed - instead of just killing it.

Most of the games on steam are fine with this feature. Please do not let a bug on our login/account system make Eco not support this.

**Comment by pamduncan** [comment]
That there is no family sharing is not a bug but is set that way for this game.  I think perhaps the problem is that you get one character to play on each server with your account (although you can have a SLG download or a Steam copy both attach to the same char).  So if a family member borrows your game and logs on then they go to a server that you have played on they are playing in your character.- there is no way for them to have their own.  Chars are based by the name that is authorized in the server and if you other family members do not have an Eco game they do not have authorization to create their own login or char.

This was happen when family share was on by mistake when Eco first released and server owners/admins were totally upset when people wanted there chars rolled back all the time because a family member came on and played and mess up their char and so on.  And people that owned the game complained because family sharing was turned on meant others could play the chars or play as them, and pretend o be them,  and get in trouble on the server and get banned ( you know little brothers).  That was when we found out that Family Share had be set on by mistake by steam.  The problem was fixed when steam made Eco a game that did not have family share.

Making it available again, even if a few want it and thing they can manage it okay with their group there are going to be a great many issues with people that it would not work well with and who do not want other playing their char.

Since there is no way to give you other chars for family members to create when they play your game like is an option in other games, this is why family share is not available.  i expect that they would have to make some major changes in the game, the server, the login process and the authorization server to allow for other chars and to find someway to protect the owner of the games char from being played by other members of the share.  The other issue would be how to give a family member authorization with a log when they did not won the game to have a separate char.

**Comment by Crafter213** [comment]
When playing offline there is not a single problem when using family sharing. Why not activate this in a first step?

When playing online, it should be possible for Eco to not only know the name which is authorized, but the name of the steam account playing as well. I mean, do you have the wrong name in chats of other family-shared games all the time?

You can configure which games to share on Steam. So there is no problem even if Eco was not able to fix that bug. Even if there was no way that family members can have different characters (I wonder how all the other games do this), people could just deactivate sharing this game for their little brother and other people enable it.

**Comment by D3nnis3n** [comment]
Actually the addition is wrong, Eco does NOT require an SLG account to be played and therefore no third party account. I'll add the EULA stuff, not the family sharing stuff, though. I don't see a reason why we should explicitly state you cannot use Eco for family sharing. Family sharing is not something every game would support or be mandatory, steam FAQ clearly states that not all games support that.
