### ISSUE TITLE
[Craft] Adding items to the projects is broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13269]
![изображение](https://user-images.githubusercontent.com/4980243/66325424-e965ac00-e92f-11e9-9a7a-329ebb8d3c70.png)
Also as i see, in some cases you cannot manyally add ingredients onto reciepe.

**Comment by SlayksWood** [comment]
1. Step to reproduce:
- add order
![image](https://user-images.githubusercontent.com/45708377/66376052-6ee06f00-e9b7-11e9-865b-265d374e826e.png)
- try to add 1 log to project (any ways without stockpile). For example I ty to add 1 Log with RMB:
![image](https://user-images.githubusercontent.com/45708377/66376691-dd71fc80-e9b8-11e9-8a26-84a47429d894.png)
- Bow project will break, No missing ingredient because this project doesn't need anything. I can't add logs and fibers to project with any ways.
![image](https://user-images.githubusercontent.com/45708377/66377105-90425a80-e9b9-11e9-92de-7a37046d59b6.png)
2. Missing ingredient refreshes incorrect.
![image](https://user-images.githubusercontent.com/45708377/66377411-37bf8d00-e9ba-11e9-8294-138cab2ce6b8.png)

**Comment by Hakuhonoo** [comment]
It seams to work this branch https://github.com/StrangeLoopGames/Eco/pull/5180
[video](https://www.dropbox.com/s/schd63qdxiousok/AddingResourcesToCraft.mp4?dl=0)

**Comment by beastyn** [comment]
still here

https://drive.google.com/file/d/14LMOqNAJqQVSAtA-pR254fgbuD04HJ7a/view?usp=sharing

**Comment by WeaselDog** [comment]
This issue combined with https://github.com/StrangeLoopGames/EcoIssues/issues/13668 is super frustrating. 

You lose all the resources & calories with no way I see to prevent it.

**Comment by elfl0rd** [comment]
Not fixed.
Start project
![20191127195759_1](https://user-images.githubusercontent.com/4980243/69744363-16c12000-1151-11ea-9990-5e17ba94b659.jpg)
wait
![20191127200105_1](https://user-images.githubusercontent.com/4980243/69744369-19bc1080-1151-11ea-8148-d210f2090b97.jpg)
restart game
"ingredients" broken.
![20191127200238_1](https://user-images.githubusercontent.com/4980243/69744400-26406900-1151-11ea-9365-dff554d5e586.jpg)

**Comment by mirasrael** [comment]
@elfl0rd isn't it different problem than described in original issue?

**Comment by elfl0rd** [comment]
Looks same, but in starting case it happens without restart.

**Comment by mirasrael** [comment]
When you say "restart" game do you mean exit/enter world or you assume server restart?

**Comment by elfl0rd** [comment]
i restarted singleplayer game :)
i think server restart

**Comment by mirasrael** [comment]
Ok. For me it seems like a completely different issue, because original issue happened when you add ingredients to started project, but the issue you reported happens due to wrong serialization/deserialization logic after server restart. It may have similar effect, but cause is different.

**Comment by beastyn** [comment]
Just,,, Ok... I will make the new one.. for you
