### ISSUE TITLE
Winning an election by majority doesn't seem to work

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1327]
Gave candidate 16 first place votes, and the other candidates no votes.
Election did not end. 
There were 4 candidates total.
https://gyazo.com/7690ebc356eb0b338ede6dfec24a8c7a

**Comment by MarjieAVolk** [comment]
So I found there's a line in the election resolver thing that doesn't allow an election to be valid if it's been running for less than an hour, so I'm guessing that's what you ran into.  I'm working now on providing an error message system for elections, because this sort of thing has been complained about a lot.
