### ISSUE TITLE
[master-preview] Civics: delete objects when table is recycled

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13298]
1. Create a map with some districts in Zoning office

![bandicam 2019-10-10 15-26-34-795](https://user-images.githubusercontent.com/27898520/66565307-9849f800-eb7b-11e9-92cf-394f5eb4c08a.jpg)

2. Pick up zoning office. The Map will be invalid.
![bandicam 2019-10-10 15-26-42-529](https://user-images.githubusercontent.com/27898520/66565320-9f710600-eb7b-11e9-8f17-e1f269223634.jpg)

3. Trash zoning ofice till its garbage.
![bandicam 2019-10-10 15-26-48-606](https://user-images.githubusercontent.com/27898520/66565340-ad268b80-eb7b-11e9-8e77-a6ed465fe159.jpg)

4. Now you have invalid map like... forever.
![bandicam 2019-10-10 15-28-52-591](https://user-images.githubusercontent.com/27898520/66565363-b4e63000-eb7b-11e9-91d9-d22af99fb3ff.jpg)

If table with some saved objects was garbaged all entities should be deleted and everything related should become invalid. For all objects ( atricles, elections and so on)

**Comment by elfl0rd** [comment]
also same for any way to destroy objects.
Smite (devtool), meteorite hit (in future) etc.

**Comment by johnkslg** [comment]
To solve this one:
- Add a 'OnPermanentDestroy ' function for items that's called when the item is permanently destroyed (by becoming garbage, by being smited, hit by meteor, etc).
- Make the OnPermanentDestroy for WorldObjectItem handle the destruction of its PersistentData member
- Change the IPersistentData class to store a reference to a new interface, instead of an object, IPersistentDataDetails or some such.
- Make that interface implement an OnPermanentDestroy function that will handle permanent removal of whatever it has.
- For Civics Objects, this should call SetState on all the relevant entries setting it to Removed (so its still visible, but just in permanent removed mode).
- For Mints, its less clear what will happen. This will mean that no more of the currency can ever be minted. I think thats fine, can just leave it as is with no response for OnPermanentDestroy

**Comment by Quadbro** [comment]
@olegshegai asked you in discord about this issue)
