### ISSUE TITLE
POST /datasets/get returning data, but value is always 0

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#1331]
Start a server,
use GET /datasets/generatetestdata

Then run any get query, like ["Plant", "Population", "Camas"]
https://gyazo.com/53a73cccf422cfddb81bd93e14608c2d

All values are 0

**Comment by MarjieAVolk** [comment]
I checked it out on my machine, and the values seem completely normal, not a 0 in sight.  Could it be because of your world generation settings?  I know you're generating tiny worlds sometimes.

I do see that it's sampling every 30 seconds instead of every 30 minutes as it used to, but that might be okay for testing still.
