### ISSUE TITLE
Many things un-highlightable after connect

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#13335]
Connected, tried to target this corn next to me, but it was very resistant.  It only highlighted if I flew around and got some weird specific angle.
![image](https://user-images.githubusercontent.com/3536496/66786732-4ca68f80-ee96-11e9-8c43-98a302378b04.png)

Seems to be related to initial connection.  Colliders hanging around from avatar creation blocking selection?  Something else?

**Comment by SlayksWood** [comment]
This problem is bigger. I don't see Anna (only the icon above her head) I don't see myself in 3d person view! I can't interact with anything.
![image](https://user-images.githubusercontent.com/45708377/66816925-94cfbb80-ef43-11e9-96f4-c0396c3f7681.png)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3728346/Player.log)

**Comment by SlayksWood** [comment]
I make separate issue with craft, which led to my consequences. But this troubles may connect with issue #13344

**Comment by beastyn** [comment]
didn't meet in last builds
