### ISSUE TITLE
[0.9.0 staging-1183] Wrong species in trigger Plant Seeds 

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13438]
Should be seeds. Now Animal, Plant, Tree or just a species choice is broken.
![image](https://user-images.githubusercontent.com/45708377/67548251-06f58c80-f70a-11e9-90e8-52bda29533d9.png)

**Comment by johnkslg** [comment]
Just added support to limit selections to tags
To implement this make a new trigger config specific to plantseeds
Follow example for the tool trigger config which allows limiting to tool selection
![image](https://user-images.githubusercontent.com/3536496/67707517-da46ac80-f977-11e9-9b3d-a4591973e8e9.png)

Change the event to specify the seed item instead of the seed species.

**Comment by olegshegai** [comment]
Outdated 
![image](https://user-images.githubusercontent.com/56091594/72219441-340e4a00-3557-11ea-9384-7a7c33095d07.png)
