### ISSUE TITLE
[0.9.0 staging-1186] Black Screen after load to world

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13448]
![image](https://user-images.githubusercontent.com/45708377/67631330-c763a780-f8a5-11e9-80f4-4fe4d592f4f5.png)
You can play only in one case: 
- start new world, enter world
![unknown (4)](https://user-images.githubusercontent.com/45708377/67631342-ee21de00-f8a5-11e9-8c46-69e603858ec3.png)
- press save. You can play, but after relog you have black screen again.

**Comment by gzatravkin** [comment]
After some investigation I see that it had missed AkSoundEngine.dll and AkWaapiClient.dll . Maybe it had some desync with SVN at moment of the build. It can be fixed by copying missed dlls to C:\Program Files (x86)\Steam\steamapps\common\Eco\Eco_Data\Plugins . 
This link contains them both (just in case you need it to be able make others tests) 
https://drive.google.com/open?id=1uBx-cTXuqEsUFop11e3HfEybuqo4Z4kn

When I did build locally I had not this problem. So I except it will be fixed at next build.

**Comment by SlayksWood** [comment]
fixed
![image](https://user-images.githubusercontent.com/45708377/67674727-53e99500-f98e-11e9-994a-84eb5d94b143.png)
@gzatravkin thank you
