### ISSUE TITLE
[0.9.0 staging-1206] Adding Calories to сraft

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#13488]
I wrote earlier and will repeat: We need the ability to add LOTS of calories at a time!
A few options for this:
1. Increase calorie intake. LMB = 500, Shift + LMB = 2500. This is the simplest solution.
2. Add Ctrl + LMB as adding max possibility calories.
Why should this be done? take simple example:
1. Go into the game and make me some high-level recipes on Research table. You nedd to click 60 times at one recipe with Shift+LMB.
![image](https://user-images.githubusercontent.com/45708377/67851392-6c3aea80-fb1b-11e9-937a-2a2b09c591c1.png)
2. Start project with 9999 Hewn Log and Add All Labor to it. Yes, people do so much Hewn Log and more.

**Comment by elfl0rd** [comment]
Agree, it is annoying.
But instead of multiple hotkeys i suggest "click and hold" mechanism with increasing adding value per time.
E.g. first 2 seconds holding button adds 100 calories per tick
next 3 seconds 250.
next times - 500.
(It's an example.)
And... for parties.
Gear button next of "work" clicking on it allow set adding value and adds it.
(E.g. just 1000 or something).

**Comment by SlayksWood** [comment]
If you added Ctrl+RMB you can change RMB and SHift+RMB some less.

**Comment by Hakuhonoo** [comment]
Ok, 100/500/full now

**Comment by beastyn** [comment]
Still 500-2500-full for me
![bandicam 2019-11-26 14-30-39-850](https://user-images.githubusercontent.com/27898520/69617023-66bcbb80-1059-11ea-9975-ed6444715649.jpg)

**Comment by Hakuhonoo** [comment]
Yeah, was my bad while merging. Fixed in https://github.com/StrangeLoopGames/Eco/pull/5299
