### ISSUE TITLE
After server running for hours, client gets disconnected and can't reconnect

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#13566]
Running debug server locally, client in unity.
No errors visible in output window, restarting client didn't help, only restarting server.

**Comment by mirasrael** [comment]
Hard to reproduce, so bug-fixing is complex.
So trying to get more details when it happens to me.
So far I found:
- Server continue to send packets to the client and connection on both ends has Connected status
- For some reason client receives packets with non-zero session id (0x2), which should only happens when same peer connected twice
- Client receives Discovery Response messages (but it should only happen in Connection UI).

**Comment by mirasrael** [comment]
I opened PR addressing this issue. It is hard to say if it really fix this or not, but fixed issue definitely may cause such behavior. So, please, if it happens after the fix let me know.
