### ISSUE TITLE
[0.9.0 staging-1240] In-game voting visualization glitch

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13616]
1. Make a law for an election (should have article for laws)
2. Make a ballot
3. Go to a ballot for voting for this law
4. Select No (1 for "Yes" and 0 for" No")
5. Press L
6. Choose legislation
7. See the color for the election process for the created law.
It should be red, but its green
Law 4 on the image
![unknown (22)](https://user-images.githubusercontent.com/27898520/68388386-531ce400-0182-11ea-83b0-2f216a6261de.png)

**Comment by olegshegai** [comment]
Can be closed according to this: https://github.com/StrangeLoopGames/EcoIssues/issues/13651#issuecomment-573886428

**Comment by SlayksWood** [comment]
Can't be closed because it doesn't say about voting from game.
![image](https://user-images.githubusercontent.com/45708377/75676146-b97dc300-5c99-11ea-87b3-94fed036e252.png)
This bar can show wrong info. Most of all it can happen when you just add new law. For example I make 'Law3'. Noone vote yet. I open Legislation and see that this bar has wrong information:
![image](https://user-images.githubusercontent.com/45708377/75676383-23966800-5c9a-11ea-954f-0505c1a06d90.png)

**Comment by beastyn** [comment]
Also, there is always "Voted No" even if you've voted "Yes"
