### ISSUE TITLE
0.9: specialities (professions) not hidden from filter list

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13682]
![изображение](https://user-images.githubusercontent.com/4980243/68808073-15382800-067a-11ea-9938-c11233d25f1d.png)

**Comment by WeaselDog** [comment]
The filter for laws it is a little worse because it includes talents, avatar objects, UI objects, dev items, and more things that should be hidden.

![ChatLog](https://user-images.githubusercontent.com/47330823/70688816-72b69900-1c67-11ea-9d22-5e4d19f9aec7.png)
![DevTool](https://user-images.githubusercontent.com/47330823/70688820-764a2000-1c67-11ea-8a4d-9adc506f6dc2.png)
