### ISSUE TITLE
[0.9.0 staging-1245] Civics: In a law's ui effects won't be updated

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13787]
1. Make a law
2. Choose trigger - Mint Currency
3. Choose Effect - Tax
![bandicam 2019-11-19 15-00-24-737](https://user-images.githubusercontent.com/27898520/69136897-8b56e780-0add-11ea-8b5d-aed767639d18.jpg)
4. Choose trigger - Completed Contract
![bandicam 2019-11-19 15-00-37-447](https://user-images.githubusercontent.com/27898520/69136938-9f9ae480-0add-11ea-9ee6-c29579621664.jpg)
5. Effect won't be updated
6. Choose effect - Tax
![bandicam 2019-11-19 15-00-45-987](https://user-images.githubusercontent.com/27898520/69136947-a3c70200-0add-11ea-9f95-18a9ff223c16.jpg)
7. Effect will be updated
Effect should be updated accordingly

PS for some triggers it was updated properly

**Comment by johnkslg** [comment]
The reason it doesnt change when you go from Mint Currency -> Completed Contract is because both of those have a 'Currency Amount' context value you can use, so it just leaves it be.

![image](https://user-images.githubusercontent.com/3536496/79376646-52496480-7f0f-11ea-9794-383f1374d085.png)
![image](https://user-images.githubusercontent.com/3536496/79376676-5c6b6300-7f0f-11ea-9f06-656351d5ab33.png)

**Comment by johnkslg** [comment]
Fixed the tooltips that weren't showing these properties though
