### ISSUE TITLE
[staging] Civics - Law: Timer is included in Action Comparisons

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13797]
Not a serious issue, but Timer is included as a condition for Action Count. Nothing happens when the law is triggered.

![TimerAction](https://user-images.githubusercontent.com/47330823/69195709-4df45900-0ae1-11ea-9bd9-76f288f2d2ec.png)

**Comment by johnkslg** [comment]
Recommend push

**Comment by tomsseisums** [comment]
Clarified with @WeaselDog during estimation meeting: the Timer action should be removed.

**Comment by Moritur** [comment]
Currently on develop "Action Count" can't be selected as value to compare in law's 'if' statement
![image](https://user-images.githubusercontent.com/44618240/118458493-1a58b600-b6fb-11eb-94bc-8fea02708a6e.png)
![image](https://user-images.githubusercontent.com/44618240/118458542-2a709580-b6fb-11eb-9eaa-bad8eff32ba4.png)

Am I missing something or was it removed?

**Comment by IcedForge** [comment]
This is the equivalent use as of right now, the flat "action" counter doesn't exist anymore, its tracked per instance or quantity inside the trigger itself for statistics.
![Screenshot_3](https://user-images.githubusercontent.com/24981362/118618118-94ed0880-b7c3-11eb-9ad7-07f74ef74e22.jpg)

I would like it to auto populate with Citizen ( in User ) and have the timer set as optional instead of mandatory as if you are only making a "forever" thing then you need to select "0 as value which is very unintuitive it would be better to have time as option if you want it ( sub selection? 0 by default )

**Comment by Moritur** [comment]
Using Citizen Statistics it's possible to select Citizen Timer or Global Timer as Action
![image](https://user-images.githubusercontent.com/44618240/118643804-4f3d3980-b7dd-11eb-8050-90d5c84916b3.png)

**Comment by WeaselDog** [comment]
This is the bug that it is possible to select this. It should not be there. We can push this though.

**Comment by Daniel-Magulado** [comment]
This is fixed on 10 Develop -714. Closing.
Omar is addressing John's nostat comment.
