### ISSUE TITLE
[staging] Civics: Wealth comparison does not include all accounts

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#13825]
I believe the intention of Wealth calculations is to count all accounts that are managed by the Citizen. Currently it only checks their Personal Account.

Bank accounts I created (besides Treasury):
![BankAccounts](https://user-images.githubusercontent.com/47330823/69276022-70927a80-0b92-11ea-85b7-a2a2bedbc26c.png)

Test law 1 doesn't prevent chat:
![Test1](https://user-images.githubusercontent.com/47330823/69276033-79834c00-0b92-11ea-9602-3d4435596a4a.png)

Test law 2 does prevent chat:
![Test2](https://user-images.githubusercontent.com/47330823/69276048-856f0e00-0b92-11ea-9fa1-6ce2402299bb.png)

**Comment by D3nnis3n** [comment]
Yep, it also needs to tax the other accounts when someone has no money on his main account anymore.

**Comment by D3nnis3n** [comment]
I'll try to find a senseful solution with John that we can actually do in time.

**Comment by johnkslg** [comment]
Alright guys I gave you the deluxe solution because I think you can do some cool stuff with this.

New advanced settings on bank accounts:
![image](https://user-images.githubusercontent.com/3536496/69378510-5e344180-0c63-11ea-871f-c15f83db64da.png)
![image](https://user-images.githubusercontent.com/3536496/69378536-68eed680-0c63-11ea-92d6-551b0b59ab34.png)

Can only be changed by Elected Title privilege:
![image](https://user-images.githubusercontent.com/3536496/69379486-69886c80-0c65-11ea-80be-3ad952328550.png)
![image](https://user-images.githubusercontent.com/3536496/69379541-815ff080-0c65-11ea-9a33-43723bcea7b9.png)

Tooltips:
![image](https://user-images.githubusercontent.com/3536496/69379898-3397b800-0c66-11ea-88cd-e68da52a1292.png)

Also introduced percent ownership when there are multiple owners. 
This respects groups (demos and titles):
![image](https://user-images.githubusercontent.com/3536496/69380165-b9b3fe80-0c66-11ea-98b1-dd322eb2e94f.png)
![image](https://user-images.githubusercontent.com/3536496/69380201-c6d0ed80-0c66-11ea-8a2a-0cb10a6e5666.png)

Wealth Calculation is affected by this.

Please give it a good run through!

**Comment by WeaselDog** [comment]
Wealth calculation is good! Still just experimenting with the Government Banking Privileges

**Comment by WeaselDog** [comment]
Works as expected with treasury and government accounts
