### ISSUE TITLE
Laws: Location conditions available for actions without location

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#13876]
I.e. for PolluteAir action (which doesn't implement `IPositionGameAction` it still allows to add `Location` related conditions).

![image](https://user-images.githubusercontent.com/475445/69527638-c9d92000-0f7d-11ea-95a3-8304699fd744.png)

**Comment by D3nnis3n** [comment]
Fix should be to make it possible, not removing the location. Pollution Districts and Non-Pollution districts are typical use.

**Comment by mirasrael** [comment]
For Air Pollution it doesn't make real difference where pollution happens, because it is global. And we can't use aggregating stats effectively for air pollution if they will have Location.

**Comment by D3nnis3n** [comment]
If course it does. Local air pollution causes local ground pollution. Its
also means of city zoning.

Alexander Bondarev <notifications@github.com> schrieb am Mo., 25. Nov.
2019, 11:55:

**Comment by mirasrael** [comment]
OK. 
You're right. It is second order reaction when rain happens in are with air pollution then it makes ground pollution.
We still may be fine if we will only restrict action in specified location, but won't allow to make historical queries for location (i.e. you can only allow to pollute air in specified district, but you can't deny to pollute air if user already performed some amount of pollution in specific area).
There also a problem with location restrictions for air pollution, because vehicles produces pollution. So if you deny to pollute in some area then as soon as vehicle enter the area it will stop working. And you won't be able to leave the area on vehicle.

**Comment by D3nnis3n** [comment]
The laws i plan actually are supposed to restrict it based on tables not on
cars. Is taxing for co2 amounts still possible even if we do not save data?
CO2 tax was very common when pollution actually was a Thing pre 8.0. Now
noone does it cause its not needed, but if 9.0 will have dangerous
pollutions again, we need effective measures to keep it down. For example
taxing outputted pollution based on amount. Otherwise there is little you
can actually do to regulate pollution.

Believe me more saved data and more lag is the last i want, but if
pollution is actually is actually a threat again that can even lead to a
underwater world, players must be given some effective Regulation Tools.
Everyone knows it wont work by common sense and agreements in most servers,
especially as Big ones as our officials.

Alexander Bondarev <notifications@github.com> schrieb am Mo., 25. Nov.
2019, 13:32:

**Comment by D3nnis3n** [comment]
Tax had to be done by craft tax for each single item pre 8.0. Very, very
exhausting. Thats why a real co2 tax would make stuff so much easier. Just
tax co2, bot each item that creates co2.

Dennis Scholz <scholzden@gmail.com> schrieb am Mo., 25. Nov. 2019, 13:37:

**Comment by johnkslg** [comment]
Youll be able to tax pollution yep.
For cars shutting off when you drive into non-pollution zone.. thats an interesting problem.  Servers would need to setup a buffer for that not to  happen.  I think we allow it!

**Comment by johnkslg** [comment]
Fixed

Not shown with 'timer' action
![image](https://user-images.githubusercontent.com/3536496/69594970-e3e12580-0fb2-11ea-92c2-b283b29128ba.png)

Shown with 'claim' action
![image](https://user-images.githubusercontent.com/3536496/69594994-f65b5f00-0fb2-11ea-896e-342e97ef0926.png)

**Comment by johnkslg** [comment]
Added to timer.
![image](https://user-images.githubusercontent.com/3536496/70084615-7a20d700-15c3-11ea-844d-29eca1f357c5.png)
![Uploading image.png…]()
