### ISSUE TITLE
[0.9.0 staging-1271] Civics: the law is breaking the game

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#13890]
1, Create district
2. Create a law like this one
![bandicam 2019-11-26 20-31-59-614](https://user-images.githubusercontent.com/27898520/69648330-e912a300-108c-11ea-908a-061d65a9907e.jpg)
3. Reset the client(completely)
4. Try to play.
Avatar won't move.
And also other funtionality will be broken.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/3892505/Player.log)
![bandicam 2019-11-26 20-39-17-648](https://user-images.githubusercontent.com/27898520/69648318-e4e68580-108c-11ea-879c-337fe6d51ecb.jpg)

**Comment by johnkslg** [comment]
This is an architectural problem with the view system: the server relies on the client unpackaging views in the exact order the server packaged them, however this may not always occur.

In this particular case, the law referencing the district is packaged on client first, and thus the data about the district is packed into the law.

However on the client, the district map registrar is unpackaged first, where the district's data is set to 'null' because it already piggy-backed across on the law.

Rather than fixing this by my meticulously ensuring that the unpackage order remains exactly the same, let's fix this architecturally.  When unpacking views, the client should be intelligent enough to perform it in any order. Ideally, it should also handle circular references of views, which I believe currently will simply break the client.  This could be achieved in a way similar to how reference serialization works, where it applies reference fixups in a post step.
