### ISSUE TITLE
0.9 Feedback: i really hate new research behavior.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#13954]
e.g.
you want to research butchery.
you prepared resources for it.
5 culinary research paper I and 5 additional "tier 1 research" (e.g. dendrology research paper I)
in storage, they're in the following order
5 culinary research paper I, 5 dendrology research paper I.
What happens if we press order for "Butchery Skill Book"?
Will it be created?
NO.
Because culinary research will go as a tier 1 research and project just stop... Due to "no culinary research paper I available."

This is probably true for many receipes, but in research, this is the behaviour that is most noticeable.

**Comment by elfl0rd** [comment]
In addition, in general, this behavior makes an extremely unbearable attempt to launch several research at once.
Simply because many papers have huge difference in costs.

**Comment by elfl0rd** [comment]
In addition, if you have resource that appropriate for both "resources" it looks as you can craft it.
But you cannot.
Like if you have 5 dendrology paper I for basic engineering
![20191202141549_1](https://user-images.githubusercontent.com/4980243/69955316-75e6b200-150e-11ea-9eb8-c137ec36b4b0.jpg)
Both counters filled, but you cannot craft.

**Comment by elfl0rd** [comment]
Side issue of new system, you cannot select "what you want to fill" in project.

**Comment by elfl0rd** [comment]
In addition, in 0.8 you totally should not need paper in researchs.
It looks funny, "research paper" without paper.
at my server, more than 30 players like this behavior.
No books, only scrools. And scrolls requie paper for crafting.
![2](https://user-images.githubusercontent.com/4980243/69956947-8a2cae00-1512-11ea-94f9-679c02fce7e1.png)
![1](https://user-images.githubusercontent.com/4980243/69956949-8ac54480-1512-11ea-88c0-10b4c26b9048.png)

**Comment by SlayksWood** [comment]
Very interesting in the game, but not very logically. Constantly research the "wheel"?
If you know how to make this job and want to share this knowledge with another player, why does he need the same ingredients?
I would prefer something like a profession to an inventor, or rather I would say an engineer, because the current engineer is more a specialized worker than an engineer. There is an original copy (skill book) and then if you have this book you can make copy (skill scroll) to learn it. To make skill scroll you need **many** papers) Of course, It's not for 0.9.0.
For 0.9.0 need to balance some specialties like Butchery, because you need Advanced Campfire Cooking now to research it.
And may be some balance in Labor and Ingredients for Research Papers.

**Comment by johnkslg** [comment]
This is indeed a problem. It should probably be tier-intelligent, so it will never use a high-tier ingredient for a low-tier ingredient without confirmation.  

Or we can change the research paper requirements, but I do like that older research papers play into new ones.

**Comment by WeaselDog** [comment]
One way to do this, we can make it always take static ingredients before it takes tagged ingredients. This will solve the above issue

**Comment by mirasrael** [comment]
Fixed already

**Comment by beastyn** [comment]
yeah, here too, so merg #14794
