### ISSUE TITLE
0.9 some convertation issues

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14019]
As i see, some objects change collision\position.
(world for convertation - https://github.com/StrangeLoopGames/EcoIssues/issues/13920)

![20191205100938_1](https://user-images.githubusercontent.com/4980243/70212242-f6442780-1747-11ea-96ce-f256d00fe58a.jpg)
![20191205100952_1](https://user-images.githubusercontent.com/4980243/70212244-f6442780-1747-11ea-8078-78496c82c6a4.jpg)
![20191205101003_1](https://user-images.githubusercontent.com/4980243/70212245-f6dcbe00-1747-11ea-8b47-33f2847e977b.jpg)
![20191205101103_1](https://user-images.githubusercontent.com/4980243/70212246-f6dcbe00-1747-11ea-8b44-8f0dd9d090aa.jpg)

e.g. table and assembly line.
Maybe more.

**Comment by elfl0rd** [comment]
After convertation you loose (client) access to all stores.
![20191205102239_1](https://user-images.githubusercontent.com/4980243/70212894-335ce980-1749-11ea-9601-cb19451c03bb.jpg)
![20191205102233_1](https://user-images.githubusercontent.com/4980243/70212895-335ce980-1749-11ea-846a-21734b7d12b4.jpg)

**Comment by Dmittry62** [comment]
I reproduced position change for tables. I couldn't reproduce authorization in stores issue but I encountered some other problems.

Store.
1. Goods for sale and for purchasing are absent.
2. Wrong currency (maybe it is because created currency was removed during migration).

Mint.
Currency is not crafted.

So I'll work on the following issues.
Position offset, missing store content, missing currency.
