### ISSUE TITLE
Birds float above workbench now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14014]
![image](https://user-images.githubusercontent.com/3536496/70179576-1fef4700-1693-11ea-9a3e-617a004ff683.png)
Looked so cool when they landed on the table before. 
May need to change the code to do a more specific collision test for where the bird lands for these cases.

**Comment by keegan-o** [comment]
I messed with the perch gameobject on the prefab-- they're a bit strange with the gizmos that appear but I think it's just a collider that represents possible spots for the birds to land. Originally I thought it was just a point, so that's why I didn't update it properly the first time. 
![image](https://user-images.githubusercontent.com/14983165/70258912-f3decf00-1741-11ea-9a65-8c6c927b1284.png)
