### ISSUE TITLE
[0.9.0 staging-1286] Building: need to check colliders for the ashlar blocks

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14023]
1. Take some ashlar blocks (any is fine)
2. Make two holes in the ground (1 block height is enough)
![bandicam 2019-12-05 15-48-21-658](https://user-images.githubusercontent.com/27898520/70228897-04f60300-1777-11ea-86de-5aaf9e5c88e8.jpg)
3. Place floor form there and one block up.
![bandicam 2019-12-05 15-48-43-016](https://user-images.githubusercontent.com/27898520/70228902-07f0f380-1777-11ea-949b-e9abf84e7c96.jpg)
4. Go close to the wall,
![bandicam 2019-12-05 15-49-23-719](https://user-images.githubusercontent.com/27898520/70228907-0a534d80-1777-11ea-8971-231e3232541d.jpg)
5. Try to move back with S
You wil stuck.
Pretty abboying thing.

**Comment by keegan-o** [comment]
I just checked the colliders and they're all cubes-- this is caused by the slope of the terrain going in towards the block, the gap between the floor block and the terrain that is. 
I will set this type to merge with the terrain but there are some big performance concerns with doing this with concave blocks we may have to look into. I might have to simplify the floor block's art.
