### ISSUE TITLE
[0.9.0 staging-1293] Civics: "Chop Tree" Action Count comparison for laws includes all swings

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14129]
The Chop Tree action count comparison includes all swings on trees, not just the final swing when the tree is felled. The comparison does not work as expected as a result.

The below law should check if someone has chopped a tree in the past 24 hours and then prevent chopping future tree. After the first swing they are prevented from logging even though the tree was not felled.
![StumpLaw](https://user-images.githubusercontent.com/47330823/70686494-5f083400-1c61-11ea-84f9-0e21f9e59d56.png)

Debug message:
![StumpLawDebug](https://user-images.githubusercontent.com/47330823/70686501-63345180-1c61-11ea-931e-f2f9e544fbd2.png)

**Comment by SlayksWood** [comment]
It's seems related with #13148

**Comment by johnkslg** [comment]
Fixed, now it only counts if a tree is felled in stats (chops aren't counted)
Same for stumps, only destruction counted in storage.

**Comment by beastyn** [comment]
Still counting each chop action.
Law is like this
![bandicam 2020-01-08 12-07-59-859](https://user-images.githubusercontent.com/27898520/71957415-883fc400-320f-11ea-92f9-4bb6f14c9cd9.jpg)
I was taxed for every hit (one birch was cutted).
![bandicam 2020-01-08 12-09-31-278](https://user-images.githubusercontent.com/27898520/71957585-f5ebf000-320f-11ea-9cd5-d67a78626d31.jpg)
![bandicam 2020-01-08 12-11-00-872](https://user-images.githubusercontent.com/27898520/71957587-f71d1d00-320f-11ea-96f2-051d1120f4bb.jpg)

For stump chopping is the same

**Comment by johnkslg** [comment]
The chop action happens still, but it only records it in stats if you fell the tree
In your law, you can add 'felled' to the conditions and it will work as you expect.

I left the chop action on trees because otherwise the law wont take effect till the tree starts to be felled. So you would chop the tree to completion, then on the final swing the law would take effect and prevent you, after youve wasted a bunch of calories and durability.  

Maybe I only register two chops, the first and the last.

**Comment by beastyn** [comment]
nope, thats fine. Just didn't check condition part. Thanks!
