### ISSUE TITLE
[0.9.0 staging-1293] Performance: Typing "/civics listdems" causes lag spike

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14130]
Typing /civics listdems on a large server will temporarily stall the client. A server with 350 users will lag for ~5 seconds as it recalculates each demographic for each user.

To replicate
- type /test makeusers, 350
- type /civics listdems

This should be addressed at the same time as https://github.com/StrangeLoopGames/EcoIssues/issues/11967. Instead of listing each user, maybe typing the command should only bring up the demographics so we can highlight the tooltips.

**Comment by johnkslg** [comment]
This is a pretty nasty one, the performance problem isn't on the server side but on the client chat processing side - it takes forever to translate the thousands of links that come through.  Do some profiling on the client to see where the problem is (I bet its in some regex search being performed on the text) and see how easy it is to address.   Follow up with me as you go please. Thanks!
