### ISSUE TITLE
[0.9.0 staging-1293] Civics: Laws for craft

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14141]
Need to cjeck crafting trigger.
1. I have a law like this
![bandicam 2019-12-13 15-53-10-239](https://user-images.githubusercontent.com/27898520/70795907-c7225b80-1dc2-11ea-806b-cfae8620fa13.jpg)
I suppose it should prevent charred food and charred papaya orders.
But I still can craft them.
![bandicam 2019-12-13 15-54-22-794](https://user-images.githubusercontent.com/27898520/70795979-ef11bf00-1dc2-11ea-8797-8c5580bdfa74.jpg)
![bandicam 2019-12-13 15-57-10-323](https://user-images.githubusercontent.com/27898520/70795993-f46f0980-1dc2-11ea-8a8c-40407d1ac3a8.jpg)

2. Why do we have two fields: matching item and Creating Product?
Also Creating Product won't show me all the products (eg. no Charred Animal).

**Comment by Sekor2600** [comment]
Charred Animal is no Product. (it is charredMeat) in the sense. It's just a name from the recipe. Charred food really does exist as food.
Don't know if that might matter

**Comment by johnkslg** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3536496/71697730-ce0f0f00-2d6d-11ea-9608-98c63c9dbcc6.png)

**Comment by WeaselDog** [comment]
The issue is adding the initial ingredients when creating a work order does not trigger the "Add to Work Order" action. Adding ingredients this way does not trigger any civic action at all.

If you try to add Papaya to an already started project, it will trigger the "Add to Work Order" and prevent you from adding Papaya. The "Add to Work Order" trigger should probably occur when adding ingredients by creating a work order.
