### ISSUE TITLE
USER ISSUE: Nutrition and housing Multipliers bug

### ISSUE THREAD

**Issue by Koksloks** [StrangeLoopGames/EcoIssues#14158]
**Version:** 0.8.3.0 beta

**Steps to Reproduce:**
Just wait in any area and the nutrition and housing multiplier will bug out and lower it self untill you eat something or remove furniture and place it back 

**Expected behavior:**
Just stay normal

**Actual behavior:**
XP multipliers lower for no reason 

**Do you have mods installed? Does issue happen when no mods are installed?:**
XP multipliers lower for no reason

**Comment by SlayksWood** [comment]
@Koksloks 
in 0.8.3 we have bug like #12780 with housing. But it seems fixed in 0.9.0. 
I don't understand what you mean about Nutrition bug. I assume that you eat bad or non-balance food and you lost multiplies. Yea, we have some fluctuations in nutrition multiplier, but it not big number. Can you provide more information?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
