### ISSUE TITLE
[0.9.0 staging-1298] Civics: Law sections that share a trigger only one activates

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#14153]
When two or more sections of the same law share a trigger, only the first section with that trigger is functional. 

In both of the following examples, only Section 1 is triggered by Chat Sent. This is true if Section 1 is executed or blocked. Section 3 works fine when using Tamp Road.

![MultiSectionLaw](https://user-images.githubusercontent.com/47330823/70933506-f74f4180-1ff0-11ea-8aca-504a1430cd85.png)
 
![MultiSectionLaw2](https://user-images.githubusercontent.com/47330823/70933512-fb7b5f00-1ff0-11ea-800f-ef1a15e3ac6d.png)

The ability to write laws this way is important because sometimes players want two condition checks that overlap. It is also simpler for some to read & write this way.

**Comment by johnkslg** [comment]
Thats because the first one 'prevents' the trigger from occurring, thus nothing else happens.
Not sure how else this should behave?  You could reorder these to get the desired behavior, or create if/then blocks within the conditions sections.
@beastyn @SlayksWood thoughts?

**Comment by WeaselDog** [comment]
In the first example, the first comparison returns false so chat is not prevented. In the second example there are no conditions, but only the first trigger functions.

If it is intended behavior, the easiest fix is to prevent people from writing laws with shared triggers. There is no problem writing laws in a way they don't share a trigger, but I can foresee many people wondering why their laws aren't working.

**Comment by johnkslg** [comment]
Good call, fixed!
![image](https://user-images.githubusercontent.com/3536496/71928133-c7a4dc80-314b-11ea-9182-295f03a9b59e.png)

![image](https://user-images.githubusercontent.com/3536496/71928105-ba87ed80-314b-11ea-9770-e96b255a40ca.png)

**Comment by SlayksWood** [comment]
For me after changes it works right. 
 - For example we have in law 4 section. 
1. False
2. False.
3. True.
4. True
![image](https://user-images.githubusercontent.com/45708377/71959936-eadf9280-3204-11ea-9f7a-0f6f3d56be5c.png)
I'm Admin with reputation=-970.
![image](https://user-images.githubusercontent.com/45708377/71960099-3bef8680-3205-11ea-8023-1439efe45250.png)
For me it should work as "else if". Law checkes 1 section, 2 section and then 3 section. 3 section is working at me and 4 section doesn't check.
Why should not 4 section be processed? Because if it will process You can build very big Laws in 1 Article. It isn't right. Second, You can't build Law with "else if" with different trigger.
But we have problems in UI, Because if I don't know how it should work I can't undestand it from UI.
- I can build this law with another way:
![image](https://user-images.githubusercontent.com/45708377/71960506-41999c00-3206-11ea-894a-56db5cf01c03.png)
And it will work like my first law. But if I need to change for example trigger in section 3 and 4, I can't build same law with second way.

**Сonclusion:** It works right for me, but may be need some changes in UI to explain how it works.
@WeaselDog @D3nnis3n 
What is your opinion?

**Comment by SlayksWood** [comment]
If you agree, you can close this issue.

**Comment by WeaselDog** [comment]
Everything you said is accurate. Only the first trigger that passes true is executed.  

I agree writing laws with shared triggers is not ideal, but the current system can still cause confusion for players new to law system. If it stays this way, there should be a change in UI so it is clear that how triggers function. Here are some examples that can cause issues.

Only Section 1 is executed:

- Section 1 - True
- Section 2 - True

Only Section 1 is executed:
- Section 1 - True
- Section 2 - False
- Section 3 - True

Only Section 2 is executed:

- Section 1 - False
- Section 2 - True
- Section 3 - True

This is an example of a law that can cause confusion. I know it is written sloppy, but it is not possible to get Section 3 to trigger. (You can also type False into the chat tag to return false for testing purposes)

![MultipleTriggerTest](https://user-images.githubusercontent.com/47330823/72025940-a668ec80-322e-11ea-9f82-504ebf05518a.png)

**Comment by beastyn** [comment]
Maybe we can expand law's logic with something like this:
- Do only the first true section. 
if (false) {don't do this}
if (true) (do this and stop)
 Actually, I didn't find any example for using such logic, so I don;t thibk we need this.
I prefer the old way with the independent sections. Like here
![bandicam 2020-01-09 14-28-54-694](https://user-images.githubusercontent.com/27898520/72055989-99f79900-32ed-11ea-9d98-f6c164c6166f.jpg)
 
We can limit sections though (max 5 sections  for example)
@D3nnis3n What do you think? Maybe I've mssed some example?

**Comment by WeaselDog** [comment]
Not sure if this is ready to close or not. There is still an issue of players not knowing that only the first true trigger passes. It is not a problem if this is the behavior, but it is not intuitive.

**Comment by beastyn** [comment]
yeah, @D3nnis3n is stiil needed here for consultation )

**Comment by D3nnis3n** [comment]
I generally think this should work as it allows better overview in laws and less complexity. Technically each Section is a new clause that should be checked, even if the trigger was already used in a different section.

I don't see it as an issue that needs to be fixed immediately, though. It's definately a nice to have, but not a must have, as it doesn't impede usage of features.

**Comment by johnkslg** [comment]
How about it will run ALL sections until it hits a 'prevent', then it will stop?

**Comment by WeaselDog** [comment]
That should work good, as long it just stops checking that trigger. For example, if the trigger is prevented, but the law has another section with an unrelated trigger, this should still go through.

**Comment by johnkslg** [comment]
Fixed in staging
