### ISSUE TITLE
[0.9.0 staging-1299] Missing Forms in some material.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14160]
- [x] Ashlar Gneiss: FloatStairsCorner, FloatStairsTurn, StairsCorner, StairsTurn.

- [x] Composite Cedar Lumber: Cube, FullWall, Floor, FlatRoof, Wall, CladWall, Window, DoubleWindow, WindowGrilles, WindowWall, Fense, SideFense, WallTrim, SlopeFlat, SlopeSide, SlopeCorner, SlopeTurn, SlopePoint, Column, Brace, UnderBrace, ThinColumn, Stairs, UnderStairs, FloatStairs, Ladder.

- [x] Composite Joshua Lumber: All Forms.

- [x] Composite Saquaro Lumber: All Forms.

- [x] For Hewn Log we have separate issue: #13391

 Mortared Basalt, Mortared Gneiss, Mortared Shale: No forms, No icon.
**[EDIT]** Keegan: These should be removed from the tech tree as the intention is to only allow building with these very hard (or un-workably soft and brittle, in shale's case) stones with the higher ashlar tier of tech.

- [x] Rename for Mortared Stone(and other same blocks) and for Hewn Log(and softwood and hardwood) Window Block to WindowGrilles:
![image](https://user-images.githubusercontent.com/45708377/70981637-9134ee00-20c6-11ea-845d-6464ff18c1fa.png)

**Comment by keegan-o** [comment]
Parts 1 - 4 fixed in staging

**Comment by keegan-o** [comment]
Missing mortared stones are a misscommunication with tech tree, those are intended to not be available-- those rocks will require higher tier tables to build with, except that we will eventually add shale roofs at the same tier of mortared stone.

Since fixing that and the other re-naming things are lower priority (but they're in the works, don't worry, I'm working with Sekoris on them), lowering priority to medium.

**Comment by keegan-o** [comment]
Renamed the windows in the blocksets, and there is a PR from sekoris with the window name change in the tech tree and the other hewn log issues.

**Comment by keegan-o** [comment]
Should be all good now in staging.
