### ISSUE TITLE
[0.9.0 staging-1299] Missing model or wrong model in some blocks.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14161]
Missing model: Cooper Bar, Crushed Slag, Crushed Stone, Gold Bar. 
Wrong model: Slag. It looks like Crushed Slag:
![image](https://user-images.githubusercontent.com/45708377/70983296-8c256e00-20c9-11ea-81e0-7f45297fadc2.png)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/73220164-afa0f700-4112-11ea-9385-264b4992ebe4.png)
This is what the metal products names should be for 9.0, there should be no 'copper bar' or 'gold bar'. That may have something to do with it-- recipes may need to be updated. I will check the blocksets though to make sure we have these accounted for:
Copper Ingot
Gold Ingot
Iron Ingot
Steel Bar
Copper Cathode

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/73500411-6a313380-4377-11ea-8d66-c98959f4842e.png)
I fixed everything, but for crushed slag we need a tech tree change because I realized it should be a stacked rock block, not a natural terrain style rock.
Now ready in the blocksets are:
SlagStacked1
SlagStacked2
SlagStacked3
SlagStacked4

**Comment by keegan-o** [comment]
assigning sekoris since I told him in chat about it

**Comment by keegan-o** [comment]
closing this actually because there is still a fixed 'slag' block as well so nothing will be broken, even before the switch to stacked slag.
