### ISSUE TITLE
[0.9.0 staging-1303] Ashlar window block has wrong collider after connect with same block.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14187]
Ashlar window block has 2 ledge and you can easy use it for running.
![image](https://user-images.githubusercontent.com/45708377/71170929-91bbb900-226d-11ea-93a8-d7278472dd71.png)
But when you build window from it you still have this ledge(where red line):
![image](https://user-images.githubusercontent.com/45708377/71171030-d7788180-226d-11ea-90bf-46c30bf42532.png)
And you can use it:
https://drive.google.com/file/d/19yG8BS-Nz_R2nun5wuf4n7rUiEDXG_xQ/view?usp=sharing

**Comment by StanKryvenko** [comment]
Also there is a problem with collider
![image](https://user-images.githubusercontent.com/10034044/80193109-76f5b880-8642-11ea-89d7-d7163a81aa3f.png)
![image](https://user-images.githubusercontent.com/10034044/80193401-ea97c580-8642-11ea-90d9-e8357988a04e.png)
It has a slope area instead of rectangle and slope
Same thing related to glasses collider, it's just very thin:
![image](https://user-images.githubusercontent.com/10034044/80193463-0b601b00-8643-11ea-993f-92e41211082f.png)
![image](https://user-images.githubusercontent.com/10034044/80193475-0ef3a200-8643-11ea-8e75-554f46614ec6.png)

**Comment by keegan-o** [comment]
fixed in staging
