### ISSUE TITLE
Add missing objects (or remove them from the tech tree)

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14203]
Missing following objects: LargeHangingWoodSignObject, LargeStandingWoodSignObject, SmallHangingWoodSignObject, SmallStandingWoodSignObject

**Comment by Sekor2600** [comment]
Plz do not remove @keegan-o woodsign is used for the other signs as parent recipe. Fix incoming that is no longer craft able with selectionwindow

**Comment by keegan-o** [comment]
So is the real problem here then the fact that parent recipe items send off errors about not existing, when they shouldn't because they shouldn't be real items? (things like the 'Axe', 'Hammer', etc are other examples which do have real items but really shouldn't since they are just more things to maintain for no reason since they are not real in-game items)

**Comment by SlayksWood** [comment]
I can craft it, but can't place it:
![image](https://user-images.githubusercontent.com/45708377/79840524-af856000-83be-11ea-89df-33194f81c8c5.png)

**Comment by WeaselDog** [comment]
It was fixed in a follow up PR. It is now not craftable.
