### ISSUE TITLE
Deed/Land Claim Glitch

### ISSUE THREAD

**Issue by Kristoffer3293** [StrangeLoopGames/EcoIssues#1420]
Pam suggested I post this here to get attention to the issue. I'm always logged in to the ECO Discord server if you need anything else from me. 

[Bug Report](http://ecoforum.strangeloopgames.com:4567/topic/2293/deed-and-claimed-land-glitch)

**Comment by MarjieAVolk** [comment]
"Pam suggested that I try the admin command /claim. When I did it said you already own this. So I tried /unclaim and it said this is already public. Clicking the same commands on the deed itself gave the same results."

**Comment by MarjieAVolk** [comment]
I'm guessing that this is all misunderstanding.  You were using Construction posts instead of Property Claim posts, so you couldn't see your property and you couldn't claim property.  I don't believe that there currently is a /claim command (maybe there was in the release you are playing?  I couldn't find that), but the Deed "Unclaim Current Plot" and "Claim Deed" buttons are not opposites of each other.  Claiming the deed claims the entire property attached to the deed for yourself.  It does not affect the specific plot you are standing on or attempt to claim more property.  You already owned the deed, so claiming it did nothing.  Unclaiming the current plot does unclaim the plot you are currently standing on.  If you are standing on an unowned plot and holding your own deed, it is correct behavior for both the "Unclaim Current Plot" and "Claim Deed" buttons to do nothing.  Presumably you couldn't claim more land because you didn't have property claim posts.  Get some Property Claim Posts and it should become more clear.  Maybe we should make the difference between the types of posts more clear.

If you are still having problems, feel free to reopen the bug!
