### ISSUE TITLE
Incorrect room definition near Zero Point (volume increase and tier decrease)

### ISSUE THREAD

**Issue by Talzaroff** [StrangeLoopGames/EcoIssues#14233]
**Version:** 0.8.3.2 beta

**Steps to Reproduce:**
1. Make a room with all Tier 1 materials (Mortared Stone)
2. Make sure the room has "Tier: 1" in the bottom right.
3. Place a Mortared Stone stair block inside the room.

**Expected behavior:**
The room should remain all Tier 1, since the added block is still Tier 1

**Actual behavior:**
Instead, the room value drops to 0.98 (depending on the room volume of course).

**Do you have mods installed? Does issue happen when no mods are installed?:**
Not using any mods.

**Comment by Fungiscrusher84** [comment]
It's not happening with hewn logs, so it is probably just a glitch with the mortared stone.

**Comment by SlayksWood** [comment]
Can't reproduce:
![bandicam_2019-12-26_10-45-35-701](https://user-images.githubusercontent.com/45708377/71460260-33865d00-27bc-11ea-9d25-c10e3cedade1.jpg)
I assume you have one mistake after Room corners fixes. If you build stairs You need to add blocks in positions 1,2,3:
![image](https://user-images.githubusercontent.com/45708377/71459982-01283000-27bb-11ea-9994-5c153bd13113.png)
If your problem is not solved, then provide:
1. Save file with room coordinates.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
or
2. Server name (if the server is not public then ID) and room coordinates.
Also provide a couple of screenshots of the room.

**Comment by Talzaroff** [comment]
Save file: https://drive.google.com/open?id=1iIV9y7SlwR4--8-ojtswLHZo8LYBEqvX
Room coordinates are visible in the screenshots below, it's the Kitchen room of the stone dwelling at (196,63,1). The screenshots also clearly illustrate the issue. 
The extra information you provided is helpful, but not applicable in this situation. I don't only have blocks at your numbers 1, 2 and 3, but also below numbers 2 and three. I'm really curious if you can reproduce the issue with my saved game. It's a Steam Eco Server game file (not sure if that matters, but just for extra information).

![Tier part 1](https://user-images.githubusercontent.com/17851498/71477936-38afd000-27ed-11ea-8142-8624153f8736.png)
Room value before placing a block inside.
![Tier part 2](https://user-images.githubusercontent.com/17851498/71477939-3d748400-27ed-11ea-811f-072dd7a05967.png)
And after placing the Mortared Stone Stairs...

**Comment by SlayksWood** [comment]
This doesn't happen due to stairs. If I place another block, I will get the same effect:
![image](https://user-images.githubusercontent.com/45708377/71504062-ec19d280-2888-11ea-91d7-9075e829eb27.png)
But I found interesting bug and will investigate this in 0.9.0. This is due to incorrect room calculation.
If you pick up, place mortared stone some times so you can get room with volume=193 instead 192:
![image](https://user-images.githubusercontent.com/45708377/71504264-d2c55600-2889-11ea-89ad-644ace07b06e.png)
Thank you for report.

**Comment by Talzaroff** [comment]
You're welcome! Good luck investigating, and thank you for your friendly and helpful comments.

**Comment by Conchipedia** [comment]
someone was having a problem with Lumber and a perfect tier 2 room, they rebuilt room and did all sort of things and couldn't get it to a perfect Tier 2 room, then removed the **Lumber Stairs** and it went to tier 2

**Comment by SlayksWood** [comment]
#18093
> This has been a tricky one to duplicate, but it looks like when two sets of stairs occupy the same room and are placed above each other in a shared stairwell, they lower the tier value of rooms they lead to. In the pictures attached, there are two stacked staircases going between three floors. The middle level is isolated behind a wall, while the stairs on the first and third floor are not. This causes the tier level of the first and third floor to drop below the expected number (2.0 in this case). The only way I found to correct for this was to either wall up the stairwell on all three floors (sacrificing room volume) or placing another block directly under each stair block (I used lumber fence pieces since I could still walk under them). This fixes the tier value of the room ABOVE the stairs, but not the room underneath them. I've attached four screenshots to help illustrate. Floor 1 with an open stair case leading down (below 2.0), the stairwell itself (also below 2.0), the second floor, which is correct because it is separated by a wall, and the third floor (also below 2.0). To be clear, deleting the stairs and sealing the floors does remove the issue and restore the room tier to 2.0, so the issue appears to be with the stair blocks themselves. I have been able to duplicate the issue with Hewn Stairs, Brick Stairs, and Lumber Stairs in both the latest version of 0.8.3 and the latest version of the 0.9 playtest.
> 
> ![floor 2 stairwell](https://user-images.githubusercontent.com/22803114/92507093-723a3700-f1d4-11ea-9f30-21944613517a.jpg)
> ![floor 2](https://user-images.githubusercontent.com/22803114/92507097-736b6400-f1d4-11ea-96fe-21fdd4901aa7.jpg)
> ![floor 3](https://user-images.githubusercontent.com/22803114/92507099-736b6400-f1d4-11ea-8939-0ff9e607a33a.jpg)
> ![floor 1](https://user-images.githubusercontent.com/22803114/92507101-749c9100-f1d4-11ea-9d96-2bdf9f7aca2d.jpg)

> @JustinGianelloni Thank you for the report. Place 2 block here:
> ![image](https://user-images.githubusercontent.com/45708377/92555993-8718d800-f271-11ea-93ce-e776cff26447.png)
> And maybe you should add 3rd block too.
> Did this solve your problem?

> Adding blocks to those locations does not resolve the issue. Adding blocks in the same location to the staircase above it, however, does correct the tier level for the third floor, but not the stairwell itself (inconsequential) or the first floor (pictured).
> 
> Also, is needing to place a block under stairs within a room expected behavior? This only seems to be necessary when there are two staircases stacked (although there may be some other edge cases), so the behavior is not consistent.

**Comment by SlayksWood** [comment]
Step to reproduce:
- build house on zero point:
![image](https://user-images.githubusercontent.com/45708377/100227293-f8dbf600-2f31-11eb-8544-cc99eed3559b.png)

- place block on 719(max coordinate):
![image](https://user-images.githubusercontent.com/45708377/100227302-fd081380-2f31-11eb-99d2-3d29c9b2f5d4.png)

- seems it calculates adjacent blocks through the zero coordinate as empty.
Not immediately noticed this( , because player have a rather non-standard world 0.71 km.
