### ISSUE TITLE
Right-clicking on a campfire while carrying logs adds logs to inventory, not fuel

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1427]
Seems like it would make more sense to add it straight to the fuel slot if there's room, no?

**Comment by MGrand3** [comment]
Reference: http://ecoforum.strangeloopgames.com/topic/2318/unable-to-add-logs-to-campfire

**Comment by pamduncan** [comment]
Just my two sense but its a tricky one.  Since in every other table it would add it to storage not fuel I think people would expect to go in storage not fuel; plus if you add it to fuel it would immediately turn on the fire whether you were cooking or not.  For me I would rather it went in storage and then i could move it to fuel when I was ready to turn the campfire 'on'.

**Comment by metachronism** [comment]
5.6 crafting tables will no longer have inventories, so deprecating this
