### ISSUE TITLE
Players on opposite sides of world borders do not render.

### ISSUE THREAD

**Issue by MGrand3** [StrangeLoopGames/EcoIssues#1429]
In 5.5.4, if two players stand on opposite sides of the world border they cannot see each other. ~Loaded buildings (and possibly also world objects) seem to show fine, but players do not.~ 

Placed blocks render fine. World objects seem to render after you're been near them and loaded them, unsure how unloading works. Relogging means you cannot see world objects on the other side of the border until you cross it again to load them.

I'll try get some testing done with another player.

EDIT: Reference: http://ecoforum.strangeloopgames.com/topic/2316/cant-see-each-other/8

**Comment by d4nlo3008** [comment]
When crossing the border 0/0, buildings, players and structures like the woodcart does not render properly and this things disappear.

We need a soon fix for that because almost everytime you're loosing your needed stuff (like the woodcart). Cant work now and losing time because of this bug.

kind regards,

a players, who loves eco

**Comment by metachronism** [comment]
fixed
