### ISSUE TITLE
[0.9.0 staging-1341] Workparty does not use the right amount

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#14420]
While creating a workparty user cannot change the work section. automatically it is filled but with wrong amount of ressouces:
![image](https://user-images.githubusercontent.com/47274045/72608584-47d4fa00-3923-11ea-895a-817f31dbb748.png)
While the amount of total calories is right (total work), the amount to add of ressouces is only the current outstanding next bunch of ressources:
![image](https://user-images.githubusercontent.com/47274045/72608662-823e9700-3923-11ea-83ae-86b06a203d39.png)
for the workparty as well the total amount of the needed ressources should be covered.

Furhter issue, if you add a new line of work, all is been deleted and an empty notification box with only OK button comes up. 

Recommendation: By default the WorkParty collects all open crafting projects into one party. You have to manually delete all other craft projects to have only one of your current running Projects as a party. I would recommend to have only one project per party default and other can be added manually. I would assume player expectation is this way.

**Comment by Alteraner** [comment]
Just was thinking a secound time about it, maybe the issue is not realy with the workparty, more with the crafting. as it acutally reports only 2 logs are missing, but this is not correct as this two are only for the next craft but not for the whole project. Calories are calculated right.
I assume, fix this and use the complete amount of missing ressources would although fix the workparty amount issue.

**Comment by Alteraner** [comment]
Okay, sorry, but while thinking about that issue, it becomes more and more complex with further testing.
What i like the new way, that tables only collect ressources for the next step and you are not able to "store" tons or ressources in an running 9999 project. Therefore the table collects only next step needed ressources like here shown in the screenshot with 2 next logs.
But this makes it more complex with workpartys as someone who is not the owner of the claim (the owner can easily link a storage and ressources will be added automatically step by step). Other players can only drop the next "2" logs directly into the table. Or he link a storage from a vehicle arround the table. So he need to keep the vehicle around the table till the job is finished, otherwise his provided ressources are not counted.
Actually i assume the trigger who has provided ressources from linked storage is based on the owner of that storage. i need to test further on this.
Beside this behavior which make sense from my side but will be hard to explain in the ecopedia for non expirianced users, the total amount of missing ressources needs to be adopted in the crafting project rather in the workparty as after (in this case) the two logs has been provided this part of the Workparty is marked as complete even the project is still pending further ressources.

**Comment by SlayksWood** [comment]
We need to wait for full craft changings to complete workparty.

**Comment by johnkslg** [comment]
Thanks @Alteraner will take a look. If you're on Discord add me @johnk

**Comment by johnk** [comment]
🤷🏼‍♂️

**Comment by johnkslg** [comment]
Depends on work party refactor from @mirasrael 

also, hi other johnk!

**Comment by mirasrael** [comment]
@johnkslg I don't think it may be solved in good way. As @Alteraner said you can't add resources directly to the order behind currently missing resources, because it only may consume resources for single iteration. If you will count resources added to linked stockpile then there no guarantee these resources won't be used by other order or picked up by player. 

Resource allocation may be a solution, but this concept is very hard both for players and for technical implementation.

Just one sample:
You added allocated resources to work order.
- Now you shouldn't be able to move or relocate these resources, because it will break allocation.
- You also can't unlink Stockpile with these resources, because it will break allocation.
- You can't break Stockpile by removing blocks below it, because it will break allocation.
- You can't sell these items, because it will break allocation.
- You can't add items to stack of allocated items, because it will mess up allocation.
etc.

So my suggestion is for 9.0 remove resource part from Work Party and only use them for Labor. We can return to this problem after 9.0.

**Comment by johnkslg** [comment]
I wouldn't remove resources for work parties, even if it can only handle a single iteration, because things like skill books still benefit.

The change that causes issues is: resources can only be taken one iteration at a time, but allocation is not implemented. If we remove this feature until allocation is implemented, then all will work as expected (and the infinite storage in a running work order will continue to be an exploit for awhile).

For the future, I think allocation will be a good solution. Then when you add resources to storage, it can detect the work party is running, allocate those resources to that order, and give you credit.  Allocated resources will be then 'locked' to that use and no other, unless the owner breaks the link. 

**Alternative**
Another option before we add allocation:  we continue to make work orders take up a single order, but we make the 'missing ingredients' display look at all connected inventories and count those items too (that number may go up and down, of course, but we handle that).
And then on the work party, it detects if you add to a storage with a needy work party attached, and allocates your addition to that.  (you'll run into weird corner cases where there are multiple work parties that could pull from the storage, and we can just pick one arbitrarily). 

I think this is the best option: keeps the 'take resources for only one iteration' feature, allows the work order display to show whats missing considering storage, and allows work parties to function.  Corner cases when you have multiple work orders/work parties will happen but we can reduce their impact in various ways, and once we add allocation remove it entirely.

**Comment by mirasrael** [comment]
@johnkslg 
I think best option for now to count separately ingredients added to order automatically and added explicitly. Because Work Party has fixed reward you can't move it back and forth, so instead when you create a work party it will count only resources already added to order as contributed.
Then you can move pack of resources on the order and if any missing then they will be added to work order directly, but other will be just placed to order linked inventory (if available). Then these resources will be counted as supplied for the order.
If these resources which was added to the order then will be contributed by another order or manually removed then work order may be unfinished, but at least enough resources will be added and you can paid for that resources. To avoid cross using resources you can just setup separate storage for work party craft.
It will be much easier to track, more predictable and won't require expensive inventory scans.

**Comment by johnkslg** [comment]
Works for me. That allows multiple iterations in work parties yes?

In this solution, work parties should deduct any 'auto added from storage' resources from the total, and any completed work order should trigger work party completion of that order.

**Comment by mirasrael** [comment]
Yes, it will work for multiple iterations.
When resources going to next work order iteration it will first subtract them from provided resources and if not enough, but they can be obtained from storage then it will subtract extra resources from work party.

I.e. you need 20 Wood and 10 Stone.
Craft iteration needs 2 Wood and 1 Stone.
Then:
- Work Party member 1 added 10 Wood.
- for first iteration it will get 2 Wood and 1 Stone, reducing added Wood by 2 (8 Wood) and reducing expected Stone by 1 (9 Stone). Now: 8 Wood added, 10 Wood and 9 Stone expected.
- for second iteration it will get another 2 Wood and 1 Stone. Now: 6 Wood added, 10 Wood and 8 Stone expected;
- Work Party member 2 trying to add 10 Stone to Work Order, but because only 8 is needed it will accept 8 and leave him with 2 Stone. Now: 6 Wood and 8 Stone added. 10 Wood expected.
- for 3rd iteration it will get another 2 Wood from added and because now we have added Stone it will get it also from added. So now: 4 Wood and 7 Stone added. 10 Wood expected.
etc.

So work party member 1 and work party member 2 will be rewarded for 10 Wood and 8 Stone, all other resources will be counted as your own.

**Comment by johnkslg** [comment]
Sounds good! 🎉
