### ISSUE TITLE
Hosted Worlds Review

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14548]
![image](https://user-images.githubusercontent.com/3536496/73403943-646b1d80-42a5-11ea-95a9-8c20aa729c26.png)
- [x] This dual display of the same data here is confusing. Let's show only the the top panel, the bottom shouldn't be shown at all.   Notably, the bottom panel has 'renew' buttons - everything should auto-renew, and you shouldnt be able to individually choose which parts of your account renew or not (they all renew as a group).  
- [x] I have 2 citizen accounts but no hosted world accounts, that should be impossible.
- [x] Add text above explaining how subscriptions work.  IE:
Each 'Hosted World' in your subscription will be hosted online and accessible 24/7, allowing up to X simultaneous users.  
Each 'Citizen Account' in your subscription allows one player to join on your hosted world without owning Eco. 
Subscriptions are charged monthly on the 1st, with changes being pro-rated for the remaining month.

![image](https://user-images.githubusercontent.com/3536496/73404384-45b95680-42a6-11ea-9604-57da90f2687d.png)
- [x] Typo, should be 'requires'

![image](https://user-images.githubusercontent.com/3536496/73404408-52d64580-42a6-11ea-84e4-19aad29789cc.png)
- [x] What does 'Reset Citizen' mean? Add a hover tooltip question mark or something on the header text that explains it.  

- [x] What is 'link account'? Does that link to an existing Eco account? Does it verify the account exists? Inform the user if it doesn't?   What does linking do?  Seems like we shouldnt have that at all, Citizen accounts should be light weight with all config done by the owner, nothing even available to the citizen themselves.

![image](https://user-images.githubusercontent.com/3536496/73404493-7ac5a900-42a6-11ea-8e24-388c8872b666.png)
- [x] On my account it says I have 0 worlds and 2 citizens, but here there are 6 citizens listed and 1 world

**Comment by rainfarmer** [comment]
@johnkslg 
**"This dual display of the same data here is confusing. Let's show only the the top panel, the bottom shouldn't be shown at all. Notably, the bottom panel has 'renew' buttons - everything should auto-renew, and you shouldnt be able to individually choose which parts of your account renew or not (they all renew as a group)."**
Some say renew, those are set to expire. 
Some say remove, as in teacher can remove that subscription.
The idea is that they may want to downsize how many citizens or worlds they buy. say they had 2 worlds and 60 citizens for last semester and need 1 world with 28 citizens for next.
If they can only remove the entire subscription. They would have to wait a month for it to expire, then buy again what they want.

 **I have 2 citizen accounts but no hosted world accounts, that should be impossible**
This supports students buying their own citizen accounts and linking it to the teacher. a requested feature by a school. Also supports self-hosted worlds.

**What is 'link account'? Does that link to an existing Eco account? Does it verify the account exists? Inform the user if it doesn't? What does linking do? Seems like we shouldnt have that at all, Citizen accounts should be light weight with all config done by the owner, nothing even available to the citizen themselves.**
This is to support students buying their own account and linking to a teachers account. giving the teacher control of the citizen. i can add a tool tip. i can put this in a more hidden drop down options for citizens.

**On my account it says I have 0 worlds and 2 citizens, but here there are 6 citizens listed and 1 world**
This is because the world and 4 citizens are marked as free, so they dont have a subscription associated with them. this is so they dont expire and we can use them for indefinite testing. Teachers wont usually see that. unless they have free items.

**Comment by johnkslg** [comment]
Re renew:
How about when you attempt to downsize worlds or citizens, it then pops up a window with a selector for which ones will expire?  So it doesnt show until you downsize. 

Re buying your own citizen and linking to someone else's account:  I'm not sure about this. The idea with citizen accounts is that they are permanently linked to a single hosted world. If they can be applied to any hosted world, then they become a little different.    Perhaps we dont allow this, and if teachers want it the students just have to buy the game. The feature adds a lot of complexity.

**Comment by johnkslg** [comment]
Some more:
![image](https://user-images.githubusercontent.com/3536496/74096949-9dcc3600-4aba-11ea-99c6-f6651ffb50cd.png)
![image](https://user-images.githubusercontent.com/3536496/74096954-aa508e80-4aba-11ea-9f71-9800de25f99c.png)
- [ ] I was able to choose 'Select World' and it stuck

![image](https://user-images.githubusercontent.com/3536496/74096959-be948b80-4aba-11ea-8958-68da4f37cd7d.png)
- [ ] Can this just be displayed as text beneath citizen accounts? Also need to explain how a citizen account logs in (they just add the citizen name and password?)

**Comment by rainfarmer** [comment]
updated requested changes.

For " I was able to choose 'Select World' and it stuck"
This is normal behavior for drop down menus. 
It would require some special code to cancel the behavior. might not be worth the effort?
