### ISSUE TITLE
Block placement: Weird dead zone

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#14555]
When trying to place a block next to a wall, you can get a weird dead-zone area when the block cursor wont appear to place a block.

![image](https://user-images.githubusercontent.com/431728/73431579-7a074280-438c-11ea-8c96-c51f50d6f5d0.png)

Robert was showing me the problem in unity, and in his case the block cursor didn't occur when close to the wall, but in the latest version it's appearing on top.

**Comment by MazonDel** [comment]
Video Showing Current State: https://drive.google.com/file/d/12uoyIJs8NNhBbPKbacEgYhHRoKN6gDHI/view?usp=sharing

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 develop 175

Issue: There's a certain area where if you point your mouse icon while holding a block, it appears that there's no place to put the block down.

Repro:
1. Place a Wall type block. For example, /give brick, hold a hammer, press and hold F and then select Wall, and then place it on solid ground.
2. Try to place another next to it without changing the type or shape of the block selected. Leave it at Wall type.
3. Observe the area where you placed the first wall down and hover your mouse to it.
4. Try to place another Wall type block next to the Wall block you already placed.
5. Observe, dead area issue as stated in this ticket.


Video Repro:
https://images.zenhubusercontent.com/47210472/7bde5e52-7cc9-454d-bbf2-258b73e47b6d/2021_02_04_04_46_01_trim.mp4 


Feedback: This could be a natural occurrence since Wall type blocks are still basically blocks and due to their thinner appearance, player's assume that you can simply point next to it and place a block. The issue is most noticeable if you try to place another wall block perpendicular to the Wall block that you already placed.

**Comment by TwixterZ** [comment]
Adding on to this, while dead zone seems to be mainly seen on the side of the walls, the same can be observed when aiming at the front side of the wall, aiming at a small area underneath the wall will show similar dead zone.

There is a prompt for place/build, but this is actually attempting to build/place beneath the wall.

Videos attached

https://user-images.githubusercontent.com/78054747/110296932-de83df00-802d-11eb-8ed6-c70106f7cf79.mp4


https://user-images.githubusercontent.com/78054747/110296944-e2176600-802d-11eb-856d-f6917096e702.mp4

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 develop 259
