### ISSUE TITLE
[0.9.0 staging-1382] Freezes with creating Districts

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14597]
Step to reproduce:
- For example we have 3 Town in game. So we have 3 Leader and they place 3 Zoning Office. So we place 3 Zoning office. And I place 3 empty zoning office.
- at first add 3 District Map (I add 100+ plots to each):
![image](https://user-images.githubusercontent.com/45708377/73640504-69eaae00-467f-11ea-8c10-91ab2ae0a7a0.png)
- at second add 3 District Map (I add 100+ plots to each):
![image](https://user-images.githubusercontent.com/45708377/73640526-73741600-467f-11ea-9eb0-051769bf5bba.png)
- at third add 3 District Map (I add 100+ plots to each):
![image](https://user-images.githubusercontent.com/45708377/73640536-77079d00-467f-11ea-8a5b-1a57ba8477c5.png)
- After It we wait successful election or use /civics winelection 9 times.
- From 4 time there will be freezing. And each time the time will increase:
https://drive.google.com/file/d/1X8rQtLrSAIejaAb1hPw2HWHYHJOv5_a9/view?usp=sharing
If you add and vote one by one, then there will be no freezes.

**Comment by johnkslg** [comment]
Ok, this turned into a giant can of worms, but I have some fixed this issue.  
![image](https://user-images.githubusercontent.com/3536496/73983115-88a0ad00-48ea-11ea-9b4e-f24372d3e15b.png)

The bug was happening because the district viewing system was doing excessive and slow updates whenever districts changed.

Technical details: The district system was manaully syncing all the districts. I removed all this code and made it use the automatic syncing we now have.  I changed the UIs to use the auto-configure and auto-update.  Lots of old code that needed replacing. I made the districts subscribe more efficiently to state changes and update minimally.  Found a problem with lists-of-lists that I fixed.

The case you described now works properly, but there are likely some effects on other parts of the code. QA, with this PR can you give everything property, minimap, and district related a once-over to see if there's any more bugs?  Also keep an eye out for problems with lists in UI.

I've added this bug which has a few things left to fix I didnt get to, getting help from @gzatravkin for these: 
https://github.com/StrangeLoopGames/EcoIssues/issues/14637
