### ISSUE TITLE
[0.9.0 staging-1383] Time in Capitol doesn't update without placing/picking up furniture. Value doesn't update when you pick up last furniture.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14605]
Step to reproduce:
- spawn Room with 3 furniture, claim it:
![image](https://user-images.githubusercontent.com/45708377/73723791-f7d79f00-473a-11ea-9190-1d3b4924ad81.png)
- place capitol and ratify it:
![image](https://user-images.githubusercontent.com/45708377/73723800-002fda00-473b-11ea-8438-6126fdba537f.png)
- pick up 1 furniture in room. I have notification about changing value to **6,7** in **19m**:
![image](https://user-images.githubusercontent.com/45708377/73723868-1f2e6c00-473b-11ea-8c60-4df564e895f7.png)
- wait 3 minutes. I still have **19m**. Time doesn't update:
![image](https://user-images.githubusercontent.com/45708377/73724019-79c7c800-473b-11ea-8ad3-7f15b72a4cb1.png)
- pick up another one furniture. Value reduced to **3**. And time will update:
![image](https://user-images.githubusercontent.com/45708377/73724169-ce6b4300-473b-11ea-9252-e248c42e217b.png)
- but if you pick up last furniture Value doesn't update. Wait 3 minute and pick up last furniture. Still have same Value and time:
![image](https://user-images.githubusercontent.com/45708377/73724277-03779580-473c-11ea-9136-7f284d30d3b8.png)

**Comment by SlayksWood** [comment]
Same for overthrow value if you change it in serverUI. you should place/pickup furniture:
![image](https://user-images.githubusercontent.com/45708377/73729194-a7197380-4745-11ea-8bf8-795d5ab58034.png)

**Comment by johnkslg** [comment]
@olegshegai This is happening because the text only updates when the room changes.
Can you change how its displayed, just say 'when timer expires (see tooltip on <Constitution 1>). Then when they mouse over the tooltip, it will display all the details and latest time.  

This will require adding info about the time to the tooltips, which should be done anyway, and make sure it works for all these invalid timers on all types of civics objects. Thanks!
