### ISSUE TITLE
0.9 mortared stone door had different model at back and front.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14679]
![изображение](https://user-images.githubusercontent.com/4980243/74198337-26d99d80-4c72-11ea-8f3f-c1088dc0bf3b.png)
Also ignore "wall attach"

**Comment by SlayksWood** [comment]
@keegan-o can you take a look?
> Also ignore "wall attach"
And about redoing the model for back and front too. do it need?

**Comment by elfl0rd** [comment]
> And about redoing the model for back and front too. do it need?

idk too...
As result, double doors looks ugly :(
Also if we open this door, door hinges rotate away from wall, lol.

**Comment by keegan-o** [comment]
@Phlo123 Make the back and front the same so that double doors work well, and fix the rotation so that the doors exist within the meter space rather than swinging outside it and intersecting with other blocks or themselves w/ double doors.
![image](https://user-images.githubusercontent.com/14983165/82958515-5cc53800-9f6a-11ea-83e5-07c78c49b967.png)

**Comment by keegan-o** [comment]
(wall attach part of this is fixed)

**Comment by Phlo123** [comment]
Fixed in staging.
