### ISSUE TITLE
[0.9.0 staging-1399] Crushed Stone isn't only in top layer.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14710]
I don't really know, but seems it's a bug.
![image](https://user-images.githubusercontent.com/45708377/74313620-1534ea80-4d85-11ea-9e3a-a505a324ee7e.png)
![image](https://user-images.githubusercontent.com/45708377/74313724-4b726a00-4d85-11ea-819e-941d92f3b271.png)

**Comment by keegan-o** [comment]
I'm reducing this to low, as long as the stone is not too deep or internal behind other formed stone I don't consider it a huge problem. It happens because of something in the way layers overlap or biomes meet each-other--- It is not easy to fix with the settings I set, most all of which only allow crushed rock to spawn in the very top most layer. But because of how that works based on the height of the first block that is not water or air, it ends up able to spawn some further down sometimes because of the position of rock layers below the soil.

**Comment by keegan-o** [comment]
With my latest changes (reduced crushed limestone by a lot) this should be even less of an issue, closing this now.
