### ISSUE TITLE
Performance issue: physics

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14742]
Examining performance in [White Tiger Server (link)](
https://drive.google.com/file/d/1Nclb5OeSvWxEnAaaHvd-kLv5U7G0E7Lc/view?usp=sharing):

There's a large amount of physics objects that seem to be consuming cycles:
Active Dynamic: 1
Active Kinematic: 52
Static Colliders: 135.4k
Rigidbody: 220
Trigger Overlaps: 3
Active Constraints: 0
Contacts: 3

In the game I'm standing in the woods:
![image](https://user-images.githubusercontent.com/3536496/74503619-4eb14700-4ea6-11ea-8fc5-0a9eaa91a9d7.png)

It looks like physics is taking up 30-60ms of the frame time 
![image](https://user-images.githubusercontent.com/3536496/74503952-7b199300-4ea7-11ea-8dea-9ca98eb8ba24.png)

FPS 10 (in development build of client)
Going to dig into it more.

**Comment by mirasrael** [comment]
I investigated this a bit and actual issue not because we have lot of animals, **but** every animal has lot of rigid bodies. I.e. Bison has rigidbody for almost every part:
![image](https://user-images.githubusercontent.com/475445/74844802-0fb84100-533f-11ea-89f8-5da0265855ae.png)

I removed all joints and rigidbodies on Awake for animals for test and doesn't notice any difference in they behavior and world interaction. I assume we have these rigidbodies only for Ragdoll mode and while animal is alive it just wastes physics cycles.

In my testing I had 4.5-5ms for physics before and 1.9-2.1ms for physics after I removed all rigidbodies for animals.

I see two options:
1. Completely remove rigidbodies and joints from animals. In this case we will have static corpse. I don't really think it makes big difference for gameplay, but corpses may hang in the air or become immovable by vehicles.
2. Have two prefabs for animal - one with rigidbodies (for ragdoll) and another for alive animal without rigidbodies. We can generate this one automatically. We will also need to replace one object with another keeping all parts synced when animal dies in this case.

@johnkslg any thoughts?
