### ISSUE TITLE
[0.9.0 staging-1402] Sometimes Constitution is disabled when room recalculate.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#14744]
Step to reproduce:
- spawn contitution. Take some block in hands (Dirt):
![image](https://user-images.githubusercontent.com/45708377/74505823-2c9ce080-4f09-11ea-89a4-ce46a63d3935.png)
-place/pick up Dirt near 1 minute:
![image](https://user-images.githubusercontent.com/45708377/74505911-62da6000-4f09-11ea-8a81-bbbbc46438b3.png)
- I have 4 notification about disabled constitution.

It looks like a trouble with broken room during recalculation for a little moment. But maybe you can add some delay before notification or something else.

**Comment by johnkslg** [comment]
See whats happening here when it fails.  race condition?

**Comment by SlayksWood** [comment]
It still an issue, but it happens very rare. Closed for now.

**Comment by mirasrael** [comment]
I reverted this commit:
https://github.com/StrangeLoopGames/Eco/pull/6426/commits/f83e7303e59173e7f107f3852ca98230e8e3db0c
Because it:
- may cause significant lag for any action which may access Room in client update, especially if there long queue or big rooms waiting for update;
- may cause recursive UpdateRooms calls which leads to killing the server performance and dropping players (see https://github.com/StrangeLoopGames/EcoIssues/issues/18857);
- doesn't fix original issue, because you still may have situation when queue empty, but Room update in progress and Room removed, so it will cause described issue. It will just happen less often.

Proper fix should be to not delete a room until room calculation complete and replace it with new room instead (or delete only if there no more room).
