### ISSUE TITLE
[0.9.0 staging-1409] Work party: completion with work order finishing

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14775]
Now a work party will be finished if all the resources are added.
But an order is not finished. This can cause some problems.
Like
- a work party was finished, as all resources were added
- new work party with this order (which is in the craft process) can be created.

**Comment by mirasrael** [comment]
@beastyn It is intended behavior. It may be confusing, but even if you supply party with all required resources they may be used by another orders or directly obtained from Storage by user. So you may need to repeat work party for same order. There no good way to guarantee resources will be used by exactly the order, because of we only get resources for one iteration.
