### ISSUE TITLE
Login names not being case-insensitive

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#14819]
I was able to login as "JohnK' then later as 'johnk'.  This should detect a naming collision and rename second one to johnk2 or some such (this used to work).

Plenty of things in the game ignore case when searching for users so we cant allow two users with different case.

**Comment by mirasrael** [comment]
Checked. It works as expected.

###  Disabled authentication both on server and client (it is Debug only case):

1. Login as "mirasrael", new user created. Logout.
2. Login as "MiRaSrAeL", matched to existing user. No new user created.

Case insensitive.

### Enabled authentication both on server and client:

1. Login as "MiRaSrAeL" first (with disabled auth). It will create new user without slg/steam ids.
2. Enabled authentication.
3. Login with my SLG account (nickname "Mirasrael"). It created new user "Mirasrael#2", because it found existing user with same username, but different ID.

![image](https://user-images.githubusercontent.com/475445/75347833-bc9c3c00-58b2-11ea-8d3b-1a2e72687c51.png)

**Comment by mirasrael** [comment]
If you was able to **same** user with disabled authentication then it works as expected, because it uses case insensitive username matching, but it only happens in Debug mode with disabled auth.

In release mode you're not using username for matching, but instead either Steam ID or SLG ID and only for new users it checks for case insensitive duplicates.
