### ISSUE TITLE
CTD and PC freezing

### ISSUE THREAD

**Issue by TomJohn-git** [StrangeLoopGames/EcoIssues#14815]
After 5-20min (its random) of playing my game drops in matter of second without any error. Only thing i got left of this is crash log that is saying i miss DLL files (as someone pointed out). Its good to mention that sometimes instead of CTD my whole PC freezes and i have to shut it down manually. I reached out to some guys at strange loop forums that gave me advice or two how to solve this but i couldnt get it to work no matter what i did (tried clean install, net framework, GPU related stuff). I dont have any issues with other games. I have 500 hours on ECO while using my older PC without single CTD. This bug appears on current version which is 0.8.3.3

My PC specs are: i9 9900K, RTX 2080S, 32GB RAM DDR4, game is installed on NVME disk with large enough capacity.

Crash log from latest CTD ive got right here
[crash.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4239436/crash.txt)

**Comment by mirasrael** [comment]
@TomJohn-git 
Hi. Sorry for long answer. It seems like the issue with Unity Engine and your system (area where we can't do much). But in 9.0 we updated Unity version to latest stable (2019.4) so probably your issue already fixed in latest (not yet released) Eco version.

I close this issue for now, but fill free to re-open it if you still have such problems after 9.0 release.

**Comment by mirasrael** [comment]
@TomJohn-git if you wanna to test it before 9.0 release you can contact me in Discord.
