### ISSUE TITLE
[0.9.0 staging-1422] Work orders interactions

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#14841]
System for adding the resources and calories to the table is kind of messy now.
This long string is pretty heavy.
![bandicam 2020-02-24 16-49-29-221](https://user-images.githubusercontent.com/27898520/75150940-5b942d00-5727-11ea-9012-ad94686d9467.jpg)

Was this change intentional by some reason?

Previously logic was fine.
Hint on the table always tells you what you will put in it.
1) If you need resources and have it in the hands -  put resources
2) If you don't have resources. need calories - put resources
3) If you have resources, don't need them, need calories - put calories
It was looking ggod with modificators (and hint, which depends on it)

Now modificators inside a table (for Work button) and outside a table work differently. Inside a table Ctrl modificator will take all avaliable calories for a big order,

@SlayksWood @seccombew @WeaselDog @mirasrael @D3nnis3n 

would be great to have your opinion

**Comment by johnkslg** [comment]
We need to unify modifiers I agree, can leave this bug open for that. I'll also display the control modifier in the popup text.

For long text: sometimes a labor unit isnt a calorie.  We could probably just show calories you'll spend here I reckon. 

But previous behavior was confusing: if I have a selected ingredient on my toolbar, an ingredient in carried, and can perform labor, what does right click do? The user shouldnt need to remember what order these are resolved, as it makes it very easy to do one thing when youre intending another. So, I moved it to shift.

**Comment by SlayksWood** [comment]
How will it be unified?
So RMB was like:
RMB = 100
Shift+RMB = 500
Ctrl+RMB = max
When I press "Work" button it was same:
LMB = 100
Shift+LMB = 500
Ctrl+LMB = max.
Modifiers should be same for RMB and LMB after changes.

**Comment by johnkslg** [comment]
Changing to ctrl + click = 5x

**Comment by johnkslg** [comment]
Added display like so:
![image](https://user-images.githubusercontent.com/3536496/75283796-5b983980-57c8-11ea-84ac-f2da0942dbf3.png)
Thoughts?

**Comment by johnkslg** [comment]
Changed work button too to use control click only.
No more button to contribute 'all', youll have to hold control and click a few times to do that (but [people](https://www.clickerheroes.com/) [love](https://orteil.dashnet.org/cookieclicker/) [clicking](https://store.steampowered.com/app/346900/AdVenture_Capitalist/) so its ok)

**Comment by redwyre** [comment]
If the interactions support multiple modifiers it should just be displayed as a separate interaction

**Comment by SlayksWood** [comment]
Ok simple example. I want to create 1000 Plastic and 1000 Epoxy(these are normal values ​​during the game, i would say normal values are 9999)
So for 1000 Epoxy I need 75000 Labor/500 = 150 Clicks
1000 Plastic - 75000/500 = 150 Clicks
Without modules I need 8000 Petroleum. With Modules I need 4000 Petroleum, Take for example best way. So I need 4000 Petroleum.
4000 Petroleum - 80000/500 = 160 Clicks also need 4000 Barrel to craft Petroleum
4000 Barrel - 70000/500 = 140 Clicks.
So I need 150+150+160+140 = 600 Clicks. But that isn't all. I need to full my stomach:
I need 75000+75000+80000+70000 = 300000 Labor. It's according to my skill =  60000-300000 calories. 
If I eat Basic salad I need (60000-300000)/800 = 75-375 Clicks!
So I need almost 1000 Clicks to create it. It looks like clicking. 
I don't will calculate clicking if you can add max calories, because we have skill influence alot and it will be different numbers. I just calculate that:
Max stomach (as I remember) =  4250. With max specialty skill 4250 Calories = 21250 Labor.
Now I can max add only 500. So 21250/500 = 42.5 times.

**Comment by johnkslg** [comment]
ok fine we can add an 'all calories' on alt!
Does eating food piles have a mult click? May want to add that. 
Going to pass to Oleg to finish this off:
Oleg can you make it say (Ctrl: x 5 Alt: max cal) at the bottom and make it top up

**Comment by elfl0rd** [comment]
can we have this modifiers rebindable in control settings?

I really prefer shift to add max.
