### ISSUE TITLE
We need a difficulty setting that disables specialty point requirements for crafting.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#14864]
Without this, single player is either impossible or endless, and at the very least it would mean requiring people who play single player to leave their server on always over-night when not playing, which would obviously be ridiculous. 

Adding this to the difficulty options is also important for small groups or even large servers who should have the option to decide if they want (more or less) forced collaboration or not. 

It's high pri because for now it has a massive effect on single-player and we would likely get significant backlash if it's not in 9.0 on release.

**Comment by mirasrael** [comment]
I don't see real reason to have such setting, because already existing settings and mechanics "fixes" this problem.
1. You can use fast forward if you don't want to wait. In single player you have to use fast forward (or keep server running) anyway, because of many other game aspects like wait until plants and trees growth, wait until long work order complete etc etc.
2. You have an option SpecialtyCostMultiplier which is 0.1 for No Collab right now (it means new Star is 10x times cheaper than for Medium Collaboration) and your XP gain boosts with food and house. For me it is already very significant cut in cost, but if during playtest we understand it is still too slow we can adjust preset to 0.05 (20x) or even 0.01 (100x). Currently on my stream server with No Colab I already maxed all my stars in few days.

**Comment by keegan-o** [comment]
Right, I forgot about sleep... But I wonder about small groups of players more or less needing to know about that custom difficulty setting in order to easily play. We should definitely work to make these settings and systems as clear as possible. My bad for now though!

**Comment by keegan-o** [comment]
I'm gonna leave this open as something I need to playtest more to investigate, others can ignore it.

**Comment by keegan-o** [comment]
Alex and Todd are tackling difficulty settings and their accessibility, which takes care of this.
