### ISSUE TITLE
0.9 Profession modules should have "basic" benefit

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#14937]
Due to any profession module is upgrade from basic.
If profession module is not add benefit like standart module, it's just annoying.

every time swap modules or build additional but useless table.
It's not add replayability or interesting, it's just add more annoying microcontol.

**Comment by elfl0rd** [comment]
Also not bad if module backend support single recipe for benefit.

**Comment by mirasrael** [comment]
@WeaselDog @Sekor2600 @keegan-o @D3nnis3n @SlayksWood 
I would like to see your opinion on this suggestion. It isn't technically hard to implement this, so don't care about technical side.

I personally like this suggestion, because:
- it makes big difference for low/no collaboration, because you usually have many specs at once and you have to build lot of tables (and rooms) it by yourself. It may be very annoying;
- it makes low difference for high collaboration, because you usually don't have all table specs. So it won't affect balance much here;
- module upgrade of next level should feel like an improvement, but when you removing old benefits it leaves you in mixed condition;
- it doesn't remove idea to build multiple tables to get max benefits, but also doesn't force you to use 10% less benefit for main spec if you have multiple uses for the table and don't want to replace module for every craft;
- it is just first iteration for modules. It doesn't mean that for next iteration we should use exactly same scheme (where specialized modules inherit all benefits), but it is good enough for start;
- we are going to have separate tables for each spec anyway, so it shouldn't be a case for future at all, but will make live a bit simpler for 9.0;
- one of possible evolution ways for modules - is using special modules per table/set of tables and then we don't have specialization limited benefits on them. So it also doesn't conflict with such implementation.

**Comment by WeaselDog** [comment]
Looks good to me

**Comment by mirasrael** [comment]
After discussing with balance team and analyzing potential problems (especially for single player and low collaboration) I approve this change.
