### ISSUE TITLE
[0.9.0-1445] Stairs don't connect to Terrain type blocks

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#15024]
not connect blocks

![изображение](https://user-images.githubusercontent.com/13696708/76139399-5fe21380-6060-11ea-90fe-ad4286ad1997.png)

**Comment by MishkaFur** [comment]
This happens in 8.3.3 too so is not a specific 0.9 bug

**Comment by keegan-o** [comment]
More or less as intended, if we made terrain merge into stairs and all similar kinds of things like ramps, it would mean we would have to either massively add to the rules in the terrain builder (it's already the most complex in the game by far), or not be able to remove internal faces in the future in the same way as we intend to do.

Short answer: Add a cube block at the top of your stairs! (Cube and other forms which take up the whole space can merge with terrain because they are not concave, so they won't reveal the inside of terrain next to them through the concave areas).
