### ISSUE TITLE
0.9 something strange with ingredient highlight at adv. smelting.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15111]
Just look - no modules, and i dont have adv. smelting, but indicator is green...
![изображение](https://user-images.githubusercontent.com/4980243/76571626-fed79700-64c8-11ea-9890-4b122d398c28.png)
![изображение](https://user-images.githubusercontent.com/4980243/76571665-0f880d00-64c9-11ea-832a-cbe10c0f0705.png)

**Comment by SlayksWood** [comment]
What is strange?
All dynamic ingredients must be green; all static ingredients must be yellow.
non-taken specialty  should not affect the green / yellow highlight. If you don't have specialty you still can start order and buy Adv.Smelting Labor.
Dynamic ingredients should always be shown because you must know what will happen after installing the module before installing it.
For me nothing is strange. Just a bug but we have another issue for it #15085
So merged.
