### ISSUE TITLE
(suggestion-feature request) different indicator for dunamic benefit for talent, module and module+talent

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#15112]
It's possible to make different indicators for benefit from module and talent?
It's a little confusing if you have talent in profession...

**Comment by SlayksWood** [comment]
green highlight - any benefits may affect
yellow highlight - nothing.
We haven't any dynamic benefit only for talent or only for module. One way it's have module without talent (you still can't take it because you haven't enough skill level). But dynamic mean that you can reduce it with talent and module. In any way you can see tooltip:
![image](https://user-images.githubusercontent.com/45708377/76593501-88a65500-6507-11ea-9d0f-b38ef929f894.png)
For me it's enough for 0.9.0, in 0.9.1 we plan to remake some talents and Skill UI, so I think it isn't actual for this moment.
@mirasrael @beastyn @Sekor2600 @WeaselDog 
What do you think?

**Comment by Sekor2600** [comment]
I think Plan was Talente for 9.1 or 9.x

**Comment by elfl0rd** [comment]
As far as I know, one of the goals of this change was to simplify the definition of which module is installed. If everything is marked green, we still won't be able to quickly and easily see what we have a bonus on this table. No - tooltips are not a clear way to provide information.

My query refers to the same problem, now having talent in the second profession, it is possible to confuse the table having the installed module of the first profession.

**Comment by SlayksWood** [comment]
Talent will be remade I don't need want to see 4 color, if you have talent it will always work. 
For me it's unnecessary to have 4 color, 2 color will enough. 
Yellow-static should be always shown.
Green should be shown if you have any effects by module.

**Comment by elfl0rd** [comment]
maybe we can display talent benefit bu something different? Like small yellow star :)

**Comment by SlayksWood** [comment]
I don't want to display talents just because this talent must be removed. Because it's overpowered.

**Comment by elfl0rd** [comment]
5% overpowered? for me it's ok.

**Comment by Sekor2600** [comment]
Talents need all rework. Why give choices? all would use the 5% reduce

**Comment by elfl0rd** [comment]
another talent is nod bad too (in idea) but main problem - some "room specific" cases (e.g. double speed, etc) wont work outside.

**Comment by WeaselDog** [comment]
The indicator was added primarily to clarify which recipes have static ingredient costs. That fact it shows which ingredients are currently benefiting from installed modules is a nice bonus.

We have plans to expand the crafting/skills UI for sure and we can look at ways to make it more clear the benefits from talents at that time. For now the feature is working as intended and this is a suggestion to consider for the future.
