### ISSUE TITLE
[0.9.0] DNS subdomain support

### ISSUE THREAD

**Issue by quequiere** [StrangeLoopGames/EcoIssues#15117]
Hello,
I'm using a server with subdomain and reverse proxy to host eco server like that:

serv.domain.com:3000 that redirect to specific game server on a docker container.

But it seems that eco doesn't care about the subdomain, and directly resolve domain.com to an ip.
I'm dev tier and I can see on the logs that Eco try to connect to 178.XXX.XXX.XX:3000
I would like to the that Eco try to connect to serv.domain.com:3000

Have you got a solution ?
It could be awsome to support this solution for those have multiple server on the same infrastructure

More details:
==> serv.domain.com:3001 redirect perfectly to the web server of eco
==> I'm using a windows server with Docker (windows plateform)
==> Using Traefik as reverse proxy

**Comment by redwyre** [comment]
So are you trying to have:
server1.domain.com:3000 connect to port 3000 on one local server and,
server2.domain.com:3000 connect to port 3000 on another local server, where

server1.domain.com and server2.domain.com resolve to the same IP?

If so, that's not possible. This only works for http because the browser passes the original host name as part of the request, and a reverse proxy or server can use that to direct it to the correct website. Connecting to a raw port doesn't have any way to do that. You will have to put the game server on different ports.

**Comment by redwyre** [comment]
@quequiere Does this resolve the issue for you?

**Comment by redwyre** [comment]
Closing for now as I think that is the explanation of what's happening, respond here if you have more to ask or feel free to join us on discord if you want to discuss further.
