### ISSUE TITLE
Tailoring table making loud noises even when not crafting

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoIssues#15261]
Tailoring table is making a very gnawing whining sound even after finishing craft.

**Comment by Knigge** [comment]
Does not diminish even when replacing table

**Comment by SlayksWood** [comment]
@Knigge game version?

**Comment by PacifyerGrey** [comment]
Hey Slayks,

I am experiencing this issue on 9.0 on test server with current ptr branch. I called it a "phantom sound source". All tables and even vehicles sometimes leave a static source of sound like they are working at this location. You can remove the table/vehicle completely but the source of the sound persists. Even if you relog the sound source is still there.

Sadly I have not been able to reproduce it with 100% result, this seems kinda random. However sadly this bug is not rare.

**Comment by SlayksWood** [comment]
some issue should be fixed with new build. But we still have one issue with this problem #15100
merged.
