### ISSUE TITLE
[9.0 Staging-1477] Server Exception.

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15273]
[server exception - eco.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4371546/server.exception.-.eco.txt)

**Comment by Daelmaron** [comment]
typing a message to another player in chat when I received a server exception and was forcefully disconnected.

[server exception.txt](https://github.com/StrangeLoopGames/EcoIssues/files/4371822/server.exception.txt)

**Comment by Daelmaron** [comment]
after some testing on client side it seems that the line 

"Am going to be making alot of them now so we can upgrade all the roads with {abcplayer} help" being inserted into the chat is one of the causes of this server exception.

We tested it further and narrowed it down to the word "roads" in the line which we think is because we have a zoned district that is proposed that is labelled as a roads district.

**Comment by MishkaFur** [comment]
Server exception when typing the below message into chat, soon as you hit enter it does server exception

it appears to be when saying roads ingame which is a district, that shows as "deleted" so typing Highways, Capitol Building is fine but access roads or service roads causes exception

![image](https://user-images.githubusercontent.com/61889138/77370178-44615300-6d58-11ea-9ac0-db26f6cf3580.png)

![image](https://user-images.githubusercontent.com/61889138/77370269-72469780-6d58-11ea-9bfc-f989875b75ae.png)


"Am going to be making alot of them now so we can upgrade all the roads with scotts help"

**Comment by Daelmaron** [comment]
Occurs to me that just after the update I logged in and was the first one to do so. I was editing the district map and I crashed out of the game in the middle of doing so.

I had started an election prior to the update and post update the server showed the previous person in the position I was running for had been **REMOVED** and then when I first opened the district map that had previously been set I got about 5 minutes of work before crashing out of the game.

When I logged back in I went back to work and didn't think anything of it until we just now encountered this issue

**Comment by Daelmaron** [comment]
![20200323175824_1](https://user-images.githubusercontent.com/1329717/77370900-eb7dc480-6d2f-11ea-83e9-0c4da606726e.jpg)

in the above screenshot the district that says District Map 1 V2 is showing as deleted however it wasn't deleted. 

All that was done with it was that it received a new name (should have automatically updated across the board) and then several new districts were added under it to expand it. **HOWEVER** it is showing as a completely separate set of districts instead.

**Comment by NN-Mike** [comment]
For reference, here is the Zoning Office
![image](https://user-images.githubusercontent.com/54982803/77374691-5399ce00-6d63-11ea-8d88-f265d8da568b.png)

**Comment by Quadbro** [comment]
In case if someone will take this issue, the problem is:
Exception: ArgumentOutOfRangeException
Message:Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Source:System.Private.CoreLib

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Eco.Gameplay.Systems.TextLinks.RegistrarFinder.<>c__DisplayClass8_1.<FindObjects>b__2(Match x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Eco.Gameplay.Systems.TextLinks.RegistrarFinder.FindObjects(String text)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at Eco.Gameplay.Systems.TextLinks.TextLinkManager.MarkUpText(String text)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessMessage(ChatMessage msg)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(String text, User user, INetObject target)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChatStripped(Player player, String text, INetObject target)</size>

**Comment by johnkslg** [comment]
Fixed!
