### ISSUE TITLE
[9.0 Staging-1477] Stores Broken?

### ISSUE THREAD

**Issue by Daelmaron** [StrangeLoopGames/EcoIssues#15274]
![20200323144421_1](https://user-images.githubusercontent.com/1329717/77356774-f4ad6800-6d14-11ea-9c2d-94e0f8a1d6d8.jpg)

Went to go perform maintenance on my store and my entire for sale list was gone as was my purchasing list. 

Going to go create a new store and see if it just broke already existing or all stores.

**Comment by Daelmaron** [comment]
Seems that picking the store block up and placing it back down has zero effect. I had to completely recraft a brand new Store table and set it back up from scratch to fix this.

See also #15278

**Comment by SlayksWood** [comment]
We definitely need a button that will reset objects with a persistent base to default #15283.
@Daelmaron 
But need some more information about broken store. Did it happen just after migration from 1465 to 1477 staging? or you had this problems without migration too? 
Seems like this problem only occurs after the migration and happened because it has some store changes. Because of this, your persistent data in the store suffered.

**Comment by Daelmaron** [comment]
From what I am looking at on a player/independent coder basis its an issue with the persistent data changing, though we now still have an issue where we cannot keep items in trucks from being available to be purchased from a store/sold to a store repeatedly because the store dumps the items back in the truck inventory.

_Stores occasionally will bug out like in the pictures above of their own accord but that is usually due to crashes_

**Comment by beastyn** [comment]
We have issue for resetting data for broken objects. #15274
Will have a look at it after some more time in playtest (new updates and migrations).
Close for now
