### ISSUE TITLE
Remove console from server to prevent save corruptions

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15325]
Closing the server console with 'x' results in save corruptions because cleanup has less than 5 seconds to process and can't finish sometimes.

We can add it to a 'Console' tab in the server, or some other solution.

**Comment by elfl0rd** [comment]
I think this button can disabled.

**Comment by johnkslg** [comment]
That would also work as a solution, though then it becomes less clear how to close

**Comment by mirasrael** [comment]
I think button disabling is better (we can also add hint into the title), because:
1. You have lot of cases where Console is only option (like Linux or MacOS server);
2. If you start server from the client then it will start as hidden console window, but you can show server UI with in-game console command, but in this case you don't want to stop the server with GUI cross (otherwise when you try to hide Server GUI you will just stop the server and drop the client).
3. You can start server as -nogui (it is useful for many scenarios like when you run the server as background service).

**Comment by mirasrael** [comment]
![image](https://user-images.githubusercontent.com/475445/78539738-b7100b00-77fb-11ea-9f4a-babd182346f0.png)
