### ISSUE TITLE
[0.9.0 staging-1485] Bug with revising District Map

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15334]
Step to reproduce:
- place capitol and ratify
- place zoning office and create district map (I called distric map like Road Map and district like main road):
![image](https://user-images.githubusercontent.com/45708377/77619156-ab455e80-6f48-11ea-9015-e927ef90d782.png)
- press revise district map. I have wrong names for District and district map.
![image](https://user-images.githubusercontent.com/45708377/77619186-bd270180-6f48-11ea-8f21-ff66441af4f8.png)

**Comment by SlayksWood** [comment]
It worked in 1464 staging
![image](https://user-images.githubusercontent.com/45708377/77634680-68908000-6f62-11ea-9ae2-d923f336ff54.png)

**Comment by Daelmaron** [comment]
@SlayksWood the zoning table seems to overwrite existing maps and create them as a **brand new** map when you make any sort of revision rather than just revising the map. 

This leads to issues like if you have laws that rely on the district map called ex. Roads with Districts of Highway, Access Road, Service Road. If the district map gets updated it overwrites those with new districts that no longer have a name however you cannot rename the new districts to those names because it tells you that "a district with this name already exists" this also creates a ridiculous amount of districts that are backlogged that you have no access to to be able to say delete previous maps etc because you can't see them and if you have a map with 5 districts each new revision adds 5 more districts, anything behind the current ones which you cannot see.

**Comment by johnkslg** [comment]
I think this is a dup of https://github.com/StrangeLoopGames/EcoIssues/issues/15206

**Comment by Daelmaron** [comment]
@SlayksWood on Royal Otter we had another player propose a new district map and it was okay for about an hour but now every district map in that slot is completely blank and has zero affect. 

Currently we cannot edit it because there is a current election on the proposed district (which I can't stop that I can find a way to it seems) and I am quite sure that this is about to start causing the server exceptions like it was the other day with the <deleted> district that was being referenced by the laws

**Comment by SlayksWood** [comment]
Seems fixed. But still has a small bug.
