### ISSUE TITLE
[0.9.0 Staging 1491] Diagnostic page not working correctly

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15475]
Diagnostics page seems to be broken

Streaming is showing an insane amount of usage even after only a few minutes ingame
![image](https://user-images.githubusercontent.com/61889138/78070478-c45c6e00-7393-11ea-920d-2c1ffee78c7b.png)

F3 and F4 to go forwards/back page wise does not work.

**Comment by MishkaFur** [comment]
Had to zip the player-rev as it was 120MB
[Player-prev.zip](https://github.com/StrangeLoopGames/EcoIssues/files/4411353/Player-prev.zip)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4411355/Player.log)

**Comment by Knigge** [comment]
I have the same issue today. I still have to restart the game from time to time due to massive memory usage. (>12gb)

1. version: 9.0beta - 1506
2. Reproduce by logging in. press f2
3. Expected no utilization.
4. Seemingly using a lot more resources than possible to allocate.

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4464689/Player.log)

**Comment by beastyn** [comment]
I can't launch it now with F2

**Comment by MishkaFur** [comment]
Seems to be working in 1611 so this might be able to get closed now?

**Comment by redwyre** [comment]
yep!
