### ISSUE TITLE
[0.9.0 staging-1495] Sickle and scythe flaws.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15480]
I move this from #13154.
So the most difference is that I can't mow, for example, Beet if I selected it, but I can mow it if I use AoE sickle or scythe if I don't select it, but it gets into AoE.
It should be same behavior for this.

**Comment by Engimage** [comment]
One issue we met on a test server was that most of the AOE tools (including sickle, scythe etc) do consume calories for all effected blocks no matter if something was there or not. So I definitely recall someone asking to get Iron Scythe instead of a Steel one as the later was consuming 4x calories per swing even if you were removing a single plant (and no other were around).

For the the issue was with Steel Hoe which, while speeding up the process due to aoe, was not really useful as it did still consume 2x calories even if I was going to process a single block say for a tree and not a large field.

So I think all AOE tools should consume calories once per swipe no matter what. Or there should be a way to toggle AOE or set the size of it somehow.

**Comment by SlayksWood** [comment]
@Engimage it's another issue #15141

**Comment by beastyn** [comment]
@Quadbro for help

**Comment by SlayksWood** [comment]
It will mow rice and bullrush. Seems okay for me:
![image](https://user-images.githubusercontent.com/45708377/83394775-d1342700-a401-11ea-8cbb-d37ef98ae015.png)
But if I select Amanita mushroom and try to mow, then nothing will be mowed:
![image](https://user-images.githubusercontent.com/45708377/83394865-017bc580-a402-11ea-91ee-5ca4ddacfa74.png)
I assume if I have highlight then Rice and Bullrush should be mowed.

**Comment by Quadbro** [comment]
adjusted higlight system on both client and server, to add new checks, and remove confusing higlights
