### ISSUE TITLE
[0.9.0 Staging-1494] Unable to add labour to projects without input materials

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15503]
When you create a new project you have to add some input materials. Sure, this is a good measure for people not to sink their labour into something stupid before they can do anything, but for higher-end players, it's a bit limiting. Today someone wanted me to crush some rocks for them in a work party so they could process things in the future, but since they didn't have any inputs, we had to wait for them to "prime" the work in order to add the labour. For projects to get rid of excess materials (say, crushed stone into sand), sometimes you want to set things up in advance but can't because of this restriction.

Maybe it would be nice to have a warning appear when you try to add labour to such a task the first time you do it ("you're about to add labour to work without materials, are you sure?"), and if you add labour at all, the warning won't appear...

**Comment by Engimage** [comment]
I found it to be an issue as well.
For example this can be really problematic with Oil products as well.
When you have an active project finishing soon you always want to queue more in advance. Pump Jacks serve as the best example, Refinery as well. The newly queued project will almost never get a single material because an active one will still be consuming them constantly so you actually never can make such a queue unless you stall all the production to pile the material up by unlinking storages and then start it again.
I do not see any game value in this and all it does is add a lot of tedium and confusion.

I am not sure how it will effect work parties as adding labor there should probably also be prevented if no materials are deposited. If so this is a real bummer as totally different people might do it and this will confuse those who want to provide labor on the order and not the materials.
