### ISSUE TITLE
[0.9.0 Staging-1494] Work parties have issues if you put your own materials in

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15539]
I tried supplying my own materials for a work party. I took some boards and put them into the work order. I got paid straight away, and the boards went into a nearby linked inventory. Then I was able to pick the same boards up and deliver them to the work party again. Work party progress was recognised and I got paid again. Eventually I delivered all the boards I needed, work party resource delivery was complete, but there weren't enough resources to complete the project.

I guess to avoid that the resources should be directly consumed when they are being delivered. I know this would let people condense their inventory up by using work parties. An alternative would be having some inventory lock or something for the resources, which could have its own problems...

**Comment by beastyn** [comment]
Its intended right now, there is no allocation for the resources. It doesn't break anything in general, as the person, who is trying to apply this kind of exploit won't get his order completed anyway. If you have access to the storage, it should be your own party, so its your money. The problem can accure with government parties with payment from the treasury.
Is there any plans for changing it?

**Comment by mirasrael** [comment]
There is no good solution to avoid this (at least I can't find such). And as @beastyn said it isn't actually problem, because you're stealing from yourself. Only option I can see is to return pre-9.0 behavior when Work Orders consumes all resources, but it is wrong in many other ways.
Even with government party if you allow direct access to inventory then you should trust that person. He can steal in many other ways (including end product from the order). So don't really see any problem here.
We can return to this if somebody will ever find good solution, but for now no plant to change the behavior and it is intended.
