### ISSUE TITLE
[0.9.0 Staging - 1494] Law to prevent placement of Capitol outside of a district does so?

### ISSUE THREAD

**Issue by Sarah-Graesyn** [StrangeLoopGames/EcoIssues#15580]
**Steps to reproduce:** Create a law to prevent the Capitol from being placed outside of District X; craft a second Capitol; Attempt to place new capitol outside of District X
**Expected behavior:** To my understanding, the Capitol being the initiator of the Government Overthrow system would be "immune to" or would "ignore" the law mentioned above and you would still be able to place it to initiate the entire Government Overthrow system.
**Actual behavior:** Law prevents the placement of Capitol outside of District X
**Providing Log files:**
Screenshot of the Law.
![20200406143914_1](https://user-images.githubusercontent.com/1329717/78598218-8b4d4f00-7814-11ea-8ce9-9ba99d5922e8.jpg)
Screenshot of the inability to place the Capitol due to the Law.
![Capitol Testing vs Law](https://user-images.githubusercontent.com/1329717/78598265-a4560000-7814-11ea-8903-9330afe9322c.png)

**Comment by Sarah-Graesyn** [comment]
So, my suggestion with this is that if it is possible to do on the backend (_and from my admittedly dated coding experience it should be, but it may be a bit complicated_) the Capitol itself should essentially ignore all active Law's, especially ones preventing the placement of blocks/objects as it is the initiator object for the entire Government Overthrow system.

**Comment by Sarah-Graesyn** [comment]
thinking further, the easiest approach might honestly be to just remove Capitol from the drop/pickup block and place/pickup object lists so that it is not selectable as an option when creating laws that use event triggers with that filter.

**Comment by D3nnis3n** [comment]
Afaik this was intended behaviour, but we might should add a server config if preventing that is allowed or not.

**Comment by SlayksWood** [comment]
It must be possible to prevent to pick up of the constitution. why is not the law? If this is not done, then a player can simply pick up it and destroy full  government system after some time. I think that is part of the game. And do not limit people in anything.

**Comment by SlayksWood** [comment]
@johnkslg 
What do you think?

**Comment by Sarah-Graesyn** [comment]
@SlayksWood I agree it should be possible to prevent the pickup of the constitution but on the other hand a law shouldn't be able to prevent the initiation of the government overthrow system that you guys have spent so much time and put in so much hard work to design and build.

**Comment by johnkslg** [comment]
I think it is worth blocking that kind of law, since overthrowing the constitution is the one safe guard in the game for government right now, and it shouldnt be so easily blocked.  I'll make sure it can still protect pickup, and just be placement that matters.

**Comment by johnkslg** [comment]
I've added a special check when creating laws with pickup/place that will prevent handling the constitution.
![image](https://user-images.githubusercontent.com/3536496/80296309-9ff37780-872e-11ea-816e-8fd1be92438b.png)

Thus, you can't block either the pickup or placement of a constitution.  As to your point Kirill, the property rights of the land the constitution is on should be sufficient to protect it, if such protections are desired.

**Comment by D3nnis3n** [comment]
@johnkslg I don't think so. It's specifically about preventing rogue players, probably from the same government, to pick it up to make it unusable. While for now you could make the the deed the constitution is on just a single room that whoever should have rights can build and fit out himself, there is another issue open on github from you, planning to count the value of the whole deed instead of the room for overthrowing. In that case the whole palace would need to be the same deed.

It's impossible then to control access, as we all need several people working on the rooms and palace, without them being able to pick the constitution up.

**Comment by trickenso** [comment]
@D3nnis3n Couldn't this all be avoided by only assigning the capitol property rights to the world leader, or similar?
Like #1087, if you elect a world leader/other official, or assign a work crew who turns rogue and destroys the building, shouldn't this be possible?
Agreed it's a subtle point, but adding arcane rule exceptions to try and legislate for all possibilities seems likely to confuse more than it helps. Or you end up being unable to do any meaningful sabotage, which is less interesting - why shouldn't you be able to gain the trust of a rival government so you're assigned building rights, and then steal the building block by block in the night?

As a suggestion for right now - maybe the exception should be that you can't make a law preventing the **placement** and **crafting** of a constitution, but you should be allowed to prevent it being **picked up**?
In the version above, you can't prevent pick up or place, but you can still presumably prevent crafting, which is worse, in a way...

For future iterations with multiple concurrent governments - was there talk of the strength of a government having a range of influence? In this version it is simpler, because this special case becomes obsolete. You could just craft and place a constitution outside the range of the government you want to compete with, to set up a competitor. That way there's no problem having any law at all, assuming you couldn't reasonably project your government influence over the entire planet without significant work.

**Comment by D3nnis3n** [comment]
> Like #1087, if you elect a world leader/other official, or assign a work crew who turns rogue and destroys the building, shouldn't this be possible?
You might want this to be possible on your server, i do not. That's griefing in my definition. Also i can actually restrict the work crew via laws, which i can no longer do for capitol. There is no way for me to protect stuff. That's the point. I don't use administrative powers but when there is no means to deal with it ingame for prevention. If i cannot prevent people via law to not pick it up, it becomes a server rule to not do so, punishable by ban. That's why we want to have options to do stuff without requiring administrative intervention, still fitting the goals of our server.

> Or you end up being unable to do any meaningful sabotage, which is less interesting - why shouldn't you be able to gain the trust of a rival government so you're assigned building rights, and then steal the building block by block in the night?

Cause this does not invalidate stuff, but actually destroys it. The goal is that you can apply your own constitution, by having better room score, e.g. a much more beautiful palace as represenation for your strength - but the others can keep their constitution and make it great again via changed to their score.

For me that kind of sabotage is a clear case of severe griefing and would be awarded a permanent ban. People are working hours for hours to set up government stuff, just to loose the whole constitution that is saved in the object. Sabotaging is PvP.

The best option is still to allow prevention of picking up the Constitution by default and linking the prevention of crafting and placing it to if government overtaking is enabled or not, given it'll be disabled on a lot of servers, including White-Tiger and most of the concept community servers due to their unique concepts.

**Comment by trickenso** [comment]
> You might want this to be possible on your server, i do not. That's griefing in my definition. Also i can actually restrict the work crew via laws, which i can no longer do for capitol. There is no way for me to protect stuff. That's the point. I don't use administrative powers but when there is no means to deal with it ingame for prevention.

So don't assign people property rights to the Capitol? You can control that by law.

Agreed that maybe just preventing a law forbidding 'craft' and 'place' is a better exception. That way a law preventing 'pick up' would be possible, which might stop your anticipated griefing? This way you could allow building rights while also forbidding removal of the existing constitution.

In answer to your other points - allowing it to be administrable by law makes sense, but allowing overthrow of a government and setting up a rival constitution is also PVP. If that is something being introduced to the game, then it has to be considered in those terms.

Increasing the flexibility to create laws to prevent those things makes sense - I agree. Hence my suggestion to disallow only laws preventing 'craft' and 'place' of a constitution, rather than 'pick up'. I don't agree that this should be a default position, either way.

**Comment by D3nnis3n** [comment]
As you've edited your post, but i still wanted to answer your old messages:

> So don't assign people property rights to the Capitol? You can control that by law.
No, i cannot. I can only give total rights to the deed for building it, or none, we do not have any finer controls. I can use finer controls if only some machines need to be used, but for building i can't and it's common that stuff needs to be moved around to make room for other stuff. On a server as big as White Tiger it's not possible to do this with only one or two persons, so objects that shouldn't be touched are protected via laws in a district, but everything else can be changed. My point was only that this would no longer be possible for the Capitol.

> Agreed that maybe just preventing a law forbidding 'craft' and 'place' is a better exception. That way a law preventing 'pick up' would be possible, which might stop your anticipated griefing?
Yes, that was exactly my first suggestion.

> In answer to your other points - allowing it to be administrable by law makes sense, but allowing overthrow of a government and setting up a rival constitution is also PVP. If that is something being introduced to the game, then it has to be considered in those terms.
I'd not agree. There is a huge difference between an intended mechanic that is based on **collaboration to reach combined efforts** against a different group (in most cases this will be a protection mechanic against bad governments, as if government is fine, noone will change it) versus single people using non-intended ways to damage other people. The second one being griefing.

> Hence my suggestion to disallow only laws preventing 'craft' and 'place' of a constitution, rather than 'pick up'. 
Which i already had suggested in my first post *g*

> If you are foolish enough to allow unlimited build rights to your capitol building, you deserve all the grief you get, and long may it continue. This can be controlled with existing laws.
While noone ever deserves grief in my opinion (server rules explicitly specify that laws are valid as of written intention, not if they work - same for abusing mistakes by others), it's not happening on White-Tiger and wasn't the point of the topic.

**Comment by D3nnis3n** [comment]
@johnkslg I believe craft isn't even affected yet, so also from that point of view, it wouldn't really be fixed currently.

**Comment by trickenso** [comment]
> No, i cannot. I can only give total rights to the deed for building it, or none, we do not have any finer controls.

We've already agreed that you should be able to prevent picking up a constitution through a law.

To protect the *building*, you can prevent 'pick up' of blocks at a district level if you want - this would prevent someone walking off with elements other than the constitution. Whether it's better to control this at a land claim level is a design decision, but it is certainly possible to have different levels of control than all or nothing using the current systems.

> Yes, that was exactly my first suggestion.
> Which i already had suggested in my first post _g_

Mine, too. Glad we're in agreement. I now see what you meant - it wasn't immediately obvious to me. Apologies for any misunderstanding.

> single people using non-intended ways to damage other people

As long as it's established that this is not intended, then sure.

If the option for someone to dismantle someone else's capitol building is unavailable across the board because of how one server decides to run itself then that's a shame.

Allowing control of this through laws, though? Perfect,

I'm personally all for learning something from the law of unintended consequences through poorly-written laws, or miscalculated subsidies. It's 'Tragedy of the Commons, the game' not 'Everybody Play Nice By Default, the game', after all.

> wasn't the point of the topic.

Agreed.

**Comment by trickenso** [comment]
> @johnkslg I believe craft isn't even affected yet, so also from that point of view, it wouldn't really be fixed currently.

Which I already had suggested in my first post _g_

Definitely need freedom to 'craft' and 'place' for a constitution to be able to overthrow a government.

**Comment by D3nnis3n** [comment]
> I'm personally all for learning something from the law of unintended consequences through poorly-written laws, or miscalculated subsidies. It's 'Tragedy of the Commons, the game' not 'Everybody Play Nice By Default, the game', after all.

Would be quite dull, if the tragedy comes from a mistake in a syntax a lot of normal people simply don't understand, though. As we use a lot of laws with only text and no syntax at all, as it's not possible to automate, that wouldn't work for us.

**Comment by D3nnis3n** [comment]
@johnkslg We'll need a crafting prevention prevention as well and pickup shouldn't be prevented.

@trickenso Thanks for the nice chat! :) (Both in discord, as well as here)

**Comment by johnkslg** [comment]
Added bool for determining if you can overthrow:
![image](https://user-images.githubusercontent.com/3536496/80543588-0f05e180-8964-11ea-90ee-c5faafc414cf.png)

Made constitutions pay attention to it:
![image](https://user-images.githubusercontent.com/3536496/80543604-188f4980-8964-11ea-872c-e5965b596873.png)

Made laws about capitols not care if it's off:
![image](https://user-images.githubusercontent.com/3536496/80543658-3f4d8000-8964-11ea-8735-952af8275ad1.png)

If it's on, laws about work orders (including doing labor on work orders, etc) can't be prevented if they are about a capitol:
![image](https://user-images.githubusercontent.com/3536496/80543733-686e1080-8964-11ea-8e78-ed599ca96ec8.png)

And the same for Pick up and Place as already implemented earlier.

I think this satisfies all.  Keep in mind we'll be revisiting a lot of this with the cities update, overthrowing will be changed a lot.

**Comment by trickenso** [comment]
@D3nnis3n - If I'm not mistaken, did you not need to be able to create laws to prevent 'pick up' of an existing constitution to avoid griefing and destruction of created laws?
My understanding was that the previous prohibition against laws preventing 'pick up' caused some difficult special cases, which are still possible.

If the Capitol deed situation isn't going to be changed before the cities update then perhaps it's not an immediate problem, but wanted to check.

**Comment by johnkslg** [comment]
If you disable 'overthrowing', then you can freely make laws about picking up/placing constitution.

**Comment by D3nnis3n** [comment]
Perfect for everyone, job well done!
