### ISSUE TITLE
[0.9.0 Staging - 1494] Max speed truck will stop when driving onto asphalt ramp

### ISSUE THREAD

**Issue by revtje** [StrangeLoopGames/EcoIssues#15582]
If you drive a truck at max speed on asphalt into an asphalt ramp the truck will stop. Only happens at max speed.

**Version**: 0.9.0.0 beta staging-1494
**Steps to reproduce**: 1. Go full speed on a straight asphalt road and in the end have one ramp up
**Expected Behavior**: Truck should drive up the ramp
**Actual behavior**: The truck stops in the middle of the ramp

**Comment by revtje** [comment]
Tested some more and it happens at various speeds. Sometimes it works when driving slow and sometimes not.

**Comment by ThePiachu** [comment]
Yup, driving a Truck on Asphalt Road into Asphalt Ramp is a problem.

**Comment by Engimage** [comment]
I am not sure if this is related but I noticed that the truck (gas one not steam) is pretty low and tends to get stuck everywhere with its body especially trunk part. Maybe it does so on an aphalt ramp as the game (due to lag) considers it touching the ramp with the body. The greater the speed the greater the probability of a lag causing the situation. And Asphalt roads increase the speed dramatically.

Steam truck is almost never effected as it has a great clearance.

**Comment by MishkaFur** [comment]
I have had this on dirt ramps too FYI

**Comment by elfl0rd** [comment]
hmm, maybe somaone broke fix for this old issue? https://github.com/StrangeLoopGames/EcoIssues/issues/5532

**Comment by MazonDel** [comment]
It was a ground clearance issue, the leading edge of the collider for the truck's cabin was impacting the ramp when the truck moved at high speed. By raising a little I've solved the issue.

The fix is currently in the Trunk branch of the SVN.
