### ISSUE TITLE
[0.9.0 Staging-1494] Can't chat / tab and do stuff while auto-running

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15614]
The auto-run feature is a bit neat, although it's hampered a little by not being able to do anything while you're auto-running. Say, if I'm on a long highway that's a straight line, it might be nice to be able to tab and eat some food while jogging or have a chat with people, but as soon as you try chatting or tab, you immediately stop auto-running. It's a bit frustrating I can't drive and chat "on my phone" at the same time like a reckless driver ;) .

**Comment by SlayksWood** [comment]
I can do everything in auto-run. 
It isn't worked with car. But for now It's intented behavior, you can add suggestion here:
https://github.com/StrangeLoopGames/EcoSuggestions/issues
@ThePiachu 
please next time don't add only text in issue. Need to add some proof: video, screenshots and log files (if you have some error)

For playtest users we have some template to write issue:

1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

Please follow the templates.

**Comment by ThePiachu** [comment]
Sorry about that, I guess I was a bit too eager with reporting things lately. I'll work on quality of my reporting.

I went back for some testing and narrowed it down - auto-run doesn't work if you're in a truck and tab / chat. Added proper description and video proof.
