### ISSUE TITLE
[0.9.0 staging-1503] Skill UI benefit tooltip

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15636]
Not performed from #15211
> ![image](https://user-images.githubusercontent.com/3536496/77042393-f0283d00-69fe-11ea-9109-0cfdac5018c6.png)
> 
> * [ ]  This tooltip makes no sense.   It should say 'Logging Level 7 Bonus: Calorie Reduction' or something like that. Then the first line should explain what a level bonus is. Then have a title for the list, 'Recipes given a calorie bonus:'

**Comment by mirasrael** [comment]
Rename to "Calorie Reduction Benefits" for now. You need to change logic here
\Eco.ModKit\ModDataSync.cs
```
benefitInfo.Info.Name = benefit.ValueType.ToString();
```
to use something like GetBenefitName(benefit) which returns custom display name based on ValueType.

We can't include title for recipes, because we don't have sub-categories and same benefit may be applied not only to recipes, but i.e. for calories per hit or for gathering wood pulp.

**Comment by mirasrael** [comment]
Also use separate category for Labor benefits: DynamicValueType.LaborEfficiency.

**Comment by gzatravkin** [comment]
Created category LaborEfficiency. @RobertMangano please add icon after this PR wille be merged.

**Comment by SlayksWood** [comment]
I still can't see on tooltip specialty and level bonus is
> Logging Level 7 Bonus: Calorie Reduction

![image](https://user-images.githubusercontent.com/45708377/80944685-cda58400-8df2-11ea-8f9c-d6a1ecb4e592.png)

![image](https://user-images.githubusercontent.com/45708377/80944833-18270080-8df3-11ea-9275-87f5e72fd0f5.png)
![image](https://user-images.githubusercontent.com/45708377/80944852-2117d200-8df3-11ea-92f3-523f75726f88.png)
