### ISSUE TITLE
[0.9.0 staging-1503] Election Bar have different size

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#15649]
Not vote, vote yes, vote no:
![image](https://user-images.githubusercontent.com/45708377/78766946-a04fec80-7992-11ea-9a5c-c58bc2023b0a.png)

**Comment by MarkZaytsev** [comment]
I've added more spacing too, since Change and Vote words have different width. And localized text might be wider. The only option here is to add default spacing. 
Screenshot illustrates how it will look with different localization
![ss (2020-05-14 at 05 35 07)](https://user-images.githubusercontent.com/50739566/81924848-d9baee00-9609-11ea-95a6-02111a413224.jpg)
