### ISSUE TITLE
Password requirement bug

### ISSUE THREAD

**Issue by rainfarmer** [StrangeLoopGames/EcoIssues#15701]
This password, q123w 
returns error: "The Password field should contain at least 2 alphabetical characters and 1 digit."

This password worked qq123w
Seems password requires letters to be next to each other?

**Comment by D3nnis3n** [comment]
This is actually possible preventing people from activating their bought accounts and while one today did contact me via support not everyone probably does. I've elevated to high.

Alternativeley, please disable the password security requirements until a fix, as there is not really password security when people need to have something specific in a specific arrangement and the requirement can also be read on our public GitHub ... None of my 16 character passwords would actually pass the current password requirement, due to me explicitly not putting letters next to characters for security reasons ...

**Comment by denysaw** [comment]
Hotifxed on Production. Implemented your new requirements
