### ISSUE TITLE
Work Parties should split xp gained for work order

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#15786]
//TODO: for work parties, split the experience gained.

**Comment by mirasrael** [comment]
It already split experience between players who added labor. I dont think that changing it to reward xp to players who added resources is correct thing, because we dont have this for regular work orders and you force work order creator to go through work party and add own resources to work order to get xp for this.

**Comment by mirasrael** [comment]
Close this issue, because discussed with John it was because of obsolete comment.
