### ISSUE TITLE
[0.9 Staging-1515] Can't effectively limit CO2 emissions with laws

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15865]
We tried passing some CO2 production limits on the test server only to find our options were limited to:

1) Limit how much time per hour someone can spend creating infinite pollution:

![image](https://user-images.githubusercontent.com/964559/79674331-fbee5700-8196-11ea-9dcd-cb341820d27c.png)

2) Tax them

We tried setting a limit of how much CO2 someone can create per hour / per day, but the best we could find was "this is how much CO2 you can create per age of server", which is not great - it means the law would retroactively apply to the whole server age or something and not curb the emissions as we wanted.

We were also thinking about doing some "carbon credits" system, where people would receive a certain amount of currency per day and they would be taxed in that currency, but then remembered that a person can only mint one type of currency ever and it's hard to limit them on how much they can mint, so that wasn't an option either.

So it would be nice to have an option to create a law saying "you can create this much pollution per day / hour".

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Try to create a law limiting how much CO2 people can create per day from the moment the law is passed (not from start of the server or the like, not how much time they can pollute)

3) Expected behaviour
- You should be able to create that law easily

4) Actual behaviour
- Can't create such a law

**Comment by WiseProjects** [comment]
Tried to count pollution by the following stats with no luck:
Time Polluting - always has a value 0-10 and never rise
Tons Of Pollution - always has a value 0 and not cumulate
Ton Per hour - seems only working option but with constant pollution can differ


Also tried to record these values with custom stats but they also not cumulating:
![image](https://user-images.githubusercontent.com/58177535/79674562-f4599d00-81ec-11ea-8ace-124de3f1dc07.png)
![image](https://user-images.githubusercontent.com/58177535/79674565-fc194180-81ec-11ea-9e09-a179ffe9b14d.png)

**Comment by mirasrael** [comment]
@johnkslg seems we are missing functionality for aggregating stats for some period. In example for 
![image](https://user-images.githubusercontent.com/475445/80209192-44e05880-863a-11ea-9e6e-3d301aa467ec.png)
it makes sense to use check not for the single action, but for period of time.

**Comment by mirasrael** [comment]
@WiseProjects "Tons Of Pollution" is not 0 actually, but it is usually < 0.01 so not displayed because of rounding. Should be fixed with PPM.

**Comment by johnkslg** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/15883

**Comment by johnkslg** [comment]
With the fix for #15883 added, this case can be handled too.
Action Count value can now define the time range it wants more flexibly, either the past X hours or the most recent X block:
![image](https://user-images.githubusercontent.com/3536496/80265634-0c964580-864d-11ea-95c7-dd63e4fd1f5f.png)

Put some polish into how this is presented to the user as it could be a little confusing.  The description detects common cases like day and hour and sets them:
![image](https://user-images.githubusercontent.com/3536496/80265671-26378d00-864d-11ea-9079-7a259aabeea0.png)

And if you go low like .01 hours, itll convert to seconds, or minutes, as needed:
![image](https://user-images.githubusercontent.com/3536496/80265688-3485a900-864d-11ea-937b-f17f8172958e.png)

![image](https://user-images.githubusercontent.com/3536496/80265543-c0e39c00-864c-11ea-8777-c3d45fd32f24.png)

![image](https://user-images.githubusercontent.com/3536496/80265503-9f82b000-864c-11ea-99d2-bdc3a0532682.png)

![image](https://user-images.githubusercontent.com/3536496/80265358-2b480c80-864c-11ea-92c8-9e34d1e8a61d.png)


![image](https://user-images.githubusercontent.com/3536496/80265541-bd501500-864c-11ea-80c0-8f3f0d7aad1e.png)

**Comment by beastyn** [comment]
@johnkslg 
I did test it today but Law didn't catch pollution from my blast furnace.

1. I have a law like this
![bandicam 2020-04-28 17-56-44-812](https://user-images.githubusercontent.com/27898520/80491299-f5709400-897b-11ea-8735-9aff09aaa9dd.jpg)


I suppose, that means pollution from me will be prevented if i will make more than 0.4 ppm in 12 minutes

2. Im placing and launching blast furnace wich makes 0.72 ppm in 12 minutes.

But it won't prevent me from pollution.
Did I miss something?

**Comment by johnkslg** [comment]
Some wiley bugs crept in at the last minute. Refixed them.

With the law you made, youll be able to start polluting until you reach a total of .4ppm raised.  Turn on /civics debug to watch it go.

**Comment by WiseProjects** [comment]
@johnkslg Action Count was the only thing that worked, but still no way to count by source.
I guess you need to add time intervals for other options like tons of pollution/pollution time/pollution per hour
