### ISSUE TITLE
[0.9 Staging-1515] Can't check pipe status if there is a problem with the machine (including pipe status)

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#15876]
I tried setting up a combustion generator in a closed loop system with a waste filter. However, since the system wasn't running, the power generator couldn't produce anything, so the water filter wasn't working, etc. Both of them had issues with pipes among other things, but here's the kicker - you can't check the pipe status if there is a problem with the machine, including having their pipe status not working:

![image](https://user-images.githubusercontent.com/964559/79676936-25f84700-81a0-11ea-92de-990dae0d0c4a.png)

![image](https://user-images.githubusercontent.com/964559/79676924-006b3d80-81a0-11ea-882c-8b6070e7c93e.png)

It's a Catch-22.

1) Version
0.9 Staging-1515

2) Steps to reproduce
- Put down a combustion generator, mess up the piping
- Try to check the pipe status
- Can't check pipe status because pipes are messed up

3) Expected behaviour
- You should be able to check the pipe status regardless of the machine's status

4) Actual behaviour
- Can't check pipe status because pipe status is bad

**Comment by mirasrael** [comment]
You shouldn't need to check Pipes tab status if something wrong. You should see issue on Status tab. If it isn't enough or not clear enough then it should be improved.
But for me both Statuses is clear:
- You don't have connection to Water for input pipe (probably because Water polluted), we may improve display to show what it has on input.
- You don't have anything accepting Water for Waste Filter output. If this info wrong then make a separate issue.

**Comment by beastyn** [comment]
So, intended for now. If you have some suggestion for the improvement please use 
https://github.com/StrangeLoopGames/EcoSuggestions
