### ISSUE TITLE
USER ISSUE: Rubble sound playing all the time

### ISSUE THREAD

**Issue by fame1991** [StrangeLoopGames/EcoIssues#15884]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
I did nothing so dont know

**Expected behavior:**
Sound stops

**Actual behavior:**
Hearing rubble sounds the whole time /clearrubble command helps only shortly. Even with a large radius given as parameter it stops for 30 secs and comes again. Nobody is close to me mining on the server.

**Do you have mods installed? Does issue happen when no mods are installed?:**
No. Vanilla.

**Comment by SlayksWood** [comment]
@fame1991 Can you provide coordinates and saved file?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by Engimage** [comment]
I had this issue all the time.
The problem for me was on multiplayer. When another player mines underground near you, the rubble for you starts "dancing" randomly around causing the constant sound. This is because physics is handled on the PC of a player who created it, and there is a clear issue passing this info to other players.

In 8.3.3 on our run it was really funny to perform duo mining. One person breaks rocks, another collects. As a collector you could see a hailstorm of rubble flying around while a breaker sees them fall down gently.

**Comment by SlayksWood** [comment]
@Engimage You describe another issue #14219

> Nobody is close to me mining on the server.
So i merge it to #14219
