### ISSUE TITLE
[0.9-1515] Work party payment UI bugs

### ISSUE THREAD

**Issue by Engimage** [StrangeLoopGames/EcoIssues#15952]
There are 2 bugs and I will show them in a consequence

1. When we want to alter the payment
![image](https://user-images.githubusercontent.com/38317412/79973111-a7e9b800-849f-11ea-97b3-7a02e5a10306.png)
The configiration windows for that appears
![image](https://user-images.githubusercontent.com/38317412/79973255-e8e1cc80-849f-11ea-870d-1579133ba2e9.png)
However the window only has the amount value visible and not many other details of the payment. You have to re-pick Currency payment to get the desired fields visible such as currency, account.
![image](https://user-images.githubusercontent.com/38317412/79973466-4544ec00-84a0-11ea-8097-70d0ea475aec.png)
This is very confusing and uncomfortable.
**Now we have to accept this to continue to the second bug.**

2. When you have accepted the new payment configuration we can see the order of rewards has changed in the Payment section. 
![image](https://user-images.githubusercontent.com/38317412/79973663-a5d42900-84a0-11ea-9dfa-5d2893e67997.png)
Now we should click on the gear icon to configure reputation reward.
However after this we will still get into currency payment configuration, which means gear icons were not re-sorted as well as rewards did and are now pointing to a wrong line.

**Comment by SlayksWood** [comment]
@Engimage Thank you for the report.
You can open additional setting with this button(mouse over it):
![image](https://user-images.githubusercontent.com/45708377/79975897-5a237e80-84a4-11ea-8fa6-f8f18c652104.png)
@johnkslg @olegshegai 
1. Maybe make this gear always visible?
![image](https://user-images.githubusercontent.com/45708377/79975337-7d99f980-84a3-11ea-98c8-0204c8d62a4f.png)
2. Yea, it's a bug. Never found it, because I know about this additional button.

**Comment by SlayksWood** [comment]
Still an issue:
> 2\. When you have accepted the new payment configuration we can see the order of rewards has changed in the Payment section.
>     ![image](https://user-images.githubusercontent.com/38317412/79973663-a5d42900-84a0-11ea-9dfa-5d2893e67997.png)
>     Now we should click on the gear icon to configure reputation reward.
>     However after this we will still get into currency payment configuration, which means gear icons were not re-sorted as well as rewards did and are now pointing to a wrong line.

Maybe don't hide any information at all? it always should be like:
![image](https://user-images.githubusercontent.com/45708377/84354778-232b3880-abca-11ea-8d78-3156ff7bedef.png)
Because we have a big window and information is not enough to fill it. Why hide it?
Also you can a little aligning this window:
![image](https://user-images.githubusercontent.com/45708377/84354934-6edde200-abca-11ea-9b3c-b75ddb3eff2c.png)
