### ISSUE TITLE
[0.8.3.3] Duplication when server restart

### ISSUE THREAD

**Issue by Tintin5535** [StrangeLoopGames/EcoIssues#15963]
I was on a server (not an official one) and when the admin start the restart i had a steam truck in my inventory. 10 secondes before the server kick me i place the steam truck on the ground. After, when i reconnected to the server i had a truck in my inventory and ther was also the truck on the ground.
I think it's a save problem because the inventory is save before the world map so if i put something on the ground before the map save but after the inventory save the server will consider the objet twice.

**Comment by SlayksWood** [comment]
Thank you for the report.
It will improve in 0.9.0. And I assume it was happened because you server admin restarted server incorrect. 
Now you can't close server by "X".
@Tintin5535 
Tell the server administrator that it is necessary to close the server by writing "exit" in the console:
![image](https://user-images.githubusercontent.com/45708377/80097717-6bd45700-8574-11ea-9c52-1c063a36dec2.png)
and press enter
