### ISSUE TITLE
[9.0 1524] Road lines with bloom and global illumination on are too glowy

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#15978]
![image](https://user-images.githubusercontent.com/61889138/80133104-a1893800-8594-11ea-9482-277936c7e655.png)

^^ With both on

![image](https://user-images.githubusercontent.com/61889138/80133153-b239ae00-8594-11ea-87dd-f58026a335d0.png)

^^ Bloom turned off

![image](https://user-images.githubusercontent.com/61889138/80133191-c382ba80-8594-11ea-8fd2-a76b194af387.png)
Bloom on but global illumination off

**Comment by keegan-o** [comment]
This is now fixed in staging with my lighting updates--- HOWEVER! Everything is capable of being blown out now, but the key difference is that if you get close or have it fill more of your screen, auto-exposure will adjust the brightness down. So the blown out things can only take up a small amount of your screen. Also, this effect should be significantly reduced by the changes I made to GI (it's a lot less bright now).
