### ISSUE TITLE
[0.9] Farmer Table is not more in the Workbench ? Issues or Plan ?

### ISSUE THREAD

**Issue by REPOSEECO** [StrangeLoopGames/EcoIssues#16016]
Now you can't start Farming without one with Carpenty Skill.

**Comment by WeaselDog** [comment]
Thanks for the feedback. We moved around some of the requirements for early crafting tables but we should not require skilled Carpentry labor to start Farming.

**Comment by SlayksWood** [comment]
Why do I need to take Farming to craft Farmers table? Maybe Farming 0 will be enough?

**Comment by mirasrael** [comment]
You don't need to get Farming - you can ask Farmer for craft (like you asked Carpenter before). Only recipes except Farming as far as I can see is for Fertilizer. And we should expect at least one Farmer on this stage. Also Fertilizer doesn't make much sense without Farmer.

**Comment by WeaselDog** [comment]
This is intentional. Previously it was Level 1 Carpentry so you had to have Carpentry to make a Farming Table.

**Comment by trickenso** [comment]
> You don't need to get Farming - you can ask Farmer for craft (like you asked Carpenter before).

If you're the (first) farmer on a server, you can't ask any other farmer to craft it for you. Unlike other professions like Masonry and Carpentry, a farmer can't craft their own products until reaching level 1 and crafting the crafting table.
I'm confused why, as a Farming specialist, learning level 0 Farming unlocks recipes I cannot use, because it requires Level 1 Farming to craft the table. If you need level 1 farming to craft the table, then what use is level 0 farming?

> This is intentional. Previously it was Level 1 Carpentry so you had to have Carpentry to make a Farming Table.

This might make more sense, since the Farming progression would be locked behind collaboration, rather than level 0 and level 1 being bundled together for no apparent reason.

Carpentry and masonry tables are both accessible without even reading the skill scroll, so the respective professions can craft their products at level 0. At least allowing the Farmer's Table to be crafted at level 0 Farming would stop this weird progression lump.

**Comment by beastyn** [comment]
@WeaselDog do you plan to look into it a bit more or just go as it is for now?

**Comment by trickenso** [comment]
How it is now works fine from my perspective. Just a design/balance consideration.
