### ISSUE TITLE
Trees don't die where are too crowded

### ISSUE THREAD

**Issue by zajcom** [StrangeLoopGames/EcoIssues#16021]
Trees doesnt die when are plant by player, also they ignore any minimal disctance and can live in very crowded area.

![obraz](https://user-images.githubusercontent.com/62840280/80314127-de9d3680-87ef-11ea-9daf-e6046de9b01e.png)

Step to reporduce:
plan 5x5 squer of trees (any type)
wait few days, and all trees will grow up. None of them will day, 

Version: 
0.9 beta - staging 1526

**Comment by johnkslg** [comment]
I think there is code in farming that specifically prevents this, so you can have nice fields without dead vegetables in them. Lets find that and disable it for trees specifically, can stay on for vegetables.

**Comment by mirasrael** [comment]
They actually dying, but with very slow rate (it is limited to something like 1% or 0.1% of population per tick). I think we can prevent planting in hostile areas (so it will just show you a message and won't let you plant).

**Comment by MazonDel** [comment]
@mirasrael From what I saw, plants/trees that are planted by a player receive the "Tended" flag and are ignored from consideration for deletion in the PlantSpawner.KillPlants() method called by the PlantSpawner.Apply() method. The only thing that overrides this protection in that space is the Habitability modifier which only takes into account the temperature, moisture, pollution, and saltwater.

Two parts that I was going to propose as a solution to this problem were thus:

Add in the command to check the plantSpecies.GetMostCrowdedSpaceUsed() value for overcrowding. If this returns a result >1.0 then the area is overcrowded, so allow that to flag the "KillTended" exception in addition to the habitability modifier. This would cause an issue for planted items like corn and such, but we could also just arrange it so this check is only done on trees.

The second part would be to implement the code I'd started for solving the Old Growth Redwoods inter-penetration issue. The idea was to give trees a "thickness" and trees couldn't spawn or be planted within a certain range of the others. This code wasn't implemented leading into 9.0 because it had certain affects on world-generation we didn't want to deal with yet, but it IS complete.

**Comment by johnkslg** [comment]
Preventing planting when too close to other things should be sufficient I think, and give the most user feedback. 

When doing the 'too close' check, can make a check to a 'Ignore Separation Distance When Planting' bool on the PlantSpecies (or some such thing)

**Comment by WeaselDog** [comment]
Thanks for reporting this.
In update 9.5, it will prevent placing if they are too close together. This setting is configurable how much distance is required.
