### ISSUE TITLE
[0.9 Staging-1526] Gold surface generation seems very common

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16031]
I think sometime recently the gold ore generation parameters might've gotten tweaked or something because a few people have noticed a lot of gold ore patches on the surface in the HW server. I've been playing a bit of a private server recently and the map has 5+ big patches of gold that appear on the surface as well. It might be worthwhile to tweak the generation parameters a bit...

1) Version
0.9 Staging-1526? Maybe a few iterations earlier?

2) Steps to reproduce
- Generate a random world
- Check the surface - you're likely to get multiple surface-level generous gold ore deposits

3) Expected behaviour
Gold ore shouldn't be that common on the surface.

4) Actual behaviour
It's easier to get gold ore now than copper or even iron in some cases...

**Comment by keegan-o** [comment]
I will say that large on the surface gold was sort of intentional because in the future we will be drastically reducing the concentration of the ore-- so that you have to strip mine a ton more of it in order to get any significant gold ore. But, for 9.0-- since this isn't hard to change, it does make sense to not have it spilling everywhere. I'm lowering it underground a fair bit so that it is not so superficial and easy to immediately find. Of note though, is that it is also hiding in plenty of other places other than just the surface of mountains, and those deposits will become more important when we do the concentration thing.

**Comment by keegan-o** [comment]
(in the future, the balance intention is that there are easy to find deposits in the mountains, and you should use those up and then have to look elsewhere-- so if they provide all you ever need in the mountains superficially then that is too much)

**Comment by keegan-o** [comment]
All that said, the copper outcrops could be a bit silly in tundra/ice as well, so I'm also lowering those.

**Comment by keegan-o** [comment]
https://github.com/StrangeLoopGames/Eco/pull/6060
