### ISSUE TITLE
Profile minimap

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16072]
See what's slow about the minimap currently.  Here are some ideas that could lead to performance improvements:
- Don't update constantly, queue up updates and apply them over time, based on number of changes and distance from player. 
- Optimize the mesh to remove polys in flat areas

The webpage minimap displays without lods and is blazingly fast to load and display.  Lets see why the client is so much slower.  I dont want to replace the in-game one with textures, even zoomed out, because that removes depth and shadows and what makes our minimap unique.  I also dont want to minimap rendering methods that we have to support going forward. Building on CPU and updating infrequently seems the way to go. 

Minimap needs to be optimized to take essentially no meaningful time to render.

**Comment by mirasrael** [comment]
Investigated different solutions and implemented probably the best option - with tessellation shader.
In comparison with other alternatives it has following benefits:
- It has significantly less vertices, because actively reuses vertices during tessellation;
- It is much more memory effective than other solutions, because you only need to define plane with patch rectangles (10x10 or 32x32 blocks) and all other vertices will be generated on GPU;
- You don't need to generate multiple meshes for different LODs. Instead you can dynamically generate required LOD depending on screen size;
- You can cull out on GPU on per patch basis, so it greatly reduces amount of geometry to render.
