### ISSUE TITLE
[0.9 Staging-1526] Skid, Excavator, Tractor don't have the correct block stack size?

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#16101]
I've been reading into some of the code and I think I found some problem with Skid, Excavator and Tractor inventory.

According to the code, Skid and Excavator have a stack size for blocks is 20 / 80, while a tractor has a stack size of 500 for seeds / food:

![image](https://user-images.githubusercontent.com/964559/80913158-52ab7300-8cf7-11ea-8df8-98c2ee6bac9e.png)

However, in-game those stacks are 10 / 20 and 100 respectively:

![image](https://user-images.githubusercontent.com/964559/80913173-78d11300-8cf7-11ea-9719-1f41d649624c.png)

![image](https://user-images.githubusercontent.com/964559/80913180-86869880-8cf7-11ea-856f-12fe95fe9627.png)

![image](https://user-images.githubusercontent.com/964559/80913189-943c1e00-8cf7-11ea-9f4b-2f9f2f922dee.png)

1) Version
0.9 Staging-1526

2) Steps to reproduce
- Spawn Skid, Excavator
- Dig - the stack size will be 10/20
- Spawn Tractor
- Load it with basic foodstuff - stack size will be 100

3) Expected behaviour
Stack sizes should be bigger than they are.

4) Actual behaviour
Stack sizes are rather small on those specialised vehicles.

5) Providing Log files
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/4570174/Player.log)

**Comment by beastyn** [comment]
from @WeaselDog 
The stack size in the vehicle is correct. You are able to manually stack items in the vehicles using the increased stack size. The issue is the code for moving stacks of items was changed a few weeks ago so that it doesn't check for increased max stack size when moving inventory. I can debug but I feel like someone else could fix it faster
