### ISSUE TITLE
Lumber Signs need a Material for Icon

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#16129]
Lumber signs still have the old style for icons. To convert them to the new style, we need a Lumber material for the icons.

**Comment by keegan-o** [comment]
lumber can be designated using the softwood/hardwood/generic material icons based on whichever it is (old art can use the generic one that is split between both for now); they will be different than the composite lumber items using those same materials because they will have 2 stars instead of 3 or 4.

**Comment by keegan-o** [comment]
but in the end it would be nice to have unique material icons for all materials, it is true. Still, as long as you can tell the difference based on tier (since there are no same tier varieties of any stone or wood material) I think this is a bit lower priority than some of the other lacking icons.

**Comment by WeaselDog** [comment]
Sounds good. I can take this one over.
