### ISSUE TITLE
USER ISSUE: lost soup

### ISSUE THREAD

**Issue by jasont44** [StrangeLoopGames/EcoIssues#16148]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
Look at the log of what was sold and bought from before the server crashed to what I have now		

**Expected behavior:**
I sold someone 200 bricks for 50 something veg soups.  The server crashed and when it got back up I had all my bricks back and all the veg soups that were in my truck were gone.  

**Actual behavior:**
Only 1 soup and all my bricks back.  I dont want bricks, i want soup.

**Do you have mods installed? Does issue happen when no mods are installed?:**
Only 1 soup and all my bricks back.  I dont want bricks, i want soup.

**Comment by jasont44** [comment]
my name is Jason.t.44 in game and in steam

**Comment by mirasrael** [comment]
@jasont44 So you had back your bricks and seller got back his soup? It is best scenario which may happen in case when server crashes. To avoid this the server should gracefully shutdown. It is OK to see rollback for 10-15 minutes otherwise.
We have another issues for improving situations when you can have incorrect state after crash (in example if you get money back and goods which you just sold or when you get items both in inventory and in stockpile), so closing this.
