### ISSUE TITLE
[0.9.0 staging-1540] Civics: pollution action count

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16159]
Coming from here #15865

Seems like we have a huge misunderstanding here (thanks to @WiseProjects for pointing).
1) Action count should count ACTIONS not PPM (laws from examples there are just wrong).

And action count doesn' work right.

I've created a law like this
![bandicam 2020-05-06 16-08-13-863](https://user-images.githubusercontent.com/27898520/81170263-d09ba280-8fb3-11ea-9c4b-a997f6546c4d.jpg)

Accordingly to this law I should not be able to make a pollute action more than 1 time in 3 minutes

I've statred to pollute with truck in 4:22
next  2 pollution actions were  in 4:23
And no any prevention.
![bandicam 2020-05-06 16-13-04-542](https://user-images.githubusercontent.com/27898520/81171193-68e65700-8fb5-11ea-909e-8cf79691d77d.jpg)

I will create separate issue for PPM parameters for counting pollution value

**Comment by johnkslg** [comment]
So this is complicated because Action Count doesnt apply to Pollution, because the actual pollution 'actions' happen at arbitrary timings (when you start a machine, and after X seconds of polluting).  In fact, the object is constantly releasing pollutions, so asking 'how many times' it has released pollution doesn't make sense.

So instead Action Count returns the sum of pollution it's released.  This is explained in a tooltip on the action:
![image](https://user-images.githubusercontent.com/3536496/81336726-b1a61a80-905e-11ea-9d36-23b9263b4a87.png)

Perhaps there is a better way to present this to the user. We could make 'action count' invalid when applied to the pollute event, and instead you need to perform custom stat queries like 'Pollution PPM released in last X minutes by user Y', and another one for time.

Thoughts?

**Comment by johnkslg** [comment]
Renamed some stuff that I think makes this more clear.
