### ISSUE TITLE
[0.9.0 Staging-1538] - Request - Some way for farmers to check crop maturity

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16150]
With the soil sampler now being locked behind Fertilizers, it's no longer possible for a farmer to check how mature crops are.

It could be a direct examine, or give back access to the soil sampler, or another tool, perhaps - just some way to check a plant before harvesting. Seems reasonable a farmer might have access to such information.

**Comment by WeaselDog** [comment]
Thanks for the feedback. We currently have Soil Sampler so that it only requires researching Fertilizer which is unchanged since the last update.

Can you clarify what you mean by being locked? Does the research feels like it comes too late?

**Comment by trickenso** [comment]
It totally makes sense to keep the soil nutrients information for the Fertilizers specialism, but depending where you spend your stars there's quite a long time between getting farming and having visibility of the growth of your plant, since that information is hidden until you have access to the soil sampler. It is not necessarily that the research comes too late, it's that I'm not sure why a farming specialist wouldn't be able to find out the maturity of the plants.

I would prefer not to rush Fertilizers before it's really necessary to get the soil sampler, just so I can check whether my beans are ready to harvest - perhaps you want to encourage people to take Fertilizers, or you expect it to be more necessary to take this specialism after balancing, in which case this will stop causing friction.

Especially in comparison with 8.3, this will give farmers much less information early on. Maybe it's in line with miners needing to research smelting to get access to drills for prospecting, in which case I'm sure people will get used to it - it just seems odd in comparison.

**Comment by WeaselDog** [comment]
So for this one it is already setup so we don't need to specialize in Fertilizers to craft a Soil Sampler, we only need to research Fertilizers. It was setup the same way in 8.3, but it probably felt like it came much sooner because it was very easy to research Fertilizer once Farming was researched. 

To solve this we will be adjusting the research costs for Fertilizer so there is not as big a gap between Farming and Fertilizer. From a design perspective, it is okay if Farmers are not able to check plant maturity during the Stone Age, but we don't want to delay it too much.

**Comment by trickenso** [comment]
Understood - thanks for the clarification.
