### ISSUE TITLE
[0.9.0 staging-1540] Civics: pollution legalization 

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16160]
Coming from here #15865

We still need to have a way to count:

1) Parameters from pollution in some amount of time. not for single action (for some period).
For example:

Time that I spent polluting in some amount of time
(for example, prevent me from polluting if I was polluting in 30 minutes already in the last hour. It should allow me polluting again when time pass and my counter will be refreshed)

2) I can't find a number of current total pollution
(so I can't make some arithmetics, say, stop everything from polluting if total pollution - trees pollution more than some value.)

*Add here if something else appear*

**Comment by johnkslg** [comment]
1. 'Time polluting' without regard to amount of pollution is tricky. What if you're running 10 furnaces? Is your time polluting 10x?  It's not clear, I think it's better to keep it to amount.
2. Those are good values we can plug in, I'll add that.

**Comment by johnkslg** [comment]
Added an environment statistic value:
![image](https://user-images.githubusercontent.com/3536496/81883842-268bbf80-954b-11ea-8476-8a91631cddb2.png)
![image](https://user-images.githubusercontent.com/3536496/81883855-2d1a3700-954b-11ea-945c-be25bfb7bd21.png)

**Comment by beastyn** [comment]
1) It looks like these stats are static and won't update with time

![bandicam 2020-05-15 16-04-57-885](https://user-images.githubusercontent.com/27898520/82049346-975be480-96cf-11ea-98c6-c88f0b78fdf6.jpg)
![bandicam 2020-05-15 17-13-56-672](https://user-images.githubusercontent.com/27898520/82049350-988d1180-96cf-11ea-9e6e-79e1aa5fff5c.jpg)

Here: Total CO2 is 325 but it was actually was much more at that time

And also CO2 from plants always 0
![bandicam 2020-05-15 17-08-48-190](https://user-images.githubusercontent.com/27898520/82049399-b3f81c80-96cf-11ea-9143-f1fc9df32368.jpg)

2) About citizens statistic:

How can I make a law for checking, how many PPM I was producing in a day?
If I want to turn off all the blast furnaces if they were producing more that X ppm in one day?

For now I can check ppm only per action, and if I have two blasts it will still count me as producing 3.6 ppm per hour. But Actually right now Im prosucing 7.2 PPM per hour.
And what if I want to check if not for an hour, but for 3 hours?

Here I have 2 woking blasts and it counts my pollution like 3.6 PPm per hour

**Comment by johnkslg** [comment]
1. It was using the first element instead of the most recent. Good find. Fixed
Also fixed animals with always zero pollution.

2.  You can do this with Citizen Statistic:
![image](https://user-images.githubusercontent.com/3536496/82100922-e437bf00-96bf-11ea-83f0-fce4ee97ea67.png)

Law above will display how much you've polluted in the current hour block:
![image](https://user-images.githubusercontent.com/3536496/82100976-07626e80-96c0-11ea-9bcd-69055e859869.png)

You could also do the 'last hour' which is different from 'current hour block', that will give you how much youve contributed in the previous 60 minutes (wheras the other rounds to the current hour).

**Comment by beastyn** [comment]
Yeap, it works, thanks
