### ISSUE TITLE
[0.9.0 Staging-1538] - Map markers disappear behind each other

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16196]
Steps to reproduce: Place two map markers close to each other - retreat to a good viewing distance with both in view so they overlap.

Expected behaviour: Map markers that overlap would both remain visible - perhaps by stacking or similar.

Actual behaviour: One marker almost entirely disappears behind the other, and becomes very easy to miss entirely because its opacity is nearly zero. In this example, the hidden marker in the centre of the screen is also further away than the one that is hiding it, which seems doubly weird:

![image](https://user-images.githubusercontent.com/48172405/81291169-36923380-9061-11ea-9d03-ce7434a2f03b.png)

**Comment by olegshegai** [comment]
@trickenso Hi!
There was a tricky case with distances, thank you for mentioning that.
As @SlayksWood suggested, a marker now becomes visible when the cursor hovers over it.
The fading is an intentional behaviour (we ended up with such design due to issues https://github.com/StrangeLoopGames/EcoIssues/issues/15076 and https://github.com/StrangeLoopGames/EcoIssues/issues/15500), but the feedback is very valuable, we will keep that in mind when we adjust the system in some future updates. Although it is not clear what exactly it will be.  As you can see in the comments, stacking can become messy (tests also showed, that higher opacity markers can flood the viewport).

**Comment by trickenso** [comment]
The hover is wonderful - thank you! This solves my problem of being unable to read the faded marker text, which is a huge improvement.
Understood it's a complex set of requirements - it's currently absolutely not game-breaking, so feel free to close this ticket.

Just an idea, but maybe something like an 'active quest' system - hides some of the clutter, but allows you to highlight the thing you're currently working on? This is in line with what has been said in livestreams about work parties being like a quest system. It's clearly a new set of features, though. I'm sure you'll come up with a great solution.

Again - feel free to close or move this as you prefer. Is there a ticket specifically for the future overhaul of this system?

**Comment by SlayksWood** [comment]
If I have item name in tooltip name it doesn't visible if you mouseover item link (tomato):
![image](https://user-images.githubusercontent.com/45708377/81655635-0bcc2480-943f-11ea-9dd0-c2a93e8c950b.png)

**Comment by johnkslg** [comment]
Probably the linktext is taking the mouseover event from the fader, because theyre in different gameobject hierarchies. I believe if they're in the same object hierarchy, then they will both get it

**Comment by SlayksWood** [comment]
I still have some unfading problem if I mouseover linked name:
![image](https://user-images.githubusercontent.com/45708377/87281534-fd13f380-c4fb-11ea-851d-9efa4b8bfee3.png)
mouseover words corn or beet:
![image](https://user-images.githubusercontent.com/45708377/87281325-c6d67400-c4fb-11ea-9b83-4892102c2322.png)
