### ISSUE TITLE
 [0.9.0 Staging-1542] Constitution vote ended after server restart/upgrade

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16197]
After Royal Otter restarted to upgrade from 1538 to 1542 the current vote for ratifying the constitution ended prematurely. The vote was only started ~7 hours earlier, it should have ran for 24 hours.

**Comment by SlayksWood** [comment]
And seems it finished successful with 50%/50%:
![image](https://user-images.githubusercontent.com/45708377/81395307-0d8aa500-912c-11ea-9aea-ecf81d43c625.png)

**Comment by beastyn** [comment]
Yeap, Had the same issue.
1) Place capitol
2) Srart ratification election
3) There were three active players. One vote Yes. One vote No
4) Server was working for about 3 hours, Election was on rails before server closing.
5) After restart election was finished.
![bandicam 2020-05-11 10-22-25-006](https://user-images.githubusercontent.com/27898520/81526624-8d558100-9371-11ea-911b-7510fcd93afa.jpg)

![bandicam 2020-05-11 10-23-45-219](https://user-images.githubusercontent.com/27898520/81526631-934b6200-9371-11ea-96f2-cb8b2162a891.jpg)

**Comment by johnkslg** [comment]
Added better handling of ties.

- If an election would end early because enough people have voted, but a tie is currently occurring, it will delay:
![image](https://user-images.githubusercontent.com/3536496/81987727-14fbf380-95ef-11ea-8e7c-a53f6d8afcfa.png)

- If the full time of the election passes and tie is not resolved, it fails:
![image](https://user-images.githubusercontent.com/3536496/81988040-a703fc00-95ef-11ea-9fc0-d8014369552d.png)

**Comment by henrikolsson** [comment]
@johnkslg I may be misunderstanding your comment, but this issue was not about ties.

It was about the election ending prematurely after restarting the server. I hope this is also fixed?
