### ISSUE TITLE
0.9-1544 moving over composite "float stairs" is not flat

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16226]
![изображение](https://user-images.githubusercontent.com/4980243/81470621-4aba6a00-91f4-11ea-81b7-1a0902041cb0.png)
https://youtu.be/FoB5oXdZ83Q

**Comment by keegan-o** [comment]
there are still questions about which collider we want because switching them all to smooth means vehicles etc could be driven up stairs. Anyways, I set these to be the same (smooth). Hewn Logs, etc, have always had the different colliders, so do the solid versions of these sets-- I don't think it's a big issue. But if it is annoying you in gameplay, feel free to open more for others that should be changed.

**Comment by elfl0rd** [comment]
> means vehicles etc could be driven up stairs

Can't see any problems with it.

> I set these to be the same (smooth)
Thank you!
