### ISSUE TITLE
Lighting experiments: kick up ambient occlusion, try to make sky a diffuse light source

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16233]

**Comment by keegan-o** [comment]
the 'try to make sky a diffuse light source' is the very very difficult one here-- probably will not be possible with settings tweaks. The effect you are imagining would likely require a procedurally generated mesh that matches the elevation of the whole world on a block by block basis so that it is far enough away to not be too bright and yet close enough to have an effect on anything. Just a big square GI object in the sky would be much too far away to have any effect on the landscape.

**Comment by johnkslg** [comment]
The gi system we're using is meant to have a feature for this I know, perhaps its just a matter of configuring it? 
![image](https://user-images.githubusercontent.com/3536496/81623549-a9c0e000-93a8-11ea-8b5a-91d34c405653.png)

**Comment by johnkslg** [comment]
In their examples: 
![image](https://user-images.githubusercontent.com/3536496/81623576-c4935480-93a8-11ea-8287-7c0dfe0df0ce.png)

**Comment by keegan-o** [comment]
found the most relevant settings I think, it's these!

![image](https://user-images.githubusercontent.com/14983165/81630146-af72f180-93b9-11ea-9ce7-daffa8984a44.png)

They do make a pretty big difference, looks like this will amp up the lighting in quality as it descends from the sky. This won't make a big difference for cave entrances and such like those minecraft shots but at least the AO stuff helps with that a bit.

**Comment by keegan-o** [comment]
I'll be setting them to this:
![image](https://user-images.githubusercontent.com/14983165/81630238-ecd77f00-93b9-11ea-8040-64da1451ab53.png)

**Comment by keegan-o** [comment]
fixed in https://github.com/StrangeLoopGames/Eco/pull/6077

![image](https://user-images.githubusercontent.com/14983165/81760428-017c4b80-947c-11ea-8e27-3bfcc2e8b594.png)
