### ISSUE TITLE
Ashlar stone - need additional part for brace.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#16270]
Now - you cannot make brace structure bigger than 2 blocks
![изображение](https://user-images.githubusercontent.com/4980243/81670188-edbaf000-944f-11ea-8563-5f454dee07fd.png)

**Comment by trickenso** [comment]
As well as having this auto-detect, could it be placeable as a separate piece? This kind of rounded edging might have uses independent of the brace corner.

Also, the side brace might benefit from a mirror image, or being made symmetrical:

![image](https://user-images.githubusercontent.com/48172405/81672998-df1a0c00-9442-11ea-9607-ce93a69bf0ca.png)

Is there maybe a case for a 'facing' block to connect braces together into a panel?

![image](https://user-images.githubusercontent.com/48172405/81672897-bdb92000-9442-11ea-8126-9f93b57c4e8c.png)

The block elfl0rd suggested would work as a smooth edging piece in this case, but you might want the option to connect them together.

**Comment by keegan-o** [comment]
The issue with panels is then you have solid blocks that are very thin-- which can result in weird things/building possibilities. However, I do like the idea of them being available. Blocks that are that thin and on the edge of the space rather than center can also make it confusing or frustrating to place world objects (also, weird-- like hanging lights would then be place-able against mostly empty air in front of the panel). We might be able to add them with designations that avoid those possibilities though.

**Comment by keegan-o** [comment]
Making the braces symetrical could be good for increased flexibility, I will see how easy it would be to do that and how it would look.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/c7bebcc9-940e-40ba-ae05-8c19ed7dd596)
Will be in 9.1!
