### ISSUE TITLE
[0.9.0 Staging-1542] - Steam tractor modules show in 'Tool' filter

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16272]
I would expect these to only show in 'modules' or 'upgrades' or perhaps 'vehicles':

![image](https://user-images.githubusercontent.com/48172405/81672261-cc530780-9441-11ea-81ea-61d2d10e77d0.png)

**Comment by SlayksWood** [comment]
@WeaselDog take a look, please. May be it's intended?

**Comment by WeaselDog** [comment]
Thanks for the feedback!

This is intentional for now. We had an opposite report at one point that they were not included in tools, so there are alternate opinions for where it fits best. When a new player is searching for tools, it is nice to know they have Steam Tractor tools as an option.

We made an effort to reduce the number of categories in the filter so I am hesitant to reintroduce the "Modules" category just for them. We are planning to expand on attachments for vehicles so we will add a separate category for them at that time.

**Comment by trickenso** [comment]
Makes perfect sense! Thanks for the clarification.
