### ISSUE TITLE
 [0.9.0 Staging-1542] Server restart caused users to not be part of "Active" temporarily

### ISSUE THREAD

**Issue by henrikolsson** [StrangeLoopGames/EcoIssues#16284]
Royal Otter crashed ~1 hour ago and was restarted. Sometime during this active users were no longer part of "Active", maybe civics tick during server startup?

Noticed because the elected titles had a requirement for the occupants to be part of "Active" and the holders were removed. 

![image](https://user-images.githubusercontent.com/982322/81746263-749ab780-94a6-11ea-862b-55bcc77d18ae.png)

**Comment by SlayksWood** [comment]
I can't it reproduce, but we have this issue before #15526
@D3nnis3n Can you provide save files before last restart?

**Comment by D3nnis3n** [comment]
That's the closest i can get, about half an hour. It did never actually crash, though. The server just didnt accept people in, it was running.

https://download.godsofwar.de/eco/qa1.zip

**Comment by beastyn** [comment]
@johnkslg take a look please.
Just start the server with  this save and see how people will be kicked from active,
Still can't repro this one

**Comment by johnkslg** [comment]
Managed to repro with test world, fixed it by making demographics and titles save their cached list of users.

Note: since the fix involved changing what is written to the save file, you wont be able to repro the fix in the save anna linked.  But you can repro it by making a new world with an elected title requiring members to be 'active' then restarting the server and seeing that it doesnt drop them (which I did).

After reload:
![image](https://user-images.githubusercontent.com/3536496/82259503-8f3eb780-9910-11ea-852f-143be86ab55a.png)
