### ISSUE TITLE
[0.9.0 staging-1548] InvalidOperationException during saving world

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16290]
Step to reproduce:
- generate new world in one language (in my case it was russian)
- when server will started, change language to another (spanish). To full switch language you need to restart server. Ctrl+C in command line. Dump:
```
Exception: InvalidOperationException
Message:Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
Source:System.Windows.Forms

System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Eco.Server.Startup.StopAsync()
   at Eco.Server.Startup.RunAsync(IHostApplicationLifetime applicationLifetime)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
```
I tried to switch with other languages. Every time I have this exception.
I can load save files, but I have a little timeback.

**Comment by Alteraner** [comment]
Hello, not sure if this issue is the same but today had very long error in the server log:
`[11:03:16] Eco.Plugins.Exceptions.NetworkServerException: Exception during SendMessage (netEvent = ClientUpdate, client = John T.):
{
  objs:
  [
    {
      id: 2 (int),
      chunks: [ Empty ]
    },
    {
      id: 39515 (int),
      state: 66 (byte),
      pos: (872.81274, 60, 256.81854) (Vector3),
      dir: (-0.806511, 0, -0.591219) (Vector3),
      time: 528344.0261541997 (double),
      health: 3 (float),
      a: 0 (float)
    },
    {
      id: 939 (int),
      state: 7 (byte),
      pos: (871.025, 71, 40.735996) (Vector3),
      dir: (-0.36639705, 0, -0.9304586) (Vector3),
      time: 528344.0261832997 (double),
      health: 4.5 (float),
      a: 106.358376 (float)
    },
    {
      id: 6010 (int),
      state: 2 (byte),
      targetPos: (882.1189, 66, 174.96568) (Vector3),
      targetTimeTotal: 23.727356 (float),
      targetTimeRemaining: 17.102383 (float),
      time: 528344.0262580998 (double),
      start: 528337.4012819998 (double),
      route: 161 bytes (byte[]),
      health: 1.5 (float),
      a: 0 (float)
    },
    {
      id: 947 (int),
      state: 6 (byte),
      targetPos: (790.01965, 80, 61.19727) (Vector3),
      targetTimeTotal: 3.7370713 (float),
      targetTimeRemaining: 3.6972222 (float),
      time: 528344.0262754997 (double),
      start: 528343.9864248998 (double),
      route: 33 bytes (byte[]),
      lookPos: (791, 80, 61) (Vector3),
      health: 4.5 (float),
      a: 0 (float)
    },
    {
      id: 2203 (int),
      state: 6 (byte),
      targetPos: (825.13104, 80, 27.848892) (Vector3),
      targetTimeTotal: 10.512932 (float),
      targetTimeRemaining: 10.476498 (float),
      time: 528344.0262962998 (double),
      start: 528343.9898606997 (double),
      route: 97 bytes (byte[]),
      lookPos: (825, 80, 28) (Vector3),
      health: 1 (float),
      a: 0 (float)
    },
    {
      id: 6596 (int),
      state: 65 (byte),
      targetPos: (642.1738, 58, 186.51993) (Vector3),
      targetTimeTotal: 17.00302 (float),
      targetTimeRemaining: 16.967556 (float),
      time: 528344.0263380997 (double),
      health: 2 (float),
      a: 159.05327 (float)
    },
    {
      id: 5913 (int),
      state: 2 (byte),
      targetPos: (604.73096, 70, 87.86287) (Vector3),
      targetTimeTotal: 5.231304 (float),
      targetTimeRemaining: 0.05190234 (float),
      time: 528344.0263443998 (double),
      start: 528338.8469409997 (double),
      route: 33 bytes (byte[]),
      health: 1.5 (float),
      a: 0 (float)
    },
    {
      id: 5995 (int),
      state: 6 (byte),
      targetPos: (800.0742, 75, 143.18573) (Vector3),
      targetTimeTotal: 2.0997636 (float),
      targetTimeRemaining: 2.0596578 (float),
      time: 528344.0264046998 (double),
      start: 528343.9862970997 (double),
      route: 33 bytes (byte[]),
      lookPos: (800, 75, 143) (Vector3),
      health: 1.5 (float),
      a: 15.663025 (float)
    },
    {
      id: 163 (int),
      players: 426 compressed bytes (byte[])
    }
  ],
  destroyed: [ Empty ],
  newObjs:
  [
    {
      id: 39515 (int),
      state: 2 (byte),
      pos: (872.81274, 60, 256.81854) (Vector3),
      type: 'Crab' (string),
      controller: 45281 (int),
      swimming: True (bool),
      targetPos: (868.9878, 60, 254.01466) (Vector3),
      targetTimeTotal: 13.695148 (float),
      targetTimeRemaining: 9.485099 (float),
      time: 528344.0255153998 (double),
      start: 528339.8154641998 (double),
      route: <invalid binary value: null>,
      health: 3 (float),
      a: 0 (float)
    }
  ]
}
   at Eco.Plugins.Networking.NetworkServer.SendMessage(NetworkEvent netEvent, BSONObject bsonObj, Object connection)
   at Eco.Plugins.Networking.NetworkServer.SendMessageWithViews(NetworkEvent netEvent, BSONObject bsonObj, IMvcNetClient client)
   at Eco.Plugins.Networking.NetworkServer.DeliverMessage(NetworkMessage message)
   at Eco.Plugins.Networking.NetworkServer.DeliverMessages()
   at Eco.Plugins.Networking.NetworkServer.Run(CancellationToken token)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Shared.Serialization.SimpleBSON.EncodeBinary(MemoryStream stream, Byte[] buf)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.SimpleBSON.EncodeArray(MemoryStream stream, BSONArray array)
   at Eco.Shared.Serialization.SimpleBSON.EncodeElement(MemoryStream stream, BSONValue v)
   at Eco.Shared.Serialization.BSONObject.EncodeNow(MemoryStream stream)
   at Eco.Plugins.Networking.NetworkServer.SendMessage(NetworkEvent netEvent, BSONObject bsonObj, Object connection)`

**Comment by Alteraner** [comment]
[log_200522111309.log](https://github.com/StrangeLoopGames/EcoIssues/files/4671530/log_200522111309.log)

Hello, sorry, still see a lot of exceptions in the server log. See attached one...
