### ISSUE TITLE
World objects should remember their name if they are removed and then placed again

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1630]
store it in the world object item probably

might want to come up with a generalized solution for this - maybe just store the entire WorldObject on WorldObjectItem?

**Comment by SeanAtr0n** [comment]
could store the name in the item, worldobjectitem is already stored in worldobject

**Comment by MarjieAVolk** [comment]
It would be pretty nice to store all the world object state in the item.  Another case where this would be awesome is vehicles + linked inventory settings, where if you pick up your cart because it got stuck then all your settings get lost and then you get confused as to why your stuff isn't getting output, etc etc

**Comment by MGrand3** [comment]
Bit late to the party, but it would be helpful if the store saved the offers when you broke it and replaced it.

**Comment by metachronism** [comment]
cut
