### ISSUE TITLE
[0.9.0 staging-1550] Time commands issue.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16317]
- [ ] 1. Name and shortcut for command "/time resettime (/resettime)". I think it should be enough "/time reset". So we don't need short cut with reordering words or add another shortcut.

- [x] 2. After fixing command "/time set" you can break Moon. It doesn't always happen, but often enough.
I had day time, then I changed time to 24 and then tried to change it to 17 and moon was broken.
![2020 05 15 Moon breaking](https://user-images.githubusercontent.com/45708377/82016113-f3e7e100-9688-11ea-81f7-c17a23641e0b.gif)

- [x] 3. /ff 0 doesn't work (/ff 1 works) if you set Allow Fast Forward = False:
![image](https://user-images.githubusercontent.com/45708377/89030428-1f4da400-d339-11ea-9e2f-6895e19104b9.png)

**Comment by beastyn** [comment]
Myve its connected
/ff run fastforward
/ff 0  won't stop fastforward

**Comment by redwyre** [comment]
It looks like /ff 0 doesn't work when AllowFastForward in the sleep config is false.

**Comment by elfl0rd** [comment]
Also as i think
If /ff run fastforward, second /ff should stop fastforward

**Comment by johnkslg** [comment]
When time is held in place with '/time set x', it will reset time every 5 seconds so you see it skipping like that. This is fine because its a debug command. 
If you do this when fast forwarding it will skip more.
Not really concerned about this case since theyre both debug commands. lets ignore this.

Could not repro /ff 0 failing: 
![image](https://user-images.githubusercontent.com/3536496/82512911-53e5e980-9ac6-11ea-843f-8d1a23fe1e9a.png)

**Comment by redwyre** [comment]
@johnkslg for /ff 0, do you have a sleep config file? It only happens when AllowFastForward is true

**Comment by IcedForge** [comment]
I think the reason that the moon breaks at setting time to 24 is because its resets itself, by the time it gets into position on the screen, its a new time cycle so it wants to shift a full lap around again to reset back to 24 position.

**Comment by WeaselDog** [comment]
Fixed the part about /ff 0 which was admin command
