### ISSUE TITLE
[0.9.0 staging-1550] Glitch with selecting trigger parameter

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16319]
Not for every triggers, seems for parametrs which has in parameter filter: election process, titles, demographics and etc.
Step to reproduce:
- create some election process
- choose Vote trigger, for example:
![image](https://user-images.githubusercontent.com/45708377/82019592-319c3800-9690-11ea-9b17-cde9b37be0a2.png)
- select certain election processes:
![image](https://user-images.githubusercontent.com/45708377/82019648-4b3d7f80-9690-11ea-91a8-c16a4ca62aa9.png)
- submit: 
![image](https://user-images.githubusercontent.com/45708377/82019663-51336080-9690-11ea-8253-cbf8a5146ae7.png)
- open filter another time. I don't have any selected election. Select the same elections:
![image](https://user-images.githubusercontent.com/45708377/82019799-863fb300-9690-11ea-8e75-a13706a82b4b.png)
- I have 4 selected election instead 2, but i still have selected only 2 elections:
![image](https://user-images.githubusercontent.com/45708377/82019838-98215600-9690-11ea-849d-d01f4e73478f.png)

**Comment by gzatravkin** [comment]
Looks be related with https://github.com/StrangeLoopGames/EcoIssues/issues/16433

**Comment by johnkslg** [comment]
Hows this related to #16433? Theres no serialization in the process to repro this bug. Can you investigate more?

**Comment by gzatravkin** [comment]
When it recivies BSON in client, it can't process right list<object> of entries (from another issue, Which may contain both types and views). Entires of gamerpicklist ends up with N empty bsonobjects at client side after sync with server. 

Basicly client can't know that what he recivies is possible to cast to views in order to have correct values.

Possible solution - create some struct at server and use it instead of list<object>, like
{
Type t;
View v;
}.

So depends on how #16433 will be solved it may be fixed too.

**Comment by gzatravkin** [comment]
@mirasrael did you checked #16433? How you going to solve it?
