### ISSUE TITLE
[0.9.0 staging-1542] Work Party - need hint for draft placement

### ISSUE THREAD

**Issue by NN-Mike** [StrangeLoopGames/EcoIssues#16347]
1. Version 0.9.0 staging-1542
2. Started to create a work party, did not modify any defaults. It started one for a charred tomato recipe that I had queued. Cancelled
The order of tomatoes was cancelled - it did warn about a draft in progress for a work party and if I wanted to continue cancelling - which I confirmed.
Picked up the campfire and returned to the contract board, now nothing is listed and I cannot create a new work party as I still have a draft - but cannot access it.
3. Expected behavior.
The draft should still be visible to cancel, or actually be cancelled
4. Actual behavior.
No work party listed and unable to create a new work party
![image](https://user-images.githubusercontent.com/54982803/82113641-7e931380-974f-11ea-817b-40aaeed29379.png)

**Comment by trickenso** [comment]
The workaround is to click the 'Work' icon that looks like a notebook at the right of the screen, and edit/delete the draft from there. It's definitely not obvious that this is possible.

It might solve this problem if a player's own drafts were visible from the Contract Board.

Note: this also applies to contracts.

**Comment by NN-Mike** [comment]
Was able to delete this inside "Work" as described, but didn't have a notification here either.

**Comment by beastyn** [comment]
@NN-Mike you didn't have party in your work list in the right panel?
Or you didn't get a notificatoin, when draft was created?

Can we have a log from that session?

I can't reproduce it right now and always get notificationa bout created work party or created draft.

**Comment by NN-Mike** [comment]
It may have initially given me a notification because I have them now. But I came back to the game later (Later Login) or deleting the campfire meant I didn’t have a (1) when I went to delete it as per trickenso’s suggestion.

The main issue is awareness of where the draft is as the error didn’t give many clues, but this might just be a learning thing as I see all work parties are here.

**Comment by trickenso** [comment]
Maybe I can clarify this:

- It is very easy to miss the notification: the notification is on a different screen than the contract board, it is small and unobtrusive, and there is no guarantee you have learned about notifications at this point.
- If you miss the notification, there is no other indication there is a draft, except if you look on the 'Work' screen (which is also easy to miss).
- The error (shown in NN-Mike's screenshot) does not tell you where to find the draft - it only states that it exists, but it is otherwise invisible.
- This error only shows from the contract board, which doesn't display the draft contract/work party.

Suggestion: Show draft contract/work party on the contract board.

Quick fix: Change error text to explain where the draft can be found.

**Comment by beastyn** [comment]
@NN-Mike @trickenso
we have some plans for changing contract board, so we will keep in mind this issue, for now we will add fast fix with hint in the error box 

@gzatravkin 
We need to add one little hint to the error for the contracts and work parties with not finished drafts:
![bandicam 2020-05-22 18-00-41-299.jpg](https://images.zenhubusercontent.com/5ec7555962ebd9185dc41217/498fb70d-12e5-4428-aa95-8379e92b4e60)

Something like:
You must finish posting <>  in the Work tab before posting another one.

Can we make name of a contract and work party here as a link with different color? So with click it will open a draft.

**Comment by SlayksWood** [comment]
Can you delete ' '. It doesn't need now.
![image](https://user-images.githubusercontent.com/45708377/82864762-f9b5b000-9f2d-11ea-820e-effffb39e4ad.png)
![image](https://user-images.githubusercontent.com/45708377/82864897-3ed9e200-9f2e-11ea-9dab-4b42f1c3dcf1.png)
