### ISSUE TITLE
Blast furnace smoke effects are funny

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16359]
![animx22](https://user-images.githubusercontent.com/3536496/82132658-e587eb00-9796-11ea-9034-fca01b88b856.gif)
They come out in sputters and spurts.

**Comment by johnkslg** [comment]
Tip: use the new '/spawn blastfurnace' command to get a fully setup, crafting blast furnace.  
(just added)

**Comment by Sekor2600** [comment]
CastIronStove has the same

**Comment by keegan-o** [comment]
The smog effect is continuous, but code deactivates and reactivates it every time a crafting project changes-- this will be particularly apparent on extreme difficulty settings that reduce craft time.
![Smog](https://user-images.githubusercontent.com/14983165/83312262-84b0d780-a1c6-11ea-9b89-70672c0076a1.gif)

**Comment by keegan-o** [comment]
Actually, it appears that code is also overriding and choosing the particle emission rate, putting it at a truly absurd 25000, which would quickly overwhelm any possible cap on total particles. So that may play a role in certain situations as well-- if the set rate thing could be a percentage of a prefab which I could edit (and it could be made to look better by lerping down and up the percent of total emit rate), I could help to make sure that prefab had good settings.

**Comment by keegan-o** [comment]
here's the prefab emiting at 25, the default for the system, then what happens when that is over-ridden to be 25000 instead:
![Smog2](https://user-images.githubusercontent.com/14983165/83312736-487e7680-a1c8-11ea-8d3e-84a7bf7f1fda.gif)
I think that the emit rate could be affected by code and it'd be fine, but the controls right now are just way off I think.
