### ISSUE TITLE
[0.9.0 staging-1542] Trigger PickUp not working

### ISSUE THREAD

**Issue by Alteraner** [StrangeLoopGames/EcoIssues#16364]
![image](https://user-images.githubusercontent.com/47274045/82159629-d6389880-988f-11ea-84c5-d84ec94d7c37.png)

Hello,
 using attached law is working with the trigger to drop, but pickup trigger is not working. 
Greetings

**Comment by trickenso** [comment]
This is related to #16254 and #16252 - picking up a Stone Road block counts as a 'Deconstruct' action, whereas placement counts as a 'Drop' action.

You could construct a law to work around this, but the fix for construct/deconstruct filters hasn't been released so laws like this aren't currently functional.

**Comment by SlayksWood** [comment]
merged to #16254
