### ISSUE TITLE
[0.9.0 staging-1542] - Corrupted crafting project - NaN resources - cannot delete project or table

### ISSUE THREAD

**Issue by trickenso** [StrangeLoopGames/EcoIssues#16380]
Playtest server - corrupted resource amount showing NaN resources - cannot delete crafting project or table. Perhaps caused by law transferring land claim?
Table location: 1368, 246.

![image](https://user-images.githubusercontent.com/48172405/82240126-cd989e80-9931-11ea-908d-604305d38977.png)

**Comment by SlayksWood** [comment]
You should not delete anothers orders for now (we have issue for that #2638), but I can't finish this order, they will broken if I add some resources. Law example can be found here #16379
> https://user-images.githubusercontent.com/48172405/82237865-3bdb6200-992e-11ea-850a-5fff8b334d0f.png

**Comment by D3nnis3n** [comment]
https://download.godsofwar.de/eco/playtestbug.zip

**Comment by johnkslg** [comment]
Not sure why property redistribution would affect this.
@SlayksWood can you make repro steps to trigger this?

**Comment by SlayksWood** [comment]
Step to reproduce:
1.
- first player claim some property and place some crafted tables (Campfire and Workbench) and stockpile on it:
![image](https://user-images.githubusercontent.com/45708377/83725353-78a39a80-a64a-11ea-80e0-3d497b158361.png)

- first player add 2 orders (2+ items) in campfire, add full labor to first order without any resources, add some resources to second project without any labor, and link campfire with stockpile. 
![image](https://user-images.githubusercontent.com/45708377/83725786-329b0680-a64b-11ea-8a12-af8517fec51f.png)
![image](https://user-images.githubusercontent.com/45708377/83725948-755cde80-a64b-11ea-9ee4-d984f01f2162.png)
![image](https://user-images.githubusercontent.com/45708377/83726017-99202480-a64b-11ea-82f2-17b65abf3757.png)

- first player add order in Workbench, add some labor to this project, don't add any resources and don't link workbench with stockpile
![image](https://user-images.githubusercontent.com/45708377/83725652-ef409800-a64a-11ea-86ec-9858106cd21f.png)
![image](https://user-images.githubusercontent.com/45708377/83725737-19925580-a64b-11ea-8dee-45eba3ddbb55.png)

2. 
- create 2 title in Registrar: Receiver and Giver. Add to Giver first player, add to Receiver second player:
![image](https://user-images.githubusercontent.com/45708377/83726508-4a26bf00-a64c-11ea-86f4-1b2a1bd6953e.png)
![image](https://user-images.githubusercontent.com/45708377/83726541-5448bd80-a64c-11ea-886c-b72c4c796090.png)
- Create law like:
![image](https://user-images.githubusercontent.com/45708377/83726697-9671ff00-a64c-11ea-8668-89a45a4ec0b6.png)
- win election and wait when second player get access to this property

3.
- So second player has access to this property and want to clear it: pick up crafted tables, for exampe. But he can't because this tables has active projects:
![image](https://user-images.githubusercontent.com/45708377/83727430-b8b84c80-a64d-11ea-9ae8-ee27cd5d826b.png)
- second player try to cancel project (it's another issue #2638). He can't because it's not his projects and he can't cancell them. (I also haven't any notification about it)
- So one way to pick up tables is complete all orders ( this way was in 0.8.3)
- So I tried to add all resources and labor to this project.
- add labor and 2 needed birch log to Hewn log project:
![image](https://user-images.githubusercontent.com/45708377/83728169-d508b900-a64e-11ea-81ab-6c495e9a16af.png)
- it don't have any linked inventories, so it finished craft of first hewn log and I should to collect this item, because I have full access to property, but I can't, and I can't add another 2 birch log to project, because project owner should collect this item from here.
- same will be with Campfire's projects. Add 1 Bass to first project. It will finish first craft and it's all. I can't do anything:
![image](https://user-images.githubusercontent.com/45708377/83728933-9de6d780-a64f-11ea-898d-540b1f885858.png)
- Same with second craft. So I can't pick up this table with any legal way.

**Comment by SlayksWood** [comment]
So this projects still corrupted, but now I can delete this projects. But in any case we need to fix this bug. Deleting projects is not fixing coruppted project. But it fixed a big problem with deleting craft stations.

> * add labor and 2 needed birch log to Hewn log project:
>   ![image](https://user-images.githubusercontent.com/45708377/83728169-d508b900-a64e-11ea-81ab-6c495e9a16af.png)
> * it don't have any linked inventories, so it finished craft of first hewn log and I should to collect this item, because I have full access to property, but I can't, and I can't add another 2 birch log to project, because project owner should collect this item from here.
> * same will be with Campfire's projects. Add 1 Bass to first project. It will finish first craft and it's all. I can't do anything:
>   ![image](https://user-images.githubusercontent.com/45708377/83728933-9de6d780-a64f-11ea-898d-540b1f885858.png)
> * Same with second craft. So I can't pick up this table with any legal way.
This still happens

**Comment by SlayksWood** [comment]
Hm but if I'll become owner of this projects I can use this projects. So it fixed, but we need to make it easier for users to understand this process. But it's a another issue. So closed.
