### ISSUE TITLE
Check asphalt mesh for face culling

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#16405]
![image](https://user-images.githubusercontent.com/431728/82415386-c8675b00-9abb-11ea-8f64-5fca38c7b2c9.png)

Full squares should be getting removed, can you check the verts are right in the corners?

**Comment by keegan-o** [comment]
Ah, alas this is the strictness of the face remover I think, because the triangles are flipped so it doesn't count them as matched. Usually of course I want it to be more strict than it is, but in this case the flipped edge means it can't detect the matching face I think.

Verts are all in the right positon, here's the cube overlaid with a perfect meter cube, it is exactly the same:
![image](https://user-images.githubusercontent.com/14983165/83315479-1293bf00-a1d5-11ea-8a97-c372d3af92e3.png)

**Comment by keegan-o** [comment]
updated the mesh to match the triangulation of the most common fallback cube in eco, that hopefully resolve the problem. But this shows another shortcoming of the face remover knowing only triangles and not faces.

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/83315641-44595580-a1d6-11ea-8680-b8b7fcea7d3e.png)
Fixed in staging, but many many blocks still have problems like this, where they match faces exactly but don't or even can't match tris, and thus cannot be removed.
Problem with some of this is that everyone wants more blocks to merge with terrain but having any that are not total cubes or the same means the extra faces will sometimes be shown and thus shouldn't be totally removed from the meshes.

**Comment by redwyre** [comment]
Currently the face remover only works if the face is completely covered with a quad, tris shouldn't matter, just that each vert is right in the corner
