### ISSUE TITLE
9.0 Daily Abandonment Check law is broken and exploiting land claims

### ISSUE THREAD

**Issue by LightOracle** [StrangeLoopGames/EcoIssues#16490]
So I'm not sure what is happening but no matter if you pick the claims up and place them back down once you claim ownership of the property it still comes back to the owner once the law script runs even if you keep the claims in your inventory. Thus letting you get infinite claims.

**Comment by trickenso** [comment]
I just checked, and this is happening on Royal Otter, too.

Here is the law:
![image](https://user-images.githubusercontent.com/48172405/82939007-9148ec00-9f8a-11ea-91b5-2bb31616b330.png)

These land claims were removed yesterday, and have returned - presumably this is happening with all similarly-claimed plots:
![image](https://user-images.githubusercontent.com/48172405/82938967-7fffdf80-9f8a-11ea-8d9d-dff5ffc54e1b.png)

**Comment by SlayksWood** [comment]
Save files:
https://drive.google.com/open?id=1zxf8ukbb8Wg9ucC7lv3qQHiHQBXlkVnL

SO you should be Active at first, then you will be added to title " Deed receiver"
Outside the house 5 different properties
![unknown](https://user-images.githubusercontent.com/45708377/83166124-1bbe5680-a117-11ea-999a-c323e577007e.png)
You should change owner to you and then unclaim it
![unknown (1)](https://user-images.githubusercontent.com/45708377/83166144-27118200-a117-11ea-884d-24e68ac74756.png)
I unclaim 3 properties
![unknown (2)](https://user-images.githubusercontent.com/45708377/83166185-35f83480-a117-11ea-8763-637b80f82f27.png)
and then just wait next civics tick
![unknown (3)](https://user-images.githubusercontent.com/45708377/83166219-40b2c980-a117-11ea-8785-9b9a61ed4fd3.png)
When the tick passes, it'll again claim this area
![unknown (4)](https://user-images.githubusercontent.com/45708377/83166251-4d372200-a117-11ea-9f94-acdbc35997e0.png)
coord: 400,61,500

**Comment by johnkslg** [comment]
It appears plots somehow got stuck on multiple deeds. 
- Added code to detect and fix this, implemented at startup time. Here's what it detects on the save that was posted:
![image](https://user-images.githubusercontent.com/3536496/83811006-df867b00-a66d-11ea-8bde-d136a88081d9.png)
- Changed how deeds and plots are linked so its impossible for duplicates to happen anymore (its only saved in one place instead of two). 

After doing this, the bug above stopped happening.  Good find.

**Comment by MishkaFur** [comment]
Appears to still be happening in 1611, might be related to "multiple owners" which RedWyre mentioned when briefly speaking about it.

Valoron's land was claimed by a dead to us law, transferred ownership to Sunlight, Law ran the following day and it claimed it all and gave it back to WL.

**Comment by beastyn** [comment]
@MishkaFur will check it, thanks

**Comment by beastyn** [comment]
Its just came back.
1) Player one claim property
2) Player 2 receive this property due to law, like this
![bandicam 2020-06-26 16-53-34-361](https://user-images.githubusercontent.com/27898520/85854368-af924980-b7cd-11ea-9ac3-3cc90812fbdc.jpg)
3) When this law is triggered for the first time claims are back.
![bandicam 2020-06-26 16-59-09-028](https://user-images.githubusercontent.com/27898520/85854741-68f11f00-b7ce-11ea-9826-f590759d38e1.jpg)

**Comment by johnkslg** [comment]
@olegshegai can you give this a look?

**Comment by SlayksWood** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/45708377/87305733-a4eee880-c51f-11ea-8a50-f0316c430648.png)
