### ISSUE TITLE
shorten crafting tables tooltip

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#1653]
![image](https://user-images.githubusercontent.com/3150561/27095585-1612130e-5023-11e7-8580-20bacb38ae86.png)

This reeks of TMI, tooltip is way too long.

some thoughts
- organize recipes in a 2 column grid layout, drop 'Recipe' from the recipe texts, color the text differently
- Combine "Crafted at" and "Craft it at", maybe something like
  Crafted at Workbench
    - John's Workbench [5.5 m SW]
    - Sean's Workbench [10 m NE]
    - ...or 5 other locations     <- this line should be clickable and open the minimap with the correct filters
- "Ask an expert to craft"
    - shorten list to 2-3 users max.

**Comment by MarjieAVolk** [comment]
Hm, so how about moving the whole "craft it at" section into the Workbench tooltip?  I've been wanting to put something like that in there, so that when you type "workbench" in chat, you can see if someone has built one already.

Also, I have wanted to have the lists be expandable or whatever, like a sub tooltip, but couldn't really think of a way to do it, since each link needs like a unique id and I don't want to be like caching all this weird stuff.... buuuut actually maybe I could create like a tooltip tag with hard coded content....

**Comment by metachronism** [comment]
we could have a <foldout> </foldout> tag that gets parsed client side and processed as child tooltips maybe

**Comment by MarjieAVolk** [comment]
Yeah that's basically what I was just thinking about... might work, but it would take some refactoring client side still, since the LinkText component assumes a lot about all the links in the text, and it would have to handle both.  But yeah that seems like the best approach so far
