### ISSUE TITLE
[0.9.0 staging-1577] Сurrency icons can be disappeared in Treasury

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#16557]
Step to reproduce:
- have some different currencies in treasury
- start to change default currency:
![image](https://user-images.githubusercontent.com/45708377/83607562-1d0ed980-a584-11ea-92d3-4d413d632315.png)
![2020 06 03 Сurrency icons can be disappeared in Treasury](https://user-images.githubusercontent.com/45708377/83607575-2304ba80-a584-11ea-85aa-4c0b2679a388.gif)

**Comment by Dmittry62** [comment]
I reproduced it not exactly as shown here but the issue is the same. Looks like the problem is somewhere in text mesh pro. Embedded icons disappear for no good reason. I suggest to put it off and recheck after next text mesh pro update.

![cBfS27FhVF](https://user-images.githubusercontent.com/8580108/87293978-c1812580-c50b-11ea-8c69-b2a79bcb4db8.gif)

**Comment by ptitducanh** [comment]
Can't reprocedure this issue. Perhaps updating Text Mesh Pro fixed it.
