### ISSUE TITLE
Hosted Worlds: UI - subscription renew UI

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16553]
1) I have, say, 2 worlds and 10 citizens
2) I want to remove 1 world and 7 citizens.
3) After changing the numbers I need to press a confirmation button.

- Why we call it "Start My World"?
I don't want to start anything, i want to renew my subscription

- What is "Total amount"? I am DELETING things, will I pay for it?

Its really hard to distinguish here: how much I will pay right now and how much will cost my monthly subscription
(And why I need make paypal step when deleting something?)

![bandicam 2020-06-02 16-51-56-252](https://user-images.githubusercontent.com/27898520/83517600-92ca6500-a4f2-11ea-9ecd-e7c3a765cc99.jpg)

4) After deleting things an order is looking like this
![bandicam 2020-06-02 17-01-05-826](https://user-images.githubusercontent.com/27898520/83517689-b9889b80-a4f2-11ea-82db-03d344c5bffd.jpg)
Will I get my money back? 
As it says:
Total Amount: $-76.07 /month*

5) After cpmleting an order I see this
![bandicam 2020-06-02 17-08-04-700](https://user-images.githubusercontent.com/27898520/83518251-a5916980-a4f3-11ea-9794-b46d63ab488b.jpg)

Subscription is cancelled? Why? I've just deleted one world! I have another one!

**Comment by rainfarmer** [comment]
@denysaw 
- [ ] If user owns world or citizen, change checkout button text from "Start My World" to "Update Subscription"

- [ ] When user is being sent to paypal screen, display notification in center of screen "You are now being transferred to PayPal to manage your subscription."

@beastyn 
- New Subscription's Total amount is just that. the total for your new subscription. Should be noticeable that when you lower the worlds and citizens, your new total goes down to match.

- ![image](https://user-images.githubusercontent.com/7343272/84196491-25b85180-aa55-11ea-93ca-2efdf97e1bd4.png)
It says when the payment will happen. If there is an immediate payment, it will display that.

- math issues I think are from using account with worlds that were never subscribed via paypal. so try testing with fresh account. Same for weird cancelling issue. (Basically you canceled more worlds then paypal knew you had. because the dev account we directly add worlds for testing, without paypal knowing.)

**Comment by denysaw** [comment]
Okay 👍

**Comment by denysaw** [comment]
@beastyn WARNING: It's fixed in Git Repo, but as I see it's not deployed on developland (as for this comment time) cuzz of broken Ci/Cd (Jenkins).

**Comment by beastyn** [comment]
Tell me when its on devland please
