### ISSUE TITLE
[9.0-staging] Right Panel Notifications super slow

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#16562]
I have drop in ~50 FPS (from 55 FPS to 4-5 FPS) when have Right Panel notifications open.
![image](https://user-images.githubusercontent.com/475445/83630616-c9f94e80-a5a4-11ea-8cc4-c6619764e287.png)
![image](https://user-images.githubusercontent.com/475445/83630657-de3d4b80-a5a4-11ea-9e0f-4180a3d1412f.png)

Also when you have unread notifications (or just after entering the world) it seems like Notifications is enabled and it causes FPS drop even when not opened.

In profiler it shows very expensive call for Layout:
![image](https://user-images.githubusercontent.com/475445/83630787-13499e00-a5a5-11ea-8f4d-fce9fa054d12.png)

I used this save (you can login as my user mirasrael for test if you won't have enough notifications):
https://drive.google.com/file/d/1J2Du1QajwGxUdiitHQit00OCDjyFQ3db/view?usp=sharing

**Comment by gzatravkin** [comment]
I belive that this issue was already solved here 
https://github.com/StrangeLoopGames/Eco/pull/6158 (merged 2 days ago). Did you test it at last staging? 

Lists are disabled when minimizated.
No significant fps changes with disabled/enabled list
![image](https://user-images.githubusercontent.com/53317567/83698725-8ddfe100-a5d8-11ea-84fb-088f80b9f59b.png)

![image](https://user-images.githubusercontent.com/53317567/83698747-9b956680-a5d8-11ea-9119-dd700bdf95ee.png)

**Comment by mirasrael** [comment]
I used most recent version.

**Comment by mirasrael** [comment]
And list disabled when minimized, but only after you opened it at least once. **Just after login** it isn't disabled.
