### ISSUE TITLE
[0.9.0 staging-1607] Reset graphics kills graphics

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16685]
Press Reset Defaults in the main menu Graphics and get some weird rendering. You can't bring quality back through settings.
https://drive.google.com/file/d/11gR27ZXSCJ4NE6A3Rt2-xOdWEr26Xzn8/view?usp=sharing

We are not sure if this due the last fixes 
https://github.com/StrangeLoopGames/EcoIssues/issues/16428

or it was the problem before.

**Comment by gzatravkin** [comment]
@keegan-o The problem is that GI on low looks really bad (worse than without GI). 
I added change to reset so it will set no GI by default, but do we need low quality for GI if it looks worse than no GI at all? 
Attaching screenshots
No GI:
![no GI](https://user-images.githubusercontent.com/53317567/84774175-d4a7e080-afb3-11ea-8117-992658fa89d3.JPG)

Low GI:
![GI1](https://user-images.githubusercontent.com/53317567/84774186-d70a3a80-afb3-11ea-8b67-f7b3a56eac8d.JPG)

Medium GI:
![Gi2](https://user-images.githubusercontent.com/53317567/84774211-e093a280-afb3-11ea-99f3-21585c5bac4a.JPG)

High GI
![Gi3](https://user-images.githubusercontent.com/53317567/84774330-09b43300-afb4-11ea-9578-d132f3dfd0da.JPG)

Screenshot of settings (changes only in GI)
![image](https://user-images.githubusercontent.com/53317567/84774362-16d12200-afb4-11ea-9112-ea09bb248df5.png)
