### ISSUE TITLE
Increase speed of sending chunks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16757]
Connecting to your local server is a signifigant amount of server startup time, and it appears that a lot of that is simply sending chunks:
![image](https://user-images.githubusercontent.com/3536496/85070843-5ee67500-b16b-11ea-8981-30cec3f75ffa.png)

When this happens locally, the transfer speed should be 100mb/s+, meaning its about 100x slower than it needs to be.   See why this is slow, and speed it up for sending, especially to local clients but also to any client, so long as it doesnt impact performance.

(It is possible that the limiting factor is the amount of time to build the chunks, see if this is the case).

**Comment by mirasrael** [comment]
Should be fixed with parallel queues.

**Comment by mirasrael** [comment]
It won't (and shouldn't) be 100 Mb though, because we don't need to send all server chunks to the client. It only loads chunks on demand (it has buffer for non processed chunks and only request new chunks when buffer isn't full). 
So limiting factors are:
1) How much chunks client really need (with current view distance settings);
2) How much chunks client can process per second.
With parallel queues we fixed issue when buffer is empty, but new chunks not yet received from server.
I don't think we need to send more chunks than necessary, because:
1. It will require more memory on the client for storing them;
2. It will require more processing time for handling them, because for every chunk it makes sorting to determine which next chunk best to build based on player position (closest front chunks should be prioritized).
3. It will fill building queue with low priority chunks which was send for previous player position (if player actively moving).
I think this issue may be closed, because it isn't what we really need from chunk loading.

**Comment by midn8t** [comment]
this was fixed ??? we have a local Machine dedicated server with 1 gig connection locally and the connection speed to it is transferring at about 72 bits second, when comparing that to transfer speed of other games like Conan exiles which transfers at speed locally of 70mbp when first connecting to it for loading chunks of data needed...  it still does not seem to be fixed.  - I remember this being issue even in 2017 the initial load in transfer speeds being slower then speeds you get after load in. ?
