### ISSUE TITLE
Hosted Worlds: can't update world to the 9.0 version

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16779]
Account: testtestqa32
World: world3 

After choosing version v0.9.0.0-beta-staging-1611 world is in the infinite pending state.

![bandicam 2020-06-19 14-35-43-608](https://user-images.githubusercontent.com/27898520/85119193-d20aec80-b23a-11ea-9c8d-e8c45f5b71a7.jpg)

**Comment by denysaw** [comment]
@redwyre Can you please check what's going on with that world? :/
P.S. Anna's idea about broadcasting world start logs would be very helpful here ;)

**Comment by rainfarmer** [comment]
The world did eventually load v0.9.0.0-beta-staging-1611
You can see in bottom left of world page: http://world3.eco.hw.sfo2.do-slg.com/?

Although the account website, still displays the world is on 8.3.3
But that should be fixed by solution below.

The logs say the world only took a minute to boot up.
I believe website waits for confirmation from HW api.
Need to make sure HW API is sending confirmation at correct time.
@mirasrael could you advice on that? Tell me how to do it or run a test yourself.

**Comment by mirasrael** [comment]
HW API doesn't wait until server fully startup. It just restarts container with another image (version). So web site should check (with cron or something like this) if server startup. Until that you may remember last version you started (or request image name from HW API and parse version from it).

**Comment by rainfarmer** [comment]
@denysaw i think we should just update server version based on game server /info
Right now its based on our db, but that falls out of sync too easily with any world hiccups or bugs.
Can you identify a time we are already calling /info and add an update function to that, that keeps our db in sync with gs version.
or open to other idea
