### ISSUE TITLE
Hosted Worlds: need to update subscribtion information properly

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#16781]
1) I've bought 1 world and 3 citizens
2) I've updated subscription to 2 worlds and 5 citizens.

Subscription page still shows me 1 world and 3 citizens.

It should be properly updated after order confirmation

The same goes for the deleting worlds and citizens.

**Comment by denysaw** [comment]
@beastyn I remember we talked about it, but can't recall what we've decided to do 😃 
The problem is we can't show new count of worlds/citizens after order confirmation (Click Confirm), but only after IPN will catch PayPal's success (in few minutes). It would be stupid if we'll show new counts before that, then PayPal got rejected and we've decrease numbers back again :) Or if user will go right away to worlds and see same count of worlds and `processing` in the bottom. So what we could do is to refresh page when IPN PayPal processing is finished. Will this solution suit you? Or what is your proposal? :)

**Comment by beastyn** [comment]
Just show pending with information about paypal proceeding.

But it should be useful and visible information. No our right-bottom little text. )

**Comment by denysaw** [comment]
@beastyn. Done, but wanna told you that right now on payment success user is forwarded to `/worlds`, not `/subscription` (if you wanna change it back, maybe ask John), so to test this issue you should click `Subscription` and now there also will be pre-loader popup, big as you asked ;) With a chance of minimizing it to a small one (by click outside) and restore to a big one (by click on a small one) :)
