### ISSUE TITLE
Pooling feedback

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#16974]
Boilerplate is getting heavy in some cases, for example:

### Renting / Returning
![image](https://user-images.githubusercontent.com/3536496/86498550-1ae29b00-bd3b-11ea-9763-283d2a663110.png)

Could be reduced to:
![image](https://user-images.githubusercontent.com/3536496/86498682-c7248180-bd3b-11ea-9987-95fcee114e65.png)

This could be accomplished by:
- Moving logic to ensure setup not called twice to the pooling system, thus initialSetupFinished not needed.
- Adding a tag that [CallOnRent] to Start, that the pooling system can detect and ensure is called when rent happens, thus removing the need for multiple functions.

Similarly for returning. This:
![image](https://user-images.githubusercontent.com/3536496/86498716-094dc300-bd3c-11ea-8792-161fb322e292.png)
Can become:
![image](https://user-images.githubusercontent.com/3536496/86498739-25e9fb00-bd3c-11ea-95bd-f63e389169db.png)

Better yet, ReturnPooledObjects should be called automatically by the system when its destroyed, so then this function wouldnt be needed at all.  This would require not destroying objects with the GameObject.Destroy function, though, but by a wrapper that will handle pooling cleanup. "PoolOrDestroy" could be this, and make it handle these children cases properly. And then assert that nothing is called with regular Destroy.

These changes would reduce the boilerplate needed in code like the examples above, meaning more focused code, more fluid and automatic use of pooling system, less errors in implementation.

**Comment by mirasrael** [comment]
@johnkslg
Unfortunately there is no way to force or even check if Start or OnDestroy methods was called. So if you will use `Start` method for rent then you may call it twice (first time when renting and another time when Unity call it). So you may have some strange effects or double cost of object startup.

For OnDestroy there is majority of cases where it differs from OnReturn logic. In example you shouldn't cleanup and release all references, because it will happen automatically when object destroyed. Or you may want to keep some cached objects in OnReturn instead of destroying them (and in some cases you may wanna to keep pooled objects so you may not automatically call ReturnPooledObjects from ObjectPool).

**Comment by mirasrael** [comment]
Also we're expecting these components should be functional out of pooling. So it shouldn't be required for all objects to be created with pooling system. Of course if we update all our code to not use `Instantiate` and always use `PoolInstantiate` instead then we can just replace all `Awake` and `Start` methods and use own life-time management events instead, but do we really wanna this and it will be really big work to rewrite everything on this system and probably will result in significant performance degradation, because of custom life-cycle management system.

**Comment by mirasrael** [comment]
What we really can do is to make base class which implements base logic, seals default Unity callbacks (to avoid accidental override) and manage life-cycle with this class.
