### ISSUE TITLE
Displayed text error in soil sampler for dead plant.

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17011]
![image](https://user-images.githubusercontent.com/14983165/86659990-2b934b00-bf9f-11ea-85ec-3b5e3cd5f326.png)

"This plant is dead. None" (not sure what the 'none' is supposed to be, probably the cause.)

**Comment by SlayksWood** [comment]
0.8.3.3:
![image](https://user-images.githubusercontent.com/45708377/86718477-cb96b600-c02b-11ea-8cb0-0a8bb42253e0.png)

**Comment by SlayksWood** [comment]
Can you specify exactly whose Logging? there may be double reading, because we have Logging specialty in game, and some people can understand that chopping tree can kill this plants.

**Comment by MazonDel** [comment]
@SlayksWood In a previous iteration of the solution we had a datatype that could possibly have held such information, but it was decided the memory overhead for adding this field to every organism in the world would be unnecessarily large.

**Comment by redwyre** [comment]
@MazonDel you should be able to calculate this information on demand

**Comment by MazonDel** [comment]
After speaking with @SlayksWood about the confusion, the issue was that on world-generation some dead plants were being called dead because of the DeathType "Logging" despite players having touched nothing. The fix I posted involved reorganizing which DeathTypes were given to plants based on the code. The source of that particular issue was that some over-crowding code during world-gen would kill things off and erroneously had the source listed as "Logging". This has been fixed. This won't update current worlds as the DeathType is only assigned at the moment of death, but new worlds should be corrected.
