### ISSUE TITLE
Sun doesnt match directional angle anymore

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17154]
![image](https://user-images.githubusercontent.com/3536496/87825827-ae809500-c82c-11ea-8446-0846a701d417.png)
Possibly due to a change I think Keegan made that limits sunset/sunrise time?

**Comment by SlayksWood** [comment]
![image](https://user-images.githubusercontent.com/45708377/87930282-74173200-ca90-11ea-90e4-7d8e9bce32fc.png)
and if you move camera a little in some side:
![image](https://user-images.githubusercontent.com/45708377/87930368-9c069580-ca90-11ea-8d17-e1781fd449e8.png)

**Comment by redwyre** [comment]
Ok, I removed some hacks that appears this needs to work.

The TOD sun obviously expects a flat horizon, but we curve so the horizon is lower.

We can just put the sun back, but I think this means that the lighting is actually assuming the world is flat. If that's the case then we could adjust the lighting to work with the curve which would give us a sunrise that races across the ground instead of all at once. Might also help with some shadow acne as well.

Feel free to ping me to discuss :)

**Comment by gzatravkin** [comment]
The sun vertical position fixed by SVN changes. Now y pos of sun is fixed (i.e. it will not raise with player). The difference (in small world) you can see here. Almost always it will be imposible to see the sun cutting (unleass you are flying or you are at some very high position).

@SlayksWood 

Before changes:
![before](https://user-images.githubusercontent.com/53317567/89110085-762ca980-d41d-11ea-9839-646ef46c9162.JPG)

After changes:
![after](https://user-images.githubusercontent.com/53317567/89110083-7167f580-d41d-11ea-8d39-300772ddf82c.JPG)
From water level 
![image](https://user-images.githubusercontent.com/53317567/89110168-5cd82d00-d41e-11ea-9d0e-67e87e147538.png)
