### ISSUE TITLE
[0.9.0.0 beta staging-stable-8] Law : Unable to input numbers

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17270]
Created a new world, created goverment and added all structures for it; when trying to create law and add pay or tax etc in the numbers fields it is unable to add anything in it at all.

Tested a few times and adding a 2nd currency type solved it. Once i built and produced a secondary currency it would allow me to set input in the numbers field.

**Comment by SlayksWood** [comment]
@IcedForge When you make issues, please make them with the following template:

1. Version
2. Steps to reproduce. (it would be nice to add some screenshots or video/gif)
3. Expected behavior.
4. Actual behavior.
5. Providing Log files. 
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
1. [0.9.0.0 beta staging-stable-8]
2. Create new world, have all required government buildings to create laws
3. Add law regarding PAY / TAX modifiers and input numbers into field and it accepts.
4. Numerical option fields for PAY/TAX etc does not allow any input unless multiple currencies are avaible 
5. Currently not on my normal pc could redo it if you need the logs specifically.

**Comment by beastyn** [comment]
@IcedForge can you check please with new update and tell if you still have it. Thank you.

**Comment by beastyn** [comment]
Seems to be fine then )
