### ISSUE TITLE
[0.9.0] Add a way to track debris (of tree) in law system

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17306]
It's currently difficult to create law to force player to clean debris.

We should be able to know how much debris a fallen tree created.

An other usefull things would be to be able to know how much debris there is in the world.

**Comment by Daniel-Magulado** [comment]
Reopening. As per the user report **We should be able to know how much debris a fallen tree created.**

Tested on 0.9.4 Develop-282.

## Issue
There's still no method to have civics law count the debris created from cutting a tree. Create Tree Debris trigger clause should have more options such as the number of debris created with options **More Than, Less Than, Equal To, and Real-Time**. This won't be a problem with the Cleanup Tree Debris clause since cleanup is literally chopping them one by one.

![image](https://user-images.githubusercontent.com/77248866/117789814-4c8d9200-b27b-11eb-95f8-674271c7cbc0.png)

This will allow players to have more flexible laws in regards to debris created from chopping down a tree. Since with the current, you can only set it as one regardless of the number of debris created.
