### ISSUE TITLE
Stretched huckleberry bushes

### ISSUE THREAD

**Issue by Caldrena** [StrangeLoopGames/EcoIssues#17412]
![image](https://user-images.githubusercontent.com/68741535/88931355-b851c180-d24a-11ea-8432-ce80a7ffc950.png)
Newly planted huckleberry bushes seem to be stretched.

**Comment by beastyn** [comment]
Thanks for the report.
It happenes when you are planting one seed near other.
And it stretches all the plants.
![bandicam 2020-07-31 10-49-28-894](https://user-images.githubusercontent.com/27898520/89004408-91af8b80-d31b-11ea-825f-bffb36122ca8.jpg)

**Comment by keegan-o** [comment]
Fixed the growth/scale curves for huckleberries.

Before:
![huckleberryGrowth1.gif](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/ab4108db-56bf-4ced-b986-45f6fe65a527)

After:
![huckleberryGrowth2.gif](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/5fcfd6d7-9dd7-492c-983f-d4afd3fa8891)

I'm not sure how it got like that, the settings must have just gotten messed up at some point somehow.

**Comment by keegan-o** [comment]
fixed settings:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/c9c7451b-66fb-4d1a-85cd-2a4ddc6d7da3)

Before the growth curve was an S curve shape, min growth was .9 and max was 1.2

**Comment by keegan-o** [comment]
This shows however that the alpha curve also somehow broke.

Not sure how either of these curves got broken, but I had to raid the threshold for the blueberries to appear in the alpha curve to get it to work again.

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/b143347c-e6e6-4bcc-8452-cadbd060648a)

**Comment by keegan-o** [comment]
Alright, what appears to have happened is a code change.

Before, the Scale Min and Max were meant to be a range that specified possible final multipliers on the Y scale of a plant at 100% growth.

Now they have been changed to become essentially hard limits that define the Y scale of the plant from 0 growth (for min scale) to maximum growth (for max scale).

This means many plants are now totally distorted because for many of them, I didn't want there to be any extra Y scaling, so Y min was set to 1. Under the new code, this means that those plants will have a Y scale of 1 at growth zero, but x and z will be a lot smaller. Thus it will be stretched out.

**Comment by keegan-o** [comment]
I will leave this with the programmers to fix back to how it was, won't commit my changes to the huckleberry except the fix for alpha curve.

**Comment by keegan-o** [comment]
Basically the way the min and max scale affects scaling of the plants for growth got changed in code to behave differently, now many of the plants are extremely stretched at young ages
before, the min and max scale settings were a range of possible multipliers (not hard definitions) on plant height (y) scaling to add variation to a field of fully grown plants-- now they act as hard definitions to (y) scaling throughout growth from 0 to 1 growth, which means all full grown plants will be exactly the same height, and all young plants will be incorrectly scaled to be massively stretched in the (y) axis.
