### ISSUE TITLE
Missing "allow" makes stuff complicated

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17441]
In a lot of laws we wished to be able to "allow" an action explicitly if a condition is met instead listing a much longer list of conditions that cannot be met with "prevent".

**Comment by johnkslg** [comment]
You can just use the 'not' clause.  All actions are allow by default. Can you show what you mean with an example?

**Comment by MishkaFur** [comment]
Currently all the laws have to be set as a fail close ie below option, this can lead to issues due to the laws now requiring you to basically auth everyone who CAN do something rather than who cannot

If not admin,president, vice president then prevent

Having a fail open as an option would be useful so ie
If admin, president or vice president then allow

I have other examples where it will be useful but cannot access atm atm, just having that allow or prevent option will be useful so the laws are not forcing you to do things in a fail close methodology and risk preventing actions being done on the server and then have to wait for the laws to time out after picking up the table in question.

**Comment by IcedForge** [comment]
Here is an example of where i want to prevent items being sold, unless specifically in a certain area
yes i can use Else - IF, NOT in district then prevent but coming off the old law system this is very unintuitive because it forces you to really explicitly only allow this exact thing to match, which is great but its also a very problematic thing for anyone that is not directly involved in coding so generic user joe will have a very poor experience dealing with laws in general.
![Screenshot_396](https://user-images.githubusercontent.com/24981362/89708839-e174ff00-d97a-11ea-871b-bb04ed4e7e2f.jpg)

**Comment by beastyn** [comment]
@johnkslg I personally agree with this position, depends on some internal restrictions (I don't know if there are some). The more intuitive - the better )

**Comment by Deantwo** [comment]
But `Allow` never made any sense in the old system. Is it my understanding that `Allow` actually did nothing at all in the old law system.

Just look at all the players that attempted to make a law using `Allow` to *enable* non-existent features.
```
When attempting to Unlearn Speciality
    Allow
```
The `Allow` action caused nothing but confusion in the past. Removing `Allow` has made it simpler and more true to how the system actually works.

As mentioned, if you want everyone except a specific demographic/title to be able to do something, simply disallow everyone that isn't that demographic/title.

**Comment by Deantwo** [comment]
That is worrying.
