### ISSUE TITLE
Custom Stats reading doesnt work

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17444]
You get a short flashing red debug error message and nothing happens when trying to read a custom stat in a law.

**Comment by johnkslg** [comment]
This is happening because the prefab 'string' isnt setup properly with the new textfield and pooling changes:
![image](https://user-images.githubusercontent.com/3536496/89087369-ea494d80-d348-11ea-9692-91cc4e7cc40a.png)

InputFieldControl is expecting a child component TMP_InputField to exist but none does.

**Comment by johnkslg** [comment]
To repro, try to set 'Record Custom Stat' in a law condition: 
![image](https://user-images.githubusercontent.com/3536496/89087435-254b8100-d349-11ea-8689-11c7d7cd7ddf.png)

Do a search for other uses of InputFieldControl that may not have the necessary component with them.
