### ISSUE TITLE
Civics: impossible to restrict the trade of an item to a specific claim or district

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#17442]
We didn't find an option to select "Land Claim Papers" at all, even when checking not-discovered and it additionally seems to be impossible to restrict the trade of an item to a specific claim or district.

On White-Tiger we got a law that restricts the selling and buying of land claim papers to only one shop on the federal bank property.

**Comment by johnkslg** [comment]
The LandClaimPapers object is missing from filters for some reason:
![image](https://user-images.githubusercontent.com/3536496/89082786-e6ff9300-d343-11ea-9cef-7ce9e600c15d.png)

**Comment by beastyn** [comment]
Dup ##17317

**Comment by beastyn** [comment]
Ok, so we have to parts. Land claims are in the #17317 And this one I will leave for the second part.

"and it additionally seems to be impossible to restrict the trade of an item to a specific claim or district."

**Comment by johnkslg** [comment]
You can restrict to a specific district just fine:
![image](https://user-images.githubusercontent.com/3536496/89232228-dea19500-d59b-11ea-9ec5-6e7261e592d2.png)

![image](https://user-images.githubusercontent.com/3536496/89232243-e7926680-d59b-11ea-9ebf-faadc6181c48.png)


Closing as the rest of the bug is covered in the referenced issue.
