### ISSUE TITLE
[0.9.0 develop-19] Make property and District map setting in the map look fancy

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#17489]
We should have property and districts under the one category.
![bandicam 2020-08-03 15-31-37-646](https://user-images.githubusercontent.com/27898520/89174030-9fc10e80-d59e-11ea-84f9-cce5768c12b0.jpg)

Its not looking good.
Like under Land Management or something

And maybe we can make it like different category?

On one level with World Layers.
And make 'Show in the world' for this category too.

**Comment by gzatravkin** [comment]
Disagree on putting it in same level with World layers. They are have same sense (some overlay map), same toggle group (check district should disable check on animal data) and same option (show in the world). I think it would be more messy if it's separate group.

I made some changes so it looks in same way as other subcategories. (screenshot).
![image](https://user-images.githubusercontent.com/53317567/89591004-7a8f0300-d81f-11ea-8958-d2847aa5bd6c.png)

District maps now lost they subgroup with districts, but shouldn't be a problem since it have a tooltip with district names/colores.
![image](https://user-images.githubusercontent.com/53317567/89591024-88448880-d81f-11ea-9444-98d586263b47.png)

**Comment by SlayksWood** [comment]
- [ ] 1. I don't have any districts in my world, and I can't select property, because civics map doesn't appear without any district map.

![image](https://user-images.githubusercontent.com/45708377/89756170-6c283c00-daea-11ea-9476-f125f9347223.png)
Create district map 1:
![image](https://user-images.githubusercontent.com/45708377/89756474-494a5780-daeb-11ea-9c10-bd3182c4909c.png)

- [ ] 2. 'Civics Map' font size:
![image](https://user-images.githubusercontent.com/45708377/89756976-a4c91500-daec-11ea-843c-2b16f390d348.png)

Something wrongs?
You create a problem by tying property to world layers. So, previous I can always see property(If I enable it 1 time) on minimap. I want to find Huckleberries? No problem, I select it, property will disapear, i find huckleberry and unselect huckleberry population and I should see property. Now I need to select property second time. And after all changes I need to make it. So we don't have basic selected point.

**Comment by gzatravkin** [comment]
Imho it hadn't clear behavior. 

What would happen when you have property unselected, you gonna to select Huckleberries, and then, with huckleberries selected, gonna to select properties? 

As I remeber, it will do nothing (huckleberries have bigger priority, so it won't show properties), it will only change state of toggle. Even if it would unselect world layer, don't seems obvius if it have different category. 

The same will happen with district maps. District maps unselected, some data layer selected. What will (should) happen after selecting district map? To change nothing in minimap? Until you desselected data layer. New user wouldn't know about it and it would feels like district map not working. Or maybe desselect data layer? So it's same toggle group and if they are related in that way it should be in same category. 

About "I want to find Huckleberries? No problem, I select it, property will disapear, i find huckleberry and unselect huckleberry population and I should see property". 

You still have 1 click way to back property. Just instead of unselected huckleberry select property. 
If we really need some temp changes of minimap we could add something like "press layer to previsualization" or cntr+z or something. 

So, for me it's: 
1) Separate category:
+ You can desselect world data to get back to property
- duplication of toggles Show in World 
- Unclear behavior 

2) Same category
+ Stronger logic of selection
+ Overlays are easier to find (all possible overlayes are in same place)
- Now you can't desselect data layer to get back to property (but anyway you could select property which is at the top of category)

Also when they are all at same place and same toggle group the system looks be easier to expand. 

@johnkslg you are doing some minimap refactoring, what you think? How it would be better? This change was originnaly done to support Show in world for District maps (and properties), but could be redone to have 2 toggles Show in world (with synced value I suppose) and Civic Maps as a group with same level as Settings/World Layers.

**Comment by johnkslg** [comment]
Im refactoring this for 9.1, so lets just fix the most basic issues and worry about categorization later
IE, you should be able to see property without districts existing yet.

**Comment by gzatravkin** [comment]
Ok, for now I fixed 1,2 from @SlayksWood comment. 
It's simplier to leave it under same category right now (to avoid duplication of toggle Show in world).

We can continue with recategorization later (at 9.1 I guess). Proabably also will be changed with multiselection of world layers.

**Comment by SlayksWood** [comment]
CLosed for now. We will return to this issue after release 9.0, after some user feedback and maybe after our future changes with towns
