### ISSUE TITLE
0.9.0.0 - beta staging -1702 : Palm logs have no soft/hard wood tag

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#17500]
Palm tree logs have no tag for softwood or hardwood, so they can only be made into regular hewn logs not specific type.
![Screenshot_282](https://user-images.githubusercontent.com/24981362/89202867-e3724300-d5b3-11ea-9a6d-8a289db1ecb6.jpg)

**Comment by WeaselDog** [comment]
Thank you reporting this. This is actually intentional as Palm Tree is seperate from Softwood and Hardwood species. Joshua & Saguaro Cactus are not technically trees, and they also do not provide Softwood or Hardwood.

We will update the description so this is clear, and also as an educational moment.

**Comment by IcedForge** [comment]
Would it be possible to add a function to the "craft hewn wood" to specify only craft it using X?
So i could avoid using possible softwood/hardwood capable logs for regular hewn?

**Comment by SlayksWood** [comment]
@IcedForge We know that the crafting UI is not very user-friendly right now, but we want to change it in 9.1. You can post your wishes here #13334
