### ISSUE TITLE
Economy View : Sale/Buy price sorting - Always put not concerned last

### ISSUE THREAD

**Issue by matheod** [StrangeLoopGames/EcoIssues#17585]
Im you want to buy someting at the cheaper price, you might want to sort sale price ASC.

But you will first get line where it isn't sold (line with a -), so you will have to skip all of them before reaching the lower price line.

Not concerned line should be pust last.

**Comment by beastyn** [comment]
@D3nnis3n not 9.0. Push please.

**Comment by IcedForge** [comment]
Back on 0.9.1.0 Staging-1804
Sorting in Ascending order works, but Descending will put blank values above.

**Comment by IcedForge** [comment]
![Screenshot_146](https://user-images.githubusercontent.com/24981362/95984005-d0d18100-0e22-11eb-8404-9da7d88fc2b5.jpg)
Sale / Buy price listing - Sorting works for Asc but NOT Desc (adds null values ontop instead of ignore at bottom)
Number Available/Number Wanted - Sorting works for Desc but NOT Asc (adds null values ontop instead of ignore at bottom)

**Comment by johnkslg** [comment]
We can make the '-' null values sort to the end in one case, and the top in the other case. I dont want to special case it to always be at the bottom, creates more problems then its worth.

**Comment by IcedForge** [comment]
That was the issue, it should always sort - null at the bottom? regardless if i filter for asc or desc i never want to see - null at the top and force to scroll down.

**Comment by D3nnis3n** [comment]
^ Agreed to Ice Forge. Makes no sense.

**Comment by johnkslg** [comment]
It breaks sorting consistency.  If you sort one way, then reverse that sort, it should be the exact reverse list, not some totally different order.  This is how most sorting interfaces I've seen work, its more confusing to have different orders than sorted/reversed. handling properly IMO.

**Comment by johnkslg** [comment]
Can just sort it to 'most expensive' instead of cheapest so when you sort by lowest cost it shows at the bottom.

**Comment by D3nnis3n** [comment]
I disagree with that, consistency != user experience and the better for user experience is definately the correct sorting with stuff that has **no value** not being considered in sorting at all and therefore being at the end. It's never interesting for someone sorting, as it has no value. In case we otherwise close with Won't fix i'd want to keep this as suggestion, as i feel this is a massive QoL issue when you need to scroll over possible hundred items until you find what you want.

**Comment by IcedForge** [comment]
Yes, a 100 times over.
As an example - I want to buy logs, now if there is 100+ stores and they sell ALL log types then thats potentially 800+ items i need to scroll through because i cannot sort by ascending value and see items with actual value at the top.

**Comment by SlayksWood** [comment]
fixed
![image](https://user-images.githubusercontent.com/45708377/98353207-118e7580-2030-11eb-8d7d-24a4ff5c8984.png)
![image](https://user-images.githubusercontent.com/45708377/98353226-16ebc000-2030-11eb-843b-0ec40664676c.png)
