### ISSUE TITLE
Solar Generator Inputs Broken

### ISSUE THREAD

**Issue by keegan-o** [StrangeLoopGames/EcoIssues#17602]
Solar Generator is a water boiling > steam > turbine model, which needs a supply of water.

Currently the water input port does nothing, this needs to be fixed so that the generator requires water via pipe to function.

**If a world object needs ports, to check which ones it should have exactly, check the prefab's Occupancy Objects and their names.**

![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/d91ad12c-1224-4db8-a5ee-fd30776c85f8)

Figuring out that objects can have water inputs without outputs is relatively new, so if issues arise with this part of the issue (adding only a water input), let the art team know and they can add a sewage output to the objects so that it can be set up with full water input/output. Like the steam engine, hopefully we can avoid this since the water is not getting tainted, it is literally turning into steam. 

Added high priority because it needs to get done in 9.1, not pushed.

**Comment by Quadbro** [comment]
@Sekor2600 @WeaselDog 
Solar generator should work if it will require this component in ecotechtree
It has same behaivor as LiquidConventer component
![image](https://user-images.githubusercontent.com/6802030/93051701-1a497780-f68f-11ea-9784-21c24a7c8be1.png)

Also we need to ensure that occupancy is updated (replace jeneral coord with typed for input one)
![image](https://user-images.githubusercontent.com/6802030/93051814-4238db00-f68f-11ea-9e50-896b5e5bb091.png)


That will lead to such behaviour
![image](https://user-images.githubusercontent.com/6802030/93051842-4cf37000-f68f-11ea-8be8-59994fb84544.png)
![image](https://user-images.githubusercontent.com/6802030/93051848-4fee6080-f68f-11ea-9e61-94af8738569d.png)

to achieve same mechanics in other objects - we need to require the same component, but instead of LiquidConverter
![image](https://user-images.githubusercontent.com/6802030/93052071-afe50700-f68f-11ea-8728-00ca2b8dcd40.png)

Please ask if you need some extra work on my side, cause it should work after tech tree changes (with some adjustments of template, or so)

**Comment by Sekor2600** [comment]
yeah i did fix the Pipes in the Prefabs last week. The only Blocker was the UI that displays Output where nothing is.
