### ISSUE TITLE
[0.8.3] Unable to play single player through Steam

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17628]
We have a new issue that players time out while trying to launch a single player world through the Steam client in 8.3. They can join worlds fine.

A few key details about this:

- It does not affect 9.0
- It does not affect 8.3 dedicated server
- It does not affect 8.3 SLG client
- Only 8.3 Steam client is affected and only when launching singleplayer

**Comment by gzatravkin** [comment]
Server error: 
[17:21:20.711] [1] [ Info] [Eco] Failed to load server, Exception was Exception: JsonSerializationException
Message:Could not load assembly 'System.Private.CoreLib'.

The same as https://github.com/StrangeLoopGames/EcoIssues/issues/17065 .

Repro steps: 
Switch to 9.0 
Host local world
Switch to 8.3.3
Host local world (you can't)

**Temporal solution**: instead of version swap get full reinstall of eco. 
Or replace files from Eco\Eco_Data\Server\Configs
by content of this archive 
[Configs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5048628/Configs.zip)
