### ISSUE TITLE
[0.9.0 staging-1711] Nerf Campfire Cooking nutrients

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#17629]
Campfire Cooking is in a very good place in terms of calories/ingredient to the point Charred Food is not very useful anymore.

Campfire Cooking has a new problem that the skill points are too high, and need to be nerfed to more reasonable levels. In the current state, early game progression is too fast and there is not enough incentive to upgrade to Baking/Cooking

**Comment by IcedForge** [comment]
40 food sp gain from charred papaya+ charred meat could be reduced to maybe 30-32 to give campfire cooking a better fit on 45-60 range ( since baking is around 74 and cooking is 85 ) having adv campfire cooking at 68 for a fraction of the cost reduces the will to bump up your food quality because of Food value per calorie vs food quality is too high of a cost currently.

**Comment by Krizzoula** [comment]
I agree Ice...  45-60 for campfire cooking would be ideal, based on the point gain for the next tier level food.. It would make the steps in progression feel a little more balanced and necessary to make the next push to upgrade.
