### ISSUE TITLE
xp points

### ISSUE THREAD

**Issue by LuZiferdk** [StrangeLoopGames/EcoIssues#17652]
ver. 9,0
Expected behavior i am making morter i expected to get  98 xp points bot only got half

![xp points 1](https://user-images.githubusercontent.com/37664204/89851883-e2ca4580-db8d-11ea-91d2-166b52c0cd6f.jpg)
![xp points 2](https://user-images.githubusercontent.com/37664204/89851894-e8c02680-db8d-11ea-97fc-55ca606d382b.jpg)

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5054498/Player.log)

**Comment by SlayksWood** [comment]
You have half because you made mortar which have exp coefficient 0.5:
![image](https://user-images.githubusercontent.com/45708377/89862468-b5db5a00-dbb0-11ea-8592-c9ad054458ed.png)

You can check it in recipe tooltip, So my XP multiplier = 20:
![image](https://user-images.githubusercontent.com/45708377/89862587-f8049b80-dbb0-11ea-9305-51b6536bc7e8.png)
Open Masonry mortar recipe:
![image](https://user-images.githubusercontent.com/45708377/89862641-14083d00-dbb1-11ea-9827-028f1d0ec951.png)
So it's intented behavior.
