### ISSUE TITLE
USER ISSUE: Plant Fiber not in store options

### ISSUE THREAD

**Issue by Aperson93** [StrangeLoopGames/EcoIssues#17662]
**Version:** 0.8.3.3 beta

**Steps to Reproduce:**
look in store

**Expected behavior:**
It should be there

**Actual behavior:**
Not there

**Do you have mods installed? Does issue happen when no mods are installed?:**
Not there

**Comment by SlayksWood** [comment]
@Aperson93 Thank you for the report. I have plant fiber in store in 0.8.3.3:
![image](https://user-images.githubusercontent.com/45708377/89978456-3d3ed100-dc76-11ea-9b36-b4031850c3c4.png)
and this is exactly fixed in 0.9.0:
![image](https://user-images.githubusercontent.com/45708377/89984658-70875d00-dc82-11ea-8cb4-b7b6da9f6f15.png)

**Comment by Aperson93** [comment]
@SlayksWood Sorry, I don't see plant fiber under any category filters only when no filters are selected. Hopefully this is fixed in 0.9.0 as well.
