### ISSUE TITLE
Stone Road Extending Beyond Meter Space Creates Problems

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#1766]
When Placing a Stockpile on Ground that has Ore or Stone hit with a Pickaxe it shows through the Stockpile base, and if i make a floor of Stone road and then place the Stockpile on it the base disappears completely, this was in 5.6 and also now in 5.6.1. Enclosed Snap shots of examples.
![snap075](https://user-images.githubusercontent.com/29383891/27809304-4fd94c64-6046-11e7-9387-4a1472b9f951.png)
![snap076](https://user-images.githubusercontent.com/29383891/27809305-4fdd6b96-6046-11e7-9802-580b49a32a91.png)

**Comment by Conchipedia** [comment]
also when using a Stone floor in a doorway i get a dip down and up effect, this can make a cart stop moving.

**Comment by keegan-o** [comment]
Stockpiles still need art, and rubble will be totally re-done for beta-- so this bug is just about making sure the road blocks don't extend above the meter space if we can avoid that, I guess (it will make road blocks look worse as roads and better as doorway floors, which is a weird compromise, but we will see what can be done!).

**Comment by metachronism** [comment]
@keegan-o all you buddy
