### ISSUE TITLE
Infinite Carts

### ISSUE THREAD

**Issue by jellyfluff** [StrangeLoopGames/EcoIssues#17727]
With one cart on the ground, as soon as you see the disconnect symbol in the bottom corner, if you hammer the cart into inventory and disconnect while it is still on the ground, when you relog you have a cart both on the ground and one in your inventory.

**Comment by SlayksWood** [comment]
@jellyfluff Thank you for the report. When you make issues, please make them with the following template:
1. Version
2. Steps to reproduce.
3. Expected behavior.
4. Actual behavior.
5. Providing Log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

As for your problem We also need some addition information:
What server do you play? Can you provide save files?
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save
Which kind of internet connection are you using? Do your have bad connection on every server?

**Comment by beastyn** [comment]
Have a new information. 9.01.

Steps:
1) Have a cart on a ramp
2) Run away (maybe chunk reloading)
3) Get back and see cart is turned upside down.
4) Try to pick it up and have a disconnect label
5) Return to the game.
6) See a cart on the ground and one in your inventory. 
7) Place the one from your inventory on the ground? it's unowned.
8) Try to claim.
All server will have a huge lag, until you disconnect.
[Player (2).log](https://github.com/StrangeLoopGames/EcoIssues/files/5216754/Player.2.log)
[Player-prev (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5216755/Player-prev.1.log)

**Comment by beastyn** [comment]
It's not a border or something around 0 coordinate.

**Comment by Erisea** [comment]
On Planet Hell server, version 9.0.2.  Server was lagging quite badly, with delays of multiple seconds every minute or so.  Placing a wood cart created a cart in the world, but didn't remove it from inventory.  Having done this, I was then unable to do anything else - if the cart was silhouetted, I couldn't place a second, but if switching to a tool, I couldn't use it.  Disconnecting and reconnecting to the server left the cart in the world while still having a copy in inventory.  I could then place this duplicate cart, and had the same issue with it remaining in inventory and being unable to do anything else.  I repeated this another two times with the same effect.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5271687/Player.log)
