### ISSUE TITLE
Minimap Refactor Assistance: Names overlap when new settlements spawn in 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#17819]
/settlement spawn
go to minimap layover section, settlements
Do /settlement spawn a few more times 
it will overlap like this:
![image](https://user-images.githubusercontent.com/3536496/90824858-e3c94880-e2ec-11ea-8e69-ec6ad5257616.png)

Wasnt sure why this was happening, probably need to do proper use of your new layout components, can you help fix this and advise what the issue was? We can make a guide for making setup like this easier.

**Comment by gzatravkin** [comment]
Can be fixed by adding ContentSizeFitter ( vertical fit = Pref. Size) to MinimapKeyView. Added in editor refactoring
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/2cb8ecf7-7236-4f0f-9450-569cb9b397c1)
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/d4ad8ba8-10d6-4faa-9125-3d7702fec7ae)
