### ISSUE TITLE
CW internal name should be unique to kubernetes pods

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#17825]
Currently cw internal name is set by accounts system,
Should be updated to be set by Cloud Worlds API, which confirms its a unique pod name.
External world name can still be set by accounts. doesn't relate to CW API.

This is to stop duplicate world names. which happens if db is out of sync with kubernetes pods. Or if 2 users purchase at exact same time.

**Comment by mirasrael** [comment]
@j3fffff won't it be enough if CW API will just inform caller about duplicate name? I don't think by design it is good to make name assignment on CW API side. It makes name generation less flexible. For uniqueness on the site side you can actually use combination of user name and world number and will significantly reduce chance of name conflict and also will make world checking simpler. Also if you pre-insert record for the world in DB you can use unique index constraints which will prevent same name creation even if you do it for same user in parallel.

**Comment by j3fffff** [comment]
ya that sounds good. usernames are unique and its maybe ideal for user to have their username in world url.
@denysaw can you implement worldnames set as username + number

**Comment by denysaw** [comment]
Done. Tested on stagingland.

**Comment by j3fffff** [comment]
@denysaw how did you handle weird characters. maybe we can strip those from usernames?
could also use user ids instead

**Comment by denysaw** [comment]
@j3fffff Hah... I used userId instead. `slg+number`. :) Really. Even forgot it should be username )) So yeah. slg+id
