### ISSUE TITLE
Invisible map bug

### ISSUE THREAD

**Issue by LightOracle** [StrangeLoopGames/EcoIssues#17895]
![Invisable Map Bug](https://user-images.githubusercontent.com/63035969/91319401-f37bdd80-e781-11ea-8780-78ee354bcb60.png)

One day on White Tiger I just logged in and had this bug with my map now I still have it on Giant Panda too even after the update. So I have no way of knowing what caused this just reporting it. Restarting does not fix it.

**Comment by SlayksWood** [comment]
@LightOracle Thank you for the reprort. We need some additional information.
1. Please provide your PC specification (include Operating System).
2. Did you meet this issue after updating to the latest staging or you had it before?
3. Please provide graphics settings.
4. Provide log files.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by mirasrael** [comment]
@LightOracle I assume you have AMD GPU.
They recently updated their software and start using dirty hack for performance by reducing by default Max Tessellation Level (which actually by standard should be at least 64).
You can fix this by setting it for Eco to 64 (be sure you set if for Eco, because it may have different global settings):
![image](https://user-images.githubusercontent.com/475445/91560580-bd398c00-e942-11ea-9e27-fae5ba0ebbe3.png)

I added info box in the game:
![image](https://user-images.githubusercontent.com/475445/91560660-dc381e00-e942-11ea-89c8-89765b49823f.png)
