### ISSUE TITLE
USER ISSUE: Left half gfx dump

### ISSUE THREAD

**Issue by xasil** [StrangeLoopGames/EcoIssues#17903]
\
**Version:** 0.9.0.0 beta staging-1740

**Steps to Reproduce:**
Graphics glitch on left half on screen, looks like its dumping debug text info.

**Expected behavior:**

**Actual behavior:**
Idling has it happening

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Zaskersky** [comment]
Version: 0.9.0.0 beta staging-1740

Steps to Reproduce:
When im crafting items, and for example eating food. it repeats often.
when standing still and nothing is being crafterd it does not happen.

Expected behavior:
no flashing red text dumps

Actual behavior:
flashes of red text on left side of the screen.

Do you have mods installed? Does the issue happen when no mods are installed?:
no, yes
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5134887/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5134888/Player-prev.log)

**Comment by D3nnis3n** [comment]
This is the debug console, it's intended to be in the testing version.
