### ISSUE TITLE
Tree parts is too complex

### ISSUE THREAD

**Issue by mirasrael** [StrangeLoopGames/EcoIssues#17946]
Many tree parts much more complex than they may be. It causes significant performance impact for rendering and instantiation, as well as memory usage. 

In example for Birches we may have thousands of them in scene and each of them has such Tree Tip:
![image](https://user-images.githubusercontent.com/475445/91554309-8f9b1580-e937-11ea-8552-45172f90052d.png)

Especially some strange looking colliders like this:
![image](https://user-images.githubusercontent.com/475445/91554396-b48f8880-e937-11ea-9bf8-5efd367c9bff.png)

Tree parts should be redesigned to have minimal number of game objects and components.

**Comment by keegan-o** [comment]
This may not be practical to get a ton done on for 9.0 because a lot can go wrong with editing trees and the system is not friendly for changes-- but I will try to investigate once I've made progress on steam page images for 9.0. In short, might have to do this for 9.1, it might also be worth applying some serious programmer attention to trees which are quite difficult for artists to touch or alter.

**Comment by keegan-o** [comment]
I got the birch tree tip and branch down to one collider each, and the behavior seems totally acceptable for cutting down etc. They have to be box colliders so that they don't roll around everywhere, but one box is I'm sure much better than 5 or 11 capsules. Will be going through and doing the same to all the others!

**Comment by keegan-o** [comment]
Fixed the cedar tree and oak tree prefabs as well, and checked all the others. It looks like the others are all using 1 gameobject/collider per part, so calling this fixed for now.

**Comment by keegan-o** [comment]
Moving to review, I assume @mirasrael will want to confirm that these changes are sufficient.
