### ISSUE TITLE
[0.9.0.0 beta stating-1742] Pop-up Notifications are too big for constant actions like tree chopping taxes

### ISSUE THREAD

**Issue by RedBaron88** [StrangeLoopGames/EcoIssues#17978]
The pop-up notifications when being taxed or allocated for constant actions like chopping trees or removing stumps are obnoxiously large and take up the entire screen. There should be an option to turn these pop-up notifications off and remove them from the chat window as well.

**Comment by IcedForge** [comment]
Latest instance of this being changed
i still would like to either move them to the side or alternatively add option to turn them off / change from on screen notifications to side bar or top notices
https://github.com/StrangeLoopGames/EcoIssues/issues/17055

**Comment by SlayksWood** [comment]
@WeaselDog @johnkslg 
Can we make something like option in law to have or not this message? Because I agree I want to see some law notification, for example, if I can't use something in any district. But I would not to see every tax notification for every similar action. We can always show it in chat. 
For example we can add another condition 'show pop-up notification'  like 'prevent if unable to pay' and two answers yes/no or more answers 'always show/ show once at a certain time (and you can change this time)/ never show.

**Comment by beastyn** [comment]
Just move the Law notifications to the top for 9.0. Later we should have more options to customize it, but we can't leave it like this for 9.0.
Only errors and important messages should be on this place.

**Comment by johnkslg** [comment]
Sounds good. 
@gzatravkin can you make an advanced option 'Display success notice as popup', and then make success notifications display in the top chat instead of in the popup window unless that's set (default to off).  Failure notifications can be made to always show as popups with no option to hide.

**Comment by beastyn** [comment]
So now we have option for notification in Then section (in advanced) and its temporary in chat window.

**Comment by RedBaron88** [comment]
Tax notifications were fixed, but other law notifications such as notification of being allowed to do something in a district still pop-up.
![Untitled](https://user-images.githubusercontent.com/69723929/92488288-f5976080-f1b3-11ea-98d5-dfbeb8d7190e.png)

**Comment by beastyn** [comment]
@RedBaron88 is there a way to get a law screenshot?
