### ISSUE TITLE
USER ISSUE: Disappearing deer

### ISSUE THREAD

**Issue by Spaceferret42** [StrangeLoopGames/EcoIssues#18017]
\
**Version:** 0.9.0.0 beta staging-1742

**Steps to Reproduce:**
shoot and kill a deer next to a cliff

**Expected behavior:**
left a carcass by the cliff where it died

**Actual behavior:**
carcass is no where to be found

**Do you have mods installed? Does the issue happen when no mods are installed?:**

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Spaceferret42** [comment]
update same thing just happened with a snapping turtle inside a building

**Comment by kealas** [comment]
This happens frequently with all animals on every game we've run.  Seems to only be getting worse instead of fixed and hunters lose around half their kills to teleporting animals including teleporting on death.  Carcass can usually be found some blocks away.  Often on a different height but sometimes it takes quite a bit of looking.  It goes away on server restart but only for about 2hours and we can't restart every 2 hours.

**Comment by beastyn** [comment]
@Spaceferret42 thank you for the report. Issue wasn't fixed yet, so still waiting here #17718
