### ISSUE TITLE
[0.9.0 staging-1774] Civics: citizen stats is counting from zero

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18077]
1. Create a law like this (fresh world)
![bandicam 2020-09-07 20-14-19-046](https://user-images.githubusercontent.com/27898520/92401344-e8905800-f146-11ea-85d5-3d96302b00b5.jpg)

2. Assuming, that after Citizen is sending a message it should send a message with count 1 (action was recorded before Then section)

3. Message send count 0

![bandicam 2020-09-07 20-15-07-453](https://user-images.githubusercontent.com/27898520/92401424-0d84cb00-f147-11ea-8bcf-f33f7a8db4f4.jpg)

**Comment by olegshegai** [comment]
So in a sense, it works as intended.
The chat sent action will be counted as performed only **after** the pack resolves (which is okay, we do not track unperformed actions).
And in this case we are looking into stats **during** that process. In other words, it displays the current state of the database, where the chat sent action doesn't exist yet (it will, but only after the pack resolves as successful, which cannot be determined from the laws block).
A possible solution is extend `StatSum` with `CountCurrentAction` boolean and check action's type. But that will require additional trickery with law's `If` block and other checks related to "should we count this action too", because it's a very special case where the performed action should be counted too (for many others - it shouldn't).

**Comment by johnkslg** [comment]
We should be able to move the statistics registration to happen before the post effect, that will fix this
