### ISSUE TITLE
[0.9.0.0 staging - 1776] Animals: arrow won't hit a target

### ISSUE THREAD

**Issue by beastyn** [StrangeLoopGames/EcoIssues#18084]
Almost every time arrow will flu through an animal. Just in some position I can hit it.

**Comment by SlayksWood** [comment]
We investigated it more with Stainslav too. So It happens when you have 2 bows in toolbar. Step to reproduce:
- have wooden bow and recurve bow on toolbar.
- select empty slot, select wooden bow. You can hit animals in 75 meters
- select recurve bow, you can 100% hit animals in 5 meters.
Few hunters have 2 bowson tollbar. So it can be pushed to hotfix

**Comment by IcedForge** [comment]
Still an issue but in a mirrored way, it is no longer possible to hit animals when going from Empty slot -> selected bow
But switching between Bow -> Bow works now.

https://i.gyazo.com/d4f6d6baf703898bd8eb492f47a2d23d.mp4
