### ISSUE TITLE
Modifying possibilitites need to be more clear

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18112]
Easier way to modify difficulty settings, either more clear that you need to select 'Custom' or or offer the customization for every of the settings, with those simply displaying the defaults for that setting. And as soon as you change a setting it goes to "Custom" automatically.

**Comment by gzatravkin** [comment]
What exactly this issue is about? 
When you start new world you have option to choose these modifiers:
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/8b4ef035-d83f-4b49-8412-8d189a9da60f)
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/81e532ee-784a-4107-835d-e8f80a076b90)

**Comment by gzatravkin** [comment]
@D3nnis3n

**Comment by D3nnis3n** [comment]
The issue is that a lot of people do not seem to get they need to select "Custom" to change stuff.
We might want to either make that more clear or offer the customization for every of the settings, with those simply displaying the defaults for that setting. And as soon as you change a setting it goes to "Custom" automatically.

**Comment by gzatravkin** [comment]
Ok, now it shows all inputs from the begining, after value change turns to Custom
