### ISSUE TITLE
New Research Paper Icon Variations Per Tier

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#18125]
From Dis#4336 on Discord, Dis is a red green colour blind player

"the colors of research papers are hard for me to see as colorblind. I can hardly tell difference between Advanced and Modern."

**Comment by MishkaFur** [comment]
Update, player on my server has yellow specific Tritanopia so in the below screenshot the advanced and Basic look near identical

"[16:28] Squishy252: The green and white are clear.
The first two are towards the same colour as the lighter background but if focusing I can see the difference
[16:29] Mishka: Yea the first two are same shade of yellow, but you can tell them apart from 3rd and 4th if focusing but otherwise they look pretty much the same?
[16:30] Squishy252: The top two and the middle two are very similar in my eyes"

![image](https://user-images.githubusercontent.com/61889138/99418691-323db180-28f3-11eb-9d73-9caa12bdbdb5.png)

Art wise could it be worth giving each one a unique picture as then regardless of colour accessibility they can be ID'ed via the picture?

**Comment by keegan-o** [comment]
I was going to hack these out but I think it'd be best to get little high quality variations on the icons for research papers.

I think for these ones specifically, things like making the basic research paper icon show a wooden plate and spoon, the meat versions have a slab on meat on the plate, and then modern or advanced ones having another variation on the plate. Or, the variation on that one could be in the lower text area with the empty squad being filled with a color or design like a star in silhouette.

Just remember to make variations focused on silhouette and objects more than color since the point is of course to make these color blind friendly. 

These are all the icons that will need the variations:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/27786a38-f9a0-4fdd-8d71-9faab0b293f2)

**Comment by RobertMangano** [comment]
![image.png](https://images.zenhubusercontent.com/5ee82262cf91f12b03cc5ad8/ce888366-9fc9-45f2-84be-fcc093d82070)added and assigned
