### ISSUE TITLE
[0.9.0.1] Contract board - buttons are not available

### ISSUE THREAD

**Issue by NuNky38** [StrangeLoopGames/EcoIssues#18128]
When addinig or editing Contract On Contract Board can not to click on the buttons (Remove, Up, Down), because it is located under the " Add " button"

![5](https://user-images.githubusercontent.com/69684724/92638300-a31d8780-f30c-11ea-804e-cb5af4b4cb87.jpg)

**Comment by beastyn** [comment]
@NuNky38 Thank you for the report.
As a workaround you can create a custom clause like the last one and remove the one on the top (button will be available)

**Comment by IcedForge** [comment]
Still an issue : Maybe the contract sections should be moved slightly apart, or change the size of the "Add Clause" button to no be across the entire bottom border?
https://i.gyazo.com/6a44946bacae7e8d0fb5d9b5822cc2ec.mp4


![Screenshot_399.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/41d2af12-addf-412a-b249-f6a67285054e)
So instead of this  ^

![Screenshot_401.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/bb6d5c71-4c12-436e-a872-544bc0b4985e)
Maybe have this instead ^?
Or alternatively have the add clause area instead ?
Another potential would be to add a very small spacing between each clause like it is for nested clauses as this seems to make the buttons less likely to interact with each other.
![Screenshot_402.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/fd733d66-d560-49e3-be12-921b84ea64a4)
![Screenshot_403.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/75235748-53d9-4ccd-b987-a64fcb71a846)

**Comment by IcedForge** [comment]
Confusion on my part, i missed that it was labeled release build not dev build. issue is fixed on Release review.
