### ISSUE TITLE
Crash when i start the game

### ISSUE THREAD

**Issue by florioz** [StrangeLoopGames/EcoIssues#18147]
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5198866/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5198867/Player.log)
[Player (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5198870/Player.1.log)
[error (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/5198871/error.1.log)

**Comment by redwyre** [comment]
This looks like it's crashing because of an audio driver issue.

I have read that nvidia drivers can cause this issue (if you install their audio driver), so maybe try updating nvidia gpu driver, or try removing the bundled audio driver. Alternatively make sure your motherboard sound drivers are up to date.

**Comment by florioz** [comment]
it's doesnt work, so i just reformated the computer and with the pilote got by windows update and ... it's work ! 
thanks for your time

**Comment by WeaselDog** [comment]
Glad to hear this is working for you now. Thanks for letting us know.
