### ISSUE TITLE
USER ISSUE: 0.9.0.2 Visual bug

### ISSUE THREAD

**Issue by Artem314159** [StrangeLoopGames/EcoIssues#18200]
**Version:** 0.9.0.2 beta staging-1786

![image](https://user-images.githubusercontent.com/17272063/92994367-42f03680-f502-11ea-8ab4-2114eef3a60d.png)
![image](https://user-images.githubusercontent.com/17272063/92994387-703ce480-f502-11ea-92f7-1325bda9cd1e.png)

What could be the problem?

**Comment by D3nnis3n** [comment]
That version isn't released yet and the issue is known.

**Comment by Artem314159** [comment]
Ok, sorry if I posted something wrong. (version taken from your site)

**Comment by D3nnis3n** [comment]
Oh, sorry. I didn't know the version has been placed on the website again, we're having issues with versions being available on the website despite they are not supposed to be, which is obviously not your fault.

The issue is a duplicate nontheless that we're working on :) Thanks for the report and sorry!
