### ISSUE TITLE
USER ISSUE: Popup Notification laws

### ISSUE THREAD

**Issue by SouSSouS16** [StrangeLoopGames/EcoIssues#18213]
![eco 2](https://user-images.githubusercontent.com/36658903/93005527-1f54dc80-f552-11ea-8404-b5d711776594.png)
![eco](https://user-images.githubusercontent.com/36658903/93005530-224fcd00-f552-11ea-88cd-660584d75ed6.png)

\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
in laws creation, in "THEN" > infobox on success > No

**Expected behavior:**
no popup

**Actual behavior:**
Despite having put no, there is always the popup that appears

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Seeing this happen on multiple triggers, some it functions on but most does not.
(harvest, player categories but not the rest)
Also this option should only be Yes - No, there is no need for it to fetch all the different options.
![Screenshot_361.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/b8ec2ef6-7ea5-47d0-a243-8e820b733cda)

**Comment by johnkslg** [comment]
- If you make it a bool instead of a GameValue<bool> it should just be a checkbox.
- The fact that it works on SOME but not ALL legal actions is worrying.  When making a solution, make sure theres just *one check* for the 'infoxbox on success', and that all the responses go through it (IE dont copy-paste the check everywhere)

**Comment by Deantwo** [comment]
Having this an option on a law seem like a bad idea. Then someone can make a law that stealthy tax people without their knowledge.

The issue is that the notification popup appear in the middle of the screen and doesn't handle duplicates in a nice way.

A nice example might be how current versions of SS13 handle duplicate messages.
Instead of showing each line like:
```
You are blinded.
You hear footsteps.
You hear footsteps.
You hear footsteps.
You hear footsteps.
```
it appears as:
```
You are blinded.
You hear footsteps. (×4)
```

Alternatively, allow a player to mute the result of specific laws.

**Comment by IcedForge** [comment]
![Screenshot_14.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/d126ccca-4d74-48c7-ba9d-3a0b6a9c8ea1)
This notification bar up top should still be occurring though so it shouldn't be an issue.

**Comment by beastyn** [comment]
+ this one #18405

**Comment by johnkslg** [comment]
I like the 'x4' idea!
