### ISSUE TITLE
USER ISSUE: Crashing on exit

### ISSUE THREAD

**Issue by AliaAnor** [StrangeLoopGames/EcoIssues#18217]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
After playing for a while, select Exit or Disconnect.

**Expected behavior:**
Disconnect gracefully
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213384/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213385/Player-prev.log)

**Actual behavior:**
Does not respond and windows asks me if I want to end the process

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213384/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5213385/Player-prev.log)

**Comment by mirasrael** [comment]
Unfortunately there is nothing in log what may help. Actually it seems like one of Unity Engine bugs which I observed in Eco and another games by myself. We updated Unity version since 9.0.1 multiple times, so probably this issue already fixed.
Closing because we can't either diagnose or confirm this issue fixed. If this issue still persist after 9.1 release then please re-open this issue and we will try to collect more info for diagnostic.
