### ISSUE TITLE
Client crashes - right after the start before main menu loads

### ISSUE THREAD

**Issue by Arnalix** [StrangeLoopGames/EcoIssues#18305]
Hi,
the client crashes right after the start. Even before the main menu is loaded. Black screen with tree bottom left and pop up unity window, then exit. I have updated all the drivers thoroughly, reinstalled game to different volumes, tried both 32/64-bit version from the site, tried steam previous version as well. It crashes for the versions 9.0+ only, 8.3.3 is fine. When I try to start server those start well (but no client). 
Please help,
Petr

Attached:

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5236445/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5236447/Player-prev.log)
[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5236457/DxDiag.txt)

**Comment by IcedForge** [comment]
Thank you for reporting this.

This looks like it's crashing because of an audio driver issue.

I have read that nvidia drivers can cause this issue (if you install their audio driver), so maybe try updating nvidia gpu driver, or try removing the bundled audio driver. Alternatively make sure your motherboard sound drivers are up to date.

**Comment by beastyn** [comment]
@Arnalix is it still actual for you? Did you try suggestions from #18147?

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
