### ISSUE TITLE
USER ISSUE: Stamp Mill no reduction when using Modul

### ISSUE THREAD

**Issue by coolinmaker** [StrangeLoopGames/EcoIssues#18347]
\
**Version:** 0.9.0.1 beta

**Steps to Reproduce:**
Place Stamp Mill
Put Modul inside

**Expected behavior:**
Reduce the cost of needed ore	

**Actual behavior:**
doesnt reduce cost 

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I dont have mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Sekor2600** [comment]
Because the cost of the recipe is a fixed cost item. You can see this in the yellow frame in the recipe when something is static and does not change with Modules or Talents

here a Example 
![grafik](https://user-images.githubusercontent.com/37456949/93685849-655df300-fab2-11ea-89c2-dd0474c72fde.png)

**Comment by coolinmaker** [comment]
nice thank you
