### ISSUE TITLE
RouteProbing may have a memory leak 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18377]
![image](https://user-images.githubusercontent.com/3536496/93797652-5e89ca00-fbf1-11ea-86e4-b8802163af3f.png)

**Comment by redwyre** [comment]
Maybe, the the bottom ones are actually the worst, eg total of System.Object[] is ~2.8GB
It actually looks like the last few are something to do with reflection and the RPCManager

**Comment by mirasrael** [comment]
It doesn't seems like RouteCache data really have problems from this snapshot. It only retains ~55Mb of memory which is quite realistic for big world size. As @redwyre mentioned most problematic are last lines, but they already fixed with Trade Tracker leak fixes.
Closing this because it seems already fixed.
