### ISSUE TITLE
[0.9.0.2 beta develop-60] Disabled state objects does not detect pipe access

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18397]
When you place an object and disable it via on/off button it does not detect when you connect water and you cannot turn it on 
because it has not water causing a catch 22 so you need to pick it up and place it down again, making sure you do not turn it off before connecting water and ventilation ( smog pipe if indoor ).

**Comment by olegshegai** [comment]
Possible solution: liquid tank UI initialization should check for on/off component and subscribe on it's state

**Comment by olegshegai** [comment]
Wasn't able to reproduce with blast furnace

**Comment by SlayksWood** [comment]
So now when you turned off Blast furnace. Water status will be green:
![image](https://user-images.githubusercontent.com/45708377/101632238-ac66df00-3a36-11eb-8446-6378412a9965.png)
So you can turn on it. After that, the water status will turn red:
![image](https://user-images.githubusercontent.com/45708377/101632322-ca344400-3a36-11eb-84ce-86b3cbb486de.png)
Seems it was fixed with pipe refactoring.
