### ISSUE TITLE
GPU out of memory possibly crashing drivers

### ISSUE THREAD

**Issue by redwyre** [StrangeLoopGames/EcoIssues#18403]
Some people are getting errors creating textures:
> The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
This can be caused by hardware or driver issues.

This is usually because the driver crashed, but in this case it may be because we are going over-budget on texture memory.

@keegan-o The solution would be to enable texture streaming on more textures to allow them to get removed or downgraded when running low on memory. Some candidates are:
* Ecopedia textures, they're not needed all the time
* world object textures, especially for rarer objects
* rare block textures

**Comment by keegan-o** [comment]
Ecopedia images are used as sprites and thus cannot have texture streaming applied, sadly.
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/797a8862-3036-4ecc-9189-a777a6523e65)

**Comment by keegan-o** [comment]
I set all world object textures to use streaming in Develop branch. I could easily do so with block textures, and potentially plant and tree textures as well. Any thoughts on if I should or not, @redwyre ?

**Comment by keegan-o** [comment]
After checking out blocks, plants, and trees, trees are the other painless option to enable streaming for. Blocks have major issues, and plants have something (instanced renderer stuff I would assume) preventing them from working as well since for textures to stream they need to re-load. 

So for now we have it enabled for all world objects, which works well on testing faked lower video memory budgets, and trees, which should help in some circumstances.
