### ISSUE TITLE
Cannot cancel job after 24h

### ISSUE THREAD

**Issue by Kenionatus** [StrangeLoopGames/EcoIssues#18438]
I have run into noncallable jobs. They are on workstations of players who's property was unclaimed by an inactivity law. They also do not complete, even if work and materials have been added. I haven't yet found one that I was able to cancel.

The pictures are from the same campfire.

![image](https://user-images.githubusercontent.com/54814353/94030984-b1fd4300-fdbe-11ea-9caf-998fd2027725.png)

![image](https://user-images.githubusercontent.com/54814353/94031010-b7f32400-fdbe-11ea-9917-77dcf42923c5.png)

![image](https://user-images.githubusercontent.com/54814353/94031025-bb86ab00-fdbe-11ea-9e50-c7248eccb8b4.png)

**Comment by Kenionatus** [comment]
It seems that it's not possible to use the collect button if one isn't the owner, but jobs complete if there is space in storage (which the job owner connected).

**Comment by olegshegai** [comment]
Hi, @Kenionatus 
Thanks for the feedback, it actually helped to spot some interesting nuances and will reduce possibility of similar cases in future.
This is going to be fixed in some of the upcoming updates. 
Currently you can claim deeds with the table and take ownership of the projects (there will be a button in bottom-left corner of a tooltip):
![image](https://user-images.githubusercontent.com/56091594/94998969-8fd5a300-05be-11eb-9a93-44ee59aa4c34.png)
After that, you will be able to cancel them.

**Comment by beastyn** [comment]
Collect button should be on the current owner side.
And now a creator of an order have a collect button

Here:
I took an order from Kirill
I can't finish a project cause I do not have Collect button
![bandicam 2020-10-06 12-40-04-729](https://user-images.githubusercontent.com/27898520/95173462-2201c500-07d2-11eb-96e4-f5d0f4d2f8ef.jpg)

And Kirill can collect and finish it
![unknown (3)](https://user-images.githubusercontent.com/27898520/95173819-a3f1ee00-07d2-11eb-86e3-2b546ab23b04.png)
