### ISSUE TITLE
[0.9.0.2 beta develop-62] Government Bank permissions further refinement

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18461]
When a player is missing a title with permissions "Has Government Banking privileges", it should disable government tagged account access regardless of the players manager/use permissions and only allow to add managers but not actually use it for purchases or transferring money out of it this to avoid any issues of tax evasion using a government account as an "offshore tax free" account.

**Comment by johnkslg** [comment]
@olegshegai where did we land on this? Whats the current behavior with regards to it?

**Comment by olegshegai** [comment]
Currently only players with banking privileges can create new government accounts.
But these players do not have access to other government accounts (like it used to be earlier) unless they are users or managers. 

Suggested solution where only players with government banking privileges can spend money doesn't look good since it won't be possible to setup some classic solutions, like `road managers` (regular players with `use` access to `government road funds`).

Here are some separate ideas (each of them will cover the problem with some costs, can play with combinations).
- At least one manager with banking privileges required to spend money from the account.
    - The problem is solved on a pretty low level.
    - Does not ruin dual-permission's access.
    - Can be exploited: just add privileged user, spend money and remove him again.
- People with banking privileges can manage any broken account (lets call them "broken" for a better readability instead of "government account that is not currently managed by anyone with government banking privileges").
    - Violates dual permissions.
    - Can be used to "steal" money.
- Combination of the previous ones: broken accounts become frozen (nothing can be spent or changed). There is a privilege that allows to see such accounts and resolve them manually (via executive office would be more government-like).
    - Still violates dual permissions and can be used to "steal" money, but on the government level which seems to be okay.
- All the money go to treasury when the account becomes broken.
    - What will it look like for multi-government?

**Comment by IcedForge** [comment]
I like the freezing of an account, that way if you have permissions to the treasury you can simply tax that account to clear it of funds if needed or via executive action.

At the same time i also like the money transfer back to treasury if there is no permission holder as manager?

**Comment by johnkslg** [comment]
I think the 'government account' bool just makes it not count in wealth calculations.
It doenst need to do anything with permissions, because that can be configured on the bank already
IE, you can just set the 'user' to be the desired elected title, and delete all 'managers'

We could make more checkboxes in government advanced settings 'can be used as source for transfers' and 'can be used as target for transfers', then these can be checked off if we want all transfers to go through law and tax system.

**Comment by johnkslg** [comment]
And while we're at it, rename 'government account' to 'Consider In Wealth Calculation' to make it more clear.
