### ISSUE TITLE
USER ISSUE: Soil Sampler on patch 9.0.2 inproper infomation

### ISSUE THREAD

**Issue by zeplintwo** [StrangeLoopGames/EcoIssues#18466]
\
**Version:** 0.9.0.3 beta release-78

**Steps to Reproduce:**
Use soil sampler on anydirt block.
look at NPP levels they will read 0%

**Expected behavior:**
A proper NPP percentage

**Actual behavior:**
Getting 0% no mater where you sample on server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by beastyn** [comment]
@zeplintwo Thank you for the report. 

NPP was removed until fixes for plants will be applied.

From patch notes:
- First batch of improvements to plants to improve their survivability
Please note that we're working on more fixes and improvements for the current issues with plants, due to be released in the next Updates.
