### ISSUE TITLE
Some purchases are not recognized correctly by web and are shown as amount "0"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#18528]
This makes their total paid amount not raising, disallowing them from getting cheaper upgrades.

**Comment by denysaw** [comment]
Oh, that's can be already tested on `staging`. We really had troubles with transactions. SignUp request was overwriting transaction with new one priceless, that's why we had 0 in `users_products` and 2 separate transactions in `all_purchases` (1 with correct amount and 2nd with 0). Now that's fixed (not yet merged to prod though).
