### ISSUE TITLE
[0.9.0.3 release-78] Mistake icon of module

### ISSUE THREAD

**Issue by Astrija** [StrangeLoopGames/EcoIssues#18524]
Icon of module "mining advanced module" have mistake icon, because have icon "touch conveyor sorter", but need "Vibrating sorter"
![изображение](https://user-images.githubusercontent.com/13696708/94590040-bfb73a80-028e-11eb-8917-df34754e3e31.png)

**Comment by IcedForge** [comment]
I agree on this we have unique icons for Basic, Modern i believe it would fit with using the shaker / dry sorter for medium tier since it is only stamp mill / screening machine that uses it.
![Screenshot_134](https://user-images.githubusercontent.com/24981362/94676469-aa3c2200-031b-11eb-980f-466a1e2e9776.jpg)
![Screenshot_135](https://user-images.githubusercontent.com/24981362/94676478-ad371280-031b-11eb-89ec-3136c880e142.jpg)
![Screenshot_136](https://user-images.githubusercontent.com/24981362/94676484-af00d600-031b-11eb-9e7b-67bfd7632f81.jpg)
