### ISSUE TITLE
Block Preview Doesn't Support Alpha Cutout

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#18591]
- [ ] Shadowplacement looks different than the block itself. looks like a whole board
![grafik](https://user-images.githubusercontent.com/37456949/95137994-8472ab00-0769-11eb-9c98-9f7bbdb01186.png)
![grafik](https://user-images.githubusercontent.com/37456949/95138019-905e6d00-0769-11eb-8c81-cbf7e894eb5c.png)
![grafik](https://user-images.githubusercontent.com/37456949/95138243-18dd0d80-076a-11eb-957a-042715731c51.png)
![grafik](https://user-images.githubusercontent.com/37456949/95138263-24c8cf80-076a-11eb-9d7f-496841aa2300.png)

- [ ] Missing faces 
![grafik](https://user-images.githubusercontent.com/37456949/95138082-af5cff00-0769-11eb-8a77-b022d12b1677.png)

**Comment by keegan-o** [comment]
These are all code/shader issues, nothing in the blocks. The black shadows are all over the place and have been for ages, and the preview being different is likely because the shader for transparent preview blocks does not support cutout alpha as well.

**Comment by keegan-o** [comment]
The black 'shadows' should be their own issue, as that is un-related and probably much harder to fix.

**Comment by keegan-o** [comment]
I would call the no alpha cutout on preview low pri and the annoying black shadows medium priority, personally. Opening new issue for the black shadows.

**Comment by keegan-o** [comment]
This is actually a bad example of the lack of alpha cutout on previewing block placement, because with this one it is also acknowledged that my shortcut to use alpha cutout instead of real geometry (for performance) is not great looking. Fixing it however will mean this is no longer a block using alpha cut-out at all, so this will no longer be an example of a block for testing if the preview mesh can support alpha cutout. Atm there are very few situations in eco where we use alpha cut-out on player built blocks (but there may well be more in the future like a lattice woven fence or something we want a detailed fringe/molding on)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/9423872f-2698-449b-91e0-29e9c97ff2ae)

Updated the clad wall meshes and materials to use just one material and real geometry, actually this is probably ultimately better for perf anyways since the old ones had to be duplicated to render on both sides anyways. The slats are thicker now but still retain the look I think.
