### ISSUE TITLE
[0.9.1.0 beta develop-77] Civics: Ignore auth trigger issues

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18629]
Checked through the action type triggers and collected a list of those that have an issue.

Economy Trigger
 - Inventory Action
	 - Deposit, retrieve

Pollution Trigger
 - Drop Garbage

Farming Trigger
 - Plant seeds

Crafting Trigger
 - Add Labor to craft

Economy Trigger
 - Craft Currency ( not to be mistaken with mint money )

Construction Trigger
 - Place or Pick up Object
	- Both

**Comment by johnkslg** [comment]
@olegshegai can you help with a pass on these actions?  The problem is that these actions are doing permissions test *outside* of the AuthManager. All permissions tests should be done through the AuthManager, that way laws can ignore them.  That call is made here:
![image](https://user-images.githubusercontent.com/3536496/95383459-111f8500-08a0-11eb-9b78-1230e9caa2be.png)

So for each action, make a law that ignores auth for it and then try to do it in non-permissioned places (use the chat command /property ownnone to quickly make a piece of property not yours).  Remove anything that is blocking your ability to do it when auth is ignored.  

Then try doing it without the law, and verify that it's still properly blocked in that case, through the auth manager. 
You might need to add some stuff to AuthManager to make this work, or adjust the AccessNeeded values of the actions.
