### ISSUE TITLE
USER ISSUE: farm yield potential

### ISSUE THREAD

**Issue by pestinhk** [StrangeLoopGames/EcoIssues#18690]
\
**Version:** 0.9.0.4 beta release-94

**Steps to Reproduce:**
seem the last update mess up the farm yield potential and also my skill point

**Expected behavior:**
at first I think it's the fertilizers problem so I take the fertilizers skill,but then I check the plant potential map, now lots of plant showing dark on the map

**Actual behavior:**
so that's a bug and now I wasted one skill point and have to wait 10 day for another point gain, please fix it quickly, it's annoying

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Thank you for reporting. Previous patches bypassed nutrient requirements and now that it is fixed, old worlds do not have nutrient layers which is what is causing your poor farm yields you need to apply fertilizers ( which will also fix the potential map as it is tied to nutrients as well since  0 nutrient = no plant will be yielding more amounts in this area ) alternatively you can get the server admin to use these 3 commands to reset the nutrient world layer.
"/sim setlayer Potassium, 0.6, 0.9"
"/sim setlayer Nitrogen, 0.6, 0.9"
"/sim setlayer Phosphorus, 0.6, 0.9"
