### ISSUE TITLE
9.0.4 Crop yields on all crops dropped to minimal value after update. 

### ISSUE THREAD

**Issue by Ser-Geeves** [StrangeLoopGames/EcoIssues#18704]
On the server I play, it's crop yields and yield potentials that seem to be affected similarly to issue #18687 . While it has not destroyed the entire populations of crops, all yield potentials are dropped to the minimum available unless fertilizer has been used. Even in areas where no players have been in the last 10 days. 

Unlike issue #18687 our trees have not been affected (as of the writing of this post).
Having checked with map layers, only trees still have any yield potentials.

With the farmer and gatherer skills at 7, max rank, I can get at maximum 2 yields from a crop, those without report only getting 1 yield per crop. Before the patch, both these numbers where ranging from 1-4 without the gatherer skill and 2-8 with the gatherer skill. 

We're looking into things on our end, but would like advice if possible.

**Comment by IcedForge** [comment]
@Ser-Geeves Thank you for reporting. This is an unfortunate side effect from the plant fix that were applied in 9.0.4 and the bandaid done in 9.0.3 caused nutrient world layer to poof. 
You can ask an admin on the server to run these 3 commands
"/sim setlayer Potassium, 0.6, 0.9"
"/sim setlayer Nitrogen, 0.6, 0.9"
"/sim setlayer Phosphorus, 0.6, 0.9"
And it will fix up the nutrient layers again which is why you see such a poor yield.
