### ISSUE TITLE
Bathtub diminishing housing value - Eco 9.0.4, Server Bug(?)

### ISSUE THREAD

**Issue by TrasHC** [StrangeLoopGames/EcoIssues#18714]
When a bathtub is placed in the same room with other items from the sink category, something strange is happening to the diminishing returns, where following items don't get the expected values. Best explained in pictures:

![20201009130752_1](https://user-images.githubusercontent.com/18727081/95580470-ad2fc480-0a37-11eb-8dc6-53cd9a565db2.jpg)
![20201009132707_1](https://user-images.githubusercontent.com/18727081/95580495-b91b8680-0a37-11eb-8383-5a4c74f15e13.jpg)
![20201009135130_1](https://user-images.githubusercontent.com/18727081/95580515-c0db2b00-0a37-11eb-9719-6ff87c7efa44.jpg)

**Comment by IcedForge** [comment]
@TrasHC Thank you for reporting.

yes there seems to be some inconsistencies in how its calculating the value of the objects
1. Sink (highest value item )
2. Bathtub ( 2nd highest value ) / 50%
3. Small Sink ( lowest value ) is stating 49%? Should be 35%? since there is already 2 objects so it is the 3rd in line and with its 70% value reduction ?

Furniture diminishing returns has always been a bit of black magic for me, maybe you have more insight in how this actually works @WeaselDog 
![Screenshot_128.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/1e6cbe32-aab5-4c65-b221-2c3c9afc5247)

**Comment by TrasHC** [comment]
Thought i deleted my post again, did someone restore it? I figured out the way it works and assumed it's meant this way - and tbh I like the way it is right now, because you do not need to worry about items further up the list devalueing items further down because of their lower diminshing returns - it just should be explained somewhere...

The diminished value of an item in nth position is simply its diminishing return to the nth power.

In the screenshot:
Sink: 5*(1-0.8)^0
Bathtub: 3*(1-0.5)^1
Small Sink: 1*(1-0.3)^2
