### ISSUE TITLE
Patches in Rainforest Biome empty

### ISSUE THREAD

**Issue by NemoLArs** [StrangeLoopGames/EcoIssues#18757]
On my server i saw that there's some patches in the Rainforest biome that's completly empty except from trees. No flowers, no bushes no nothing. See pic..

![ecorainforestempty1](https://user-images.githubusercontent.com/32419758/95976011-37e93880-0e17-11eb-939d-ee43b7fba350.png)

There is a couple of these patches. So far only found in rainforest. 

Uploading my server folder if that helps.
Server files : https://www.dropbox.com/sh/xg32a6518y10w2l/AADMI_kEt3CTCwqn-uxaYM-Fa?dl=0

// Nemo - Mr Magic

**Comment by IcedForge** [comment]
The area affected is in limbo due to heat map + soil moisture + rainfall collides into this perfect storm situation where its too hot or too wet for either type of plants to survive in this border area.
Heat overlay on the area affected
![Screenshot_145](https://user-images.githubusercontent.com/24981362/95982158-104a9e00-0e20-11eb-82af-d8fd33d1f52e.jpg)
Probably need to take a look at possible generation issues for further information.

**Comment by hitzu111** [comment]
In our world, we have such a spot at the border of 4 tree species grow areas where neither of them can grow (redwood, fir, spruce, old growth redwood). In that place around the center bottom house before the last update, there were more trees, including an old growth redwood tree.

![Screenshot_144](https://user-images.githubusercontent.com/50346354/95985412-3cb8e700-0e2d-11eb-95bc-4b46fa70b38c.png)
![Screenshot_143](https://user-images.githubusercontent.com/50346354/95985414-3e82aa80-0e2d-11eb-81b8-c457f070f79d.png)
![Screenshot_142](https://user-images.githubusercontent.com/50346354/95985415-3f1b4100-0e2d-11eb-8289-375fe73b9711.png)
![Screenshot_141](https://user-images.githubusercontent.com/50346354/95985416-3fb3d780-0e2d-11eb-952b-96424725a2e4.png)
![Screenshot_140](https://user-images.githubusercontent.com/50346354/95985418-404c6e00-0e2d-11eb-8c59-d13487ba2b95.png)
![Screenshot_139](https://user-images.githubusercontent.com/50346354/95985424-417d9b00-0e2d-11eb-88e0-9d6463cb140a.png)
![Screenshot_138](https://user-images.githubusercontent.com/50346354/95985427-42163180-0e2d-11eb-8bf7-2c24b579a887.png)

**Comment by SlayksWood** [comment]
> **Version:** 0.9.0.5 beta release-100
> 
> **Steps to Reproduce:**
> 
> 1. We played about 10 Days now
> 2. Since a few days all plants in the rainforest except the trees and the bushed with red flowers are remaining
> 3. Our eco system is not affected that much, we have no pollution at all, only a level 1 pollution of the ground because of tailings until we move them underground. But that area is faaaaar away from all rain forests
> 4. The rest of the world is fine
> 
> **Expected behavior:**
> Plants won't die out in the rainforest.
> 
> **Actual behavior:**
> Plants in the rainforest die out
> 
> **Do you have mods installed? Does the issue happen when no mods are installed?:**
> No mods installed
> 
> **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by NemoLArs** [comment]
> > **Version:** 0.9.0.5 beta release-100
> > **Steps to Reproduce:**
> > 
> > 1. We played about 10 Days now
> > 2. Since a few days all plants in the rainforest except the trees and the bushed with red flowers are remaining
> > 3. Our eco system is not affected that much, we have no pollution at all, only a level 1 pollution of the ground because of tailings until we move them underground. But that area is faaaaar away from all rain forests
> > 4. The rest of the world is fine
> > 
> > **Expected behavior:**
> > Plants won't die out in the rainforest.
> > **Actual behavior:**
> > Plants in the rainforest die out
> > **Do you have mods installed? Does the issue happen when no mods are installed?:**
> > No mods installed
> > **Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

I did attach the whole server folder. And it's not the same issue. The plants don't die. They don't spawn in on these areas. And i think (atleast my tests) that all server and all worlds have this "issue" atm. So just start a world and look around in the "jungle".

**Comment by WeaselDog** [comment]
I investigated this a bit more. Biomes are showing moisture levels well outside of the correct range for that biome.  It causes a lot of strange behavior. You can quickly check with Soil Moisture overlay. I do not see this issue with temperature overlay, even with biomes that are closely overlapping.

Here is Rainforest with 0.671 moisture. It should be no less than 0.7:
![RainforestSoilMoisture](https://user-images.githubusercontent.com/47330823/101292428-3b1ff580-37c4-11eb-9859-f95d4b07056a.png)

Here is Coldforest with 0.470 moisture. It should be no less than 0.5:
![ColdForestMoisture](https://user-images.githubusercontent.com/47330823/101292472-80dcbe00-37c4-11eb-8a29-aad57ef3af89.png)

**Comment by mirasrael** [comment]
I investigated the issue and there few problems.
1. It had significant rounding errors which caused Rainfall and Temperature values to go out of ranges (Fixed in https://github.com/StrangeLoopGames/Eco/pull/7451).
2. In 9.2 we changed way how Moisture works for plants. Previously it was Rainfall, now it is Soil Moisture. But moisture for Biome is actually Rainfall, because it is only possible relatively constant characteristic. Soil Moisture also may be modified by fresh water. Also it affected by spread and evaporate effects which causes Soil Moisture to drop in original locations. Another notable thing - it has only 0.8 of Rainfall layer on initial generation and increases by 0.04 of Rainfall layer every tick (10 minutes), but at same time decreases by 0.05 from evaporating. It currently very complex characteristic with many interactions which hard to control and keep in specific range. It either should be reverted back to Rainfall or simplified if we wanna control it (i.e. it may be just sum of Rainfall and Fresh Water which synced every tick).
