### ISSUE TITLE
[Eco Server 0.9.1.0 beta staging-1804]  Failed to load server

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#18787]
i am use SLG account for first enter in game but second from Steam and get Error

https://yadi.sk/d/ia352dPGlB5i3w
[log_201015062849.log](https://github.com/StrangeLoopGames/EcoIssues/files/5390105/log_201015062849.log)

**Comment by mirasrael** [comment]
Investigated issue. It related to server locale changes and way how personal account naming and lookup works.
Assume following steps:
1. Start server in English. Login as Stalef, "(Stalef Credit)" named currency created.
2. Stop the server and change locale to Russian.
3. During load it will try to create personal currency for User and will lookup it by personal account name (which is now "(валюта Stalef)"), fails to find mapping and create new personal currency with this name.
4. Stop the server and run again. It now crashes with the reported error, because it now has two personal currencies associated with Stalef with different names: (Stalef Credit) and (валюта Stalef).

**Comment by mirasrael** [comment]
Fixed in 9.2
