### ISSUE TITLE
Placing Carts Causing Excessive Client Side Lag/Disconnect

### ISSUE THREAD

**Issue by Rybadour** [StrangeLoopGames/EcoIssues#18801]
Currently on our server placing a Wood Cart, anywhere causes the client placing the cart to become unresponsive for around 3-4 minutes. As the client I can move but not interact with anything. Chat and notifications can be received but not sent. After unresponsiveness ends all my actions get executed, chats sent, inventories opened, etc.

**Comment by Rybadour** [comment]
Also when picking up a steam truck...

This is very urgent bug game play experience is greatly hampered.

**Comment by Rybadour** [comment]
Additional observations: It seems I can dupe Steam Trucks during this if I log out and log back in.
My placed steam truck now will not accept the fuel from the cart I placed during all of this. Logging out and in does not change the fuel situation.

**Comment by MishkaFur** [comment]
Please can you provide full server specs including OS as advised on Discord :)

**Comment by SlayksWood** [comment]
@Rybadour Thank you for the report and sorry for waiting. This is known issue, and it will be fixed in 0.9.1. To solve this problem now you need ask your admin to restart the server. Sometimes on large servers with large online this can happen.
But it will be fine to have log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by IcedForge** [comment]
Will close this for now as this should be addressed in 9.1, if you run into this issue again after update please reopen and let us know.
