### ISSUE TITLE
Deadlock when trying to bind and unbind simultaneously

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#18818]
Thread 1:
![image](https://user-images.githubusercontent.com/3536496/96398784-8da84280-1181-11eb-9dab-13c5dbf7b751.png)

Thread 2:
![image](https://user-images.githubusercontent.com/3536496/96398815-9d278b80-1181-11eb-8e25-e64b6a40bb34.png)

Dump here: https://drive.google.com/file/d/1iJN0VLvoc-_d0P7dgmzl7UG_L0sq4qGs/view?usp=sharing

Was debugging when it happened, but it could happen naturally

**Comment by mirasrael** [comment]
Investigated this issue. It doesn't looks like dead-lock. I analyzed both paths on screenshots and they can't cause dead-lock, because they doesn't have nested locks. Also in stack trace you can see they both locked by thread 33424 (but in case of dead-lock you should have 29608 (BindController) locked by 3112 (UnBindController) and vice versa). I tried to analyze dump file to get info about thread 33424 (ClientMessage), but DMP doesn't contains stack trace for this for unknown reason. So may be this thread was corrupted somehow and didn't release the lock.
I'm closing this issue for now, because it seems like a regular lock, but if you have it another time can you please add info about locking thread (you can get it number from the message "Waiting on lock owned by Thread <>").
