### ISSUE TITLE
[0.9.1.0 beta staging-1806]Dev Command: /civics spawngov oddities

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18822]
Not sure if intended or not, but using this command it does not pass / enact all object types
Districts, election processes are applied and added to object
Demographic, Law is only added as drafts
Title is added as an election draft.

**Comment by IcedForge** [comment]
Also not sure what happened here
![Screenshot_48.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/15e6ab9d-73af-423c-84c9-5dd32aace313)

**Comment by serpopov** [comment]
this issue caused by concurrency:

when election passed, it sets proposed.State = Active **CivicUtils.cs**
![image](https://user-images.githubusercontent.com/4238643/105535252-3cc85d00-5d21-11eb-8fec-26f4f6a13193.png)

this change triggers SubsribeAllRecursive OnChanged to happen in different thread: **DisplayErrorView.cs**
![image](https://user-images.githubusercontent.com/4238643/105535380-684b4780-5d21-11eb-8bcb-b5a57edcf208.png)

which cause PropertyScanner to check validity of constitution.
This validity check tries to check constitution: **Constitution.cs**
![image](https://user-images.githubusercontent.com/4238643/105535638-aa748900-5d21-11eb-89cb-30a3413d46c3.png)

And this will set new constitution state to _Removed_ immediately **ConstitutionManager.cs**
![image](https://user-images.githubusercontent.com/4238643/105535704-c710c100-5d21-11eb-8a84-31526977d453.png)

and after this constitution is no longer valid.

to make it 100% reproduce we could add Sleep in proposing thread:
![image](https://user-images.githubusercontent.com/4238643/105535845-f8898c80-5d21-11eb-91c4-04e3bcb70232.png)

**Comment by serpopov** [comment]
Actualy this would happen no matter which thread it is running, same or different.
proposable's OnChanged calls should be delayed here until all code below performed

**Comment by mirasrael** [comment]
The main issue here that State change isn't atomic. It has two parts:
State = value;
and then later:
OnStateChangedInternal
Between these two lines may happen everything (including actions which changes State to different value as in above example). It also will go wrong if you check the state until it fully applied (in example above it collects active constitutions and removes all active which isn't current constitution, but no one is current, because it didn't yet handle state change callback).

There few ways to fix it:
1. Make state change atomic. It will require write lock on state modification and read lock on state access. Cons: it may create dead-locks when used inaccurate and it may block critical threads during state change processing (depending on cost of state change it may be an issue or not).
2. Align all state changes to single-thread. In this case instead of direct state change it will create an operation which then added to queue and will be processed next Tick. Same with operations like UpdateConstitution. They shouldn't happen instantly on callback, but instead schedule the operation. It will require code refactoring and all code usages should be rewritten to either async-await pattern or callback pattern. This way it may also optimize updates (only one update per tick per multiple operations), free of locks (and so dead-locks).
3. Extract all logic to separate service and perform all modifications via this service which has full control over operations and so may correctly control flows and set locks if required. Direct property modifications should be disallowed this way. I.e. instead of State = Active, OnStateChanged => SetGlobalConstituion(this) it will be `service.SetGlobalConstitution(constitution)` which internally sets constitution.State = Active etc. Also requires refactoring, but without async code.
