### ISSUE TITLE
[0.9.1 staging-1810] Timer for disabling constitution doesn't work.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#18830]
Step to reproduce:
- ratify constitution:
![image](https://user-images.githubusercontent.com/45708377/96459386-be908200-122a-11eb-8cb9-8ed3cc446571.png)
- pick up it, I have notification that this constitution will be disabled in 20 minutes.
![image](https://user-images.githubusercontent.com/45708377/96459778-2a72ea80-122b-11eb-8371-38dfb70fac6b.png)
- wait 20 minutes, nothing happens.
![image](https://user-images.githubusercontent.com/45708377/96462229-049b1500-122e-11eb-8dfd-358f698ea4dc.png)

Check this one after fix #18182

**Comment by johnkslg** [comment]
@olegshegai Can you help with this?

**Comment by olegshegai** [comment]
Seems to be okay.
I guess the problem is about server settings: `minutes between civics updates` are real minutes and not affected by fast forward.
So disable span may already expire, but civics plugin didn't tick yet.
![image](https://user-images.githubusercontent.com/56091594/96558797-db799380-12c4-11eb-9271-1e1541a282a6.png)

**Comment by IcedForge** [comment]
We were not fast forwarding though?
