### ISSUE TITLE
[0.9.0.5 beta release-100] Cannot unclaim/delete land passed to elected title via law

### ISSUE THREAD

**Issue by aaronstatic** [StrangeLoopGames/EcoIssues#18864]
I have a law that passes land from abandoned users to an elected title, but the person in that elected title cannot unclaim it or delete the plot. Says "this plot belongs to Mayor" but I am mayor

![image](https://user-images.githubusercontent.com/899639/96749606-c0b73400-1416-11eb-8f47-b166c86c699b.png)
![image](https://user-images.githubusercontent.com/899639/96749652-cdd42300-1416-11eb-8f31-f0006e342791.png)

**Comment by SlayksWood** [comment]
@aaronstatic Thank you for the report. This is known issue and will fixed in 0.9.1 #18537, but you can avoid it now:
You need to press gear:
![image](https://user-images.githubusercontent.com/45708377/96835972-01ca3b00-144d-11eb-8a31-9a939bfd4e1f.png)
and transfer property to yourself, then you can unclaim it.
