### ISSUE TITLE
[0.9.1.0 beta staging-1827] Wrong types or missing error msg when moving items in the UI

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#18980]
Adding this issue as a collective for all UI related drag & drop message issues.

Missing prompts when incorrectly dragging materials into a slot that does not accept the item.

- [x] Stockpile item into chest needs to give an error saying, this item is too bulky and cannot be stored in a chest or something like it.

- [x]  Dragging any item into this red section returns item to previous cell and not move it at all, giving no msg as to why this is happening. 

![Screenshot_17.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f4690754-186b-44e8-918b-01e43c9f3670)

- [x] If you shift drag items into the red zone, it will give you an error prompt with "There is no room in destination"
and if you shift drag items into the blue zone it will not give any notifications at all.

I suggest an overall rework of how this is detected and if you shift drag into a containing ui element it would act as if you dragged it into a cell  and auto sort ( big quality of life improvement factor )
![Screenshot_19.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/8ba6895b-9c73-4339-9afe-fe58d552d18e)

- [x] Dragging an ineligible item into a fuel slot, it will give this error which should be "This item is not an accepted fuel type"
- [x] Dragging a non tool item into repair bench it also does this.

![Screenshot_20.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/11a26b83-5dc3-4f9d-a4d9-f23f106f006f)

- [ ] Dragging an item into a module slot in work benches that is of incorrect type or not a module at all gives no error.

**Comment by IcedForge** [comment]
Adding this #17721in here as its related in regards to moving items into non cell areas makes it forget where items came from and drops them at the top of the list instead.

**Comment by madpingui** [comment]
Tested on staging branch editor:

Stockpile into chest:
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/20213f44-8049-4131-87bb-703c0c51df1a)

Item into fuel storage:
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/3e63bebe-50e2-4530-964f-84d2278e52dc)

Non tool item into tool bench:
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/72ecd5b9-4e0c-4eb7-9bc7-0cf4176e33a4)

When an object is moved to an empty area, the item simply returns to its default place and in my opinion this is the correct behavior (just as it is without saying any error, since this would be overloaded to put an error for each movement that the user does), also the shift drag to the empty areas of an inventory already auto sorts the item.
![Shift.gif](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/91a154fe-3160-40f2-acd2-1b2c44f2cce4)
