### ISSUE TITLE
[0.9.1 release-105] Some tool animation has wrong speed and need improvement in 3rd person view

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19058]
I tested tier1 tools. Wrong speed.
- [x] hammer: 10 action, but 14 animation (Could be related with modern hammer speed)
- [x] stone sickle: 10 actions but 9 animations.
- [x] hoe: 12 actions, but 13 animations
- [x] machete: 10 actions, but 13 animations.

it is necessary to slightly better select the speed of the tools.

I think it needs to review the animations:
- [ ] Machete.
- [ ] Axe

**Comment by SlayksWood** [comment]
#19177
> The Reaping animation in third person view looks awkward and swings the wrong way
> By comparison, in first person view, the reaping action is smooth and first goes right to left, then left to right to complete the movement and looks very natural.

**Comment by SlayksWood** [comment]
#19178
> The chopping motion to chop down a tree is vertical in 3rd person view, instead of horizontal like the first person view

**Comment by Quadbro** [comment]
Currently machete uses axe animation for 3-rd person. Maybe intended, looks good.
Fixed animation timers in 3-rd person for: hammer, sickle, axe,, machete, hoe
Now they should have same timings and speed as for first person.

Reap animation has same direction in both view (maybe outdated?)
Axe chop in 3-rd person differs, but probably we need to ask someone to make a different one (for same directions)
Fixed as much as possible with animation controller/code, the actual animations probably need to be fixed by art team
