### ISSUE TITLE
Plants are allowing placement atop them of world objects

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19066]
![image](https://user-images.githubusercontent.com/3536496/98034416-d0962700-1dcb-11eb-93a8-8d19eea9825b.png)
May be related to https://github.com/StrangeLoopGames/Eco/pull/7088

**Comment by tuha263** [comment]
This occurs because of the conflict of player's input when you move the object above the plant (which can interact with)
![PlaceObjectOnTopOfPlant](https://user-images.githubusercontent.com/9598614/99260605-3368d300-284e-11eb-85ee-9858a889ec7f.png)
In this case when the "E Pick up" appears then you right-click, you can place the object above the plant.
So to prevent it, I will make the object's shadow invisible when the "Place" action does not appear.
