### ISSUE TITLE
Game progression as well as titles were messed up after recent update

### ISSUE THREAD

**Issue by POLARICED** [StrangeLoopGames/EcoIssues#19072]
Basically when we logged onto the server after the recent 9.1.0 patch all our profession went from x level (the level we had before the update) to max level doing any skill related operation, ie. mining went from level 5 to level 7 by hitting sandstone. The same thing happened with elected titles are now invalid creating a whole mess with laws that depended on those titles.

**Comment by IcedForge** [comment]
@POLARICED Thank you for reporting these issues.
The progression experience issue is most likely related to an issue with your servers difficulty.eco being incorrect after it was fixed in 9.1
Update this by removing your old one and set difficulty again.

Titles got removed from the government offices on migration unfortunately, if you pickup the government office and place it back down you should be able to reattach the missing titles.

Please close this if this resolves your issue. If you still have problems you can contact me directly on discord(Ice Forge #5886) or just comment and reply here.

**Comment by POLARICED** [comment]
The difficulty was resetted fine. About the titles, unfortunately the admin of the server used admin commands to remove the title and we tried to re add it via the voting system which caused an error in the webpage. This is a bit of the error:

la eleccion de titulo de equipo gestor no se puede votar: Error: {"Errors":{"RankedVotes[0]":["Could not convert string to integer: Yes. Path 'RankedVotes[0]', line 1, position 55."],"RankedVotes[1]":["Could not convert string to integer: No. Path 'RankedVotes[1]', line 1, position 60."]},"Type":"https://tools.ietf.org/html/rfc7231#section-6.5.1%22,%22Title%22:%22One or more validation errors occurred.","Status":{},"Extensions":{"traceId":"|c097f66c-4dd11e08f40ac3c0."}}

Can this be fixed somehow?

**Comment by POLARICED** [comment]
Somehow it fixed itself, thanks for the support
