### ISSUE TITLE
USER ISSUE: Bloomery glitch

### ISSUE THREAD

**Issue by normanrichomme** [StrangeLoopGames/EcoIssues#19097]
\
**Version:** 0.9.1.0 beta release-105

**Steps to Reproduce:**
Place bloomery. Load with fuel. Doesn't pull from nearby stockpiles at all. Load material into it manually. Suppy work. Once done with one work order, it is unable to put the iron ingots in a nearby stockpile. Try to collect iron ingots from it and it says my inventory is full even when completely empty. Doesn't let me cancel the work order because I need to collect. Doesn't let me break it because it has an active order.

**Expected behavior:**
A working bloomery

**Actual behavior:**
A machine made to eat 2 iron concentrate and an indestructable brick.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Thank you for the report. You can't collect this order, because you have 2 different items (Slag and Iron bar) that you need to carry on hands.
1. Did you link any stockpile?
![image](https://user-images.githubusercontent.com/45708377/98082074-34caf080-1e89-11eb-8683-369f1816a809.png)
I don't have any problem:
![image](https://user-images.githubusercontent.com/45708377/98082119-47452a00-1e89-11eb-83bf-09642b39e51a.png)
2. Provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
3. Can you describe the problem in more detail, perhaps with screenshots or videos?

**Comment by IcedForge** [comment]
Is this on owned property or is it unowned?
If the machine is owned by a title this could be a problem with links.

If you own the property and you have linked stockpile do you still have this issue?

**Comment by IcedForge** [comment]
Will close this issue as its almost been 30 days without a reply.
