### ISSUE TITLE
Inconsistent format used for the labor icon tooltip for the Tailoring Skill Book in the Research Table Crafting page

### ISSUE THREAD

**Issue by dmplatten** [StrangeLoopGames/EcoIssues#19192]
Inconsistent format used for the labor icon tooltip for the Tailoring Skill Book in the Research Table Crafting page

![Untitled](https://user-images.githubusercontent.com/32143431/98451963-fb101900-2118-11eb-906c-c978a51ceca3.jpg)
0.9.1.2 beta release-111

**Comment by dmplatten** [comment]
This also applies to the Butchery, Carpentry, Farming, Masonry and Smelting Skill Books as well.

**Comment by SlayksWood** [comment]
As far as I understand it should be: This recipe requires 1,000 {Gathering} labor (1,000 cal) (You have this specialty). And it happens for research books if you know specialty for this book.

**Comment by Daniel-Magulado** [comment]
Build: 0.9.3 Staging-1968.

Isn't it suppose to be
This recipe requires 10,000 labor (10,000 cal) and (level of specialty requirement).

Where calorie is the unit of measurement of a resource we gain from eating food and converting it to labor.

For example, 
![image](https://user-images.githubusercontent.com/77248866/113114691-2e755080-923e-11eb-8d2e-5f9cf622b700.png)

I have Campfire Cooking Specialty Level 1.
A recipe called Fish Stew requires Campfire Cooking Speciality Level 3 to cook. So, the error indicates
**You don't have the required level of specialty**

So it should be 
**This recipe requires 20 labor (9 cal) and Campfire Cooking 3.**

Otherwise, I find it confusing in its current setup and very odd to read it as is.
Fish Stew
![image](https://user-images.githubusercontent.com/77248866/113115374-f589ab80-923e-11eb-8b45-3e77730e37eb.png)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-282.

Closing as it is fixed. Tailoring book now requires Gathering labor.
