### ISSUE TITLE
Clicking a bank account in a dropdown will open the bank account window

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19224]
![animx22](https://user-images.githubusercontent.com/3536496/98605761-d0e66480-229a-11eb-8b76-b6a21d3f1f2c.gif)
These are supposed to be no-click. 
When fixing this, figure out why it broke in the first place, and ensure that whatever bug was addressed with that change remains fixed.

**Comment by gzatravkin** [comment]
This was introduced by https://github.com/StrangeLoopGames/Eco/pull/7054 . It was broken because of using IconLink which had always enabled click functionality. 

As a fix added enableClick so it can be toggled. And removed clicks from popupselector: 
![image](https://user-images.githubusercontent.com/53317567/98848633-c958c400-2430-11eb-97cc-4b47239abdc4.png)
