### ISSUE TITLE
[0.9.1.2 beta release-111]User Report: Issue with invisible object stopping avatar

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19222]
User contacted via Discord with forwarded world file not sure what is going on, there is 2 invisible objects that cannot be interacted with smite, are not affected by /level and is blocking movement  and you can place blocks against it in the air.
![Screenshot_28.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/d8eaed4f-a0d5-47ee-9c5e-25ac48b36edc)
The 2 marked positions both have these invisible objects 1 tile up from the ground.
Coordinates
1034,66,90
1037,64,81
Sending download link via pm.

**Comment by mirasrael** [comment]
Investigated issue. It happens because of invisible collider here:
![image](https://user-images.githubusercontent.com/475445/98677992-ee84fe00-236e-11eb-9d2c-0592e8f121d8.png)

and it corresponds to highlighted framed glass:
![image](https://user-images.githubusercontent.com/475445/98678085-14aa9e00-236f-11eb-842c-f308d54e426b.png)

**Comment by mirasrael** [comment]
Looks like a bug in WallCorner collider position:
![image](https://user-images.githubusercontent.com/475445/98678717-090ba700-2370-11eb-9f1a-c961ffa990a1.png)

**Comment by mirasrael** [comment]
@keegan-o assigned issue to you because it requires to fix WallCorner.fbx for FramedGlass (I can't edit it from Unity).

**Comment by keegan-o** [comment]
Fixed in staging and develop branches.
