### ISSUE TITLE
[0.9.1 release-118] Vehicles can stuck in Lumber stockpiles

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19341]
![image](https://user-images.githubusercontent.com/45708377/99242594-802db900-2810-11eb-8586-a6e6dde16671.png)
![image](https://user-images.githubusercontent.com/45708377/99242603-84f26d00-2810-11eb-864c-aea88bd98199.png)
![image](https://user-images.githubusercontent.com/45708377/99242611-86bc3080-2810-11eb-9963-9f78c5192daf.png)

**Comment by MazonDel** [comment]
The collision mesh just needed to be set to a layer that vehicles collide with, in this case to make it similar to other similar objects, I set it to Terrain. The fix is already in the Repo so this issue can be closed.

**Comment by IcedForge** [comment]
Lumber stockpile seems to be working rather well, there is some weirdness going on with the side mirrors causing a bit of unpredictable bumping but its somewhat natural since they cannot break.

![Screenshot_19.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/34e0ff05-7ee0-497b-bac2-984cd38aa1f9)

There is no physical interaction on the same way with the Large Lumber stockpile though?

![Screenshot_20.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f8090795-9207-4f94-b9d4-178ee63b18dc)

**Comment by MazonDel** [comment]
Large Lumber Stockpile fix pushed to SVN.

**Comment by Daniel-Magulado** [comment]
Fixed on 0.9.4 Develop 198
