### ISSUE TITLE
USER ISSUE: Old Growth Redwood Respawns

### ISSUE THREAD

**Issue by Micro753** [StrangeLoopGames/EcoIssues#19363]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
When I cut down an old growth redwood, a new old growth redwood spawned in. When cutting down trees, there are sometimes small saplings that appear. I assume the game incorrectly tried to spawn an old growth redwood sapling, but since those don't exist, it spawned a new full grown old growth redwood instead.

**Expected behavior:**
Only regular redwood saplings appear after cutting down an old growth redwood.

**Actual behavior:**
Instead, it spawned another old growth redwood.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5557136/Player.log)

**Comment by SlayksWood** [comment]
I cutted 15-20 Old Growth Redwoods, and in next tick I find one respawned

**Comment by SlayksWood** [comment]
Still an issue.

**Comment by mirasrael** [comment]
Finally realize why it happens. Because Trees unlike all other plants hasn't fixed position they may have their position updated after felt and if tree falls out of original chunk then instead of original chunk it modifies neighbor chunk and then (because layer value wasn't decreased) it recovers trees in original chunk to layer value.

**Comment by SlayksWood** [comment]
staging-1860 fixed.
