### ISSUE TITLE
USER ISSUE: Stuck way up in the sky. Out of the map

### ISSUE THREAD

**Issue by deedvax** [StrangeLoopGames/EcoIssues#19415]
\
**Version:** 0.9.1.5 beta release-119

**Steps to Reproduce:**
(Singleplayer game) Break a limestone, step on one of the rocks while pressing e. Get send into space faster than a rocket. Even after delogging and relogging my character is still in the void

**Expected behavior:**
Not send me into space, or at least teleport me back on the map after a reboot.

**Actual behavior:**
Sent me into space, leaving the game did not fix the issue.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5578357/Player-prev.log)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5578358/Player.log)

**Comment by Fireztonez** [comment]
Yes, this is a relatively common problem when you walk over rubble or tree logs and the trees move in a certain way, you pick up being propelled more or less far. Sometimes you are actually propelled into space. A few times people have been tossed onto my server into space far enough that they couldn't see anything at all. In general we always end up falling back to earth, but sometimes it can take more than 10 minutes so that we are far away !! I think that we should put a certain limit on the level of the force of probability that an item can do.

In the meantime, when that happens the / unstuck command seems to work on my end to bring me back to earth, but last time it sent me halfway around the world!

Other things I noticed, every time you get propelled into space, when you land on earth, the shadows in the game are completely messed up.

![20201121183454_1](https://user-images.githubusercontent.com/19277301/99890101-e14af780-2c29-11eb-89f1-af5111e252b9.jpg)
![20201121183536_1](https://user-images.githubusercontent.com/19277301/99890102-e14af780-2c29-11eb-9c8f-fc72383fa783.jpg)

**Comment by SlayksWood** [comment]
dup #18805
@deedvax Please ask your administrator to teleport you (/teleport targetto).
shader's issue #14042
