### ISSUE TITLE
[0.9.2.0 beta-staging]Notifications happens even with option disabled

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19420]
With crafting notifications disabled i am still receiving notifications via crafting with issues appearing and when you have 1 machine feeding to another it causes a lot of 1 item added to project missing X items type situations.
(it does not list them in the chat window but every update for quantity it posts in chat and its really frustrating when you do not want it)
![Screenshot_1](https://user-images.githubusercontent.com/24981362/99907879-b327ef00-2cdf-11eb-97ef-978928863af2.jpg)

Would like a second opinion at least from @SlayksWood on his thoughts on this
personally i would think that if i disable a notification option i should no longer see this at all.

**Comment by IcedForge** [comment]
Make sure to check on #29368 and #16748 when verifying and fixing this

**Comment by SlayksWood** [comment]
This issue is fixed:
![image](https://user-images.githubusercontent.com/45708377/110090890-de26e200-7da8-11eb-8072-6a4d24405607.png)
![image](https://user-images.githubusercontent.com/45708377/110090906-e3842c80-7da8-11eb-8159-741f156bd2e8.png)
2 others is fixed in 0.9.4 develop. Need to check them separate.
