### ISSUE TITLE
[0.9.1.6 beta release-122]Vehicle positon not properly saved? Spawns all vehicles at 0,0 on loading

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19458]
Seems like all vehicles reset to 0,0 all the time now with seemingly not saving position properly or reseting.
![Screenshot_46.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ad8058fd-0272-4a33-bedb-403826ba1136)

**Comment by mirasrael** [comment]
Physics changes was reverted in `release`, but still present in staging. Need to find a way how to reproduce it locally and fix.

**Comment by mirasrael** [comment]
I investigated issue with porting vehicles to 0,0,0. It related to two things.
1. Unity resets position and rotation for Rigidbody to zero when game object disabled.
2. Recently introduced hasCollided flag which forces object sync even if Rigidbody is sleeping (it is always sleeping when disabled).
It is quite hard to reproduce and requires at least two players.
- Player A should be controller of vehicle physics. In same time vehicle should collide with something
- Player B should go toward vehicle, but it should be on non loaded chunks. So the vehicle will be disabled by WaitForGround until chunks loaded. It will receive physic updates from Player A though including hasCollided flag.
- Player A eventually become physics controller and start sending updates for the vehicle. But because it still disabled (chunk not yet loaded) it will get zero position from Rigidbody and send it to server. If player will wait until chunk loaded then WaitForGround will activate the vehicle, rigidbody position will be set to transform position and it will sync correct position to server.
- But because we need to reproduce the issue Player A shouldn't wait until chunk loaded, but instead go from the vehicle. So last synced state will be at zero position. If another player become controller at this time then the vehicle position will be forced to zero coordinate and from no reproduce steps complete.
It is much easier to reproduce with rubbles because of another bug. World Object should be disabled when chunk unloaded, but it doesn't work for vehicles. Though works fine for rubbles. So when you go far enough and if chunk unloaded before rubble destroyed then it become disabled, rigidbody reset position and it syncs invalid position to the server. So it is possible to reproduce even solo.

**Comment by mirasrael** [comment]
If fixed this with disabling physic updates for disabled SyncPhysics component.

**Comment by gzatravkin** [comment]
Seems like it still happens (maybe fewer times)
![image](https://user-images.githubusercontent.com/53317567/108161751-78f5a000-70ca-11eb-9b54-a1597872de5f.png)
