### ISSUE TITLE
USER ISSUE: Can't order workbench

### ISSUE THREAD

**Issue by Rinma** [StrangeLoopGames/EcoIssues#19475]
\
**Version:** 0.9.1.7 beta release-126

**Steps to Reproduce:**
1. Start a new game
2. Build a tent
3. Chop a tree and add wood to a storage pile
4. Order Workbench
5. Add Labor points
6. Workbench never finish

**Expected behavior:**
The workbench should be build

**Actual behavior:**
The workbench does not build. Says the wood is missing. Linked storage has 36 (oak) wood inside. On the time bar, there is "NaN". The work order shows "0 sec".

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5598674/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5598675/Player-prev.log)

**Comment by SlayksWood** [comment]
@Rinma Thank you for the report.
Seems you have Craft Resource Multiplier = 0. 
1. Start game and write /serverui, it will open a window with server settings
2. open the Difficulty settings tab and make sure that Craft Resource Multiplier and Craft Time Multiplier are greater than 0:
![image](https://user-images.githubusercontent.com/45708377/100312740-240f2580-2fc4-11eb-9fa9-009b9ab74f81.png)

This problem has been already fixed in 9.2 #18640

**Comment by Rinma** [comment]
I see. This was the case. Don't know why this was set to 0, the only setting I changed by myself was the meteor time and added me to the admin section. 
Anyway, now I can create a workbench.
