### ISSUE TITLE
[0.9.1.8 beta release-130] `Large Corrugated Steel Doors` broken since latest patch

### ISSUE THREAD

**Issue by F0x06** [StrangeLoopGames/EcoIssues#19534]
Hi everyone, since the latest patch `Large Corrugated Steel Doors` are broken, all the orther ones seems working fine. I asked on discord and i'm not the only one with the issue.

Here are the issues:
   - There is no more collisions with the door, you just pass through it (noclip)
   - Placement is nearly impossible, and if you manage to place one, sometimes it desapears instantly
   - If you look at the ground the door disappears (visually), seems like a render bounds issue.

Video of the issue: https://youtu.be/2J3sDDGhjSo

Thanks in advance.

**Comment by memnarr** [comment]
Our server is also experiencing this issue.

**Comment by Thibault-Brocheton** [comment]
version is 0.9.1.8    not 7 :)

**Comment by LsHallo** [comment]
Also experiencing this issue.

**Comment by mirasrael** [comment]
Investigated the issue. It happened because of Unity upgrade from 2019.4.12 to 2019.4.15. It has broken pefab in 4.15

2019.4.12
![image](https://user-images.githubusercontent.com/475445/100874282-64cfd880-34b5-11eb-99a7-c69e383f8135.png)

2019.4.15
![image](https://user-images.githubusercontent.com/475445/100876111-fdffee80-34b7-11eb-87a0-bd26bb307d19.png)

**Comment by mirasrael** [comment]
@keegan-o can you fix (or assign someone) to fix the prefab for 2019.4.15 in staging?

**Comment by SlayksWood** [comment]
fixed in 0.9.2
