### ISSUE TITLE
Database corruption on officialplaytest cloud world

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19542]
```
[12:25:05] System.IndexOutOfRangeException: Index was outside the bounds of the array.
[12:25:10] LiteDB.LiteException: Invalid Index on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 1511. ShareCounter: 1.
```

Server seems to have a broken database, in this case leading to server downtime and inaccessability by players when it's online. Find cause and why the corruption causes the server to be unstable while this is not the case for normal servers.

**Comment by mirasrael** [comment]
I loaded CW locally and tried to login. It failed with LiteDB error when tried to insert a record (for played time).
So it seems backup I used to restore Lite DB also corrupted. I fully removed DB and it should work now I guess.
Problem it doesn't fail on startup. So we can't immediately identify this issue, but instead of first (or even non first) operation with DB.
As workaround I may suggest to catch all DB errors and if we identify some of errors as corrupted DB (there actually just one of two such exceptions we usually have) then we can try to repair DB in runtime from most recent backup.
It should then remember which DB it used for recovery and if it also corrupted then it should start looking for good backup from it.
If no good DB backup found then it should re-create DB.

**Comment by j3fffff** [comment]
@mirasrael would your auto db fix plan be running from cw api or game server?

**Comment by mirasrael** [comment]
From game server.

**Comment by j3fffff** [comment]
Created task for db auto repair **https://github.com/StrangeLoopGames/EcoIssues/issues/19823**
