### ISSUE TITLE
Test hosting local game and inviting people via steam

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#19598]
Lots of chatter on the channels that this isn't working anymore at all

(Don't have forwarded ports, obviously)

**Comment by IcedForge** [comment]
If you invite / click join on a friend/user in your list and you do not have the same client / server version it will not connect.
It will also not inform you of this and will either just launch the title screen and nothing else or it will briefly try to connect only to time out with no error.

If you try to connect with ID or directly in the game list it will give you a big notification as to why this is not possible.
this should happen in every instance where a client connection is rejected due to version mismatch
![Screenshot_34](https://user-images.githubusercontent.com/24981362/101148651-2f92ca00-361e-11eb-8194-3d0885ab0dea.jpg)



Second issue:
If you invite players to a server via steam friends, and you have not hosted the server it seems like steam can forget to actually send the server address to the client.
[Player5.log](https://github.com/StrangeLoopGames/EcoIssues/files/5641850/Player5.log)
`[12:37:26.294] Disconnected with error: The requested server was not found. It either doesn't exist, or is not registered on the master server.`

**Comment by johnkslg** [comment]
Raising this to critical, our review score is getting hit with people having this problem
![image](https://user-images.githubusercontent.com/3536496/105135821-7b51e380-5aa5-11eb-9612-30285bbeb455.png)
![image](https://user-images.githubusercontent.com/3536496/105135835-84db4b80-5aa5-11eb-87a2-cb03c31d30ac.png)
