### ISSUE TITLE
[0.9.2 staging-1863] Incorrect district name when adding a new district

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19602]
- [ ] 1. I guess 'Add New Entry' previously was 'Add New District'

- [x] 2. When I press 'Add new Entry' it should add new district with name District (N+1), but it add district with name 'Map Entry':
![image](https://user-images.githubusercontent.com/45708377/101141792-d6c72f80-3625-11eb-8040-394a71fe28df.png)

Seems I can create a lot of districts with the same name, but they will renamed after adding:
![image](https://user-images.githubusercontent.com/45708377/101142443-a59b2f00-3626-11eb-92f0-fe3613ff4acc.png)

If this is all intended behavior then rename 'District 1' and fix 'Map Entry N+1'

**Comment by Mattprass** [comment]
I think this is all intended behavior. Per a comment I found:
`//Client will create new elements without communicaction with server, so their id's can't match new districts
  //This dictionary will link client ids to real districts, so after creating districts entry, we can't link map from "client" id to real district id` 
The client makes the name the default name "Map Entry" because it is not checking against server portion until you hit the "Submit" button to edit. I don't think the "District" should be renamed either as it automatically adds the district you're editing to the list, and that just so happens to be the name of the district.

**Comment by gzatravkin** [comment]
It's difficult now to make correct names at the moment of creation of map entries.

But it should be possible instead to pass default name and Add new text to MapEditRequest (with defaults as Map Entry, Add New Entry, but overridden for districts as District, Add New District)

**Comment by Mattprass** [comment]
The default is already set to "Map Entry" when creating it, no? That is part of the original issue. 

I'm not really understanding the issue here. If I were to add a count or something on the client side (because as per the comment of the code I mentioned above, the user would edit it on the client before submitting it to the server), say it would become Map Entry 1, Map Entry 2, etc. It would then be renamed anyway when you hit submit button to "May Entry N" because of the server logic in place that renames them to something not already in the list, which is more confusing to the player in my opinion.
Here's an example:
Before Submit:
![ss](https://user-images.githubusercontent.com/31013483/101791699-d6211400-3ad1-11eb-8c22-e16c9424e5fe.png)
After Submite:
![ss](https://user-images.githubusercontent.com/31013483/101791843-ffda3b00-3ad1-11eb-828c-4bb61847ca08.png)

Not sure why it got changed to 13, 14, and 15 exactly but I hope I demonstrated my point.

**Comment by gzatravkin** [comment]
Yes, it's true that client can't know names name. 
How about add a message (OkBox) after saving map, which will say "District MapEntry was renamed to MapEntry 1 to guarantee unique name" or simmiliar?

**Comment by johnkslg** [comment]
Some notes:
- It gets renamed because district names must be unique.
- When youre creating new districts, give it a 'best guess' name. IE, the client can look at the Registrar containing Districts (GlobalData.Registrar<DistrictView>) and create a new district named 'District <min number that doesnt result in a name duplicate'
- It will still be possible that the name will be unavailable when the user does submit, but rare. In this case can just rename it.

**Comment by SlayksWood** [comment]
Awesome! but need to fix one bug:

- [ ] 1. Second district duplicate first district name when creating a new district map. Step to reproduce:
- start to create a new district map:
![image](https://user-images.githubusercontent.com/45708377/102592019-eebda980-4123-11eb-94ba-dedd244a527f.png)
- press Add new Entry:
![image](https://user-images.githubusercontent.com/45708377/102592047-f67d4e00-4123-11eb-8922-25fcef4b4648.png)
- should be district 6. 
- other district names are right:
![image](https://user-images.githubusercontent.com/45708377/102592087-05fc9700-4124-11eb-91a5-dd24c9acdf5c.png)

- [ ] 2. Should we rename the button 'Add new entry' to 'Add new District'? it will be more clear.

**Comment by Mattprass** [comment]
1. I will try and improve the naming of new districts as they are added, but due to how the client and server communicate with each other in this instance, it won't be perfect 100% of the time. It may be out of order or a different number than what came before it. 

2. This UI can be potentially used with other kinds of maps of the future, however I can try to change it algorithmically.
