### ISSUE TITLE
Jenkings failing lots of builds

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19643]
![image](https://user-images.githubusercontent.com/3536496/101400561-f0ff4880-3885-11eb-9912-55a552dacc3a.png)
It looks like it cancelled it because a new commit came in, but then never restarted it. 

It also added a 'tests failed' when it doesnt appear to have run any tests.

**Comment by redwyre** [comment]
As stated, there are three possible causes:
* Someone aborted the build
* The build timed out for some reason
* The build was cancelled by another commit

Since there wasn't another build, it's going to be one of the first two. I cannot tell you which case happened because of limitations in Jenkins.

In either case, first check the failed build log by clicking the red X and read the log file.
* If it timed out mention it to me, or start another build if unavailable.
* If it was aborted by someone check #eco-code/#eco-devops, if nothing ask them why, or start another build if they are unavailable.
* If unable to figure out the reason, ping me.

I've added this to https://github.com/StrangeLoopGames/Eco/wiki/Pull-Request-Testing-in-Eco

**Never merge a build if you don't know why it failed** this could break the main build leaving many people unable to work and all subsequent PRs will fail until it's fixed.

This build has already been discarded so I can't say for sure what happened in this case.
