### ISSUE TITLE
Economy Viewer Needs Better Icons for Small Display Size in UI

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19644]
![image](https://user-images.githubusercontent.com/3536496/101402486-aaf7b400-3888-11eb-8348-aaf4058d0c31.png)
We have an art process problem, icons are being created by the artist without knowledge or regard to how theyre going to be used.  As a result, we get icons that are non-matching styles, too much details displayed for their size, etc.  

Here: Rent, trade, and work party are too small to read, contract board icon is not an orthographic view.

Fix these icons but also fix the process that resulted in the problem.

**Comment by keegan-o** [comment]
Code/UI that is being developed needs to make clear tasks for artists, that explains the context for new assets needed. That's all. All the icons used in this UI except for the Rent icon were not made specifically for this UI. Using old assets in new contexts means they might not look as good. If we need to make new icons for this new context where they appear at half-size, we can do that.

**Comment by keegan-o** [comment]
Using placeholders and requesting art once a feature is ready to be checked in-game would be the best way to ensure this doesn't happen again, also. That way, when an artist gets a task for a UI asset, they can load up the game, see the placeholder, see it's context in-game, then make art for it, then check it. Placeholders could be any kind of thing, preferably something that obviously needs to be replaced like an mspaint scribble or red target or white square.

**Comment by WeaselDog** [comment]
We have had a good discussion on this. We can convert this into an issue for fixing icons in Economy Viewer

**Comment by RobertMangano** [comment]
what size are these icons supposed to be if we have our regular icons at 64x64px. are we halving that and making them 32x32?

**Comment by MilenkoTunjic** [comment]
We learn as we go. None of the icons were ever designed to be used smaller than 64x 64, except some recent examples. Using them smaller than that obviously results in undesirable outcomes.
So I suggest that we set up the process, define the icon size and commit to those sizes down the line.
I have seen icons being used randomly, in and for things they are not designed for. A lot. Having one design fits all is possible, but we would have to strip it down to bare basics and we did not do that in the process so far (simply because that was not the direction we were going in so far).
As it is, style wise, you can not expect them to work at any random size that gets thrown in. I always ask for the art stuff to be used in 1:1 pixel ratio, otherwise you get anti aliasing, blur and unreadable stuff.
Even if it means doing smaller icon variants, or redesigning them to work with different resolutions.
However, squishing, stretching and randomly scaling pixel based art will always give you what you do not want.
They can be any size you want, but you need to communicate that, and we both have to commit to producing them, but also USING THEM at that size.
Squishing icon box just so it can fit in randomly sized tab will never give you what you want, no matter what we do on our end.
So please.
Define the sizes you need them at, let us know which icons you need, but make sure you also stick to those sizes, and it will all be good.

**Comment by MilenkoTunjic** [comment]
Although, those ancient perspective icons that someone did ages ago do look bad, and have always been on the books to be replaced, but no one had the time to do it yet
It will be done though.

**Comment by StallEF** [comment]
@MilenkoTunjic  since the 9th version, many large signs have been added to the game, which are often used as showcases and the use of 64x icons looks very bad, so the problem of large icons is also relevant
https://user-images.githubusercontent.com/26339332/104806371-056d2400-57e8-11eb-9426-9092127fba4e.png

**Comment by MilenkoTunjic** [comment]
That is what I was saying. 64x64 icon is intended to be used at that resolution, any other uses would produce artefacts. so we should have defined resolutions and produce icons at those resolutions.
