### ISSUE TITLE
[0.9.1.8 beta release-130]Remove from office list is not user friendly

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#19719]
There is 2 issues at the moment i can tell with this UI and we have 

1. - [ ]  When you select a title to remove someone from office it should not list all titles; only those that have an actual user or title owning them.

Currently it lists ALL titles available regardless if they have a user or not in them.
![Screenshot_36.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/2b2a2468-5b89-4397-9f6f-f96104fc36f6)

2. - [ ]  When you select who to remove from this elected title, it should only show the actual player occupying this not fetch the entire complete player list.

![Screenshot_37.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/e10b8433-6281-4490-880c-6b8c614626ae)

3. - [ ] I would also consider flipping them around so you select title first, then the appointed individual to remove.

These are all fairly nested together so i left them as a single issue as they should be able to be fixed in one go since its the same ui window.

**Comment by SlayksWood** [comment]
Still an issue. I can select any Titles:
![image](https://user-images.githubusercontent.com/45708377/107358072-fd04c200-6ae3-11eb-9c03-d412c2525f4b.png)
And after your changes I have another UI flaws (close to point 3 of the original problem):
- Have Test User 7 as Title 1 occupant
- Have Test User 9 as Title 2 occupant
- Start to select Test User 9 in Players, I can select only Title 2 now:
![image](https://user-images.githubusercontent.com/45708377/107358483-7e5c5480-6ae4-11eb-840c-b68efe41b5f2.png)
- SO I need to change first player and then change I can select title:
![image](https://user-images.githubusercontent.com/45708377/107358556-9633d880-6ae4-11eb-819b-eb136d8cf4ad.png)

**Comment by Mattprass** [comment]
Not sure what the issue here is. If anything, those UI changes make this UI more versatile, in case the player wants to filter on User OR Title, they can. Why would it make sense for them to choose Title 1 when they filter on a user that does not have that title?

Also, maybe helpful to mention that the selection of titles was based on the initial requirements of this ticket:
"When you select a title to remove someone from office it should not list all titles; only those that have an actual user or title owning them"
which it does. Filtering on whether anyone can vote them out of office is different but makes sense and can make that change too.

**Comment by gzatravkin** [comment]
@Mattprass there are issue with first screenshot for sure. It shouldn't appear Title 1 since nobody can remove people from it by definitions. 

Can you fix this one? About second one, @SlayksWood any ideas? It was done this way on propose and makes sense for me. Otherwise what should happen when you selected user and after that select some title without this user? It should be impossible as I see it.

**Comment by IcedForge** [comment]
In my mind, they would filter depending on entry

Field 1 - I select title and it gives me a list of users in that title.
Field 2 - I select user and it gives me a list of titles this user holds.

Which would allow both as the original problem is i need to manually find both and i also needs to know full details on both parts to be able to do anything, this is one of those very small but big QoL improvements especially if you have titles with a lot of users.

**Comment by gzatravkin** [comment]
This way is supposed to work now if I understand you right. @Mattprass can you confirm that? And can you attach a video? To avoid confusion.

**Comment by Mattprass** [comment]
Yes, @IcedForge is correct, that is how it is now. Here's some videos on it working:

https://gyazo.com/1451a88f37f4877cd33225df301400f2
https://gyazo.com/4986ca7227ee5f3bc3b1d9a479b2b084

Also yes I can fix that slight error in there as well demonstrated from that first screenshot @gzatravkin
