### ISSUE TITLE
[0.9.1.8] When new players spawn they get stuck

### ISSUE THREAD

**Issue by SweGer96** [StrangeLoopGames/EcoIssues#19721]
Hey, i had the issue that when players spawn simultaneously that they got stuck on spot, but even when they spawn alone they get stuck on spot, I tried teleporting them, unstuck etc and it didn't work, the only thing that worked was that i gave them admin, let them fly away, and revoke admin, but that only resolves the issue until they log on again and are stuck again.  

At first i thought it was the mods, but even in vanilla it happend. 
If important, these are the mods im using:
https://eco.mod.io/industrial-elevator
https://eco.mod.io/wooden-bracers
https://eco.mod.io/shipping-container
https://eco.mod.io/beekeeping-mod

The game.eco + game.db file size seemed to be to big so i made a google drive folder with it instead:
https://drive.google.com/drive/folders/1mio79yDcVq3ghiROj1JpG5K4P5oEKNSL?usp=sharing

**Comment by SlayksWood** [comment]
@SweGer96 Thank you for the report and sorry for the waiting.
We had this issue after releasing 0.9.0 but it should be fixed in 0.9.1 #18639. I tried to reproduce your problem with your save file but I didn't have such problem. So we need more detail:
1. What language is used on the server?
2. What language are used by people who connect to your server.
3. Can someone of them provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
4. Do players have any problem when connect to another server.
5. What version do you use?
