### ISSUE TITLE
Jenkins failing tests, not giving details, not re-running on 'run tests' comments

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19748]
https://github.com/StrangeLoopGames/Eco/pull/7385

**Comment by redwyre** [comment]
There was an issue with the build trying to analyse the wrong log file, which is now fixed in staging.
Jenkins failing the build was correct, it has broken scripts. This is easy enough to determine from the jenkins logs.
Typing "run tests" will queue a build, if jenkins has a long queue it will take a while. If it's not fast enough we need another or better build machine.
