### ISSUE TITLE
USER ISSUE: Poor Optimization on high end pc

### ISSUE THREAD

**Issue by traycej231** [StrangeLoopGames/EcoIssues#19800]
\
**Version:** 0.9.1.8 beta release-130

**Steps to Reproduce:**
Play	Game

**Expected behavior:**
Avg to High fps in game	

**Actual behavior:**
Very low unplayable fps in game

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed 

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@traycej231 Thank you for the report. We known about this problem and try to solve it. Can you provide log files? Your FPS drop may be caused by exceptions.
Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
and please provide your PC specification (include Operating System).

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information.
We continue to improve our optimization step by step.
