### ISSUE TITLE
Investigate locking in rubble collection: potential deadlock or bad use of locks

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#19808]
From comment here: https://github.com/StrangeLoopGames/Eco/pull/7370/files

![image](https://user-images.githubusercontent.com/3536496/102734372-8540c500-42f4-11eb-8246-4794a4fe5ed8.png)
I know this isnt your code, but I'm suspicious of this lock.

It could lock for quite a lot of code: the creation of the game action pack, its execution throughout the game action manager, and any subsequent actions.

It's also a very broad lock, other things could be locking on the rubble object outside of this function resulting in problems.

Furthermore, I'm not sure the lock is actually effective. Say another thread hits this lock and pauses, waiting for the other thread. The other thread finishes, which destroyed the rubble. Now this thread proceeds, and calls 'destroy' on that rubble again anyway.

Filing a bug for getting thoughts on this, @mirasrael would like to get your input, and then can pass the fix to another dev.

**Comment by mirasrael** [comment]
Actually @johnkslg you added this lock in this commit https://github.com/StrangeLoopGames/Eco/commit/d36aa729e070499c0bece97c1d494427c3e662e3
So usually I would like to ask you what was a motivation :) But for me this lock seems useless, because as you said it doesn't prevent anything. It will just delay operation. It seems it is only lock usage with rubble and then no check for rubble state so it will perform all operations anyway.
As far as I understand it was done to prevent collecting same rubble by multiple users. In this case you can use one of two approaches:
1. Keep this lock, but add check after lock given to ensure this rubble not collected:
```csharp
Monitor.Enter(rubble);
if (rubble.Destroyed) {
    Monitor.Exit(rubble);
    continue;
}
```
2. Or add atomic flag to Rubble which can be set with Interlocked.CompareExchange(). You need ensure to revert this flag if you didn't collect rubble though. This way is preferred, because it is lock free.
