### ISSUE TITLE
[0.9.2 staging-1881] UI glitch with hidding window when open it during disconnect.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#19813]
It is quite difficult to reproduce and record high-quality video (because one way to make my server laggy to use all CPU or RAM, but I can't record video if I don't have free resources). This can very easily happen on a live server. Servers that are online for a long time often have small disconnects. But it can be easy reproduce in debug. So Step to reproduce:
- place workbench
- start to debug to have disconnect icon:
![image](https://user-images.githubusercontent.com/45708377/102774149-7bbe6800-439b-11eb-95c3-7da8f6edd1fb.png)
- try to open workbench (press 'E' 3-5 times):
- you can't open it because you're disconnected now.
- move away from the table (outside the radius on which this table can be opened):
![image](https://user-images.githubusercontent.com/45708377/102774232-a90b1600-439b-11eb-8895-5a1b0fb7d04f.png)
- exit debug. Window will close very slow:
https://drive.google.com/file/d/1R5N_8pgxKpPuPrI7cbCXCn6-ibLppR2o/view?usp=sharing
- and I can't do anything with this window. Just wait until it will be hidden.

**Comment by gabrielgindridev** [comment]
Followed the steps. But can't reproduce in current develop. Sending to QA again.

**Comment by Daniel-Magulado** [comment]
## Findings
Due to the changes done with the UI where you can't spam them anymore to open multiple UIs and /civics ticknow doesn't do the same behavior as shown on the [video](https://drive.google.com/file/d/1R5N_8pgxKpPuPrI7cbCXCn6-ibLppR2o/view?usp=sharing), this is almost impossible to reproduce.

However, the same behavior of the UI can still be reproduced and observed by spamming interaction with multiple tables while disconnected. Using the build **0.9.4. Develop-261**, I've made a recorded video that shows the same behavior of the UI, still slowly moving down.

### Reproduction Steps
1. Connect to a server that requires internet or LAN Wi-Fi.
2. In-game, go near a crafting table.
3. Turn your PC's internet connection off. Either disable your internet driver if connected with an RJ45 ethernet cable or turn on AirPlane mode if via Wi-Fi.
4. Go back to the game and quickly Interact with a crafting table. To better show the issue, interact with multiple crafting tables.
5. After literally spamming E on step 4, move away from the crafting tables. Make sure you're at a distance that prevents interaction and force closes any UI.
6. Turn your Internet back on or turn AirPlane mode off.
7. Observe.

### Actual Result
https://user-images.githubusercontent.com/77248866/115755936-77996a00-a3d0-11eb-82e4-3612ac0d1d44.mp4

As you can see, the UI's are still exhibiting the same behavior of slowly tucking themselves down the screen.

### Recommendation
I believe that this might be a no-fix issue but I can always be wrong. It's just that, players are highly unlikely to do such activities in the game. To prevent this, I recommend terminating the clients' connection to the server once the game detects no internet, unstable internet, or lousy Wi-Fi connection. This is also highly unlikely to occur on Solo mode as it requires disconnection from the server state to reproduce. Furthermore, if the game immediately terminates connection from the server instead of trying to reconnect itself, a lot of exploit issues that require unstable or disconnected to the server as part of repro step can be solved such as #21215 and #17727 where part of the repro steps is having the disconnected from the server state.

**Comment by gabrielgindridev** [comment]
Thanks @Daniel-Magulado. Will try to fix now 😄

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Develop-280.

Unable to reproduce anymore. The game doesn't exhibit the same behavior as shown in the video after reproduction steps. 
The first table you interact with persist and stays open. Even after losing connection, the UI persists and the glitch issue doesn't happen anymore.

Thank you for fixing it. Closing.
