### ISSUE TITLE
[v0.9.1.9-beta] Exception: InvalidOperationException Message:Host creation call failed

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#19849]
Change IP address in the configs from **Any** to the **current IP address of the server**.|
Receive "_Exception: InvalidOperationException Message:Host creation call failed_" when starting the Eco server.

[LogsAndConfigs.zip](https://github.com/StrangeLoopGames/EcoIssues/files/5741066/LogsAndConfigs.zip)

Let me know if you need more info!

**Comment by SlayksWood** [comment]
@fillion07 Thank you for the report. You should use local ip address here instead of external one.
The notification will be improved in 0.9.2 
![image](https://user-images.githubusercontent.com/45708377/104308494-d1d98380-54e1-11eb-9a4e-580ce24209b7.png)
But I guess we still can improve description, its behavior( maybe to prevent server crash) or at least make non-latin readable. So I create a new issues for that.
