### ISSUE TITLE
Finishing a contract crashes the game

### ISSUE THREAD

**Issue by LovelySanta** [StrangeLoopGames/EcoIssues#19896]
Make a contract, inside the contract you grant permission to a steam truck. During the execution, the steam truck fell into the ocean, so the client of the contract picked up the steam truck and placed it back on the road, manually granting permission to the contractor. When trying to finish the contract, the game hard crashes the server.

The current state of the contract looks like this:
![image](https://user-images.githubusercontent.com/26593477/103465664-4c660e80-4d3e-11eb-8039-3854d37fe2b6.png)

neither the client or the contractor is able to finish the contract.

**Comment by salix-d** [comment]
Related issue : https://github.com/StrangeLoopGames/EcoSuggestions/issues/1348

Please allow us to delete these invalid contracts somehow. For now they'll just stay in our work menu forever.

**Comment by SlayksWood** [comment]
@LovelySanta @salix-d Thank you for the report. To delete this invalid contract you can try to use admin command.
/objects remove contract, 1. Where '1' is contract ID: 
![image](https://user-images.githubusercontent.com/45708377/104177354-abe8ac00-5419-11eb-9876-887c2c74b1f1.png)
But previosly make a backup (just in case).

**Comment by SlayksWood** [comment]
Seems contract was fixed in 0.9.2. 
- Player 1 create a contract like this one:
![image](https://user-images.githubusercontent.com/45708377/104178761-eb17fc80-541b-11eb-826a-5302da227520.png)
- another player take contract and try to pick up Truck. This part is fixed:
![image](https://user-images.githubusercontent.com/45708377/104178787-f66b2800-541b-11eb-86c9-bf0208be8ae3.png)
But I can reproduce crash with another way with another contract (similar to this behavior), but I will create a separate issue for that.
