### ISSUE TITLE
9.1.9 Usernames are affected by bloom - Accessibility issue

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#19992]
Usernames are affected by bloom which can cauuse some visibility/accessibility issues for those with eyesight issues

![image](https://user-images.githubusercontent.com/61889138/104374656-154fe400-551a-11eb-9929-bbcbd1197a2f.png)

**Comment by Jason-Skillman** [comment]
After investigation I have narrowed down that this issue has to do with the post-processing volume. It seems that the bloom is affecting any bright white material/surface (Regardless of shader/type). 

With post-processing running after rendering, there is no way to overlay the nametag after post-processing. Using Unity's default post-processing stack there is no way to easly fix this issue (Without a large modification to the rendering pipeline). However, we could look into using a different post-processing solution instead of the Unity `Post-processing v2 stack`.

This is accually a popular problem on the Unity fourms with no current solution. https://answers.unity.com/questions/1753920/post-processing-bloom-effect-affects-all-light-col.html

**Comment by Jason-Skillman** [comment]
Another possible solution is to render the nametag on a different camera without post-processing, however since the main camera is using a render texture this solution would not work. The render texture and the raw image UI would have to be disabled for the multi-camera setup to work.

**Comment by Jason-Skillman** [comment]
### Solution
Found another solution that where I switched out the nametag material with the TMP SDF Overlay shader which removed the bloom affect from the player's name.

Before:
<img width="950" alt="bloom_before" src="https://user-images.githubusercontent.com/35405997/120032880-d900ba00-bfc8-11eb-9bd5-535971b4c9e3.png">

After:
<img width="955" alt="bloom_after" src="https://user-images.githubusercontent.com/35405997/120032910-e158f500-bfc8-11eb-82df-c49d13ecc18c.png">
<img width="711" alt="day" src="https://user-images.githubusercontent.com/35405997/120032931-e9b13000-bfc8-11eb-9ade-3723e6e5e595.png">

**Comment by WeaselDog** [comment]
Fixed in SVN

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2004

Closing as fixed.
