### ISSUE TITLE
[0.9.2 staging-1898] Migrated Server crashes after second start

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20015]
@IcedForge made server to test this issue #19903. I start it first time, the server was started and migrated right. But when I restart it rhe server always crashes.
https://drive.google.com/file/d/1nA8duiYu9Oyh0UiAb4iF-zwbriWYfIV-/view?usp=sharing

Step to reproduce:
- start server, you may not even connect to it.
- restart server:
```
--BEGIN DUMP--
Dump Time
01/14/2021 14:47:01

Exception
Exception: ArgumentException
Message:An item with the same key has already been added. Key: WaterweedSpecies
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: WaterweedSpecies
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Eco.Shared.Utils.BidirectionalMap`2.Add(TKey key, TVal val)
   at Eco.Stats.ShortNameMap.<Init>b__8_0(ShortNameEntry x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Eco.Stats.ShortNameMap.Init(List`1 collection)
   at Eco.Stats.StatInfoManager.Initialize(List`1 entries)
   at Eco.Stats.Stats.Initialize(TimedTask timer)
   at Eco.Server.PluginManager.InitializePlugins()
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)

--END DUMP--
```
[ServerCrash ArgumentException 01144701.txt](https://github.com/StrangeLoopGames/EcoIssues/files/5814218/ServerCrash.ArgumentException.01144701.txt)

**Comment by mirasrael** [comment]
Investigated this issue together with @SlayksWood 
It actually very strange issue. I'm not able to reproduce it on my PC (Windows 20H2), but Kirill get it every time (windows 1909).
It related to issue with LiteDB. When we checked "index" table then realized it doesn't return records for `SELECT $ FROM index where _id = 'wa'` and `SELECT $ FROM index where _id = 'vo'` on Kirill PC, but on my PC it successfully returns records by same queries for exactly same .db file. Though you can see both records if run `SELECT $ FROM index`.

It isn't related to migration. We tested this with 9.1 and it has exactly same error.

So following scenario happens:
1. When server load first time it loads records from DB and merges them with new records. Then it makes Upsert for all ShortNameEntry records, but because it can't find some entries (Vote and WaterweedSpecies) by primary key it creates new records for them.
2. Next time when you start the server it has +2 duplicate records in DB which causes server crash when used for mapping creation.

When Kirill generated new world locally then it didn't create any such broken records. Only known source of broken works is @IcedForge :) It already created two broken worlds. I initially thought it was because of thread safety issues, but now it seems it is something related to Jens environment. Most interesting it happens for Jens and for Kirill, but doesn't happen for me.

**Comment by SlayksWood** [comment]
I updated my Windows to 20H2 and this issue was fixed! Anna  still have 1909 version too and have this issue.

**Comment by beastyn** [comment]
I was building a server from VS

**Comment by mirasrael** [comment]
It doesn't really matter how you run server. This issue happens in LiteDB.Studio and seems related to Windows version.

**Comment by mirasrael** [comment]
I reported this issue to LiteDB: https://github.com/mbdavid/LiteDB/issues/1922

**Comment by mirasrael** [comment]
We can update Eco Server hosting requirements to Windows 10 2020H2 to avoid this error, but it seems only happen when save copied from one PC to another and doesn't happen on same PC.

**Comment by mirasrael** [comment]
As workaround you can open your db file and `DROP COLLECTION index` with https://github.com/mbdavid/LiteDB.Studio/releases

**Comment by maxkhl** [comment]
Hey there I've analyzed the problem on my server. The problem occurs when using this tool -> https://eco.mod.io/eco-server-extra-confuguration
Once I applied mirasrael DROP COLLECTION index it worked for me but the mods from that tool didnt work anymore. When I re-applied the tool I got the exact same error as before.
I was able to fix it by doing mirasraels workaround but instead of DROP COLLECTION I used `DELETE index WHERE _id = "VO"`  Then, without starting the server, I applied the tool to my savegame and that finally solved it and the mod from the tool is still working.

**Comment by mirasrael** [comment]
@maxkhl did you try to restart server after this?

**Comment by maxkhl** [comment]
@mirasrael It did an automatic restart this morning. Everything is still fine so far.

**Comment by WeaselDog** [comment]
Let us know if you experience this issue again
