### ISSUE TITLE
[0.9.2 Staging 1898] Server crash when "Connecting To" process gets halted then continued again.

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20024]
Build: 0.9.2 Staging-1898

Issue: The game server crashes when halted during initial setup/load then continued again afterward.

Repro:
1. Create a new game.
2. Join any world or host a private world.
3. When the game tries to connect to the server, press ESC or halt the process.
4. Then proceed to join again once more.

Result:
Unable to connect to the server.

Note: The same issue can be reproduced via creating a new game then hosting a private world. Stop the initial setup of the server and then click **Your World**. Select the newly created server and load it.

Screenshot 1
![Server Crash.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/16dabc76-5046-4239-8ad5-1762a8a93ed9)
Screenshot 2
![Server Crash 2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/231f6992-04cc-4e0a-9c37-08e46a5539ed)

Video Repro:
https://images.zenhubusercontent.com/47210472/8877591a-b6db-4cf1-ab17-da1fe4e31e37/server_crash.mp4

Crash Log:
[https://app.zenhub.com/files/47210472/95de5714-c0d3-45f6-bf56-1eb86ba3b1a0/download](https://app.zenhub.com/files/47210472/95de5714-c0d3-45f6-bf56-1eb86ba3b1a0/download)

**Comment by IcedForge** [comment]
Looks like its not properly shutting down the DB so its in use at the time of starting up the server again

System.IO.IOException: The process cannot access the file 'E:\SteamLibrary\steamapps\common\Eco\Eco_Data\Server\Storage\sda.db' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at LiteDB.Engine.LiteEngine.Upgrade(String filename, String password, Collation collation)
   at LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   at Eco.Stats.LiteDbService..ctor(String filename)
   at Eco.Stats.Stats..ctor()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.)
Exception has been thrown by the target of an invocation.

**Comment by IcedForge** [comment]
Bumping priority on it, but i believe it might be possible to push to a hotfix possibly?

**Comment by mirasrael** [comment]
Added running server detection and improved error message. I created new low priority issue in case if we need to improve UI for waiting for running server to shutdown: https://github.com/StrangeLoopGames/EcoIssues/issues/20195

**Comment by Daniel-Magulado** [comment]
Build:
- 0.9.3 Develop - 175
- 0.9.2.3 Release - 154

Issue: Still happening.

![crash](https://user-images.githubusercontent.com/77248866/106795955-b3f0e000-6695-11eb-9f58-15e9d90542e5.jpg)

Feedback: I think the best fix for this one is to introduce a UI where it prevents the player from starting the server immediately and has a display message of **"Server Interrupted: Please wait."** and the UI closes automatically once the server shuts down properly and saved the files.

**Comment by mirasrael** [comment]
@Daniel-Magulado can you check in today build (v0.9.3.0-beta-develop-176)?
The fix was in staging and only merged to develop yesterday and it wasn't merged to release.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.3 Develop-176

A new window message appears when reproducing the issue.
![dd](https://user-images.githubusercontent.com/77248866/106943967-03e8a900-6761-11eb-9dd9-59bbb9e48d82.jpg)

Resolution: Closing
