### ISSUE TITLE
Tomato bush is invisible

### ISSUE THREAD

**Issue by Staric1982** [StrangeLoopGames/EcoIssues#20040]
MacBook Pro 2019, Catalina.

<img width="1680" alt="Screenshot 2021-01-16 at 17 33 29" src="https://user-images.githubusercontent.com/3616310/104815145-e42a2900-5823-11eb-9890-b754f0a71270.png">

**Comment by PixlRainbow** [comment]
Not sure if it is related, but I have a similar issue where not only the tomato plants but also many other plants from the rainforest are completely invisible; no models, no shadows and no glowing highlights.
They are otherwise interactable with collision and with harvesting and soil sampler.

Ubuntu 18.04, Nvidia 1050Ti, first party nvidia driver.

**Comment by Daniel-Magulado** [comment]
Adding related tickets with disappearing or invisible.
#20502
#20383
#20351
#20549
#20601

**Comment by PixlRainbow** [comment]
Update: on further testing, I found that the plants are visible at a distance, vanish up close, with behaviour similar to redwood and ceiba leaves in #18416 
> from a distance, they appear to ...... [be] intact with but blurry textures/models, but as I approach they fade out entirely without loading in the high quality textures/models.
