### ISSUE TITLE
USER ISSUE: Can't make workbench

### ISSUE THREAD

**Issue by Praedon** [StrangeLoopGames/EcoIssues#20051]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
1. place your tent
2. put wood in storage
3. order workbench
4. press work to do labor
5. It keeps saying nan% for resources and stays at 0s remaining	

**Expected behavior:**
Create a workbench

**Actual behavior:**
Stays forever creating it

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Praedon** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5827019/Player.log)

**Comment by jk-fwh** [comment]
i have exactly the same issue. Can not play the game at the moment with this issue

**Comment by SlayksWood** [comment]
@Praedon @jk-fwh Thank you for the report. It's known issue and will be fixed with 0.9.2 #18640. But you can fix it. So seems you have Craft time multiplier and Craft resource multiplier = 0. You need just to change it either server UI (use '/serverui' command):
![image](https://user-images.githubusercontent.com/45708377/104891261-c1ae2200-5981-11eb-992a-a11c7d61ed0a.png)
or change it in config files:
- open Eco Server folder -> Configs -> Difficulty.eco:
![image](https://user-images.githubusercontent.com/45708377/104891377-e6a29500-5981-11eb-8fa8-c765b298a60e.png)

Did it help you?

**Comment by StallEF** [comment]
https://www.youtube.com/watch?v=rvd2dyeCqAE&feature=youtu.be

probably Game need to talk about connecting stockpile to the workbench (start camp ) in the training just =)

**Comment by Praedon** [comment]
> @Praedon @jk-fwh Thank you for the report. It's known issue and will be fixed with 0.9.2 #18640. But you can fix it. So seems you have Craft time multiplier and Craft resource multiplier = 0. You need just to change it either server UI (use '/serverui' command):
> ![image](https://user-images.githubusercontent.com/45708377/104891261-c1ae2200-5981-11eb-992a-a11c7d61ed0a.png)
> or change it in config files:
> 
> * open Eco Server folder -> Configs -> Difficulty.eco:
>   ![image](https://user-images.githubusercontent.com/45708377/104891377-e6a29500-5981-11eb-8fa8-c765b298a60e.png)
> 
> Did it help you?

This resolved this issue. Thank you!

**Comment by SlayksWood** [comment]
@Praedon You're welcome.
