### ISSUE TITLE
[0.9.2 release-141] Elevator Call Post doesn't work from every sides of Industrial Elevator.

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20158]
The center of the elevator is on the edge. Elevator Call Post radius = 5 blocks from the center of the elevator. For this reason, Elevator Call Post only works from 2 sides and not the entire of their length:
![image](https://user-images.githubusercontent.com/45708377/105688506-bbccb980-5f0a-11eb-814f-8106f1c3eebf.png)
The other 2 sides:
![image](https://user-images.githubusercontent.com/45708377/105688651-e7e83a80-5f0a-11eb-8ddd-44257db37b77.png)

**Comment by SirFrogstar** [comment]
![image](https://user-images.githubusercontent.com/78167691/106175954-9d76f000-618e-11eb-99c9-88dfe7ebeddd.png)

Elevator seems to be very picky about placement of call post. Wont work at all on far side and only works on the right hand side of the other.

**Comment by Zaskersky** [comment]
Hi, i also did a bit of testing, with the industrial elevator and the normal one.
I dont know how its coded but im throwing a asumption in here, it might be right or wrong but.
I think that the Industrial elevator and the Normal Elevator, get Locked in to a X,Z cordinate on placement specificly on 1 corner that you see in front of your character when placing it down +-, might be offset 1 block forward and 1 to the left.
And that the Elevator call sign button works in a circel/squarish radius around it, with no limit on Y level.
That worked good on the Wooden Elevator, but since the Industrial Elevator is a bit bigger, could it be as simple as increasing the numer in the programing as ?, lets say detection range from 4/5 to 7-9 ?|
![test1](https://user-images.githubusercontent.com/35546090/106270323-1aa57200-622e-11eb-9de6-6427fa0f8d6b.png)

**Comment by Zaskersky** [comment]
Hi, i also did a bit of testing, with the industrial elevator and the normal one.
I dont know how its coded but im throwing a asumption in here, it might be right or wrong but.
I think that the Industrial elevator and the Normal Elevator, get Locked in to a X,Z cordinate on placement specificly on 1 corner that you see in front of your character when placing it down +-, might be offset 1 block forward and 1 to the left.
And that the Elevator call sign button works in a circel/squarish radius around it, with no limit on Y level.
That worked good on the Wooden Elevator, but since the Industrial Elevator is a bit bigger, could it be as simple as increasing the numer in the programing as ?, lets say detection range from 4/5 to 7-9 ?
![test1](https://user-images.githubusercontent.com/35546090/106270497-635d2b00-622e-11eb-9132-14ebba36bea6.png)

**Comment by killerfrienddk** [comment]
@SlayksWood So what happens is that the elevator moves on his screen but not on mine, for him the elevator is one place and for me, it is in another place for me.

[image of my friend standing on the elevator in his game client](https://cdn.discordapp.com/attachments/410443397065867284/812796312676335646/unknown.png)

Note: It sometimes works and other times it doesn't.

**Comment by SlayksWood** [comment]
@killerfrienddk I created a separate issue to investigate synhronization problem #20738

**Comment by SlayksWood** [comment]
The original issue was fixed, but we still have some flaws. Created a new one #20740, need some code improvements here.
