### ISSUE TITLE
Kelp messed up

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2016]
![image](https://user-images.githubusercontent.com/3536496/29840154-d5aa83e4-8cb5-11e7-992b-d0148337ae1b.png)

**Comment by keegan-o** [comment]
This is a problem with not being able to use more than one sprite sheet I think for item icons? All the new icons on the new sheet appear to not work. This is a pretty annoying limitation because if I increase the size of the old icon sheet I'm pretty sure every single icon in the game will no longer be assigned.

**Comment by keegan-o** [comment]
(Also, it's already quite large)

**Comment by keegan-o** [comment]
Yeah, this would be a couple of hours of work minimum to re-name and/or at least re-assign every icon in the game-- let me know if that's what I have to do or if it can be made to allow the use of the second icon sheet.

**Comment by MarjieAVolk** [comment]
I haven't looked yet, but if there is a new sprite sheet, have you made a TMP sprite asset for it?  That's what usually causes this.  It should be fine if there are icons from 2 different sheets

**Comment by keegan-o** [comment]
Ahhhh right that whole thing.... will try and set that up if I can remember correctly.

**Comment by keegan-o** [comment]
fixxeeexdddddddd
