### ISSUE TITLE
USER ISSUE: Cement Kiln Req Tier changes

### ISSUE THREAD

**Issue by KajiK07** [StrangeLoopGames/EcoIssues#20186]
\
**Version:** 0.9.1.9 beta release-136

**Steps to Reproduce:**
When I put the kiln on the bottom floor of my 1.18 stone worshop and in my 1.8 tier brick workshop, it requires 2.0 tier but when I place it on the top floor of my stone worshop, it only requires 1.8 tier

**Expected behavior:**
Should reqire 1.8 tier regardless where its placed

**Actual behavior:**
It changes depending on where it's placed

**Do you have mods installed? Does the issue happen when no mods are installed?:**
N/A

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@KajiK07 Thank you for the report. I guess you have 'Lavish Workspace: Masonry' talent. So instead of 1.8 it should always require 2. Perhaps when you place in the wrong room, the necessary tier requirement is not updated. 
Can you provide a little more information, a several screenshots and information about the character's skills?
Also provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
Closing for no response, reopen when you can provide us with necessary information
