### ISSUE TITLE
[0.9.2 release] Feet Sink into Stone

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#20230]
When an avatar is standing on Sandstone, it looks like their feet are going into the stone. I am not sure if this applies to other stone types as well.

![FeetInStone](https://user-images.githubusercontent.com/47330823/106235878-7b8e6500-61b0-11eb-9740-d7c93b6c2d2b.png)

**Comment by WeaselDog** [comment]
It is also true for the Industrial Elevator. There is a command /test industrialelevator you can run.

**Comment by MilenkoTunjic** [comment]
Could we have proper collision for those? At least for the elevator and unique assets

**Comment by keegan-o** [comment]
So I tried adding a 'Collider' mesh to the decorator builders that add these decorative lumps to the top of rocks. Unfortunately that did not succeed in adding collision. Collision must be something that can't be added with decorators, but instead can only be on the main builder.

It goes against my better judgement to have these have collision, anyways, though. I think it is probably not worth the performance cost to do so. Given that, the other option is to simply remove these decorator builders or make them flatter.  @mirasrael Any opinions on if it's a bad idea to add colliders to bumps like these?

I approached it mostly like this, where the green is the collision I tried to add:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/2084e6a6-46f9-4ebe-afd4-0fec54841c32)

**Comment by keegan-o** [comment]
With the top decorators turned off:
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/206b40e2-a6d0-48fe-b9e3-67459797bc60)

This looks not as good on first impression but one key thing to remember is no natural cliffs will spawn like this, so flat. If you see this in-game it's because you mined it out, which means being a bit un-naturally flat is actually not bad.

This is also something we eventually can improve with natural boulder objects as part of the future natural object system.

I think what I'll try is switching all these decorations off in develop and see if people notice it or think anything of it. Better to reduce complexity and remove issues rather than decrease performance and increase complexity, if the first option looks fine.

**Comment by keegan-o** [comment]
committed the de-activation in develop branch, which means technically this is 'fixed' there-- feel free to post here with opinions about it.

**Comment by Daniel-Magulado** [comment]
Build: 0.9.4 Develop-203

Tested on Sandstone, Granite, Coal, and Industrial Elevator.
Not happening anymore.

Resolution: Closing.

**Comment by Daniel-Magulado** [comment]
Build: 0.9.4 Develop-203

Reopening, sorry. I tried another test on single blocks just to stress test the feet and shoes for their different steps and angles.
There are certain decorators appearing for single blocks.
See the image below:
![sink](https://user-images.githubusercontent.com/77248866/110243597-0c1d4980-7f96-11eb-8348-31ef9e85ea5a.jpg)
Standing on a block of Basalt.

**Comment by keegan-o** [comment]
That is likely a 'won't fix'-- it's not worth it to make detailed colliders for those types of pieces, in the same way it's not worth it to make detailed colliders for all the world objects you can also stand on top of. You'll notice if you jump up on any world object your feet are not going to contour to all the little objects on it. Whether floating is much more of a bigger deal than sinking in or vice versa is I think pretty subjective.

**Comment by keegan-o** [comment]
I'm going to close this out since the original issue was fixed, and labeling it 'won't fix' might be confusing since it was fixed for that main instance of the issue. If another issue is opened with just the last example, it will likely just be labeled 'won't fix', because adding the geometry to the colliders you would need in that case doesn't feel worth it to me.
