### ISSUE TITLE
Cloud world scaling not working

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#20256]
cloud worlds stuck in pending on sfo2. probabaly will be same on fra1.

had to turn off auto scaling on DO (i thought it was already off).

Manually adding a node fixed the pending worlds that wouldnt start.

**Comment by mirasrael** [comment]
Update with auto-scaling fix wasn't deployed. Deployed it today.

**Comment by j3fffff** [comment]
still got pending worlds issue

**Comment by mirasrael** [comment]
Seems finally fixed this.

On screen it starts new node for requested game servers:
![image](https://user-images.githubusercontent.com/475445/106594879-c9fe8380-6563-11eb-9e82-a270b9953afd.png)

Issue was related to Digital Ocean/Kubernetes bug. For some reason it had node in pool which wasn't registered in Kubernetes. So Kubernetes seen only 7 nodes, but Digital Ocean had 8 in the pool. So when Kuberntetes requested 8 nodes then Digital Ocean did nothing, because there already was 8 nodes in the pool.

I recycled broken node and it successfully registered in Kubernetes. I also improved available nodes detection algorithm. It now doesn't count as available nodes which scheduled for deletion by Digital Ocean, but still visible in Kubernetes.
