### ISSUE TITLE
USER ISSUE: Error when being a member of non-existent area

### ISSUE THREAD

**Issue by kickrazz** [StrangeLoopGames/EcoIssues#20289]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.2 beta release-149

**Steps to Reproduce:**
claim 2 different area's
delete the area you're originally a resident in
problem occurs when hovering over your name

**Expected behavior:**
it should remove or change your residency to another area

**Actual behavior:**
it still remains in an unexisting residency until you change it manually, it will throw an error when you hover over your player name

**Do you have mods installed? Does the issue happen when no mods are installed?:**
i do not have mods installed, did a fresh install aswell

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5900576/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5900577/Player-prev.log)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for reporting this.
I can confirm that this issue is happening.

Repro:
1. Start a new game and place a campsite.
2. Place the campsite and delete the property. Open the property/deed window and delete it.
3. Press C and then press Tab. Hover your mouse icon to your avatar's name.
4. Observe.

Result:
Window box appears with an error message.

Screenshot:
Normally
![1.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/3787c131-3f1c-4a0c-a56a-2731ff95fa2a)

After deleting deed/property
![2.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c0aa357c-f4c6-47ca-8879-ba4ebfe65cf0)

**Comment by Daniel-Magulado** [comment]
Existing #19978
