### ISSUE TITLE
Charcoal is Too Expensive

### ISSUE THREAD

**Issue by Sekor2600** [StrangeLoopGames/EcoIssues#20295]
Since update 9.0, the usefulness of Charcoal has decreased significantly. Craft time, labor costs, and fuel costs all contribute to this. We should find a middle ground between old costs and new costs.

**Old costs:**

- Recipe cost: 15 Lumber with 1 Minute crafting time
- Max skill cost: 3 Lumber with 0.2 Minute crafting time

**New costs:**

- Recipe cost: 7 Wood with 4 minute crafting time and 80 labor cost
- Max upgrade cost: 3.5 Wood with 2 minute crafting time and 16 labor cost

**Comment by danisani1** [comment]
Made the same observation as a logger + carpenter: With an advanced logging upgrade it starts to be okay-ish, but for 100 charcoal u already burn a massive amount of coal. The long production time though is quite realistic, since charcoal usually is burned for several days. There would be the need for a charcoal kiln/heap. It should create smog (the kiln should as well) and consume very little fuel.
With massive coal reserves in grasslands the ecological need for charcoal is near 0 anyways, just the stackability is a great argument. 

If there is another step (like crushing, concentration, cleaning etc.) necessary for mined coal to be burned, it could increase the viability of charcoal naturally.
In addition charcoal, due to its high purity, could be used in filtration (activated carbon: though it had to be crushed)

**Comment by jamesyoung79** [comment]
Charcoal's biggest advantage is it is not carried and is 1/4th of the weight and stacks to 100. Charcoal is also renewable while coal is not. Each Wood burns for 1 min 20 seconds (4000J / 50W). Charcoal take 7 wood + 3 wood in fuel to create 1 charcoal. With this in mind with a logging advanced upgrade module from a fuel stand point charcoal breaks even for fuel (See Chart Below). 


Upgrade | Reduction | Logs | Log Fuel | Craft Time | Fuel Used | Total Fuel | Total Logs
None      | 1               | 7       | 28000 J   | 240           | 12000 J     |  40000 J   | 10
AU1        | 0.9            | 6.3     | 25200 J  | 216            | 10800 J     |  36000 J   | 9
AU2        | 0.75          | 5.25   | 21000 J  | 180            | 9000 J       |  30000 J   | 7.5
AU3        | 0.6            | 4.2     | 16800 J  | 144            | 7200 J       |  24000 J   | 6
AU4        | 0.55          | 3.85   | 15400 J  | 132            | 6600J        |  22000 J   | 5.5
Logging  | 0.5           | 3.5     | 14000 J  | 120            | 6000 J       |  20000 J   | 5

Perhaps if the Time to create charcoal was reduced by 1 minute it would be more attractive for people.

One thing that comes to mind would be to allow food cooking fuel sources should not allow coal, but rather use charcoal. Food cooked over coal is sure to be delicious.
