### ISSUE TITLE
9.2.4 framed glass stairs collision box too "low"

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#20359]
Framed glass stairs collision box seems to drop down somewhat so cannot so a stairs setup like the below, red is where its hitting, blue is the stair lines, also cannot jump in the area despite it visually having space above char 

"Under slope" though is fine in this case.

![image](https://user-images.githubusercontent.com/61889138/106918050-c5230680-6700-11eb-8b71-a974c7f07d07.png)

**Comment by IcedForge** [comment]
Thank you for reporting these oddities. 

![Screenshot_195.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/23671b32-df0e-4fd7-82ef-705d0432078d)

I would assume these are because the old block sets where not updated with detection for their block less styles.

Following blocks are having the same behavior that needs correction.
Corrugated Steel - FloatStairsCorner, FloatStairsTurn, FloatStairs
Framed Glass  - FloatStairsCorner, FloatStairsTurn, FloatStairs
all the ashlar models seems to work properly

**Comment by keegan-o** [comment]
fixed in develop and staging ![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/63e7d31f-d9f4-4a68-9b4d-2f8e659ba364)
