### ISSUE TITLE
Skills UI Update

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20390]
![image](https://user-images.githubusercontent.com/3536496/107096058-b8fd7e80-67be-11eb-8177-177d180ca4a0.png)
- [x] Make the undiscovered professions a question mark in their icon, like the specialties.

![image](https://user-images.githubusercontent.com/3536496/107096072-c0bd2300-67be-11eb-8b88-c95ca23456dd.png)
- [x]	Make the ‘level benefits’ background bar a brighter color, so you can tell when it’s greyscaled or not.
- [x]	Make a frame to hold the scroll and star indicators on the left – these indicate the things you need to unlock the benefits at that level. 
- [x]	Make a nice XP source bulb at the bottom of the meter there. 

![image](https://user-images.githubusercontent.com/3536496/107096098-d5012000-67be-11eb-9a3d-67aa38cfd625.png)
- [x] Greyscale professions you don’t have.

![image](https://user-images.githubusercontent.com/3536496/107096126-e0ece200-67be-11eb-8bd6-da04a9c97984.png)
- [x]	Show the stars stacked up here, show the icons for your professions, and show the specialties you hold.
- [x]	Make these caps take effect, so that you cant get more than the shown amount

![image](https://user-images.githubusercontent.com/3536496/107096147-eb0ee080-67be-11eb-8189-4d6827595512.png)
- [x] If there are no benefits display a ‘none’ 

![image](https://user-images.githubusercontent.com/3536496/107096204-07ab1880-67bf-11eb-8f35-7a6a523e1c86.png)
- [x]  These tooltips are annoying because they block what youre looking at. Remove them, and instead put the tooltip on the big icon: 
![image](https://user-images.githubusercontent.com/3536496/107096220-1265ad80-67bf-11eb-8d75-03ec4a4f348f.png)
- [ ] Go over this whole dialog in detail and find more polish to add!  Think of it from the user perspective and improve it.

**Comment by Mattprass** [comment]
seeing as how this is a huge task, @madpingui and I will be sharing the workload here

**Comment by madpingui** [comment]
Professions Dialog:
https://docs.google.com/document/d/1WIyXy4WEmy19VZmQ05r_wjVedVZKDrR8vlcwT9398ks/edit?usp=sharing

**Comment by TwixterZ** [comment]
checked on 9.4 Develop 277 

Frame around star and scroll changes makes the icon looks low res, older icon looks better in comparison
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/99e583e6-464a-4309-93cc-5cdfa64c8cbc)

**Comment by IcedForge** [comment]
Best way to check it is if you open it up and try see what new things you unlock, the list forces the currently displayed information to be misplaced. I need to scroll to find it and its very counter intuitive.

So initial suggestion would be something like below instead.
![Screenshot_91.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/07c6aea9-23f4-411d-a1b7-c26e1d98c0f3)


My other idea was if we want the list to expand upwards, swap out the placement of the top and bottom block completely.
So learn skill is below the list of objects you unlock this way we also have the same effect of, enabling it doesnt change it unless you scroll and want to look it up. But this is a difference between if we want the list to ascend or descend visually.

![Screenshot_92.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/ac62bd5e-2ba3-4fb6-afe4-e656fea6692d)

**Comment by IcedForge** [comment]
Also noticed that we no longer display the amount of skills you have / specialized in is no longer summerized and numbered?
Im not sure this is a intended feature but it can potentially look very odd if you have a lot of professions

https://i.gyazo.com/bf82237ccfb8aec5a85dd55aebdd8802.mp4
Its a bit fast, but you can see how its "shrinking" and removing a lot of the icons due to exceeding the width limits of the display.

**Comment by IcedForge** [comment]
![Screenshot_94.jpg](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/239b31ed-8a8c-49ae-9022-085bcdf6cc51)

**Comment by madpingui** [comment]
The skills summerized in icons instead of numbers was a @johnkslg decision, it is readjusted in size to try to fit all in a single line, if there are many it changes to be 2 lines, that is why they also reduce in size, it is balanced so that the size is not too small and not too wide to overlap the professions, has the objective in addition to being a shortcut to access the specialization if you click on them.

**Comment by IcedForge** [comment]
Well then the skills row is broken somehow since its not displaying them all anyway as you can see in the video it shrinks and hides the entire 2nd row.

**Comment by madpingui** [comment]
its not broken at all, the desired behaviour of the icons is that everytime you open the Skill UI they do an iteration trying to find the best size to fix in 1 row, so they reduce in size until they get to a certain minimal size, if they are a lot then they it becomes 2 rows, but you can see that the last element of the second row ends up being the last one in the first row after they complete the iterations.

**Comment by SlayksWood** [comment]
I will not close it. the first thing that catches my eye is the progress bar that goes down:
![image](https://user-images.githubusercontent.com/45708377/117927576-10057900-b303-11eb-96e3-93bbb5650e3f.png)
For current interfaces, this is strange. usually either left to right or bottom to top. 
The same is true for the skill level, it is strange to see all the progress down, although this was suggested above, but this is not as critical as the progress bar.

**Comment by IcedForge** [comment]
![Screenshot_76](https://user-images.githubusercontent.com/24981362/120643897-ff19d480-c476-11eb-9c43-80680b417d10.jpg)

Im still not convinced that using icons at the bottom is the best way to go about it, i would rather have numbers as right now it feels very very cluttered with icons shrinking to fit in place and also very hard to tell what is what if you have poor eye sight and it is starting to be just "overload" of things going on.

I would propose going back to the original display of just numerical representations as you already have all the icons all over on this UI already.

**Comment by IcedForge** [comment]
I also do not understand the value of being able to mouse over tooltips of icons in 2 places inside the same UI element?

**Comment by SlayksWood** [comment]
The user interface is still incomprehensible, incomplete and uses unusual ways of displaying information:

- [ ] 1. Expirience bar. It cannot be intuitive for anyone to understand when your progress is going down! 
![image](https://user-images.githubusercontent.com/45708377/121644278-7ebd2a00-ca9b-11eb-97f9-23bda288b842.png)
or it should be up or from left to right like here: 
![image](https://user-images.githubusercontent.com/45708377/121643848-f76fb680-ca9a-11eb-8ea5-af12c6494134.png)

- [ ] 2. Still have icons and a lot of stars here:
![image](https://user-images.githubusercontent.com/45708377/121644222-6cdb8700-ca9b-11eb-83ff-a270448a0828.png)
![image](https://user-images.githubusercontent.com/45708377/121645947-749c2b00-ca9d-11eb-99e2-38b331f3cdd7.png)

- [ ] 3. Command '/point' breaks icons and stars: 
- take a lot of specialties and have several stars.
- use /point to add a few stars again.
- check UI:
![image](https://user-images.githubusercontent.com/45708377/121645375-ca240800-ca9c-11eb-9a96-3ae8b59b49fb.png)

- [ ] 4. Survivalist profession is not counted in professions held:
![image](https://user-images.githubusercontent.com/45708377/121645787-44548c80-ca9d-11eb-8c1b-2fa5bfb22a07.png)

- [ ] 5. Perhaps this is just my problem, but I get confused - at what level what opens. It is possible that this is due to the first point, well, here's a comparison.
- 0.9.3 UI: 
![image](https://user-images.githubusercontent.com/45708377/121647773-7830b180-ca9f-11eb-8e4a-542149477b87.png)
- 0.9.4 UI, How is it perceived by me:
![image](https://user-images.githubusercontent.com/45708377/121648096-c9d93c00-ca9f-11eb-925b-1b1774319593.png)
every time I open the skill UI, my level is shifted by 1. Personally, I do not perceive this information. Of course this is a habit, but it seems to me that most of the players will come across this, because now they have more information here. And everyone will have a habit to old UI. Although, over time, this feeling is possible and disappears (when the players get used to it).
But getting used to the interface is not equal to a good interface. If we leave the system from top to bottom, we need clearer boundaries by levels.

**Comment by SlayksWood** [comment]
I still don't like a lot of stars and icons on  bottom, but this is intended, so I'd closed this one and will open another issues if this UI has bugs.
@IcedForge Can you check it too?

**Comment by IcedForge** [comment]
I guess we can close it, it looks alright and we spent a lot longer on it then i think was necessary can create a new issue if there is any problems we find as you say.
