### ISSUE TITLE
[0.9.2.4 beta Release-150] Database issues and overall performance degration - Server:White Tiger

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20486]
We are seeing more and more degration on tiger with civic ticks not running off, inconsistent counting and overall statistic bugs caused by extensive use of the DB system for law interactions.

https://cdn.discordapp.com/attachments/690968592874995792/808792094125719572/Screenshot_46.jpg
Save file
https://drive.google.com/drive/folders/1_8popFDRBT03BFGl7oVh0KJIXxLaXjFF?usp=sharing

With the added requests to add further data and statistics into the DB this needs to be looked into if we need a refactor / reconstruction on how the db operates before this happens.

This will be blocking the following addition
#20446

**Comment by redwyre** [comment]
Please write up a report of what you discover with performance

**Comment by gzatravkin** [comment]
So after some investigation, one of worst operations now is demographic recalculation with conditions based on DB.

At White Tiger we have 1300 players, and it makes 1300 count queues to db, which takes a lot to process (near 60s at my pc). And this operation is repeated every 4-5 mins. 
![image](https://user-images.githubusercontent.com/53317567/107691636-75a58300-6c8a-11eb-837c-a74b7b0d3524.png)

One possible optimization - to create some class DBCache, refill it for all users with single query before dems are calculating, and use this cache instead of 1300 new queries. 

Other problem is GarbagePlugin. It takes 10-20% of cpu without any need. 
Seems like when server is laggy, it causes it to work with 0ms delay. It make thousands of repeats per second per inventory.
Probably just change to not repeat faster than 1s would be enough.

![image](https://user-images.githubusercontent.com/53317567/107696487-c6b87580-6c90-11eb-84ca-c7470471d4d2.png)

![image](https://user-images.githubusercontent.com/53317567/107696884-45151780-6c91-11eb-9932-38845eaedbe0.png)

Change that I offer: 
![image](https://user-images.githubusercontent.com/53317567/107697022-71c92f00-6c91-11eb-87e8-1bef01c2b95e.png)

**Comment by gzatravkin** [comment]
After replacement for garbage: 
![image](https://user-images.githubusercontent.com/53317567/107699422-d20da000-6c94-11eb-9d19-0cb52ce7fb14.png)

**Comment by D3nnis3n** [comment]
I need moar improvements!

**Comment by IcedForge** [comment]
I will close this issue then as we have tested the performance changes on white tiger for an extended period of time and have had quite good results. Will need to further refine and optimize this later but for this particular issue i think we are good.
