### ISSUE TITLE
AutoGen File changes

### ISSUE THREAD

**Issue by jamesyoung79** [StrangeLoopGames/EcoIssues#20514]
To make modding more seamless with updates can we get a change to the auto-generated classes to include ModsPostInitialize and ModsPreInitialize partial functions. See AshlarBasalt.cs if need example. If all recipes, items, world objects, and organisms had this it would allow for server mods to be completely separated from SLG seeded mod files.

**Comment by IcedForge** [comment]
@jamesyoung79 Thank you for reporting. This should already be fixed in 9.3, ill be verifying it this week but i believe it was sorted.
There is currently though a slight issue with it and that is you cannot edit serialized values, only add new ones. So changing stack sizes and such is impossible to do via separate hook files as of now, we are working on improving this system as we go.
