### ISSUE TITLE
USER ISSUE: solo Game wont launch.

### ISSUE THREAD

**Issue by BrotherDerp** [StrangeLoopGames/EcoIssues#20530]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
1. Attempt to launch a server

**Expected behavior:**
Launched a server

**Actual behavior:**
Doesnt launch server, throws an error message

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/5976125/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/5976126/Player-prev.log)

**Comment by MishkaFur** [comment]
Server log from discord

[log_210213093026.log](https://github.com/StrangeLoopGames/EcoIssues/files/5976174/log_210213093026.log)

**Comment by IcedForge** [comment]
Will close this for now, would be good to know what you edited / used that initially caused this but any time you manipulate things with admin commands in particular using hidden or features that are disabled due to not working properly or not implemented completely make sure to backup any relevant information.
