### ISSUE TITLE
User feedback: too much food required

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20541]
"Stamina is...bad. Considering food takes like six real life hours to grow it gets used way too fast. I don't know where you are all from, but I'm in the US, in a state called Montana. It's a place of nothing but forests and mountains. I quite literally grew up wandering the outdoors via the back yard. You know what you don't need? Anywhere near as much food as you eat in this. That's a general complaint of any "Realistic" survival game though. Nobody seems to know what a real amount of food is."
https://docs.google.com/document/d/1nFnxlEBwzV4lkEiE6BhzuS-p0obhNJO7GrjTNvUZxVQ/edit

Thinking this is the result of 'low skill lets you do the action with bad calorie efficiency', and the user not realizing that.  To fix this, we either need to change those super-low-efficiency actions to be prevented, or make it very clear the efficiency of the action youre doing in comparison to what you could be doing.  Could change the calorie number that pops up to say how efficient the action was.

**Comment by WeaselDog** [comment]
@johnkslg What actions would you like to prevent or add a warning to?

**Comment by CrazyFluffyPony** [comment]
This is not a survival game, it should not reflect how much food one person would actually need.

If you dont have the time to read everything, at least read the conclusion and suggestion at the end.

If you craft 1 million mortared stone on 50 tables at the same time, its no wonder that you need more then 3 bowls of rice a day.
Food consumption is something that is almost only there to create an incentive to players to buy stuff from a chef/cook etc.
And if you ask me (1000hrs on the clock, almost played all professions long term) then **food is not important enough** in the current version.

I have played on multiple servers, and the only time people in the food industry are able to make some money (or be able to get resources from trading in order to build a house or decorate it) is when they are part of a team of people (that have some kind of social connection, like friends etc.). Or when you have a really really really friendly server that behaves like a bigger family, but that is the same in my eyes.
On any server that has no deep social connections (and that is 90% of all servers and 100% of the official servers), food industry is doomed to fail (in terms of being able to trade with people). And here is the explanation:

A. New people don't know much about food, they are overwhelmed buy other things. They might know games like Minecraft, where you consume food and it fills up your stamina/health (and yes i know that we have some explanation in the wiki, but you know yourself how few people read all of that before playing). So new players are totally fine in picking up corn and tomatoes, at least for the first 2 weeks of playing.

B. Time
The longer you play, the higher your skill level will be. The higher the skill level and the better your equipment (backpack, tools), the less calories you will consume. The same rule applies to tables and upgrades. Assuming that you play the same amount of time and you do similar tasks (e.g. cutting wood) then your consumption declines. On the other side, you will craft/produce more items, so the amount of calories put into labor will increase (but from my experience, not too much. Unless you start to build huge decorative castles).

What also changes over time, is the necessity of skill points. Of course this depends on the play style, so it is a very personal view. But i normally do not NEED more then 2 or 3 stars. If i choose a profession i am very dedicated to it, which consumes time, so i simply do not have enough real life time to take care of more then 3 professions (especially if you would have work/school/kids/...)
Even on very high collaboration settings, you will receive those stars pretty quickly. Building a small house with +20 bonus will get you there without any problem.
And yes, low skill bonus means it will take more time to level up your skills, but hey, its the beginning of the server, there is NO good food anyway! But we got some nice hewn log furniture en mass!

Now comes the change of food availability over time:
In the beginning, there is no simply no good food.
I would actually go so far to say, getting 400 papaya from the rainforest is 20x faster then trying to get some tomatoes, a campfire, wood and then fry them.

A couple of days later, farmers/gatherers and the first few chefs have set themself up, maybe had some conversions going on, and we have the first food available on the market that was grown professionally. But here comes the next problem: ONLY cooks will buy your stuff. You have nothing to sell to anyone else. Sure the farmers and gathers can trade with each other, but about external sales? No one can use oil, fiber production by hand is absolutely inefficient and the only recipes are the ones from the cooks. Meanwhile a logger and a miner etc. have different products that can be sold to different other professions (stone to the masonry, ores to the smith, clay to a potter, crushed stone to a basic engineer). It is especially hard to trade for anything on the market, since you can only sell goods everyone can pickup anywhere, and no one except the chef wants. If you want something, you have to buy processed food from the chef, then hope that the basic engineer shop buys exactly that kind of food, for a price that is at least somehow realistic. So a miner, that is used to pickup 4 stone after running to the next hill, and using his pickaxe once, now has to think about the price of corn, where he has to move 10 meters and then press E to pick 2 corn up.
Of course, the problem is, that while the amount of stone available over time is infinite, you just have to go another block. But for corn, you have to plant it in the proper space, take care of seeds, wait, gather it, then maybe fertilize it.
Even though i totally accept this communication problem as part of the game, it definitely makes food business way harder then it could be and that it looks like to new players.

Fast forward a couple of days:
The farmer and gather now have a very nice production going on, all the fields are flat and accessible (in different biomes), they have a good seed/food ratio. The consumption of raw food per cal decreased because of increased cooking skill level. And also, cooks are not required to craft more food solely for the purpose of leveling up.

C. Shops cant sell/buy based on calories, quality or category of food
It is insanely hard to put sell orders for the chef already but still doable. Meanwhile, any other profession that wants some food, ANY FOOD, has to create buy orders for every frkn kind of food out there and set a somewhat realistic price, even if they never played chef/farmer/gatherer before. OR, THEY SAY WHATEVER, AND CONTINUE TO PICKUP CORN AND TOMATOES!
But above is more an early game problem, that is minor compared to the long term problem.

**Conclusion**

Food has not enough impact on the other professions, especially the quality of food.
I have been playing Life is Feudal, and i suggest to implement a similar solution to what they did. They gave everything a quality. Depending on the quality the item was more or less effective. E.g. an apple of high quality would provide way more calories/stamina. A tool made out of bad quality stone and wood would break sooner.

Now, implementing exactly this behavior would not really solve the food problem and it would (maybe) be a lot of work.
But what about this:

Food quality has an effect on recipe effectiveness. You only eat corn? Then you will cut 50% less boards out of the hewn log then the person eating a delicious bear supreme paired with salad and fish!

This means, that good food is now essential to effectively spend play time in this game! And yes, of course once this is added, proper balancing is necessary. I don't want to cripple other professions too much, but boost the food industry!

**Comment by WeaselDog** [comment]
This has changed a lot since this was first posted. We have a couple tasks to address some of the remaining topics.
