### ISSUE TITLE
Improve smoke display in 'cities upon a hill' graphic

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#20605]
![image](https://user-images.githubusercontent.com/3536496/108134806-b545e380-706b-11eb-9c9a-5a3fdcd0ae16.png)
There are white blocks, and it just dissipates instead of disappearing.

Compare to campfire on next graphic:
![image](https://user-images.githubusercontent.com/3536496/108134849-cb53a400-706b-11eb-99e9-3b36b753f69d.png)

**Comment by keegan-o** [comment]
@MilenkoTunjic @johnkslg want to touch base on this, it sounds like working with UI prefabs somewhere which I am not familiar with. Also it sounds like something simple just broken with the particle effect used.

**Comment by z-73** [comment]
![CityUponAHill.gif](https://images.zenhubusercontent.com/60a3593a199750a6f2fe297d/08970e30-03c5-41ea-b807-36e50853fe68)

Fixed! I just changed the shader to use an alpha blended one that can take the particle over life colour and changed the particle system to prewarm so that it is already fully simulated when the screen is in view.

**Comment by WeaselDog** [comment]
Unfortunately this will have to be redone on develop due to a merge conflict going into 9.5

**Comment by SlayksWood** [comment]
fixed in 0.9.4 but as far as I understand it reopened to fix in 0.9.5 again. changed qa pipeline too.
