### ISSUE TITLE
Server problems 

### ISSUE THREAD

**Issue by SgtKillmaschin** [StrangeLoopGames/EcoIssues#20671]
Hello I have since 0.9.2.4. very strong performance problems and always have a warning message (in the link)

do you have an idea how it can get better again?

VM server data:
intek Xeon e5-2680 v2 6 core
10GB ram

World info:
4km³
15-30 players 

[https://prnt.sc/1019bmw](url)

**Comment by IcedForge** [comment]
@SgtKillmaschin Thank you for your report, unfortunately it seems like the upload is broken, also can you take a screenshot of the memory / system use while the server is running?

**Comment by SgtKillmaschin** [comment]
[https://prnt.sc/101taap](url)

**Comment by IcedForge** [comment]
Still didnt fix upload properly, you need to either link it from an external source, or let it finish uploading the image before submitting post.

**Comment by TwixterZ** [comment]
@SgtKillmaschin would you able to give requested screenshot again? have this issue persist at your end?

**Comment by IcedForge** [comment]
Will close as there were never a follow up information wise. 

But i suspect strongly that the cpu is struggling quite significantly because a 4km world in particular if there is a lot of active players keeping a lot of different areas loading in / out this can have a pretty significant simulation impact as well as the world size being the maximum supported on a low speed core will combined make for a less optimal performance, i would suggest lowering down to 2km or lower and see if it performs differently.

Eco favors single core speed over multiple cores with lower speeds.
