### ISSUE TITLE
Extend localization system to gather const strings

### ISSUE THREAD

**Issue by olegshegai** [StrangeLoopGames/EcoIssues#20695]
It's currently impossible to share `LocDescription` attribute between different properties without copy-pasting the same strings.
It would be great to be able to declare constant strings and pass them to the attribute, but the system is currently unable to gather such strings.

As it was suggested [here](https://github.com/StrangeLoopGames/Eco/pull/7661#discussion_r579436403), we can leave a `//Localize` marker at the end of the line to point out such cases.

**Comment by StallEF** [comment]
@WeaselDog suggestion:  creating a single dictionary for such cases
I will give as an example:
-Enter Description.​
-Enter Description
-<Enter Description>
-Enter description here.
-<Enter work description>

as you can see it makes no sense, and use one option is preferable

**Comment by gabrielgindridev** [comment]
@olegshegai it already works! Since this change: https://github.com/StrangeLoopGames/Eco/pull/8183

![image](https://user-images.githubusercontent.com/65634950/114608011-9763bc00-9c73-11eb-9bac-7e09beb162b8.png)

Another question. Is in this issue intent to create an actual place (class) to store LocString const or we will leave them in their own context like in the PR: https://github.com/StrangeLoopGames/Eco/pull/7661
