### ISSUE TITLE
Game server lags when opening Webui

### ISSUE THREAD

**Issue by jolpeh** [StrangeLoopGames/EcoIssues#20699]
Game server lags for multiple seconds when someone opens the webui (note the webui works fine it just seems to take a while to load) I think its something to do with the authentication as it throws "up a Error when verifying login token: The operation has timed out" in the server console. Would love to know a fix cant find anyone with this issue online and its the only thing in the server that is causing any lag 

Thanks

**Comment by TwixterZ** [comment]
Thank you for reporting this @jolpeh I have tested this in my private game, and seems that I do not face this problem.

Does this happens to you in a public server or your private game? Have this happen to you again since?

Appreciate you providing these additional information for us to pinpoint the cause of this issue.

**Please also provide log files. Instruction is here 
[https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file]

**Comment by TwixterZ** [comment]
closing issue due to lack of response
