### ISSUE TITLE
[0.9.3 Staging-1941]Ramps always faces west after picking it up

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20772]
Tested on 0.9.3 Staging-1941.

Issue: When picking up placed carriable items that follow a direction or orientation such as stairs, walls, etc, they always follow their original orientation after being picked up. However, Ramps always resets or faces towards the west after picking it up regardless of position.

Repro:
1. Place a Ramp. Make sure it's not facing towards the west.
2. Pick the Ramp that you placed on step 1 and observe.

Result Video Repro:
https://images.zenhubusercontent.com/47210472/ee5ee251-6d10-4654-b522-3b937b6191cd/2021_02_28_01_28_trim.mp4

Note: Only happens to Ramps.

**Comment by MazonDel** [comment]
I am posting my investigation results from looking into this issue so that the next person to look into this issue has an understanding of why it was not done the first time it was assigned. A tldr-summary is at the end.

Normally anything in the game is just a singular block OR it's a WorldObject or animal, but the dirt/stone ramps are hybrids. Ramps are still just 4 individual blocks with special code that pretends to treat them like WorldObjects for the most part (ex: On the server if you try to pick up a ramp, it starts as a "delete this one block", but there's a special check for "Is this a ramp?" and then it has special behavior which treats everything as individual blocks.

From a functional standpoint, picking up a block causes the server to generate the following actions.

(If allowed.) Delete current carried inventory. Pick up 1 dirt block, put it in inventory.
(If allowed.) Delete current carried inventory. Pick up 1 dirt block, put it in inventory.
(If allowed.) Delete current carried inventory. Pick up 1 dirt block, put it in inventory.
(If allowed.) Delete current carried inventory. Pick up 1 dirt block, put it in inventory.
(If allowed.) Delete current carried inventory. Add 1 stone/dirt ramp.

Instead of just a singular pickup action.

The reason this is a problem is that the game doesn't really treat rotated blocks LIKE rotated blocks. We just have 4 copies of every block, each with a rotation. So blockID 1234 might be a north facing brick staircase and blockID 1235 might be an east facing brick staircase. That's all the client knows about the block it just picked up. So when you pick up the staircase it doesn't say "Brick, staircase, north.". It just says "blockID 1234". It doesn't KNOW it's facing any given direction, that information isn't tracked, it's sort of just inherently derived because the adjacent blockIDs are for the other directions.

And the reason this is a problem for ramps, is that the client doesn't really ever know which direction the ramp is pointed when it's picked up, because if it's a dirt ramp, then what it picks up is a dirt block (which has 1 rotation) or a stone-road block (which has 1 rotation). So that information is already lost when you pick it up. But that doesn't really matter because the following "Delete current carried inventory..." set of actions definitely wipes out all that stored inventory information anyway. So that information is pretty much doubly deleted.

When we specced the issue, we thought it was just a matter of the directionality code not executing for some reason, but there pretty much isn't any directionality code to run because that's fundamentally not how blocks are treated.

SUMMARY
Dirt/Stone ramps are hybrid Block/WorldObjects with custom code overlaid on normal block functions to handle their special use-cases. Directionality under normal circumstance is obtained from the blockID of the block that is picked up, or in the case of WorldObjects is just not maintained at all. In order to fix the issue, it would require "hackjob" code to determine and reapply the directionality on the client, or it would require an architecture change (blocks being aware of their rotation).

Recommendation: Make dirt/stone ramps cost 1 dirt/stone per "ramp" and shift their operation to be like asphalt ramps, which use the Block Form system to let the players specifically place each segment of the ramp.
