### ISSUE TITLE
USER ISSUE: Coal on map raises with terrain height increase. 

### ISSUE THREAD

**Issue by Trustyn** [StrangeLoopGames/EcoIssues#20794]
\
**User Id: (Trustyn)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Raise the terrain from 160 to 220.

**Expected behavior:**
The terrain height will be allowed to grow up to 220 and the resources will stay underground. I.e Not being above ground unless intended. 

**Actual behavior:**
The coal on the map raises along with the terrain causing it to all be above ground.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/6063555/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/6063556/Player-prev.log)
![Eco_d1aqXWqtKP](https://user-images.githubusercontent.com/15116880/109539282-fd0a3900-7a75-11eb-9e6c-d2e03f4920e4.jpg)
![Eco_ryd8dSvvDC](https://user-images.githubusercontent.com/15116880/109539286-fda2cf80-7a75-11eb-9cbc-45411a5ab029.jpg)

**Comment by IcedForge** [comment]
@Trustyn Thank you for reporting this, could you upload your worldgenerator.eco file for me to take look at?

**Comment by IcedForge** [comment]
It seems like its just an unfortunate side effect from the current restrictions in the world generator, as it sets the veins from a central block under specified conditions, and it looks like your coal vein spawned in that limestone cliff which caused the vein to be built outwards from that, in that height.

As a graphical representation below, the red line is actual ground level in the cleared area.

![Screenshot_15](https://user-images.githubusercontent.com/24981362/109786367-5f497200-7c0d-11eb-84d3-0d17ffdfa241.jpg)

Which means on the offset that the vein decides to spawn in a tall cliff this can cause some bad/unwanted behavior.

Which can be seen like this, while the bottom vein is fine as its in leveled terrain yet if the same sized vein spawn on the left top indicator this will cause the vein to stick above ground quite significantly.

![Screenshot_14](https://user-images.githubusercontent.com/24981362/109786689-b64f4700-7c0d-11eb-971a-52b4ea5f51ca.jpg)

As for your explicit odd case from what i can tell, because the coal vein is not contained inside the desert it has no interaction with it and because its generated above the ground level of the desert its empty below?
Which makes this a problem both with how veins are non conditioned between biomes as well as non restricted.

![Screenshot_19](https://user-images.githubusercontent.com/24981362/109787339-6ae96880-7c0e-11eb-90f7-5e667c53695a.jpg)

**Comment by Trustyn** [comment]
That makes a little sense. It's as if every coal node was pushed up and if it would have originally spawned just under ground level it was pushed up higher then the surrounding terrain. Unfortunately at the time I was creating random seeds looking for a "good" map for a new server. Here is a recreated map that has the same issue. I've only been manipulating the: Seed, Dimensions, and Height.
[WorldGenerator.zip](https://github.com/StrangeLoopGames/EcoIssues/files/6078345/WorldGenerator.zip)

**Comment by IcedForge** [comment]
Will close this issue as we have plans to upgrade / change out the world gen systems in the future but this particular limitation wont be fixed until then unfortunately.
