### ISSUE TITLE
[0.9.2.4 beta release-156] Fuel inventories are linked by default

### ISSUE THREAD

**Issue by thomasfn** [StrangeLoopGames/EcoIssues#20793]
When placing a new world object with the `LinkComponent` component (e.g. a workbench), it will link automatically to any fuel inventories nearby, in addition to any regular inventories. This causes an issue when the workbench has recipes that use fuel, for example, "Hewn Logs" that consume "Logs". This also affects vehicles when buying from a store (e.g. drive to a store, buy some hewn logs, sometimes they end up in the vehicle's fuel slot).

Typically a player would expect to place logs in their fueled world object (e.g. a campfire) and to have them all be used for burning as fuel - the player would not expect the logs to be "stolen" out of the campfire for crafting. Therefore fuel inventories should not be linked by default, as the only two cases I can think of where linking to a fuel inventory is desirable is as follows:

- Linking a store to fuel inventories, to allow players to sell fuel into fuel slots (e.g. buy coal into fuel slots of an array of kilns)
- Linking a kiln to fuel inventories to craft charcoal directly into them

**Steps to Reproduce**

1. Place a fueled world object, for example a Campfire, on a claim
2. Place a Stockpile nearby, on the same claim
3. Place a Workbench nearby, on the same claim
4. Examine the linked inventories on the Workbench. Observe that:
    - The Stockpile is linked (expected)
    - The fuel inventory of the Campfire is linked (_not_ expected)

**Comment by MazonDel** [comment]
Look into the Potted Plants system, because we previously gave an upgrade so that the inventories of a potted plant cannot be seen by stockpiles/workbenches, but they can see others.

For example, if you create a new world and put a stockpile down and a potted plant. When you access the stockpile, you should not see the potted plant. But when you access the potted plant, you should see the stockpile.

You might be able to repurpose the same system to solve this.

**Comment by TwixterZ** [comment]
fix tested and confirmed as of 9.4 Develop 259
