### ISSUE TITLE
[Clothing Improvements] Two new shoes to replace two duplicate shoe items

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#20845]
Build: [0.9.3 Staging-1945]

### Issue
The art design for both Low-Top Shoes and Running Shoes are the same. The same issue can also be observed with Work Boots and Tall Boots.

Screenshot:
![s.jpg](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/56576e99-aa69-44cd-8c06-6d4fc1ab39a7)

Running shoes should have shoelaces with designs appropriate for running. Tall boots should be tall like cowboy boots.

**Comment by keegan-o** [comment]
Oh milenko, master of clothing, will thou bless us with some new shoe assets to use for these already existing items? Looks like we want something properly sneaker-like for the running shoes, and something more utilitarian for either tall or work boots. I could imagine tall boots being something stylish rather than practical. But all up to you.

**Comment by Daniel-Magulado** [comment]
Additional info from #21978.

> I didn't see the old model but the icon was like this
![image](https://user-images.githubusercontent.com/77248866/119448743-52e43980-bd64-11eb-8792-96373c268bf2.png)

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/084a918c-bbb2-4c25-9c84-3a2f2b7e4e23)![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/fce8443f-3053-4ad2-b8b5-e6118c710c77)

Two new shoe assets assigned to Running Shoes and Work Boots, thus the four different shoe items have 4 different looks.
