### ISSUE TITLE
[0.9.3 staging-1948] Hide Settlements from ECOpedia

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#20858]
![image](https://user-images.githubusercontent.com/45708377/110287989-64853300-7ff8-11eb-870e-520b7d416846.png)

**Comment by WeaselDog** [comment]
You can find this in the Reference Section under World Index. The World Index is calculated automatically by everything in the registrar. There is a registrar entry for Settlements.

We need an option to hide things from the World Index in Ecopedia. Ideally instead of making an exclusion for Settlements, we create an option to have some entries hidden from the Ecopedia.
