### ISSUE TITLE
USER ISSUE: Glitch

### ISSUE THREAD

**Issue by espencapable** [StrangeLoopGames/EcoIssues#20874]
\
**User Id: (Not logged user)**
**Version:** 0.9.2.4 beta release-156

**Steps to Reproduce:**
Mining a tunnel through shale rock.

**Expected behavior:**
Continued mining

**Actual behavior:**
Teleported me to the top of the mountain. 20 blocks up.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by TwixterZ** [comment]
hi @espencapable 

Thank you for reporting, 

Since you did not provide a short video of this happening, we would assume that there are shale ores on the floor that pushes you into your cave wall which have prompted the game to teleport you to the next Y tile height with clear sky access (in this case, on top of mountain which is 20 blocks up). 

this however is an intended function (to prevent players to be stuck in a wall) 

I will close this report for now, feel free to re-open this if what have happens to you is different than what I have pictured above.
