### ISSUE TITLE
[0.9.2.4 beta release-156] /elections/generatetestdata: 500:error code

### ISSUE THREAD

**Issue by IcedForge** [StrangeLoopGames/EcoIssues#20960]
Was not sure who to assign this too, from conversation with @denysaw 
its throwing a 500 error and not liking it.

![Screenshot_62](https://user-images.githubusercontent.com/24981362/111234418-cc3a1000-85ee-11eb-9621-5c78ef07051a.jpg)

![Screenshot_63](https://user-images.githubusercontent.com/24981362/111234624-3d79c300-85ef-11eb-9941-8548a6c6aec6.jpg)

Expected behavior, it generating a bunch of data according to parameters

**Comment by mirasrael** [comment]
I fixed original issue (NRE), but now it fails with constitution related errors:
On first attempt: "Failed to ratify constitution." (Constitution.State == Removed instead of Active).
and then on other attempts:
"Failed to start election creating the Constitutional Amendment 1: No article in constitution providing this ability.."
"Failed to start election creating the Constitutional Amendment 2: No article in constitution providing this ability.."
I guess new issue should be created for Civics team.
