### ISSUE TITLE
Housing value calculation misleading for 0 residents

### ISSUE THREAD

**Issue by Skasi** [StrangeLoopGames/EcoIssues#20979]
###### Desired behavior:
The housing value shown for a deed should always assume at least a single resident to prevent confusion among players.

###### Current behavior:
To clarify, since 0.9.2.4 (according to https://github.com/StrangeLoopGames/EcoIssues/issues/20296#issuecomment-772978853) there exists the following formula to calculate room penalty:
Assuming `n` is the number of residents. The first `n` rooms of each type give 100% of their house value. The following rooms `n+1`, `n+2`, `n+3`, ... would then get a penalty of 50%, 75%, 87.5%, ...

The problem is that when n = 0, there are 0 rooms with 100% and the first room already gets the penalty of 50% and the second room a penalty of 75%, etc. This is not communicated in the UI and makes it hard to compare different houses with and without residents.

###### Idea:
I suggest that the code which was implemented in the above mentioned issue sets `n` to at least 1, as in `n = Math.max(1, n)`

###### Screenshots showing current behavior for 0 and 1 residents:
![Example screenshot showing the difference between a deed with 0 and 1 residents](https://user-images.githubusercontent.com/132906/111467834-32c14a00-8725-11eb-8159-f0c2556456c9.png)

**Comment by TwixterZ** [comment]
@Skasi thank you for your report, I can confirm your report is accurate, 

tested in 9.2.4 beta release-156
room calculation without any residence is halved by default for some reason

Steps to reproduce : 
1. Spawn 2 separate buildings on unclaimed land. (QA/Admin command used : "/bt 3,10,4,5"
2. Claim both buildings under 2 separate land claim (do not become resident for any of these yet)
3. Insert furniture (Tested by adding "Wooden Fabric Bed" + "Couch" + "Large Rug")
4. Observe "Housing Points" calculation for both rooms
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/d4f2ade1-7b62-46f2-9dab-c91934ae50e5)
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/a857748c-76a0-4c22-a11d-f84182802d3e)
_nobody is residence on both properties, however total housing points are showing as 4 instead of 8 (Bed(4) + Couch (2) + Large Rug (2))_
4. Become Resident on either one of property
5. Observe "Housing Points" calculation for property with resident
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/f9411dd6-90ff-476d-8308-1c75ab2317ef)
_Housing Value is now showing correctly._
6. The same tested with multiple residence on same property, occupancy penalty is showing correctly.
![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/5519f427-f6ad-4696-9472-34382afa16d4)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008.

0 resident rooms now calculate housing value properly.

Closing as fixed.


![image](https://user-images.githubusercontent.com/77248866/120853948-fd532c80-c5ae-11eb-9353-df9bb4a304a9.png)
