### ISSUE TITLE
Animations can be cancelled to speed work up 2 to 3 times

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#21068]
Typically to mine a block, you click and hold for X milliseconds and after the animation has completed the block you're targeting is broken. 

You can 'cancel' the animation by doing a  X/2 millisecond click and releasing early. This causes the animation to stop early, but the block you are targeting still breaks

Works with all tools.

**Comment by TwixterZ** [comment]
Adding couple of video reference 

Axe:
https://gyazo.com/4608f75d380f66e5ffac740bab63980b

Pickaxe:
https://gyazo.com/33c472f46ef53edf611150b15322e022

**Comment by Quadbro** [comment]
Fixed animation controller for all tools (exept hammer) to support holding properly without exploits

**Comment by SlayksWood** [comment]
@D3nnis3n In fact, I investigated this issue for a very long time. And I don't think it looks like exploit. I would say here you can use the player's skill to mine/chop faster.
@TwixterZ You video is wrong, with such animation you didn't hit tree, of course you have animation of wood chips, but in fact tree don't get any damage. 
The first time I tried using this in 8.3. I tried to create a macro to my mouse to exploit it. I calculated the ideal timings and made a macro to save as much time as possible but I almost did not get any advantage. Why? because we have ping and sometimes small lags, so sometimes of any reason the hit is not complete yet. Therefore, automation did not help me much in this.
Of course, having some experience, I can use it more clearly by myself, but again I am a human and sitting and chopping 20-30 trees in a row with such an exploit is not an easy task.

To clarify the situation a little. From my long observations, I realized that the tree takes damage only when the player receives (or does not receive) experience. Therefore I can say that this exploit is still exist, but I'd say It is harder to use it now. Or maybe I forgot how it was used in 9.3 and earlier. Earlier, too, no 2 times or even 3 times there was not

At the moment, I can speed up the mining. Here's an experience for you to compare. On the left I cut with interruptions, on the right I cut by holding the button:
![image](https://user-images.githubusercontent.com/45708377/119127458-071c5200-ba3d-11eb-875c-7fd3068cd7e1.png)

But I can give another example where I miss one hit and spend more time (3rd):
![image](https://user-images.githubusercontent.com/45708377/119127643-3f239500-ba3d-11eb-87a2-392006c4fbb7.png)
As you can see I tried to do it faster but for these reason I miss one hit.

I'd say this issue is not a big problem, that slightly encourages more skillful players, however, without using any automation (which I think is a completely different problem) in this mode you will not chop for a long time.

@D3nnis3n @WeaselDog @johnkslg need you opinions to decide what to do with this issue.

**Comment by D3nnis3n** [comment]
I'm confused.

So there is a fix to it, and another fix to it.
And there is Kirill saying it's not really a problem, despite I have seen the original exploit in use which made mining indeed three times faster.

In general:
1. I don't think we want Eco to be based on peoples skill to click buttons in a timely manner, which can be abused with a macro. That's no "skill", that's just fishy.
2. If the issue after the first fix indeed is no longer allowing up to three times the mining speed - which before it indeed did, I saw it - then the issue might not be worth fixing - but there was a second fix made already.

So I have no idea whats the state. There is an issue I saw and found too OP, Kirill that says the issue never was that OP (or is no longer after first fix?) and a second fix made.

So I'll keep it at my above comment. TL;DR: If it does no longer actually allow you to mine at least double as fast, it might not be worth fixing, if it does, it should, as Eco shouldnt be about 'click-skill' or macros.

**Comment by Quadbro** [comment]
Currently you shouln't be able to mine faster with your personal click skills or macro (after fixes)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging.

Players are now unable to skip or cancel the animation as reported here.
Once you click LMB regardless of whatever tool you are using, the animation will play through.
However, I am reopening this ticket as you can still perform switching between similar tools to cut the animation off and perform a faster action.

I've made a comparison video below to showcase the issue of switching:

https://user-images.githubusercontent.com/77248866/119653463-f19e9200-be59-11eb-8bc0-a6644238d9d0.mp4

#### Reproduction Steps
1. Have similar tools next to each other on active tools such as Steel Pickaxe and Iron Pickaxe.
2. Select one and start mining.
3. The moment that the rock you are mining on step 2 changes form and becomes harvestable, switch to the other tool mentioned in step 1.
4. Start mining.
5. Perform step 3.
6. Perform step 4.
7. Keep repeating this process.
8. Observe.

#### Actual Result
You increase mining speed by 10%. It could be more once you mastered this process.

#### Expected Result
Prevent active tool switching until the animation triggered by the players action is complete.

**Comment by Daniel-Magulado** [comment]
Retested on 0.9.4 Staging-1993.

I can still reproduce the trick for switching tools to increase mining speed by about 10% or so.
Attaching a new video where I changed the video for 1992 to a 1993 record.


https://user-images.githubusercontent.com/77248866/119818524-e9118e80-bf21-11eb-9161-0e445f36dc0f.mp4

**Comment by SlayksWood** [comment]
Seems last fix not change anything
(8,24-7,24)/100 = 0,146... almost 15% with a chance to miss. I'd close it. @WeaselDog @johnkslg 
@D3nnis3n Could it be that in addition to this, something else was involved in this exploit? I heard about this from some players, but only due to the animation, it does not win 2/3 times.

**Comment by D3nnis3n** [comment]
But Daniel confirmed its fixed?

**Comment by Daniel-Magulado** [comment]
@D3nnis3n 

Ah no, I reopened it for the reason that I can still cut animation to speed up mining by 10% to 15% as shown on the latest video above. 
I can do so by switching between the same tools of different tiers such as alternating between Iron Pickaxe and Steel Pickaxe.

**Comment by D3nnis3n** [comment]
But Kirill said the original exploit still works. Can someone please
clarify what works and what doesnt, lol.

**Comment by SlayksWood** [comment]
@D3nnis3n I deleted my comment when I realized that I had accidentally tested on the wrong version.
Seems exploit was fixed, but have a small flaw. I create a new issue for it #22043
@Daniel-Magulado Can you test it too to confim fixes.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1997.

Switching between similar tools doesn't work anymore to increase speed. Tested on all mining hand tools.

Closing as all exploits are fixed.
