### ISSUE TITLE
[0.9.3.0 staging-1967] Ecopedia Images Text Overlapping

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21190]
After updates to Ecopedia for localization, many of the entries have overlapping text and can't be read. We need to figure out why and get it fixed for 9.3

This is the **Deed Sales Component**:
![DeedSalesComponent](https://user-images.githubusercontent.com/47330823/113062838-3f07c700-9169-11eb-8c10-20f9e7986c15.png)

**Comment by WeaselDog** [comment]
@RobertMangano We need the images with no text adding back in

**Comment by RobertMangano** [comment]
the images still contained numbers so only text was removed

**Comment by RobertMangano** [comment]
removed all text and numbers from all ecopedia images these have been checked into staging.

**Comment by IcedForge** [comment]
Need to make sure these changes is brought into release svn as we  still see a bunch of images with double overlay with gibberish at least running .

**Comment by IcedForge** [comment]
a few examples ( 9.3 release branch )
![image.png](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f824b63f-9ab6-4f41-b267-7d74b97da87e)

![image.png](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/0a1d275d-0786-4c4a-8b47-25134e17cfef)

![image.png](https://images.zenhubusercontent.com/5f5a7fa59878ed957a861886/f57bdf36-ccb9-4340-bb9e-6cc2e738c520)

**Comment by WeaselDog** [comment]
@RobertMangano Looks like the headers we missed

**Comment by WeaselDog** [comment]
Ecopedia is fixed in English, but please check for overlap in other languages.

**Comment by RobertMangano** [comment]
checked in headers without text or numbers on develop as requested.

**Comment by SlayksWood** [comment]
0.9.3 Release-186 Still have overlaps even in English:
![image](https://user-images.githubusercontent.com/45708377/114363279-e8df4e80-9b80-11eb-8419-6128eb6353c9.png)
![image](https://user-images.githubusercontent.com/45708377/114363319-f1d02000-9b80-11eb-8af5-dcf7a0e347b6.png)
![image](https://user-images.githubusercontent.com/45708377/114363393-01e7ff80-9b81-11eb-8bd5-477ba350e3f3.png)
![image](https://user-images.githubusercontent.com/45708377/114363438-10ceb200-9b81-11eb-978a-f4b4017b8532.png)
I will start a new build to update SVN, because 186 was build a day ago.

**Comment by SlayksWood** [comment]
Still have 1 problem in English in release-187:
![image](https://user-images.githubusercontent.com/45708377/114392228-281d9780-9ba1-11eb-9e0a-1f20d4eb9108.png)

And one overlap in Russian:
![image](https://user-images.githubusercontent.com/45708377/114392104-ff959d80-9ba0-11eb-8cf0-74f3de829044.png)
But it happen because the text is longer in russian.
![image](https://user-images.githubusercontent.com/45708377/114392171-11774080-9ba1-11eb-8c3f-064ab981785c.png)

**Comment by Daniel-Magulado** [comment]
Update with 9.3 Release-194

A few more overlapping images found in Contract, Research, and Data.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/e6badf2c-71fc-4cb4-8be3-e0e87c348241)

While sometext has become quite difficult to read such as the Default Currency found on Taxes Entry,

**Comment by Daniel-Magulado** [comment]
Also related #21365

**Comment by Daniel-Magulado** [comment]
Checked Ecopedia all pages from Getting Started to Eco Development. Tested on 0.9.3.1 Release-204
Couldn't find any text/image overlapping but #21365 is still there.
Closing this ticket.

**Comment by WeaselDog** [comment]
It is back in many places on develop

**Comment by WeaselDog** [comment]
The text is back on staging. Please fix images and double check afterwards but opening pages in the Ecopedia.

**Comment by RobertMangano** [comment]
added images without text back to staging
