### ISSUE TITLE
[0.9.2.4] Ingredients display too many Talent Benefits

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoIssues#21204]
If you hover over inputs for a recipe in a table, you see the list of Talent Benefits that should apply to that ingredient. However, it seems that all the Talent Benefits display instead:

![image](https://user-images.githubusercontent.com/964559/113120921-f0891580-91c6-11eb-9dfd-54d42bde6325.png)

So instead of seeing Lavish Workspace Butchery for carcases, I see things like Lavish Workspace Composites, etc.

**Comment by SlayksWood** [comment]
- [ ] 1. Still have a problem here. I have 3 specialty with Lavish Workspace talent and in some recipes I have 2 benefits instead of 1. More I have different benifits for different ingredients in one recipe.

Step to reproduce:
- take levelup Carpentry, Pottery and Glassworking and take talents Lavish Workspace:
![image](https://user-images.githubusercontent.com/45708377/117103872-d3c29d80-ad83-11eb-88a2-670c4fc15a17.png)
but 
![image](https://user-images.githubusercontent.com/45708377/117103892-dd4c0580-ad83-11eb-8de6-39380ec563e5.png)
![image](https://user-images.githubusercontent.com/45708377/117103904-e2a95000-ad83-11eb-99c7-555c801b2328.png)

- [ ] 2. If you don't have any Talents benefits need to hide it in tooltip:
![image](https://user-images.githubusercontent.com/45708377/117104169-5a777a80-ad84-11eb-99c0-f6c93385ce5c.png)

**Comment by Mattprass** [comment]
The first is intentional, as the iron bar ingredient is indeed used in both carpentry and pottery. Not sure how that is an issue? The original issue is on per ingredient basis, so some ingredients will have multiple talent benefits because they're used in multiple areas, all relating to what the user has as a talent. It should also be noted that the reason for the original issue is because the tooltip was for a tag, and there wasn't support for tag->talent when building the tooltip. Wood is also part of carpentry.

The second issue I can do though

**Comment by SlayksWood** [comment]
@Mattprass This is still not entirely correct, but I understand why it is implemented this way. theoretically player can have 28 specialties and some item that is used in 10 of them and there will be 10 benefits in tooltip. Closed for now.

**Comment by ThePiachu** [comment]
Ideally the talent benefits would only display the talents relevant to a given recipe if it's taken from that recipe, but all talents if it's accessed from elsewhere. But yeah, that might be a bit complicated one way or the other.
