### ISSUE TITLE
Chopping Trees on the edge of the claims Bug

### ISSUE THREAD

**Issue by krashiel** [StrangeLoopGames/EcoIssues#21269]
When **chopping a tree on claimed land** if the tree **falls on someone else's claim** you **can chop the tree and loot it as long as you don't chop the stomp, if u chop the stomp then you can still cut the fallen tree on his land but u are not authorized to loot it**.
Something is not working as intended but only you guys know the intention of it. 
**One important thing to mention, I tried this with an "old" huge tree. Didn't have the opportunity to try it with normal trees also.**

**In my opinion it's not fair** that if my tree falls on someone else's claim i'm no longer able to get it because it's pretty hard to control the way a tree falls when u cut it. I tried many times many ways but never falls as intended and **because of the collision sometimes tree jumps like a football**. Not to mention that **i was thrown off the planet**(200height+) while simply touching a piece of fresh chopped wood :D.

If explanation in words might get confusing the image explains clear so i went for this aproach too :) 
![image](https://user-images.githubusercontent.com/9423653/113732142-01271780-9702-11eb-9663-1a467cb6b625.png)

**Comment by Daniel-Magulado** [comment]
Hi, thank you for submitting a report about this.
I can confirm that this issue is happening and can be reproduced.

Tested on both 0.9.2.4 Release-156 and 0.9.3 Release-184.

Repro:

1. Chop a tree and ensure that it will fall on someone else's property.
2. Remove the stomp.
3. Try to chop the fallen tree and retrieve its logs.
4. Observe.

Video Repro:
https://images.zenhubusercontent.com/47210472/aa1f7f5a-2ca0-48f2-b71b-b9b32af60e14/ddss.mp4

Screenshot:
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/bb01f276-a187-4768-ae76-df0408fac420)

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6 release
