### ISSUE TITLE
[Clothingh Polish] Tints on hats that already have darker colors doesn't look or feel good

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21290]
- [ ] 1. Bandana:
![image](https://user-images.githubusercontent.com/45708377/113835378-94109200-9794-11eb-85b4-0ac69041acba.png)
![image](https://user-images.githubusercontent.com/45708377/113835526-b86c6e80-9794-11eb-997e-e3231fcc7657.png)
It's darker than it should be. Seems it's regression, because here #15468 you can see that bandana has the same color like Derpy hat.

- [ ] 2. Tailor Bowler Hat:
![image](https://user-images.githubusercontent.com/45708377/113843771-8ced8200-979c-11eb-808a-f717e022a85d.png)

- [ ] 3. Smith bandana:
![image](https://user-images.githubusercontent.com/45708377/113845962-b14a5e00-979e-11eb-98de-b8a0b1aaead2.png)

- [ ] 4. Alpha hat too:
![image](https://user-images.githubusercontent.com/45708377/113841756-b73e4000-979a-11eb-844c-f3a12ea14a0c.png)
This hat has always been like this, but maybe this is also a bug?

**Comment by Daniel-Magulado** [comment]
Build: 0.9.3.1 Release-204

Additionally, Hats don't change color at all as most clothes would. If you select the color white, Hats simply gets a brighter Tint of its original color. Except for Farmer Hat, Builder Helmet, and Derpy Hat.

Screenshot: 
![image](https://user-images.githubusercontent.com/77248866/115110902-30664000-9fb0-11eb-8f78-bfa458477771.png)

Do note that all of the headgear shown on the image has the color set to White.

**Comment by keegan-o** [comment]
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/5da697e5-faa6-4745-b680-754225b732e8)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/5d8d4f6c-aa28-47c2-a533-729c87fd2cc0)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/d93f5158-6bbb-47b3-b9b1-7777f90ca2d1)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/0d719144-119b-4887-a945-78a3edaf3f00)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/7b945ae2-9f6c-47a3-b94d-1faf7fb4b7a5)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/f0af1eed-2e0d-4a51-8196-832ae98b2bce)

All the new hats are fixed in develop branch as of 5/13/21, we will get fixes for the alpha hat and derpy hat as well. Wolf whisper might stay as is, not really designed to tint the fur.

**Comment by keegan-o** [comment]
Actually managed to fix these ones with just the texture, others had to be split between hair and hat avatar parts
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/9e558f0a-ae01-4612-9513-1bd4a4fb22cf)
![image.png](https://images.zenhubusercontent.com/5ee003d5cfaa7fb4ca69f828/8103d749-8d28-4a1e-a824-907b190a1f9a)
