### ISSUE TITLE
[9.4 Develop 252] Failed to handle RPC method: XPEffect 

### ISSUE THREAD

**Issue by TwixterZ** [StrangeLoopGames/EcoIssues#21362]
Issue arises when trying to plow 2 area of dirt continuously  

https://images.zenhubusercontent.com/47210472/b1af364e-8eb3-44fd-a24b-a342cdc9f384/9_4_rpc_xpeffect_2.mp4

Below error recorded on log (repeated multiple times) :
(Filename: currently not available on il2cpp Line: -1)

ArgumentNullException: Value cannot be null.
Parameter name: uriString
  at System.Uri..ctor (System.String uriString) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.LoginUser (System.String serverUri, System.String accountIdUri, System.String vivoxAccessToken) [0x00000] in <00000000000000000000000000000000>:0 
  at VoiceManager.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by madpingui** [comment]
I was investigating the problem and why it was regression, but it turns out that in staging a fix had been made by Sergey in this PR https://github.com/StrangeLoopGames/Eco/pull/8176, but because its staging it didn't applied to develop, he changed the way we got the skills.

From getting the skill (only discovered ones)
![image](https://user-images.githubusercontent.com/68016784/117190974-ab4b9b00-ada5-11eb-834b-3e76a0baf3df.png)
To getting the tree (even if its not discovered)
![image](https://user-images.githubusercontent.com/68016784/117191083-c8806980-ada5-11eb-8b11-25808f9d9584.png)

Thats why the hoe was giving the Exception because the specialty Farming wasn't discovered yet.

**Comment by IcedForge** [comment]
This is still happening after staging > dev merge 
If farming is not yet unlocked/discovered AND you are trying to till a plot that is already tilled

**Comment by madpingui** [comment]
This is not happening for me in staging branch, tested on editor.
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/7da8d618-1956-4ff1-bfc9-189fabf517fe)

**Comment by madpingui** [comment]
Staging branch
https://drive.google.com/file/d/1xZSHrU439d_LJ26eHKQOGorpFL9e9Cu7/view?usp=sharing

**Comment by TwixterZ** [comment]
fix tested and confirm as of 9.4 Staging 1986

**Comment by TwixterZ** [comment]
Issue is re-open as still having this RPC error notification when trying to till a plot that is already tilled.

![image](https://user-images.githubusercontent.com/78054747/118818584-1093a600-b8e7-11eb-954f-6f95f6418b0d.png)

**Comment by SlayksWood** [comment]
fixed.
