### ISSUE TITLE
Sewage output pipe disappearing and general pipe issues

### ISSUE THREAD

**Issue by Tbear1825** [StrangeLoopGames/EcoIssues#21388]
After a run of items in the blast furnace and the sewage pipe is no longer spewing sewage the last pipe will disappear.  It seems to only occur once the run is done.  

If you run a long smelting run the pipe is good until the run is complete and the sewage output pipe is no longer in use, then it removes the last pipe.

If you have it set up to run as the concentrate trickles in it will remove a pipe each time an ore is processed and the sewage output pipe is no longer in use.  This is the very costly process as it completely deletes the pipe as well.  

I also had an issue with a "ghost" pipe on the smog output of one of my two blast furnaces.  It appeared as if there was no pipe connected to the smog output.  When trying to place a pipe it would not let me.  Also with the blast furnace being in a room this voided my room as there was a hole in the ceiling.  When trying to connect a pipe it would not allow me to.  I was also unable to place a block in that space as well.  It acted as though there was a piece there but it was not visible.

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this.
We're currently aware of the pipes disappearing as well as ghost pipes.
A quick fix where you can connect a Pipe to output is to take the Blast Furnace and place it again.
This issue is mostly caused when an output source is turned ON.
Merging with #21366 and closing this.
