### ISSUE TITLE
USER ISSUE: Construction tool

### ISSUE THREAD

**Issue by RaphaelBalse** [StrangeLoopGames/EcoIssues#21403]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.0 beta release-194

**Steps to Reproduce:**
1. take hammer and a block2. Press F for select line3. Try to make a line

**Expected behavior:**
Make a line

**Actual behavior:**
Loose line and make a block

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@RaphaelBalse Thank you for the report.
Need some information to clarify it:
1. How much construction block do you have in hands when try to build with hammer?
You can't build with line if you have only 1 blocks. So the behaviour should be:
- you take 10 bricks.
- select line.
- place 9 bricks. Line will be changed to Point, because you can't build line with 1 block. 
- take 19 bricks from stockpile. Point should be changed to Line again.

2. If you have another behavior please describe it more. Also don't forget to provide log file when you have this problem next time. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

3. Provide PC specification (include operating system and its version)

**Comment by RaphaelBalse** [comment]
It's ok
