### ISSUE TITLE
[0.9.3.1 Release-204]Cotton can grow on any soil with yield

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21440]
Build: 0.9.3.1 Release-204

## Issue
Cotton apparently can grow on any soil. Furthermore, it reaches 100% maturity with yield. This is despite Soil Sampler saying 0% compatibility and inhospitable environment. Possibly related to #21415

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/e5b071d0-c8ac-4d2c-aa04-46ac025d7ec5)
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/c507dbeb-c9e7-44c6-95ae-2dfe4c39cc77)
![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/63ca7a40-7d29-4dbd-8b86-ba678b7eae88)

**Comment by WeaselDog** [comment]
Could not replicate on my branch. Possibly fixed with linked PR:
![DeadCotton](https://user-images.githubusercontent.com/47330823/118086994-af655300-b379-11eb-82a9-b343bf635369.png)

**Comment by SlayksWood** [comment]
Fixed in 0.9.4 develop-285
![image](https://user-images.githubusercontent.com/45708377/118239943-0e72b700-b4a3-11eb-8c76-954ec347ae37.png)
![image](https://user-images.githubusercontent.com/45708377/118240003-21858700-b4a3-11eb-99d2-638270ecf49d.png)
![image](https://user-images.githubusercontent.com/45708377/118240483-bd16f780-b4a3-11eb-90e0-338f54db54ff.png)
