### ISSUE TITLE
[0.9.3 release] Tutorial should automatically continue.

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21552]
After completing a step of the tutorial, the tutorial does not automatically continue to the next step. Right now, the player must enable the cursor and click the top left of the screen after completing each step. This is a problem because it is inconvenient, but more importantly new players will not always know to do this.

Most of the tutorial has a clear linear progression. Completing steps in a tutorial task should transition into the next step that follows this. If all steps in a tutorial task are complete, the next task at the top of the list should be automatically selected.

**How screen looks after completing first task:**
![StalledTutorial](https://user-images.githubusercontent.com/47330823/115940023-f506be00-a454-11eb-89ca-4aac38e7811a.png)

**How it should look:**
![TaskSelected](https://user-images.githubusercontent.com/47330823/115940048-08b22480-a455-11eb-9224-850ed3e830a4.png)

**Comment by johnkslg** [comment]
This was the original design decision, to let them 'proceed at their own pace'.  Perhaps we give this change a try though: if a tutorial completes and there's any pending, it opens the next one automatically.  They can always close them.

Meteor tutorial is a tricky one because you might not be able to do it for a couple minutes while the meteor moves around the world, but maybe that's ok.
