### ISSUE TITLE
[0.9.3.1 beta release-204] Escrow account missing funds for work party

### ISSUE THREAD

**Issue by Dave247** [StrangeLoopGames/EcoIssues#21623]
I had a strange thing happen where I started a work party for someone else where the money was set to pay as you go, and due to requiring a lot of labour it took the contractor two goes to complete it. The full amount was taken out of my account into Escrow and the client was paid for the first chunk of labour, but for some reason it failed on the second amount stating there wasn't enough money in the account, when looking at the screenshot you can see from the account and error message there clearly was.
![20210429003250_1](https://user-images.githubusercontent.com/10183015/116422950-9477e680-a883-11eb-97bc-19288cb25e42.jpg)

I have also included a screenshot of the work party itself for reproduction purposes.
![20210429004003_1](https://user-images.githubusercontent.com/10183015/116422963-980b6d80-a883-11eb-8381-780fea363a10.jpg)

**Comment by IcedForge** [comment]
Thank you for reporting.

This should be fixed with the changes and fixes in the recent hotfix (9.3.3) as there was an exploit to get money out of the escrow account. Please reopen or make a new issue if this happens in your next fresh cycle ( as there may still be some "bad" contracts affecting you on your current world)
