### ISSUE TITLE
World markers created for tutorials like campsite and workbench can just be the icon

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21659]
![image](https://user-images.githubusercontent.com/3536496/116597289-4b9f4c80-a8da-11eb-9428-de3a9acb744d.png)
Remove the text, it blocks stuff.  

Also, lets make the marker omit the circle in this case:
![image](https://user-images.githubusercontent.com/3536496/116597324-5954d200-a8da-11eb-9c10-4adf4c867b36.png)
It can be the campsite icon with the little arrow under it.

**Comment by gzatravkin** [comment]
Check if new sprite is needed (little arrow)

**Comment by SlayksWood** [comment]
The issue was not fixed by description. But it's pretty good, It realease something that we already discussed #20058.
So we have issue how to improve this, so I closed this one.
One issue that it only works with smallest minimap, if you place your minimap like here it will not work:
![image](https://user-images.githubusercontent.com/45708377/119609476-4f05f500-be00-11eb-8985-b41df78ea50b.png)
