### ISSUE TITLE
Add a subtle sound for mousing over a button when it highlights

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21666]
Should apply to the button prefabs to ensure all buttons get it, if they are the 'highlighting' type.  Can also use Grigori's 'fixup' system if needed.

**Comment by gzatravkin** [comment]
Another possilbe solution which wouldn't include to add script to every button: 

Detect which element is highligted now and play sound if needed. You can detect it by raycasting mouse position. The same goes for "interactable" cursor: instead of putting script to every component you can just detect if there are some button at cursor position. 
But both solutions are fine I guess.

**Comment by madpingui** [comment]
I was investigating that there are several components to add sounds such as SpawnPrefab and AutoSoundSubscriberUI, but it turns out that having made this overfix of the buttons (https://github.com/StrangeLoopGames/Eco/pull/8377).
![image](https://user-images.githubusercontent.com/68016784/117327826-a4319500-ae58-11eb-9537-4591085f8df4.png)
This same component includes the use of sounds when hovering over the UI that contains the component, so that PR directly fix this issue.
![image](https://user-images.githubusercontent.com/68016784/117327980-ca573500-ae58-11eb-82d3-03eb9890ac5f.png)
