### ISSUE TITLE
Make fill-type something you unlock with higher level tools

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21671]
![image](https://user-images.githubusercontent.com/3536496/116602191-3cbb9880-a8e0-11eb-8649-28967aaa6ce5.png)
Hide it altogether for basic hammer.  Make each version of hammer add some more. 

Also, make this wider so the whole thing can be shown in a single line. Move it to the top right too and make it mirror the form.

**Comment by IcedForge** [comment]
Would also like to overfix this by making it also base block shapes with hammer tiers.

**Comment by keegan-o** [comment]
Please don't move it to the top right, that area is reserved for the material selection I still want to have usable for any building tool we decide we want to put it on, once it is added to the game in more places like the crane.

**Comment by keegan-o** [comment]
I also think this is unfortunate in general, and that all the basic shapes should be done with the lowest tier hammers-- the things to unlock should be specialized forms like framed boxes (where you drag it out and get just the frame around the box you made) and other things we have yet to add. Splitting up and spreading out the existing forms will effectively mean just reducing power to build very very simple things like a floor, which you want for your very first building often. Placing blocks one by one for a large floor is not really what I want to add to initial game grind.

**Comment by keegan-o** [comment]
Here's examples of fill types we could add to steel hammer + or wherever, if we wanted to grant power to make progression:
- Dashed Line (fills in every other space in defined line, useful for making alternating windows/walls)
- 1/2 Sloped Line (place stairs or slanted roofs going up or down just like that!)
- 1/2 Sloped Wall (make roof building so much easier)
- Frame Floor (fills in the edge lines of defined floor)
- Frame Wall (fills in the edge lines of defined wall)
- Floor Box (fills in the tops and bottom of defined box, useful for making two floors at once in buildings)
- Wall Box (fills in only vertical walls of defined box)
- Hollow Box
- Frame Box (just fills in the outside lines of a defined box)

**Comment by SlayksWood** [comment]
@WeaselDog I wouldn't change that so drastically either. The players are already used to it. If we had introduced this at the start of 9.0 or at least 9.1 But by the release of 9.4 we will have almost a year since the release of 9.0.
So no needs to leave only 1 fill type for stone Hammer.
So my suggestion is:

Stone hammer - point and line. We leave a good filling option to the hammer to avoid the negative and returning to 8.3. However, we show that it is better to use a better hammer.

Iron hammer - Point, line, Rectangle, Floor (and maybe Wall 2 Point and Wall 3 Point). A hammer that supports almost all of the current functionality.

Steel and modern hammers - all available forms for now. The difference between the two ones and the iron hammer could be added in the future in the form of new fill types, as @Keegan wrote.

**Comment by WeaselDog** [comment]
Please create a follow up issue to adjust for balance if the filtypes should be adjusted. This issue can be closed if the feature works as intended.
