### ISSUE TITLE
Declunkify: Improve machete

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21693]
- Make it obtained early (workbench probably)
- When its swung, destroy most plants in the region in front of the player, without having to individually target them.  
- Smaller plants like grass should still need targeting.

**Comment by IcedForge** [comment]
The stone machete is obtained via the tool bench which is mandatory first or second item crafted for repairs and other tool crafts such as first bow, sickle etc so this should be fine where its at we might need to look at calorie consumption and efficiency a bit closer though as i rarely use it myself since i can use a sickle instead and get plant fiber for mortar and so on making it feel like a redundant item.

**Comment by WeaselDog** [comment]
It is crafted the same time as other tools. Passing this to Otter to handle the mechanics of swinging.
