### ISSUE TITLE
[0.9.3.3 Release-219] Tutorial tooltip window not showing after completing Controls on super ultrawide resolution

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#21734]
Build: 0.9.3.3 Release-219

## Issue
Tutorial window tooltip not showing after completing the Controls tutorial when monitor display is set to 32:9 resolution and above.
Tested on: 5120x1440 resolution and 5120x1080 resolution.

https://user-images.githubusercontent.com/77248866/116830925-231b9900-abdf-11eb-8d6a-fa4a72b9566e.mp4

**Comment by SlayksWood** [comment]
This is issue fixed in 0.9.4 develop #20252. I don't have any problem:
![image](https://user-images.githubusercontent.com/45708377/116881881-7962f900-ac2c-11eb-9f7a-6bef84b4a1b7.png)
![image](https://user-images.githubusercontent.com/45708377/116881910-7ff17080-ac2c-11eb-95da-70e2b7ce08f0.png)
![image](https://user-images.githubusercontent.com/45708377/116881937-87b11500-ac2c-11eb-955c-85cb8743d659.png)
