### ISSUE TITLE
USER ISSUE: Invisible object in the middle of the road

### ISSUE THREAD

**Issue by butterhahn** [StrangeLoopGames/EcoIssues#21810]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.4 beta release-226

**Steps to Reproduce:**
Not sure.
It's a stone ramp and causes collision with a truck if you want to drive over it. The other stone ramps to the left and right are ok (6 wide road). No collision on foot. Removing and replacing object didnt help. Building a pile of dirt on the area and removing it again also doesn't help. Restarting the server shows also no effect.	

**Expected behavior:**
No collision with invisible object	

**Actual behavior:**
Collision with invisible object

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi, thank you for making a report about this. We received similar reports where objects become invisible. However, restarting usually fixes this issue. Since yours did not, we would like to request more information.

Kindly provide us your game logs. Preferably, fresh game logs. To get fresh game logs: start the game, proceed to the area where the invisible object is located, and try various actions to interact with it such as collision or hitting it with various tools.
Once done, please provide your game logs. To upload game logs, please follow the instructions here:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

A recorded video of the issue would also be helpful so we can narrow the possible causes.

Thank you.

**Comment by MishkaFur** [comment]
@Daniel-Magulado I also have a few of these on my server though only one is constant (persisting through reboot) its just above a asphalt ramp in the desert.

Will try to get video of it from my server
