### ISSUE TITLE
[0.9.4 develop-282] Missing shadowplacement for logs and rubbles

### ISSUE THREAD

**Issue by SlayksWood** [StrangeLoopGames/EcoIssues#21843]
maybe something else. Step to reproduce:
- /give sandstone, you have shadowplacement
![image](https://user-images.githubusercontent.com/45708377/117783232-07516c00-b24b-11eb-997a-608fb5e53eb8.png)
- place and pick up it, shadowplacement is missing:
![image](https://user-images.githubusercontent.com/45708377/117783286-11736a80-b24b-11eb-9dca-79cf84f60061.png)
So it's missing every time when you pick up rubbles/logs.

**Comment by SlayksWood** [comment]
Still have some regression compare to 9.3 with shadowplacement. Step to reproduce:
- take 2 rubble or log, place one of them:
![image](https://user-images.githubusercontent.com/45708377/119644368-73c09380-be25-11eb-9956-df00b5b3cee9.png)
- move mouse a little left you have 2 shadowplacent now:
![image](https://user-images.githubusercontent.com/45708377/119644427-85a23680-be25-11eb-9787-3648eee2a790.png)
![2021 05 26 Double shadowplacement](https://user-images.githubusercontent.com/45708377/119645543-cd758d80-be26-11eb-86a1-cc6231459621.gif)

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-1995.
Still has regression.
Extensively tested including logs, concrete, corrugates steel, and bricks.

When stacked together, the shadowplacement ends up being confused and flickers in different positions during placement of the 6th, 10th, and 12th piece. Could be more but same issue.

To reproduce, simply stack up together either rocks, woods, or construction materials.
On the 6th piece, observe before placing.


https://user-images.githubusercontent.com/77248866/120110966-79f69d00-c1a2-11eb-9ac3-d45e07ad7b0e.mp4


https://user-images.githubusercontent.com/77248866/120110968-7ebb5100-c1a2-11eb-94ed-ac1c4c1d8e23.mp4

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2020

Reopening as there still some kind of glitch and flicker happening.

1. There's a flicker of the shadow placement to a location where it should not be since I'm not even pointing at that location.


https://user-images.githubusercontent.com/77248866/121968614-38badb80-cda5-11eb-9126-0ab9d225b8a4.mp4

To reproduce, stack 5 construction materials. On the 6th one, hover the mouse around the area where the 6th stack will be placed and observe the behavior of the shadowplacement.



2. If pointed exactly in the middle of the stacked blocks, the shadowplacement places the blocks outside of the stack and infront of the stack which should not be happening.



https://user-images.githubusercontent.com/77248866/121968685-54be7d00-cda5-11eb-8804-0ee8abb60065.mp4

To reproduce, stack 5 construction materials and for the 6th one, aim the mouse in the middle of the 5th, 4th, and 3rd stack.



Both issues are not happening for the 3rd stack which is the correct behavior.

**Comment by SlayksWood** [comment]
Looks like it has 2 shadowplacements:
![image](https://user-images.githubusercontent.com/45708377/122030614-9a476e00-cdd6-11eb-9c80-a17c3e553286.png)

**Comment by Jason-Skillman** [comment]
I investigated the two shadow placement issue and it seems to just be with the lumber. The shadow placement that is being shown is the next stack to be placed which would be `LumberStacked2` mesh. In `LumberStacked1` the lumber does not 100% overlap the one in `LumberStacked2` so it looks a little offset.

Same example but with the logs. In this example `LogStacked3` is currently placed but the shadow placement is showing `LogStacked4`.
<img width="466" alt="log_example" src="https://user-images.githubusercontent.com/35405997/122578715-28636480-d022-11eb-84af-c12bdabce65a.png">
