### ISSUE TITLE
[0.9.3.5 release] Escape must close backpack

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoIssues#21990]
As a player, the expected behavior is that escape should close an open UI. This works for almost all UI except, the backpack. This is because some people prefer to play with the backpack UI open at all times.

We must go with the behavior that is most intuitive to the majority of players. We will create a follow up issue to allow pinning a UI so it is unimpacted by pressing escape.

**Comment by SlayksWood** [comment]
We already have this issue #20617. Is it possible to do it right away? I'm just that player who likes to run with an open backpack xD.
By the way, I would not say that I like to do this in all games, but thinking why I do this, I realized that we do not show how many free cells are in the backpack at the moment, so it's easier to keep it open.

**Comment by D3nnis3n** [comment]
I disagree with that, the feedback has clearly shown that there is a split in opinion, and ESC closing the backpack is not the majority intuitive thing. I veto this being implemented without pinning a UI at the same time. Having backpack opened all the time is pretty pevalent in Eco.

**Comment by D3nnis3n** [comment]
By the way, we already had consenus in the team to introduce this together and not switch it around until then. We should keep to that consensus.

**Comment by IcedForge** [comment]
Backpack doesn't close on ESC
#20369
#20539

Backpack is closing on ESC
#18045

Backpack doesn't open on Tab
#14453

We had a big discussion regarding this, and the consensus was we do not change this behavior until  #20617 was done.
The biggest reason for this i because as mentioned in this comment there is a massive 50/50 split down through the community where one side hates that we cannot close it with ESC the other half hates that they cannot keep it open.

I will close this issue as it was agreed that we would not change this until it was permanently fixed to allow a Player Preference to be the deciding factor in this as it is a giant game play element and we had tons of complaints on discord one way or the other so i don't see how this is a solution without an "Over fix" for the actual problem and that's an ui element that has 0 customization capacity.

**Comment by WeaselDog** [comment]
Duplicate of other issue
