### ISSUE TITLE
Declunkify: text input should be selected when opening dialogs

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#21994]
![image](https://user-images.githubusercontent.com/3536496/119740259-74aef080-be38-11eb-8515-a00176b53827.png)
I opened this dialog on the sale list of a store.  Tried to start typing.
As I typed, nothing went in the filter box, instead it opened a bunch of random UI's all over the damn place, because it was registering my typing as hotkeys.
*CLUNKINESS INTENSIFIES*

Any typing when this is open should go to the filter regardless of what is selected, and hotkeys should not work.  
(Make this as a part of the underlying UI system, dont special case it)

**Comment by SlayksWood** [comment]
I remember that this was fixed, can't find this issue. But if you observe it, when you open it, you can see that the field is activated, but after a split second it becomes inactive. If you type the text while opening, it will even appear there.

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2008

Reopening for the purpose that this should also be the same behavior when opening the Chat UI and on selected Trigger/Then clauses.

![image.png](https://images.zenhubusercontent.com/5ffb75c5aa5c9e2a1278e024/8aaf46f7-304c-40da-b28f-9b93e2c24555)

**Comment by madpingui** [comment]
The ChatUI already has the input field activated when it is opened.
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/833eb531-6ff8-457b-8df7-ea0e83f0a4fb)
If you refer to the chat log I think it should not be activated since it is used to see the log precisely, so if it were activated while one was walking with the character, it would start to write meaningless letters and the focus of the character would be lost, It seems to me that the chat log should be left like this to not frustrate the player.
(it can be changed easily but its juts a game design opinion).

In case of the law "triggers" and "then" i think there is no need for this either, since for example the case that Daniel puts, there are two bars of input fields. 
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/5f030b36-bd18-498a-9042-b85ee027fc04)
_Note: both input fields_

And in the "then" the player may want to select another of the options instead of directly writing the message.
![image.png](https://images.zenhubusercontent.com/6026e9076b870867c5685cdc/3ca2f8fa-41a4-4bcf-b66e-698481d03a8b)

I think the player is interacting with this UI directly with the mouse, so selecting an input field is not seen as a problem, and it would not be a solution to anything.

If the change is required though let me know.

**Comment by Daniel-Magulado** [comment]
Closing.
