### ISSUE TITLE
[0.9.4 Staging-1993] avatar skin color

### ISSUE THREAD

**Issue by StallEF** [StrangeLoopGames/EcoIssues#22023]
![2021-05-28](https://user-images.githubusercontent.com/26339332/120083583-4c422300-c0d2-11eb-8f7b-7f21dbd04721.png)
avatar skin color not used in info about get new profession

**Comment by Daniel-Magulado** [comment]
Hi @StallEF,

Thank you for writing a report about this.
This is actually not the normal game behavior since after you learn a specialty, the one that should show up is the specialty icon.
The only time that the profession icon appears when learning specialty is by using commands such as /creative.
I'll be merging this with #21709.

**Comment by StallEF** [comment]
@Daniel-Magulado  if server admin used command /skills reset Playername -  can see it problemp too so it in normal game too
