### ISSUE TITLE
Pull out world layer history and stats to own zip/storage

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#2202]
keep them in the same folder, just use a different filename maybe?
the gamesaves are ballooning in size, nearly 80% of this is just world layer history and the stats

stats -> move to a database
world layer history -> look into storing as a video instead of gif;

**Comment by MarjieAVolk** [comment]
I'm not sure what the advantage of this would be, as the information still has to be there.  Doing this would require changing up the way backup works, and would make users just have to zip those things into a folder anyway, since stats at least is an important part of the game save and can't just be discarded.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#373
