### ISSUE TITLE
USER ISSUE: Charcoal is unaivalble in Laws

### ISSUE THREAD

**Issue by NomarCraft** [StrangeLoopGames/EcoIssues#22137]
\
**User Id: (Not logged user)**
**Version:** 0.9.3.5 beta release-231

**Steps to Reproduce:**
Create a LawTry to find charcoal in the item list when setting up a filter/conditionOnly coal show up in the list and not charcoal
When hovering coal in the item list it appear to be refering to both charcoal and coal so we though it would work anyway

**Expected behavior:**
We create a law to tax coal trade between players as a way to prevent mass poluting by player using coal/charcoal powered vehicles/workshop.When a trade occured the law should trigger and tax the player selling the item at his store.

**Actual behavior:**
The law doesn't detect a charcoal trade (it does detect a coal trade). We tried with another item (Hewn Log) to see if our law was the actual problem but it worked as expected when using another item.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by SlayksWood** [comment]
@NomarCraft Thank you for the report. I don't have the problem in 0.9.4 staging-2010:
![image](https://user-images.githubusercontent.com/45708377/120974571-f546e880-c778-11eb-8d74-940d1ad52367.png)
and we didn'tr change anything here.
Can you provide some law examples and screenshot that charcoal is missing? Maybe you didn't discover it?
try to add checkpoint here:
![image](https://user-images.githubusercontent.com/45708377/120974845-46ef7300-c779-11eb-94d6-f5a7c1c26cf8.png)
and check it again.

**Comment by TwixterZ** [comment]
hi @NomarCraft

I have checked this in 9.3.5 Release 231 and can confirm that this is happening, 

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/0c773407-5214-430c-8c7b-96b0f10a22e1)

![image.png](https://images.zenhubusercontent.com/6017bedcbf0e6bfb14e12003/4158a519-4b6c-4484-974a-febceac945c3)

However as mentioned by @SlayksWood above, this is fixed in 9.4 version. 

As such I will proceed to close this issue. 

Thank you for raising this up =)
