### ISSUE TITLE
New workorders should be combined with existing ones if possible when theyre created

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2217]

**Comment by MarjieAVolk** [comment]
:O

**Comment by MarjieAVolk** [comment]
This might have some problems, particularly due to efficiency/speed skills changing (which does not updated old work orders)

**Comment by MarjieAVolk** [comment]
I don't really think this is going to be worth it, since it will require some deep changes in WorkOrder and lots of corner case handling.  In fact I might suggest kind of the opposite, that is to have a max size for work orders (something like 20), in order to make the cap on # of queued orders make more sense.  That way you won't make an infiniproject and then cancel and recreate it when you get more skills or something, which is what I often do but is kind of weird.
