### ISSUE TITLE
[0.9.3.5 release 231] Work party research won't accept generic research papers.

### ISSUE THREAD

**Issue by CrazyIvanTR** [StrangeLoopGames/EcoIssues#22183]
I have one other person on the server who had the same problem. The work party that will find a new research couldn't accept generic research papers, even though there were plenty of room to accept it.
![111](https://user-images.githubusercontent.com/15908001/121590922-936cd400-ca41-11eb-898b-65f63444b028.png)
![112](https://user-images.githubusercontent.com/15908001/121590945-99fb4b80-ca41-11eb-885d-749b819ff25e.png)

Not sure if this happens with all the research or just the ones that have modern papers in it but it happened with Composites research in my case.

slgid: slg202595

**Comment by TwixterZ** [comment]
Hi @CrazyIvanTR 

Thank you for raising this issue, 

Can you share your save copy for when this issue is happening for us to look into this better? 

you may refer below link for instruction how you may find your save files
Save files:  https://github.com/StrangeLoopGames/EcoIssues/wiki/Uploading-a-world-save

**Comment by CrazyIvanTR** [comment]
I'm not running the server itself, so I can't really send the world save. I don't think the issue could be reproduced on a singleplayer server either. 

I will try to test it with a friend on a private server but it might take time as we're usually both busy with work and on very different time zones.

**Comment by Daniel-Magulado** [comment]
Hi @CrazyIvanTR 

Thank you for getting back to us.
It appears that this issue is related to #21960.
I'll be merging this ticket to #21960 for now.
If you ever encounter this issue again, please do not hesitate to write a bug report of it but we highly recommend waiting for the upcoming game updates as this might be fixed by then.

Thank you.
