### ISSUE TITLE
[0.9.4 Staging-2020] Wheelbarrow and Hand Plow backward movement behavior

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22251]
Build: 0.9.4 Staging-2020

## Issue
With the said build, if you try to walk backward straight while holding any of the affected vehicles, you move backward correctly. However, if you try to move backward while turning left or right by moving your mouse once to initiate a direction, the game shows different behavior between Wood Cart and Wheelbarrow. Hand Plow exhibits the same behavior as with Wheelbarrow.

With Wheelbarrow, the avatar get's stuck in one direction and the camera doesn't follow the avatar's movement but with Wood Cart, the avatar keeps backing up and the camera follows it which becomes a backward spin movement. See video recording for difference below:

https://user-images.githubusercontent.com/77248866/121867528-a0840e80-cd32-11eb-83ab-4bc601ead6fc.mp4

Please note that I only moved the mouse to change the camera for the Avatar to move in a different direction. I'm not constantly moving my mouse to follow the avatar movement.

If this should be a separate issue as well, please do let me know.

**Comment by Quadbro** [comment]
Fixed glitches with backwards stuck BUT,  due to the very different prefab setup for plough/wheelbarrow they will have different camera behaivor with rotations (from regular carts).  I can make camera on them equal (swap front/back wheels, but we will lose the actual wheelbarrow behaivor with tilts and rotation (also their movement will be very weird)

**Comment by Quadbro** [comment]
Also fixed glitches with legs

**Comment by Daniel-Magulado** [comment]
Tested on 0.9.4 Staging-2028.

Closing as fixed.
