### ISSUE TITLE
[0.9.4 Staging-2039] Fish trap only captures Salmon and Trout

### ISSUE THREAD

**Issue by Daniel-Magulado** [StrangeLoopGames/EcoIssues#22409]
Build: 0.9.4 Staging-2039

## Issue
Fish trap only captures Salmon and Trout despite the presence of Cod and Bass in the same area where I placed the Fish Trap. If I try to fish in the same area, I can fish out Cod. Map also indicates a significant population of Cod and Bass in the same lake.

![image](https://user-images.githubusercontent.com/77248866/123837425-683d1c80-d93d-11eb-9ef3-51a4d943bbdf.png)

I've tested this on SLG Playtest server. I placed down Fish Trap on different lakes in between different Biomes.
After 10 hours of waiting, all Fish Traps only have Salmon and Trout caught.

Here's a map of the SLG Playtest Server. If you observe, I've circled all my Fish Trap locations.
![image](https://user-images.githubusercontent.com/77248866/123817314-a0872f80-d92a-11eb-967c-3fb202d48c05.png)

All of these Fish Traps contain Salmon and Trout only. It's not capturing Cod and Bass which has the same weight and tag for Salmon and Trout.

![image](https://user-images.githubusercontent.com/77248866/123818308-75511000-d92b-11eb-84f4-a3d7d149ddf8.png)

**Comment by Sekor2600** [comment]
Cod is a Seswater fish.
no idea which Bass is used. gives both Seawater & Freshwater variant.
The Problem is more that each Fish lives in Freshwater & Seawater.

And the Fishtrap is used for Rivers only for Freshwater fish
![grafik](https://user-images.githubusercontent.com/37456949/123831729-e7fac500-d904-11eb-8e6f-51cec95e8e5f.png)
