### ISSUE TITLE
[0.9.3.6] Custom channel does not instantly hide or show

### ISSUE THREAD

**Issue by Ry4ndrew** [StrangeLoopGames/EcoIssues#22446]
Build: 0.9.3.6 beta release-235

## Issue
Creating a custom channel has issues with hiding and showing itself instantly

### Recording
https://user-images.githubusercontent.com/49683923/124707652-b64cb400-df2b-11eb-9631-c711840fb4ab.mp4

**Comment by TwixterZ** [comment]
Issue also exist in 9.4 Staging-2047 

![Custom chat room](https://user-images.githubusercontent.com/78054747/124805522-36a40100-df8e-11eb-99d2-7153ac9bbfdb.gif)

To clarify, this issue happens when custom channel is selected when channel is hidden (by clicking RMB)

Repro :
- Create custom text channel
- Select said channel (LMB click created channel)
- Hide channel (RMB click) 
- Observe channel is not listed under "Hidden"
- Select #General channel (LMB click)
- Observe custom channel is now visible in hidden chat list

P/S : Hiding custom channel while having #General text channel selected instead will not produce this issue.

**Comment by Ry4ndrew** [comment]
Converted to ClickUp and closed as chat is being revamped entirely.
