### ISSUE TITLE
Tutorial Dialogue Box Gets Stretched

### ISSUE THREAD

**Issue by Steve2456** [StrangeLoopGames/EcoIssues#22450]
Eco version: 0.9.3.5 beta release-231

![eco](https://user-images.githubusercontent.com/87134222/124932682-6e6c8080-e042-11eb-8417-2c97c0ea3c56.PNG)

To reproduce:
1. complete controls tutorial
2. complete meteor tutorial
3. observe

![20210708230651_1](https://user-images.githubusercontent.com/87134222/124932486-467d1d00-e042-11eb-9365-cd65973fea35.jpg)

when game is restarted, the bug occurs after completing 1 tutorial

**Comment by TwixterZ** [comment]
Hi @Steve2456, thank you for raising this issue. 

This issue will be fixed with upcoming patch 9.4 (you may read about this here [#22434](https://github.com/StrangeLoopGames/EcoIssues/issues/22434).

As a temporary work around, may I suggest that you change your resolution to 2190x1080 for the duration of the tutorial. 

I will proceed to close this issue. However, if your issue is not the same as given link above, feel free to re-open this issue with additional details. =)

**Comment by Steve2456** [comment]
Hello,

Thank you for the quick reply. How would I change my resolution to
2190x1080 as it is not an option in the graphics settings.

Thanks again,
Steve2456

**Comment by TwixterZ** [comment]
@Steve2456 My apologies, I meant to say 1920 x 1080.

mistake from my end.

![image](https://user-images.githubusercontent.com/78054747/125148703-cdc3b100-e166-11eb-9a1b-266cd13d679e.png)
