### ISSUE TITLE
Staging 9.4 2086 settings for food tasting and food diversity not saving on server side

### ISSUE THREAD

**Issue by M3n5ch** [StrangeLoopGames/EcoIssues#22526]
Settings for food tasting and food diversity not saving on server side when restarting server. Need to reactivate it each time I restart server.
![Screenshot 2021-08-15 123238](https://user-images.githubusercontent.com/82637840/129475588-b878f879-3449-4b5b-a337-e4d620e9b01e.jpg)

**Comment by Daniel-Magulado** [comment]
Hi @M3n5ch 

Thank you for writing this report.
When changing settings inside the ServerUI, you need to ensure that you save every change you made. So that your preferred settings get applied all the time regardless of your server restarts. To save your settings, simply click the **File** located in the upper left corner and click on **Save**.

![image](https://user-images.githubusercontent.com/77248866/129485072-d95c40a6-33dd-4ff7-a034-320bd14f204b.png)

Let me know if this has helped you out.

**Comment by M3n5ch** [comment]
Ok with saving data manually it works. All the other options I tested yet are automatically saved when changed, so I didn't thought I have to save these settings.

**Comment by TwixterZ** [comment]
Hi, @M3n5ch is the information given by Daniel is satisfactory, can we close this issue?

Please let us know if you wants us to check further.

**Comment by TwixterZ** [comment]
Closing issue as no further response received
