### ISSUE TITLE
Carts steering is unreliable after update

### ISSUE THREAD

**Issue by Noneforu** [StrangeLoopGames/EcoIssues#22557]
Every time I go to operate a hand cart since the update, the steering has been very unreliable. It either turns the cart way to much and I end up facing a direction I do not want to be. Or is bairly steers at all. PLEASE bring back the old realistic controls.

**Comment by tonycoz** [comment]
The hand cart now steers like a four wheel vehicle, pushing w goes in the direction of the handles of the cart rather than the direction the character is facing,  A and D let you steer that movement, but do nothing unless you're moving due to W or S.

It's very confusing when you're used to the old behaviour, or even to the behaviour I expect from such a 2-wheel vehicle.

I do think it should be reverted.

**Comment by Noneforu** [comment]
Its when you are Pushing the cart that the over turning and u derturning occurs. The new controls just do not five the accuracy tue old controls gave. Now I struggle just parking a cart on the elevator without hitting every wall on the way in. Its horrable.

**Comment by IcedForge** [comment]
Thank you for reporting, after a lot of feedback we enabled legacy controls as an option where you can use the old control system while we keep working on the new system.
