### ISSUE TITLE
USER ISSUE: Masonry table room requirments

### ISSUE THREAD

**Issue by Fistepa** [StrangeLoopGames/EcoIssues#22584]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
1. level up masonry skill to lvl6
2. pick the upgrage that lowers the room requirments by 0.2
3. place masonry table to room with tier 0

**Expected behavior:**
It should work. bcs masonry table has room requirment 0.2 and with the upgrade it should be 0. So it should work.

**Actual behavior:**
Masonry table would not start. it shows that it needs 0.2 room tier. When i place it back into wooden room it shows " room tier 1 out of 0"

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No. I play vanilla. just downloaded eco

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7046702/Player.log)

**Comment by Daniel-Magulado** [comment]
Hello @Fistepa 

Thank you for writing this bug report.
I can confirm that despite the skill that reduces related table tier room requirements, tables still require 0.2 Tier Room.
I'll go ahead and write a report about this so that our development team can look into this further.

[ClickUp Report](https://app.clickup.com/t/10591183/ECO-14824)
