### ISSUE TITLE
USER ISSUE: dirt ramps wont rotate

### ISSUE THREAD

**Issue by UwUfluff28** [StrangeLoopGames/EcoIssues#22685]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.1 beta release-242

**Steps to Reproduce:**
have dirt ramp

**Expected behavior:**
ability to rotate

**Actual behavior:**
dosent rotate

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Daniel-Magulado** [comment]
Hi @UwUfluff28 

Thank you for writing this bug report. However, we are unable to encounter this issue.
Could you provide us with your game logs and complete PC system specification?
If possible, please also provide us a recorded video of the issue.
Otherwise, we currently have an internal report that ramps are missing rotate instruction.
To rotate ramps, press either R or Q.

Please let us know if this worked for you.

Thank you.

**Comment by Daniel-Magulado** [comment]
Closing due to lack of reply.
