### ISSUE TITLE
Game crashes when any player uses a scythe on grass or wheat

### ISSUE THREAD

**Issue by GigglingNinj** [StrangeLoopGames/EcoIssues#22703]
Doesn’t need much explaining. Whenever a player in our server uses a scythe to harvest grass or wheat, the game crashes for everyone that’s logged on at that moment.

Server host: 4Netplayers, 8 slots
Eco version: 9.4.3 (happened in 9.4.2 aswell)

**Comment by D3nnis3n** [comment]
Please attach player.logs for the crashes:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by GigglingNinj** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/7227060/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/7227061/Player-prev.log)

**Comment by Acromatic** [comment]
This issue was resolved in 9.4.3 created in 9.4.2 ( September 2021 Updates )

Update 9.4.3 has been released and includes the following bug fixes:

Fixed: Harvesting grass and wheat was causing a client crash
Fixed: The camera was set to a fixed position when driving a vehicle as opposed to adjusting to face the direction the vehicle was moving
Fixed: Players were often appearing invisible to others
Fixed: Tool animations would not always display when viewing others use a tool

**Comment by Acromatic** [comment]
You need to Update Server AND Clients... make server server mismatching isn't enabled. I've not had any problems on my server

**Comment by GigglingNinj** [comment]
yep, turned out I had to update the server manually. Thanks!

**Comment by Acromatic** [comment]
it's not that you need to manually update it, steam will do it's job... but it needs downtime and scheduling to auto update, you can't update running steam apps... you can have the server announce mods and auto shutdown for 2 hours and schedule steam during that time though... or as you say just manually update every patch.
