### ISSUE TITLE
9.5 2191 - Minting currency has some "random" items?

### ISSUE THREAD

**Issue by MishkaFur** [StrangeLoopGames/EcoIssues#22890]
Minting a currency, I can use a few random items? (Ignore the item next to limestone)

Barrel, claim, leather/animal hide?

Plastic, iron plate and steel plate make sense

![image](https://user-images.githubusercontent.com/61889138/147881297-993a8411-7ac6-4589-a0c8-165b9bcf86b5.png)

**Comment by TwixterZ** [comment]
Hi @MishkaFur  while land claim paper, leather, and animal hide is included by design, I do not have barrel as a mint-able item at my end. 
![image](https://user-images.githubusercontent.com/78054747/147974557-67881fbe-b1a0-4ca6-860f-f84e85aa2d6a.png)
this is taken from 9.5 Staging-2191.

Is this issue found in a modded save by any chance?

**Comment by MishkaFur** [comment]
Barrel is my fault ignore that one, but as discussed in DM on discord am closing
