### ISSUE TITLE
USER ISSUE: ECO - impossible de se connecter suite update 9.4.5

### ISSUE THREAD

**Issue by Lucky370** [StrangeLoopGames/EcoIssues#22918]
\
**User Id: (Not logged user)**
**Version:** 0.9.4.5 beta release-278

**Steps to Reproduce:**
Bug toujours malgrés avoir relancer le serveur privé

**Expected behavior:**
Il aurait du se connecter sans problème

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
<size=150%>Connexion échouée</size>

Version mismatched.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non, nous jouons sur un serveur privé sans mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
The server you are trying to connect to needs to update to 9.4.5, alternatively you can downgrade your own version in the meanwhile by right clicking on Eco in Steam, choosing properties -> Betas and selecting 9.4.4 in the dropdown. Make sure to revert to 'none' once the server has upgraded, as you otherwise will not get automatic updates in the future.
