### ISSUE TITLE
View All Votes on voting site does nothing

### ISSUE THREAD

**Issue by mstrwiz** [StrangeLoopGames/EcoIssues#23444]
Version: 0.9.6.1 beta release-337

If you click on "View All Votes" on any election, it does nothing. However, the styling for clickability is there. There is no error or warning produced in the JS console log.

Notably, the View All Votes is a span whereas the ones that work are actual anchors:
![ViewAllVotes](https://user-images.githubusercontent.com/2541009/189762693-4ac04039-5f50-47e9-9ccf-e65279a1e64f.jpg)

**Comment by Daniel-Magulado** [comment]
Hi @mstrwiz 

Thank you for submitting this bug report. We are aware of this issue and fortunately, a fix is already set to roll out in the coming game updates. Please look forward to it.
With that being said and the fix is set for the next updates, I'll go ahead and close this report.
Feel free to reopen this again if you still have this bug after the next rollout of bug fixes. You may also use this reference ID - ECO-23748 as a follow-up ticket if the need arises.
