### ISSUE TITLE
Alpha.6 [E80b350f] Wrong inventory capacity / Carrying Weight issue

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2357]
40kg/50kg with an empty Character:
![image](https://user-images.githubusercontent.com/3965439/30939782-f64d2472-a3de-11e7-8be9-1226b426bb35.png)

Reconnect does not fix.

**Comment by metachronism** [comment]
need more repro steps - what were you doing to create this state?

**Comment by Frozen-byte** [comment]
Since I am unable to reduce my weight, it is impossible for me to reproduce.

Last actions where: carrying 20 Coal while picking up wooden carts and playing around with deeds. Not sure if these reproduce the issue.

Will have an eye on it next time.

**Comment by MarjieAVolk** [comment]
Yeah I think this can happen when you try to pick up a vehicle but aren't able to (because your inventory is full or something), think I saw that before

**Comment by fillion07** [comment]
Same problem here. After selling Bison and elk carcasses to a store, my weight remains to the same. My weight was 49.32kg with the carcasses on me (on my backpack), and after selling it, my weight stay to 49.32kg.
![image](https://user-images.githubusercontent.com/7052045/31063726-98030238-a703-11e7-883f-9320665652c3.png)

**Comment by Frozen-byte** [comment]
currently only a server restart does reset the weight correctly

**Comment by MarjieAVolk** [comment]
Okay, I've fixed some instances of this (in master, will be available in the next release), such as selling at stores.  I'm going to close this bug for now, since this issue has a lot of causes, and may or may not be completely fixed already.  If you do ever see it happen again, please file a bug with as much context about what you were doing as you can remember.  I'll continue keeping my eye out for it as well.
