### ISSUE TITLE
Terrain Stops loading

### ISSUE THREAD

**Issue by Entiffo** [StrangeLoopGames/EcoIssues#23656]
ECO Version: 0.9.7.6 (Latest at the time of posting)

Issue appears on Server for all players, and also if savegame is loaded in Singleplayer.
World is 22 days old, was created on 0.9.7.4 version.

Steps to reproduce: In save, there is a main highway, walking anywhere past that highway will produce the issue at random times and always on few specific spots, one showed in the video in real time.

Save files and video file link: https://cloud.uexp.org/index.php/s/JabwxEsWZrsPf3Y

Username on Discord is the same (Entiffo) for direct questions or requests.

Server for serverside testing: Unlimited Experience - RP/No Meteor/LowCollab - BeginnerFriendly

**Comment by Entiffo** [comment]
Just noticed, the terrain loading bug appears on the lines that are visable from web view:
![image](https://user-images.githubusercontent.com/120136848/210282714-c2780ba5-f79d-4f49-a0a3-4928d20ed913.png)

**Comment by D3nnis3n** [comment]
Your world unfortunately is way beyond the maximum size supported (2,56 km²) and the size we take bug reports for (4 km²), I'm hence going to close this issue. If we do find open resources to look into, we'll do, but this issue is likely to be a side effect of the size being outside of the supported values.
