### ISSUE TITLE
[9.7.6] Base freshness deteriorates over time

### ISSUE THREAD

**Issue by MonzUn** [StrangeLoopGames/EcoIssues#23671]
When a new FoodItem is created, it should always show with 100% freshness.
Leaving the server running leads to this being untrue and it will just keep going down until the server is restarted and it starts from 100% again and over time the same issue comes back.

STR:
1 Start the server
2 Pick any crop
3 Observe that the freshness of the crop is 100%
4. Leave the server funning for at least an hour (/ff will not repro the issue)
5. Pick any crop
6. Note that the freshness of the picked crop is NOT 100%

Download link for server setup
https://drive.google.com/file/d/15qJ8MbOOnd3tDKzq7gl7SJktKqZBSPie/view?usp=share_link

Feel free to reach out to me on Discord.

**Comment by JulianMa** [comment]
So i spend the last few hours digging into this bug and oh boy, i found it.

**First of all: As far as i know, the Bug can't be triggered in pure vanilla, or atleast, its very rare. But it's still a eco bug:**

Eco creates Item Instances by first getting an item instance from the AllItems Array, which holds global instances for every Item in Eco. Then it calls the clone method onto that, which in it's Base Implementation just creates a new Item Instance. 
See `InventoryChangeSet:575`.

The `FoodItem` class is overwriting this Implementation and passing the spoilageTime of the Global Item Instance into that newly created item. **Basicly that is the issue.** 

The only reason why it's not getting triggered in Vanilla is, because the `Duration` on the Global Item instance is 0. As long as this is the case, all items which get cloned from that, will recalculate their durability with the Maximum Value, see `FoodItem#GetDurability()`. 

**So why does this get Triggered by mods?**
Some mods do data dumps of all Items. They will Iterate over all Item Instances in `Item.AllItems` and serialize them. This serialization step will also call `GetDurability()` at some point, on all FoodItems, which will init the duration value of the `spoilageTime` Timer. 
After this process, all Items which get cloned from the global instance, will have their duration timer set to this value. 

So the STR from @MonzUn don't apply for Vanilla. But it can be reproduced with a Mod, containing this:

```
foreach(var foodItem in Item.AllItems.Select(item => item is FoodItem))
 {
     (item as FoodItem).GetDurability();
}
```

**Comment by MonzUn** [comment]
This issue has been fixed
