### ISSUE TITLE
I can't play the world i created and played for about 30 min

### ISSUE THREAD

**Issue by FreeBrennen** [StrangeLoopGames/EcoIssues#23717]
\
**User Id: (Not logged user)**
**Version:** 0.9.7.9 beta release-451

**Steps to Reproduce:**
I had a world and disconnected. tried to get back in and this pop up keeps happening

**Expected behavior:**
can't log in

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no i do not

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/10832963/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/10832965/Player-prev.log)

**Comment by D3nnis3n** [comment]
This means that you are not able to reach our authentication server, typically an issue with antivirus or security software, can also be caused by VPN or ISP settings. This is hence not a bug, but rather a support issue for [support@strangeloopgames.com](mailto:support@strangeloopgames.com), where you can reach out to.
