### ISSUE TITLE
Interaction bugs on 9.7.12.

### ISSUE THREAD

**Issue by X66Herobrine66X** [StrangeLoopGames/EcoIssues#23784]
On the new Hotfix, I can't interact with left click at all. Blocks that I look at aren't highlighted, and I can't break them. Grass can't be harvested, stone can't be mined, and my shovel appears to be carrying dirt that I'm not actually carrying. If I give myself oak logs with commands, I can place them, but if I give myself dirt I cannot. I can't pick up either. If I exit a wooden cart my hotbar may disappear, or it may not.
I'm using a few mods.
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/11240709/Player.log)
[log_230415051415.log](https://github.com/StrangeLoopGames/EcoIssues/files/11240716/log_230415051415.log)

Steam username is 'Kronos'.

**Comment by D3nnis3n** [comment]
Fixed savegame provided, but caused by user error or mod: https://drive.google.com/file/d/1AiSGdZCHd4BtZF_E0oZLbtkoTktQa5yf/view?usp=sharing

**Comment by gzatravkin** [comment]
Hi. The problem was in dummy users (which seems to be created using developer command /me times). Developer commands are only for internal testing and not suppose to be used in the world. This coorupted the save. I fixed the save here https://drive.google.com/file/d/1AiSGdZCHd4BtZF_E0oZLbtkoTktQa5yf/view?usp=sharing but do you have any clue how you got these 2 dummy users on your server? Did you run this command?
