### ISSUE TITLE
USER ISSUE: World layer Plant group don"t work

### ISSUE THREAD

**Issue by Nolaa-Uzul** [StrangeLoopGames/EcoIssues#23837]
\
**User Id: (slg230037)**
**Version:** 0.10.0.0 beta staging-2624

**Steps to Reproduce:**
1- Go near plant (Beans in my exemple)
2- open map and select World layer BeansGrowth
3- The map Preview don't show any beans
4- Active The overlay in main View
5- All is Gray 

**Expected behavior:**
have a Plant world layer opérationnal

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Non PlayTest V10.0 on local server solo

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.zip](https://github.com/StrangeLoopGames/EcoIssues/files/11550453/Player.zip)
![Layer_select](https://github.com/StrangeLoopGames/EcoIssues/assets/134451438/98caa8c3-b555-4dc2-a476-ace8321dc80e)
![OverlayinMain](https://github.com/StrangeLoopGames/EcoIssues/assets/134451438/61f0f221-63f7-472c-a497-d199c148dca5)

**Comment by D3nnis3n** [comment]
Thanks, this issue is already known and tracked (ECO-28299). As per our announcement this tracker is not taking bug reports until public playtest on WT starts, hence I'm closing this. For future reports, please post them in our discord's update 10 channel, so we can filter out issues we're already aware of easily.
