### ISSUE TITLE
USER ISSUE: Unpickable rock

### ISSUE THREAD

**Issue by Nolaa-Uzul** [StrangeLoopGames/EcoIssues#23836]
\
**User Id: (slg230037)**
**Version:** 0.10.0.0 beta staging-2624

**Steps to Reproduce:**
1- Mine rock
2- Try pick up 
A lot of rocks can't be pickable

**Expected behavior:**
all item can be pickable...

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No, Playtest V10.0 on local server solo

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[Player.zip]
(https://github.com/StrangeLoopGames/EcoIssues/files/11550422/Player.zip)

**Comment by D3nnis3n** [comment]
Thanks, this issue is already known and tracked (ECO-27911). As per our announcement this tracker is not taking bug reports until public playtest on WT starts, hence I'm closing this. For future reports, please post them in our discord's update 10 channel, so we can filter out issues we're already aware of easily.
