### ISSUE TITLE
10.0 staging 2644 : Hunting broken

### ISSUE THREAD

**Issue by BennoHase** [StrangeLoopGames/EcoIssues#23843]
Hi,
Hunting is broken in 10.0 staging 2644. I use the bow, the arrow hits the animal (I tried 3 different) and the animal dies (after the correct amount of arrows hit). But I can't pick it up. I can kick it through the area and I can dig a hole under the dead animal. The dead animal falls in the hole and I can put sand on it and the animal is gone, even if I dig the hole again. I could remove it with the devtool, but not everytime (it was gone after server restart)

**Comment by BennoHase** [comment]
still there with stating 2646

**Comment by D3nnis3n** [comment]
Thanks for your report, this issue is already internally tracked under ECO-28478.

I'm closing this issue as we currently until start of public playtest do not accept Update 10 issues here,
see the announcement on Update 10 preview and the intended usage of #upd-10-test in Discord for any reports,
due to the early stage of the Update with most issues already being known.
