### ISSUE TITLE
USER ISSUE: Firing bow crash's player

### ISSUE THREAD

**Issue by Piroxgp** [StrangeLoopGames/EcoIssues#23987]
\
**User Id: (slg190024)**
**Version:** 0.10.0.0 beta playtest-102

**Steps to Reproduce:**
pull back bow and release

**Expected behavior:**
fires arrow at target

**Actual behavior:**
crash's the player or kicks them from server

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods are installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Salenders** [comment]
Version: 0.10.0.0 beta playtest-102

Steps to Reproduce:
pull back bow and release

Expected behavior:
fires arrow at target

Actual behavior:
crash's the player or kicks them from server

Do you have mods installed? Does the issue happen when no mods are installed?:
no mods are installed

[TargetInvocationException 08253908.txt](https://github.com/StrangeLoopGames/EcoIssues/files/12437090/TargetInvocationException.08253908.txt)

**Comment by D3nnis3n** [comment]
Fixed.
