### ISSUE TITLE
USER ISSUE: first person glitch

### ISSUE THREAD

**Issue by chopper35s** [StrangeLoopGames/EcoIssues#24162]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.0 beta release-532

**Steps to Reproduce:**
1. go to first person
2. see your own teeth/eyes

**Expected behavior:**
no teeth/eyes

**Actual behavior:**
has teeth/eyes

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no, and no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Cannot reproduce, do you use /fly?

**Comment by chopper35s** [comment]
Negative. I also found another bug
![20231213194558_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153701353/a3032b96-5592-4aac-a1e2-91ea5cad50f7)
![20231213194554_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153701353/6dd6181b-df0b-436d-9c60-7e9589c128ee)
![20231213194539_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153701353/eeb0a302-29ff-4b2c-b6d9-dc540a8e4feb)
![20231213194536_1](https://github.com/StrangeLoopGames/EcoIssues/assets/153701353/32da69cb-084b-4e74-88e2-40a65bb44b90)

**Comment by D3nnis3n** [comment]
That looks like it's after sleeping? In that case it would already be known.

**Comment by anakreon** [comment]
Same issue here. 0.10.0.3 beta release-547. No mods, no /fly command.

This happens sometimes when I start the game. Instead of sleeping lying in the bed, the character is standing on top of bed.  Also, when looking at the character in 3rd person and moving, his arms and legs are not moving - no moving ragdoll animation. This seems like a common bug in games.

![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2128212/80601a46-8de6-4ec4-849d-c1a5d3c45a5e)
![image](https://github.com/StrangeLoopGames/EcoIssues/assets/2128212/1bf8448a-ce6e-47d6-b479-df5da1dc85a3)

**Comment by D3nnis3n** [comment]
Duplicate, was reported for sleeping already.

**Comment by anakreon** [comment]
@D3nnis3n if this is a duplicate, could you please provide a link to the original issue? So that not only us but also other people who accidentally find this issue will have a way to follow up and see if this has been resolved.

**Comment by D3nnis3n** [comment]
If no Github issue is stated, it is a duplicate of an issue in our internal tracker. We do no longer use Github for development, we only use it to collect user issues. Newer reports have mad that clearer by stating it in the duplicate message.
