### ISSUE TITLE
USER ISSUE: Error to connect

### ISSUE THREAD

**Issue by Eridiath** [StrangeLoopGames/EcoIssues#24325]
\
**User Id: (Not logged user)**
**Version:** 0.10.0.2 beta release-544

**Steps to Reproduce:**
Cannot connect to own server.

**Expected behavior:**
It should have allowed me to connect.

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[logs.txt](https://github.com/StrangeLoopGames/EcoIssues/files/13721466/logs.txt)

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach authentication servers. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
