### ISSUE TITLE
[Enhancement] Automated item transfer

### ISSUE THREAD

**Issue by Frozen-byte** [StrangeLoopGames/EcoIssues#2446]
I would like to have a game-mechanic to automate transferring items from Point A to Point B (like a Belt transporting the Items around).

I'd also like to see auto-re-filling Power-Storage if they are linked to a Stockpile/Chest.

**Comment by MarjieAVolk** [comment]
The second thing you want is like a battery?

**Comment by Fank** [comment]
I think what he mean is that, the power tab does not pick fuel from stockpiles.
You need to drag and drop them everytime if its empty

**Comment by Frozen-byte** [comment]
What @Fank said.

**Comment by Conchipedia** [comment]
i agree with the idea of a transport system as being a miner i often have to move stuff from a lower level to a table at a higher level, at the moment in my Current Server i have a mint at level 144 (surface) (don't want to move this as had problems with it breaking the Currency and if i make another Mint at a lower level i cannot make the same currency), Stone main underground supply (level 129), Iron ore (level 107), Coal (level 84), Gold ore (level 45) copper ore (level 43) the copper and gold are at differnet locations (found by doing test holes), so at the moment i either pick up 20 of the stuff im digging out and then using unstuck to deliver it to a table/stockpile (depending on my needs) or placing chests and stockpiles at differnt levels and moving the stock between them (i know i should be doing this by a cart but trying to get ramps down possible up to 100 levels does take a bit of work. so a conveyor belt or a lift system would be perfect, either move ore at lower depths to a furnace above, or moving the  ingots from a furnace below to a Mint or storage area above.
because sometimes things are so deep a lift object could be built that acts like a moving stockpile or chest
then a possible point of exit or level can be crafted for the lift to stop at, either by sending it from below, with a button system, entering the lift with button system or being at the level desired with a call lift button system. one of the reasons for using a lift would be a miner can create shafts down which can be done manually by digging them out and placing the dug out material into stockpiles at certain levels.

also the arguement for having a power tab automatically take the required Fuel supply (possibly chosen by a tick system next to what should be used) from  a stockpile is for example a lot easier for a player to keep a stockpile full of coal (max 500) than filling 10 power generators power tab (40 max) or if lucky you have a modder around (6 stacks in a power tab) (120 max) as the coal at max efficiency and with all lights on Continuously (no way to have then turn off in daylight) the power tab will last just about 24 or 36 hours depending how many things require this power.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#370
