### ISSUE TITLE
Unable to sell at a store - "Invetory only accepts non-carried items"

### ISSUE THREAD

**Issue by Timmay24** [StrangeLoopGames/EcoIssues#2447]
![unbenannt](https://user-images.githubusercontent.com/5476826/31125677-65d35d3e-a849-11e7-8be2-4a00c530c2fa.png)

Seems to me that the store tries to put the wheat into a stockpile primarily.
For the record:
- no stockpile is linked
- linked storage chest has enough room

Also tried putting a chest nearby - same prob.

**Comment by MarjieAVolk** [comment]
Hm, wish we had better messaging for inventories.

I would say maybe the store owner has different link settings than you, which you might not be aware of.  But the message it gives doesn't sound right for only moving wheat, since wheat IS non-carried...

I'll see if I can repro - but would it be possible to send me your server's Game.eco save file?  That might make it easier

**Comment by Fank** [comment]
@MarjieAVolk Pick the save from here https://github.com/StrangeLoopGames/EcoIssues/issues/2449#issuecomment-333892914 the store is located in the room with the water wheel in the from (spinning in air, there is an issue for that)
