### ISSUE TITLE
Conditional clause "has access" returns Everyone when "deed at location" is selected

### ISSUE THREAD

**Issue by Psojed** [StrangeLoopGames/EcoIssues#24507]
**User Id: (Not logged user)**
**Version:** 0.10.0.3 beta release-547

**Steps to Reproduce:**
1) Place down a deed as the Player.
2) Create a Demographic with the condition "Citizen has access to Deed at Location where location is Residence of Player".
3) Observe the amount of people in the newly created Demographic.

![2024-01-02_082838](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/626b8b36-21c1-442d-80c6-6ee3bd33bc30)

**Expected behavior:**
Demographic only contains people who have access rights to the deed where Player has his Residence.

**Actual behavior:**
Demographic contains Everyone.

![2024-01-02_083359](https://github.com/StrangeLoopGames/EcoIssues/assets/12875358/1a85c727-9db1-458a-b98d-e2e3bb65cadc)

**Do you have mods installed? Does the issue happen when no mods are installed?:**
None

**Comment by D3nnis3n** [comment]
Duplicate.

**Comment by Psojed** [comment]
@D3nnis3n I couldn't find another ticket describing this issue. Could you point me to the right ticket so I can subscribe to it?

**Comment by D3nnis3n** [comment]
When we don't notce a Github issue for the duplicate it means it's a duplicate of our internal tracker. (We don't use GitHub anymore, only for collecting user reports)

I hence can't give you a link, as you couldn't access it. The issue is classified as medium priority, though, so a fix won't be available before the next minor Update 10.1. That's at least Q2. Sorry :(

**Comment by Psojed** [comment]
I see, thank you for the details :)
