### ISSUE TITLE
New player. Constant crashes to desktop. 

### ISSUE THREAD

**Issue by Firebrandonasegway** [StrangeLoopGames/EcoIssues#24681]
followed all suggestions regarding lowering of settings, disappling AA and reducing memory allocation. Eventually able to join server to an immediate crash. currently matching server version 10.1.1 
crashes occur with no apparent trigger.
[log_240123022604.log](https://github.com/StrangeLoopGames/EcoIssues/files/14019623/log_240123022604.log)

**Comment by Firebrandonasegway** [comment]
Reinstalled to latest version. attempted to run on new world. crashed while picking corn
[log_240123052544.log](https://github.com/StrangeLoopGames/EcoIssues/files/14019869/log_240123052544.log)

**Comment by D3nnis3n** [comment]
These are the wrong logfiles, for the server.

Please provide the client logfiles _after_ a crash happened:
https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Firebrandonasegway** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14037440/Player.log)
[Player (1).log](https://github.com/StrangeLoopGames/EcoIssues/files/14037442/Player.1.log)

Here are what i think to be the correct ones. taken from among a series of crashes.

**Comment by D3nnis3n** [comment]
Both crashes are happening due to the system being out of memory. You can try to reduce graphic settings notably, close other programs that use memory while playing Eco and playing on smaller servers that don't have too much stuff going on, which will increase memory requirements.

While we do plan to improve memory usage, that is a continuously ongoing task and there is unfortunately nothing we could do as immediate remedy, which is why I close this issue, as a internal one for memory usage already exists.
