### ISSUE TITLE
Server Crashed and doesn't start again with ArgumentNullException

### ISSUE THREAD

**Issue by Ju1yan** [StrangeLoopGames/EcoIssues#24693]
Hello, the server is hosted on a self hosted pterodactyl webinterface, It worked for some time, but recently it crashed (without a crash report the log just ends with the last removed backup and then it didnt want to start again, now It always crashed at the step where it loads the world. I updated the server so no it is on the newest version (Eco Server 0.10.1.2 beta release-584) , which doesn't make a difference. but If I load a backuped world from a few days before the crahs it works for a short time and crashes with the exact same crash report and doesn't start again (I did this twice to see if something that happened in the game accidentally caused it) but it comes back. it has something to do with the world, because if I download the world and put it in my game instace it crashes too at startup. in the attachements are the world and the crash report
PS: No mods are installed

Last log infront of the crash: [log_240120124243.log](https://github.com/StrangeLoopGames/EcoIssues/files/14068318/log_240120124243.log)
Crashlog on startup: [log_240126060235.log](https://github.com/StrangeLoopGames/EcoIssues/files/14068282/log_240126060235.log)
World it happens on: [Game.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14068287/Game.zip)

**Comment by D3nnis3n** [comment]
Your save only contains the database, not the actual savegame, can you attach the correct full savegame?

**Comment by Ju1yan** [comment]
oh yes, my bad, here is the database and savegame
[Game (2).zip](https://github.com/StrangeLoopGames/EcoIssues/files/14088447/Game.2.zip)

**Comment by D3nnis3n** [comment]
Fixed in 10.1.3.

**Comment by gzatravkin** [comment]
Can you also attach the backup from before the crash?

**Comment by Ju1yan** [comment]
Of course, here is the last working savegame:
[LastWorkingSaveGame.zip](https://github.com/StrangeLoopGames/EcoIssues/files/14104271/LastWorkingSaveGame.zip)

**Comment by gzatravkin** [comment]
@Ju1yan So I tried to run for some time your server, its not getting broken to me. The save file after crash is just corrupted, I dont see any obvious what could have cause that. 

In order to be fixed that I will need to get more info about why it gets crashed.

Do you know which specific action cause the crash so I could reproduce that crash locally? Otherwise if you would be able to get crash dump it also could help. https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u000000CpfyCAC&lang=en_US%E2%80%A9&refURL=http%3A%2F%2Fknowledgebase.paloaltonetworks.com%2FKCSArticleDetail here some instruction of getting crash dump, I know that there are also a global config at windows that allows to dump all crashed processes in a specific folder. This dump should have more information about what exactly caused it.

**Comment by D3nnis3n** [comment]
To me it sounds like the corruption actually has to do with Pterodactyl, which we don't support.
I remember another case of that failing to deal with Eco correctly, leading to a corrupted save game.
A game bug doesn't seem to have caused this issue - your posted save file is in a generally corrupted state.

**Comment by D3nnis3n** [comment]
Closing for now until reproduction steps provided that work on a vanilla Eco setup.
