### ISSUE TITLE
USER ISSUE: Spalsh Screen Wont' Load

### ISSUE THREAD

**Issue by trek-e** [StrangeLoopGames/EcoIssues#24721]
\
**User Id: (slg241663)**
**Version:** 0.10.1.3 beta release-592

**Steps to Reproduce:**
Load Eco start connection to serverlose power, shutting off computer hard.	restart computer/game

**Expected behavior:**
Splash screen and ability to pick serer/login	

**Actual behavior:**
splash screen with no menu items nothing works except esc to set optinos, but can't get back to 'pick a world' or any other options on screen other than animated background/sounds

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by trek-e** [comment]
log file is 0kb and dated at the time of the crash.

**Comment by D3nnis3n** [comment]
Please type "run" in your system, enter "%UserProfile%\AppData\LocalLow\Strange Loop Games\Eco" and delete player.eco in there. Does that help? If not, please reach out to support@strangeloopgames.com. This problem is likely caused by the hard powerdown, which - if you were playing singleplayer - will have corrupted your savegame. They will be able to assist with that problem.

For a bug report we at least need a complete logfile.
