### ISSUE TITLE
Still unable to interact with objects

### ISSUE THREAD

**Issue by adventuresofaj** [StrangeLoopGames/EcoIssues#24757]
Happening since November, across all servers and after updates.

I am not super technical so struggled to supply some of the information needed. But it's been three months, will I never be able to play this game again? I have tried reinstalling, verifying my game files, all kinds of in-game tests at the end of last year.

I know nothing about computers so apologies if any of this is unhelpful:
Processor: AMD Ryzen 5 3600 Six Core CPU
Motherboard: ASUS Prime B450-PLUS
Memory: Corsair 16GB Vengeance LPX DDR4 2400MHz
Graphics Card: 6GB Nvidia GeForce RTX 2060
Installed RAM: 32GB

Edition	Windows 10 Home
Version	22H2
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0
Security: None?

[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/14230116/Player-prev.log)
[Player.log.copy.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14230119/Player.log.copy.txt)
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/14230120/Player.log)

**Comment by collinticer** [comment]
Not a developer for SLG but your issue just caught my eye and I noticed something in your log files, so I thought I'd chime in.

Your logs mention issues with being denied permission to files under the path `C:\Users\AJ\AppData\LocalLow\Strange Loop Games\Eco\` such as the `inputManager.cfg` as well as various other files. This seems odd to me and as a start I'd suggest troubleshooting why your install of Eco doesn't have permissions to parts of that directory.

If I were you, I'd uninstall Eco, and then delete the `C:\Users\AJ\AppData\LocalLow\Strange Loop Games\Eco\` directory since the uninstall might not remove it. Once the directory is deleted, then try and re-install Eco once more.
