### ISSUE TITLE
USER ISSUE: Cannot start local server

### ISSUE THREAD

**Issue by SkarletKill** [StrangeLoopGames/EcoIssues#24806]
\
**User Id: (Not logged user)**
**Version:** 0.10.1.4 beta release-603

**Steps to Reproduce:**
1. Start local server you've created2. At the last state "connecting to server..." somewhat the speed is too low 100b/sec and after 10 sec disconnectSometimes it can connect and if so stable game for 2-3 hours, but periodical connection issues

**Expected behavior:**
The server connects and works fine

**Actual behavior:**
Вигулькнуло таке повідомлення про помилку: 
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach authentication servers. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
