### ISSUE TITLE
6.0 alpha worlds suddenly flooding

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#2486]
This is the game world and logs from a  6.0 world that was running just find and then suddenly flooded complete.  I have had several reports from other people of 6.0 worlds of about the same age suddenly flooding too

https://www.dropbox.com/s/p9drcrxz08uclwy/uskillserver_Game.zip?dl=0
https://www.dropbox.com/s/hdetuebcpdkb82n/uskillservers_Dump.zip?dl=0

If you want the backups of this world to see what it looked like prior to flooding please let me know

**Comment by MarjieAVolk** [comment]
Another save file + backup save which had this problem (from MasterWhoMW): https://drive.google.com/file/d/0B5OT8hSaePzAbjVFX21YcWJSUE0/view?usp=sharing

**Comment by MarjieAVolk** [comment]
"Id like to add, i made a 4th server (as we run 3) our first 3 servers have been absolutely fine, no new worlds needed, very minimal crashing, but on the 4th server i left it sit for an hour after being generated, completely new vanilla files and it had flooded the world, the only things in this world where a few stockpiles and a few chests, i had started a new world because of it and joined during the generation (by accident) and had noticed that the CO2 PPM was rising even though i had started a fresh world, so i created a new world again and have left it sit for a few days but the sea level hasn't risen, so i'm not sure how this occurs, Thanks Guys.

Edit: sorry i also noticed when the world was flooded the Co2 PPM was at the maximum but there was absolutely no pollution in the world at all."
-- KyeEco

**Comment by johnkslg** [comment]
Fixed
