### ISSUE TITLE
USER ISSUE: Town Foundation Issues	

### ISSUE THREAD

**Issue by ProductionEXP** [StrangeLoopGames/EcoIssues#24889]
\
**User Id: (slg216391)**
**Version:** 0.10.2.1 beta release-647

**Steps to Reproduce:**
I placed a town foundation and it instantly disapeared. 

**Expected behavior:**
Just place the town foundation and let me claim plots and build my town.

**Actual behavior:**
The twon foundation dissapears, and when I try to unclaim the polt that was claimed by the placement of the town foundation, the following error message popped up
```
Server encountered an exception:

<size=60.00%>Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:Eco.Gameplay

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(User user, PlotPos plotPos)
   at Eco.Gameplay.Settlements.ClaimToolBaseItem.Unclaim(Player player, InteractionTriggerInfo triggerInfo, InteractionTarget target)
   at InvokeStub_ClaimToolBaseItem.Unclaim(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Outer Exceptions:
Exception has been thrown by the target of an invocation.
Exception has been thrown by the target of an invocation.</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
Yes the server I play on has mods, I belive just price calculator and big shovel.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by ProductionEXP** [comment]
Log file
[test.txt](https://github.com/StrangeLoopGames/EcoIssues/files/14985692/test.txt)

**Comment by D3nnis3n** [comment]
Please post your Features.eco config file.

**Comment by Daniel-Magulado** [comment]
Hi @ProductionEXP 

Thank you for submitting this bug report. 
Are you using "Claim Paper Item" by chance on your homestead? Did you obtain it via /give or consuming skill scroll? 
We are aware of a bug that causes the foundation object to disappear upon placement—leaving the deed and influence on place. This happens when a player is currently using "Claim Paper Item" on his/her homestead before placing any foundation object.

Unclaiming the deed created will cause the error log you shared with us.
What we suggest for now until our team releases a fix update is to avoid using a "Claim Paper Item" that did not spawn from the settlement foundation object.

**Comment by ProductionEXP** [comment]
> Please post your Features.eco config file.

I will see if I can get that from the server we play on

**Comment by ProductionEXP** [comment]
Uncalming and then removing the papers fixed it, thanks!
