### ISSUE TITLE
Game Starts, Main menu switch to a blue Screen and it freezes

### ISSUE THREAD

**Issue by ShardsFuchs** [StrangeLoopGames/EcoIssues#24919]
After Installing Cant play the Game.

Version : 10.2.x (current status)
![eco](https://github.com/StrangeLoopGames/EcoIssues/assets/168845052/030939bd-585a-449b-ab08-da47eb0fff63)

https://github.com/StrangeLoopGames/EcoIssues/assets/168845052/23f4c506-7506-40f7-864d-79d63888e73e

[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15201711/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15201712/Player-prev.log)

**Comment by D3nnis3n** [comment]
Make sure you have installed the latest VC++ redistributables: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Afterwards try to remove any cameras you have attached to the computer. If that still doesn't help, remove any camera software and drivers one by one. The problem is likely related to incompatible / outdated cameras or respective drivers.

**Comment by D3nnis3n** [comment]
Mind letting us know what was the culprit? :)
