### ISSUE TITLE
USER ISSUE: Failed to login

### ISSUE THREAD

**Issue by madd0g37** [StrangeLoopGames/EcoIssues#24925]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
load a local game and it loads to auth server then fails to auth. i have changed nothing on my pc the game worked for two days then tonight just stated this everytime. i am running this on manjaro i tryed restarting my pc tryed resetting my router disabled my firewall. i am not sure what else it could be

**Expected behavior:**
loaded the game

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
[log_240509024710.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253322/log_240509024710.log)
[log_240509024906.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253323/log_240509024906.log)
[log_240509025256.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253324/log_240509025256.log)
[log_240509025819.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253325/log_240509025819.log)
[log_240509061644.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253328/log_240509061644.log)
[log_240509061736.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253330/log_240509061736.log)
[log_240509061954.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253331/log_240509061954.log)
[log_240509062310.log](https://github.com/StrangeLoopGames/EcoIssues/files/15253332/log_240509062310.log)

i added a bunch here to show it was working fine.

**Comment by D3nnis3n** [comment]
This is not a bug. The log simply states that the server is unable to reach authentication servers and hence the request timeouts.

This can be caused by anything: No internet connection, security software, any software that blocks ads (PiHole, Adguard), global routing issues, ISP connection issues, DNS issues, Cloudflare taking temporary security measures against the ip range you are in, etc.

There is no way for us to identify which of these reasons it might be in your case. You can reach out to support@strangeloopgames.com, which can provide hints with diagnosing but can not diagnose it either.

**Comment by D3nnis3n** [comment]
Local games work by starting a dedicated server on your computer, which authenticate every player that join the server.
If the authentication fails or is not possible due to networking issues, the player cannot join the server.

We do plan to provide a limited offline mode when leaving Early Access, but currently Eco needs internet access when playing.
