### ISSUE TITLE
USER ISSUE: Invalid login info

### ISSUE THREAD

**Issue by PsyCoder** [StrangeLoopGames/EcoIssues#24920]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.2 beta release-660

**Steps to Reproduce:**
Load my local game from my local server

**Expected behavior:**
Allowed me to play the game

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods.  

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by PsyCoder** [comment]
[Player.log](https://github.com/StrangeLoopGames/EcoIssues/files/15210460/Player.log)
[Player-prev.log](https://github.com/StrangeLoopGames/EcoIssues/files/15210461/Player-prev.log)

**Comment by D3nnis3n** [comment]
Not a bug, connectivity issue on your local PC. Make sure no security software is blocking access and check network configuration.  Can also reach out to support@strangeloopgames.com.

**Comment by PsyCoder** [comment]
Yeah, no such software is running or blocking anything.  AND it worked
several times the day before, which is why I filed it as a bug, but thanks.
I guess.

**Comment by D3nnis3n** [comment]
Sorry, guess I was not verbose enough - the log you attached says nothing else than the connection cannot be established, which is always caused for third-party reasons we cannot detect. As such there is no suitable information to assume or investigate a bug.

This can be caused by anything: No internet connection, security software, any software that blocks ads (PiHole, Adguard), global routing issues, ISP connection issues, DNS issues, Cloudflare taking temporary security measures against the ip range you are in, etc.

Best bet hence is support@strangeloopgames.com, but they also cannot diagnose any network issues on your end - they ultimately only can give tips on how to find the cause. If there is an issue with our servers, a different error will be provided.
