### ISSUE TITLE
USER ISSUE: Cannot create custom game

### ISSUE THREAD

**Issue by Montgomery-Billings** [StrangeLoopGames/EcoIssues#24984]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
Change any setting and create a new world

**Expected behavior:**
Created the world with the settings I wanted

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
NO MODS

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach authentication servers. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
