### ISSUE TITLE
[Client] Deleted roles or election processes cause major issues with linked objects.

### ISSUE THREAD

**Issue by RHAtHome** [StrangeLoopGames/EcoIssues#25004]
Version: beta 0.10.2.4
OS: Win 10

The problem occurs when a settlement table that holds (for example) either an election process, title or constitution becomes disabled.
A timer starts and eventually all the things it was holding are deleted.
I have no idea why devs chose to delete, because it gives a lot of issues.

When something gets deleted, it remains in the game forever as a deleted object. You can see it exists, but there is no way to interact with it. In any object with a reference to this deleted object, the deleted object's reference gets renamed and totally bugs the game. So clearly it is not actually deleted, but merely marked as deleted, then why can't i restore it?

For example:
It started when i accidentally disabled my government office. The mayor title got deleted, which destroyed the constitution and the election process and all titles i had created at the registrar since i set the mayor to be the manager of these titles instead of my player name. When you then re-enable everything, the game gives you the default stuff everywhere. I managed to modifiy the mayor title, the election process and even the new constitution to the version they used to be, but the titles are gone, since i am somehow no longer the manager. I am still the mayor, but i can't access or see any of the titles i have created. Probably because the game renamed the original mayor title to something like "Mayor 2 revised (deleted)" and now the titles' manager references to a deleted mayor title object.

So far i have multiple ghosting election processes i can not reach from anywhere and 2 constitutions marked as invalid. I never created these constitutions, the game did when the election process became invalid, because the mayor role became deleted.

It would be SO nice if this timer would not delete the object, but mark it as detached. So that i can replace the table, reattach the object and everything just works again as if nothing happened.

This is a very frustrating and disappointing issue. After spending weeks on a town, i end up with lots of weirdly named election processes, constitutions and roles and a lot of roles from the registrar that i am literally incapable of seeing or interact with.

**Comment by D3nnis3n** [comment]
This works as intended, and as such is not a bug. When objects get disabled contained and related civics become invalid and get deleted after a grace time (in which you are warned about this fact multiple times), ensuring that the state doesn't persist eternally and / or can be abused.

The system for completely disabled settlements due to invalidity has been changed in Update 11 to instead of deleting the whole settlement only disable all laws and the settlement influence.

**Comment by RHAtHome** [comment]
I understand detaching a constitution is indeed not possible. But if this is the solution to something that could be abused, I would advise you to reconsider this solution. The warning system is faulty, it does not always give a warning and if it does, it gives you just a single one at the start. If you didn't get the warning or forget about it, the consequesnces are in my opinion way too destructive for the settlement. I was forced to use admin commands to delete all of the roles that nobody could acces anymore and then readded them. I hardly believe this is part of your intended behaviour.

The ghost objects I keep seeing and the weird renaming are just an eyesore, they don't break the game. The inaccessible titles do. It can not be intended behaviour to force a user to use admin commands.

**Comment by D3nnis3n** [comment]
We're not aware of any ghost objects, can you provide a screenshot of what you mean, I have a hard time to imagine what you mean.

Deleted civics get renamed and are purposefully no longer accessible - they need to replaced by new versions and laws with references be updated. Likewise, if access to titles was lost due to the only manager being such a removed demographic or elected title, new ones need to be created. You are not supposed to in any way manipulate the deleted ones, you can break your save by doing that. There is technical reasons why it's handled like that. There is no need to delete old titles that are inaccessible, they do no harm.

I understand you feel that is inconvenient, but it is not a bug. That doesn't exclude the possibility for the functionality to be changed at a later point, but there is no current plans to do so. Your request for that was already tracked, though.

You also have the option to disable the timer for civics in Civics.eco by setting it to a high enough timeframe - that would stop any civics from being deleted due to being invalid.

**Comment by RHAtHome** [comment]
<img width="341" alt="image_02" src="https://github.com/user-attachments/assets/c5056235-3435-4497-9edc-28a7c4a0cedc">

![image_01](https://github.com/user-attachments/assets/1a2bc65f-3a1f-4bcb-848c-90a789e720d5)

<img width="609" alt="image_03" src="https://github.com/user-attachments/assets/a3f291bd-268e-477d-80b9-1f0986ac94cd">

Image_01 shows all the invalid constitutions. They show up, marked as invalid. I can't do anything with any of them -> ghost objects. 

Image_02 shows all the inaccessible titles (BB <name>). These were not removed, so not renamed, so not possible to re-use the original names. Which means I had to come up with new names for them, which is very much not preferable. These titles were used for many things and I wanted to keep the old names.
There were properties that were owned by one of these titles, that ended up unmanaged.  The only way I could find to get this done, was to delete them as admin and then readd them with the old name, update all the references in laws etc, seize property as admin. A lot of work...
For the elected titles, I am not sure if I saw these show up anywhere else, so it could be that the only way I got to see those was with an admin command, as you said is intended. These are part of what I was referring to as ghost objects.

If something is invalid/deleted and there is no way the user can restore it or interact with it in any way (or as you call it "no longer accessible"), why is it shown?
I understand these can't simply be deleted due to existing references, deleting them would probably crash the game.

For the renaming, our election process and constitution are currently named "<name> 3", so something with the renaming before the removal didn't works that well here. I can not rename it to not have the 3, because that one already exists somewhere (probably as deleted and not renamed). This can be seen in image_03.

Thank you for your time and the mention of the Civics.eco file, i was not aware and will look into this.

**Comment by D3nnis3n** [comment]
Picture 1 (which I guess is what you declared as Picture 2) is intended behaviour, the /titles list command is a development command - they are supposed to show everything. We only lock such commands away when they are dangerous (like /meteor impact), which is not the case here. The command isn't really suitable for anything but internal purposes either, as on a big server you will see a few hundred entries there. These are not ghost objects in any case, they won't be displayed inside any actual user facing UI. I'm quite surprised you are using that at all, which is why I had no idea what you refer to.

Registrar titles are not civic titles, they cannot become invalid - as such they aren't removed. The issue you faced can also happen naturally though, for example when the only manager of a title leaves the game or you purposefully delete the manager title, instead of loosing it by accident, this simply requires attention to what a user is doing - if everything fails there is a simple admin command to fix this issue and is safe to use, but you can also use the /edit command to bring up the dev menu - important: Any change you make in that menu is valid immediately, even if you didn't press submit. But that isn't necessary as you can just create a new title with a new name.

Picture 2 (which is Picture 1 for you) shows a known issue when the constitution is automatically reset and is already tracked.

In Picture 3 I assume you are refering to the constitution number, as mentioned before constitutions don't work the same as other civics and do not get renamed - there is no way for a constitution to ever reset or change without amendments, as such a constitution is always permanent and does not get renamed. It only did in your case, as the rescue mechanism kicked in to reset your settlement after a core title was deleted. This is also the cause for the bug in Picture 2 - the system is not made for the idea of multiple constitutions to have existed and the rescue mechanism is pretty new and didn't exist before. You should not be able to select normal civics anywhere that were removed.

**Comment by RHAtHome** [comment]
Picture 1 and 2 indeed got swapped.

The reason I used the /titles command is that I went to the registrar, saw 0 titles and wanted to know what the hell was wrong. At this moment I was unaware of any invalid structures, processes or titles. It seemed like the intended way to show all known titles, which gave me the exact information that I wanted.
I was not aware of titles not being settlement bound. It makes a lot more sense it works the way it does knowing that (the registrar is crafted at the settlement crafting table I believe, so I assumed it was settlement bound).

I understand your explanation about the title and how it can and should become inaccessible. I agree on this reasoning. You also basically say that you rely on people to pay attention before/when they do something like this.
The thing is, this was an accidentally triggered process that nobody was aware of, with a lot of "collateral" damage. Nobody wanted anything to be deleted. Not being able to restore it when this does happen is well... inconvenient. No checks were done, because nobody knew.
If something can have this much of an effect and you, as a developer, rely on people to pay attention, make (and keep!) them aware of the threat and risks. If you expect a player to keep an eye on their settlement being valid, notify them when it isn't. Giving a single 60 minute notification at the start is in my opinion not enough. It seems that you understood my point in this already though.

As for picture 3, i was also referring to the name of the election process which is visible here. Same issue, same story.

And yes, what happened here was a broken election process, which broke the mayor title, which broke the constitution and removed access to all titles. A single building became invalid and caused a snowball. Your system did indeed prevent it from falling apart entirely and it was theoretically possible to restore things without admin commands. We would just have ended up with unmanaged titles (which is intended behavior) and had to create new ones.

I'm glad at least I found something that happens extremely rarely. =)

**Comment by D3nnis3n** [comment]
Yeh, it is fully fine to use that command - it's not harmful. It is intended for what you think - but that information is typically only relevant for development purposes. On a normal server there can be hundreds of titles as every single player can create them freely. Users are supposed to always interact with the UI's and when something isn't visible in the UI we did that on purpose (like with removed civics that are of no relevance to a user anymore). I'm not sure where the use of seeing a list of all titles is for a user - the ones they made themselves (and have access to) are in their own registrar. Titles typically aren't necessary to be beknown to others, other than maybe for cooperation in civics creation, but then there typically is talking about the civic (like in parliament).

I fully understand the frustration as well, don't get me wrong. It is generally important to take good care of settlements and when working with civics - it also requires a high amount of trust as a builder that you authorize on your city halls can in malicious ways remove your laws given they are bound to objects not "ethereal". When working with civics it's always important to keep that in mind - as such typically this, if at all, only happens once. Civics can do much worse things, a simple mistake in coding could stop everyone on the server from doing anything in a federation - these mechanics are extremely powerful, but they also require in-depth responsibility.

The problem with invalidity hints is that it is problematic to determine who to notify to begin with. We had a lot of complaints in the past that the notifications for invalidity of settlement objects are very annoying to people as they always happen when you move an object or just pick it up for building something as well. (Given you could forget to put them down again, but when objects aren't placed we can't detect them anymore - as such we cannot send repeat notifications, that only works when a in-world civic is invalid) As such we tuned them down and only send them to people that have access to the plot the civics are on and could do something - priorly we sent them to all settlement members so they could inform someone as well -, as when people think it's too much they also do no longer care about them when they pop up. This is something where I don't know immediately how to get the attention of people but without annoying them. We haven't found the right way yet, but I doubt we'll soon. Most people ignore notifications, no matter how intensive we make them - or rather even, they ignore them more the more intensive we make them. That is a sad reality that we can't really change - and given the rarity of such an issue it's not resource efficient to put a lot of development time into a problem that in the end will never satisfy everyone when we could use the time to work on a new feature.

Orphaning is a system that specifically holds civics in "limbo" when their objects were picked up, that system doesn't currently work when things become invalid / deleted, but I'll suggest that. I can't promise anything, though.
