### ISSUE TITLE
USER ISSUE: I can no longer play my 5 worlds or play solo

### ISSUE THREAD

**Issue by Moonmedicine** [StrangeLoopGames/EcoIssues#25023]
\
**User Id: (Not logged user)**
**Version:** 0.10.2.4 beta release-674

**Steps to Reproduce:**
logging into one of 5 worlds

**Expected behavior:**
they should have allowed me into the games

**Actual behavior:**
The following error message popped up:
```
Invalid login info.

<size=60.00%>No response from auth server</size>
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods.  I used to use wemod once in a while just so I wouldn't have to constantly eat but even without using it I can't play the game solo anymore.  The game is useless to me without solo.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Moonmedicine** [comment]
please let me know how to fix this issue because at this time, this game is a brick to me

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach authentication servers. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to and are not using blocked VPN's, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
