### ISSUE TITLE
USER ISSUE: Help	

### ISSUE THREAD

**Issue by oithatguy** [StrangeLoopGames/EcoIssues#25020]
\
**User Id: (360440b2-73ac-4fc7-5a69-08dc8d11157e)**
**Version:** 0.11.0.0 beta playtest-476

**Steps to Reproduce:**
I cant log into my account when creating server all passwords etc are correct

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
This server is in offline mode, but you are not - you cannot join it until it has been restarted in online mode.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Please reach out in discord in #playtest, this can't be handled through bug report system.
What it says is that the server you are trying to connect to is in offline mode, which automatically happens if your login fails or you determine the server to be. Then you cannot connect to it when your client is online. Everything here seems working correct, maybe a usage problem.

**Comment by oithatguy** [comment]
Yet I use my account to sign in and it consistently fails soooo offline was
the only way to turn server on. How can I get my login details to actually
work

**Comment by oithatguy** [comment]
I have 3 yet none work
