### ISSUE TITLE
USER ISSUE: Issue picking up materials on my own property

### ISSUE THREAD

**Issue by Blackmanni** [StrangeLoopGames/EcoIssues#25086]
\
**User Id: (5e340226-0806-4c49-bf70-08dcbd51a712)**
**Version:** 0.11.0.1 beta release-702

**Steps to Reproduce:**
1. Mine sandstone or limestone within my own property
2. attempt to pick it up
3. Error noting i cant due to me being on someone elses property when the other persons place is well away from myown

**Expected behavior:**
been able to pick up sandstone

**Actual behavior:**
error: on someone elses property

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods installed

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by Blackmanni** [comment]
[Player-prev.log](https://github.com/user-attachments/files/16681189/Player-prev.log)

**Comment by D3nnis3n** [comment]
That works as intended, the root cause of the problem is already reported here: https://github.com/StrangeLoopGames/EcoIssues/issues/25037

If a tree or stone is hit on a different property, the authentication will be set to it. E.g. a tree that was cut on one property, rolling over to the other is still property of the person that owns the property it originally stood on. The same applies to rubble - that rubble isn't from your mine.
