### ISSUE TITLE
USER ISSUE: What is this, offline/online

### ISSUE THREAD

**Issue by praetorian228** [StrangeLoopGames/EcoIssues#25097]
\
**User Id: (449bbdd2-10eb-4d85-24d4-08dc8cbaa722)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Create server, IP to connect

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
This server is in offline mode, but you are not - you cannot join it until it has been restarted in online mode.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No and Yes

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Server is in offline mode, but needs to be in online mode to be able to play on it with an online client.

Make sure you have logged in correctly to the server, it otherwise starts in offline mode automatically.

Can reach out to support@strangeloopgames.com if you have any account problems, but this is not a bug.
