### ISSUE TITLE
USER ISSUE: Large hanging Wood Sign Needs to be on the floor (can't put it on a wall to hang)

### ISSUE THREAD

**Issue by ShoppyCodes** [StrangeLoopGames/EcoIssues#25105]
\
**User Id: (3a9f240e-89e5-44de-4d34-08dc8d11157e)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Try to place Large hanging Wood Sign on a wall

**Expected behavior:**
Allowed me to place it on the wall

**Actual behavior:**
Says that it needs to be on the ground even though it is a HANGING sign.

**Do you have mods installed? Does the issue happen when no mods are installed?:**
On Giant Panda, so I think no mods?

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file
![image](https://github.com/user-attachments/assets/560995a4-7659-4416-8369-6111124ff41e)
![image](https://github.com/user-attachments/assets/9b60bff4-6527-457c-a75a-8f9f763678ca)

**Comment by Daniel-Magulado** [comment]
Hi @ShoppyCodes,

Thank you for submitting the bug report. I can confirm that the issue is specific to large hanging wood signs, as other hanging signs are working as intended. I have created an internal bug report so that our development team can implement a fix in the upcoming game updates.

Reference number: ECO-36238

**Comment by D3nnis3n** [comment]
Will be addressed via https://github.com/StrangeLoopGames/Eco/pull/14445.
