### ISSUE TITLE
USER ISSUE: Abandoning a newly acquired specialty doesn't work

### ISSUE THREAD

**Issue by DeciusBrutus** [StrangeLoopGames/EcoIssues#25116]
\
**User Id: (94e3416a-ad9f-4d9a-c85e-08dcbd8319be)**
**Version:** 0.11.0.2 beta release-707

**Steps to Reproduce:**
Accidentally gain a new speciality, then abandon it.

**Expected behavior:**
The XP refunded for abandoning your most recent speciality should be the amount needed to get it and provide enough for a star	

**Actual behavior:**
It provides no eperiecnce

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is not a bug, the abandon feature by default gives no XP back and even at 100% refund rate configured it will only give back the amount of XP that was required to get your _last_ star, but every new star costs more XP, so abandoning a specialty will never provide you with a new star on its own if you haven't gotten other XP progress to your next star yet.

This is not a refund specialty feature, it is intended to allow you to drop a specialty to take a different one with already accumulated XP on servers that limit how many specialties you can have in total, even if you have more stars than that. That allows to for example, in later game, switch into a profession that is now in need due to players with that profession no longer playing.
