### ISSUE TITLE
almost all servers dont respond to ping

### ISSUE THREAD

**Issue by Arranoa-jolasten** [StrangeLoopGames/EcoIssues#25127]
![image](https://github.com/user-attachments/assets/47d7c660-7fc3-4183-9404-93719b4828b4)

**Comment by D3nnis3n** [comment]
Not reproducible:
![image](https://github.com/user-attachments/assets/1900cca1-a6b1-4422-9c8e-b1a07b1dbf25)

Server owners need to ensure they have correctly set RemoteAddress in Network.eco.

**Comment by Arranoa-jolasten** [comment]
i litteraly see it in your screenshot :D....

**Comment by D3nnis3n** [comment]
Yes, that's a few servers that seemingly have not set RemoteAddress, the vast majority of active servers has no issues.

I noted that an action needs to be taken on the server side to address the problem, it's a configuration fault. We could make a discord announcement, I guess.

**Comment by Arranoa-jolasten** [comment]
i have been doing this for a long time and i never heared or knew about 🤔

**Comment by D3nnis3n** [comment]
We do have a pinned message since early 2023 on Discord:
![image](https://github.com/user-attachments/assets/bea0411c-dda6-44cc-9697-49af34ba60ac)

But yes, I agree this should work much easier, which is why I made a internal task to do so, but that will likely not make it within 11.0, as it needs more in-depth changes, especially to support servers with multi-ip or switching ip setups - which are the reason for why a static IP has to be provided.
