### ISSUE TITLE
USER ISSUE: strangloop server no connection

### ISSUE THREAD

**Issue by seelenhol** [StrangeLoopGames/EcoIssues#25153]
\
**User Id: (00000000-0000-0000-0000-000000000000)**
**Version:** 0.11.0.4 beta release-722

**Steps to Reproduce:**
i cann´t play eco on line

**Expected behavior:**
be playable online

**Actual behavior:**
The following error message popped up:
```
You are in offline mode, but this server is not - you cannot join it until your connection to the Strange Loop servers has been restored.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no mods

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach the Strange Cloud and can only play in offline mode on local servers as long as that persists. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
