### ISSUE TITLE
WebURL wrong when connected over Relay Server

### ISSUE THREAD

**Issue by JulianMa** [StrangeLoopGames/EcoIssues#25156]
In some specific Server Configurations, pressing the G button will send users to either `http://54.244.203.197:3001` OR `http//3.123.89.127:3001`

We received reports of our calculator mod sending people to some strange ip, instead of the local http server, so i looked into this.
It turns out, that the EcoClient is taking the IP-Address of the Socket which it is connected to as WebURL, when the `WebServerUrl` config variable is not set.

This is problematic for Servers behind NAT or without set `RemoteAddress`, because the remote IPAddress of that Socket is actually the Address of the Relay Server the Client is connected to (either `eu.relay.play.eco` OR `us.relay.play.eco`).

This causes confusion about weird foreign IP's being opened from the Client.

Maybe it would be better to show some kind of error message to the user? The correct adress can't be determined anyway in that case.

**Comment by D3nnis3n** [comment]
This is known and has been classified as Won't Fix before, the system will detect the Relay Address as the Server Address.
Connection via Relay Server is mostly a fallback mechanism that allows players to connect to incorrectly configured servers that are not otherwise reachable. A correct server configuration always requires both setting WebServerURL and RemoteAddress, setting the latter also prevents the necessity to connect via Relay in most cases. Administrators should make sure that both are always set correctly.
