### ISSUE TITLE
USER ISSUE: I can't play on any server for more than a feww weeks((

### ISSUE THREAD

**Issue by vovikgoodman** [StrangeLoopGames/EcoIssues#25178]
\
**User Id: (00000000-0000-0000-0000-000000000000)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
I can’t play on any server for more than a few weeks, I’ve already reinstalled the game and tried logging in with a VPN, i can’t log into any server, the “new game” button is offline, something related either to my account or to the servers, but definitely not to my device or internet connection also, when I start the game, I get an error that the game is running offline and I won’t be able to connect to the servers

**Expected behavior:**

**Actual behavior:**

**Do you have mods installed? Does the issue happen when no mods are installed?:**
I didn't install any mods myself, but played on moded servers

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/Eco
[Player.log](https://github.com/user-attachments/files/17105873/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17105875/Player-prev.log)
Issues/wiki/Getting-the-Eco-game-log-file

**Comment by vovikgoodman** [comment]
The following error message popped up:
```
You are in offline mode, but this server is not - you cannot join it until your connection to the Strange Loop servers has been restored.
```

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach the Strange Cloud and can only play in offline mode on local servers as long as that persists. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
