### ISSUE TITLE
USER ISSUE: CONNECTION SERVER

### ISSUE THREAD

**Issue by FOXFOXYS** [StrangeLoopGames/EcoIssues#25184]
\
**User Id: (d5a17903-7b5f-4367-7281-08dc8d1bff58)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**

**Expected behavior:**
Ce connecter aux 
serveur 

**Actual behavior:**
Le message d'erreur suivant est apparu :
```
Server encountered an exception:

<size=60.00%>Exception: FileNotFoundException
Message:
Source:Eco.Plugins

System.IO.FileNotFoundException: 
File name: 'PlayFabAllSDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Eco.Plugins.Networking.Client.FinishAuthenticateAsync(String version, String username)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Eco.Plugins.Networking.Client.FinishAuthenticateAsync(String version, String username)
   at Eco.Plugins.Networking.Client.AuthenticateOnline(String worldTicket, String username, String version)
Outer Exceptions:
One or more errors occurred. ()</size>

```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
AUCUN MODS INSTALLER

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
Your installation is missing necessary files, this typically happens due to antivirus software blocking access to or deleting them. Please remove any antivirus software from your computer, add an exception for Eco to Windows Defender and then verify Eco files via Steam. For any further requests please reach out to support@strangeloopgames.com.
