### ISSUE TITLE
Game freezes after trying to join and when i join, i only have max 4fps

### ISSUE THREAD

**Issue by TimjoinLP** [StrangeLoopGames/EcoIssues#25195]
[Player.log](https://github.com/user-attachments/files/17329667/Player.log)
[Player-prev.log](https://github.com/user-attachments/files/17329668/Player-prev.log)

**Comment by D3nnis3n** [comment]
Is this issue persisting in 11.1?

The log is full of errors, especially connection related - I actually can't even see the attempt to join a server being successful in there, due to an auth error?

Also using a Intel Arc graphics card, we honestly have no experience with those so far, so not sure if that could play any role - they are not in the list of supported cards for Eco.

**Comment by D3nnis3n** [comment]
Closing due to no further information provided. Feel free to open a new issue if the proble reappears.
