### ISSUE TITLE
USER ISSUE: Game keeps telling me I can't connect to SLG

### ISSUE THREAD

**Issue by dragonisk** [StrangeLoopGames/EcoIssues#25194]
\
**User Id: (00000000-0000-0000-0000-000000000000)**
**Version:** 0.11.0.6 beta release-741

**Steps to Reproduce:**
I opened the game today and was asked to re-do my avatar which confused me since I've already done that two weeks ago. After redoing my avatar I keep getting put into offline mode even though I'm connected to the internet.

**Expected behavior:**
I shouldn't have been asked to redo my avatar and I should be able to connect to the game without issue

**Actual behavior:**
The following error message popped up:
```
You are in offline mode, but this server is not - you cannot join it until your connection to the Strange Loop servers has been restored.
```

**Do you have mods installed? Does the issue happen when no mods are installed?:**
No mods on my end.

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This is a local networking problem, you are unable to reach the Strange Cloud and can only play in offline mode on local servers as long as that persists. Make sure you're not having any security software or firewall blocking your connection or Eco's ability to, check if there is issues with IPV6 configured and otherwise reach out to [support@strangeloopgames.com](mailto:support@strangeloopgames.com). This is not a bug, though.
