### ISSUE TITLE
Banning certain Server names

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#2522]
I have recently seen and gotten complains about offensive server names. We need to build on our server browser site a filter where we can remove servers with an offensive name from the public server list.

**Comment by MarjieAVolk** [comment]
Don't think this is a web task

**Comment by mpkmix** [comment]
why not? to be honestly I would like to know how ECO's team solve this problem

**Comment by MarjieAVolk** [comment]
Because people don't see a list of server names on our website anywhere, the list is in the desktop client

**Comment by pamduncan** [comment]
Due to the fact that I get this issue from both sides - as NBT does I get at least one contact a day with people telling me about an offensive server name and as a server host a couple have been servers run on on my service.  To work around the issue we implemented a company policy that said we had the right to remove any server name that violated the ECO profanity filter.  We did it this way to avoid an argument that we were arbitrarily deciding on what was acceptable or not.   We added to that that policy that any server name that could be considered in violation of the law we would remove (we had an incident where the server name was explicitly soliciting favors other then game play).  If the report is of an offending name on a server we host we now just go change the name and notify that owner of the server.  That is a very localized solution because anyone can put up a public server at home with an offensive name and/or other server hosts probably don't care to take the time/effort to police issues liek this.  That means that just about any server set to public can use anything the wish as  name and expose anyone that loads the server browser to it.  Including a classroom full of children.  If possible it would be nice if names that did not ass the profanity filter sniff test either would not come online or at least were forced to be private servers that could not show in the in game browser.  It really does not matter how inappropriate a name is - its not offensive if other cannot see it.  The server would still run and could be reached by IP/Port but if the profanity filter forced it to be set a private server then no one would see it to complain.

**Comment by metachronism** [comment]
Will be really easy to circumvent this no matter what we do, I dont know how we could programmatically solve this

**Comment by mpkmix** [comment]
hi!)

you can create rules and give opportunity to game's community to report any guy and any server.

If you can't create the programme, so.. give choise to decide about servers.



>Пятница, 10 ноября 2017, 1:28 +03:00 от Eric Anderson <notifications@github.com>:
>
>Will be really easy to circumvent this no matter what we do, I dont know how we could programmatically solve this
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
MPK MIX
mpk.mix@bk.ru
