### ISSUE TITLE
MacBook M4 is not supported

### ISSUE THREAD

**Issue by thomas-illiet** [StrangeLoopGames/EcoIssues#25273]
Hello Team,

I'm creating this issue to inform you of a hardware incompatibility with the execution of this game.
On start i have only black screen....

The new MacBook M4 is unable to run this game: 
```
ERROR: Shader Curved/Minimap shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
```

PlayerLog: [Attachement](https://github.com/user-attachments/files/17881865/Player.log)

**Comment by D3nnis3n** [comment]
MacBooks with ARM processors have never been supported and there is no plan to support them currently, please refer to our compatibility list:

**Support Status of Eco on different Operating Systems**
**Windows 10+ (64 Bit):** Supported.
**Windows 10+ (32 Bit):** Supported until Update 9.6 - No longer supported or provided for later Updates.
**Linux:** Unsupported. Development builds available and provided as-is without warranty. We recommend to use Proton. (Server: Supported)
**Mac without ARM processors:** Unsupported. Development builds available and provided as-is without warranty.
**Mac with ARM processors:** Unsupported. Development builds not working at all due to processor type.

**Steam Deck:** Unsupported. Compatibility: Playable, no adjustments made. (Windows: Works. | Linux: Development build available and provided as-is without warranty.)

**Comment by thomas-illiet** [comment]
I have only one choice: wait for the new graphics engine.
