### ISSUE TITLE
USER ISSUE: Fall throught map

### ISSUE THREAD

**Issue by andrew88585** [StrangeLoopGames/EcoIssues#25285]
\
**User Id: (48e5cd7a-04e3-4c89-0932-08dd0e88bbc6)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
I set a bed near a wall. I used the first material, made of dirt. There are walls above, below, and to the left of the bed. When I exit the bed, I fall into a mine. I purchased the game because the old versions had errors....
It is because the room is only 2 blocks high, the 3 rd is the roof. When Im doing this in another place I just go above the roof.

**Expected behavior:**
Wake up in the room

**Actual behavior:**
fall

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

[Player-prev.log](https://github.com/user-attachments/files/17996450/Player-prev.log)
[Player.log](https://github.com/user-attachments/files/17996451/Player.log)

**Comment by D3nnis3n** [comment]
This is expected behaviour of the reset system when the player character cannot be placed near the position it should be after exiting a object. Neither the placement on the roof nor the one in the mine are optimal, but a vertically free position is preferable over other solutions that can come with different, more severe issues.

There is plans for improving that later down the road, but the simplest and most effective solution is to actually make the rooms high enough to provide sufficient space for placement on existing buildings for now.
