### ISSUE TITLE
USER ISSUE: time of day sped up extremely

### ISSUE THREAD

**Issue by joshxtra** [StrangeLoopGames/EcoIssues#25286]
\
**User Id: (c948644e-895d-4f22-bbf8-08dcfdbdc43c)**
**Version:** 0.11.1.2 beta release-767

**Steps to Reproduce:**
Start a new Server -> crash computer -> rejoin server		

**Expected behavior:**
everything is normal

**Actual behavior:**
Time was speed up extremely and on day lasted about 3 seconds

**Do you have mods installed? Does the issue happen when no mods are installed?:**
no

**Please provide log files. Instruction is here https://github.com/StrangeLoopGames/EcoIssues/wiki/Getting-the-Eco-game-log-file

**Comment by D3nnis3n** [comment]
This could be due to the only or last player sleeping at the time or due to fast forward having been turned on, which can be turned off via /ff 0. Both aren't bugs. Given there was no logfiles provided or reproduction steps attached, there is nothing we could investigate beyond that.

Eco saves backups of saves regularly in the /Storage/Backups folder that you could restore if you want to revert the additional passed time.

If the issue appears again, please make sure to provide logfiles and reproduction steps. The configuration for sleep and used admin commands are also relevant and so is the information if that is a single player server with only the host on it or a multiplayer server that stayed online after the crash.
