### ISSUE TITLE
[6.0.1] Hammering Small Cart, Wood Cart, Powered Cart and Excavator will send them to oblivion

### ISSUE THREAD

**Issue by wiloxe** [StrangeLoopGames/EcoIssues#2555]
So... Mentioned in the title when hammering any form of carts will remove them but instead sending it to your inventory you will lose it forever.

**Comment by MarjieAVolk** [comment]
:'( Sigh, I got this to happen once just now, and now I can't get it to happen again.  Guess It's a race condition type thing

**Comment by wiloxe** [comment]
It appears it is rare. I don't know how but it happened to me and 2 other in the same world and same day. We haven't seen this until today.

**Comment by MarjieAVolk** [comment]
You know what, I think I found it /facepalm (was putting the cart into its own inventory instead of the player inventory, gotta stop doing that)

**Comment by dmorchard** [comment]
I'm still having this occur in 6.0.3.  It seems that when player inventory is too full to accept the weight of the cart it gets deleted rather than picked up.

Repro steps...
1) Place a cart
2) Fill player inventory to near-capacity (i.e. wood cart weighs 15 kg, so player inventory of 15.1 out of 30 kg should be sufficient to cause the error)
3) Hammer the empty cart and it will disappear along with its deed
![image](https://user-images.githubusercontent.com/30359271/32661749-b9f5ef32-c5ed-11e7-9260-2053f929b471.png)
![image](https://user-images.githubusercontent.com/30359271/32661794-e1b4e78a-c5ed-11e7-86d0-2f5a9e8372d1.png)

**Comment by MarjieAVolk** [comment]
This fix is not in the full release yet, only in staging
