### ISSUE TITLE
Dialogs snap back to fully on screen when you drag them off

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2618]
Would be nice to let them be partially offscreen.  Some things like contracts should be allowed to shrink further as well.

**Comment by MarjieAVolk** [comment]
I added snapping UIs to the screen space to prevent UIs from getting lost off screen.  Not a bug.  (See also https://github.com/StrangeLoopGames/EcoIssues/issues/2168)

What I would like to do though is go through all the UI prefabs and make sure their bounding boxes are accurate, so that I can reduce/remove the screen space bounding margin thing.

What do you mean by 'shrink further'?  Do you mean the minimum size of the UI?  That is controlled on the UI prefab; the Resizable script has parameters for min size

**Comment by johnkslg** [comment]
In all windows management systems I've experienced (windows et all) you can have windows half-off the screen, which I use all the time to only view part of the window I want to see.  Our system should allow this as well.  It can pop stuff back on if the movement handle is offscreen, though.

**Comment by MarjieAVolk** [comment]
Trying out how Windows works, and the difference there is that the cursor is not allowed to go off the screen.  So it's impossible to send the handle off the screen because of that.  Hmmmm

**Comment by MarjieAVolk** [comment]
But I'm still hoping that we will move to one non-resizable window at a time, in which case this would be a moot discussion
