### ISSUE TITLE
Items in stockpile

### ISSUE THREAD

**Issue by cuda70** [StrangeLoopGames/EcoIssues#2649]
v0.6.0.3-alpha Things in the stockpile only stack to 5 not to 10 like before Is this correct ??

**Comment by wiloxe** [comment]
Logs, Bricks, Mortared Stone and ect only stack up to 5 since they take up a full block. If they stacked 10 then the amout of slots would need to be lowerd and increase the amout of stone in one slot. So they ended up with 1 slot for 5 block area. That would be 20 rocks and 5 of mostly everything else.

**Comment by cuda70** [comment]
Thank you for the explanation

**Comment by wiloxe** [comment]
No problem. You should join ECO's discord if you have questions :)

**Comment by MarjieAVolk** [comment]
Yep intended behavior
