### ISSUE TITLE
Move settings away from escape menu

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#2755]
Place them in a separate window that can be accessed from escape menu.

Should improve on escape menu load times as well.

**Comment by MarjieAVolk** [comment]
Like in an advanced settings menu?

**Comment by Nanders** [comment]
This:
![image](https://user-images.githubusercontent.com/6262198/32572395-3d32b170-c47f-11e7-9abc-12b9fcb3776d.png)
Should be this:
![image](https://user-images.githubusercontent.com/6262198/32572496-a2d2c10a-c47f-11e7-920d-ad1499e0bef9.png)

**Comment by Conchipedia** [comment]
possibly add a Reset to Default option? as sometimes people can move sliders, turn things on and off and cannot rememeber how is was before they started mucking about and testing things

**Comment by MarjieAVolk** [comment]
@metachronism I assigned it to you because you seem to know which settings have the highest & lowest impact to benefit ratios

**Comment by MarjieAVolk** [comment]
Also some of the settings should be removed entirely.  Like Vibrance, Eye Adaption, maybe Bloom (no idea what this even does so maybe not)... all those things that we put in there because we were like arguing over it, somebody just needs to decide and remove all those confusing settings.  Have an artist decide.

**Comment by keegan-o** [comment]
At the moment now this seems fine, but I will be happy to provide more input on menu options and color grading stuff later in dev.
