### ISSUE TITLE
Trees grow back as fast as you cut them down

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#2794]
Slow em on down?

**Comment by wiloxe** [comment]
Wait, It's back to the old growing speed again?

**Comment by metachronism** [comment]
it takes 5 days for them to grow back, thats too fast?

**Comment by Conchipedia** [comment]
i always remove my tree stumps and work deeper into the forest surrounding my claim, and i see little wild trees appearing as they normally do, this is in 6.0.3 but i didnt notice trees growing too fast because unless the trees in a local area are are hammered by players the growth is ok, as its not worth touching a little tree as you dont get that much from it anyway and if its really small one hit makes the whole tree disappear

**Comment by Conchipedia** [comment]
did notice something by accident in 6.0.3 if i hoe the central block under a tree the whole tree just vanishes

**Comment by Nanders** [comment]
The problem is the baby trees appearing as soon as you clear a forest, not fully-grown ones.
