### ISSUE TITLE
Eco Launcher Takes Long Time to Load

### ISSUE THREAD

**Issue by starcitsura** [StrangeLoopGames/EcoIssues#2892]
When launching Eco.exe, it frequently takes a long time to load.
[https://youtu.be/QH9x3soYptU](https://youtu.be/QH9x3soYptU)
I suspect a fresh reboot makes the problem more likely to happen.

**Comment by pamduncan** [comment]
Just as a note, this has apparently been an issue for some people for some time.  No one mentioned it assuming that the client might just need a very long time to load.  It was not until someone was getting the normal pretty quick game start up and other times getting a game start up the took many minutes to load that they brought it up asking 'what was expected'.  Most report a very quick load, which is the usual experience but some people have been dealing with the game taking up to 3 minute to start up and load the opening screen.  I first wondered if this was new in 6.1 but those with the long start ups tell me that its always been this way for them since they started playing - far back as 5.0 from those I was talking with.  The ones that say it takes a long time never reported it because it always has taken that long on ever game start and they assumed it was supposed to take that long.  One other person did report that they have it load quickly and take a long time like Starcitsura and its been that way a long time but they did not report it prior to this so I guess Its pretty rare - just a  few with this issue but thought it might be something you would want Starcitsura to make an issue about so you could look into it.
