### ISSUE TITLE
Experiment with a more GC-friendly MemoryStream implementation

### ISSUE THREAD

**Issue by knexer** [StrangeLoopGames/EcoIssues#2957]
https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

The MemoryStream in ZipBlob.Persist is doing lots of allocation on the large object heap - it should be pooled (if it isn't already) to avoid fragmentation since the GC doesn't compact the LOH.  Friend suggests the above library.

**Comment by metachronism** [comment]
theres placeholder code to already do this, and we'd have to be on net46 on the client which is still "experimental"

**Comment by ndrwrbgs** [comment]
If you have issues with LOH memory pressure, you can always do periodic [forced LOH GC](https://msdn.microsoft.com/en-us/library/system.runtime.gcsettings.largeobjectheapcompactionmode(v=vs.110).aspx) collections.

If the servers often run long periods of time, it's probably worth it to have a short pause very few hours (on a timer) rather than let it run out of memory - if you have any reports of that happening.
