### ISSUE TITLE
Can eat Birch Tree Seed but not Cedar Tree Seed

### ISSUE THREAD

**Issue by brad992** [StrangeLoopGames/EcoIssues#3056]
Found this out when planting trees, when trying to click a soil patch and missing, you are able to eat Birch but not Cedar seeds when right clicking

**Comment by MarjieAVolk** [comment]
Yeah it's because one has nutrients on it and the other doesn't.  For the record, you can eat both if you show your cursor and right click on it with your cursor.

@craig-jong I decided to allow you to eat seeds with right click only if they have nutrients - (a) does that seem reasonable?  And (b) want to update the nutrients on seeds with that in mind?

**Comment by craig-jong** [comment]
should be fixed
