### ISSUE TITLE
Brush pile for debris

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3083]
I feel like a brush pile is needed for all that early on wood pulp that's is built up. something similar to a stockpile but solely for wood pulp

**Comment by Huntermeign** [comment]
Wood pulp isn't garbage. The only thing I can think of that's garbage is extra papers floating around from empty deeds and scrolls from research books to go unlearned. Brush pile makes sense because you don't want to let it decompose in the compost pile (assuming that's its function) because you want to make pitch later on but you aren't a Mason yet so you can't make campifire pitch. And shoving a bunch of sticks in a chest sounds as appealing as sticking a bunch of dirt in a chest. I say its a good early on implementation. In fact theres other things you can do to. You can choose to set it on fire as a bonfire and that could be your 'garbage' disposal
