### ISSUE TITLE
Brodie Bug: Show Avatar in world while youre choosing parameters, with third person

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3097]
Camera can move around them, or you can control it with the mouse. The UI can hide while this is happening till you accept the character.

**Comment by MarjieAVolk** [comment]
Okay so first of all, is this instead of https://github.com/StrangeLoopGames/EcoIssues/issues/3096?

And second of all, I added the ability to see your avatar walking vs standing in the edit screen recently, which I think is important because of the walking animation slider.  This wouldn't be compatible with that.

**Comment by johnkslg** [comment]
![image](https://user-images.githubusercontent.com/3536496/34853457-acf6e620-f6e8-11e7-9d2a-c527c5aaeca9.png)
Basically this shouldnt be the intro to Eco!
- Remove posture slider, can either lock all animations to male/female or just make both genders use the same animation.
- Hide the rest of the UI until the character is locked in.
- Showing the avatar in 3rd person with camera rotation would be ideal
- Text explaining what you need to do.

Since its the first thing you do in the game it should be pretty polished.

**Comment by SeanAtr0n** [comment]
looking into it
