### ISSUE TITLE
I know "be able to drop items" has already been posted but I just wanted to say how things went for me.

### ISSUE THREAD

**Issue by dassmatte** [StrangeLoopGames/EcoIssues#3127]
I just started playing again to see what has happened in the game since I last played and forgot that you couldn't drop items, so I started a new game and didn't unlock chest early and then I got full inventory and nowhere to put it..., what should I do then? Go somewhere and edit a savefile? I just assumed that you could drop items because otherwise you could get "gridlocked". These new wood pulp things get in the way all the time when you're getting wood so you accidently pick them up, atleast you should be able to put them down again so those was filling up my whole inventory without me being able to do anything.

**Comment by Huntermeign** [comment]
Well i do know trading to people in person is going to be a thing, but yeah being able to drop wood pulp into a pile (Brush piles were mentioned earlier, this could be how to do it)

**Comment by pamduncan** [comment]
I think the ability to just drop items to get rid of them is not possible in the game because that is a 'magical' way to get rid of trash that should be dealt with in some way as you would handle a ting polluting the world with out just having it disappear cause you drop it.  You can process debris to wood pulp and other recipes to get rid of it, and it can be placed in chests to store it out of the way.   There are a few things that end up cluttering the world and you have to get used to dealing with - like seeds but can't just be dealt with by dropping them and having them disappear.  I hope that maybe they will had trash cans and maybe landfills at some point so we know we are dealing with left overs and trash

**Comment by TreeNuts** [comment]
Maybe if they added a way to deal with the 'trash' items properly. Maybe like extra skill pages could be used as fuel in the camp fire.

**Comment by Huntermeign** [comment]
I agree that items shouldn't just disappear. Like in real life, we either burn our trash, bury it, or send it out to sea. This is ideal, except some items, like scrolls from a research book or deeds when claiming a property also magically appear. There should be a way to make them disappear such as placing them back into the research book or like burning or throwing them out to the water to float around and be eaten by fish which later effects water pollution. This would add another element to the game where people have to consider where their trash/extra items go. Seeds imo should also have the option to crush them into seed oil and the leftovers could be used in the compost pile we are waiting for.

**Comment by MarjieAVolk** [comment]
Yeah, this is definitely a concern.  We want to add a way to drop items as trash, but we haven't decided how we want to address it yet.  This feature is not planned for beta, but we're hoping to work on it shortly after the beta release: https://trello.com/b/BK1Fma6l/eco-roadmap

So closing this as won't fix for now; but these issues should be addressed at some point.
