### ISSUE TITLE
[Art] Mortared Stone (wall,Roof and Floor) leave gaps when placed 6.3.1

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3205]
![snap792](https://user-images.githubusercontent.com/29383891/34327628-36530d4e-e8c1-11e7-9646-2e1df5048de0.png)
![snap793](https://user-images.githubusercontent.com/29383891/34327643-7c24ace2-e8c1-11e7-9e17-828ddde78da0.png)
![snap794](https://user-images.githubusercontent.com/29383891/34327645-88d5fb30-e8c1-11e7-96de-a705cd9fe61b.png)

**Comment by Conchipedia** [comment]
[Art] Logs and Mortared Stone will not join together nicely 6.3.1 #3221
for got to add it to this one

**Comment by Conchipedia** [comment]
![snap1672](https://user-images.githubusercontent.com/29383891/36106089-40526636-100e-11e8-8d26-fc9aeadad7ce.png)
![snap1673](https://user-images.githubusercontent.com/29383891/36106090-40739932-100e-11e8-853d-36edc51a29ae.png)
Still a problem in 7.1.0 @keegan-o  way more noticeable using Floor block, having to change to solid Block in design to avoid the gaps

**Comment by Conchipedia** [comment]
![snap1668](https://user-images.githubusercontent.com/29383891/36186196-4cc96f90-1135-11e8-902b-bab54a3bd085.png)

Even A Tortoise came to check the Holes in the joints, he didnt seem impressed as he wasn't smiling

**Comment by keegan-o** [comment]
I can now actually suggest that you use Stone Road for this purpose-- it will have the rims around the top and bottom like Stone Floor but meet up with the edges and so have no gaps. I might make it so floors reach the very edge at some point but for now since that would sacrifice their look a bit I will leave it to the stone road block to fill this role.
![image](https://user-images.githubusercontent.com/14983165/37230978-32aafbe4-239e-11e8-8c5d-b2353cb6f414.png)

What do you think Conchita, should I just make the Mortared Stone Floors like the Stone Road only with the other central texture? That might very well be where I go.

**Comment by Conchipedia** [comment]
i trust your decision @keegan-o if you make them Square it should solve the gap problem on the diagonals, and if i place the other type of solid block next to them it should give a slight pattern change for a very rough mosaic type effect

**Comment by keegan-o** [comment]
closing this now, having blocks that fill the gap and look good will be improved as we add more forms
