### ISSUE TITLE
the layer "WaterSpread" does not exist

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3246]
Exception: The layer "WaterSpread" does not exist.
WorldLayerManager.RequestLayerView (System.String layerName, System.Action`1 ReceiveView) (at Assets/Scripts/Managers/WorldLayerManager.cs:68)
WorldLayerManager.RequestLayer (System.String layerName, System.Action`1 ReceiveLayer) (at Assets/Scripts/Managers/WorldLayerManager.cs:84)
LayerAudio.Init () (at Assets/Art/Audio/Scripts/LayerAudio.cs:33)
LayerAudio.GetLayerAudioData (Vector3 position) (at Assets/Art/Audio/Scripts/LayerAudio.cs:43)
AmbientAudioPlayer.Update () (at Assets/AmbientAudioPlayer.cs:50)

This causes problems on the client, as it breaks a lot of water ambient audio

**Comment by knexer** [comment]
Right, I saw that.  Didn't realize there were client use cases for specific layers like this.

This seems like it's very much not the right way to handle ambient audio.  It conflates two otherwise independent requirements (there should be water sounds near water, and fresh water should encourage plant growth in the surrounding area).  Also, using world layers for this sort of purpose is... profoundly bizarre.  World layers are specifically meant as a tool for ecosystem (and, maybe, someday) climate simulation.  More to the point, they're 2d, and have no notion of occlusion.

We could fix this by adding back a WaterSpread-like layer, but it seems vastly preferable to use a different method for water ambient audio instead.  On the gripping hand, if we want to fix this quickly we might just have to bandaid it anyways.  @Nanders , what are your thoughts on this?

**Comment by MarjieAVolk** [comment]
I get what you're saying about the 2d/3d issue and stuff, but it seems to me that using world layers directly for client side art and audio is fine.  Another example is the pollution layer or whatever, which we use to apply that pollution effect to the world.  IMO we should have more world layers animated like that, so that the layers actually have a detectable presence in the world.  Although in this case I guess I would think it should use the water layer if there is one, find the distance to the nearest water etc, instead of the water spread layer.  Since as you say water spread doesn't have to always mean a body of water nearby anymore.

**Comment by Nanders** [comment]
Using the waterspread layer was only ever a band-aid solution. We have been intending to have dedicated audio layers for a while (or something similar. potentially will be needed for more dynamic music), but that has been backburnered.

It isn't really obvious to me what the best solution is. Need a way to differentiate rivers, streams, oceans, aqueducts, and waterfalls. 

Would want to discuss this more, but we probably need a band-aid just for now.
