### ISSUE TITLE
Research Efficiency benefit seems to be x10

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#3266]
level 1 gives 200% cost reduction

**Comment by MarjieAVolk** [comment]
By the way, having more than a 100% reduction breaks everything, there's like negative items and all kinds of weird stuff

**Comment by MarjieAVolk** [comment]
Actually I think that's what is causing this one: https://github.com/StrangeLoopGames/EcoIssues/issues/3230  So gonna close that one

**Comment by CallMeOzz** [comment]
came here to report this, and saw that it already existed.

Figured I could add some additional details.  At first glance, it appears that the problem resides in the definition for the "MultiplicativeStrategy" static in \Mods\AutoGen\Tech\ResearchEfficiency.cs.  As the original poster suggested the values in the float array appear to 10x the expected value (e.g. 2 instead of .2)

As packaged within the Staging Alpha 6.4.0 #A6a22be6 build, the definition appears to be:

```
public static ModificationStrategy MultiplicativeStrategy = 
            new MultiplicativeStrategy(new float[] { 1, 1 - 2, 1 - 3.5f, 1 - 5, 1 - 6.5f, 1 - 8 });
```
Instead, I believe the static should be defined as: 
 
```
public static ModificationStrategy MultiplicativeStrategy = 
            new MultiplicativeStrategy(new float[] { 1, 1 - 0.2f, 1 - 0.35f, 1 - 0.5f, 1 - 0.65f, 1 - 0.8f });

```

Using the default definition, the Research Efficiency tooltip reads like this:

> Reduce Brick cost by 200% (next rank 350%) 

Using the default definition, the amount of needed materials (for crfting any skill book) ends up as a negative value,
