### ISSUE TITLE
Backup wont load on new Server Installation

### ISSUE THREAD

**Issue by Subtra** [StrangeLoopGames/EcoIssues#3355]
Did you guys had it happen that Backups dont work after reinstalling the Server?
It was like that for our Server. first it was still online but trying to enter it was trying to create the world and booted me out of the Server. Other Servers were still working. So we tried to restart it but it didnt came back online at all. After some Support Stuff happened we got an new install so we tried to apply the backup. But it didnt work, even with standart Settings. But with a fresh start it worked out. Providing that Backup below, please look what we did wrong or if the Game saved something wrong. Hope for a good answer:

https://mega.nz/#!CdNzlSCS!TTbfELpdoWa4xNx-dgEVGWLQCsjLav8TIr6_HlicYsg

**Comment by pamduncan** [comment]
I believe they are being hosted at Nitrado and that host has had this issue since they started offering Eco.  Several other hosts have contacted them about how to resolve this and they have not yet taken steps to do this.  Their clients have had to move to other providers to get games that would save the Game.eco correctly and then have it where it would be available to load next time the game started.  NBT.  This is an issue on the hosts side and until they fix it so that Game.eco is back in the Storage folder for the game to use this will not be resolved.

**Comment by Subtra** [comment]
Yeah thanks for the information, just need to select a nice company that runs the game without to much issues or trouble.

**Comment by pamduncan** [comment]
The backup does have an error in it so worth having the devs look at that too

**Comment by metachronism** [comment]
Looks like your world got corrupted somehow - I did put in a fix for the backup plugin, which should prevent this bug from occurring in the future.

If you incur this error again, please reopen (with the other gamesave) and I'll take another look
