### ISSUE TITLE
Should be able to level down skills that gave you items eventually

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3382]
![image](https://user-images.githubusercontent.com/3536496/34902154-9b037dd8-f7ca-11e7-9f26-fbbc5b6bc6c9.png)

Perhaps there's a timer on this, so I can abandon old specialties mid-game for example.  Especially since these are primarily low-level skills that you'll want to abandon eventually.

**Comment by MarjieAVolk** [comment]
Oh yeah, totally forgot about this.  Well... since specialties are pretty expensive now, I think we could probably remove this restriction.  Actually, another thing we could do is have a flag on the skill saying if it's ever been leveled up, and only give items if it hasn't  Okay yeah, that seems like a good solution.
