### ISSUE TITLE
USER ISSUE: Getting confusing Put and Take options when carrying building Materials when looking at different Tables

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3428]
**Version:** 0.6.4.0 alpha staging-ca25d17a

**Steps to Reproduce:**
pickup any type of block then look at a table

![snap1094](https://user-images.githubusercontent.com/29383891/34995738-4e083912-facf-11e7-95fc-193b4be15864.png)
![snap1095](https://user-images.githubusercontent.com/29383891/34995739-4e2164a0-facf-11e7-8b62-76ec32aec3a1.png)
![snap1096](https://user-images.githubusercontent.com/29383891/34995740-4e37e270-facf-11e7-9ce5-6f606ba4fd39.png)
![snap1097](https://user-images.githubusercontent.com/29383891/34995741-4e51453a-facf-11e7-8103-73849a40494a.png)
![snap1098](https://user-images.githubusercontent.com/29383891/34995742-4e6eba66-facf-11e7-93f1-37cad6db8013.png)

**Comment by WeaselDog** [comment]
This has been updated to be more clear. For crafting tables it says "Use" instead of "Open". It also detects if you are carrying a block that can be inserted and displays the correct message:
![HoldingStone](https://user-images.githubusercontent.com/47330823/71121843-1e924400-2194-11ea-8722-1898fd935f6a.png)
![HoldingCoal](https://user-images.githubusercontent.com/47330823/71121845-1fc37100-2194-11ea-8cd8-3ddd555c18ac.png)
![MasonTableWithStone](https://user-images.githubusercontent.com/47330823/71121851-22be6180-2194-11ea-96d9-32ee8de22f11.png)
