### ISSUE TITLE
USER ISSUE: Mill Is saying "Power Grid Operational" when we haven't even built one near us yet

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3430]
**Version:** 0.6.4.0 alpha staging-ca25d17a

**Steps to Reproduce:**
I just placed a mill to get the room to detect it as a Kitchen so i could get the Room Score and then just looked at Status Tab

![snap1102](https://user-images.githubusercontent.com/29383891/34997741-18f39360-fad5-11e7-9bf0-1368dcc84e66.png)
![snap1103](https://user-images.githubusercontent.com/29383891/34997742-191679f2-fad5-11e7-9a57-d8e907bfc166.png)

**Comment by MarjieAVolk** [comment]
Hm, I think this is expected behavior if the mill is not crafting anything.  If you start trying to craft at the mill, does it disable the mill?  That is what I would expect, if not then there is a bug.

This is because the Mill itself creates a 'power grid', since it demands power, and while the mill is not operating, it requires no power, so the power grid has 0 supply and 0 demand, which is a valid state.

Thinking about how to make this more clear for players though...

**Comment by elfl0rd** [comment]
Looks fixed
![default](https://user-images.githubusercontent.com/4980243/41868635-58ddfcfa-78bf-11e8-8ece-0d94004372e9.png)

**Comment by D3nnis3n** [comment]
Issue is fixed.
