### ISSUE TITLE
Linux servers not working.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3450]

**Comment by Yorkforce** [comment]
Any idea when Beta 7 is arriving? Or if it's going to be out before steam release? Or if a hotfix can/will be applied before then?

Reason I ask is because I host the UnionWorld server, which is on Linux and we had some pretty big plans for steam release, I understand Linux servers aren't officially supported but albeit with some minor issues, its been ok up until now. 
We have put a lot of work into this so far, it would be pretty devastating for us to miss the steam release.

**Comment by metachronism** [comment]
it should work now, reverted the test change that caused the issues during startup

**Comment by Yorkforce** [comment]
Thank you very much for the quick fix!
