### ISSUE TITLE
USER ISSUE: Gameplay options

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#3511]
**Version:** 0.6.4.0 alpha

**Steps to Reproduce:**
just request to get ability maybe get following options.

1. Log cabins be nice to be able to pick the art for them the new textures art dose not look as nice as the old log cabin look. or maybe be able to have ether or in game. the new one dose not really look like a real log cabin and its so white washed. current log cabin looks like all wood was put through a planner and is more of a lumber then a log.. not very rustic.

2. ability for server admin to change how bright the game is at night and during day, there way to much gamma and player lighting is point less again.

3. option for sever admin to setup what players start with so we can maybe give them axe , hammer, and shovel stone tools right at the start so players do not have to waist points just to be able to use tools that are needed for cross skills.

example building a home requires axe , shovel, pix axe along with hammer so they always have to unlock 4. major skill trees forcing them to spend all there points and also in cress there cost by a lot making it so first thing you do as a new player is log out and wait for skills.

5.  tir 0 ability to just stack items like dirt and stone on top of each other to make basic level 0 buildings.
the doing this with stone looks great.

**Comment by metachronism** [comment]
You can already do 3, take a look at "PlayerDefaults.cs" in the mods folder, can give players whatever collection of items you so desire.

We want to do 2, but will need to add more lighting options into the game first

**Comment by midn8t** [comment]
PlayerDefaults.cs did not know that, i did not see option in dedicated server tool set so I just did not think there was option to do it.

**Comment by pamduncan** [comment]
While it can be modded in a .cs file many admins don't 1) know this or 2) know how to modify .cs files and have gotten into trouble doing so - and prefer to not touch them.  That is why this was posted :https://github.com/StrangeLoopGames/EcoIssues/issues/3512  asking that it be set as a on/off option in configuration files where an Admin only has to consider editing a true or false. Certainly instead of just on and off there could be a set of collections to pick from for configuration that would hold a different grouping of tools but, of course, the main thrust of #3512 is to be able to turn it off so players do not receive that 'boost' and have to work with others to get started, it makes sense to have just one option that does all - located in one place..

**Comment by keegan-o** [comment]
For my part of this, we made Hewn Logs darker, and will be adding in eventually a floor form that behaves as the old one did more or less. Also we will eventually add more tiers of wooden buildings for more aesthetic options/stained looks.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#316
