### ISSUE TITLE
[Suggestion] Add Admins info to World Save

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3557]
If a Player is made an Admin and the world is used again, but in a different version the player has to ask the Server owner to be made Admin Again.

Example: Hoary Marmot as this gets updated quite regularly and if we have been given Admin Rights we have to ask for them again when its updated but the world is still the same one.

Don't Add it to user Info as quite often when testing i want my Character deleted from Server but when i join again as a new Player i don't want to have to ask again to be made Admin,

**Comment by MarjieAVolk** [comment]
I am not sure now whether it would make more sense in the config vs. the world save.  I suppose we need it to be in the config in order to edit it in the server interface.  There are a few things that are like that too, that are really more part of the save but live in the config so that they can be edited.  /shrug

But one thing that is definitely a problem is that server config doesn't get saved when it should.  And/or doesn't get marked dirty when it is edited.

**Comment by Conchipedia** [comment]
it was mostly because Marmot gets updated so often and the save is the same , i didn't want to be a pain asking to be made Admin again (just was an idea) ❤️

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#311
