### ISSUE TITLE
USER ISSUE: Can't Cancel Project in carpentry table

### ISSUE THREAD

**Issue by zenwidjet** [StrangeLoopGames/EcoIssues#3577]
**Version:** 0.6.4.1 alpha

**Steps to Reproduce:**
1.setuup a carpenter table outside (not in a room) 
2.request a project for something that requires more of an item than you can carry at 1 time (5 board orders (max log carry 20 5 logs per order)
3.Cancel the request.

**Expected behavior:**
cancel 4 of the 5 and "give" me back the resources I can carry (20 of the 25 logs)

**Actual behavior:**
recieve message stating I do not have enough inventory space.

**Comment by MarjieAVolk** [comment]
This is expected behavior.  The usual solution would be to build a stockpile, so that when you cancel the order the rest of the materials can go into the stockpile.

I can see how this might be frustrating for a new player, if you've put all your materials into something and realized it doesn't work because of rooms, and don't have any stockpiles yet.  But not going to address this now.
