### ISSUE TITLE
USER ISSUE: Newly Created Singleplayer World Biomes Missing 

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3682]
**Version:** 0.7.0.0 beta staging-73643fd0
Newly Created World (Singleplayer)
No WetlandsBiome
No ForestBiome
And Ocean has both GrasslandsBiome and DesertBiome underwater
![snap1363](https://user-images.githubusercontent.com/29383891/35483619-732442ec-043c-11e8-8eb7-21f26509bab7.png)
![snap1364](https://user-images.githubusercontent.com/29383891/35483620-733d9d50-043c-11e8-8058-0f4714825f32.png)
![snap1365](https://user-images.githubusercontent.com/29383891/35483621-735800be-043c-11e8-8d8f-ff516d5f61e1.png)
Also Saltwater seems to be in rivers and Saltwater Spread seems way to much
![snap1368](https://user-images.githubusercontent.com/29383891/35483664-dc0653d6-043c-11e8-9c25-3ea2cec690b2.png)
![snap1369](https://user-images.githubusercontent.com/29383891/35483665-dc1cfbd6-043c-11e8-97d8-0a39231280a7.png)
![snap1370](https://user-images.githubusercontent.com/29383891/35483666-dc3510ae-043c-11e8-86ac-90c5542f9fa1.png)
![snap1371](https://user-images.githubusercontent.com/29383891/35483713-34a0dc96-043d-11e8-8e79-623cae34a6f8.png)
![snap1372](https://user-images.githubusercontent.com/29383891/35483714-34b98228-043d-11e8-8dec-803ef580f51f.png)

Linking to this **World layers issues #3630**

**Comment by knexer** [comment]
All of this stuff is unchanged from 6.4, except for two things:
1) default world size is smaller now (72 instead of 100), so there are fewer opportunities for wetlands/forest to appear.
2) noise distribution of rainfall and temperature was adjusted, but in a way that looks like it should have *increased* the variation.

**Comment by Conchipedia** [comment]
with Forest not appearing won't that stop where huckleberries and beans grow (as that seems to be always the place where they are most abundant)?

**Comment by knexer** [comment]
Oh, it's definitely a problem, didn't mean to imply that it wasn't :) Just giving context for myself and others who might try to fix the bug.

**Comment by knexer** [comment]
We've fiddled with the biome balance enough at this point that this isn't a high priority issue any more.  Still needs more work though.

The outstanding problems with biome balance, as I see them, are threefold:
- Because temperature varies most strongly with height, there's a paucity of desert and wetland environments, particularly on the hotter end of their spectrum, and they primarily appear on shores, which is a bit weird for deserts
- The effect of fresh water on soil moisture is quite inconsistent, especially far from the river's source, which exacerbates the scarcity of wetlands in particular.  This is because world layers is quite atrocious at detecting rivers, as you can see in the shots above ^
- Desert and wetlands look terrible when they're right next to one another - and yet they are the only two hot biomes.  We need to design a sixth biome that can fit between them, or extend grassland up into that regime somehow, or make them look good when they're adjacent / intermixed.

Thorny questions all, particularly the last, and not something to be addressed in a hotfix.

**Comment by craig-jong** [comment]
even more changes to sim should make 0 pop plants at worldgen less likely. Incoming world generation changes will change this entirely as well.
