### ISSUE TITLE
Login needs to come after title menu 

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#3718]
![image](https://user-images.githubusercontent.com/3536496/35589353-673dc87c-05b8-11e8-9cc7-78b950b0976a.png)

It should be restored to start as follows:
- Fade in world
- Fade in Eco logo
- Fade in title menu
When the user selects a menu option, it then asks them to login 

Two reasons for this:
- It's way more impactful to have that fade in sequence
- You cant quite or exit when the the login screen is up, escape does nothing.

**Comment by metachronism** [comment]
you need to login before doing anything - why hide that behind a menu option?  99% of users will never see a login anyway, since its done automatically from steam, or from a cached login.  Its strange to be presented with the screen and then force a login when you click on something that doesn't say "login"

I can tweak the fades though

**Comment by johnkslg** [comment]
I could live with a login on startup I suppose, if it had some text in there.  Welcome to Eco, login here.  And a way to exit the game, and the fades were noce.
