### ISSUE TITLE
staging-71fcbff4 - Whole world died in 1 tick

### ISSUE THREAD

**Issue by Senlarus** [StrangeLoopGames/EcoIssues#3735]
I think this was a previously reported issue, but when I went from staging 7da08558 to 71fcbff4, after about 2 minutes on the server... all of the sudden in 1 second every plant on the server died. Also there are no animals again.
![image](https://user-images.githubusercontent.com/1503963/35605370-737e743e-0616-11e8-9e12-d05d553dd629.png)

![image](https://user-images.githubusercontent.com/1503963/35605362-632c298c-0616-11e8-9c12-36d9f1bbed97.png)

**Comment by GWraith1985** [comment]
After some testing with a fresh build of the current staging release, it seems that this issue may have been caused by migrating from an older build to a new build or a config file incorrect setting. More troubleshooting needs to be taken to verify that older builds cannot be migrated correctly to the newer builds.

**Comment by Senlarus** [comment]
Ok, I did some further testing and it appears the animals went extinct during the 7da08558 build. When I migrated my previous version, a5db4bb6, which had animals they were there in the new build 71fcbff4.

Closing ticket.
