### ISSUE TITLE
Server Crash with falling tree

### ISSUE THREAD

**Issue by Hazard55** [StrangeLoopGames/EcoIssues#3754]
Caught exception: Caught exception invoking RPC CollideWithTerrain on TreeEntity!

Index was outside the bounds of the array.

Stack:
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at TreeEntity.CollideWithTerrain(Player player, Vector3i position)

It probably occured during a tree falling onto a player. The whole server crashed from it.

**Comment by knexer** [comment]
OK, latest staging build definitely does not contain the change to CollideWithTerrain that I just made, so unless you were playing on master it couldn't have been that.

And it looks like there's a HashSet 'groundHits' there that's not threadsafe; that could conceivably be the problem, though if so this must be a fairly uncommon crash since that's been like that for nearly a year.

Dropping the priority accordingly.

**Comment by Hazard55** [comment]
happened on Alpha 0.6.4.2

**Comment by SeanAtr0n** [comment]
Thanks for reporting! Will be fixed in 7.0 (hopefully it's rare enough not to cause too many issues until then, would have expected an earlier report if it was common)
