### ISSUE TITLE
[Suggestion] Having Two Version of Eco on Steam each with their own unique Manifest ID

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#3756]
When Eco is downloaded and you choose a Version under Beta tab it will download this version, But if you choose another version to play it downloads it all again
My idea would be Have The Stable release as it is with the following ID
appmanifest_382310.acf
then Add another Version of Eco for those that want to do Both Versions but not have to download each one Before playing.
so Eco (Staging) would be  a NEW Appmanifest ID
@Nanders 

from a conversation i was having With @MarjieAVolk in SLG Discord

Marjie - Today at 1:44 AM
suggest it to @Nanders , he is doing the steam related stuff

Obviously The main Game Would be in a Directory called Eco in Common Directory as it already is
and Eco (Staging) would be a New Directory for the New Cutting Edge version

**Comment by Conchipedia** [comment]
Will our SLG Account Page let us Still download and play the versions there  without the need for Steam (After Steam release) if we can do this still, Ignore this Github About two versions in Steam

**Comment by pamduncan** [comment]
As a suggestion, if two separate listing in steam is not possible that you could do what we do with other games that we need to jump back and forth between a current version and a beta/test version - I often have to run multiple versions of games, both the current version and betas or test versions that I am opted into.   When you first install a game it will, of course, download to the default setting you have for steam - for example you steam library.  If you later want to install a version you opt into - say a beta or test version, change your settings to an alternate download - either another Folder or Drive and install it to that location.   This way you do not have to reinstall each time you want to play one or the other - when you flip to opt in or opt out it will remember and not download it again. It will remember where it was installed to even if you then go back to settings and change back to your preferred steam default.   Then also when you update the "live game' it will go in you usual steam library (if that was where you originally installed it to) but if you are opted into beta/test and download that version for update it will go to where it was installed.    You do have to remember to manually change the settings option so it downloads to different folders the first time you do it.  Of course having two separate versions and two separate installs is most likely cleaner but we ended up having to do it this way because it was difficult for some games to get two different listings and installs in the Steam Library

**Comment by Nanders** [comment]
The method described by @pamduncan is possible right now.

I don't imagine we'll support older versions under new appIDs any time soon

**Comment by MarjieAVolk** [comment]
@Nanders I don't think they want older versions, I think what they want is 'latest' as one and 'staging' as one.  So people who want to test on staging can also keep playing on the stable release more easily.  (I think we will want to remove the myriad branches we have on steam now, and change it to just release and staging anyway possibly?  That's more like what we have on our own site)

**Comment by Conchipedia** [comment]
@MarjieAVolk  hit the nail on the head, with Release and Staging , one to play and one to test (without hassle of updating every time we swap between them)

**Comment by Nanders** [comment]
In which case, my above statement still stands.

Upon Release, older versions will be soft-locked behind passwords to declutter the list. 

Steam has Beta - switching for almost this express purpose.

**Comment by MarjieAVolk** [comment]
You mean this beta drop down thing?  Yeah I mean honestly it's not tooooo bad to switch back and forth.  And like this would probably be okay if our staging builds were higher quality.  But as it stands, I think nobody wants to play exclusively on staging.  They want to pop in and file some bugs, and then go back to their regular game.  So if our staging builds are bad and also it's that much harder to pop in and out of staging, there will be a lot fewer people on it.

**Comment by Nanders** [comment]
Staging will always be opt-in?
Default is and will be the released, stable build version of the game.

If people want to download multiple versions to their computer, they can use the method Pam described or they can just switch the branch.

Maybe I'm still confusing your point though.

**Comment by MarjieAVolk** [comment]
Yeah Pam's way sounds like a workaround, although I am not sure how much faster it would be.  I just think structuring the releases differently could be a lot more friendly to people who want to play on staging sometimes.  Of course staging would still be opt in, just saying less people will opt in if it's a pain to switch over, and also it's not really feasible to play on it constantly.  But on the other hand, maybe we want to keep staging less visible.  And maybe we will have been staging releases someday.  Maybe.
