### ISSUE TITLE
Fir trees don't seem to get completely deleted

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#3827]
Stump collider never gets removed
Tree object never gets deleted from the server after stump deleted + all logs picked up

Oak might have the same problems

Birch/Cedar work fine

**Comment by Nanders** [comment]
Any idea what might cause this? Unfamiliar with how the sim and trees are supposed to interact in this way.

**Comment by Senlarus** [comment]
@Nanders On my issue, #3986 it turns out it was a log not a stump. After a server reboot, when I went back to that area I saw a small thin oak log laying flat against the ground. I picked it up into my inventory and placed it in my stockpile and there is no more collision at that spot for me. I guess it wasn't a stump afterall.

**Comment by Nanders** [comment]
closing as duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/4908
