### ISSUE TITLE
USER ISSUE: Could not create save file - .eco file already exists

### ISSUE THREAD

**Issue by baradah705** [StrangeLoopGames/EcoIssues#3984]
**Version:** 0.7.0.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Could not create save file: C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\baradah705.eco already exists
```

**Comment by MarjieAVolk** [comment]
This is expected behavior if you are trying to create a new world with the same name as an existing world.  Try loading your existing world, or naming you new world something else.

It has been noted that this error message is a bit confusing, eg. https://github.com/StrangeLoopGames/EcoIssues/issues/3842
