### ISSUE TITLE
[Suggestion] Admin command to broadcast message

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#4041]
A broadcast or announcement command would be useful when informing my users that I am restarting/updating the server or for any other admin needs. Maybe have them as big as the message you get when you destroy the meteor.

**Comment by ChrisMayhew** [comment]
Great idea in my opinion.

**Comment by MarjieAVolk** [comment]
I would say, if we are going to add more tools for this, they should be closer to regular chat.  Be nice if you could create different chat channels, give them different permissions with laws, maybe enable them being treated as read-only channels if people don't have access to post in them so that they can have them turned on, maybe enable special default formatting for each channel, etc
