### ISSUE TITLE
Repair Stand Kicks user when attempting to use.

### ISSUE THREAD

**Issue by Sarongas1999** [StrangeLoopGames/EcoIssues#4074]
7.0.4 issue where a user tries to repair there item and when clicking the repair button it crashes the player out.
![screenshot_50](https://user-images.githubusercontent.com/36120114/35948738-11d3db8a-0c3c-11e8-8910-ea0a49125c38.png)

**Comment by Sarongas1999** [comment]
It seems to happen to weapons that are SPAWNED into the game.

**Comment by Sarongas1999** [comment]
So its been 100% determined that spawning items and trying to repair them kicks me.  The tools from tutorial repair fine.

**Comment by ecoemmeck** [comment]
Can also confirm that spawned standard tools cause a crash when trying to repair them.
Is it perhaps because they don't have a repair cost.
The only thing I can think of is when spawning tools as an admin you might need to spawn in say stone hammer or iron axe instead of just spawning in hammer or axe

**Comment by MarjieAVolk** [comment]
Oh I see, when you /give yourself a hammer and it's just a 'Hammer' and not a 'Stone Hammer' or something.  Yeah those tools are not meant to be spawned in. @craig-jong we need to prevent people from giving these to themselves

**Comment by craig-jong** [comment]
this was fixed a while ago. You can still give yourselves the tools, but they actually have a proper repair cost now.
