### ISSUE TITLE
Laws: groups for species

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4088]
In the species filter on actions, we really need species groups, eg. 'trees'

**Comment by thereporter42** [comment]
This comes from my post in ticket https://github.com/StrangeLoopGames/EcoIssues/issues/9076

Version: 0.7.6.3 beta

Steps to Reproduce:
Login to the game and hit L to open up the law window
Try and specify a law for all animals or all plants

Expected behavior:
To write a law that would cover all plants or all animals. 

Actual behavior:

Well the actual behavior right now is to do a law for each one of the species 
of animals separately it makes it for a novel of a law trust me I did it. 

An example of this is: 

When attempting to Harvest where (species is Bison)
If in district Hunting District #1
Then allow
Otherwise If in district Hunting District #2
Then allow
Otherwise If in district Hunting District #3
Then allow
Otherwise prevent

Ok so basically what this law does is if the species is a Bison and you are in one 
of the three hunting districts which are already setup on this server then 
allow the hunting to occur but if you are outside of these three hunting zones 
prevent the player from killing the bison. 

Now I had to specify each species separately  because there
was no way to say "all animals" in the law 

So you end up doing a law for Bison, Elk, Wolves, Turkey, Fox, Tortoise, Hare
all separately the same way as above all in one big long rule. 

It would really be easier if we could specify either "all animals" or "all plants" 
and would shorten the law a lot . 

Make it so that all animals or plants are included so that you can just
do this once instead of having to repeat it over and over again. 

An example of what the law may look like may be: 

For an animal: 

When attempting to Harvest where (species is Animal)
If in district Hunting District #1
Then allow
Otherwise If in district Hunting District #2
Then allow
Otherwise If in district Hunting District #3
Then allow
Otherwise prevent


And one for plants: 

When attempting to Harvest where (species is Plant)
If in district Gathering District #1
Then allow
Otherwise If in district Gathering District #2
Then allow
Otherwise If in district Gathering District #3
Then allow
Otherwise prevent

It would make things so much easier and simpler can you please
fix the laws this would be a great fix if you can do this because it will
shorten down the laws a lot when writing laws like this! 

My law for animals is massive right now so big I couldn't even get the whole thing 
in the screenshot.  you only see a couple of the laws for the animals. 

![hunting laws aug 25 2018](https://user-images.githubusercontent.com/38896397/44616950-5cd55880-a817-11e8-98fc-a7f5c8066372.jpg)

**Comment by MarjieAVolk** [comment]
Here's my group brainstorm list so far:

Plant 
Animal
Herbivore
Carnivore
Aquatic
Terrestrial
Edible

**Comment by Deantwo** [comment]
Maybe more informative, such as "Animal herbivore" and "Plant edible".

**Comment by MarjieAVolk** [comment]
You should be able to use the existing and/or to do more complex things, like 'species is animal and species is herbivore'

**Comment by Deantwo** [comment]
@D3nnis3n, am I horrible if I poke you about this?
This is one of the most annoying issues they makes otherwise simple laws very long and hard to make. Many of the questions I get on Discord is how to make a law that affect all animals or all trees, and telling them to do complicated logic is very dissatisfying.
``` SQL
((AnimalA OR (AnimalB OR AnimalC)) AND currenttime > blabla...)
```
A simple category option like:

- Any tree
- Any crop
- Any plant
- Any animal

... would help immensely.

**Comment by Deantwo** [comment]
Rather devastated that so many new trees, plants and animals were added, but we didn't get this issue solved. This means that making a law that covers all tree types is now a huge chore, same with animals and plants.

Bump for hoping we get a fix before v0.9.0.0, since waiting that long for it will be unbearable.

**Comment by Cyborgmatt** [comment]
Agreed, there are so many different trees in the game now the law you need to cover them is growing way too big.

**Comment by Deantwo** [comment]
Alternatively (and possibly better?) the `Harvest` law option coupd be split onto multiple different types. For example `Harvest Tree`, `Harvest Plant`, `Harvest Animal`, etc. This would also make more sense to the average player. I doubt anyone has ever used `Harvest` to affect multiple species categories at one, and couldn't simply add a second trigger.

**Comment by thereporter42** [comment]
That is absolute BS Deantwo your idea is horrible I mean we do need this!  Your idea is not enough 
and this needs to be done the way I described.

**Comment by D3nnis3n** [comment]
Please keep clam. To be honest his idea is pretty much the same as yours, just with a different UI.

In your post you wanted to have the option to use all animals or plants, which is possible with his solution.

**Comment by Deantwo** [comment]
A v0.9.0.0 milestone? *puppy eyes*

**Comment by SlayksWood** [comment]
- [ ] Need to delete all Trees from Plant group.
- [ ] Add more groups. May be separate Trees to Softwood and Hardwood, separate plants to vegetables or fruits...

**Comment by johnkslg** [comment]
Law system is totally rewritten, and new selector for species supports tags and easy multiselect so that should cover all cases here, let me know if otherwise. 
Here's what the new one looks like:
![image](https://user-images.githubusercontent.com/3536496/67707304-79b76f80-f977-11e9-8a87-f68b776eec28.png)
