### ISSUE TITLE
When proposing a law, shows an empty red bar

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4094]
This was for someone logged in through steam, think that might be related?

**Comment by MarjieAVolk** [comment]
Okay, the person I was debugging this with figured out what the errors he had were.  One was the default citizenship law, and the other was duplicate title.  So they were real errors coming from the server side, but the message just wasn't showing up in the bar.

This turned what would have been easy fixes on the player's part into hours long debug pow wows, so I think this is really important to fix.

**Comment by elitejp** [comment]
We can't vote or propose law, cuz we can't be citizen. The first law to become citizen was broken and block us to vote or propose law.

**Comment by MarjieAVolk** [comment]
Yes, the default law is broken right now unfortunately.  It will be fixed in the next release.  In the mean time, your admin can remove it for you - They will have a delete button on the web page for the law.

**Comment by TMSpuz** [comment]
I have 0.7.2.0 beta right now. I could get the laws to work before the update after deleting the initial Citizenship law, but now they don't seem to work at all no matter what I try.

I've just created a simple law to repeal another law that I set up incorrectly, and all I get is the red bar without a message. I've tried 3 different browsers at the moment.

**Comment by MarjieAVolk** [comment]
Often, you can get the error messages to show up again by closing the browser tab and reopening it through the in-game button a few times.  Doing this refreshes your login information, which seems to be related.  Are you being prevented because of a duplicate title?  (Failed or removed laws also count for title uniqueness)  Or maybe you didn't enter a description for the law?

**Comment by TMSpuz** [comment]
Well, after restarting the server it seemed to work fine when entered the same. Perhaps it was a failed title from earlier. Does a server restart clear these?

Also, not sure if related but I should note, I was added to the admin list when the server restarted.

**Comment by MarjieAVolk** [comment]
Hm, failed laws shouldn't be deleted on server start, but it's possible that they weren't saved when the server went down.

**Comment by darkshad9999** [comment]
So sick of this crap! your web interface is absolute GARBAGE! I can't even propose a law on a server 0.7.3.2 Beta 

All I get is an orange bar up across the top.  What the heck is going on this has been open since February 2018 and it still is not fixed.

When I go to propose a law all I get is an Orange bar that comes up across the top. 

You really need a way better law system and instead of using a web browser for it.
This is kinda a half ass implementation.  

Fix this!!! 

![eco - repeal law orange bar](https://user-images.githubusercontent.com/4023976/38472836-1c2f0330-3b43-11e8-88f7-83c9def544ae.jpg)

**Comment by rainfarmer** [comment]
empty red bar has been fixed
