### ISSUE TITLE
Deadly Lag Spikes

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4213]
The server will randomly freeze up, then after a long enough period of time kick the player with the message "Inactivity." While attempting to log back into the server, an extended delay is experienced before the loading world phase activates. The 7.0.6 patch improved performance but did not get rid of these periodic game halting lag spikes.

According to my server info, I'm only using a small portion of my 6gb ram and only up to 50% cpu. This is a tier 1 server from killservers with high performance.

**Comment by ecoemmeck** [comment]
can confirm this were having players kicked every minute or so for inactivity

**Comment by MarjieAVolk** [comment]
Is this new in the current hotfix, or has it been happening for a while?

**Comment by Blanclour** [comment]
Lag spikes confirmed to still be present in 7.0.7

**Comment by ecoemmeck** [comment]
It's only just started happening for us in 7.0.7 we didn't have it with any of the previous releases though we have also only just released the server to the public and because the server is now public we have around 15+ people online

**Comment by Blanclour** [comment]
I might have found a possible correlation regarding carts entering/exiting roads. It is not exclusive to lag spikes but the spikes often occur the instant this happens.

**Comment by Blanclour** [comment]
Spikes still present in 7.0.8

**Comment by ecoemmeck** [comment]
As soon as we get over say 9-10 players we've started noticing the lag spikes on 7.0.8

**Comment by ChrisMayhew** [comment]
We're running 0.7.0.7 and the lag is horrible, You can ping the server IP fine (28ms) but in game it reports 2000ms+
Server load is also not maxed out either.

**Comment by Blanclour** [comment]
Currently the most detrimental part of this bug is the long wait time on the "Entering World..." screen after being kicked for "Inactivity."

**Comment by DiploBlock** [comment]
to tag onto this comment because it actually got a priority tag. this is a copy/paste from my post about this issue:
UPDATE: Every time i use a table to make a project or to add materials to a current project i am being kicked for inactivity. This is the same for everyone on my server and it is a huge playability issue.

Adding items to tables while items are being processed is causing huge lag spikes/ game lockup. This is also happening when making store transactions and adding people permissions to deeds. It almost always causes kicks due to inactivity. Issues related to these lockups include other players having chunk loading problems and falling through the world.

**Comment by Blanclour** [comment]
I can confirm that the above happens on my server and just about every server I've been on as well.

**Comment by GophTheGreat** [comment]
+1, another user with a similar experience maybe:

i have a eco server built on a vps with 8 core and 8 gb ram.

When i play on it, very often i get kicked from my server with the message in the server panel that it happens because of inactivity. But i dont were inactivly.

And sometimes i cant do anything like choop a tree or something else, only can run around and then i get kicked from server with the same message in server panel.

It happens sometimes very often and sometimes only after ca. 20 minutes of playtime.

**Comment by ChrisMayhew** [comment]
Got to be honest this doesn't seem to happen on my server since the latest server releases. It was definitely a stats issue.

**Comment by metachronism** [comment]
should be fixed as of 7.2+,  more stats db fixes coming in 7.3
