### ISSUE TITLE
USER ISSUE: NO FLOOR OR CEILINGS

### ISSUE THREAD

**Issue by NitroBeast** [StrangeLoopGames/EcoIssues#4224]
**Version:** 0.7.0.7 beta

**Steps to Reproduce:**
put hew logs in carry slot
use hammer to place walls
make a 7x7 grid on floor or ceiling 

**Expected behavior:**
it should become a floor or ceiling like it use to

**Actual behavior:**
it just is a bunch of walls connecting
it was working fine before update today and now i cant get any further cause crafting tables require rooms

**Comment by DiploBlock** [comment]
hold shift and scroll through the options of what kind of shape you want to build? not sure if that helps

**Comment by MarjieAVolk** [comment]
We have now added the hammer constructs, which replace the old behavior of trying to auto detect which shape each block should be.  Simplifying the block behavior allows our artists to focus on adding more different types of blocks with many construct variations, rather than working on making the blocks automatically choose their shapes.

**Comment by MarjieAVolk** [comment]
You will need to take the Wood Construction specialty in order to unlock more of the constructs for Hewn Logs
