### ISSUE TITLE
USER ISSUE Crash of game in connecting to webpanel

### ISSUE THREAD

**Issue by Kastuk** [StrangeLoopGames/EcoIssues#4274]
Maybe another excess of RAM limit.
[Crash_2018-02-11_002420.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1713833/Crash_2018-02-11_002420.zip)

**Comment by MarjieAVolk** [comment]
Okay, you got a 'UnityPlayer.dll caused an Access Violation'.  This is some kind of internal problem in Unity.  I believe since you filed this bug, we have updated our Unity version, so it might be resolved now.  I haven't gotten a report of it in a little while at least.

If you are still having the problem, some people reported updating drivers or uninstalling Geforce Experience helped them.
