### ISSUE TITLE
(New Feature) Item Transfer

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#4280]
Is there any way we could transfer all items from a cart into a stockpile or chest and also transfer all items from a stockpile or chest into a cart.

The other idea would be to be able to hold control and transfer what we are clicking on into a cart or stockpile or chest.

Perhaps by only having the 2 things you want to transfer between linked or place you want to transfer from being the storage you have open and the place you want to transfer to being directly under it

**Comment by Bazzi89** [comment]
Yes, that would be a nice feature. ;)

**Comment by MarjieAVolk** [comment]
Yes, I would like to implement more convenience features like this.  I am still not quite sure how to do it, since as you noted you can have more than 2 inventories open at a time potentially, so the established solutions won't necessarily work for us.

**Comment by Dreepa** [comment]
Suggestion:
-Click on an entry in shared storage GUI to set it the active entry.
-SHIFT + Click transfers between player inventory and active containter
-When transfered to player inventory, hotbar is used first, if available
-When transfered to storage, left to right

Current "Split stack" function on shift click needs to be remapped for this to work.
Possible suggestions:
Opening split dialogue by:
-SHIFT + Drag icon a few pixels
-CTRL + Click

**Comment by MarjieAVolk** [comment]
> Regarding the streamlining of storage management/quick transfer by the player.
> 
> The standard use of pressing 'T' to transfer a stack, naturally doesn't work with the more complex options available from multiple storage options so I would like to suggest the following mechanics;
> 
> A) Double Click grab - One of the difficulties can be holding down Left Mouse Button, then at the same time needing to scroll your mouse wheel down to a lower storage. Most of us naturally use our Index finger to perform both these tasks.
> 
> Suggested behaviour:
> 
> Double clicking an item would perform the same function as holding LMB on an item. The hand would close to a grab and that item would be held by the hand.
> 
> Closing the inventory or clicking anywhere not considered a destination inventory slot will reset/ungrab the item.
> 
> A single click on a valid destination inventory slot will transfer the held/grabbed item.
> 
> This would remove the difficulty of the index finger being expected to perform several different functions at the same time.
> 
> B) 'Ctrl' Double Click grab - (Any modifier besides Left Ctrl could be used.) The same function as described in 'A', though the result of step 3 would be;
> 
> 3b) All items of the same type i.e. Coal, from the source inventory will be transferred to the destination inventory so long as valid storage slots are available.
> 
> In the event of too many slots in the source inventory compared to the destination inventory, the maximum amount of available slots will be filled i.e. 20 stack of coal from Storage A, Storage B has 14 available slots, results in 14 stacks of coal being transferred from Storage A to Storage B.
> C) Alphabetical storage filtering option - The connected storage system is fantastic, really, we love it. One thing often discussed in the workload involved to organise this storage when a new table/storage is created. By offering the user an 'Arrange alphabetically' button, the user could easily pre-define storage orders.
> 
> For example, players often have one Stockpile and one chest that they prefer as destination outputs. Players could rename that from 'Workshop Stockpile' to 'A - Workshop Stockpile', could rename 'Brazier' to 'Z - Brazier.'
> 
> The result would be that any storage that has 'Arrange Alphabetically' option selected, will automatically display the 'A - Workshop Stockpile' at the top of the list and the rarely needed 'Z - Brazier' at the bottom of the list.

-- @ParadoxedHope

**Comment by ParadoxedHope** [comment]
Popping this here as it is a storage related issue/bug.

The excavator storage cannot be reordered as it is locked to the excavator fuel storage, which is a good thing I feel, since it is locked together can we lock them together for the purpose of reordering too?

Current Behaviour;

Cannot drag and reorder Excavator storage, due to being tied to Excavator Fuel storage.

Desired behaviour;

Dragging excavator storage to reorder will automatically drag the excavator fuel storage with it.

-------

Since this is also excavator storage related;

Current behaviour;

Player held fuel, when Right clicked on the excavator, transfers the fuel into the excavator storage instead of the excavator fuel storage.

Desired behaviour; 

Player held fuel is deposited in the fuel storage, other player held resources in the normal storage

Suggestion;

I think if the excavator fuel storage was locked above, rather than below the excavator storage, then this would be the default storage for player attempted deposits? Then anything non fuel would naturally default to the next available storage that accepts it's type, which would be the main excavator storage?

**Comment by Dreepa** [comment]
As to index finger overload with holding the item and using the mouse wheel: You could copy windows explorer functionality. When you drag an item near the border of the window, it will start scrolling in that direction.

**Comment by MarjieAVolk** [comment]
Ah yeah, that's a reasonable idea.  It has proven remarkably difficult to re-implement windows explorer in Unity. 😆

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#278
