### ISSUE TITLE
CLIENT ISSUE: Despite 7.0.5 fix, I still have missing main menu screen

### ISSUE THREAD

**Issue by PinkWafflePig** [StrangeLoopGames/EcoIssues#4281]
I load the game, a forest background appears with birds chirping and then the game stops responding. I am on a Mac and I have tried it on steam as well and I made sure it is the latest by doing a fresh reinstall.

**Comment by MarjieAVolk** [comment]
Could you attach your error log?  It should be at ~/Library/Logs/Unity/Player.log

**Comment by ThomasFontaine** [comment]
Here is mine for the same issue 👍 
`Initialize engine version: 2017.3.0f3 (a9f86dcd79df)
GfxDevice: creating device client; threaded=1
Renderer: NVIDIA GeForce GTX 960 OpenGL Engine
Vendor:   NVIDIA Corporation
Version:  4.1 NVIDIA-10.18.5 378.05.05.25f04
GLES:     0
 GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_st
orage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
OPENGL LOG: Creating OpenGL 4.1 graphics device ; Context level  <OpenGL 4.1> ; Context handle 43311104
Begin MonoManager ReloadAssembly
- Completed reload, in  0.027 seconds
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.
The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'Hidden/SEGI' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGI' - Setting to default shader.
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDBACK' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - All passes removed
WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/SEGIRenderSunDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Post FX/Temporal Anti-aliasing' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Post FX/Depth Of Field' - Pass 'COC TEMPORAL FILTER' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Setting to default shader.
Setting up 2 worker threads for Enlighten.
  Thread -> id: 70000405f000 -> priority: 1 
  Thread -> id: 7000040e2000 -> priority: 1 
UnloadTime: 3.285980 ms
Setting breakpad minidump AppID = 382310
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198031584878 [API loaded no]
The given primitive topology does not match with the topology expected by the geometry shader
 
(Filename:  Line: 0)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

-------- GLSL link error: WARNING: Output of vertex shader 'vs_NORMAL0' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' differs in type/qualifiers to that written by vertex shader
WARNING: Output of vertex shader 'vs_TEXCOORD3' not read by geometry shader
ERROR: Input of geometry shader 'vs_SV_InstanceID0' not written by vertex shader
ERROR: Input of geometry shader 'vs_TEXCOORD0' not written by vertex shader



 
(Filename:  Line: 668)

Note: Creation of internal variant of shader 'Curved/Minimap' failed.
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
 
(Filename:  Line: 438)

RPC lookup took: 13203.643ms
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

`

**Comment by MarjieAVolk** [comment]
So looks like your OS is not liking shaders >>

**Comment by rainfarmer** [comment]
+1

I bought ECO game with 3 friends. They have Windows and their games run well but not mine.
I have Linux so I had to download the game for Linux. After the download I unzipped the game and launched the Eco.x86_64 file.
I opened the game and it started normally, I can hear twitters and I see the backscreen but I can't do anythings (screen is frozen). I have to hard restart the computer to go out of the game.
What can I do?

My configuration is as follow:
Memory : 3,6 Go
Processor : Intel core i3-7100 CPU @ 2.40 GHz x 4
Graphic card : Intel HD graphics 620 (kaby lake GT2)
OS : Ubuntu 16.04 LTS, 64 bits
SSD : 266,6 Go

**Comment by Epimetheus89** [comment]
+1

If I start the game for the first time, it takes about 5 minutes to load the menu. This happens on the following both configurations:
1.: Lenovo T460p with Ubuntu 17.10
CPU: Intel Core i7-6700HQ CPU @ 2.60GHz x 8
Memory: 32GB
Graphic card: Geforce 940MX/PCIe/SSE2

2.: MacBook Pro with i7, Radeon Pro 560 and 16GB memory

**Comment by rainfarmer** [comment]
+!

7.1.2 freezes at the same spot.  Birds chirping and a 1/4th of a second fade in into what looks like a forest.

Mac OSX 10.13.3 (17D47)

**Comment by rainfarmer** [comment]
+1
Me and 4 friends picked this up today, and we were able to play for maybe an hour before the game kicked us out to the menu screen except it had no menu options. Closing and reopening the game does not resolve the issue nor does an uninstall and reinstall. What gives?

**Comment by Katorone** [comment]
Issue persists on beta 7.2.5.

**Comment by metachronism** [comment]
Can anyone having this issue please try the latest staging build?

**Comment by Katorone** [comment]
I'm having this issue on linux, so sadly I can't test the staging builds.

**Comment by MarjieAVolk** [comment]
Elsewhere @Sebi-M suggested this may be related to path capitalization on linux (https://github.com/StrangeLoopGames/EcoIssues/issues/6158)

**Comment by vandermore** [comment]
I am having the same issue with macOS High Sierra (10.13.3). It looks like a similar shader issue.

I am on a Macbook Pro (Retina, 15 inch, Mid 2014)

Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
Vendor:   NVIDIA Corporation
Version:  4.1 NVIDIA-10.28.10 355.11.10.10.20.111
GLES:     0
 GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_st
orage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
OPENGL LOG: Creating OpenGL 4.1 graphics device ; Context level  <OpenGL 4.1> ; Context handle 67445760
Begin MonoManager ReloadAssembly
- Completed reload, in  0.058 seconds
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/BlitToDepth_MSAA' - Setting to default shader.
The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

The referenced script on this Behaviour (Game Object 'Contents') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDBACK' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - All passes removed
WARNING: Shader Unsupported: 'Hidden/SEGIRenderSunDepth' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Minimap' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Minimap' - Pass 'FORWARD_DELTA' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Minimap' - Pass 'SHADOWCASTER' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Minimap' - Pass 'DEFERRED' has no vertex shader
WARNING: Shader Unsupported: 'Curved/Minimap' - All passes removed
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Curved/Minimap' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/Post FX/Depth Of Field' - Pass 'COC TEMPORAL FILTER' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/Post FX/Temporal Anti-aliasing' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGITraceScene' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGIVoxelizeScene' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/SEGI' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/SEGI' - Setting to default shader.
Setting up 4 worker threads for Enlighten.
  Thread -> id: 700008375000 -> priority: 1 
  Thread -> id: 7000083f8000 -> priority: 1 
  Thread -> id: 70000847b000 -> priority: 1 
  Thread -> id: 7000084fe000 -> priority: 1 
UnloadTime: 4.496042 ms
Setting breakpad minidump AppID = 382310
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197962802454 [API loaded no]
RPC lookup took: 21645.087ms
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by SeanAtr0n** [comment]
Most of the issues here should be resolved... Please open a new issue if you still have problems
