### ISSUE TITLE
USER ISSUE: fertilizers lvl 1 500 points?!!!?

### ISSUE THREAD

**Issue by rsgodkilla** [StrangeLoopGames/EcoIssues#4302]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
to get level 1 i need 500 points thats a bit crazy is it a bug ?

**Expected behavior:**

**Actual behavior:**

**Comment by imthe666st** [comment]
The requirements needed to learn a skill increase exponentially with the number of different specialities you have learned. 
It seems like you have many different specialities, which is why the skill points requirement is this high. 

![image](https://user-images.githubusercontent.com/7377849/36073074-f42c1e52-0f2a-11e8-8a0d-1b6ad8c60ca6.png)

**Comment by rsgodkilla** [comment]
ugh so if i unlearn them will it go down ?

**Comment by imthe666st** [comment]
Yes.

**Comment by imthe666st** [comment]
But you will only receive 50% of your invested skill points if you unlearn a skill.

**Comment by MarjieAVolk** [comment]
As stated, specialty costs increase based on how many specialties you already have.  Working as intended
