### ISSUE TITLE
Plants die on first tick - 7.0.8

### ISSUE THREAD

**Issue by stormoffires** [StrangeLoopGames/EcoIssues#4315]
planted a tree, had no pollution, 56% match...

first game tick it died.

attaching game file

https://drive.google.com/open?id=1MuwXUwluYRFokuv0Y42gs-idicYNbMrm

**Comment by MarjieAVolk** [comment]
I believe death is probabilistic, so this isn't necessarily a bug, but rather might need tuning.

**Comment by knexer** [comment]
In addition to what @MarjieAVolk said, I would check for a bug that specifically affects trees due to them having a different layer resolution.  I've seen a number of reports of trees dying immediately, but it could also just be a more commonly encountered issue because their long maturation time means that more trees die before reaching maturity.

If that bug does not exist, it may make sense to reduce the birth and death velocities for trees substantially to match their longer maturation time.

**Comment by craig-jong** [comment]
Made changes (a while ago) to planting that make this not possible anymore.
