### ISSUE TITLE
USER ISSUE: No Plants

### ISSUE THREAD

**Issue by Marc-Jansen** [StrangeLoopGames/EcoIssues#4326]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
World spawned. No Corn. No Beets. No Bunnys.

**Expected behavior:**
It should have it.

**Actual behavior:**
Dont have it.

**Comment by craig-jong** [comment]
We're looking changing worldgen, but there isn't a whole lot we can do about this in the meantime. There have been tweaks since .0.8, so if you encounter this issue with such a large variety of species, please let us know.

The current stopgap is to use /regenlayer to see if the correct species will spawn.
