### ISSUE TITLE
USER ISSUE: Turtle on snow biome

### ISSUE THREAD

**Issue by Arkadia3** [StrangeLoopGames/EcoIssues#4341]
**Version:** 0.7.0.8 beta

**Steps to Reproduce:**
I met turtle on snowy biome :)

**Expected behavior:**
Turtle should spawn on other biome; (maybe) with water, sand or swamps

**Actual behavior:**
turtle spawns on snowy biome

**Comment by ecoemmeck** [comment]
While slightly odd turtles do survive is snow and icy conditions

**Comment by Amphysbaenas** [comment]
it's a real problem
![image](https://user-images.githubusercontent.com/29807119/36078574-c38db820-0f78-11e8-86c7-f4f940794fa1.png)

**Comment by Amphysbaenas** [comment]
![image](https://user-images.githubusercontent.com/29807119/36079489-ae4e947e-0f83-11e8-8b6d-146a8ceb57ca.png)

**Comment by Kastuk** [comment]
Looks like in EcoSim.eco
Tortoises "SpeciesChangeRate": 0.9,
Hares "SpeciesChangeRate": 0.05,
Elk "SpeciesChangeRate": 0.02,
Bison "SpeciesChangeRate": 0.01,
is wrong here.

**Comment by Kastuk** [comment]
Also
`       "$id": "331",
          "$type": "Eco.Simulation.Types.AnimalSpecies, Eco.Simulation",
          "AnimalType": {
            "Type": "Eco.Gameplay.Animals.AnimalEntity, Eco.Gameplay"
          },
          "FoodSources": {
            "$id": "332",
            "Eco.Simulation.Types.Species": {
              "$type": "System.Collections.Generic.List`1[[Eco.Simulation.Types.Species, Eco.Simulation]], mscorlib",
              "$values": []`

Looks like there no determined foodsources for Tortoises.

**Comment by darkshad9999** [comment]
Give your tortoise some snow shoes? :)

**Comment by darkshad9999** [comment]
Version: 0.7.3.1 Beta

Steps to Reproduce:

Just go to a snowy area on your map and look around you will find 

Expected behavior:
Turtle should spawn on other biome; (maybe) with water, sand or swamps

Actual behavior:
turtle spawns on snowy biome

Ya I just ran into that too... I was way up in the mountains and  here is this little Tortoise crawling along 
I don't think that it would do to well up there I don't know why a Tortoise would be up there.

A Tortoise would be suited to a warmer, sandy or swamp environment 

I can confirm that this is happening on version 0.7.3.1 Beta still. 

Currently on the server I am playing on we are topping out at about 700 for tortoises. 

![eco snow tortiose april 2 2018](https://user-images.githubusercontent.com/4023976/38186388-03e0ceae-3610-11e8-8fd3-99fe9bf8b2e8.jpg)

**Comment by craig-jong** [comment]
Food sources are slightly weird, but bison do eat. Animals with no food sources would not spawn at all.
