### ISSUE TITLE
Block orientation issue / stairs

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#438]
http://ecoforum.strangeloopgames.com/topic/675/stairs-not-placing-correctly

**Comment by craig-jong** [comment]
Perhaps we should remove stairs automatic orientation and have them placed based on the player's facing.

**Comment by Breitschwert** [comment]
Stairs should behave like ramps and be rotate-able via Q and E. Automatic orientation should indeed be removed. Initial facing could be "lower side towards player".

**Comment by duffyboyo** [comment]
👍 for using Q and E

**Comment by keegan-o** [comment]
Having hundreds of extra world objects in any given world so that each stair can be manually placed may be a problem with our current system in terms of performance.

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1364/stair-placement-could-be-improved

**Comment by keegan-o** [comment]
I'm un-assigning myself for now as this is a code issue-- the stair mesh exists and can be improved, this bug is actually about adding a new feature that allows you to see a ghost of 4 alternate blocks based on using q and e for rotation like the world objects-- or however the programmer thinks it is best to have it work. Ideally instead of 4 separate blocks/meshes it would find a way to rotate one mesh, but it's ok if it has to be 4 blocks.
