### ISSUE TITLE
USER ISSUE: Cart sinking to the ground

### ISSUE THREAD

**Issue by MC2424** [StrangeLoopGames/EcoIssues#4393]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
I build a house with Hewn Log floor
I left my small wooden cart on the floor

**Expected behavior:**
The cart should be on top of the floor		

**Actual behavior:**
The deed shows the cart to be in my house, but I cannot find it (could be underground but digging does not help, cannot find it).

**Comment by MarjieAVolk** [comment]
Is the cart on top of your house by any chance?  The position listed in the deed should also give a Y value - does it show it as being below you?

**Comment by MC2424** [comment]
I just checked, and you are right, the cart indeed is on top of the house. Still I have no idea how it got there…
Thx

**Comment by MarjieAVolk** [comment]
If something like a cart or animal gets stuck inside the terrain it will teleport to the top of the world as an effort to fix it.  It's a last ditch effort to keep carts from sinking into the ground :P

This is something we're aware of and will continue improving, but we can't easily fix it.  So since your immediate issue is resolved, closing this bug.
