### ISSUE TITLE
Plants giving incorrect resources when farmed

### ISSUE THREAD

**Issue by craig-jong** [StrangeLoopGames/EcoIssues#440]
http://ecoforum.strangeloopgames.com/topic/677/farming-weird-issue

Likely related to farming/harvesting.

**Comment by craig-jong** [comment]
related https://github.com/StrangeLoopGames/EcoIssues/issues/422

**Comment by craig-jong** [comment]
I know this is an issue because its happened to me before randomly, but I just planted like 12 cycles of crops and it never occurred. I'll look into it more later.

**Comment by jhadred** [comment]
To duplicate:  
-Set up a two plots of land for comparison.  two 4x11's would be useful.
-Plant the same crop in both for comparison.
-Harvest these when they grow.
-In one plot of land, plant a different crop. 
-In the other plot of land, do nothing.
-wait
-The planted land should sprout and the other land is likely blank.  Do not harvest yet since at this point it *should* be giving the correct image and harvest
-Wait more
-The plot of land we did not replant should now have regrown on it's own.  It seems most, but not all, of the squares will regrow.
-Harvest both to compare.  The first plot should be getting both results of what was planted, as well as what was previously planted.

If a third iteration is desired, plant the first plot with yet a different crop.  Do nothing again to the other plot. Repeat.

If a 4th iteration is desired, do nothing to both plots of land and see what comes up.  The first plot should now be a mix of the three crops and the image does not necessarily represent what is harvested.

The issue appears to be that the plants automatically regrow but (and this requires more testing) this regrowth is not affected by the agriculture growth speed.  
This is why an immediate harvest should be fine (for example, 50% growth time and harvesting after that but before the full original time), but if you wait the  original grow time before harvesting that crop, people are getting other things they've planted yet the image is of what was planted (since this "grew" first).
