### ISSUE TITLE
[Suggestion] Districts and laws rework

### ISSUE THREAD

**Issue by Huntermeign** [StrangeLoopGames/EcoIssues#4400]
Current mechanics: Districts cannot overlap. Districts and laws take a whole 24 hours to vote 

Proposed change: Districts should be able to overlap with option to either ignore or inherit parent districts laws. Laws should be added as an addendum to proposed districts to save time that could be crucial in saving the environment. 

Reasons: 
- More incentive to vote on laws that may affect area.
- Can be used to create road districts on Industrial/commercial/residential districts but can remove restrictions or can add laws to specific areas of attention without effecting entire communities because of unforeseen planning 
- Laws take too long to pass. Addendums can do both create districts and pass laws in half the time.

**Comment by CompactDisc** [comment]
I agree, attaching laws to districts on creation would be a great thing to have. Halving the time that things can still go wrong.

**Comment by SeanAtr0n** [comment]
Overlapping seems unlikely, bug i agree with your other points 👍 
Voting to shorten the voting window would be cool

**Comment by Huntermeign** [comment]
I only suggest the overlapping because if there was ever an instance where the entire town planning had to be removed it would require periods of time to remove districts and reinstate new one. Perhaps instead of overlapping we have subdistricts?

**Comment by MarjieAVolk** [comment]
You can already propose a law that both changes districts and has an action prevention clause (as you say, and addendum, if I understand the suggestion).

I would also like to revisit voting so that it is possible to reduce voting time.  The issue of course is that you don't want to allow a troll to propose a law while most people are away and then it passes before anyone sees.  Letting servers vote on what the voting time should be is one option.  Another thing that I have been hoping to do is let severs define what a 'citizen' is (Eg. like the default Citizenship law, but more customizable), and then laws can be automatically passed early if a majority of citizens have voted yes on it, etc.

**Comment by Huntermeign** [comment]
Sorry, have been away past couple days. Whats the status on the criminal justice system as shown to be featured on the site?

https://www.strangeloopgames.com/how-the-player-run-criminal-justice-system-works-pvp/

**Comment by MarjieAVolk** [comment]
We have not started working on it yet.

**Comment by Huntermeign** [comment]
But is still planned?

**Comment by MarjieAVolk** [comment]
Yes :)

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#272
