### ISSUE TITLE
USER ISSUE: Connection failed

### ISSUE THREAD

**Issue by Litschi123** [StrangeLoopGames/EcoIssues#4426]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Connect to a server

**Expected behavior:**
Join the server

**Actual behavior:**
Won't connect to server and shows the following error message:
> Connection Failed
> Login info could not be verified. Our auth servers may be down.
> Unexpected character encountered while parsing value: <. Path ", line 0, position 0

**Comment by knexer** [comment]
If the exception is a parseexception it'd be nice if we could include the response body in the error message

**Comment by MarjieAVolk** [comment]
Guess we could just always do that

**Comment by MarjieAVolk** [comment]
Upping the priority on this as I realized this is completely preventing multiple people from playing

**Comment by Weissenburger** [comment]
To answer the question asked by MarjieAVolk: **Do either of you have accounts with us? Or are you only using steam?**

I bought the game on Steam and did create an account on [https://ecoauth.strangeloopgames.com](url) and linked it to my Steam account, but I am launching it through Steam.

I did try launching it without steam and typed in my strangeloop account name and password and it said **Invalid username or password**.
Should I be able to login using the strangeloop account without steam? If so could there be a problem with the account linking?

The strange thing is this didn't start happening until patch 7.0.6 or 7.0.7 (don't know which, last patch I was able to run without issue was 7.0.5), and hasn't been resolved since.

When the game was launched on Steam on the 6th I also had some problems joining servers, it didn't give me any error message or anything, but that issue was resolved with one of the hot fixes.

I'm able to play single player with no issues, I just cant join any server.

**Comment by MarjieAVolk** [comment]
You should be able to log in with your slg account, yes.  If you can't, then it seems likely those issues are related.

What is your SLG username?  @rainfarmer can look up your account and see if there is anything wrong with it in our database.

**Comment by Weissenburger** [comment]
My SLG Username is Weissenburger and the Id is slg87639

**Comment by MarjieAVolk** [comment]
@rainfarmer says he has fixed your account.  There was a period of time where people's accounts could get into a bad state apparently.  Let me know if you can log in now!

**Comment by Weissenburger** [comment]
Yes it works now, thanks!

**Comment by MarjieAVolk** [comment]
@Litschi123 If you give us your slg username too, we can fix you as well.  We will try to fix everyone who has the issue, but will fix yours first ;)

**Comment by cr0ss0vr** [comment]
My buddy was getting this, but then we worked out that the server was v.7.1.0 and he was v.7.0.8

**Comment by Litschi123** [comment]
@MarjieAVolk Thanks, my slg username is: Glare

**Comment by MarjieAVolk** [comment]
We are on PST, and usually there are people here from about 10am to 7pm.  Although right now everyone is running late because we are worn out :P

**Comment by knexer** [comment]
@Litschi123 I fixed your account, you should be good now

**Comment by Litschi123** [comment]
@knexer it's working. Thanks a lot

**Comment by MarjieAVolk** [comment]
Okay, we ran a script to fix this for all players now, should be resolved
