### ISSUE TITLE
Servers cannot be run as non root users

### ISSUE THREAD

**Issue by Pingperfect** [StrangeLoopGames/EcoIssues#446]
The way we run our servers is that each service is run as a user that only has full access to where the server is installed, nothing else (for security) Running an Eco server this way causes an Access Denied error on startup and the webservice will fail to start and the server will fail to show in the serverlist.

So running a server as Administrator or system works fine, running the same server as a more limited user the server ultimatly fails to work.

https://www.dropbox.com/s/m1so6kl1dcb0shp/Screenshot%202016-07-06%2002.52.45.png?dl=0
An example commandline would be 

runas /user:TCAVirtualSvr156 cmd.exe
Password: ##############
cd /d C:\Pingperfect\Users\Admin\9662\
EcoServer.exe

**Comment by metachronism** [comment]
windows needs netsh access to allow listening on http traffic.  The server attempts to run the following command as an admin to grant it:

"netsh http add urlacl url={address} user={domain}\user"

if running as a service, the UAC box isnt allowed to pop up it seems, so that process will fail - but you can just run the command manually outside and it should work fine afterwards
