### ISSUE TITLE
Ecosim.eco causing World Devastation and extinction? 

### ISSUE THREAD

**Issue by bfc1974** [StrangeLoopGames/EcoIssues#4469]
please see attached file - grass is going brown which suggests not enough moisture in the soil- so whats the answer??

[EcoSim.txt](https://github.com/StrangeLoopGames/EcoIssues/files/1721671/EcoSim.txt)

**Comment by MarjieAVolk** [comment]
I take it you have edited your simulation config?

**Comment by bfc1974** [comment]
Yes I did. This was in response too the plants all dying on day 2. Tried checking graphs  again but no indicators as to what was going on. So far so good still some brown grass but looks like we could do with an optimal settings file ad the original settings seem to go awry quickly. let me know if i can provide any more info

Cheers
Iceman

**Comment by MarjieAVolk** [comment]
If you can reset your config file to the default, I believe plant dying issues have already been fixed.

**Comment by bfc1974** [comment]
reset of the server was necessary and it appears the clean config file rectified it.

**Comment by fezhub** [comment]
My server also had a mass plant death event at the end of day 2, see animation of OccupiedShrubSpace:
https://gyazo.com/d05c71a1d4bd5a71803b4f9012253443
Another server with the same map seed has the same issue.
So we're now stuck with >85% dead plants everywhere and the only way I can see to remove them is LayerInitOperation.MigrateVersion or AdminCommands.Repopulate but this looks dangerous.
Can you advise what approach we should take or if you would like any more information?
Thanks

**Comment by knexer** [comment]
@fezhub Does the server have a modified ecosim.eco?  Was the world generated on 7.0.x or migrated from a previous version? Did anything at all of note happen at the end of day 2 - in particular, did someone run /repopulate?

What's interesting about the animation you posted is that far too much space is occupied before the end of day 2 (see how it's white almost everywhere? pure white means OccupiedShrubSpace is above 1, which is always going to cause plants to die off until that's no longer true).  It's weird that it happened suddenly, though, it should have been gradual unless /repopulate command was used.

**Comment by fezhub** [comment]
Only ecosim changes were to SkillGainRate. World was generated about 5 days ago on 7.0.6 and updated as each update was released since then. Don't think anything too notable happened, there was a crash at some point but not sure if this was before/after the plantpocalypse began. The fact it starts at Day 3 00:00 exactly makes me think its from the simulation.

Most of the grass died off as well, ShrubSpace just illustrates the sudden change.
If it helps it seemed our planet was very moist, min moisture 36% and average much higher so was very difficult to find optimal crop locations. While checking other servers I found one that was very green overall still had dead zones close to water.
It makes sense that plants should die over time eventually but there seems to be no cleanup mechanism, so the players have to shovel everything to get a chance at regrowth? Is this correct?

**Comment by knexer** [comment]
Dead plants don't prevent regrowth.  By the time they're dead they're completely cosmetic and will get replaced by new plants freely.

There is no cleanup mechanism - I'm working on one right now though, should be in the next content patch.

**Comment by knexer** [comment]
Also, wow, that's extremely moist!  The planet shouldn't be quite so wet.  Would you be able to send me your save so I can take a deeper look?

**Comment by craig-jong** [comment]
closing this due to no response. If you're still around and want to zip up and send us a save, I can take a look.

As for dead plants, they now decay after a set amount of time,

**Comment by bfc1974** [comment]
Sent it ages ago but threads were merged I believe!!!
