### ISSUE TITLE
USER ISSUE: Unsble to cancle job (boards)

### ISSUE THREAD

**Issue by PorcusMalus** [StrangeLoopGames/EcoIssues#4475]
**Version:** 0.7.1.0 beta

**Steps to Reproduce:**
Place wood station outside. Attempt to do a project by selecting one, then place resources in. Try to cancle the job. Claims not enough resources. Can't move the bench.

**Expected behavior:**
Not let me start the project without meeting minimum station requirements like a room.

**Actual behavior:**
Lets me brick my workbench and make it permanent.

**Comment by MarjieAVolk** [comment]
So I presume what is going on is that you don't have enough inventory space to take all the logs back out?  This is kind of an icky situation.  What you will need to do in order to pick it back up is to get or make a stockpile or cart - You can do this at your workbench, and you can prioritize the project by dragging it to the front of the project list; or maybe you can borrow a cart from a friend.  Once you've crafted that, you can place it down, make sure it is linked to your workbench, and then cancel your original project again.  The logs should go into the stockpile or cart, and you can then pick up your things again.

It is a bit problematic that you can't partially cancel projects to get just some of the resources back, etc; but we don't have a good solution for this at the present moment, so we probably will not be working on a fix right away.  (See https://github.com/StrangeLoopGames/EcoIssues/issues/3577)
