### ISSUE TITLE
Aqueducts don't transport water far enough?

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#4478]
Had some people complain about aqueducts - let's make sure they work right, because they are very important for farming now.

**Comment by Sirisma** [comment]
I was under the impression that they are disabled entirely. Is this not the case or are they disabled due to performance drops?
https://eco.gamepedia.com/Aqueduct

**Comment by MarjieAVolk** [comment]
From @Conchipedia : 
![image](https://user-images.githubusercontent.com/23460210/36697999-895004d4-1afd-11e8-9eaf-a5a78b052fb2.png)

**Comment by UnknownViper** [comment]
It can apparently be enabled if you add Watertight to the aqueduct definition of brick.eco and using it as a mod that way (thanks to Grav on Discord for that one).
It seems to function, albeit water will apparently not disappear if you modify/remove the aqueduct.

It would be really, really nice to know what the deal is with all of this. Is it bugs that'll be fixed at some point, or is the entire aqueduct thing getting scrapped because of issues (that would be sad), and instead it'll be done by pipes etc. in an invisible manner, so to speak.

I can understand that it can create performance issues, especially if a lot of aqueducts are built, but I do hope we will get to flow our own water at some point using aqueducts. :)

**Comment by LiaungYip** [comment]
Fixed in https://github.com/StrangeLoopGames/Eco/pull/2542 (?)

```
Public Release Notes:
Fixed aqueducts not transporting water correctly
Fertilizer will now stack
Torches will now stack
...
```
