### ISSUE TITLE
USER ISSUE: Voting has ceased to work on my server

### ISSUE THREAD

**Issue by magww** [StrangeLoopGames/EcoIssues#4493]
**Version:** 0.7.1.1 beta

**Steps to Reproduce:**
A law was passed to prevent players from voting until2 houo of play time
Since then no one has been able to vote.

**Expected behavior:**
People should be able to vote

**Actual behavior:**
They cant

**Comment by MarjieAVolk** [comment]
Because of stats being disabled, the default law that you described is broken.  We are working on getting stats reenabled asap.  Might be today or tomorrow.  In the mean time, you can have your admin remove the law with /clearlaws or from the world's website in order to use the rest of the law system.
