### ISSUE TITLE
[CLIENT ISSUE] Can't pull Small Wooden Carts up Dirt Ramps

### ISSUE THREAD

**Issue by OfficialNoms** [StrangeLoopGames/EcoIssues#4535]
Issue persists in the game client.

When pulling a small wooden cart up a dirt ramp, upon reaching the top in most cases, you'll come to a stop and be unable to go over the top. 

This issue is reproducable 95% of the time. You can sometimes get it over with enough jiggling and getting a bit of a head start. 

Reproduce:
Build a dirt ramp up to a new level of dirt, get a Small Wooden Cart, pull it up the ramp and get stuck.

**Comment by MarjieAVolk** [comment]
So this doesn't work well with ramps + regular dirt, because there is a crevice between the ramp and the dirt.  What you are supposed to do is make the dirt into a road using a Road Tool.  This will cause the ramp to connect to it, and make pulling it up easy.  We've been thinking about how to improve this experience, so if you have any suggestions, let me know.
