### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by edvardm96** [StrangeLoopGames/EcoIssues#4547]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
I can not join my friends game

**Expected behavior:**
I should have been able to join them

**Actual behavior:**
The following error message popped up:
``` Invalid login info
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Steam is currently having an outage that is preventing many people from playing.  You can try to download the game from our webpage and play that, which should work.

If that does not work, you can also try deleting the folder C:\Users\[username]\AppData\LocalLow\Strange Loop Games\ECO

Closing as this is likely due to the steam outage, but if these solutions do not work for you, you can reply here and I will still see it.
