### ISSUE TITLE
USER ISSUE: Cannot connect to servers after recent update

### ISSUE THREAD

**Issue by TammasDexter** [StrangeLoopGames/EcoIssues#4551]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Attempt to join server

**Expected behavior:**
Connection to server

**Actual behavior:**
Failed login information error message

**Comment by MarjieAVolk** [comment]
There are a couple of things that could be causing this. You can try:

* If you are also seeing a message 'invalid login info', send me your Strange Loop username so that we can fix your account in our database.
* Deleting the folder C:\Users[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disabling your firewall and/or antivirus software
* If running your own game, when starting a new world, select 'Generate new'
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* If those don't work, send me any log files in '[...]\steamapps\common\Eco Server'
