### ISSUE TITLE
Account permissions issues steam vs slg/ Admin access not available for steam only?

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#4604]
If I make a char for a server through my slg client and the server has my slg ID on it as an admin I am able to use admin commands on the server.  

If I make a char through the steam client and connect to a server with my slg ID set as admin it tells me i do not have access.

If I make a char through steam  and an on server with my SteamID in the admin settings i have admin access.

If I make a char on my slg client and log onto a server with my steam ID in the admin settings I do not have access.

If I log into a char through my steam that I made in the slg account and has the slg ID set to admin or if I mad e achar in the slg client and log into through steam  (in both cases with the sgl ID set in admin) I sometimes have admin access and sometime sI do not meaning I have to log out and go access the char through the application it was originally created in.

Basically I was told this and I believe it is still supposed to be the case:
if player only has an SLG only account -> use SLG ID
if player only has an Steam only account -> use STEAMID64
if player only has an SLG + Steam linked account -> use SLG ID

So, the slgId should work for me on both apps, but this does not seem to be the case.  Getting complaints from several people about the same issue, they can get access but only as long as they log in with a char made in the same app as the id they are using.  I can work around this using both slgID and steam64ID but i was told that was not a good idea.

Also many people on steam are reporting that they set themselves as admins but they are not give admin access in game, they had shown screenshots of the Usere,eco file and they edited correctly

**Comment by MarjieAVolk** [comment]
It sounds like your steam and slg accounts are not linked.  It's possible that if you linked them earlier, they got unlinked again, because we had some problems in our database with linking.

When you log in to the game, you can use /whoami to see what ids are associated with your character.  I'm guessing you will see that you have steam only when logging in via steam, and slg only when logged in via slg.

Our auth code has changed a bit since launch, so now if you have a linked account, you should be able to use either slg id or steam id anywhere and have it work.
