### ISSUE TITLE
7.1.2 Severe Lag and Crashes

### ISSUE THREAD

**Issue by Blanclour** [StrangeLoopGames/EcoIssues#4611]
With 12 people online, my server is now experiencing major lag and periodic crashes. Have not identified what may be causing it yet.

**Comment by Blanclour** [comment]
The lag seems to happen after I pass the 10 player online threshold.

**Comment by wolfie359** [comment]
What hardware/os are you running for a server?

**Comment by Blanclour** [comment]
I am running a killservers.com tier 1 server. 6 gb of ram and good cpu. I don't know the os. The crashes happen after more people log onto the server. Then when it reboots everything is fine until too may people log on then it crashes and cycle continues.

**Comment by wolfie359** [comment]
Okay, I was more curious. I've been running 3-4 player on an older AMD Quad core 3.2, 8gb ram on Win 10 and haven't had any issues with lag yet. We haven't gotten into the upper tier items yet either so we'll see.

**Comment by pamduncan** [comment]
There are many reports of crashes associated with 12 + users - most hearing about them form people with dedi servers they are running at home.  The OS at killserver is =, of course windows as that is what the server is supported under.  I don't know from the discord name if he is running on our AMD boxes or the Intel - I would need the username to correlate that,  We monitor all servers across the board and we only know of one server that has had a demand for more then 6GB RAM in the hosting environment and that was due to a world corruption and only happened when loading the game.   There is a noticeable jump in CPU requirement when more then 10 players are on a server.  Also there would be crash logs in this users Dump file and having them would help- but I can retrieve them without knowing user name but he can post them here.  That might help.

**Comment by stormoffires** [comment]
sadly nothing new here, with our server on average 20+ players we use over 300% CPU with a 4core, 8gb ram.. >_>

**Comment by pamduncan** [comment]
I believe this is the Crash log being generated when he crashes at these times:  --BEGIN DUMP--
Dump Time
02/15/2018 21:28:19

Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Core.Controller.ControllerInstanceInfo.<>c.<CleanupBoundClients>b__16_0(INetClient boundClient)
   at System.Collections.Immutable.ImmutableList`1.Node.RemoveAll(Predicate`1 match)
   at System.Collections.Immutable.ImmutableList`1.RemoveAll(Predicate`1 match)
   at Eco.Core.Utils.ImmutableHelper.ApplyImmutable[T](T& original, Func`2 apply)
   at Eco.Core.Controller.ControllerManager.RemoveUnreferencedControllers()
   at Eco.Core.Controller.ControllerManager.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

--END DUMP--

**Comment by Blanclour** [comment]
I think 12 is a magic number in causing crashes for some reason.

**Comment by th3t0mb0mb** [comment]
Can confirm this problem.

**Comment by Blanclour** [comment]
My players are being stuck with a lot of rollbacks due to the very frequent crashes. They have been rebuilding the same stuff over and over again.

**Comment by MarjieAVolk** [comment]
If that stack trace is what your server crashes with, this is the issue open for that: https://github.com/StrangeLoopGames/EcoIssues/issues/4368

**Comment by Blanclour** [comment]
Yes I think it is the same bug.

**Comment by MarjieAVolk** [comment]
Okay thanks, then closing as duplicate
