### ISSUE TITLE
USER ISSUE: ADD RESSOURCES TO PROJECTS

### ISSUE THREAD

**Issue by Chax59** [StrangeLoopGames/EcoIssues#4631]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
i play with a friend on server, sometimes i can put stone on massonnery table (1 shared table for 2 players) on a project (launched by my friend) and sometimes i can't add this stones.

**Expected behavior:**
Normally 1 table should be shared completly by 2 players, even if a project is launched by a player, the other player could add his ressources  on a friend project.

**Actual behavior:**
i play with a friend on server, sometimes i can put stone on massonnery table (1 shared table for 2 players) on a project (launched by my friend) and sometimes i can't add this stones. stones.

**Comment by bfc1974** [comment]
I would add that if a table is shared items can be removed when they are completed - it seems currently the game works o the basis that it won't allow you to collect any of your project you have made if the previous project created by another player hasn't collected it.

**Comment by MarjieAVolk** [comment]
@bfc1974  Really?  If someone else has a project on a table, that prevents you from collecting yours?

@Chax59 The way it is supposed to work is if you add materials to a crafting station by right clicking directly on the crafting station, it will only add those to your own projects.  This is because some people use public tables, and there might be strangers' projects on there, which they don't want to add to by accident.  Other methods of adding materials to the project should work - eg. if you open up the stations' window and drag the materials directly onto the project; or if you put the materials into a connected inventory.

**Comment by Chax59** [comment]
I knew that, but it dont work even if i try to right click directly on the table, or even if i put my ressources when im on the window.
This bug sometimes works, sometimes not.

**Comment by bfc1974** [comment]
I would second what chax said

**Comment by MarjieAVolk** [comment]
So, you can't add resources to the project by right clicking on the table, by dragging it in to the window, OR by adding the materials to a linked inventory?

**Comment by Chax59** [comment]
i never try the last option, how can you link an inventory?  by placing a chest next to crafting station i suppose ?

**Comment by MarjieAVolk** [comment]
Yeah, placing it near the crafting station is step one; then on the crafting station go to the Storage tab and make sure the storage object is linked by checking the checkbox next to it.

**Comment by WeaselDog** [comment]
Merged with https://github.com/StrangeLoopGames/EcoIssues/issues/2638
