### ISSUE TITLE
USER ISSUE: Add a special character to the world name

### ISSUE THREAD

**Issue by mjackson34** [StrangeLoopGames/EcoIssues#4670]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. In the world name type: World?

**Expected behavior:**
Either it allows the special character or gives you a message about special characters are not allowed in the name

**Actual behavior:**
Could not create save file: Win32 IO returned ERROR_INVALID_NAME. Path: D:/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\DefaultWorld" or "D:/Steam/steamapps/common/Eco/Eco_Data/Server/Storage\World?.eco

**Comment by MarjieAVolk** [comment]
Yeah it would be nice if these error messages were more clean.  In this case, the error message is coming from a library, and the set of characters that are allowed is defined by your operating system, so it's kind of weird and scary to try to go in and muck with that.  But I can look into better messages here, since they are scaring a lot of people.

**Comment by MarjieAVolk** [comment]
This is implemented now :)
