### ISSUE TITLE
Farming Fixes

### ISSUE THREAD

**Issue by katabare** [StrangeLoopGames/EcoIssues#4694]
Problems

1 Conditions for land are random and make little sense with no obvious system on optimal conditions. Temperature and moisture values make some sense but are mostly random. Comparing land that is right next to each other yields differences of 5-8 degrees and 5-8 in moisture (that is excessive).
2 Trees take way too long to regrow.
3 Tree seed drop chance is too low.
4 No graphic to distinguish dead tree saplings from living tree saplings.
5 There is very little to no explanation on how to farm or change conditions to be optimal in-game or on the wikipedia page.
6 Crops are too easily overcrowded even when there are not many plants around them.
7 Plants are too sensitive to conditions causing them not to grow.

Suggested Fixes

1 Have a system where the conditions for temperature and moisture make sense. The closer to water, the higher the moisture. The further from water, the lower the moisture. Land that is on the same altitude and in very similar conditions should not differ much in temperature from each other if at all.
Rationale: I like the complexity if farming, but it should be more systematic in order to avoid having to plant tomatoes 10 spaces apart randomly. Plots of farmland are thus harder to make look nice.

2 Tree saplings should be made equally as available or even more available than other seeds. Trees also should not take days real time to grow.
Rationale: At most, have trees take 1 day to grow and at least 4 hours to grow. Wood is a very vital source in this game and having it be so rare to regrow runs into problems of tree extinction very early in the game thus causing a lot of frustration especially to those that have spent days only to reset due to unideal tree growing mechanics.

3 Have a graphic to distinguish all dead plants (ie trees) from each other.
Rationale: This cuts down an immense amount of time to distinguish the living plants from the dead ones (this includes trees of course).

4 Implement items that would help change the conditions of the land in order to be able to grow plants in optimal conditions. The introduction of certain buildings might also help. An irrigation system could help with moisture. A greenhouse could help with both moisture and temperatures. Heat lamps. Cold lamps. etc
Rationale: As of yet, I have not seen any way to change the conditions of the land in order to facilitate optimal growing conditions. Being able to change the land in order to fit your farms needs is a crucial part of farming. If you cant grow it there, you should be able to change it right? This goes hand in hand with suggestion number 1.

5 Lower the standard for overcrowding crops and lower the sensitivity of plants for optimal conditions.
Rationale: This simply makes growing plants unideal especially when mixed with all the other problems in this post. Plants unable to be close to each other creates sparse farmlands rather than small organized farmlands. The sensitivity of plants to conditions is too dramatic. Example: a 0.17 C above optimal temperature and a 2% below optimal moisture lowers the optimal conditions for that plant by 33%. It would be understandable if it was a 10-15% decrease for this example.

6 Include more information in the game on how to farm in your wiki and in-game. You can include a book in-game that can be made from the paper and some crops called "Guide to farming".
Rationale: There could be more direction in the game on the mechanics for growing crops. If a certain plant requires a certain amount of space away from other plants, it should be notated somewhere. Without direction, the player is left with a lot of guesswork which is great if you are going for a "figure it out yourself" type game, but I think luxuries like this would attract more people to the game and enhance game-play immensely.

**Comment by DiploBlock** [comment]
I really like the idea in section 4. You do have very valid points when it comes to farming. I think the greenhouse would be an awesome addition to the game. Hopefully it would help with the wildly varying growing conditions needed for farming.

**Comment by Huntermeign** [comment]
I kind of like how trees take irl days to grow. shows the effect of deforestation. what I don't like is how easy it is for trees to die now. Also, seeds are very common to get from trees for anyone who invests into forest forager. I get anywhere between 6-18 seeds a tree

**Comment by MarjieAVolk** [comment]
Thanks for your detailed feedback.  Farming and plant simulation changed a lot recently, and we're aware that it's unbalanced and still needs more work.  We're working on improving it and making it more clear.

1. Worlds have randomized water and temperature levels in different places in order to create biomes.  Water and temperature levels are also affected by terrain features like proximity to water and altitude.  Ideally, biomes would help to indicate what the conditions are like, although admittedly that is a very coarse indicator currently.  To address your concerns listed here, we are going to tune down the space requirements for plants so that it will be feasible to have them in a dense plot as before.  But I do wonder if we can't also visually indicate temperature and moisture in a more precise way.

2 & 3. I agree completely.  We need to fix those things.

4. Aqueducts are supposed to be the way to irrigate your farm.  We had some aqueduct bugs on steam launch, but I believe many of those have been fixed.  Although they are also not very discoverable, which is a big problem too - They are a form of Bricks currently.  As for your ideas about heat lamps or other temperature controlling devices, we don't really have anything like that currently.  That sounds like a good idea.

5. We are currently working on tuning these requirements, as you say :)

6. The Soil Sampler is one thing that is supposed to help you understand what your plants need.  We are still working on making its output more clear also.  Part of the issue currently is that we have designed this 'Cause and Effect' page that is visible on the server website, but we didn't really get it completed for launch; so this was supposed to be one of the main places where you can discover how farming works.  But perhaps we should invest in the wiki for now, as we continue working on those features.

**Comment by MarjieAVolk** [comment]
I have filed the following new bugs based on your suggestions:
https://github.com/StrangeLoopGames/EcoIssues/issues/4889
https://github.com/StrangeLoopGames/EcoIssues/issues/4886
https://github.com/StrangeLoopGames/EcoIssues/issues/4888
https://github.com/StrangeLoopGames/EcoIssues/issues/4887
https://github.com/StrangeLoopGames/EcoIssues/issues/4890

Going to close this bug since it has too many things in it to be treated as one bug :)
