### ISSUE TITLE
USER ISSUE: Suggestion for Districts

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4730]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
instead of Districts to be drawn and defined - allow cummintys to grow and then vote on becoming a District the land claims of players holding then = the drawing zone of the District in whole. as players incress inside the District matches that, players in that District when voting or running for offices only effect that District or community.   a town hall could be setup for a district that could be used to claim land for future growth out in public areas, latter on allow town to sell land with prebuilt buildings and areas in the townhall.

land markers made at townhall would not belong to anyone but the town hall aka the people who make up that District.  so ownership of public space = District name and people who have land in that district would have access to that space. and town hall have be able to give or sell land as a store.
then world leader as office could be removed also.

also could work with blueprint system with deeds latter being the blue print for sale.

- we lock world leader title out so people cant run for it anyways. only admins can due to power it allows one person over whole world.

**Expected behavior:**

**Actual behavior:**

**Comment by Sirisma** [comment]
Removing the ability for Districts to be drawn would remove the point of districts almost entirely. You wouldn't be able to disallow people from hunting on unclaimed land and wouldn't be able to mark large swaths of land as a wildlife reserve or similar. Allowing people to form their own districts may prove helpful in the absence of authority but it would be pointless once you have one as the point of a world leader is to make decisions and fulfill the desires of his constituents. Not forming districts for the people would be asinine. Allowing districts to be expanded as people claim land could prove faulty as somebody could claim land in an adjacent district or have land they do not want to be a part of the district. Allowing players to make government-level decisions is just too large of a petri dish for potential trolls or simply inept people.

**Comment by midn8t** [comment]
well district would form around group who control that land area not by the people who do not live in that area.

**Comment by spookychief** [comment]
> Removing the ability for Districts to be drawn would remove the point of districts almost entirely. You wouldn't be able to disallow people from hunting on unclaimed land and wouldn't be able to mark large swaths of land as a wildlife reserve or similar. Allowing people to form their own districts may prove helpful in the absence of authority but it would be pointless once you have one as the point of a world leader is to make decisions and fulfill the desires of his constituents. Not forming districts for the people would be asinine. Allowing districts to be expanded as people claim land could prove faulty as somebody could claim land in an adjacent district or have land they do not want to be a part of the district. Allowing players to make government-level decisions is just too large of a petri dish for potential trolls or simply inept people.

Ya I don't agree with any of the points you made. You seem to imply that most players are too stupid or are just trolls, which is far from the case. Districts could be controlled very easily by only allowing them to expand that districts borders. So you would would not be able to go into another district and claim land..that would be ridiculous. As it stands now you can't go onto another persons property and lay a marker why would you be able to do that in a district? Allowing a district to grow naturally through boarder expansion makes sense. You could start a town and have a town center that starts with say for example 30 markers or whatever and you would only be permitted to attach more markers to the already established border of that district. The initial district outline would radiate out from the center and added on to by the local government through voting on which squares to encompass into their district. I think you could get a lot of interesting dynamics out of this idea in where people choose to live and how the borders of that district start to get drawn by the people who control it. 

The current government system leaves much to be desired. Allowing districts to police themselves through laws that only apply to that district makes a whole lot more sense than allowing the entire world to vote on what happens in the district you live in and they don't.

**Comment by Sirisma** [comment]
Neither of you seem to understand what I'm talking about which is sad.
The op's English is so damn bad it actually confuses me trying to understand it.
They literally started their post off with "Instead of" then tried to claim "no one implied they would not formed" which, if I translate correctly, means he doesn't understand the meaning of "instead of"

> "Ya I don't agree with any of the points you made."

So you don't agree that making wildlife reservations or banning land claims in them is a good idea? 
You don't think it's an obligation of the world leader to make informed, intelligent decisions for the people while they slave away trying to stop the meteor? You think that the leader refusing to do part of his job isn't wrong? You think that the only people that play this game are wholesome, intelligent ecology majors?

> "I don't agree with any of the points you made"

You either ALSO have no grasp of the English language or you put so little thought into that sentence that I refuse to believe you actually read and garnered comprehension from what I said. At all.

> You seem to imply that most players are too stupid or are just trolls, which is far from the case.

You would not give the average person the power to: Change a residential zone in a town into a casino and industrial park in real life. People in general are not educated or patient enough to weigh the pros and cons and consider the backlash of that sort of decision. Likewise, I wouldn't trust my neighbor to not claim the open pasture behind my house so that he can build something obstructive.
I never said that all people are trolls or stupid, I never even implied it. I said that "Allowing players to make government-level decisions is just too large of a petri dish for potential trolls or simply inept people."
The average person is not a leader. Most people are selfish, ignorant, or lack the resolve to make difficult decisions.

> As it stands now you can't go onto another persons property and lay a marker why would you be able to do that in a district?

That was poorly worded on my part so I fixed it. What I mean is that if you have a town district that is set up for residential only but have a nearby, adjacent industrial park or the person wants to set up a mine that isn't restricted by the residential regulations but they don't know how to split claims what are they going to do? More than likely: get frustrated, bitch on the forums about the feature, or give up claiming land outside their domicile. While I understand how you misconstrued what I wrote, my point stands.

> Allowing a district to grow naturally through boarder expansion makes sense.

I never said it didn't.

> The current government system leaves much to be desired. Allowing districts to police themselves through laws that only apply to that district makes a whole lot more sense than allowing the entire world to vote on what happens in the district you live in and they don't.

That we agree on. I would still stress that not everybody is an ecology major and not everybody is selfless and there will always be people that are more focused on "Me, me, me" even if it means they get shunned or banned as a result.

**Comment by midn8t** [comment]
no one is talking about if your able to do or not to do any of those things.

what people are saying that thee is no such thing as a one world government period.

this is suppose to be a realistic real world eco / geo politic game  - not a fantasy land

there for you can not have a one world government and be true to that from.

**Comment by Sirisma** [comment]
English is not your first language, is it? Not trying to be rude but seriously your comprehension is lackluster. Why are you spending time reiterating a point you made that I agreed with?

> no one is talking about if your able to do or not to do any of those things.

You LITERALLY said so in the FIRST LINE OF THE OP.

> in real life people in USA do not vote on the laws in Canada

Why do you keep making comments on this thread directed at me reiterating points I've agreed with?

> there should be many governments in the world not one

The game is deliberately designed to have a "World Leader" 

> not place to bash ideas but to be enlighten by them and expand ones own thoughts

I'm not bashing ideas I'm critiquing them. I AM bashing the lack of English comprehension in this thread because quite frankly, it's terrible and depressing.

**Comment by spookychief** [comment]
First, I would like to welcome you to the internet. Please refrain from personal attacks. Just because a person grammar isn't perfect doesn't mean you need to start attacking them...that's netiquette 101. If you needed clarification on a statement then highlight it and ask them to clarify what the intention of that statement was. 

I read your post, fully understood what you wrote and didn't care for your points because I thought they were very weak or had very little reasoning behind them. You made claims and provided "Trolls" and "Inept" people as your reason for your stance.

> So you don't agree that making wildlife reservations or banning land claims in them is a good idea?

No, but you never really made that an explicit idea in your statement. Here's what you said without taking it out of context....like you did.

> "Removing the ability for Districts to be drawn would remove the point of districts almost entirely. You wouldn't be able to disallow people from hunting on unclaimed land and wouldn't be able to mark large swaths of land as a wildlife reserve or similar. "

That is what I disagreed with. You could still designate land as reserves.

> You don't think it's an obligation of the world leader to make informed, intelligent decisions for the people while they slave away trying to stop the meteor? You think that the leader refusing to do part of his job isn't wrong? You think that the only people that play this game are wholesome, intelligent ecology majors?

No, I don't think it's the obligation of the leader to do so. It's the obligation of the people in the world to be good stewards of the land and resources. I'm less willing to hand over world control to one person than over to a group.  A single world leader can easily enact a law to prevent anyone else from running for office. Do you think that is a great idea?

**Comment by midn8t** [comment]
well first off this statement is false "The game is deliberately designed to have a "World Leader""  its being made to be a realistic simulation of the environment and how politics interact with it.  the world leader destroys that learn curve completely.

**Comment by MarjieAVolk** [comment]
Okay, let's keep it civil in here.  What someone's first language is does not make their ideas better or worse.

@midn8t what you are suggesting sounds more like a multiple governments idea, or multiple countries, rather than a district replacement specifically.  I think I agree that I would not want to replace districts with this.  But I could picture this maybe working as a meta-district type thing, where different governments/countries hold different territory somehow, and within their own country they can also use the districts and laws features we already have, but they only apply while inside that country.  Maybe countries would have their own like country claim flags, and would get more based on how many people they have or something?

**Comment by midn8t** [comment]
could do both regional nationals and districts inside those places. 

biggest issue is like spooky put out, in our games is that current system is romp with miss use and authoritarianism which is why some players love it so much and others do not, it even comes to fights like this in game at times.

some players want to take control and do things over there area of the world and other people want to force there view on those players. which fractures it and if world laws get enacted by people out side of that region those people in that region get mad and just rage quit as admin i usually have to come in and just clean the slate with the laws or lock out the world leader.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#255
