### ISSUE TITLE
USER ISSUE: WebClient kinda broken

### ISSUE THREAD

**Issue by GoldenCrox** [StrangeLoopGames/EcoIssues#4758]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
The Graphs in the WebClient wont work. 4 Player tested it with different Browsers. Tested on IE11, Edge, Firefox and Chrome.

It loads, i see the menu and the rotating world + some Infos and my name on top, but the graphs show no lines and the menu wont work properly.

**Expected behavior:**
- Graphs must show vaules
- Menu "Run for Office" must work
- 

**Actual behavior:**
- No Lines in the Graph
- "Run for Office" shows a red bar unter the header

**Comment by Sirisma** [comment]
I can only assume that's the reason I log in and see nothing but (0) listed for every species.

**Comment by yanphi** [comment]
Yea, if your administrator then you should be able to see the statistics on the server UI/Console. Otherwise ask one to post a screenshot.

**Comment by Sirisma** [comment]
It's my server so maybe I'm just dumb and didn't actually make myself an admin. I've never tried to use commands, so...

**Comment by yanphi** [comment]
its not a command but part of the server UI. There should be a tab in the console that displays what is still in the game. Its one to the left of "Stats"

**Comment by MarjieAVolk** [comment]
Thank you - Yes, this is because stats are disabled right now.  This causes several features to do nothing, including the couple you noted, as well as some law features.  This was done because stats were causing big performance problems on larger servers.  I don't believe there is a way for you to turn them back on for yourself in the current version.  However, in the next release we have done some performance improvements to stats and also added options to disable/enable stats yourself (they will be enabled by default).
