### ISSUE TITLE
USER ISSUE: Wooden Shovel Durability Bug

### ISSUE THREAD

**Issue by vallard192** [StrangeLoopGames/EcoIssues#4788]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Get wooden shovel to "1 use remaining"
2. Use shovel
3. Lose "broken tool" calories even though tool had 1 use remaining

**Expected behavior:**
Cost me normal calories.  Check calorie cost of action before decrementing tool durability

**Actual behavior:**
Cost broken tool calories.  Updating tool durability and then calculating calorie cost

**Comment by MarjieAVolk** [comment]
@craig-jong This might be my fault, since I changed the tooltip from 'approximately 1 use remaining' to just '1 use remaining'; I'm assuming there is some off by one stuff going on, which is maybe why you put approximately to begin with.  Buuuut imo this is something we should be able to know and display so idk.

**Comment by SlayksWood** [comment]
merged with #12756
