### ISSUE TITLE
Unexplained animal die-off events

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#479]
The hare, elk and wolf populations have experienced simultaneous unexplained die-off events. There are no corresponding spikes/increases in the cause of death charts. Protective acts have been in place and hunting is minimal.

Server is running Alpha 4.1

![image](https://cloud.githubusercontent.com/assets/6193670/16759910/691a8ff4-486d-11e6-9d43-e226cb450e78.png)

**Comment by newzealdan** [comment]
This chart is confusing, but does't explain the above problem, but might be of interest

![image](https://cloud.githubusercontent.com/assets/6193670/16872563/9b7f87a8-4ae1-11e6-914c-e9b0dd88f664.png)

It would be nice to have a "clear selections" buttons for charts

**Comment by newzealdan** [comment]
What do animals eat anyway?

**Comment by mariowenig** [comment]
I have updated the wiki with Food Sources and some info a few days ago.
http://eco.gamepedia.com/Animals
These are the default settings provided by configs.
If you have access to the server, or want to see for yourself. 
Download and fire up a server.
Go to the Simulation tab
Click Config tab
Click on the Species (Collection) and open it up. A little ... shows up on the right.
Click Elk (example)
Find Food Sources, open Collection ... again on that.
Default checked for Elk are Camas, Huckle, CommonGrass, BunchGrass.
There is also a MaxFoodFindDistance that is set to 64 for Elk.

Hope this helps.
Like I said, I did add those values already to the wiki under animals, since I am sure lots of people are interested in those values.

**Comment by mariowenig** [comment]
I am not sure if player planted crops are used for this, but I started planting extra seeds I have in areas of Elk mingling. To provide them with food. Once your yield skills is high enough you will have plenty of excess of camas and huckleberry seeds to plant for them.

Keep in mind, depending on soil those plants might not spread. Check into Huckleberries:
SpawnChance: BlockType ForestSoilBlock (meaning it will not spawn on GrassBlock tiles, but the darker forest soils only. Camas: BlockType GrassBlock. :)

**Comment by mariowenig** [comment]
"Population"
![image](https://cloud.githubusercontent.com/assets/10489431/16896941/e36a757a-4b70-11e6-90c6-8e274246dae0.png)

Elk Chart
![image](https://cloud.githubusercontent.com/assets/10489431/16896949/0e582340-4b71-11e6-9021-c87216996166.png)

Hare Chart
![image](https://cloud.githubusercontent.com/assets/10489431/16896953/23a08b98-4b71-11e6-950e-356a4efd5734.png)

Wolf Chart
![image](https://cloud.githubusercontent.com/assets/10489431/16896958/37f9a2aa-4b71-11e6-8632-3d345d7430b2.png)

**Comment by mariowenig** [comment]
We found our cause, why the food value dropped we dont know.
![image](https://cloud.githubusercontent.com/assets/10489431/16899259/a1287cb0-4bcb-11e6-984a-90590b65615e.png)
That is a pretty significant food value drop, are their famine disasters?

**Comment by newzealdan** [comment]
Things seem much more steady on the server you are playing on. The phenomenon you experienced isn't present here unfortunately for us. Good spotting - wonder what would cause that?

![image](https://cloud.githubusercontent.com/assets/6193670/16899745/5de60736-4c63-11e6-8ce4-1780800eef4c.png)

Out of interest, what is your pollution look if overlayed with the food and animal lines?

**Comment by mariowenig** [comment]
Doesn't seem to have a pollution correlation:
![image](https://cloud.githubusercontent.com/assets/10489431/16901717/599a51ae-4c19-11e6-9103-f6ef62a4a412.png)

**Comment by newzealdan** [comment]
I saw someone talking about this on the eco forums and thought I would follow up.
Since the release of 4.2 I am fairly happy to say that the unexplained die off is now explained. 

![image](https://cloud.githubusercontent.com/assets/6193670/17290577/430af9e0-5833-11e6-8ca8-09870dc3a7ad.png)

One I had enough food rolling in to feed me and 1 other I started a widespread replanting campaign, starting with bunch grass, then camas and then huckleberries. Populations of every animal had an upward trend. I planted along the coast, right across the planet really.
![image](https://cloud.githubusercontent.com/assets/6193670/17290943/257e42ea-5835-11e6-97d8-42769be0e9d3.png)

What I did notice though, is that the animals seemed to migrate. They just seemed to head south. If they couldn't go south without going north, they just congregated there. What would happen, is they would consume the food that was there (most of it), and then start to die from starvation. There were still plants around, but the starvation started to shoot up. 

![image](https://cloud.githubusercontent.com/assets/6193670/17290795/67b03a02-5834-11e6-90e9-1441eb366527.png)
![image](https://cloud.githubusercontent.com/assets/6193670/17290878/c3d14506-5834-11e6-85d2-4c2a94c216a2.png)

Interestingly enough, the numbers don't seem to quite add up. Previously, deaths had no explanation. Now, starvation numbers are unexplainably high (not enough animals were alive to start with, and they're not reproducing THAT much).
![image](https://cloud.githubusercontent.com/assets/6193670/17290919/ffac4986-5834-11e6-88fd-d7e7d17058d8.png)

Can't show you wolf starvation because it won't let me scroll down to select it on the charts.

Anyway, food population keeps increasing because animals are clustered tightly in some areas (particularly southern peninsulas). They don't wonder north at all really. They're starving yes, but only if they don't have heaps of food. I stopped the re-planting at about day 6 because we can't progress any further in the game anyway. Happy to answer any questions :)

**Comment by mariowenig** [comment]
The congregation of Elk/Hares on the shorelines seems to be a major issue.
Inland food source (Huckleberries are fine since they are in the High Lands)
![image](https://cloud.githubusercontent.com/assets/10489431/17334891/eae06f84-58a5-11e6-94e0-81fc4dd3acbd.png)
Camas/Wheat has been continuously decreasing without any Human help of replanting on our 4k world (which would be rather insane)
With the Hares dying off from starvation, and our wolf pop being 4x as large as our elk pop, soon elks will be dead with no food and being food for large wolf pop.

I think once breeding becomes a thing, these phenomenons might be controllable, other then going on wolf rampages and killing them off to allow Hare/Elk pops to regenerate faster.

**Comment by metachronism** [comment]
alpha 5 addresses a lot of this
