### ISSUE TITLE
Bug pollution

### ISSUE THREAD

**Issue by midn8t** [StrangeLoopGames/EcoIssues#4866]
seems to be some kind of issue with pollution

some reason if the pollution level goes up to certain level seems to break the system some thousand then on its own dropped to -20k%

and world kind of did this on its own.

![20180220092316_1](https://user-images.githubusercontent.com/15990789/36432540-0fe9d7c8-1620-11e8-995b-60d44c071e17.jpg)

the factory below did have some tailing out and some near water, but I do not get how it can go to such extremes up and down.

we also had issue with tailing multiplication in stockpiles where they duplicated them selfs and stockpiles randomly teleport around like carts. for example stockpile we had underground came to the surface.

**Comment by MarjieAVolk** [comment]
What version are you playing on?  I know we had some pollution issues that were fixed recently.

**Comment by midn8t** [comment]
1.2

I think what happened is level hit certain level over a certain amount and then system just broke down.

**Comment by craig-jong** [comment]
Has this happened any time recently? This could have possibly occurred because a /repopulate and then a fastforward.

**Comment by midn8t** [comment]
have not ran into it so far.

the thing ended game in 7.1.2 is meteor at time bugged out and hit ground multiple times.

**Comment by craig-jong** [comment]
My small testing hasn't produced anything similar.

Even under extreme pollution, the number doesn't behave like above. This was definitely a bug, but I'm going to chalk it up to repopulate unless someone else encounters the bug in a more recent build.

If anyone stumbles upon this and is having the same issue, it would be super awesome if I could get my hands on a gamesave where the issue is already occurring.
