### ISSUE TITLE
USER ISSUE: Server Rollback - Cart / Deed Loss

### ISSUE THREAD

**Issue by Jimmylurks** [StrangeLoopGames/EcoIssues#4899]
![deletemesoonish](https://user-images.githubusercontent.com/36611838/36469979-cdad86ea-16ae-11e8-8656-f316b1153d68.PNG)
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1) Server restart rolled back to a point where a small wood cart was upside down
2) Owned cart of mine said I didn't have the proper deed for it
3) Deed shows no location of the cart it belongs to

**Expected behavior:**
It should have remained my property and let me pick it up with a hammer.

**Actual behavior:**
It stayed flipped over and I couldn't recover the small wooden cart in any way while the deed remains on my person.

**Comment by Narone85** [comment]
[Desktop 2018.02.20 - 20.30.29.01 rev 2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1752433/Desktop.2018.02.20.-.20.30.29.01.rev.2.zip)
As discussed from the closed thread, uploading a short video with the issue i had (Sadly not how to reproduce as i don't know so just the problem). Had to speed the video up a lot due to file size restrictions but hopefully it's viewable.

**Comment by Narone85** [comment]
From the closed thread.

Just realized it wasn't the cart deed that i were unable to access, apparently it was an area deed, no idea where that one came from though as i have made sure two only make two area deeds. However, my cart deed seems to be gone too and i have no access to the cart that i owned before so the problem still exists.

Anyways, the film i mentioned that i could upload at least shows the area deed (when i thought it was a cart deed), but the problem is still clear, i am unable to give access to myself on that deed so like you mentioned MarjieAVolk, would be good to have a way to claim a deed again.

Had to speed up the film due to file size restrictions but hopefully it shows enough. 

PS. For those that lost access to a cart in the middle of the base, use dirt or similar, drop it next to the cart and it will slowly move further away.

[Desktop 2018.02.20 - 20.30.29.01 rev 2.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1754156/Desktop.2018.02.20.-.20.30.29.01.rev.2.zip)

**Comment by MarjieAVolk** [comment]
Looks like what you had was a default deed object, with all state lost.  It might have originally been your cart deed.

**Comment by MarjieAVolk** [comment]
@SeanAtr0n I had been thinking this was a save desync issue, but this bug reported something similar, but with the cart disappearing right in front of them: https://github.com/StrangeLoopGames/EcoIssues/issues/5107

Possibly there are multiple issues associated with this bug now though >>

**Comment by D3nnis3n** [comment]
I also do not have that deed view. My deed view is normal and shows name of the cart and it's position. But it's Missing Position with Marker on 0,0,

**Comment by MarjieAVolk** [comment]
Okay I will reopen yours.

**Comment by MarjieAVolk** [comment]
Fixed in 7.6 (not the release today, but the next major release after that) -- hopefully :P  Deeds have been deeply revised.
