### ISSUE TITLE
Tree seed issue / trees can grow on occupied space from another tree

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#490]
Trees that have been planted seem to have many layers of wood logs. This one tree has 7 trees worth of logs from just 1 tree. Just keep chopping and a new tree explodes out of it. Gonna be a pain to get rid of 7 trunks :( lol

![image](https://cloud.githubusercontent.com/assets/6193670/16835294/2e84d944-4a0c-11e6-973e-b4f376142265.png)

**Comment by mariowenig** [comment]
Interesting, are you able to reproduce this with more trees? Anything special about your tree farm? Have you had a tree right there before? Did you chop it down once and 7 trunks appeared or did you keep chopping and they kept appearing?

**Comment by craig-jong** [comment]
This is very likely the same bug as the original planting one. It seems like seeds just keep growing and growing forever.

Not sure if this is related, but it sounds like it might be.

**Comment by jhadred** [comment]
I was considering that possibility.  I checked my place this morning after seeing this post and it can be viewed on the dev server where I also has this situation, particularly outside the front door if someone wants to view it and try cutting them down.

  It also appears to be random.  In one place only 1 tree grew.  In another, multiple grew.  It's appears possible to tell based on the branches.  
In my situation with multiple trees which looked like copies of the same tree with the same branches but at very slightly different heights, I chopped down one tree and the there was still one standing.  

I couldn't tell if this could be the situation with the seed regrowth because in my situation, I've only planted trees in a spot once and these multiple trees all seem to have a similar growth level, but different enough that you could see replications of the branches.

**Comment by newzealdan** [comment]
Your explanation of how seeds growing forever could be right. Planted trees that have been left longer  or have had a longer grow time before harvesting seem to produce more faux-trees.

 Yes, 7 compete trees, took 70 chops to get them all out. 70 chops to get rid of the 7 trunks too.

**Comment by metachronism** [comment]
This shouldnt be possible anymore
