### ISSUE TITLE
7.1.2 - Possible Tailing Storage bug?

### ISSUE THREAD

**Issue by Mahsaap** [StrangeLoopGames/EcoIssues#4992]
Hello,

So, I have done some testing on [Tailing] for the wiki and noticed that I can store [Tailing] in [Hewn Logs] and [Mortared Stone] towers safely with no leakage. 

The tower is 1 bottom layer level with the [Dirt].
[Stockpile] in the middle filled with [Tailing].
Every direction is then covered with 10 layers of the corresponding material.

![unknown](https://user-images.githubusercontent.com/13688718/36598270-01620cd4-1882-11e8-85ab-c28d19cd1a3f.png)

This image displays the towers after I removed just 1 layer (total 9) from the top. When I had 10 layers there was no leakage what so ever.

Is this the proposed method of how they should work? Or is it only supposed to be specific materials?

---edit--
Additionally, the towers were there with 10 layers for at least 2-3 game days maybe more, Once I removed the 1 layer it took 2-3 ticks to show.

Build 7.1.2

**Comment by MarjieAVolk** [comment]
Yes, this is actually working as intended :P We have been planning to revisit how tailings storage works.

**Comment by Mahsaap** [comment]
I brought it up because Pam ask meta and said it wasn't supposed to happen that way. So unless information was list between the conversations, I'm getting 2 different responses to this situation.

The response was only dirt underground should work.

**Comment by Mahsaap** [comment]
If someone (dev) gave me the most accurate description for what is supposed to be done for tailings. I can update the wiki accordingly. Taking out any guess work or mis communication from others.
Would be greatly appreciated and I can close this issue. Cheers keep up the great work.

**Comment by MarjieAVolk** [comment]
Well for this particular feature, I guess it's somewhere between 'working as intended' and 'known issue', in that we've wanted it to work differently for a while, but haven't actually hammered out what the new behavior should be yet.  So that's probably why you are hearing different things from different people.

**Comment by Mahsaap** [comment]
Ok ya that makes sense I'll close this then. Thanks for the response.

**Comment by MarjieAVolk** [comment]
I'm gonna leave it open to remind ourselves to change it

**Comment by ZeelNightwolf** [comment]
Hi, Ive been doing testing on that storing of tailings. I have discovered you can use the following to creat e just a roof above the tailings and the pollution will stop being created. I know this is "known issue"/ revise in the future but wanted to leave the here anyways since a roof made out of pipes,roads and rubble was amusing to me. 

Building Materials:
All Brick Forms
All Corrugated Steel Forms
All Flat Steel forms
All framed glass forms
All hewn logs forms
All lumber forms
All mortared stone forms
All reinforced concrete forms
Glass

Word Generated Blocks:
StoneBlock
IronOreBlock
GoldOreBlock
CopperOreBlock
DirtBlock (any biome)
SandBlock

Stacked4Blocks:
StoneStacked4Block
CopperOreStacked4Block
IronOreStacked4Block
GoldOreStacked4Block
LogStacked4Block


RoadBlocks:
TilledDirtBlock
StoneRoadBlock
AsphaltRoadBlock

PipeBlocks:
CopperPipeBlock
IronPipeBlock
SteelPipeBlock

**Comment by craig-jong** [comment]
I changed how tailings work. Be sad and happy at the same time!
