### ISSUE TITLE
USER ISSUE: No idea wtf happened

### ISSUE THREAD

**Issue by pretzL** [StrangeLoopGames/EcoIssues#4997]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Got kicked out of our game with this bug report thingy. No clue how or why it happened, sorry.

**Expected behavior:**
It should have kept me in the game?

**Actual behavior:**
The following error message popped up:
```Caught Exception: Object reference not set to an instance of an object```
Caught exception: Object reference not set to an instance of an object.
```

**Comment by NortonDK** [comment]
Happened a lot with me too, same version

**Comment by MarjieAVolk** [comment]
Thanks for the report - We've gotten a number of these, and unfortunately I don't know how to track it down without a better error message.  For the next patch, we are going to make sure a better error message gets returned, so that we can start fixing these.

If you happen to be able to get a more complete stack trace from the server logs, I could try to work from that.
