### ISSUE TITLE
USER ISSUE: probleme pour ce log

### ISSUE THREAD

**Issue by netocloud** [StrangeLoopGames/EcoIssues#5043]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
je mais mon psaudo et le  mdp il me dt invalid username or password.

**Expected behavior:**

**Actual behavior:**

**Comment by MarjieAVolk** [comment]
Désolé pour la traduction automatique. Je ne comprends pas quel est votre problème, car mon traducteur ne peut pas le gérer. Peut-être à cause des abréviations. Vous rencontrez un problème de connexion. Je peux vérifier si votre compte Strange Loop est cassé. Quel est votre nom d'utilisateur Strange Loop?

EN:
Sorry for the automatic translation.  I can't understand what your problem is, since my translator can't handle it.  Perhaps because of the abbreviations.  You are having some kind of login problem.  I can check if your Strange Loop account is broken.  What is your Strange Loop username?

**Comment by MarjieAVolk** [comment]
Closing due to no response
