### ISSUE TITLE
Gathering with scythe costs energy, gathering by pressing E is free

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#511]
A scythe is for harvesting crops (camas, huckleberries, ferns, wheat).

I understand that if your stomach is empty, you can't do any work. If you have no food in your inventory and can't get any from anyone else you would be doomed (to die perhaps?) Fortunately, you can gather food (camas, huckleberries, ferns) by pressing E as that doesn't cost any calories.

To gather wheat you must still use a scythe.
But why would you use an calorie intensive scythe to harvest camas, huckleberries and ferns when you can just press E for free?

Probably this isn't a bug but is just an alpha feature to enable alpha-testing?

**Comment by mariowenig** [comment]
Hey newzealdan, as you explained the picking with E prevents the starved deadlock of not being able to eat. Not sure if the following is the case, please verify if you can. 

Test: Does picking with E vs using scythe apply the harvesting modifiers for obtaining extra resources/seeds?

If indeed those are applied, then that should be fixed. Guessing picking with E should not apply modifiers vs harvesting with Scythe should.

**Comment by jhadred** [comment]
After realizing that E would work on grown crops per http://ecoforum.strangeloopgames.com/topic/677/farming-weird-issue  I've been using E (except for the situations of an early test).

It's possible that E is intended to pick/pick up in this situation as with berries, you're picking them from branches with your fingers, fern fiddleheads are normally harvested with bare hands, snapping them off rather than cutting, and with roots, you're pulling them from the ground (though the shovel would also make sense.).  The scythe is, however, necessary for both wheat and bunchgrass in both wildgrowth and farmed growth.  

Gamewise, using E does give me the same positive benefits on harvest amount as well as seed amount, just the same as using the scythe.

**Comment by mariowenig** [comment]
Gonna guess that will be changed eventually. Otherwise it does not balance well with new users vs more experiences farmers. Ultimately up to the SLG devs on how it should  be handled.

My thought would be:
E: Camas, Huckle, Wheat(curernt exception) should give base resource (not destroy plant), no seeds
Scythe: All should give modified values + seeds (modified values)

Making lvling into farming/scythe to be the farming way, and E the basic consumption way (low hunger, new players)

**Comment by newzealdan** [comment]
@mariowenig Sounds good! :)

**Comment by PhosphorDragon** [comment]
I think if the land has been hoed or in a players plot only a scythe can harvest it but if the plant is wild E should work also.

**Comment by metachronism** [comment]
gathering has changed, now more specific tools required to gather
