### ISSUE TITLE
USER ISSUE: Flying rocks

### ISSUE THREAD

**Issue by ImCracking** [StrangeLoopGames/EcoIssues#5117]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. Mine a bloc 	

**Expected behavior:**
It should have fall to the ground

**Actual behavior:**
Instead it floats in the air

**Comment by pmeyerson** [comment]
I had this happen to me today.
I was returning to a tree on the ground I had chopped into pieces.  As the tree pieces came into sight, they started flying!
This was after I had used the /unstuck command because I got stuck somehow building my house.
https://imgur.com/a/7hdzh
https://imgur.com/a/EdCVv

0.7.1.2 beta, win10.  Nothing logged (pun intended!)

**Comment by SeanAtr0n** [comment]
fixed 7.2
