### ISSUE TITLE
Extreme low FPS / laggy (MacOS)

### ISSUE THREAD

**Issue by fwohlfarth** [StrangeLoopGames/EcoIssues#5119]
Hello,

i am using / testing Eco Version 7.1.2 and 7.2.0 Beta on my Macbook Pro 15, 2017 with Macos High Sierra. Both Eco Versions has exactly the same issues.
On every Graphic settings i get a laggy game with 15-30 fps.
I tryed with windows mode too and there i have under 15 fps. I found a issue with graphic saves too.
Every time i try to set the resolution to Full HD it not saves my settings there. In the most cases it jumps back to 4k resolutions.

The next issue is, to start the game: it takes around 4-5 Minutes to start the game and has a high cpu using.

Please fix the extreme perfomance issues on Mac Systems. There are much more issues, but it take to long time to post all these issues on mac systems.

**Comment by haniawni** [comment]
I'm facing this exact same problem. LONG startup time only to find that even **the menu** is difficult to navigate due to extremely low (low teens?) fps. It has been like this since the _original alpha release in Nov 2015,_ I've checked back in regularly figuring it'd get fixed eventually but no dice. 

Consequently, I've yet to see more than the menu screen of this game.

I've made a meme to express how this makes me feel:
<a href="https://imgflip.com/i/2696pn"><img src="https://i.imgflip.com/2696pn.jpg" title="made at imgflip.com"/></a>

Thank you all for your work on the game! Looking forward to playing it when possible!

**Comment by haniawni** [comment]
Hi! turns out theres a settings menu you can access on the main menu through hitting escape; I'm gonna explore how the fps varies on my machine across the different graphics settings:

## All Other Settings Disabled, Fullscreen:
- 640x480: 58fps
- 800x600: 46.4fps
- 1024x768: 33fps
- 1280x800: 25fps
- 1440x900: 22fps
- 1680x1050: 17.2fps
- 2048x1280: 12.3fps
- 2560x1600: 8.6fps
- 2880x1800: 5.2fps

Turning on all the default-on graphics options makes no visible difference to fps in the settings menu (unsurprisingly), at least at 800x600.

**Comment by SlayksWood** [comment]
Computer specs are:
![image](https://user-images.githubusercontent.com/45708377/56811255-ffc7f180-6840-11e9-9fc6-aefd4f42709b.png)
FPS in main Menu:
5120x2880 - 14fps
2560x1440 - 36.1fps
1920x1080 - 48.8fps
I tested with resolution 1920x1080. It's very low FPS in game (Other better resolution unplayable)

**Comment by D3nnis3n** [comment]
Seems okay. I don't get more than 35 fps in 2560x1440 in Windows either ...

**Comment by SlayksWood** [comment]
We have FPS improvements in 8.3. Also we have some improvements with FPS dropping in 0.9.0. And have some issues about FPS improvement. Closed for now.
