### ISSUE TITLE
USER ISSUE: Roof block bug?

### ISSUE THREAD

**Issue by Gice020** [StrangeLoopGames/EcoIssues#5126]
![1](https://user-images.githubusercontent.com/36849199/36671596-775c28d0-1afc-11e8-93f1-d4d8825d3edf.png)
![2](https://user-images.githubusercontent.com/36849199/36671599-7a732212-1afc-11e8-81c3-7ab1d13694f6.png)
![3](https://user-images.githubusercontent.com/36849199/36671601-7d1afad0-1afc-11e8-8658-590dfb0e89ac.png)

**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Try building a pointy roof.	

**Expected behavior:**
The roof blocks should have the sloped appearance.	

**Actual behavior:**
As soon as there's a roof block next to another the sloped appearance changes to the flat one.

**Comment by Conchipedia** [comment]
where you have the Wood on the roof, if you make that also a roof block then the roof will slope
![snap1826](https://user-images.githubusercontent.com/29383891/36688640-012157de-1b25-11e8-8ef5-e3306c2849fa.png)

the bumps at the front is because those pieces are also roof blocks but they are shown as the flat front
so you are really placing two rows of roof blocks then above another two rows its the only way to get the roof to slope properly.

![snap1835](https://user-images.githubusercontent.com/29383891/36689022-18d3fa8e-1b26-11e8-809a-fd50744a5b68.png)
![snap1836](https://user-images.githubusercontent.com/29383891/36689045-2bf696e4-1b26-11e8-83ed-44fcf2cffdd7.png)
![snap1837](https://user-images.githubusercontent.com/29383891/36689057-3808715a-1b26-11e8-8b25-d28a7040d462.png)

this is the only way i know how to get a sloped roof, because if you dont use a roof type block the roof above it will just go flat

**Comment by MarjieAVolk** [comment]
We had another bug to support this case, but looks like it was accidentally closed.

**Comment by keegan-o** [comment]
I'm going to consider this part of the general Roof Builder legacy un-idealness to be fixed and thus this is a duplicate.
