### ISSUE TITLE
SUGGESTION: Incinerator or Recycling

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5183]
Despite trying to distribute Everything created to People with a need for it we got a lot of useless things we would like to have to vanish. Especially old tools. 

Recycling would be an Option to get ingredients back. Another option, especially for not recycable things would be an incinerator producing co2 and electricity depending on the burnt thing. Maybe even tailings could be burnt for high co2 output. I don't know what they so with it in real life.

**Comment by Huntermeign** [comment]
In real life Tailings are actually processed even further in a more polluting fasion to get more metals out of it. For the most part though, Tailing storage facilities are some of the largest known man made structures and are stored as backfill of mines created. So basically what we are doing already by storing it underground. 

Difference in real life thouh, is its generally slag thats produced from bloomeries or smelteries and tailings are produced from a series of chemical processing of the gathered materials to separate the metals from the rock which creates a sludge like waste we call tailings. This is then either stored in tailing ponds, created into dry tailing piled where they are back filled into the old mines. submerged into the ocean (Like how some people did with carts) and other methods such as phytostabilisation using Hyperaccumulator plants (plants that absorb metals from the soil)

To put into perspective of how much tailing is actually produced, its about 1 part usable ore to 40-49 parts unusable rock for ores like copper. If this were to be implemented and tailings became sludge instead for early and mid game, it would have to be way later in the game. 

Trying to burn tailings is like trying to burn stone. It cant be done because its mostly comprised of elements that cant be broken down through burning methods.

**Comment by Huntermeign** [comment]
Yeah but even then it would maybe only reduce tailings by like 40% But the metals we extract irl arent in game (yet?). (Nickle, Aluminum, etc)

**Comment by D3nnis3n** [comment]
We definatley need a solution. The produced Tailings are way too much at the moment. We don't feel happy with how it is now.

**Comment by Huntermeign** [comment]
Thats the interesting part. The tailing we produce are at a much larger ratio irl. While we have had a problem with newer players and tailings though, underground storage has worked and blast furnaces make for CO2 instead of tailings atm. (which also makes slag irl)

**Comment by D3nnis3n** [comment]
As of my knowledge i heard the ratio is off, e.g. in Eco you produce way more tailings as you would in RL. Some other issues exist for this view, too. I agree to this.

For now, we will start banning players producing tailings despite a given warning, as we got no other choice. Burying for new players works after much explaining, but even then it's still polluted with those who don't. We also thinks it's way to overpowered in polluting. While we do not manage to make any impact with CO2, the impact of the tailings is massive and just not fun. The burying isn't too. It's just too much.

**Comment by Huntermeign** [comment]
Depends on the ore really as far as tailings go. Copper is an extreme example where others are closer to 1:1. The ones closer to 1:1 arent in high demand like copper is though. This is why scrapping for copper is so in demand right now

 And dont ban players. Defeats the purpose of the game. When laws work again, make em. Its a learning experience. Unless you are playing no meteor, then theres no worrying to the ground pollution. It eventually goes away once tailings are moved deeper.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#227
