### ISSUE TITLE
SUGGESTION: Improve Excavator and Powered Cart Steering

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#5242]
As for those two all players on our server say the same:
The excavator is absoluteley unintuitive to use and every player is faster doing the job by hand then doing it by this curios control mechanism, which makes the Excavator pretty useless.

And as for the Powered Cart most players thinks it has a much too high turn range.

Maybe you can optimise a little bit there.

**Comment by D3nnis3n** [comment]
For the steering a much more fluent usage of the arm would be appreciated, my players told me.

**Comment by ProFatBoi** [comment]
I will second this. Went round today making all roads 4 wide for when i got the powered cart and the cart doesn't actually turn enough to go round the corners. Seems to carry on driving forward more then turning.

**Comment by fillion07** [comment]
As a workaround for now,
what I usually do for powered carts, is to build curvy intersections instead of a square corner intersection (same idea for curves). For ramps near intersection, I make sure the ramp is at least two blocks away from the intersection to avoid the cart drifting on the ramp when turning (same idea for curves). The last suggestion: 8 wide roads is not too much overkill when you start using powered carts.>
The idea is give them space: no tight roads, no tight corners and 
promotes straight roads. 

You want to avoid this:
![image](https://user-images.githubusercontent.com/7052045/37000033-00d780a8-2090-11e8-8f9d-551880c83194.png)

You want to have this:
![image](https://user-images.githubusercontent.com/7052045/37000247-cd338084-2090-11e8-8951-bf0f6b96f2cb.png)

**Comment by ProFatBoi** [comment]
Hello, thankyou for the suggestions. 




Unfortunately the world has been built up around a 4 wide road. Will try to sort the corners to make it easier to turn round. 




Is there any word on the powered carts getting better handling?




Get Outlook for Android







On Mon, Mar 5, 2018 at 9:18 PM +0000, "fillion07" <notifications@github.com> wrote:












As a workaround for now,

what I usually do for powered carts, is to build curvy intersections instead of a square corner intersection (same idea for curves). For ramps near intersection, I make sure the ramp is at least two blocks away from the intersection to avoid the cart drifting on the ramp when turning (same idea for curves). The last suggestion: 8 wide roads is not too much overkill when you start using powered carts.>

The idea is give them space: no tight roads, no tight corners and

promotes straight roads.


You want to avoid this:




You want to have this:

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#222
