### ISSUE TITLE
USER ISSUE: Login as wrong character

### ISSUE THREAD

**Issue by dustinpianalto** [StrangeLoopGames/EcoIssues#5271]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
Unknown,
Every time I login to this server I start as Travelers Wings instead of My character. I have restarted Eco, logged into different servers, etc. Apparently this happens on this server from time to time.

Server Name: Tag/Geeks Eco Crazyness

**Expected behavior:**
Login as my character

**Actual behavior:**
Logs in as Travelers Wings

**Comment by MarjieAVolk** [comment]
So to clarify, this issue only happens on a single server?  And on this server, sometimes you login as your normal character?

Can you check /whoami on this server for both your normal character and your 'Travelers Wings' character, and show me a screenshot of it?

**Comment by dustinpianalto** [comment]
I have yet to login as my character. My first time logging in to this server I started as someone else. I will try that command. It says I am not logged into an account and it won't let me link my steam account to my eco account.

**Comment by dustinpianalto** [comment]
![382310_20180301093533_1](https://user-images.githubusercontent.com/16179393/36862942-cd3e6350-1d34-11e8-9fde-a3460a38f0b9.png)

**Comment by MarjieAVolk** [comment]
Oh okay, so it always happens on this server.

It's okay that you can't link your steam account.  We are no longer supporting that, because it was allowing people to scam us and get the game for free.  But it shouldn't affect you normally.

You can double check that this is your correct steam id if you like, by going to a tool like steamidfinder.com.  I would guess that this is your correct steam id though, and that this user on this server was able to log in while the server had require auth turned off, and created this character that was not associated with any ids, so that when you logged in you were given this character with no ids and put your ids on their account.  This is this bug: https://github.com/StrangeLoopGames/EcoIssues/issues/4296

Although I thought that this issue would be fixed by now.  When was the first time you logged in as this other name?

**Comment by MarjieAVolk** [comment]
Oh wait, nevermind - The fix for this is only in the staging build.  So hoooopefully this sort of thing will not happen again after the next release.

For you right now however, it will be hard to fix this problem on this server.  No one else should be able to log in as your 'Travelers Wings' character anymore, but if you do want to change your name, what you will need to do is first remove everything to do with that character that you can from the world (eg. unclaim all property, pick up all carts that you own), put all the things you want to keep in a chest somewhere, and then ask the server admin to delete your character file.  The character file will probably be named just "_".  Make sure they make a backup of the save file before doing this, in case deleting the character causes issues.  Then you should be able to log in as a fresh character with your own name and go pick up your things.

**Comment by dustinpianalto** [comment]
About an hour ago was the first time I connected to this server. And Yes I can verify that that steam ID is mine. I admin other games and we whitelist based on Steam ID so I am very familiar with my ID. Ok, thanks for that issue.

**Comment by MarjieAVolk** [comment]
Okay, well in that case I would suggest you just play on another server for now.  Hopefully you won't encounter this issue again.
