### ISSUE TITLE
USER ISSUE: Cannot abort finished board process

### ISSUE THREAD

**Issue by ecreators** [StrangeLoopGames/EcoIssues#5322]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1. No Building
2. Build a carpenters table
3. Produce 20 Boards

**Expected behavior:**
I cannot cancel this production, because it's already finished and I have not enough space in inventory to build up other materials.

**Actual behavior:**
I cannot abort / deconstruct it until it was placed in then world, but I can't place it into the world (no building there)

**Comment by MarjieAVolk** [comment]
Okay, I am going to restate your problem, to make sure I understand.  You put down a carpenter's table outside, so its requirements were not met.  You started a project to make 20 boards on the table, and you added some logs to the project.  Then you realized you needed to put it inside a room, so you tried to pick the table back up.  But you couldn't pick up the table because of the project, and you couldn't cancel the project because it had too many logs for you to carry already in it.  Is that right?

For now, what you can do is build a stockpile, and link the stockpile to the carpenter's table via the carpenter's table's Storage tab.  Then when you cancel the project, the logs can go into the stockpile.  (This can also work with a cart.)

What we should do to fix it is not let you start projects while the table's requirements are not met.

**Comment by MarjieAVolk** [comment]
I think I'm going to close this as won't fix for now.  We've changed around starting items a bit, so you will start with some storage now, which should help prevent cases like this.
