### ISSUE TITLE
USER ISSUE: Stuck Connecting

### ISSUE THREAD

**Issue by R0n1n5** [StrangeLoopGames/EcoIssues#5324]
Good Morning,

When I click on NEW to generate a new world it goes through the motions (Initializing, generating, ticking) then just stops on Connecting (have to go to Task Manager to End Program)

If I click LOAD the generated world shows up, I can click to load it, it then goes through the same motions (generating, loading...) then stops on Connecting again.

I've uninstalled, reinstalled, completely deleted all folders and files, disabled my firewall, disabled my routers firewall, opened ports 2999-3001.  Turned down all the settings.

I'm officially out of ideas.

Version: 0.7.1.2 beta

**Comment by MarjieAVolk** [comment]
Hey, sorry you've been having trouble.  Some things you can try are selecting 'Generate new' when creating a world, or creating a world with the 'Eco Server' tool instead of in-game.  Let me know if that works for you.

**Comment by MarjieAVolk** [comment]
Several other people have reported this issue, so we are looking into it.

**Comment by metachronism** [comment]
@R0n1n5 are you in a locale other than en-US ?  I suspect a localization issue was causing your crash, and I believe we have since fixed this issue, let us know if that is not the case by reopening this bug

(and if you still have the files, browsing to Server/Dump you should have some logs there that might help us figure out more)
