### ISSUE TITLE
Unlimited barrels by skill efficiency

### ISSUE THREAD

**Issue by neutronc** [StrangeLoopGames/EcoIssues#533]
If you skill up refining efficiency you'll need less barrels to produce one petroleum, but upon refining you still get per petroleum one gasoline and one barrel. Thus the first skill level in refining efficiency is netting you 28% of barrels.  The refininf efficiency should be taken into account in a negative way to yield 28% less barrels on refining actually ?

**Comment by mariowenig** [comment]
Not sure this can be fixed easily.

Assume you are making 10 petroleum and save 28% on barrels on level 1 getting your 10 Petroleum at 8 barrels used. Refinery will get your 1 barrel per petroleum resulting in 10 barrels (netting your 2 extra barrels). In order to fix this the math would have to deduct your refining skill when making gasoline, which in case would require you to make the same batch amount i.e: 10 gasoline (which I dont think can be kept track on between different tables.

Requirement for this to work; Make X petroleum and force user to make also X gasoline of it, to keep barrel amount the same.

At 28% example:
8 Barrel -> 10 Petroleum
10 Petroleum -> 10 Gasoline, 8 Barrel (deduction refining skill barrel generation)

It is possible i guess, but this would mean on smaller batches you would lose barrels (which shouldn't be the intend) 

I do understand the main concern, that you would continuously gain barrels (which aren't expensive, but also not super cheap either.
Please do not remove Barrel gain from Petroleum -> Gasoline conversion!!! That would be :-1:

**Comment by metachronism** [comment]
this should no longer be possible
