### ISSUE TITLE
Election / Single Candidate = Tie = No leader.

### ISSUE THREAD

**Issue by mariowenig** [StrangeLoopGames/EcoIssues#540]
![image](https://cloud.githubusercontent.com/assets/10489431/17160486/50ba11a8-5373-11e6-807d-034659503c76.png)
Highlighted some issues found.

**Comment by MarjieAVolk** [comment]
I believe this is intended behavior.  Election results are not valid if only one candidate runs.  The display issues you pointed out are problems though obviously.  Seems like we should have some explanatory information for why no one was elected as well.

**Comment by rainfarmer** [comment]
This should all be working now.

I am able to win an election with 1 vote and 2 candidate.
https://gyazo.com/e619d5aabc0cb89940fba7fe990abada

That might be because there are only 2 users, which 1 vote would be 50% of the votes.
I tried testing with more users, but did same thing. 
I used the /generatetestdata query, so it might act different with real users?
