### ISSUE TITLE
Game crashes to windows when opening storage or skill menu. 

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#5457]
"I have a problem, when I play eco and I open a menu (storage or skill) the game closes and I return to windows without any error message. Config : Win7 / Gtx 1070 / I5-4670k 8go RAM..."

**Comment by MarjieAVolk** [comment]
O.o

**Comment by MarjieAVolk** [comment]
Can you ask them, are they running their own game?  Or are they playing on another person's server?  When they crash, does the server also crash?

If they are actually crashing, then they prooobably won't have anything useful here, but ask them to attach their log file at 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt'

I am wondering whether you don't want to have people file their own bugs, since often I will want to ask them more questions.

**Comment by MarjieAVolk** [comment]
Okay well, I can't really do anything with this as is, so closing for now.  Can reopen if you get more info.
