### ISSUE TITLE
Truck too heavy to pick up and place

### ISSUE THREAD

**Issue by combatbanana** [StrangeLoopGames/EcoIssues#546]
Truck unit instructs to place in the tool bar and right click to place but when attempting to do so it says it is too heavy to be carried and then returns to the chest/cart.  says its 500 kg.

**Comment by mariowenig** [comment]
@combatbanana We encountered the same issue with the Truck, somehow one user was able to place it (believe by emptying their entire inventory. The truck has no usage and is just a chest when placed. Recommend not placing it, since you wont be able to move it and it neither drives, nor has inventory.

**Comment by jhadred** [comment]
I also recall a mention of hitting the workbench (or cart) with a hammer so that it went into their carrying slot rather than trying to drag it in.

**Comment by metachronism** [comment]
trucks aren't intended to be working yet, so closing this for now
