### ISSUE TITLE
Stockpile is not used for workqueues if you are not owner

### ISSUE THREAD

**Issue by ItsReddi** [StrangeLoopGames/EcoIssues#5466]
2 Players:
First Player 
1. claim something
2. create a stockpile and store some wood / stone
3. set a workbench
4. give the player 2 all rights
5. if you want to build something the materials will be used automatically from stockpile
---
Second Player
1. Build something in workbench
2. Stockpile will not be used

Expected:
The stickpile would be used for 2nd player also

**Comment by MarjieAVolk** [comment]
Each person can customize which storage is used by a crafting station, by going to the 'Storage' tab on that crafting station and checking the checkboxes for whatever storage they want to use.

When you are on your own property, these checkboxes default to on.  But on someone else's property, they default to off.  This is done to protect your crafting output from going to others' storage.

Once we implement this feature, we should be able to fine tune the default settings even more, so that your case will work better by default: https://github.com/StrangeLoopGames/EcoIssues/issues/2190
