### ISSUE TITLE
USER ISSUE: Waypoints

### ISSUE THREAD

**Issue by Sebi92** [StrangeLoopGames/EcoIssues#5481]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
The waypoints are acting weird. If you are standing next to them, it shows you (in my case) 700 meters away

**Expected behavior:**
The waypoint should be about you

**Actual behavior:**
Instead it wants you to run around the whole world and get back to the same point

**Comment by thibaut-fagart** [comment]
I've been seeing this too, both in 7.1 and now in 7.2.

The direction hint to the waypoint is not always in the correct (shortest) direction

See the below screenshot, i've circled the pumpjack on both visual screen and map, and the associated waypoint
![image](https://user-images.githubusercontent.com/1150232/37079931-b26e4a0e-21e4-11e8-8123-f9f2dc35c5be.png)

**Comment by thibaut-fagart** [comment]
I should mention that once i get close enough to the waypoint it fixes itself

**Comment by Thyriel** [comment]
Didn't saw this here when i posted https://github.com/StrangeLoopGames/EcoIssues/issues/5692

The cause is simple: Waypoints are displayed like we would play on a flat map with edges, so instead showing waypoints by the shortes available path it's showing them only within the x/y grid and nit taking into account that the zero coordinate is not the end of the world

**Comment by johnkslg** [comment]
Fixed
