### ISSUE TITLE
USER ISSUE: Bug reporter doesn't scroll when text goes past box.

### ISSUE THREAD

**Issue by Tannyr** [StrangeLoopGames/EcoIssues#5553]
**Version:** 0.7.2.0 beta

**Steps to Reproduce:**
Fill a text box with more lines of text than can fit.

**Expected behavior:**
character limit / scrolling down

**Actual behavior:**
text goes offscreen but can still be entered

**Comment by MarjieAVolk** [comment]
I took another look at this, and it looks like it's working as intended.  It's true there is no scroll bar and you can't use the mouse wheel, but the text scrolls to your cursor as you're typing, and you can scroll back up by arrowing up beyond the top of the box.  I think this is good enough, since we don't have much control over how these text boxes work.
