### ISSUE TITLE
USER ISSUE: Room Stops being a Room

### ISSUE THREAD

**Issue by KatherineOfSky** [StrangeLoopGames/EcoIssues#5659]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**
Removed corner wall from an adjacent room, then replaced it.

**Expected behavior:**
Should not affect current room.

**Actual behavior:**
The room stopped being a room.  I picked up and replaced the furniture and it becomes a room again.  (I removed the Ice Box and the Bakery Oven.  I left the Mill alone).   All functioned after removal/replacement.

Sometimes the room stops being a room randomly, when I am nowhere near my house/workshop.  (Playing singleplayer).  It's always the Kitchen Room that has this issue.

**Comment by Teemine** [comment]
Same has happened to me when i logged in to my world today.

**Comment by D3nnis3n** [comment]
We had the same, removing and replacing a door did fix it for every room.

**Comment by Splutty** [comment]
I've had this issue. Several things were involved in different cases:
- One had a tiny corner not claimed, which causes issues when changing the walls.
- One just took a few minutes to register as a room again (but this was during the performance problems, so that might not be related at all)
- Your case where you've removed a corner block and the room doesn't regain room status after replacing the corner block is one I've seen a lot of times, and is indeed so far only solvable by changing something in the room itself (dropping a chair generally works for me)

**Comment by SlayksWood** [comment]
Checked on 0.8.2.9. Wasn't able to reproduce. Seems fixed.
