### ISSUE TITLE
(Reproduce included)Unlimited Claim stakes through exploit of un-learnable scroll

### ISSUE THREAD

**Issue by SirusDaggani** [StrangeLoopGames/EcoIssues#570]
Not sure if it's client or server side, but it is easy to reproduce. 

Steps to reproduce:
1.  Do not place any points in Research tier tree.
2. Have another player research the Advanced Research Book that requires Basic Research Level 4 to learn. 3. Produce unlimited scrolls with the Advanced Research Book.
4. Player that has NO points in Research tier tree can use the scrolls infinite times since it never learns the skill in the tier tree, so it assumes you are learning it new each time.

Result: You can have infinite claim stakes which could cause a massive game breaking unbalance of power. Since player with nothing unlocked in Research tier cannot unlock the Advanced tier without unlocking the prior tier... it just loops over and over.

**Comment by metachronism** [comment]
Probably need to make sub-tree skill learning handle prerequisites

eg, can't use/learn butchery scroll till you are level 4 in campfire cooking

**Comment by pan7s** [comment]
Same goes for a lot of scrolls.  I think it depends on the world because for me it changes.  One time I used masonry scroll over and over.  Says I already learned skill but gives me claims. But then another time masonry did not do this.  Sometimes baking scroll too. Says already learned but gives claims anyway.  This is a huge issue I think for sure for any multiplayer server that is decently populated

**Comment by metachronism** [comment]
Verified this is fixed in alpha 5.
