### ISSUE TITLE
0.7.2.3 Linux Server - 9km World - Very long startup times

### ISSUE THREAD

**Issue by Yorkforce** [StrangeLoopGames/EcoIssues#5771]
Since 0.7.2.3 our linux server is taking a very long time to start up, usually around 20-40 minutes, around half of this time is taken by the compressing section.
On 7.2.2 and lower it took around 10 mins to start up which was bearable.

Our machine has a intel xeon E5-1650 hexa-core CPU and 256GB RAM with SSD drives so its not a case of lack of hardware.

In comparison to windows on a budget AMD FX quad core CPU and 12GB RAM with a non-SSD drive with the same world, it takes 3 minutes to start up.

**Comment by LiaungYip** [comment]
The server start time has also increased noticeably for a 1km² world on Linux. Again, the extra time is taken up by `Compressing...`

**Comment by Yorkforce** [comment]
Indeed, I'm just concerned at this point that we won't see a hotfix for this until next major version, as it currently stands we are losing alot of players from the server, it's really frustrating when you put in a ton of time/work in trying to build a good community/server, even more so when you're one of the more active servers out there.

**Comment by Yorkforce** [comment]
Scratch that above, even with Compression None its still compressing during start up...

**Comment by Yorkforce** [comment]
Testing on 7.2.4 with same world:
Startup time Linux - 24mins
Startup time on Windows - 2mins 2seconds

**Comment by kicker22004** [comment]
Can confirm this is an ongoing issue for Linux hosting. And I know it's not officially supported but Devs should keep and eye on this link..... https://ecoservers.io/

Prior to this Compression bug some of the most played servers were hosted by Linux boxes. Including Yorkforce above. They are losing users at an alarming rate. Now i'm not say FIX IT. Because I know it's not officially supported but maybe a glance into what might be cause it.

**Comment by SeanAtr0n** [comment]
Fixed in the next hotfix build, until then you can use this build which is compatible w/ 7.2.5
https://drive.google.com/file/d/1qFYGvphK0IMnttqdA7n_t7Aka4OVGXkf/view?usp=sharing
