### ISSUE TITLE
Waypoints stuck on the other other side of the world

### ISSUE THREAD

**Issue by mindforger** [StrangeLoopGames/EcoIssues#5839]
walkeed around the planet multiple times and the markers did not refresh, i needed to walk the way back until they reset

sometimes they return when i am alsmot under the marker position

it seems there is something very location specific on when the markers ar updating

**Comment by MarjieAVolk** [comment]
Duplicate of https://github.com/StrangeLoopGames/EcoIssues/issues/5481

Looks like that was marked as fixed today, so should be fixed in the next release.  (For now, to help you play - they are confused by the '0' border.  They will show you the fastest route that does not cross '0' in either direction)

**Comment by mindforger** [comment]
haha :) classic
