### ISSUE TITLE
USER ISSUE: placed blocks do not appear

### ISSUE THREAD

**Issue by pmeyerson** [StrangeLoopGames/EcoIssues#5906]
**Version:** 0.7.2.3 beta

**Steps to Reproduce:**
1. This seems to only occur in specific areas of my map.
2. Occurs every time I try to place a hewn wood block in a specific area - the number of blocks I'm carrying decreases but nothing shows up.  It does not appear if I quit the server and rejoin up (I'm running local)

**Expected behavior:**
Blocks should appear if carry count decrements

**Actual behavior:**
Blocks do not appear.  But I have less in my inventory.

Notes:
It does not seem to matter what shape hewn logs I try to place.  The land I am on says it is authorized for my use.  This is on the roof of my home where I am trying to expand my 2nd floor - some of the spaces I am trying to build on are right next to an existing room that I was able to build just fine.  All tiles I am trying to build on have wood blocks (as a roof) below them.

**Comment by MarjieAVolk** [comment]
Are you allowed to place another block in the same place when this happens?

**Comment by pmeyerson** [comment]
Yes I can place multiple blocks in the same spot when this occurs

**Comment by Bl4ckthunder** [comment]
Hi,
had the same Bug today.
Was Building a 2nd Floor, and then I could place all my hew logs in the same spot and they didnt appear.
If i removed that invisible block i got all hew logs back.
So i thought something "did i reach a building hight limit? And walked to a Hill to test it, same thing happened there.
**Something intreresting**:
Going back to my House, the invisible Logs just appeared. Then looking to the Hill, they appeared too.
Tested it, since bug still was happening. 
Everytime i just walked away and they appeared.
Dont know why, but it just fixes itself some minutes later and i could build fine without the bug.

Hope this info helps you :)
