### ISSUE TITLE
Oak Tree Saplings Spawning Unstopable

### ISSUE THREAD

**Issue by DiploBlock** [StrangeLoopGames/EcoIssues#5930]
Just throwing this into the ether here as i'm not even sure these bug reports get read anymore because the devs are so busy. 

Anyway, something is wrong with oak spawning. In this screenshot I had cut down all the oak saplings near my base at 6:51pm
![eco 3_11_2018 6_51_44 pm](https://user-images.githubusercontent.com/13935476/37259704-29cb7184-2560-11e8-832d-c4d6c6227a29.png)

Then I took another screen shot at 7:00pm.
![eco 3_11_2018 7_00_27 pm](https://user-images.githubusercontent.com/13935476/37259712-4dc3ddd8-2560-11e8-9cca-d9dc91a048b5.png)
As you can see, THEY JUST KEEP COMING BACK. 
I have chopped them all down about 15 times now and they will not stop respawning. It doesn't matter what I try but they ALWAYS come back. Sometimes it's as soon as while I am still chopping. Other times it takes 30 minutes or an hour. But they can't be stopped. It almost seems like they are even spreading. If you need any more info please just ask.

**Comment by spool1** [comment]
Isn't this an intended feature? Tree's regrow into saplings if your chop the stumps up? I feel like if you dig up the dirt where they were and replace the dirt it may remove the spawn location for the sapling.

**Comment by DiploBlock** [comment]
I have tried that. I have tried tilling the dirt, doesn't help. I have gone so far as to put hewn log blocks in the spots where they commonly spawn, they pop up in the block adjacent to the wood. I am at my wits end with these unkillable saplings.

**Comment by Thyriel** [comment]
>  Isn't this an intended feature? Tree's regrow into saplings if your chop the stumps up?

Would be good to know if its intended or not. Until i saw this here i thought they only insta regrowth (it's all tree types btw) because i reduced CanopySpace to 4/5 on my server. If it is a feature there's not much sense in collecting saplings now.
And it did not used to work like that in 7.1

**Comment by DiploBlock** [comment]
Yeah I have completely stopped collecting or using acorns. The saplings respawn so frequently that it is almost impossible to get a mature oak to grow. They pop in severely overcrowded and even if i remove all the grass blocks around and the other saplings, they still do not grow because how quickly the other saplings and grass spawn back in. I have also found that some of them never disappear from the minimap even if they are cut down or dug up in world. It's like they are inherently there. Would really love to get a response about this.

**Comment by MarjieAVolk** [comment]
We look at every bug that is reported on Github :)  Sometimes we are a few days behind, especially right after the weekend.

Stumps are not supposed to regrow into saplings.  And saplings shouldn't be spawning that fast, so that is a bug.  As to the other particulars of how tree spawning works, I am going to ask someone else, as I'm not the expert on that.

**Comment by craig-jong** [comment]
As of right now, plants that already exist in your world are very difficult to truly drive to extinction unless the environment in-which they live in no longer exists. Due to the way world layers has changed, even removing all existing trees will only drop the layer value to a value approaching zero.

This means that trees will regrow, even if you kill all of them. The rate at which they do so is definitely too fast, plus this whole thing needs to be adjusted such that plants with no possible way of reproducing should not continue to respawn in such location.

Stumps have nothing DIRECTLY to do with trees regrowing (or at least they shouldn't - AFAIK dead plants do not affect the population counts), but removing them will increase the amount of fertile ground and, thus, the potential for new trees to spawn.

I'm going to leave this bug open, but this is more of a problem with balance than anything else.

**Comment by Kastuk** [comment]
Got the same after planting of few acorns in rich yield zone and wait a tick.
Thay replant themselves in such young age. Shameless!
Also they got some deformed branches.
![20180907165744_1](https://user-images.githubusercontent.com/36314945/45225541-740b5000-b2c5-11e8-85a6-6646e82bedce.jpg)

And I got the kicking out with such message:
[eco shameless oaks disconnect.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2361477/eco.shameless.oaks.disconnect.txt)

**Comment by WeaselDog** [comment]
Oak have different spread settings than all other trees which is source of this bug

**Comment by beastyn** [comment]
don't see changes

**Comment by Sekor2600** [comment]
Now something should have changed. have adapted the csv again.

**Comment by WeaselDog** [comment]
Looks fixed to me. I tested with both planting and harvesting.
