### ISSUE TITLE
Districts Difficult To Create

### ISSUE THREAD

**Issue by PerksPrisoner** [StrangeLoopGames/EcoIssues#5985]
Talking to the trusted aid in Discord about the issue with being able to create districts she mentioned that the ideal browser is chrome however I can not find a place to log in, even though all actions demand it. Looking for a solution. Photo Enclosed
![capture](https://user-images.githubusercontent.com/22648457/37323544-bc040e9e-2641-11e8-847c-13cdc5b7e3d4.PNG)

**Comment by MarjieAVolk** [comment]
You are supposed to be logged in automatically when you click the button from in game to visit the page.  If it isn't working, I would say your best bet is to close the page and go back in game to click the button again.  Right now you do actually have to be running the game in order to use the page, which is an issue we hope to address soon (https://github.com/StrangeLoopGames/EcoIssues/issues/4104)

Let me know if that helps you.

**Comment by PerksPrisoner** [comment]
The problem is on Chrome I am not able to find anywhere to log in, the districts drawing seems incompatible with Firefox and Microsoft Edge (What isn't). The default browser is MicroEdge so I can not use the functionality of the the districts.

**Comment by MarjieAVolk** [comment]
Yeah, you don't log in in the browser at all.  You log in by following the link from in game, which automatically passes your login info from the game to the web page.

**Comment by PerksPrisoner** [comment]
That would be great if it didn't default to Microsoft Edge. Which doesn't like the web interfact at all. Managed a work around where I stole the token from ME before it sent the info and dumped it into Chrome but otherwise it would of been a loss.

**Comment by MarjieAVolk** [comment]
Huh, it should open the page in your default browser.  For me it opens in Chrome.  You might just need to set your default browser on your computer.  We are just using Unity's utility to open the web page, so it shouldn't have any preference for Microsoft Edge haha
