### ISSUE TITLE
Law Names not Re-usable

### ISSUE THREAD

**Issue by Toby-DeWitt** [StrangeLoopGames/EcoIssues#5989]
Once you used a Name for a law, it cannot be used again after you deleted the one with the same name

Example:
If yout delete the Law "Citizenship" you cannot create it again with the same name
If you try, you only get "an error has occured."

**Comment by MarjieAVolk** [comment]
Related to https://github.com/StrangeLoopGames/EcoIssues/issues/4094 (for the error has occurred thing - should show an informative message)

Failed an deleted laws are currently saved on the server, in order to preserve history.  We have some features that display law history; although I believe they are being deprecated, our intention is to continue supporting better history/news feed type things.

Possibly we should have a failed/deleted laws section on the web page.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#205
