### ISSUE TITLE
Tailings do not fall or pollute

### ISSUE THREAD

**Issue by noblackthunder** [StrangeLoopGames/EcoIssues#6]
http://54.218.22.86:4567/topic/366/bug-tailings-do-not-fall-or-pollute

**Comment by metrotyranno** [comment]
Just a thought, when moving the tailings ive noticed you can stack it on each other like normal blocks, it should taper off like it does when originally generated or people will just make small pits and stack the tailings ontop of each other with no consequence

Something else to add to this.. I built my refinery underground 1 or 2 blocks from the max depth. I cleared out a space behind the refinery for the tailings but they appeared on the surface instead of underground next to the refinery.

**Comment by metachronism** [comment]
will address in alpha 5 with ecosystem updates
