### ISSUE TITLE
USER ISSUE: Store Things with rightclick while carrying items

### ISSUE THREAD

**Issue by SeppDE** [StrangeLoopGames/EcoIssues#6004]
Version: 0.7.2.4 beta

Steps to Reproduce:
Try to store items (hotbar) with right click (while looking to the chest) into an chest while holding blocks in the Carrying-Slot will not work till you place/store the blocks you hold in the Carrying-Slot

Expected behavior:
Storing items (hotbar) with an right click directly (while looking to the chest) without clear the Carrying-Slot first

Actual behavior:
You have to clear the Carrying-Slot first before you can put items inside an chest
(Was working in 0.7.2.3 beta, got confirmed as I asked an other player who is still there on Discord)

**Comment by MarjieAVolk** [comment]
I'm actually going to close this as expected behavior.  Either carrying or toolbar had to canonically be first, and we chose to go with carrying being first.  I think this makes sense in a lot of situations - For example, you are often carrying a tool and some building material, and you are a lot more likely to want to put the building material in the chest than the tool.
