### ISSUE TITLE
USER ISSUE: Skill-Bug

### ISSUE THREAD

**Issue by 109117ca** [StrangeLoopGames/EcoIssues#6277]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
1. Get Enough Ressources to research some Skill.
2. Wait...
3. Learn Skill
4. If u have more than 5 Active Skill Points you cant set any Skillpoint. You need to restart your game	

**Expected behavior:**
Can use my new Skill instant.

**Actual behavior:**
Need to Restart my local game.

**Comment by MarjieAVolk** [comment]
Was trying to get this to happen today, no dice.  Dropping priority since there are no other reports.

So, could you give me some more details?  When you say you can't set any skillpoints - are you talking about taking a specialty, or a skill within a specialty?  Is the button to add the skill visible and enabled?  Do you see an error message in chat?  Also, how often have you seen this happen?  Only once?  Consistently or randomly?

The next time you see this happen, could you send me your log file? "C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt"

**Comment by beastyn** [comment]
Can't repro
