### ISSUE TITLE
USER ISSUE: Multiple bugs

### ISSUE THREAD

**Issue by DubsTheFox** [StrangeLoopGames/EcoIssues#6313]
**Version:** 0.7.2.5 beta

Here are some bugs I have found. Most of them are with ramps.

1.: Sometimes if you mine a block the block behind it has no texture.
![blocks without texture](https://user-images.githubusercontent.com/37247290/37669407-0b599b00-2c67-11e8-892c-f43d742683cf.gif)
2.: You cant place Blocks on ramps. I right clicked all the time in the gif.
![cant place blocks on ramps 2](https://user-images.githubusercontent.com/37247290/37669893-38076d0c-2c68-11e8-901f-58dbb1f33d94.gif)
3.: Carts are twitching sometimes if you walk over ramps with them.
![cart twitching on ramps](https://user-images.githubusercontent.com/37247290/37669853-1e2b9098-2c68-11e8-9c15-483fc17997a6.gif)
4.: you cant mine a block if a ramp is in front of it.
![dig threw ramp](https://user-images.githubusercontent.com/37247290/37670165-f2ee99ec-2c68-11e8-9b42-b6a94905b4cd.gif)
5.: sometimes you get kicked away with the cart.
![trololololol](https://user-images.githubusercontent.com/37247290/37670503-c5f7244e-2c69-11e8-8671-bb3d11f8a25e.gif)

I have to admit, I kinda provoked it in this one:
![slingshot cart](https://user-images.githubusercontent.com/37247290/37670591-f9341dc6-2c69-11e8-9341-672013121ff5.gif)

6.: sometimes you get teleported about one block upwards if you stand on a ramp and mine something.
![teleport on ramps when mining](https://user-images.githubusercontent.com/37247290/37670698-404b466c-2c6a-11e8-9de9-259c08a5ea6c.gif)

7.: the command /spawnplant doesn't work. And it doesn't show an error message, so the command should be valid.
![spawnplant doesn't work](https://user-images.githubusercontent.com/37247290/37670826-96a51272-2c6a-11e8-9bd5-2eafd7e80216.gif)
I've tried it with multiple plants and it doesn't work with any of them.

8.: Sometimes the world generation doesn't spawn every plant, that is one of the biggest issues we had.

9.: Stones are looking threw ramps.
![screenshot_1](https://user-images.githubusercontent.com/37247290/37671485-1ad34fa4-2c6c-11e8-8668-a3c3829c1a27.png)

I hope it was helpful.

**Comment by MarjieAVolk** [comment]
Thanks for all the details and gifs.

1. Same as https://github.com/StrangeLoopGames/EcoIssues/issues/3897
2. We are going to redo ramps soon to make them be blocks, which should address these issues
**3. Might be related to (9.) - @SeanAtr0n ?**
4. Filed a new bug: https://github.com/StrangeLoopGames/EcoIssues/issues/6318
5. Filed a new bug: https://github.com/StrangeLoopGames/EcoIssues/issues/6316
6. Filed a new bug: https://github.com/StrangeLoopGames/EcoIssues/issues/6317
7. Looks like this is because the command is case sensitive.  You have to enter 'Corn'.  I will fix this for 7.3, and give better messages.
8. Same as https://github.com/StrangeLoopGames/EcoIssues/issues/5568
9. Same as https://github.com/StrangeLoopGames/EcoIssues/issues/2033 - That was marked as fixed, but looks like there are still some issues, so we're double checking that.
