### ISSUE TITLE
Iteration of server browser really necessary

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#6366]
Hi,

now that your game gains quite some traction, especially with the steam release, I think it is about time to re-consider your very basic server browser GUI and functionality. It might be suited for basic connectivity but with hundreds of servers being in there, it no longer is up to the task. It needs a re-design / rehaul to be up to date to scale to the needs of that magnitude.

Some suggestions I would consider:

1. Seperate GUI update loop from network activity. GUI functionality must not lag when refreshing the array in the background.

2. Decrease font size and the box area showing a server entry. Having the luxury of using so much space for a single entry is no longer a valid path if you want a server browser that is readable. You need more entries on the screen per page to reduce scrolling in that immense list. Best would be to have one row per entry, <NAME> <PING> <PLAYER/MAXPLAYER> <UPTIME> etc.
Look at how many entries a good solid browser shows on one screen, and how small the font (yet clear) it is to achieve this goal:
http://i.imgur.com/nE4nbwi.jpg

3. Sorting options by ping, by player amount, by max players, by uptime, by name, etc. (and reverse sorting aka standard functionality basically)

4. Filter options: Game options, meteor, skillgain, min/max amount of player, min/max ping, min/max uptime, etc.

5. Save filter option and remember sorting.

6. Refresh all / Quick Refresh .
-Refresh all will fetch a complete new server list
-Quick refresh will only get updates on the currently shown servers on your list (AKA filters applied).

I guess there is more, but that is what I can do out of my head.

Generally speaking, this area needs some love to keep up with the success of the game (and thus amount of servers managed).

Anyway, keep up the good work!

Cheers,

**Comment by MarjieAVolk** [comment]
Hey, thanks for the suggestions.  We agree, and we are already working on a rewrite of this window.  Re your specific points:

1. Unfortunately Unity is single threaded, so this isn't really possible in exactly that way.  But I do hope to use coroutines or some such in order to space out the network traffic to a more manageable pace.

2. We are planning to have less info on each listing, and instead have a detail panel to the side that will show details only for the selected server.  Should help cut down on space a lot.  I will consider how many entries fit on screen as I continue.

3. Agreed, this is planned

4. This is also planned.

5. Yeah that's a good idea, I will look into that

6. I think ideally the 'quick refresh' would happen automatically every few seconds.  But yeah, you are right that both are important

I am also planning on having a separate tab for favorites+lan+friend games vs. all public servers, so that you can open 'Join' and quickly pick from your favorites without having to get out the big guns of the public server list at all.

**Comment by ShaydenMac** [comment]
Via Reddit: 

"[–]Voguhl 
Sadly the new connect Gui has its issues. Had to put my server to public for my friend to find the server and see it as online. Direct connect via favourites always showed it as offline."

**Comment by MarjieAVolk** [comment]
@ShaydenMac moved your report to https://github.com/StrangeLoopGames/EcoIssues/issues/7614

Going to close this one as resolved in 7.4
