### ISSUE TITLE
USER ISSUE: 12

### ISSUE THREAD

**Issue by EvgeniyTremasov** [StrangeLoopGames/EcoIssues#6406]
**Version:** 0.7.1.2 beta

**Steps to Reproduce:**
1

**Expected behavior:**
it

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
The next time you have this problem, if you can send me any log/crash files in '[...]\steamapps\common\Eco Server\Dump' or '[...]\steamapps\common\Eco\Eco_Data\Server\Dump' and also 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO\output_log.txt', I can try to diagnose the problem.

There are also a couple of things you can try as a workaround:

* If the server is still loading, wait until it has finished before trying to join
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If running your own game, when starting a new world, select 'Generate new'
* If running your own game, run the server via the Eco Server tool
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

**Comment by ecoemmeck** [comment]
This is a consistent issue from what I've noticed. However without little to no info from the OP it's not very deal with able

**Comment by MarjieAVolk** [comment]
Yes, this is just our fallback message and can have a lot of reasons.  One of the main ones for local saves is that you still see this message if your local server crashes while starting up.  Once we add better error messages for that, it should be a lot better.  It's likely that we still have some network cases that we could handle better also.  But it's hard to tell the difference between an actual network problem and a bug on our part.  So that's where we're at.
