### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by Voosle** [StrangeLoopGames/EcoIssues#6504]
Programm crashed while starting up (I'm not sure if I clicked on rejoin to the server...)
[error.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1845841/error.zip)

**Comment by MarjieAVolk** [comment]
```
mono.dll caused an Access Violation (0xc0000005) in module mono.dll at 0033:e8a29eeb.
```

This is the main error message - you can google 'mono.dll caused an Access Violation' and see a variety of things built using Unity have seen this error.

Sounds like you could give these things a try:
* Decrease graphics settings in Eco
* Update drivers
* Uninstall GeForce Experience
* Uninstall and reinstall Eco

There are also some steps out on the internet that we could try, although it's hard to guess whether they will help you, since most people aren't seeing this error to my knowledge.

**Comment by MarjieAVolk** [comment]
Gonna close this as can't fix for now.
