### ISSUE TITLE
USER ISSUE: workbench

### ISSUE THREAD

**Issue by dndplayer25yrs** [StrangeLoopGames/EcoIssues#6537]
**Version:** 0.7.2.5 beta

**Steps to Reproduce:**
all

**Expected behavior:**
 place items on workbench with right click

**Actual behavior:**
does not work at all. can not place items on workbench with right click.

**Comment by MarjieAVolk** [comment]
Oh, I thought this was on 7.3.  Since it's on a stable version, and I haven't heard any complaints about this previously -- What are you trying to place into the workbench?  Are you sure that you have a project that requires that item?  And does the project belong to you?  You won't be able to put items into someone else's project with right click (this is a safety measure for public stations).

**Comment by dndplayer25yrs** [comment]
Thank you for the comment but I figured it out. I was able to place the workbench near the supplies and able to link them to the table and then it uses them. Just learning this game.

**Comment by MarjieAVolk** [comment]
Okay.  You should be able to add resources to the workbench with right click, as I said only if you have an active project.  Linking an inventory is a better long-term option, but both should work.  If you think it is working, I will close this.
