### ISSUE TITLE
USER ISSUE: Eating to Full Stomach

### ISSUE THREAD

**Issue by Kharomoth** [StrangeLoopGames/EcoIssues#6590]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
1. Fill stomach
2. Eat something
3. Lose your food

**Expected behavior:**
Not consume food when stomach is full

**Actual behavior:**
Insteawd it weill consume the food, even when stomach is full

**Comment by MarjieAVolk** [comment]
Fixed in next hotfix

**Comment by darkshad9999** [comment]
Ya I was about to report this as well I saw this as well if you have a full stomach the message
saying that you are full is appearing and the food is being removed from your stack of food in your backpack or where ever it is even though your stomach is full and you are not getting any credit 
for this since your stomach is already full.  This just started happening in 0.7.3.0 Beta
