### ISSUE TITLE
USER ISSUE: Clearing Debris uses more calories than chopping a tree

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#6596]
**Version:** 0.7.3.0 beta

When i chop a tree with my Iron axe i use -17 calories But if i chop Debris i use -51 shouldn't this be the same? or maybe less for Debris as it IS smaller than a tree? also it may encourage players to clear up after they chop down trees, because at the moment it is exactly 3 times as many calories clearing debris.

**Comment by MarjieAVolk** [comment]
We intended cleaning up debris to be a bigger job than cutting down the tree, so that it would be something people would struggle with and have to pass laws about, etc.

**Comment by Conchipedia** [comment]
ok, thats fair enough 👍

**Comment by MarjieAVolk** [comment]
It could be argued that it's a bit too high, maybe it should just be x2...

**Comment by Conchipedia** [comment]
i trust your ideas @MarjieAVolk you seem to know what you are doing, who am i to argue with 2x instead of 3x ❤️

**Comment by MarjieAVolk** [comment]
Hahaha thanks

**Comment by Conchipedia** [comment]
its easier to understand things that are in in game if we know the logic behind why they are in place, as i hadn't realised that Debris was made harder to encourage the law thing and to make players struggle a bit 👍

**Comment by Thineboot** [comment]
While the intention to show people the drawbacks of their wrongdoing by leaving behind a complete mess after chopping down a tree many don't either don't know the bad effect or simply don't care as long as there is enough space in the world. Out of sight, out of mind.
Beside the effect for the forest clearing up the debris has no positive effect for most skills. People used to collect deadwood aka wood debris for millennia to fuel their fire places. And while you need more than one big strong lumberjack to deal with a tree kids were able to perform collecting deadwood.
The balancing seems to be off track. Keep in mind that while you know your intentions player, especially those playing alone or with just a few friends may need a long time to realize these hidden intentions. Give them hints along their way even after finishing the tutorial. Keep track of the tutorials a player has fulfilled 'cause when you change and/or add new tasks they simply may never see them in the first place due to clicking away the whole tutorial at once. Don't make them frustrated 'cause that's the least you wanna do based on the whole idea of making Eco.
