### ISSUE TITLE
USER ISSUE: 

### ISSUE THREAD

**Issue by Sutako** [StrangeLoopGames/EcoIssues#6655]
**Version:** 0.7.2.2 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Connection Failed
```

**Comment by MarjieAVolk** [comment]
Well it's hard to say what the problem is without more information, but here are some things you can try:

* If the server is still loading, wait until it has finished before trying to join
* If connecting to another server, try connecting directly by entering the server's IP address in the 'Join' screen
* Try steam's 'verify integrity of game files' button
* Delete the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO
* Temporarily disable your firewall and/or antivirus software
* If running your own game, run the server via the Eco Server tool
* If none of those work, you might try nuking it all - Uninstall Eco, shut down Steam, delete the AppData folder, restart your computer, reinstall the game.

If you have any crash files in '[...]\steamapps\common\Eco\Eco_Data\Server\Dump', sending those to me could help me figure it out.

**Comment by Sutako** [comment]
Я полностью удалял все файлы игры, я не знаю, что именно могло послужить причиной ошибки, возможно то, что я запретил доступ к интернету когда запустил первый раз игру, только я не знаю как снова разрешить доступ.
I completely uninstalled all the game files, I do not know what this may be causing the error, perhaps the fact that I banned Internet access when I ran the game for the first time, only I do not know how to re-enable access.

**Comment by MarjieAVolk** [comment]
Ah, well that seems like a likely candidate.  In what application did you ban internet access?  Windows firewall or something?  I'm not sure I will really be able to help you, you will probably need to search for information about whatever firewall you are using.

**Comment by Sutako** [comment]
Я сделал разрешение доступа в интернет и дал полный доступ, всё равно не работает, пишет (сервер полный)
I made permission to access the Internet and gave full access, still does not work, writes (server full)

**Comment by MarjieAVolk** [comment]
If it says server full, then you need to change your config.  I guess it got messed up somehow.  Here is how:

- Go to 'Browse Local Files' for Eco
- Go to the folder 'Eco_Data\Server\Configs'
- Open the file 'Users.eco' with a text editor
- Look for the setting "MaxSlots"

Normally the setting should be set to -1.  This is supposed to allow any number of users to play.  If it is not set to -1, change it back to -1.

If it is already set to -1, try setting it to the number of people you want to allow on the server.  For example, if you want to play with a couple of friends, maybe set it to 5 or 10.

**Comment by Sutako** [comment]
Если кратко, вы говорите, сделать мир не с 1-3, а с 3-10
If briefly, you say, make the world not with 1-3, but with 3-10

**Comment by Sutako** [comment]
Спасибо за помощь, число (-1) помогло
Thanks for the help, the number (-1) helped

**Comment by MarjieAVolk** [comment]
You're saying, after you set it to -1, it was set to 1 again later?  Did you open another save game?  Maybe you have this problem: https://github.com/StrangeLoopGames/EcoIssues/issues/3768

**Comment by Sutako** [comment]
Да, спасибо
Yes, thank you

**Comment by MarjieAVolk** [comment]
Okay, glad you have got it figured out.  Sorry about the settings overwriting issue, hopefully we will get around to fixing that soon.
