### ISSUE TITLE
USER ISSUE: Server not in list

### ISSUE THREAD

**Issue by werkrat** [StrangeLoopGames/EcoIssues#6676]
**Version:** 0.7.3.0 beta

**Steps to Reproduce:**
Everything is set up correctly, and it's been a couple weeks now. I can only connect if I directly add my server, it isn't in the server list.

**Comment by MarjieAVolk** [comment]
Oh alright.  Well yeah, it is not listed in our server listing thing.  So the problem is somewhere before that in the food chain.  Since you say direct ip connections work, and the server is also set to public... I guess it's a problem in the server listing thing maybe probably

**Comment by metachronism** [comment]
check here: https://ecoauth.strangeloopgames.com/game/serverlist
if you IP/port shows up in that list after setting your server to public, then you are good.

Showing in-game is something that can take a while, due to how many servers we have now - its best to add it manually, but we have lots of changes coming to the server browser to make this less annoying in the future
