### ISSUE TITLE
Wall Blocks do not connect to floor blocks and 'Glass' item may need more forms.

### ISSUE THREAD

**Issue by AcidDotCom** [StrangeLoopGames/EcoIssues#6695]
Glass can only face one way now. Cannot be rotated. Picture attached.

[http://steamcommunity.com/sharedfiles/filedetails/?id=1345976682](url)

**Comment by MarjieAVolk** [comment]
I wasn't able to access your picture.  Is your problem that you can't make a glass ceiling (eg. https://github.com/StrangeLoopGames/EcoIssues/issues/6670)?

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/38115405-cb5dd5ce-3360-11e8-8246-14f03f393e0c.png)
reupping here.

And fix yo tools! D:

**Comment by craig-jong** [comment]
Okay, so it turns out "wall blocks" can't connect to "floor blocks".

Your walls are currently made out of HewnLogFloorBlock - you can use shift + mousewheel up/down to change block forms when placing items with the hammer.

Unfortunately there isn't any easy fix to making walls connect to floors in the way this screenshot shows. We're definitely working on builders as a constant thing, so hopefully at some point it will be possible.

**Comment by keegan-o** [comment]
Duplicate
