### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by dimensionwizard** [StrangeLoopGames/EcoIssues#6712]
The other day the game updated to 4.3 then downgraded to 4.2.5 again in a short span... I didn't notice anything unusual afterwards, but on restarting my server for 4.3 getting released again, I noticed the world won't start anymore. Same for the 4.2.5 server application when loading from any of my rolling backups...

World file is too big to attach to github, so I'm posting google drive links:

https://drive.google.com/open?id=1wsA3JWQLL3wRvVuWMkOQLgOpTUM-hzac

Also a crash dump:
[Crash AggregateException 03292521.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1862414/Crash.AggregateException.03292521.zip)

I noticed after the downgrade before that the doors had fallen off of all the structures in the world... not sure if that's related, and I did replace the ones on one of the structures.

**Comment by MarjieAVolk** [comment]
Yeah, downgrading versions is not usually supported.  But since you sent the save file, I was able to doctor it.  As you mentioned, there was something wrong with the doors.  I deleted all the doors from the save, and now it is working again.  You may want to cheat yourself some doors though :P

https://drive.google.com/file/d/1cOuymL_34dIDmao3KAQuu2tZn9_6Wr7k/view?usp=sharing
