### ISSUE TITLE
Suggestion: All items will break

### ISSUE THREAD

**Issue by skeykc** [StrangeLoopGames/EcoIssues#6724]
Eco has a resource, economy, and environmental management and it is very interesting.
However, I feel unsatisfactory to the economy.
Items other than meals will be no longer necessary if the required number is available.
Beyond a certain line, tools, furniture, clothing, crafting tables will be out of demand.
Resources are not consumed either.
Certain production vocational skills ultimately have no meaning.

So, I propose an option to break all items.

For example
- The durability of the crafting table decreases according to the use time, and production efficiency deteriorates
- Likewise, the durability decreases according to installation time, and the value of the housing bonus decreases
- The durability of clothes decreases according to calorie consumption, and the buffing effect decreases

Options for broken and disappearing and options that can not be repaired.
It would be nice if you could switch between these settings.

**Comment by neyna** [comment]
On my server almost all people agree that all items should be durability to help the economy to work. Because when all people bought their stuff (furniture, clothes, carts, etc) some people sell no more and have no more interest to play. If we want to keep all professions interesting for long game they need to be able to have costumers all game long. 
To do so, item with durability could either : 
- break at 0 dura
- be repaired by people with the required skill to craft it

So i agree with skeykc but i disagree on the point to make house value depend on durability because house is already very complicated as it is right now, most people dont understand how to works in details.

**Comment by skeykc** [comment]
Thank you for agreeing.
I am using Google translation because English is not good.
A word dropped out of the result translation, I'm sorry.

The second item is about furniture, not house.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#169
