### ISSUE TITLE
Player cant open 7.2 save game in 7.3

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6768]
https://drive.google.com/drive/u/1/folders/13B5CWT2BwxvcX2385YqyQPPJbgM6XNCS
bernas.eco/db

"I'm having problems opening my save that I created in update 7.2. in the Eco for steam and I have always played in it having arrived at the 6 days of game in this world but yesterday 29/03/2018 was released the update 7.3. from Eco to Steam and updated the game. After the game has updated I opened the game I wanted to play in my old save and it tries to open it but then when trying to open it gives the error of connection failed. Can you help me please I have a lot of game time in this save and would like to continue playing the same."

**Comment by MarjieAVolk** [comment]
It's a corrupted zip file.  I think that means there was a failure during save process earlier?

They will need to restore a backup to keep playing.

**Comment by johnkslg** [comment]
Nasty, for the fix we should make the game auto-detect this and communicate it to the user, and load the most recent backup.

And, of course, not corrupt on save.

**Comment by MarjieAVolk** [comment]
We should probably have a way of loading backups in game I suppose.  In the Load screen.

**Comment by GophTheGreat** [comment]
Got one from the support queue. I don't actually think it's the same error that John's user reported but this already has a fitting title, so: 

"What an amazing game, I love it!

BUT while loading my world with Eco server 0.7.3 the following error message appears after „loading plants 100%“:

 
Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Exception: Error(s) occurred when loading Plants
   bei Eco.Core.Serialization.DataStore.LoadAsync[T](String folder, Action`2 createFunc)
   bei Eco.Simulation.PlantSim..ctor()
   bei Eco.Simulation.EcoSim.Initialize()
   bei Eco.Simulation.EcoSim..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---

   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)

   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   bei Eco.Server.PluginManager.<.ctor>b__10_3()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---

   bei System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Eco.Server.PluginManager..ctor()
   bei Eco.Server.Startup.Start(String[] args)
   bei Eco.Server.MainClass.Main(String[] args)

The interesting thing: this file was an backup file that was created automatic by the server itself. This file is broken and 7-Zip also says that there are CRC-Errors in the ECO-File.

After all by backups after the 7.3.0 world-convert are broken.

Is there any chance to get the file working or to repair that backup file, because there are a few “working” hours in it?

---

(continued from a second email):

it seems to be a problem at a species type definition in Eco.

I debuged the server application for more information in Visual Studio, please see attached file no. 1.

I also attached the eco dump file (see no. 2) and here you can download the world-files in zip-archive:
https://www.amazon.de/clouddrive/share/D8FOEg3voC766j9B05VswNIiWZAy2i4V59eIi7p8AGz


![eco_debug](https://user-images.githubusercontent.com/13459026/38188490-ebced332-35f7-11e8-918c-35613f54aa18.png)

https://pastebin.com/Z5ugKDnx

**Comment by MarjieAVolk** [comment]
@GophTheGreat that exception is unrelated to the original bug.  I filed this one for it: https://github.com/StrangeLoopGames/EcoIssues/issues/6898

**Comment by metachronism** [comment]
backups won't really solve this issue as they are only taken every 4 hours
