### ISSUE TITLE
Username "Name<text>" has a variety of errors.

### ISSUE THREAD

**Issue by vintrove** [StrangeLoopGames/EcoIssues#6778]
https://cdn.discordapp.com/attachments/179459805046505472/429416685955448843/unknown.png
Example of one error.

Because they have a NAME<text> nickname, they are unable to:
- Talk in chat.
- Display activity.
- Vote on anything.
- Be voted for on anything.

Changing their nickname on steam and the eco site doesn't update on the server.
They simply can't participate socially at all.
The only solution we can come up with is to delete the server side character and have him join again with a new functioning name.

**Comment by MarjieAVolk** [comment]
Yeah, the '<' and '>' characters break a lot of things that use xml.  I have actually committed a fix for this, but I didn't put it onto the hotfix branch, so it will come out with the next major release.  The fix will just be to replace '<' and '>' with '?' when logging in for the first time.  (I would have preferred to escape them so that we could support these characters in game, but it seems that the various third party tools we use have different character escaping requirements, which made that very difficult)

Sorry for your troubles!
