### ISSUE TITLE
USER ISSUE: tabbing out of the game/mouse getting picking up

### ISSUE THREAD

**Issue by TobiasZeskaNielsen** [StrangeLoopGames/EcoIssues#6807]
When I tab out of the game, the mouse still moves the game, as does the scrollwheel.

I play with the game windowed.

**Comment by mrtitusr** [comment]
When Eco is running in windowed mode, Eco accepts mouse input from other windows that on top. The only input that is accepted and tracked is mouse location, and scrolling, if mouse is over a location that allows scrolling as an input.

Eco will 'Grab' the mouse and force it into the center of the play window, regardless of onscreen location, and not let go until you Alt-Tab into Eco so that you can inform it that you don't want to provide any actual input yet.
To Replicate this, Have any other program window on top of your Eco window while logging in. once Eco finishes loading and your game starts, that is when the mouse cursor is grabbed.

All tests performed in Windowed mode by reverting from full screen using Alt-Enter, and Windows+Up Arrow to maximize. I have not tested this in Forced left, right, or any variant of these.

**Comment by SeanAtr0n** [comment]
fixed
