### ISSUE TITLE
Game is now actually unplayable.

### ISSUE THREAD

**Issue by GnomeLoli** [StrangeLoopGames/EcoIssues#6828]
I was playing yesterday night on a private server with friends and after a while we decided to call it a night.
Next morning I wanted to go check on my craftings before going to work but I couldn't connect back to the server. In fact, I couldn't even connect to any server nor create a singleplayer world.
Everytime after trying to connect it would just tell me "Connection failed".

I've tried everything in the book given to me to fix this issue (deleting *everything* and reinstalling, changing lines in the files), even with the help of a moderator and the lead moderator of the discord without any fix. They told me I would have to make a bug report for it so here we are.

We are on 7.2.4, everyone else in my group can join the server no problem while I'm no longer able to. Not only that but nothing changed between the time I was on yesterday and now (no server reset / computer reset, at least until we tried fixing the issue)

We tried updating the server to 3.1 but it still doesn't work for me.

Please help, we were having a blast with the game until it became unplayable

**Comment by darkshad9999** [comment]
Sounds more like a connection issue with the server and more of a server issue than a game issue. Once again this is why Strange Loop Games needs to setup and run servers instead of letting individual people that have no clue how to properly administer a server actually run the server.  Did the server crash if so then maybe there is an issue but you need to post some more stuff from the server logs.

The devs need more info to go on than this.  If there is something that crashed the server then 
you need to post the logs for it. The developers are not miricle workers and can't troubleshoot 
and fix the issue with no logs.

again if I was a developer at strange loop games I would just close off this ticket due to lack of 
information.  Man people really need to learn how to do proper bug reports.

**Comment by Dreepa** [comment]
I thought this isn't a discussion board darkshad. Violating your teachings again?
Did it occur to you, that not everyone was born a tech guy, and some are just playing games? Then being asked to come here and get support for a problem they have? 
How is he supposed to know how a "proper bug report" works. He even was explicitly told by the lead moderator to come here and post. 
To say it in your words:
"Man, people really need to learn how to deal with other human beings..."

**Comment by darkshad9999** [comment]
Dreepa go away I was answering  this.  Again Dreepa if you are going to troll me in every thread then I will ask that you be removed from here. I will not put up with your garbage.  People on here that are beta testing this game shouldn't be because they are not giving the developers enough information to actually troubleshoot the problem. 

Once again folks if you are going to submit a bug ticket at least give the developers enough information to be able to have them troubleshoot the issue.  The ticket that this person GnomeLoli did 
is useless.  It gives you no screenshot of the error. It doesn't even tell you what the exact error message
was. 

This is Beta if you are just going to "play" then don't open up half ass tickets and I would recommend
that you come back later once the game is out of Beta. Right now this is being beta tested if
you can't take the time to do proper tickets then come back when this game is fully done!

**Comment by MarjieAVolk** [comment]
Hey guys, please keep it civil in here.

**Comment by darkshad9999** [comment]
I am sick of being stalked by Dreepa and him trolling me in every thread.. Also Dreepa go look up Asperger's Syndrome before you tell me that I need to learn how to deal with other human beings. 

I have a hard enough time dealing with people I don't need your crap. 

https://psychcentral.com/disorders/aspergers-disorder-symptoms/

And for MarjieAVolk I am trying to keep it civil in here for this troll continues to follow
me from thread to thread. 

All i am saying in my responses is that people should be giving the developers enough information to be able to troubleshoot and figure out the problem which a lot of them are not doing.

I have worked in the computer field I know what this is like when you get a ticket from
some one like this which vritually no information at all. The developers are not mind readers
or god and need a proper ticket to be submitted in order to troubleshoot and fix the 
problem.

**Comment by GnomeLoli** [comment]
darkshad99999 
I would have given more information if I had any, but that's all there was to it with the problem itself.

I was able to fix the game by changing the game location to my external drive, I was still unable to join my friend's server despite being able to join other's, but we moved to Hamachi and somehow it worked just fine.
I worked IT for 5 years,  I know it's sometimes best to get all the details from problem like these but at the same time I didn't really expect a response to begin with since I'm on an outdated version.

I also pointed out I talked to two support guys from the discord itself and didn't get much help, so that's another reason I didn't put much my specs / what I ate for breakfast on here.

**Comment by GnomeLoli** [comment]
"If you worked IT for 5 years then you should know what a good bug report looks like then"
I don't think you understand what IT is. The reason I said that is because I know I should have put a more descriptive report if I truly believed that it was the game being broken more than my side being screwed up.
I know you probably love acting all smartass-y, but sometimes you should take a step back. The tech guys told me to paste my message here, the same one that I sent them. If anything this was a question for other users and if they had a fix for the same if not similar issue to mine.  Like I told you just before, I didn't put much more thought into it because it's an outdated problem and it seemed like it was just my computer suddenly acting up with that specific game only.

You're practically repeating what I've been saying since the start,  just making it sound more douchy.
Dreepa isn't wrong about you.

Anyway, have a good life and hopefully you will listen to what I said about taking it a notch down, BTW working IT for 5 years means great patience and understanding for people who know way less than yourself. That too could do you some good.

**Comment by darkshad9999** [comment]
GnomeLoli I am sick of you and your attitude.  You said "worked in IT" there may be a reason why you are not working in it currently because you really stink at it. I doubt you are telling the truth anyways about working in IT for 5 years because no one that worked in IT would ever do a ticket like that.  The only one that is a douche bag here is you GnomeLoli you are ignored ... I am sick of these aholes on here like you.  You are the weakest link GnomeLoli, Goodbye!

**Comment by Dreepa** [comment]
darkshad you are constantly on a high ground, lecturing people, discussing stuff, bloating up threads, while at the same time criticize others for the same thing. I am not stalking you. You are responding to my tickets, as I am commenting on some you are in. 
Here I say it: I think you are super toxic,unbearable and your attitude is intolerable. Humble and civilized interaction doesn't work with people like you. If you challenge people, you cannot expect them to just bow down to you as their master and be treated like 5y olds. Learn to show some respect for other users, seriously.

**Comment by MarjieAVolk** [comment]
Okay guys, this fight needs to stop.  Please do not attack people who are filing bugs.  You are preventing @GnomeLoli from getting help.  I haven't kept track of the complete play by play of this argument, I don't want to play parent here, but these personal attacks on someone who is just filing a normal bug are not okay.  We can ask for more information from filers as we need it.

@GnomeLoli I'm sorry that there is so much drama on your bug report.  If you would like some help on a private thread instead, you can message me on Discord (I am just Marjie there).
