### ISSUE TITLE
USER ISSUE: Where is the living room?

### ISSUE THREAD

**Issue by neuromantiker** [StrangeLoopGames/EcoIssues#6860]
**Version:** 0.7.3.1 beta

**Steps to Reproduce:**
The little table doesn't start the living room anymore.

**Expected behavior:**
Rezzing the small table should bring usa the living room.

**Actual behavior:**
It's still a general room.

**Comment by Thineboot** [comment]
That's because for unknown reasons [Path]\Eco\Eco_Data\Server\Mods\AutoGen\WorldObject\SmallTable.cs line 74 has been changed from
                                                    Category = "LivingRoom",
to
                                                    Category = "General",

Therefore a small table acts like any other general furniture.

**Comment by MarjieAVolk** [comment]
The Living Room type has been removed.  The reasoning for this was mostly that a lot of Living Room items really could go in a number of different rooms; for example you could have a little table in your bedroom now.  So hopefully it should be more flexible.

**Comment by Thineboot** [comment]
Ok, let's say that's what you were told. In that case this
![ecolivingroom](https://user-images.githubusercontent.com/4364842/38220502-c530dc64-36da-11e8-8293-816fd950abf4.png)
proves that there is a bug. Because I did what I wrote before and this is what 0.7.3.1 shows. And there is a *Living Room* calculated which is added to the Housing Value.

Your explanation makes sense and if they really remove the *Living Room* from code that's ok. But it is still calculated just by changing one word to it's former value.
