### ISSUE TITLE
Trees/grass can grow on full stockpiles

### ISSUE THREAD

**Issue by cjAnteka** [StrangeLoopGames/EcoIssues#6902]
Should probably stop this from happening.

**Comment by MarjieAVolk** [comment]
Same as https://github.com/StrangeLoopGames/EcoIssues/issues/2733 - meta doesn't seem to want to fix it though, so if you are going to then I'll close that one :P

**Comment by ShaydenMac** [comment]
[https://clips.twitch.tv/ConfidentDirtyDragonMrDestructoid](url)

**Comment by elfl0rd** [comment]
@D3nnis3n can you select one issue from duplicates? this newest, but contain more information...

**Comment by Florian7843** [comment]
Dear Gods of SLG,

I hereby ask you to please fix this, because it's annoying like hell. It even seems to be a quite easy fix, because you already are able to tell whether a block is inside a stockpile, as the players get an error message when trying to pick up a block from a stockpile.

I'd even be willing to do this myself if I didn't have to pay for developer tier to get access to src...

**Comment by WeaselDog** [comment]
Thank you for reporting this bug! I can confirm this has been fixed in the upcoming 9.6 update
