### ISSUE TITLE
Freezing, lag when opening Storage tabs

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#6903]
From Discord player: Gabeux#1309

"Basically the more storage containers you have, when you open the Storage tab in a crafting table the game can freeze for a long while. Even without that, going into a multiplayer server and opening a Workbench makes the game freeze for a few seconds (I have an average of 150ms ping, not sure if that could cause it. But lower ping players complain as well)
The same thing happens with the Economy Window. The more trades available, the worse the freeze gets

I'm currently playing on this server: https://ecoservers.io/server/584/  due to high pop it can work for testing it out. Unforunately it runs mods so not super reliable for tests/experiments on that front.

But the lag I mention happens on vanilla servers too. It just becomes horrible on modded servers, but still bad on vanilla"

**Comment by Dreepa** [comment]
Yes, this feels not very nice. One thing I noticed is that the click and the sound are torn apart.  (async of haptic when pressing the button and mechanical *CLICK* feedback). This increases the perceived lag factor. I would assume that firing the button-pressed sound in sync with the click would already feel better.

If it is a lot of re-work, maybe visualizing activity to the user might also go a long way to not create the feeling of "this feels wrong". So changing the window immediately with high response time, on click, but fetching the content inside the frame afterwards while showing a progress indicator.

For example:

![image](https://user-images.githubusercontent.com/37662083/38257194-18856030-3760-11e8-82b0-dfcab8a45da6.png)


![image](https://user-images.githubusercontent.com/37662083/38257217-21eca110-3760-11e8-9ebb-298ba5c07264.png)

![image](https://user-images.githubusercontent.com/37662083/38257839-5ee3271e-3761-11e8-9daf-f66febcdbedb.png)

**Comment by gabeux** [comment]
Hi Dreepa! I agree completely. I believe that would be so much better.

I do believe that the Storage type is missing some Quality-of-Life features, like "Expand all", "Collapse all" and "Sort Alphabetically" buttons, and that the Economy Window just have filters by items instead of making players browse through every item and trade available - Economy Window would benefit by your solution since it downloads the whole world data while keeping the game frozen.

This is probably all things for other issues/tickets (and probably already planned), but in 80 game hours those are the only really bad user experience issues in my view.

Thanks all!

**Comment by Biglulux** [comment]
I also experience the issue, and it seems to get worse with a slower internet connection. I myself have a high speed 10 MB/s down connection, but a friend of mine has a slow ~1 MB/s connection. Our computers are similar in power, and yet his loading times for crafting tables and interface windows are far longer than mine.

**Comment by Caledorn** [comment]
On the KatherineOfSky community server we are also experiencing this issue quite severely. I am running my client on an i7-7700K, w/32GB RAM, M.2 PciEx SSD, GeForce 1070 just to exclude hardware issues here. I timed how long it takes for me to open the economy viewer (this is on my GBit network LAN, since the server is run here at my home), and it takes me 15 second from I click Y until the viewer is open and ready to use. The same issue happens with the storage tabs, depending on how many storage containers are within range of whatever container/machine I open.

It also takes several seconds to close the economy viewer. So when I click the X in the upper corner I have to wait for a while until I can do anything.

Note that both after clicking the icon (or Y) to open the Economy Viewer, and the X to close it, the game is 100% non-responsive. I can see no visible difference in CPU/Disk or memory usage (having the task manager open in detailed mode in W10) neither when opening nor closing the Economy Viewer however.

**Comment by ShaydenMac** [comment]
People are not using more than one currency because of the lag that occurs when trying to look at the Economy Viewer. The person that reported is using 7.3.3.

**Comment by ShaydenMac** [comment]
Via KoS Betazed server. 1st file is mods.zip and the second is the game.eco file.

https://drive.google.com/file/d/119m_iD1ce8i143SU7WubmPWudIDv5JG-/view?usp=sharing
https://drive.google.com/file/d/1VO3JPpsTAp0TvA-msfW5_FBLzoGCcGaO/view?usp=sharing

**Comment by Caledorn** [comment]
Note that the above save is not from our current Betazed server (which is the KatherineOfSky Community Server #4), but rather from our Community Server #2 from a few weeks ago. I thought it would be more helpful to include that one, as the time it took to open the Economy Viewer in that server was SUBSTANTIAL.

Thank you so much for your efforts! 😀

**Comment by johnkslg** [comment]
Economy viewer part is fixed!

**Comment by metachronism** [comment]
handing this over to @MarjieAVolk who is working on optimizations in this regard

**Comment by MarjieAVolk** [comment]
Oh yeah, was just improving this

**Comment by MarjieAVolk** [comment]
Fixed in next major release
