### ISSUE TITLE
Beta 7.3.1 - Trees in pot are buggy.

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#6907]
**Steps to reproduce:**
1. Plant a tree in a pot.  
2. Reconnect to the game.

**Current result:**
The tree is gone and when you try to plant a new one there is a error message saying: "Plant already exists there".

**Expected result:**
The tree should remain planted in the pot and should always keep its sapling size.

**Note:**

- Removing the pot doesn't solve the problem. If you place the pot back to its original position, you will not be able to plant a new plant/tree and you will still have the mentioned error message.
- Because it is a tree sapling, putting dirt on top of the pot will not remove the "invisible object".
- The pot was close to a building wall.
![image](https://user-images.githubusercontent.com/7052045/38234429-db4228bc-36eb-11e8-806c-6f69edfb9516.png)

**Comment by fillion07** [comment]
**Update on the issue**

After the server was restarted, I was able to plant in the pots again. This time I plant huckleberry bushes :)

**Comment by craig-jong** [comment]
I'm going to morph this bug into a sort of feature change.

I'd like to change pots to just change their appearance to have a "fake" plant of whatever seed is used on them rather than having an actual simulated plant. This can either be a new UI that takes a seed or simply just take whatever seed is used on it. This also means we can fix some of the floating plant issues since we won't need to respect the whole "plantblock" thing.

Please feel free to ask me anything related to this.
