### ISSUE TITLE
Esc doesn't close deed

### ISSUE THREAD

**Issue by ecoemmeck** [StrangeLoopGames/EcoIssues#6963]
I opened my land deed and tried to exit it with esc button but it wouldn't close

**Comment by MarjieAVolk** [comment]
Yeah, deeds are pinned open like HUD elements.  A bunch of people requested this, because they needed to walk around with the deed open and unclaim things.

Some day I would like to have better controls for unclaiming, so that you don't need to do this, at which time we can unpin the deed UI.  (Another option would be to support manual 'pinning', eg have a little pin icon on each window that will let you keep it open while walking around)

**Comment by MarjieAVolk** [comment]
See also https://github.com/StrangeLoopGames/EcoIssues/issues/3133
