### ISSUE TITLE
Players glitched into the void, couldnt play until server was restarted.

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#6979]
"other players kept losing room integrity, or outright losing parts of their walls each time the server had to be restarted"

Is it possible their coordinates glitched to something not repairable?  Re-logging in should at the worst case fix it, the fact that a restart was required is bad.

Here is the world where it was occurring:
https://drive.google.com/open?id=1ffCwhv8HGHJf5YPvl6o7lIT9SFwAPhuV

Mentioned in follow up to review: http://steamcommunity.com/profiles/76561198014737314/recommended/382310/

**Comment by MarjieAVolk** [comment]
Sounds related to https://github.com/StrangeLoopGames/EcoIssues/issues/6882 and https://github.com/StrangeLoopGames/EcoIssues/issues/6786

**Comment by craig-jong** [comment]
As noted in the issues linked by Marjie above, connection stuff was reworked.

It's not exactly clear what this issue is about exactly, but also the problems relating to blocks not appearing/randomly disappearing should have been solved too. Please who fall through chunks should be placed into appropriate locations, although if a lot of chunks area not spawning it might mean the server is unresponsive - the new connection lost thing should help with that.
