### ISSUE TITLE
Game Reports Incorrect User for "User adds n items to the item project at User's Machine Shop."

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#7016]
**Version:** 0.7.3.2 beta

Three users are involved in this process. I have been given permission to Quotes' store, Quotes' Machine Shop, and Tlkoonzjr's Wood Cart. I parked Tlkoonzjr's Wood Cart between Quotes' objects to aid in transfering heavy copper ingots and it turns out Quotes is the one who gets assigned as the person adding the Copper ingots to the project, but I was the one who did the purchase to "own" the ingredients. Not to mention, I also started the project and linked all the storages.

**Steps to Reproduce:**
Place Tlkoonzjr's Wood Cart within range of Quotes' Machine Shop and Quotes' Store.
At Quotes' Machine Shop, create Copper Wiring Project that needs 30 Copper Ingot 
Attach Tlkoonzjr's Wood Cart to Quotes' Machine Shop's Storage.
Attach Tlkoonzjr's Wood Cart to Quotes' Store's Storage.
Purchase 30 Copper Ingots.

**Expected behavior:**
Chat window shows "Legends0 added 30 Copper Ingots to the Copper Wiring Project at Quotes' Machine Shop. 12m until completion."

**Actual behavior:**
Chat window shows "Quotes added 30 Copper Ingots to the Copper Wiring Project at Quotes's Machine Shop. 12m until completion."
![image](https://user-images.githubusercontent.com/5702579/38400921-956c5876-3920-11e8-8278-e72f2126ed89.png)

Also, I am on the side of the grammar war that argues proper names ending with an s should only have apostrophe at the end when showing possession, the game seems to be against this.

**Comment by MarjieAVolk** [comment]
Detecting who is 'responsible' for adding items is actually pretty complicated, lol.

Okay, so you purchased the copper from the store, it went into the cart, and at the same moment was then taken by the machine shop for the machine shop project.  Yeah, that's a weird one, because in this case I believe the code will detect the store as the 'actor' that is moving the objects, thus why the owner of the store is getting the credit.  Recently, the actor for stores was changed to null/nobody, so in the future I'm guessing it will not show a message at all for this situation.

We need to change up how inventory edit actors work a bit for the store case, since this inventory edit requires the auth permissions of the store owner as well as the customer, and sometimes credit for the move should go to the customer, sometimes to the store owner, depending on whether it's buy or sell, etc.
