### ISSUE TITLE
Cannot grant admin rights on serevr after latest update (steam)

### ISSUE THREAD

**Issue by Mephiztopheles** [StrangeLoopGames/EcoIssues#7034]
in version 0.7.3.2 i cannot grant any user admin rights.
i got complete new configs and added my steam id, my ingame name and an id which i got from a mod on your discord server (zEverdeen).
Restartet Server multiple times and my computer also.
I tried every idea which i had or which zEverdeen had.

**Comment by MarjieAVolk** [comment]
So, when you restart your server, the list of ids that you added is still there, right?

**Comment by MarjieAVolk** [comment]
Okay.  Just to double check, when you say steam id, that is an alphanumeric id, not your steam nickname?

**Comment by Mephiztopheles** [comment]
I tried the custom id, which is used to generate the link to my profile and the numeric steamID and the nickname. Also the username ^^

**Comment by MarjieAVolk** [comment]
Haha, okay well only the numeric steam id should work, or your slg id (I assume this is the one zEverdeen gave you).

While playing the game, can you type in /whoami and show me the output?  The ids returned there are the ones that you should put in the admin list.

**Comment by Mephiztopheles** [comment]
ok, seems that i got the wrong number from the moderator.
i opened Game.eco with 7zip and used the name from the file in Users. double checked it with the value in steamdb.info. I don't know where to find in steam.
And i swear that i did not use that number before that update and i was admin

**Comment by Last2Night** [comment]
@Mephiztopheles You can find your or any other player's STEAMID64 following this link: https://steamid.io/

**Comment by Mephiztopheles** [comment]
So, to say, it works now but I'm confused that I now need a different value as before the update. A nice feature would be that I can copy my steam Id after command whoami

**Comment by Last2Night** [comment]
@Mephiztopheles Its the same values you needed on 7.2,  7.1, 7.0. There were no changes.

**Comment by MarjieAVolk** [comment]
What version were you on previously?  I think it has been this way basically since the steam release.  But maybe your configs just got overridden on the update, and you hadn't had to deal with it for a long time or something.

It would be real nice to be able to copy things out of chat (this is requested here also: https://github.com/StrangeLoopGames/EcoIssues/issues/1390, I will add a note there for this use case).

Once you yourself are an admin, you can easily make other players an admin by using the /admin command with their username (this will look up their ids via their username automatically).  Also, when running a server from in game, you are automatically made an admin.  So it's only the server owner of a standalone server who has to deal with this.  Not that it's not still annoying.
