### ISSUE TITLE
Crash when starting new game

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7042]
From the support queue. Additional logs attached in a zip.

"The version of the game you were running: 0.7.2.5 beta game and server ver.
Operating system: windows 7 premium 64bit
Processor model: Intel Core2 Quad CPU Q9650 @ 3.00GHz
Graphics card model: Nvidia GTX 750Ti
Amount of RAM: 8GB

start game and name world, as soon as I finish that and continue to start game the server starts and immediately crashes.

error message:

Problem signature:
  Problem Event Name:    CLR20r3
  Problem Signature 01:    EcoServer.exe
  Problem Signature 02:    1.0.0.0
  Problem Signature 03:    5aaab716
  Problem Signature 04:    EcoServer
  Problem Signature 05:    1.0.0.0
  Problem Signature 06:    5aaab716
  Problem Signature 07:    29
  Problem Signature 08:    a7
  Problem Signature 09:    System.MissingMethodException
  OS Version:    6.1.7601.2.1.0.768.3
  Locale ID:    1033
  Additional Information 1:    40cf
  Additional Information 2:    40cf079a96ef2995d5fbb3c34d123859
  Additional Information 3:    7861
  Additional Information 4:    78615ac179a99c1a13f2152b23b66502"

[2018-04-07-09-47-25.zip](https://github.com/StrangeLoopGames/EcoIssues/files/1886152/2018-04-07-09-47-25.zip)

**Comment by MarjieAVolk** [comment]
This error is caused by not having the right versions of .NET installed.  Steam is supposed to automatically install them normally, but our configuration for this was set up incorrectly for a while.  Since the player is running on an older game version, I believe if they update to the latest version this should be resolved automatically.  (See https://github.com/StrangeLoopGames/EcoIssues/issues/6054)  If that is not the case, they can install the correct .NET versions manually here:

https://www.microsoft.com/net/download/thank-you/net46
https://www.microsoft.com/net/download/thank-you/net35-sp1

**Comment by noblackthunder** [comment]
I think its better to use the latest version always https://www.microsoft.com/net/download/windows , it normally contains always the older versions too. So downloading the latest .net Framework runtime is what i would recommend. 

Sorry Marjie for also commenting :P
