### ISSUE TITLE
Server List Issues

### ISSUE THREAD

**Issue by Xephita** [StrangeLoopGames/EcoIssues#7044]
Server list still needs serious improvements
Still no sort function other than the default ms, which is awful because it just causes the server list to jump about. The search function isn't really very useful either.

Suggest being able to filter by some of these 'Day' 'Total Players' 'Skill Specialization' 

No way to see if a server has a password before trying to connect.

Suggest adding a Padlock Icon visible by the server name.

Error messages are non informative for most people, no idea why connect attempts fail.

Suggest adding a more user friendly error system / description.

The server list jump's around too much and cannot select a server to 'hold it' or highlight it in the moving list.

Suggest stop the list jumping around *until* you hit either sort / filter, add a way to hold or highlight a server instead of having to quickly try to favorite possible choice.

**Comment by MarjieAVolk** [comment]
Hey, thanks for the suggestions.  I am currently working on a rewrite for the Join screen, which will include many of these.  Sorting by a couple of different parameters, as well as much more powerful filtering are some of the major features planned.  I like your idea of not sorting until you have specifically chosen to sort.  This will make a lot more sense once we have these default filters as well.

The search functionality is really a different use case - that is, for searching for a specific server, if you already know which one you want to join - and in the new version, this will be placed in a separate area from the 'browser'.

Displaying password settings more prominently is a good idea, I will make a note to add a filter for that, as well as a display somewhere.

As for the servers jumping around, I am hoping that by applying several common sense filters by default, the filter list that you see will be much shorter and the jumping around won't be as big of a problem.  In addition, the new version of the join screen will have a 'detail panel', so that you can click on a server to select it, and then details and the Join button will be on this detail panel.  This should help with your problem of having to favorite a server to be able to look at it / decide whether to join it.  I can also look into keeping your selection scrolled on-screen - not sure if that will be implemented or not.

As for connection error messages not being great - I also wish they were better; I think the main issue is that we can't really give an error message unless we actually know what is wrong, and in this case we still don't really.  We do have one big class of errors that give a 'connection failed' message when they really shouldn't (https://github.com/StrangeLoopGames/EcoIssues/issues/4956), which we hope to address soon.  We are also working on a server connection overhaul right now, which we hope will reduce the number of connection failed problems.

I've made some notes to myself of your ideas that I will implement while working on the new Join screen.  Thank you!

**Comment by Xephita** [comment]
Great, thanks for the info and reply. Look forward to the changes in the future!
