### ISSUE TITLE
Powered Cart "ZeroCoordinate" Remote Controlled Vehicle

### ISSUE THREAD

**Issue by Tetramorium** [StrangeLoopGames/EcoIssues#7051]
Version: 0.7.3.2 beta

Steps to Reproduce:

Drive the powered cart over the zero coordinate. 200 x 200 world

Expected behavior:

Not getting kicked out and continue driving

Actual behavior:

Get kicked out and be able to still control the vehicle.

https://clips.twitch.tv/SilkyAmericanJalapenoPunchTrees

**Comment by ecoemmeck** [comment]
instead of me opening another issue im just going to add to this one. as its probably tied to the same kind of thing

when using /fly and then getting into the powered cart the same thing happens except your still flying but the cart is moving what ever way your moving your player with the wasd keys

**Comment by SeanAtr0n** [comment]
Does this still happen in 7.4? I haven't been able to reproduce this yet
