### ISSUE TITLE
Cannot remove Powered Cart fuel when cart is in another player's claim (without auth)

### ISSUE THREAD

**Issue by gabeux** [StrangeLoopGames/EcoIssues#7057]
Hello!

A constant issue in the server I play in is players falling down ramps or getting stuck in other players' claims, who they have no Auth on, and they cannot remove the fuel from their Powered Carts. This makes them really stuck (without being able to hammer to remove it) and requires admin intervention every time.

Thanks!

**Comment by 10KEco** [comment]
I have had the same issue. i could not take the gas out or pick up the PoweredCart due to not being authorized. i tried to drive off the property on to unclaimed land, I've tried driving onto my land and nothing helped. I did notice that the name of the cart as well as the deed took the name of the property owner where i first had issues.

**Comment by MarjieAVolk** [comment]
O.o Okay this sounds like it should be easy to fix, I will look into it.

**Comment by SeanAtr0n** [comment]
seems to be fixed in 7.4

**Comment by SeanAtr0n** [comment]
actually, nevermind >.>
