### ISSUE TITLE
[SUGGESTION] Key binding

### ISSUE THREAD

**Issue by Ekkelus** [StrangeLoopGames/EcoIssues#7081]
I was told by a player to suggest this as a function, key binding.

**For example:**
bind x chat.say "/unstuck"

**Comment by gabgab01** [comment]
just my opinion, but:
this can easily be exploited by griefers and would not only be hard to implement, as there is already a keybinding menu, (people would accidentally open a menu while doing this,) and you could just use autohotkey for this. just make a simple autohotkey command that presses enter and then types what you need to have typed, then presses enter again.
also, how often do you need to use the unstuck command? :D 

but i can see where you're coming from (or your friend for that matter: garrys mod)

**Comment by lightdrawn** [comment]
Not „/unstuck“, but I use „/give dirt,10“ and „/give sand,10“ quite a lot, would make things way more convenient. ^^

**Comment by MarjieAVolk** [comment]
Yeah seems unlikely we would implement this, since as suggested, you can already use third party software to do this.  But we have been meaning to add a command history, so it is easier to repeat a command you just did recently: https://github.com/StrangeLoopGames/EcoIssues/issues/2585  Might help your problem.
