### ISSUE TITLE
D/C from Server, Stuck on Entering World

### ISSUE THREAD

**Issue by Henolicro** [StrangeLoopGames/EcoIssues#7088]
Related to #6882, however not fixed on 7.3.2 update.

Running a PingPerfect server.  We have frequent disconnects and get stuck on "Entering World" when trying to reconnect.  Issue resolves on server restart.

We suspect it's related to laws and voting, as it seemed to occur most when accessing those menus, although not all the time.

All laws and voting were removed and haven't seen the issue in approx 12 hours.  This obviously takes away a large portion of the gameplay.

Error in server log reads "Caught update exception ThreadAbortException from Henolicro! Disconnecting..."

Once it happens to one player it seems to cascade to others.

**Comment by gabeux** [comment]
+1. We had to 'flush' ours laws twice in our server due to it. Can cause extreme lag or prevent the server from starting, even with only 1 player on.

Thanks so much for the developers to Responding ASAP to this. It's core to the gameplay and one user lost hours he spent doing a district map due to lags/crashes and this issue.

**Comment by SeanAtr0n** [comment]
you notice any particular type of law that triggers this?

**Comment by MarjieAVolk** [comment]
Okay we think this is actually the same as https://github.com/StrangeLoopGames/EcoIssues/issues/6882 now, and that this was not fixed in the hotfix, so merging this issue back over there.  Thanks for all the details!
