### ISSUE TITLE
Player groups

### ISSUE THREAD

**Issue by CuAnnan** [StrangeLoopGames/EcoIssues#7091]
I've run two worlds now. And the biggest problem is always deforestation and people not cleaning up after themselves. There are no reasonable laws that can be crafted to stop players from being assholes.

The same is true of tailings.

We need to be able to say "these players have shown they can mine/forest".

**Comment by MarjieAVolk** [comment]
So you want a whitelist/blacklist for player actions?

This is similar to a feature I had wanted to add, which I was calling 'demographics' - That is, you define a 'demographic', either using existing law conditions or via a whitelist/blacklist, give it a name, and then you can reference that demographic in multiple laws.  Could be a way to support mod privileges and the like also.

**Comment by CuAnnan** [comment]
That's exactly what I mean. And demographics is an excellent term for it. Thanks.

**Comment by TheGhost10000** [comment]
This would be absolutely horrible to allow players to put in a law like this to prevent a person from 
mining or logging. 

If I was a logger lets say and I have a bunch of friends of mine on this server as well and there
was a 2nd logger on the server who was my competition on this server and selling wood
products as well.

If a law like this was allowed I could setup a law to restrict that person from cutting down
trees indefinitely and I could tell all my friends to vote for this law to get it passed so that
player B could basically never cut down a tree again.

There is way too much room for abuse and it could prevent player B from being 
able to construct a wood house if they wanted or cut down any trees.

There is way too much room for abuse of power here and I don't think that 
the players should be able to white list or blacklist the actions of another player.

If you are having issues with people not removing the stumps then the server
admin should be getting involved at that point and speaking with the player 
and telling them hey you have to remove your stumps or we will ban you from
the server if you don't follow the rules. 

I do not believe that this issue would be a good idea at all and ask that the devs 
please not implement something like this as the ability for abuse is extremely 
high.

**Comment by TheGhost10000** [comment]
No wrong again there may be a server admin that should administer the server but the whole player base 
should not be allowed to put a law against a single player.  LOL and don't say if you don't like it then go play on another server that is just a BS answer.

If a group of players are allowed to wrongly restrict the action of another player than that is clear abuse 
of power.  Which is what could happen with a law system like this. 

There is plenty of room for abuse if you allow a law system like you are proposing where a law
could be put against a person for absolutely no just cause. 

You say there is no room for abuse but there is plenty of room for abuse here where a law
could be put against some one to stop them from mining or logging for no good reason
simply because you and your buddies don't want competition.

There is a lot of room for abuse here and a law system like this could easily be used to 
grief another play intentionally or intentionally. 

And what are you talking about asking a mod to micromanage is absurd. I never said a mod
should micromanage. 

This idea is absolutely stupid and should not be implemented in any way in Eco once again
admins please don't put a law system like this in place.. 

It is idiots like this that is going to ruin Eco please don't put a law system like this 
in place. 

Most of the people (99%) who currently do run servers shouldn't be running a server
anyways because they have no clue as to what they are doing. The servers 
really should be run by Strange Loop Games but they aren't right now 
and the system CuAnnan is proposing would leave it open to way 
too much abuse or griefing towards another player. 

Once again Devs please don't put anything like this in place that could be used 
to grief another player. 

Both logging and and mining is a key component of the game and if you take
either of these away from a player it would take away a lot of the game for that 
person. 

I hate immature little brats that tell you "if you don't like X then go play on
another server" that is absolutely wrong everyone should be able to play 
on any server they choose and not be griefed by another player.

**Comment by CuAnnan** [comment]
People **pay** for servers.

Want your own server with your own rules **pay** for it.
SLG can't afford to run servers for everyone. They would need to soak up all of the costs that all the people already **paying** for servers pay. CPU, RAM, network bandwidth, hardware administrators, tech support, these things *all* cost money.

There is *literally* no reason SLG should be expected to soak this.

The problem you're describing is an edge case. One that already exists. One that I have already described the way these griefers can put in place. The system being described does not impact that at all.

By all means, continue the conversation. But refrain from further personal insults please.

**Comment by MarjieAVolk** [comment]
You're welcome to express your opinion, but please don't attack people.

It's already very easy to create annoying laws, and to target people specifically.  For example, you could define a district around a player's property and prevent a bunch of actions while in that district.  Or you could check whether the performer's (Susie Credit) balance is higher than 1,000,000 and if so prevent a bunch of actions.  Etc.  So I don't really see the problem.

**Comment by TheGhost10000** [comment]
MarjieAvolk I am not attacking anyone what I said is 100% right.  If there is an issue then maybe
I should speak with your supervisor then because I am not attacking anyone. 

I have my right to express my opinion about this and this would be extremely bad
for the game! 

And if you don't see a problem with a law that would target a player to intentionally
grief them then there is a real issue here.


For CuAnnan 

I really don't care who pays for the servers people should NOT be allowed to be targeted 
directly. 

There is a reason why Strange Loop Games should be running the servers is because  99%
of the people out there don't know how to properly administer a server or properly
run this game.  The servers should be run by Strange Loop Games. 

The problem I am describing is not an "Edge Case" it would be used to to grief and target
an individual player. 

And if you don't like my response then you can ignore me but I have my right state my opinion
here and I will. Don't be telling people to play on other servers then if they don't like it. 

That is an absolutely horrible response for anyone running one of  these servers and is the reason why the game servers should NOT be run by players but rather professionally hosted by Strange Loops. 

CuAnnan you will not dictate to me either how I respond.  If you don't like my response then
block me but I will not be told how I should or should not respond by you or anyone else.

**Comment by CuAnnan** [comment]
You have no rights here. You have obligations. Per the terms and services, which you agreed to when you registered your account. And you did make personal attacks. You called me immature. For pointing out what your rights *actually* entail. The freedom to leave a server.

Neither this site, nor any server you join, are public domains, and so your first ammendment rights are not being infringed upon when someone moderates you. The first ammendment protects your right to set up a competing website, that is *literally* all.

People who pay for a server can do with that server whatever they want. That is a legal right they *actually* have. You have no rights when you join a server. Any server you play on, you play on with the blessing of the server owner.

Now. Unless you are personally willing to pay SLG 20 dollars a month to play on their servers, (and that's so that they can pay the people and costs I listed) asking them to host servers is unreasonable. They provide the game and they provide the server software to all players who have paid.

I run a server. I run it fairly. So I am speaking as one of those people.
I suspect you're not running a server.

**Comment by TheGhost10000** [comment]
I have the right to post my opinion about what you are saying here.

I would hate to be on any server you would run because it would be run like Nazi Germany during 
world war 2 if you say anything that CuAnnan doesn't like you get instantly banned. 

I will call you immature because you are and if you don't like that then tough! 
Telling people to go play on another server is the wrong attitude for a server admin to
have. 

People like you should not be running a server in the first place and the servers should
be run by Strange Loop games not people like you. 

LOL And I wouldn't be no $20 a month either ... it may be about $10 - 15 a month 
which would be a standard charge for a MMO. I should know I have played enough 
of them. But since the game is currently under development and this game is in Beta 
and really the players are doing them a huge favor by beta testing this game so that
they don't have to hire people to do all the beta testing then I would say that 
until the server was actually out of Beta and at full release there wouldn't be any
kind of a charge anyways.  Clearly you don't know what you are talking about when 
you say $20 a month. 

I would rather have a professionally run server by admins that know what they are 
doing than an amateur like you and have the servers run on a professional grade
server. 

Also I am a network admin as well so I suggest you watch what you are saying. 
you are the one that is throwing insults at me. it seems that you can dish it out
but you can't take it. 

Simply because you pay for the server does NOT give you the right to grief another 
player and ruin their playing experience which is exactly what a law system like this 
would allow. 

I highly doubt you run it fairly what so ever

**Comment by MarjieAVolk** [comment]
@TheGhost10000 I have asked you not to attack people.  Now you are not only attacking, but threatening people.  If you continue, we will ban you from our github projects and our discord.

**Comment by CuAnnan** [comment]
Did she block me or were her posts deleted?
If her posts were deleted could mine be too so I don't look like a crazy person?

**Comment by MarjieAVolk** [comment]
Oh I see hahaha - It looks to me like they have deleted their own comments.

Okay, I will just delete this whole conversation.  Thank you, and sorry about the harassment.

**Comment by Deantwo** [comment]
Allow us to add numeric values to people in those _demographics_, and then we can use them to set limits for people too. "You can cut down this many tree" or "you can claim this many plots", and then we can make laws to add more _points_ to them or allow us to sell/trade them as items.

**Comment by MarjieAVolk** [comment]
Like variable definitions?  Like `'tree chop permits' is defined as 5 - your harvest actions where species is Birch`

**Comment by MarjieAVolk** [comment]
Or I see, this is a request for something that behaves more like the currency experiments from the discord discussion.  Like `Players start with 5 'tree chop permit'`, and then you'd have laws like `when attempting to harvest, lose 1 'tree chop permit'`, `when attempting to plant, gain 1 'tree chop permit'`

**Comment by Deantwo** [comment]
Yeah stuff like that. Figured it could work somehow well with groups/demographics maybe.
But might me hard to make them tradable items then. So maybe I am just mixing things that shouldn't be mixed.

**Comment by MarjieAVolk** [comment]
No, I don't think there's an issue for that yet.
