### ISSUE TITLE
[ISSUE] Abusing /unstuck

### ISSUE THREAD

**Issue by Last2Night** [StrangeLoopGames/EcoIssues#7123]
A timer cooldown has to be added to /unstuck of at least 15 minutes. Players can spam /unstuck to get up to mountains top, bypass cliffs or simply to fast travel. Please hardcode a cooldown of at least 15 minutes and add an admin command `/adminunstuck <playername>` with no cooldown for admins to help people with /unstuck on a cooldown.

Thank you.

**Comment by elfl0rd** [comment]
or make unstuck - "teleport to spawn"

**Comment by ecoemmeck** [comment]
I think there maybe a problem with this idea. I'm an admin myself for the most part I get where your coming from however the main concern I have is what if an admin isn't online to help out a player that is legitimately stuck these players will end up hating the game simply because they get stuck and have to wait. I propose that the cool down is configurable in the server UI so admins can set a cool down time themselfs

**Comment by Dreepa** [comment]
Incremental penalty

**Comment by lightdrawn** [comment]
> or make unstuck - "teleport to spawn"

I like that, I once was stuck in a full stockpile of glass, I needed several tries with /unstuck to get out of there. 

And even if people abuse it then, they are more likely meet someone at the spawn, it's good for socializing. ^^

**Comment by Nanders** [comment]
This has been implemented

**Comment by Last2Night** [comment]
Implemented in what form and which version?
Thank you.

**Comment by elfl0rd** [comment]
Cooldown, upcoming version.
Release soon.

**Comment by Nanders** [comment]
elfl0rd is correct,

Right now /unstuck is on a short cooldown timer.

**Comment by elfl0rd** [comment]
Yep, i reading your discord #codestream :)
