### ISSUE TITLE
Objectives accept text formatting

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7145]
![image](https://user-images.githubusercontent.com/6262198/38649373-0f355caa-3dab-11e8-9988-4fe32b51799a.png)

**Comment by MarjieAVolk** [comment]
I was saying earlier there's just a checkbox on TMP objects, enable rich text or some such, that can disable this.  But it does have to be done everywhere this is displayed in order to handle that well.  Chat relies on rich text for things like icons and tooltips, so that might not be an option.  Maybe we can strip tags on submit or something.

**Comment by MarjieAVolk** [comment]
You know, is this really something that we need to prevent actually?  Because people do seem to like using tags for colors etc.  Especially since the world objective is displayed in the server browser, and is kind of an ad for the server.  Thinking this is working as intended...

**Comment by MarjieAVolk** [comment]
Reopen if you disagree
