### ISSUE TITLE
Sometimes hard to find ore

### ISSUE THREAD

**Issue by Dreepa** [StrangeLoopGames/EcoIssues#7176]
Finding ore is just based on luck

Sometimes you can get unlucky, and dig super long, without finding what you look for. This is rather boring (and annoying, as you have to always bring back 20 stone before you can continue digging, making it tedious).

Suggestion:
Add a device to the game (maybe something that you need to craft, like the soil sampler) that helps you find a specific ore/coal. Maybe something showing the general direction in which you would find the selected ore, or maybe something that has a signal-strength display, which rises when you get closer to the ore, and drops when you move away from it.

**Comment by zimmah** [comment]
Maybe have the regular ore be surrounded by an amount of lower density ores.  
Currently stone and ores break into 4 pieces. So why not have some stones and ores drop into 3 ore and 1 stone, 2 ore and 2 stone or 1 ore and 3 stone?
This will help you locate ore deposits, since if you start finding low density ores, a deposit may be close.   
This could also overlap with each other (an iron deposit close to a gold deposit may have 1 gold, 1 iron and 2 stone for example).

**Comment by PacifyerGrey** [comment]
Ore Prospector device would be really cool. But I would add a twist to it. You should have some skill learned to ba abl eto see the data provided by this tool. This would make a miner profession so more effective as a standalone thing on high cooperation servers! And with this change you can lower ore generation in the world making it even better overall

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#138
