### ISSUE TITLE
Treasury Allows Allocating Negative Currency

### ISSUE THREAD

**Issue by Legends0** [StrangeLoopGames/EcoIssues#7201]
**Version:** 0.7.3.3 beta

Treasury currently supports stealing currency from users. This also works on credits, which is a much worse situation since you can get indefinite amount of that. Fortunately, you must be voted the world leader first.

**Steps to Reproduce:**
As the world leader, use the treasury and allocate negative coin to a user.

**Expected behavior:**
Treasury ~~only accepts positive~~ does not accept negative integers.

**Actual behavior:**
Treasury accepts negative integer and takes from the user.

Using Coin:
![image](https://user-images.githubusercontent.com/5702579/38774437-fbaa5e54-4036-11e8-81b5-edcdbb026d65.png)

Using Credit:
![image](https://user-images.githubusercontent.com/5702579/38774461-adfb3d30-4037-11e8-8482-da15055f96a2.png)

**Comment by Rick86** [comment]
Hey wait! We use this to get "taxes" and other payments by users.
For example: We sell lands in the city via auction and take the payment via the treasury... So the leader should be smart enough to know that negative values are taken from the user...
PLEASE keep the negative values.

**Comment by Dreepa** [comment]
The world leader has more rights and acts as an authority. He/she can already set high taxes to sabotage the game. This is really a fundamental game design decision about the regulating capabilities of the world leader in general. Currently, the WL is empowered. I think this is a good thing, as there is a voting process to put them in place. 

Instead of removing WL rights, maybe it would fit more into the concept of "instant dismiss", here the people can demote a bad world leader (rebellion!) in a much shorter time frame than the usual 24h but with a certain min-reqirement (like at least 60% of all players online in the last 2 days or something).

**Comment by Rick86** [comment]
@MarjieAVolk The law clause will **enable** the option to allocate negative values via treasury? Or what do you exactly mean? The thing is: The leader represents the government, and the government can set taxes und can share the money with everyone or take it for itself, or burn it or whatever. So what is the difference between setting tax to 100% or allocating negative values (which means takes money like instant tax or payment for government services).

One more example: We want to give claimed grounds to our farmers, they have to pay a small amount every day or week. How could the government take the money for the grounds?

If there is an option to get payments from government side, everything is fine for me. I think the treasury would be the best place for this.

@Legends0 If you are afraid that someone will abuse the treasury function (and he can abuse it without negative values also), then disable the leader / vote function via a law.

**Comment by MarjieAVolk** [comment]
No, I mean when you would want to allocate a negative value, instead you propose a one time tax, and after it gets voted on it gets applied once.

As for your question about taxing land periodically, I don't think there is a good way to do that right now, but I will make a note of it for future features to add to laws.

**Comment by Rick86** [comment]
At the current version I can just allocate a negative value, maybe once a week, this works fine for me. But this is just for a bunch of people, and everyone has different payments. So the easiest way would be keeping everything as it is ;)

I saw also the ECO Team removed the ability to do negative values for **contracts**. This way we sold the government grounds (if they "buy" the contract, they get access to the chest with the deed and can claim the deed with the ground). This feature was removed also, now we have to set up a deposit and accept the contract, so they get their deposit back. Therefore we have to take the money after accepting the contract (via the treasury of course)... Everyone was fine with negative values (I mean we are in Version 7.3 now)... Now one person dont't like it... I think it's a bad way to **remove** a feature, instead of **add** a new feature... The same happened with the "government currency" feature, I saw this on facebook, but it seems the feature was removed.

If an user dont like a feature and he can disable it or just don't use it, it should be okay. But if an user like a feature (or need it) and it's get removed, this is very bad for the user.

Maybe you should think about this: How many people use the treasury the same way we do? Why should anyone write this like me? The don't know the feature will be removed. We have a big server with many users, do we have to cancel our project and lose all of our users? Some people of our server buyed ECO just because of our project.

So this is just my opinion, less work, less problems ;)
It's your decision, anyway thanks for your time :)

**Comment by Legends0** [comment]
Allocation of negative currency does not accurately reflect how government interacts with the economy to hand out funds. In the real-world, the closest way to represent the government "taking" currency, that exists simulated in the game, is taxation.

Governments cannot arbitrarily set values of currencies, but attempt to do so indirectly through exchange rates, and even then it gets predominately controlled by the foreign markets regardless of what the government would like its currency to be worth. This exchange system is simulated in the game, but not government controlled.

For Eco, there needs to be a better solution than relying on allocation of negative currency to allow players to trade with the government. There could be government owned stores or contracts, but the game does not yet have such a mechanism in place where the owner is the government.

**Comment by johnkslg** [comment]
Good comments all
I've removed the ability to set negative currency. However, with the law system, you have a lot more control in achieving the same 'payments from the treasury' effect, but without the bugs. You can make users receive money on actions.  We'll be adding more power to this law system overtime for more complex government fund management. Cheers!

**Comment by elfl0rd** [comment]
Bad. Uses allocate negative number to fill treasure from minted currency :(
