### ISSUE TITLE
Cooking needs more complexity

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7235]
Per Reddit user:

"Personally, I love the farming because it's so zen and doesn't require a butt-load of time. I look for the right soil, try to get the nutrients about right, plant crops, set a timer, repeat ad nauseum.

Cooking I also enjoy but feel it's a bit bland. Could benefit from some other variable that makes it more interactive.

Devs, if you're watching, holy cow. Great game, guys. I bought it and convinced six friends to do the same."

**Comment by WindRider739** [comment]
Hey, that's me!

I feel like food needs something more than fire-and-forget mechanics. Anyone who's done baking in real life knows a teaspoon too much of flour can ruin a cake. Maybe a mechanic where food has a quality value that is affected - within reason and to a limit - by how many times the item has been made by that player? Of course I don't know how you'd overcome the Life is Feudal element of quality stacks going haywire everywhere.

I wonder if maybe you could increase production time on baking or lumber-cutting etc, by participating in an optional mini-game for each activity? Say you're making a stack of kebabs; a one minute minigame where you rotate the kebab at the right times to distribute heat evenly could knock a percentage off of the cook time for that project. Or say you want to produce 20 lumber - use your mouse and guide each piece of wood through the sawmill with a steady hand in order to speed it up a bit and possibly get some extra out of it if it's perfect.

Hi. I'm Wind. I like to help and have no clue what coding is involved with implementing things.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#128
