### ISSUE TITLE
Suggestion: Trains as a method of transit/transport

### ISSUE THREAD

**Issue by GophTheGreat** [StrangeLoopGames/EcoIssues#7282]
From the support queue: 

"I love your game eco. I like it realy but I would like it if you can add for example trains. Maybe they can work like moveable stockpiles. That would be awesome 
I hope you like this idear and maybe you can add thi in one of the next patches. "

**Comment by Elliander** [comment]
I actually like this idea quite a bit. Personally, I love building road systems under ground, but I have to plan for all vehicle types. If I could put in rail tracks and construct the building as well, then set it on a loop where players have to pay to use my train it would add incentive for my to build such tunnels. 

It would also add a use for coal, and introduce new demands and consequences.Is the ability to quickly circumnavigate the globe for rapid trade worth the cost to the local environment? 

In real life, planting trees is a good way to cheaply reduce coal particulates around power plants, so I'd hope that such a mechanism also exists in this game.

Maybe then an upgraded train could use an electrical wire, so that I'd have to plug the train in for it to run, and maybe another player could actually run the wind turbines and I pay them for delivery. That way I could have clean trains.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#132
