### ISSUE TITLE
suggestion  Animal authority change

### ISSUE THREAD

**Issue by 10KEco** [StrangeLoopGames/EcoIssues#7300]
If you remove the property authority off of the animals it will give players more of a need to create laws about hunting. This will also give the opportunity to charge players who hunt on owned land.

**Comment by Elliander** [comment]
I like this idea. I didn't even realize people could hunt on my lands. Without fixing this I would easily expect people to hunt in other people's land preferably - just like how I catch players preferring to cut down trees at the edge of my property our outside their own rather than spoiling their own view.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#119
