### ISSUE TITLE
duplication of truck and different object on stagged version.7.4

### ISSUE THREAD

**Issue by Marathorn** [StrangeLoopGames/EcoIssues#7325]
Server use last stagged version, and sometimes things duplicate. at start i had a truck, and 3 more appeared without crafting. Some other things duplicate like that : chests, farming table and more.

**Comment by Marathorn** [comment]
another example : i decided to move 2 chests. i did and after deco reconnection, i had 4 chests : the two i moved , and two more that were on old position....

**Comment by elfl0rd** [comment]
This happines after server restart, yes?

**Comment by Elliander** [comment]
yeah, same thing happened to me. I was actually planning on building a giant pit to dump all our excess vehicles into when the server went down yesterday, but then when it went back up I couldn't get back in - or see any staging server in the join a server list for that matter. Are they all down due to this issue? I can play in and host 7.3 worlds just fine.

**Comment by SeanAtr0n** [comment]
Should be fixed in next staging build.
