### ISSUE TITLE
[7.4.0 #68e3874b]  Refresh not working on "My Servers"  and other Browser and filter issues issues.

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7367]
When server status changes it does not reflect on the servers in "My Servers", if you refresh to change status nothing happens except that "Recent" will update.

If you had servers set in favorites in version 7.3.3 they will show up in "My Servers" in 7.4.0 however they show offline although they still show online and you can connect in the 7.3.3 version

Shows all 7.4.0 servers that you favorite as offline, even while showing those same servers as online in the "Browse" window

Even with "version match" and 'language" unchecked it will not show servers other than 7.4.0 servers in "Browse"

To get filters to apply and servers to show up in "Browse" you must click 'search' and click "apply" with nothing set for it to search for, refresh does not always show all available 7.4 servers

If in "My Servers" and are clicked on one and then do a "refresh' it puts that server in the top line and deletes the server that was there

Filters do not remain as set by user if you enter a game.  When you return to the main menu the filters have reset to default.  They also revert to default when you shut down and restart game.

**Comment by pamduncan** [comment]
Also, many servers showing up with 0 ping although online.

Searching on "blank" returns more servers than "refresh " does

**Comment by MarjieAVolk** [comment]
It sounds like a lot of these issues are related to redoing the networking in 7.4, and won't be an issue for future versions.  For example, servers showing as offline in favorites - if they are on 7.3 or a previous version, they won't be responding in the way that 7.4 expects now, so they will be treated as offline since they will never respond.  Similarly, if servers are on a version before 7.4, they won't show in the server listings, because we have a different server listing service now, which servers will only be on in 7.4+.

Searching with a blank string will switch you from filter mode to search mode, so it will get rid of any filters that you had set, which is why you may be seeing more when you do that.  Applying the filters will set it back to filter mode.  Refresh shouldn't affect which servers are filtered out, it should keep the same settings that you had before you hit refresh.

Some of the other comments you made are also reported in other bugs you filed:
https://github.com/StrangeLoopGames/EcoIssues/issues/7525
https://github.com/StrangeLoopGames/EcoIssues/issues/7526

So after all that, the remaining unique issues are:

> When server status changes it does not reflect on the servers in "My Servers", if you refresh to change status nothing happens except that "Recent" will update.

- Filed https://github.com/StrangeLoopGames/EcoIssues/issues/7615

> Shows all 7.4.0 servers that you favorite as offline, even while showing those same servers as online in the "Browse" window

- Filed https://github.com/StrangeLoopGames/EcoIssues/issues/7617

> If in "My Servers" and are clicked on one and then do a "refresh' it puts that server in the top line and deletes the server that was there

- Filed https://github.com/StrangeLoopGames/EcoIssues/issues/7618

> Also, many servers showing up with 0 ping although online.

- Filed https://github.com/StrangeLoopGames/EcoIssues/issues/7619
