### ISSUE TITLE
Beta 0.7.3.3 - Performance issue | Low FPS

### ISSUE THREAD

**Issue by fillion07** [StrangeLoopGames/EcoIssues#7392]
If it can help for future reference or for statistics, I'll give you my GPU, CPU and RAM specs, plus my current settings of the game.

The following specs and game settings make the game run between 15 and 25 FPS (with minimap CLOSED).
GPU: Graphics Chipset [AMD Radeon HD 7700 Series] | Memory Size [2048 MB] | Memory Clock [1125 MHz]
CPU: Intel Core i7-3770K @ 3.50GHz
RAM: 16 GB
Game Settings:
- Shadow Quality: Fastest
- Foliage Quality: ~40%
- Render Scale: 100%
- Brightness: 100%
- Field of View: 59
- View Distance: 76
- Interface Scale: 76%
Advanced Game Settings:
- Resolution: 1920 x 1080 | Fullscreen
- VSync: TRUE | 1 syncs/frame
- Atmosphere Scattering: FALSE
- Fog: FALSE
- Realtime Reflection: TRUE
- Sunshafts: TRUE
- Vibrance: TRUE
- Ambient Occlusion: TRUE
- Bloom: TRUE
- Global Illumination: FALSE
- Show Interact Cursor: FALSE
- Underwater Distortion: TRUE
Other Information:
- Minimap is turn off in game.

If you need more information on computer specs or game settings, even if you need some screenshots, I'll be happy to give you those details.

At the end, if the low FPS is not a common issue for the previous specs and settings, let me know so I can troubleshoot on my side.

**Comment by Nicolausi113** [comment]
Hi fillion07
In my opinion, your installed memory size 2 GB is to less for that game, so the PC uses swap space ( hard disk). The rest of your machine is pretty and should work .
My PC is not so good equipped, but has 8 GB memory installed, and the game runs acceptable. If ECO is running, “taskmgr” tells me that about 3 GB are used.

**Comment by fillion07** [comment]
@Nicolausi113 You read it wrong I have 16 GB of Memory (RAM). The 2 GB is about the memory of the GPU only. So my machine should run like a charm.

**Comment by thereporter42** [comment]
Version: 0.7.4.4 Beta

Steps to Reproduce:

Just try and play the game and watch it lag to hell

Expected behavior:

An actual half decent frame rate of maybe around 32 FPS. 

Actual behavior:

Same video card as Fillion07 and the same issues with this game.  He opened 
this ticket like 20 days ago or more now and still no fix to this I am on a 0.7.4.4
server and it is just horrible.

Wow this is just horrible getting between  6 - 9 Frames per second (FPS) 

You really need to work on this game and make it a heck of a lot better.

Wow this is just horrible and I am running on an I7 as well here.. with 16 GB of RAM
AMD Radeon HD 7700 Video card. 

Intel Core i7-2600 3.40 GHZ 
16 GB RAM
AMD Radeon HD 7700 Series Video Card
DirectX 12
Page File: 9809 MB used out of 13963 MB
Windows 10 Pro (64 bit) Build 16299

[DxDiag.txt](https://github.com/StrangeLoopGames/EcoIssues/files/2011561/DxDiag.txt)

And I have my settings turned down a lot as well Here are the screenshots of my 
Graphics settings and Advanced Graphics settings. 

![eco graphics settings may 16 2018](https://user-images.githubusercontent.com/38896397/40155659-38f8e224-5952-11e8-959b-284bda7fbea3.jpg)

![eco advanced graphics settings may 16 2018](https://user-images.githubusercontent.com/38896397/40155662-3db92e54-5952-11e8-91fb-a3bf726f9ed7.jpg)

Please fix your game immediately this is just horrible it gets to the point where it just
unplayable! 

This is more than just optimization this is a totaly overhaul of your graphics system
and how things are handled this is absolutely no good the way things are now. 

Please fix this immediately!

**Comment by metachronism** [comment]
8.0 will have more optimizations, we are always working on optimizations.
this issue seems like its using the wrong GPU?  were you in a multi GPU system (like a laptop, that only uses the GPU when it detects games are running)
