### ISSUE TITLE
Mine cart and rail line

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7398]
From Forum User: http://ecoforum.strangeloopgames.com/topic/4430/will-mine-cart-rail-systems-be-a-thing-for-this-game

"Will "mine cart" rail systems be a thing for this game

  Razorflare posted 13 days ago   1 
Like the title says. Will mine cart and rail line be added in the future. It would be neat to have a rail system in place that could cross the entire globe, with road intersection, so those that just want to load a mine cart/ rail car with their goods, rather then using a small cart/road buggy to transport items to shared stockpiles.

Powered carts could be steam, combustion, electrical, and "handcar" ppl power car.

Rail stations could be used to store, setup, and manage carts. advanced versions could have an automated system for distribution of items.

just some thoughts"

**Comment by Elliander** [comment]
I'd really like to see this as well. Maybe it could have multiple improvements as well. For example, the simple mine cart that is powered by mechanical energy - you stand on it and pump, and if someone else pumps with you it can go twice as fast. It could have a place to load up stockpile resources in the center:

![a_handcar_pump_trolley_uk](https://user-images.githubusercontent.com/15022396/39277660-7889ce84-48b4-11e8-87a9-7e66cc45433a.jpg)

or even a simple vehicle:

![3591096](https://user-images.githubusercontent.com/15022396/39277729-e5efe03a-48b4-11e8-883d-cee48c340a23.jpg)

This could be the simplest version that can be of use early in a world without technology improvements.

Then maybe you could add powered objects, like coal powered trains, before eventually getting into electricity where you could run a cable like you get in street cars like so:

![1397801_orig](https://user-images.githubusercontent.com/15022396/39277748-0269a6c4-48b5-11e8-86bd-45e76c303412.png)

and of course a way to shift lanes:

![252519_orig](https://user-images.githubusercontent.com/15022396/39277761-0fca276c-48b5-11e8-860c-65db96189de1.png)

If it's done right, it would create an incentive for someone to actually build the infrastructure. Tracks could be owned objects with a fee to use, and instead of power being automatically distributed to all nearby objects, it could allow someone to create an electrical power company to sell power to the rail operator.

The highest build could be a monorail system with the tracks themselves being powered, and really high speeds.

The only real problem I see is how to go about ownership. In my experience, for a sufficiently wide highway, I'd need two side by side parcels claimed per short length and I'd run out very quickly. A random troll could then claim the middle of the track and close the borders shutting down the entire system. 

For that, I think we'd need a mineral rights system where one player can own the land below a point or above a point, as I suggested here:

https://github.com/StrangeLoopGames/EcoIssues/issues/7269
 
Maybe we could have an option for using properly claim flags, where they are worth a larger area if the player choose to either claim just the surface or just the minerals. In that case, when building a rail system or underground highway I could claim just what I need and purchase surface rights only where I will need to go above ground. I could then purchase from land owners rights to dig under their land, and likewise someone only interested in building on the surface could claim a larger area while ignoring the underground such as in a low skill point world where only miners would really be the ones digging like mole men.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#101
