### ISSUE TITLE
Save game backups need to be much more frequent

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7406]
Current rate of 4 hours is too infrequent.
Need rolling backups at expanding intervals.

**Comment by johnkslg** [comment]
Filed by user Jewseph

**Comment by johnkslg** [comment]
Need to address backup saves for single player.

**Comment by Elliander** [comment]
Personally, I make sure to start the backup whenever I shut down the server, but my suggestion here:

https://github.com/StrangeLoopGames/EcoIssues/issues/7334

Would address the problem with single player servers, since it could be a one click setting to save and shut everything down.

I'd also add that there needs to be a way to roll back a backup in the event that an upgrade goes bad. Without such a feature I'd be inclined to copy the entire server folder prior to updating and maintain a manual backup just in case.

**Comment by johnkslg** [comment]
Good suggestion!  Added more frequent backups so closing this one.
