### ISSUE TITLE
Crash looking up slg_id for a blank username

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#7424]
Could not look up slg id for user '': Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden..
   bei Eco.Gameplay.Players.UserManager.AddUser(User user)
   bei Eco.Gameplay.Players.UserManager.GetOrCreateUser(String steamId, String slgId, String username)
   bei Eco.Plugins.Networking.Client.SpawnPlayer(Single viewDistance, String language)

**Comment by MarjieAVolk** [comment]
According to translate: "The underlying connection was closed: No trust could be established for the protected SSL / TLS channel."

This message is going to come either from 'https://ecoauth.strangeloopgames.com/game/useridv2/', or from an exception in UserManager.LookUpId, which calls that web query.

I tried entering 'https://ecoauth.strangeloopgames.com/game/useridv2/' (with a blank username) into my browser, and I got a funky error.  Passing in a fake username gives me a normal '{"error":"User not found."}' response.  So looks like this is web side.

**Comment by MarjieAVolk** [comment]
I mean that's assuming we want to support empty names, which maybe we don't.  This would have been from someone logging in with no steam id, no slg id, and no username, which isn't really that reasonable of a situation.

**Comment by MarjieAVolk** [comment]
Okay so after looking at this a little more...  here is my theory for what happened.  The client has to call Client.Authorize before called Client.SpawnPlayer (we know that it did so because the session object was not null, if authorize had not been called we'd be getting all kinds of null refs instead).  The client must have passed in login info with a blank username, since that's the only place the username comes from.  But when calling UserAuthentication.VerifyToken, most likely the code path that sets the user id and steam id did not get called (unless https://ecoauth.strangeloopgames.com/game/verifytokenv3 returned a successful response with no slg id or steam id, which seems unlikely to me).  The only way that code path can be skipped without disconnecting the client is if https://ecoauth.strangeloopgames.com/game/verifytokenv3 fails and the player is playing on a local world OR has require authentication turned off; so they would have had to meet one of those conditions in order to bypass the error handling there.

So if that's all true, the issue in this case would still be that the client passed in an empty username and possibly a bad auth token.  But the problem didn't get caught until much later than usual because of our attempts to support auth servers being down.

In terms of why the client is passing in an empty username.... It kinda looks like the only way that could happen is as a response from https://ecoauth.strangeloopgames.com/game/responsev4 (or potentially as a response from the steam API, but several independent steam API calls would have to return bad values without throwing an exception, which seems unlikely).  We would be passing in a guaranteed non-null username and password to responsev4.  But we don't really have error handling for this call, so if the call errored out for some reason, it looks like we might just happily pass along the null information.

It's starting to look like... the auth servers may actually have been down?  It may be the case that while auth servers are down, when logging in for the FIRST time on a new server, this will always happen.  I am not sure if we should do anything about this, because creating a new user with no ids on it has already caused us endless problems, and I do not think we should knowingly do it, which would be the only alternative to erroring out if we get to this point and have no ids.

**Comment by MarjieAVolk** [comment]
So think I'm gonna close this as won't fix... unless we get lots more reports of it.

Another explanation of course is hacking of some kind, for the client sending bad info, didn't mention that earlier.
