### ISSUE TITLE
Many players filling same profession

### ISSUE THREAD

**Issue by ECO34RT** [StrangeLoopGames/EcoIssues#7433]
Too many people are filling the same profession.
This leaves players out of the economy with no income.
It should be quick and easy to change professions because currently you have to wait a long time for your skill points to increase again.
I think the 50% skill point refund should be 100% because it is hurting players who are left competing with too many other players that come along and open the same shops as you.

**Comment by pamduncan** [comment]
You can adjust the skill point cost of the refund down to 0 if you want.  That is done Difficulties tab or .eco config file and it has been an option since the Difficulty settings were added..  We have a 1.0 cost set on several servers we have for new players starting out.  On other servers we have 0.0 set so they get nothing back.  The admin can set this as they desire, 

People have asked that there be a way admins could set how many of s skill could be in a world, and I don't know if that is a good idea or not.  I would think community and economic pressure would dictate that and people might not like being forced into certain skills by a setting the admin makes.  On the other hand I can understand admins of more closed communities wanting that to make sure the community balances well...

But as it is you can make it not hurt at all to refund if that is what the admin and community want.

**Comment by ECO34RT** [comment]
Hey,

Thank you for your reply.
It's good to know that there is an option for the server admin to change the skill difficulty.


What I would love to see is a new game mode for ECO.
Players would have the ability to research, craft and build all objects in the game by themselves. Basically it would play similar to Minecraft but with an ecosystem and beautifully detailed graphics which ECO does really well.

I am not aware of any block based sandbox game out there that bridges the two ideas together.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#99
