### ISSUE TITLE
Gameplay realism - randomly-crated map borders

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#7445]
From our forum: http://ecoforum.strangeloopgames.com/topic/4524/game-play-realism

"MX posted about 12 hours ago  0 
Would like to see a version of this game where as when the world is generated it creates borders for different countries that are claimed by teams that end up being governed differently as I believe this would better simulate our own world ECO system and the effects different individual countries have on the world."

**Comment by Elliander** [comment]
This would actually be very interesting on a large world, allowing for more than one government and economy to form, and can introduce new elements of realism such as what to do if a neighboring country is heavily polluting due to a lack of environmental laws that your nation has.

Of course, logically, if this were to happen it would lead into being a cooperative real time war SIM before long unless there was a cooperative model to deal with such issues.

**Comment by BlazeGuy2** [comment]
This issue was moved to StrangeLoopGames/EcoSuggestions#97
