### ISSUE TITLE
Vehicle not appear to certain player

### ISSUE THREAD

**Issue by Twelve57** [StrangeLoopGames/EcoIssues#7454]
Hi ! 
I've checked a bit with the search function but apparently no one has already report this issue, but it's an old one.

Vehicles : All.
Sometimes (often/always in a mine) when a player try to join another one by driving with a vehicle to the other player location, we figure it out that the other player doesn't see the vehicle.
For example, you mine with your friend, you do all the transport with the cart during your friend is mining. Sometimes when you go back to him (to fill the cart with stone) your friend doesn't see the vehicle !
The only way to counter that we've found is to disconnect and then reconnect. (when you're not stuck on Entering World...)
But yeah it's very annoying to do that each time because you cannot see the Cart. 
With that, it brings a lot of "small disasters" inside our society, invisible cars are dangerous for pedestrians haha ! 😆

**Comment by mindforger** [comment]
not only the cart sometimes a player becomes stuck and is standing somewhere for others while he can move freely, after a reconnect he spawn atthe location where he was standing for other players instead of where he logged off ... maybe this is tied together ... it always feels like a desync in minecraft for example when the server can not deal with the player moving anymore but the playerclient can still move around freely

**Comment by SeanAtr0n** [comment]
Fixed 7.4.5
