### ISSUE TITLE
USER ISSUE: Falling Forever

### ISSUE THREAD

**Issue by TheDestroyah44** [StrangeLoopGames/EcoIssues#7470]
**Version:** 0.7.3.3 beta

**Steps to Reproduce:**
Wait for half of world map to disappear. Step off ledge

**Expected behavior:**
Half the world should still exist

**Actual behavior:**
The dark accepted me into a giant freefall, for which I fell +250km into oblivion

**Comment by Elliander** [comment]
I encountered this problem in 7.3.3 as well and isolated the cause - at least in my case. It's somehow related to setting the view distance high. When I do, I'll have holes in the map appear - seemingly at random - but they only seem to occur where I recently did some kind of change to the map, like cutting down a tree. Fixing the issue is as simple as changing the view distance to minimum briefly and then back up again to reset what's loaded.

I also noticed that this is more likely to occur on taller maps where you can see more of the landscape from a distance. It causes things to load and unload in a weird way as to result in the entire map being fragmented in appearance, so maybe there's some kind of limit to how many blocks can load and then the recently changed blocks that are closer ends up falling off?

This is the kind of issue that I think could be solved by allowing the entire world - or at least a representation of it - to remain loaded in memory at once if you have the RAM to support it, as I described here:

https://github.com/StrangeLoopGames/EcoIssues/issues/7409

**Comment by metachronism** [comment]
sean fixed this a while back
