### ISSUE TITLE
Russians blocking Eco

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#7496]
**Version:** 0.7.4.0 beta staging-68e3874b

**Steps to Reproduce:**
Launch game.
Try to add server to favorites, try to see servers in server browser, try to connect to friend trough steam

**Expected behavior:**
Succeed.

**Actual behavior:**
Nothing. Work only singleplayer.

p.s.
On 0.7.3.3 all works fine.
Adding to favorites, server browser, connect to friend.
Return to 0.7.3.3 on all these users, fix this issue...
Back to 0.7.4? Bug here, again.
Cleaning settings in %appdata%, clean reinstall, disabling antivirus software\firewall is not helped.
https://ecoauth.strangeloopgames.com/game/serverlist - available. (52.38.104.243)

I have six Russian users with identical issue...

If you need additional info - say me what you need.

**Comment by elfl0rd** [comment]
0.7.4 uses new masterserver, masterserver.eco.strangeloopgames.com (54.213.175.208) correct?
They partially blocked in Russia by Russian government :(
https://blocklist.rkn.gov.ru/
![default](https://user-images.githubusercontent.com/4980243/39448611-17a99a72-4cce-11e8-8acb-b15f749a8e71.png)

**Comment by johnkslg** [comment]
Russians blocking Eco, reducing high priority because its a regional thing that needs to be appealed

**Comment by elfl0rd** [comment]
@johnkslg but...
Unavailible masterserver, ruine network game, even if you know server ip.
It's not right :(
Please allow direct connection (old stule) using ip:port, and\or allow use proxy to connect to masterserver!

**Comment by thereporter42** [comment]
This info comes from another ticket but since I am sure the other one will get closed
i will post the information here since it does have some intresting information that
i found out. 

https://github.com/StrangeLoopGames/EcoIssues/issues/7663

Since when would this be an issue with Stangeloop Games. IF your ISP is blocking the master server to connect to for the server list then maybe you should call your ISP and complain to them.

I am not having any issues here in North America.   I don't see why you posted this here this 
is an  Internet Service Provider issue or a country issue in Russia only if they are blocking
them then complain to them not Strange Loop games. 

Call your ISP and complain to them if thy are blocking the IP and find out why.

If it the Russian Government blocking the IP then well maybe you
should contact some one in your government and find out why.

I did a bit more digging and found more info: 

Also this was addressed in ticket #7496

https://github.com/StrangeLoopGames/EcoIssues/issues/7496

"0.7.4 uses new masterserver, masterserver.eco.strangeloopgames.com (54.213.175.208)"

https://blocklist.rkn.gov.ru/

English translated version of this page: https://tinyurl.com/yaen5emb

"Through the form published below, you can obtain data on measures taken to restrict access to sites and / or pages of Internet sites within the framework of meeting the requirements of Articles 15.1-15.6 of Federal Law No. 149-FZ of July 27, 2006 "On Information , information technologies and information protection "

When I enter that IP 

It comes back with the following

Russian: 




Статья основаниявнесения в реестр | Реквизиты основания внесения в реестр(орган принявший решение, номер, дата) | Ограничение доступа
15.3 | Генпрокуратура27-31-2015/Ид4082-15 04.12.2015

Translated English: 




Searched for: 54.213.175.208
Total records found: 1

We draw your attention that the presence of the Internet site in the Registry does not at all mean full restriction of access to it, since access can be limited to a separate page of the site in the Internet. The locking method is reflected in the "Access restriction" column.

Founding Article
Requisites for registration in the register
(decision-making body, number, date) Restriction of access
15.3 The Prosecutor General's Office
27-31-2015 / ID4082-15
12/04/2015

so it looks like the Russian Prosecutor General's Office is the one responsible for 
the block.  I would contact them to find out why. now they refer to section 15.3 

https://blocklist.rkn.gov.ru/article15-3/

English Translation: https://tinyurl.com/y8q2wy3r

"On February 1, 2014, Article 15. 3 of the Federal Law of July 27, 2006, No. 149-FZ "On Information, Information Technologies and Information Protection" came into force.

This legislation regulates the procedure for restricting access to sites on the Internet, containing information with calls for riots, carrying out extremist activities or participating in mass (public) events conducted in violation of the established procedure.

Roskomnadzor organizes restrictions on access to such information on the basis of the demand of the Prosecutor General of the Russian Federation or his deputy. "

The Prosecutor General's office website in English is located at 
https://eng.genproc.gov.ru/

Prosecutor General’s Office of the Russian Federation
Bolshaya Dmitrovka, 15a GSP-3, Moscow 125993 RUSSIA
Phone #: +7 (495) 987-56-56
Website: https://www.genproc.gov.ru/

Maybe the Russian Government would be happy is Strange Loops Games put a flag pole and 
a Russian Flag in the game so you can raise the Russian Flag every day :) 

I would be very careful getting involved in this matter Strange Loop Games this 
sounds like a very political issue with this country.  any assistance in helping
them bypass this block may put Strange Loop Games in some very hot water. 

I would seriously have a lawyer speak to them that represents Strange Loop Games
I would not want to mess with the Prosecutor General's Office for the Russian Federation
they don't seem to have much of a sense of humor over there.

**Comment by elfl0rd** [comment]
@thereporter42 apellation can take LOT of time, change ip is really faster way.
(But yes, they written and sended.)

**Comment by thereporter42** [comment]
LOL telegram what the heck are you talking about using a VPN would bypass the blockage 
because the packets are encapsulated it is the answer to your problem.

Connect to a free VPN and you can easily get around the block. 

Please don't say it isn't the answer because it is.  Telegram isn't ON that IP
address nor are any of their servers. 

A VPN would get you a round the blockage.  I have been doing this for YEARS 
probably long before you were even born. Try it.. it will work!

**Comment by elfl0rd** [comment]
thereporter42
Please stop spamming, vpn is not answer, they require action from all users.
(If you still promote vpn, go to #русский in discord and help users with this issue.)
Change ip - require action only from dev and fix issue to all.

**Comment by elfl0rd** [comment]
Masterserver ip changed, to another blocked ip :D 
35.163.80.53

**Comment by thereporter42** [comment]
elfl0rd you and the rest of the Russian players refuse to do anything to try and help yourself. 
The IP has changed  for the master server masterserver.eco.strangeloopgames.com to IP 
35.163.80.53

I am also in no way spamming I am responding to the ticket which I am allowed to do. 

And yet you still complaining about the IP being blocked. Once again this is why I said before
that changing the IP is not the answer the Russian players here refuse to try and do anything
to help themselves they refuse to use a VPN to get around the block even though it would work. 

I believe elfl0rd is either just a kid or really has very little clue about computers. 

Bottom line is it is time for the Russian players to s tart to try and help themselves 
a VPN would work and you can use steam using a VPN because i have done it. 

Basically the issue is the Russian Government which seems to think that censorship
is the answer to everything. 

This is an issue with the Russian Government go complain to them there isn't
much more that Strange Loop Games can do they changed the IP from 54.213.175.208
to 35.163.80.53 and yet you are still complaining about it being blocked. 

There are only a very small number of Russian players on this game anyways.

at this point try my suggestion of a VPN or stop complaining here please! 
It is time that you take action to do something to fix this issue. 

You have an option available to you being a VPN so try it at least!

**Comment by elfl0rd** [comment]
> I believe elfl0rd is either just a kid or really has very little clue about computers.

I consider the further conversation with you useless.

**Comment by MarjieAVolk** [comment]
Let's keep it civil please.  No personal insults.  Also there is no need to argue about how important this issue is, we will address it as we see fit.

**Comment by elfl0rd** [comment]
> Let's keep it civil please. No personal insults. Also there is no need to argue about how important this issue is, we will address it as we see fit.

Thx! They say about "small" ru players quantity with this issue, But.. I stop 90% it from writting identical issues here, to prevent spam.

**Comment by elfl0rd** [comment]
Unlocked, closing.

**Comment by MarjieAVolk** [comment]
Woah it's not blocked anymore?

**Comment by elfl0rd** [comment]
Only your forum :D
