### ISSUE TITLE
USER ISSUE: 7.4 SLG id broken?

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#7546]
**Version:** 0.7.4.0 beta

**Steps to Reproduce:**
Play 7.4 w/ slg id

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
Failed to login

Unexpected character encountered while parsing value: <. Line 2, position 1.
```

<details>
<summary>Log File</summary>Initialize engine version: 2017.4.0f1 (b5bd171ee9ba)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   NVIDIA
    VRAM:     2997 MB
    Driver:   23.21.13.8813
Begin MonoManager ReloadAssembly
- Completed reload, in  0.036 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

The referenced script on this Behaviour (Game Object 'Camera') is missing!
 
(Filename:  Line: 1758)

WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [Double Sided]' - All passes removed
Setting up 6 worker threads for Enlighten.
  Thread -> id: 1227c -> priority: 1 
  Thread -> id: 17ab4 -> priority: 1 
  Thread -> id: 798c -> priority: 1 
  Thread -> id: 196c -> priority: 1 
  Thread -> id: 17fbc -> priority: 1 
  Thread -> id: 152fc -> priority: 1 
UnloadTime: 3.342226 ms
Client version: 0.7.4.0 beta
Tuesday, May 01, 2018 1:59 PM
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/.\libc
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/Eco/Eco_Data/Mono/libc
RPC lookup took: 8213.8731ms
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: PreLogin -> LoggingIn
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Changing state: LoggingIn -> PreLogin
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

</details>

**Comment by thereporter42** [comment]
Getting the same on a 7.3.3 Beta server as well..  Same error message

https://github.com/StrangeLoopGames/EcoIssues/issues/7547

Version: 0.7.3.3 beta 

Steps to Reproduce:

1. Select User name and enter your user name 
2. go to the password field and enter your password 
3. press the login button 

Expected behavior:
A valid login response and being able to log into the game

Actual behavior:

I get a window that pops up with the error message 

"Failed to login Unexpected character encountered while parsing 
value: <. Line 2, position 1." 

I have tried this with two separate accounts and get the same error message
on both.  This is occurring around 5:43 PM MST (GMT-0700) on May 1 2018 
I was on the the  server I play on earlier today around 2:30 PM today and I was 
able to log in fine so I am suspecting that this is something on the server side. 

I am using the same password as I always have and have not changed it or anything
recently. 

This is the server I am playing on 

http://104.192.227.90:6005/index.html?
https://ecoservers.io/server/3765/

![eco unexpected character encountered may 1 2018](https://user-images.githubusercontent.com/38896397/39498815-99dfe9c6-4d67-11e8-88fb-71ab5214cbae.jpg)

**Comment by SeanAtr0n** [comment]
was just fixed
