### ISSUE TITLE
MASTERSERVER IP BLOCKED IN RUSSIA

### ISSUE THREAD

**Issue by mizantrop777** [StrangeLoopGames/EcoIssues#7663]
[RU]
пожалуйста, смените ip адрес мастерсервера, он заблокирован в России, поэтому не видно ни один сервер
[EN]
please change the ip address of masterserver, he is locked in Russia, so do not see any single server

**Comment by thereporter42** [comment]
Since when would this be an issue with Stangeloop Games. IF your ISP is blocking the master server to connect to for the server list then maybe you should call your ISP and complain to them.

I am not having any issues here in Canada.   I don't see why you posted this here this 
is an  Internet Service Provider issue or a country issue in Russia only if they are blocking
them then complain to them not Strange Loop games.

**Comment by mizantrop777** [comment]
there are two options: write to the developers of the game in Roskomnadzor, or change the ip address. If no one does anything - the game is useless in Russia

**Comment by Last2Night** [comment]
Im curious how popular ECO is in Russia... whether its worth the hassle for devs to get involved legally in that mess, after all its not devs fault the IPs are blocked.

**Comment by thereporter42** [comment]
Well no you need to contact your Government mizantrop777 and have them remove the IP from 
their block list.  this is a Geo-political thing that Strange Loops game shouldn't get involved in
your country has blocked the IP  and you need to contact them to find out why. 

If it wasn't for the Russian Government blocking the IP everything would be fine. 

This issue was already dealt with in ticket #7496 so why is this been set with a critical priority
when it is already open in ticket #7496

I would agree with Last2Night it isn't Strange Loop Game's fault that your country 
is blocking the IP. 

Now if you really want to get around the block then try using a VPN there 
are several free ones out there. 

https://tinyurl.com/yajceoaa

https://www.vpnmentor.com/
https://www.tunnelbear.com/
https://windscribe.com/
https://www.hotspotshield.com/
http://speedify.com/
https://account.protonvpn.com/signup

**Comment by mizantrop777** [comment]
this ip was blocked in 2015. so it is unlikely that the lock has to do with ECO. Most likely, the developers just got a server with this ip.

I have already written to Roskomnadzor, but there is no answer yet. It'll be a long time, birocracy. As I said, it will be easier and faster for developers to change ip

VPN-not the solution for a number of reasons (for example, on my PC the heap of servers of different games is started, I have a static ip)

**Comment by thereporter42** [comment]
LOL yes it is mizantrop777 it sounds to me like you are not willing to try anything to even
get around the block. 

This isn;t an issue with the game this is an issue with your country blocking the IP so
either appeal it with your government or use a VPN to get around it.

Have you even tried a VPN yet because it will work I have been doing this
a heck of a lot longer than you have and I am a trained Network Admin.

The way the packets are encapsulated for the VPN traffic will get you around
this block.

they are not going to change the IP it is working everywhere else in the world
except Russia and it is because of your government blocking it.

LOL saying that the VPN isn't the answer because you have a static IP shows
how little you really know about a VPN and how he traffic is routed.

When you connect to a VPN the packets of data are encapsulated 
and it it will get you around the block also your IP changes as well
when connected to the VPN. 

The most important part is that the packets for a VPN are encapsulated
and 

It sounds like you don't even want to try anything to get around this
and fix this issue and are just demand Strange Loop Games to change
the IP. 

It works everywhere else in the world this is an issue with just Russia! 

Try other things like the VPN first to get around the block or stop complaining
here.

**Comment by mizantrop777** [comment]
do you offer all users from Russia (of which many can not even install windows) to use vpn? ridiculously...

**Comment by elfl0rd** [comment]
Another vpn problem - steam regional restriction.
You cant use lot of your games if you use vpn.

**Comment by thereporter42** [comment]
See this is exactly why I said that changing the IP is NOT the answer...  you need to contact your government and have them remove the listing.  

The IPs being used by Strangeloop games works fine everywhere else in the world
except Russia who is blocking the IPs. 

Also you can use steam using a VPN that is  incorrect elf0rd I have used steam before 
using a VPN. 

It isn't ridiculous at all either mizantrop777 that I am telling you to use a VPN.

What is ridiculous is the Russian Government who thinks that censorship is 
a good thing. 

Go complain to your government the IPs being used works everywhere else in 
the world. IT seems that there is only a small number of Russian players on this game
anyways. 

It seems that you are just going to demand that Strange Loop Games
change the IP and you are not even willing to try anything like a VPN
to get around this block. 

The Russian players like you elfl0rd and mizantrop777 are the ones that
are ridiculous.

The master server  masterserver.eco.strangeloopgames.com  is now at 
IP 35.163.80.53 (Amazon.com) 

The IP has changed and yet you are still complaining.  It is time that
the Russian players actually helped themselves and tried my suggestion
of a VPN.

**Comment by elfl0rd** [comment]
thereporter42, stop flood please.
Learn more info about steam regional restrictions based on prices in different counties.
And vpn is really not answer, more than 100 players have this problem. You want to learn it all about vpn?
And apellation written, but rewiew can take more than 60 days.

**Comment by mizantrop777** [comment]
@thereporter42 "The master server masterserver.eco.strangeloopgames.com is now at
IP 35.163.80.53 (Amazon.com)"

Amazon.com!!! 
there is a telegram, because many ip blocked. and they're not unlocked. the fact that github few people write-it does not mean that there are no players from Russia. at that rate - they will not be exact.

VPN shove itself far any away, we want normal game, without crutches and Bicycle.

**Comment by thereporter42** [comment]
And yep when i go to https://blocklist.rkn.gov.ru/ and enter 35.163.80.53
it is blocked. 

![russian block ip 35 163 80 53](https://user-images.githubusercontent.com/38896397/39945281-2b9ab596-5527-11e8-8610-0e4f586a26eb.jpg)

Once again try my suggestion if you are not willing to try anything then maybe
you should just go find another game. 

Once again Strange Loop games changed the IP and you are still complaining
at this point you need to get your government to remove the block and wait the 
time. 

You have no clue what you are talking about either when you are talking
about a VPN. 

There are only a small number of players on here from Russia
take some steps to help yourself!

**Comment by mizantrop777** [comment]
@thereporter42 http://www.mk.ru/politics/2018/04/16/internetu-konec-roskomnadzor-zablokiroval-milliony-ipadresov-amazon-i-google.html

I represent Russian hosting, we planned to deploy rent of servers and the corresponding advertizing. Your messages are informative and do not carry an adequate solution, so please do not respond, as VPN to thrust himself to hell.

**Comment by thereporter42** [comment]
LOL Mizantrop777 no you are not .. now you are claiming to deploy servers before you were just a player who was playing on a server do not try and lie.  I am sick of these Russian players refusing to do anything to help themselves. 

I am trying to help them and they refuse any advice given to them can a staff member of Strange Loop Games please just close off this ticket.  They have options and they refuse to take them.

**Comment by mizantrop777** [comment]
@thereporter42 https://hosting.alkad.org
@thereporter42 you in ignore

**Comment by elfl0rd** [comment]
Masterserver mirror is UP.
Now in testing state.

**Comment by thereporter42** [comment]
LOL anyone can link a site doesn't mean that is yours.. wow these Russians are just rude..  If you are hosting a server why not talk to the devs and see if they can put up your own master server in Russia for servers
based in Russia then... LOL

**Comment by elfl0rd** [comment]
Masterserver mirror working all weekend without any problem with >10 users
More information sended to Metachronism DM

**Comment by eliotcougar** [comment]
Masterserver is unavailable again... Looks like the traffic goes in circles... I'm having the similar issues with some other services hosted on Amazon even when I'm using VPN...

Traceroute:
masterserver.eco.strangeloopgames.com [35.163.80.53]

  1    <1 мс    <1 мс    <1 мс  [redacted]
  2    <1 мс    <1 мс    <1 мс  [redacted]
  3     4 ms     4 ms     4 ms  [redacted]
  4     3 ms     3 ms     4 ms  [redacted]
  5     4 ms     3 ms     4 ms  [redacted]
  6     5 ms     4 ms     4 ms  [redacted]
  7    22 ms    22 ms    22 ms  80-64-96-225.rascom.as20764.net [80.64.96.225]
  8    22 ms    22 ms    22 ms  80-64-96-225.rascom.as20764.net [80.64.96.225]
  9    22 ms    22 ms    22 ms  be4338.ccr21.sto01.atlas.cogentco.com [149.6.168.137]
 10    22 ms    22 ms    23 ms  be3376.ccr21.sto03.atlas.cogentco.com [130.117.50.225]
 11    38 ms    38 ms    38 ms  be2281.ccr41.ham01.atlas.cogentco.com [154.54.63.1]
 12    50 ms    50 ms    51 ms  be2815.ccr41.ams03.atlas.cogentco.com [154.54.38.205]
 13   201 ms   201 ms   201 ms  be12194.ccr41.lon13.atlas.cogentco.com [154.54.56.93]
 14   201 ms   201 ms   202 ms  be2982.ccr31.bos01.atlas.cogentco.com [154.54.1.117]
 15   205 ms   206 ms   204 ms  be3471.ccr41.jfk02.atlas.cogentco.com [154.54.40.154]
 16   205 ms   205 ms   205 ms  be2806.ccr41.dca01.atlas.cogentco.com [154.54.40.106]
 17   205 ms   205 ms   206 ms  be2112.ccr41.atl01.atlas.cogentco.com [154.54.7.158]
 18   201 ms   201 ms   202 ms  be2687.ccr41.iah01.atlas.cogentco.com [154.54.28.70]
 19   201 ms   201 ms   201 ms  be2927.ccr21.elp01.atlas.cogentco.com [154.54.29.222]
 20   206 ms   205 ms   205 ms  be2929.ccr31.phx01.atlas.cogentco.com [154.54.42.65]
 21   204 ms   205 ms   205 ms  be2931.ccr41.lax01.atlas.cogentco.com [154.54.44.86]
 22   201 ms   201 ms   201 ms  be3271.ccr41.lax04.atlas.cogentco.com [154.54.42.102]
 23   203 ms   210 ms   201 ms  38.88.196.90
 24     *        *        *     Превышен интервал ожидания для запроса.
 25     *        *        *     Превышен интервал ожидания для запроса.
 26     *        *        *     Превышен интервал ожидания для запроса.
 27     *        *        *     Превышен интервал ожидания для запроса.
 28     *        *        *     Превышен интервал ожидания для запроса.
 29     *        *        *     Превышен интервал ожидания для запроса.
 30     *        *        *     Превышен интервал ожидания для запроса.

**Comment by elfl0rd** [comment]
you are using my proxy, try direct.
Masterserver ip in unblocked range.
My proxy est work for next ~1week.

**Comment by elfl0rd** [comment]
Masterserver available, and masterserver range is unblocked.
Try direct connection?

**Comment by eliotcougar** [comment]
@elfl0rd I know it's not blocked anymore... That's why this traceroute is strange... Can't ping it either...
Similar things happen with some other services unrelated to ECO: Traceroute reaches Amazon and after that it's all "request timeout"... The same happens when I use any remote traceroute webtools...

**Comment by metachronism** [comment]
sorry comrades, we dont yet have the power to influence the russian govt :/
However its not blocked now, so closing this out
