### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by Booza95** [StrangeLoopGames/EcoIssues#7693]
**Server, Client or Website?**

Server/Client

**OS/Web Browser?**

Windows 10

**Detailed Description of Issue:**

Fee's that are put in place for machines are being waived because the people using it are authorized whether it's on whitelisting or set to public.

**Reproducible? How difficult is it to reproduce?**

quite easy.

**Steps to reproduce bug/issue:**

1. Set up a machine 
2. Setup fees for others to use
3. Let the others use it.

**Additional Comments:**

Authentications over all seem to have been messed up with the recent 7.4 update, people are able to hammer any machine owned by Person A, on Person A's claimed land as long as they have permission to use the machine.

P.S: The message is sent for the owner of the machine only.

**Client Version? [Alpha .01 for example]**

7.4.1

[image of what we get when we setup a fee and someone uses the machine.](https://cdn.discordapp.com/attachments/178472431634087937/444199436470714379/unknown.png)

**Comment by Booza95** [comment]
hey, thanks for helping out.

Yeah it happens to everyone on the server. Only the owner of the machine gets notified. When i buy something from a shop i do get taxed and get the messaged about it.

But when i use a refinery for my case i didnt get any message, but the owner of the refinery got the message attached in the image.

**Comment by MarjieAVolk** [comment]
Hm well I tried with a Refinery too, and it is still charging me the fee as expected.  Do you have the same problem on other servers?  Maybe it is related to your save?  Do you have any mods installed that might be affecting it?

**Comment by Booza95** [comment]
hmm, not really sure if its the save. and i havent tried on other servers.
We are currently playing pure eco vanilla, no mods or anything but we do have some tweaks for the point income.

**Comment by MarjieAVolk** [comment]
Okay, that shouldn't affect it.

**Comment by MarjieAVolk** [comment]
Hm, well it really should be checking the authorization on the property.  Okay here's another thought - refineries are pretty big.  Is it possible that this refinery is halfway on and halfway off the property?

**Comment by Booza95** [comment]
![image](https://user-images.githubusercontent.com/26549422/39914807-3268d6e2-5517-11e8-8426-e168ca72d8e7.png)


It is definitely in the claim. maybe you can try and join our server and see if you can figure something out?

**Comment by MarjieAVolk** [comment]
Actually it would be better if you could send me your server's Game.eco save file, so I can run it in debug here.

**Comment by Booza95** [comment]
https://cdn.discordapp.com/attachments/188326370848276481/445890792691597312/ecoworld.zip

if you go ahead and download that, thats the most recent file we got on our server.

**Comment by MarjieAVolk** [comment]
Okay, I loaded up your world, went to the oil refinery, ordered a project, and it wouldn't let me because I didn't have enough money for the fee.  Cheated myself some money for the fee, tried again, and it charged me the fee.  I also tried this while logged in as a random existing player on the server, and it worked.

So.  Seems to be working over here.  The only thing I can think to check would be to log in as someone who definitely has this error - If you have it, then what is your username in this server?

But it seems likely that either the problem only happens sometimes, or the problem is related to your server and not to your save somehow.  Does a server restart make the problem go away?  Do you have any mods?  Have you changed any settings on your server that might be related to this?

**Comment by MarjieAVolk** [comment]
Okay good to hear, thanks!
