### ISSUE TITLE
path to void

### ISSUE THREAD

**Issue by TheNitrogen** [StrangeLoopGames/EcoIssues#7721]
Eco oficial testing server 7.4.2
https://www.youtube.com/watch?v=9D4Uso7xX-8

**Comment by TheRealMaxion** [comment]
Seen this too. Much like in minecraft, it's what happens if one or more chunks fail to load.
Trying to walk into it leads to infinite falling until it eventually loads (the falling sound gets pretty intense after a while), usually better to stand around looking at the missing area until it loads, which can take a while. Would love to see this fixed somehow.

**Comment by surcoufx83** [comment]
I have this on my private server too.

**Comment by SeanAtr0n** [comment]
will be fixed in 7.4.5
