### ISSUE TITLE
Can't join friends server ever since i pressed "C"

### ISSUE THREAD

**Issue by Boyjedi** [StrangeLoopGames/EcoIssues#7728]
So i was in my friends server, and i pressed "C", so when i first pressed it my game froze, then crashed. After when i restarted eco to rejoin my friend it stops at Entering World . . . and then freezes! It is just me because my other friends can join him and i can join other's servers. I deleted the game completley, uninstalled and re-installed
I need help i want to play ECO again. 

Thanks!|
![eco 5_11_2018 8_49_00 pm](https://user-images.githubusercontent.com/7998585/39951923-c565e508-555c-11e8-9da5-f66591dcb334.png)

**Comment by MarjieAVolk** [comment]
Sounds like deleting the folder 'C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO' might help you.  This will reset all your local preferences, but won't lose you progress in the game.  Since you've re-run the game several times at this point, I'm guessing you don't have any logs left that might help determine what happened 🤔 But if you don't mind, if deleting that folder does help, could you send over the contents of the folder, so I can look for bad state in it?

**Comment by MarjieAVolk** [comment]
Ah, I just realized this is the same as https://github.com/StrangeLoopGames/EcoIssues/issues/7736 - Closing this one as a duplicate, but do let me know if that helps.
