### ISSUE TITLE
Force the server to save Network.eco if the password isn't encrypted

### ISSUE THREAD

**Issue by UnknownViper** [StrangeLoopGames/EcoIssues#7730]
Currently if you have added a password through other means than the server software, it will remain as plain text in Network.eco.
Couldn't the server be made to save Network.eco with the encrypted password, if one is detected and it's not encrypted?

**Comment by pamduncan** [comment]
The problem with that is then the admins with direct server access cannot even see what password is set on the server.  Plus if the hash is in the password field it becomes the password.  That happens now and causes major issues on servers/  If you do a File>Save to save any changes made in the Server UI to your configs it then saves the hash to Network.eco file and the hash becomes the password.  Then next reboot the hash iss the password and if your players are not white listed they are unable to log in unless you go back and edit Network.eco and put in the password again and restart the server,  To be very honest I have multiple servers and often have to check that config file to remember what password has been set.  Since a person would need access to the server itself to see that config file its not like it that much of risk.  As it is difficult having the Server UI hash the password and I am not sure why that is even done as you would have to have server login information to even view the server UI,  It has actually made server administration much more difficult having that password hashed.  The argument here, I assume, is security of the server.  If you are leaving things so wide open that anyone can get on and see the password, those people also have access to change any setting in either server UI and/or a config file or files and even shut down the server and/or delete it.  That password security should be at a much higher lever - at server login itself and not trying to protect something after the door is already left open.  If someone is going to leave their server so insecure that anyone can log on and view the password, then there server is at a great deal more risk than someone getting a password to log on the game.

**Comment by UnknownViper** [comment]
Oh, I see - so it's actually kind of a problem if the hashed password gets saved to the file. Then it's certainly not ideal to save it. I just assumed it wouldn't be the case, and that the actual password would still be the password, even when saved to the file.

So in other words the hashing is merely for communication between the client and server, and the password should remain as plain text in Network.eco.

**Comment by MarjieAVolk** [comment]
Server passwords are fixed up in the next hotfix
