### ISSUE TITLE
World layers not wrapping correctly on webpage

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#7783]
![image](https://user-images.githubusercontent.com/6262198/40083259-769795c2-5848-11e8-8bbf-6c101b83e09f.png)

**Comment by SeanAtr0n** [comment]
not easy to fix, webgl 1.0 requires power of 2 textures to use texture wrapping

**Comment by beastyn** [comment]
9.0 
still actual
![bandicam 2020-01-23 12-03-01-057](https://user-images.githubusercontent.com/27898520/72963281-a3e2c700-3dd8-11ea-8e32-a90531f06f4c.jpg)

**Comment by denysaw** [comment]
Sorry, but sadly it's a GameServer issue (btw, TextureLoader wasn't changed from Feb 24, 2017 (git history). Example:
![image](https://user-images.githubusercontent.com/5720101/80034998-8c0e0280-84ef-11ea-9185-a8f82d608e44.png)

I've saved gif-layer and opened it with usual image viewer. As we see there's no smooth alpha-gradient of the layer on top, so surely sharp-ending bottom part of the layer will be so perfectly seen by the eye on the map. Globe shows ideally what it was given to show. Re-assigning the issue.

**Comment by gzatravkin** [comment]
The gradient is not part of gif, it's part of heat map mechanic. Each pixel from gif (as can you see in your screenshot) is surronded by color gradient: from white to orange to red to blue to dark. 

And this gradient wasn't working at edges of map. Fixed in https://github.com/StrangeLoopGames/Eco/pull/6843 by JS changes

Attaching illustration after and before fix. 
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/349cc06a-2c28-429c-8d53-26aeda6d4597)
![image.png](https://images.zenhubusercontent.com/5ee8f9e511fef00acff64193/52e26692-c403-4442-965b-ee144e8494fa)

**Comment by j3fffff** [comment]
w00t
