### ISSUE TITLE
Sea-level rising perf is bad - Server using over 20GB RAM suddenly

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#7834]
World is a 200X200 and averages 3-4 GB RAM with average of 15 players on it daily.  Last night due to high air pollution the sea water started rising ver quickly and RAM shot through the roof.  We are over 20 GB at this time and going up:  https://www.dropbox.com/s/n7jg3bs9oxjjs8e/Game.eco?dl=0

**Comment by pamduncan** [comment]
Per JohnK set it so oceans don't rise,  and disabled the sea level.  I also increased the plants consumption of CO2 just to get that cleared for now and the world is now sitting between 4-5 GB RAM usage with more players then when it was at 21GB so okay for now but its a bit startling what happens to RAM when the seas gets high

**Comment by neyna** [comment]
We had the same problem on our server. When sea level rises, the server gets very laggy (sometimes we were forced to restart it). And after a couple of days, the server started to eat 30 GB of RAM.

**Comment by SeanAtr0n** [comment]
So the reason why flooding was occurring on most servers is fixed in 7.4.6 and flooding won't fight with itself forever like it did previously but it still performs very poorly while the climate sim is doing the flooding.

There is still some air polution propagating on servers previously affected like this so sea levels will continue to rise for a little while after updating. You should probably disable flooding until it dissipates.

I'll leave this bug open as a general 'sea level rising performance is bad' bug

**Comment by SeanAtr0n** [comment]
Note, you might want to leave flooding enabled for a bit if your world looks like this: It'll smooth out if you let it run through a few ticks
![image](https://user-images.githubusercontent.com/774628/40568684-06795c80-6031-11e8-9aba-f4e37c9d3385.png)
