### ISSUE TITLE
Cap text size on signs

### ISSUE THREAD

**Issue by gnedge** [StrangeLoopGames/EcoIssues#7864]
every sign on my server bugged out this morning and set `<size=50000>`causing hundreds of giant letters to appear all around the world.  Please cap or remove the `<size>` option on signs to prevent griefing and mistakes.

**Comment by cazrea** [comment]
Can confirm, look at this large "r" and another letter floating on top of it:
https://i.imgur.com/q4nSh5z.jpg

When you walk close to it, it has a solid color so you can't see the block behind it.
Side 1: https://i.imgur.com/TEu5dHG.jpg
Side 2: https://i.imgur.com/LZBHFJO.jpg

You can see that that the other side isn't visible. I found the hole and didn't fall in, but someone could easily have. I was patching it up when I took the screenshots. 

Here's a picture of the text end: https://i.imgur.com/nRntHFe.jpg

I haven't checked the other side of the world if it clips through as well since this world is large and I'm pressed for time at the moment, I'll update when I get there if it hasn't been fixed (in the world) when I come back.

**Comment by craig-jong** [comment]
this is fixed
