### ISSUE TITLE
Big letters all around the world

### ISSUE THREAD

**Issue by Sonic1305** [StrangeLoopGames/EcoIssues#8046]
Someone placed big letters (and other symbols like a Swastika etc.) on our server. We can't determine how to remove them or how they placed them so this is a thing that should be prevented.

Picture of what happened: https://imgur.com/a/aEmVHUu
Game.eco: https://drive.google.com/file/d/1v7C2cUr1KiWh-9uOgzx67Qq7EeH6tJvX/view?usp=sharing

**Comment by Sonic1305** [comment]
We found the source, as it are just signs with the following code: For example: <size=9999>PINKO<br><br>

Swastika is also easy to add if you copy it which should not be allowed to be in a text box....

**Comment by MarjieAVolk** [comment]
Hey there - the whole team has been discussing this issue, which seems to have happened to several servers.  We are going to fix the giant letters everywhere by clipping sign text so that it can only be displayed within the bounds of the sign.  This will come out with the next release, which should be within the next week.

We are still discussing whether to add the swastika character to our default profanity filter.  We recognize that it would still be quite easy for someone like this to build a giant swastika out of blocks, for example.

**Comment by MarjieAVolk** [comment]
@rachaelfosner Assigning this to you, since I'm told you were the one who implemented the sign text masking.  Can you double check that this got fixed for all signs?  It should probably be fixed for vehicle license plates as well.

**Comment by elfl0rd** [comment]
> We are still discussing whether to add the swastika character to our default profanity filter.
Overfix, in my opinion.
Size fixes - close problem with swastika.
(And adding to profanity can not prevent users to paint it from symbols...)

**Comment by MarjieAVolk** [comment]
Hm, this is part of the actual object, and it's really not intended to be a feature, so I doubt we will offer support for continuing to use signs this way.  We do have some larger signs available now though.  Does that help?

**Comment by metachronism** [comment]
fwiw

<size=X>  does not respect the max size settings of the box, but <size=X%> does

**Comment by craig-jong** [comment]
All sizetags are being forced to percentages now.

Should fix the issue, but hopefully we can find a better solution at some point.
