### ISSUE TITLE
World won't load, but it goes to main menu

### ISSUE THREAD

**Issue by deapetersson** [StrangeLoopGames/EcoIssues#8096]
The world is loading fine in the server client, but when i try to access my world, it just keeps going back to main menu.

I chatted with moderator Pam for 3 hours about the problem, but nothing is working.

**Comment by pamduncan** [comment]
We spend several hours on this.  The saved world appears okay as we were able to load it by command line tuning the server outside the client. The server and the current world loaded and the server UI was up and running, saw no errors with it outside the client  We also tried creating a fresh world in case it was a profile or law issue that was preventing a log in but this happened in a  fresh would to.  It would go to log character in the world and drop back to the menu.  With the server started by command line and server UI, the server was visible as a LAN in the client browser but browser dropped to menu as soon as a log into the LAN was attempted.

Originally steam verify several times reported a missing file and ant reinstall was done and that was corrected by correcting the av software.  The problem continues.  Also a complete re-install was done twice during the course of this

appdata delete was tried and loading up the SLG copy of the client outside of steam was tried and same thing happening in the SLG copy as it did in steam copy.

Net frameworks is up to date and running 4.7.2
Made sure that permission was granted through firewall for Eco.exe and EcoServer.exe, both incoming and outgoing and after the SLG client through an firewall error also ran the netsh command to make sure that the game had access.

Since the world loads there are no errors from the console or from dumps.  There were no error file in appdate folder.  Could not get it to give much of a clue as to why its not allowing access to the game world

**Comment by BlazeGuy2** [comment]
Which version are you on?

**Comment by deapetersson** [comment]
Version 7.4.7 I believe.

**Comment by metachronism** [comment]
cant do anything without the gamesave, please attach and reopen!
