### ISSUE TITLE
Conflit on Unique identifier Server ID

### ISSUE THREAD

**Issue by Hactarus** [StrangeLoopGames/EcoIssues#8115]
Hi,

I've found collision on unique identifier with my server.

If i use direct connection with : eco.cresi.be or 178.32.122.23:3001
I can connect to my server, but on Favorite or Continue button, I'll connect to another server (different ip, not same AS, one ip is FR the other DE)

You can check this collision with a simple curl/browser :
[https://eco.cresi.be/info](https://eco.cresi.be/info) / [http://178.32.122.23:3001/info](http://178.32.122.23:3001/info)
"UniqueIdentifier": -2371104388876035499,

[http://5.189.144.250:3001/info](http://5.189.144.250:3001/info)
"UniqueIdentifier": -2371104388876035499,

If i look at my fav' the other server is saved not mine.
$ cat favorites.eco
[{"Description":null,"UniqueIdentifier":-2371104388876035499,"Address":"5.189.144.250","GamePort":3000}]%

**Comment by MarjieAVolk** [comment]
Hey there - sorry I never responded to this, but I wasn't sure what to tell you.  It looks like this id is coming from a third party library, and I'm not sure if there's a way to regenerate the id.  Theoretically this should happen extremely rarely.  Of course that doesn't help you very much.

**Comment by MarjieAVolk** [comment]
@metachronism says the ID is generated the from your MAC address.  Were you spoofing your address or anything funky like that?

**Comment by Hactarus** [comment]
My eco server is on a docker on a dedicated server with public alias ip fronting. So the Mac is randomly generated and not associated to real hardware. I've change my server (remove game.eco and moved to another dedicated server) and get a new id.
Thanks for looking at it.

**Comment by MarjieAVolk** [comment]
Glad you got it working.  Sorry for the delay!

**Comment by BurningEnlightenment** [comment]
@MarjieAVolk this problem seems to be strongly related to docker, maybe they do some deterministic MAC assignment for internal docker networks or something. Booting up the same docker image on different servers resulted in the same id for me and probably others. E.g. my server https://eco.deeplex.net/info and some other foreign test server http://185.142.213.26:3001/info share the same id -3431301874222990000 which breaks the favorite, join and reconnect buttons for my playerbase 😞. Can't you switch to something which is more likely to be unique like a UUID?

**Comment by MarjieAVolk** [comment]
Hm, that is unfortunate.  Maybe so.
