### ISSUE TITLE
USER ISSUE: Player can't join

### ISSUE THREAD

**Issue by Deskiba** [StrangeLoopGames/EcoIssues#8153]
**Version:** 0.7.5.0 beta

**Steps to Reproduce:**
1. I load my game
2. I invite my friend
3. The game of my friend crash before he can join the game

**Expected behavior:**
My friend should be able to join and we should be able to join me. It was working on the 25 of june. now, the 7.5.0 is out and it isin't working anymore	

**Actual behavior:**
After accepting my invitation, the game of my friend instantly crash and quit the game entirly

**Comment by X-ITT** [comment]
After updating I had a problem trying to get into my server,  I think it is an access issue with either steameid or slgid. Your friend can join another server right? I ended up creating another slg account to get into server,  because I don't know how to correctly remove user profile in server. But I understand not everyone has the luxury to create another account.

**Comment by metachronism** [comment]
consolidating into #8443
