### ISSUE TITLE
Client server unable to load game - server not compiling Eco.Mods.dll

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8154]
On the client servers I have been dealing with the Eco.Mods.dll is not compiling. Its all been on steam installs and not on SLG download/installs.  It appears that steam is not cleaning out all the old files and leaving some behind and so they are mixing some 7.5 files with some older ones.  verification does not seem to help as it seems to see the file is there and it think its correct.  The work around has been to do a 
complete clean reinstall (manually deleting everything but the /Storage/ folder) and so far all these people with this issue have found files left behind in both the Mods directory and the Webclient directory.  Deleting everything so all they have left is any game save and any backups and reinstall a clean copy of 7.5 and the Eco.Mods.dll will compile without an issue

**Comment by Thurdi** [comment]
I found an inconsistency with the naming of the SkidSteer.cs file and the SkidSteerObject.cs file following the update from 7.4.7 to 7.5.0.  Because of the naming inconsistency the new SkidSteerObject.cs file didn't overwrite the SkidSteer.cs file.  When the game tried to load both it crashed.  Upon removing the SkidSteer.cs file in \Mods\Objects\ the server launched properly and started converting the world to 7.5.0.  I can provide the crashdump if needed.

**Comment by metachronism** [comment]
should be fixed in 7.5.1
