### ISSUE TITLE
Access Violation on Client crash

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8177]
From:  (discord name)  EldaRion   email  eldarionspiel@gmail.com
(cannot write English so posting for him)

Eco [version: Unity 2017.4.2f2 (52d9cb89b362)]

Eco.exe caused an Access Violation (0xc0000005)
  in module Eco.exe at 0033:00000001.

Had been playing on server for 2 hours then started crashing try to log in

**Comment by X-ITT** [comment]
I've gotten this error, after server/client update 7.5.0. I was able to get into server played 30 mins crash, go back 5mins crash again,  go back crash instantly,  continue to get crash instantly. I think it's an access issue with either steamid or slgid. Creating a new slg account helped, but not everyone has this luxury. I've heard this happened to previous people on previous updates, and the fix was to delete their profile in game.eco file, and then use admin commands to restore sp, but every time I tried this the file became corrupt, mainly because I don't speak gibberish.

**Comment by miketek1** [comment]
I also got this twice yesterday one time someone ran into me in game with a harvester attached to a tractor. Also someone today said that they crashed after I ran into them. Attached Both Crashes, occurred on 7.5. 
[error1.log](https://github.com/StrangeLoopGames/EcoIssues/files/2142535/error1.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2142537/error.log)

**Comment by Voosle** [comment]
@elfl0rd: EldaRion (reporter) version is 7.5.0 after regular update last night. I'm playing on same Server :-)
@pamduncan: fyi

**Comment by Voosle** [comment]
EldaRion assumes to be locked 'in' a block somehow. Even unstuck command does not free him.
May I provide a backup of the save game?

**Comment by Voosle** [comment]
@elfl0rd: 
Here are error.log, Output_log.txt and crash.dmp files from EldaRion.
[Crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2145963/Crash.zip)

**Comment by X-ITT** [comment]
Issue is do to entities (usually a ramp) that is in the way. Remove the entities. Have another person remove the the entities in the way of the location your player is at, This will most likely be a ramp. You can find that location by logging in, a different person should see your location on their map then go to it, remove entities in the way, and try logging back in again.

**Comment by BlazeGuy2** [comment]
Ramp bug was fixed in an older hotfix.
