### ISSUE TITLE
USER ISSUE: Can't connect to my single player game

### ISSUE THREAD

**Issue by freyr-666** [StrangeLoopGames/EcoIssues#8179]
**Version:** 0.7.5.0 beta staging-4ba58c84

**Steps to Reproduce:**
Start a new game in 0.7.5

**Expected behavior:**
create the world and join them

**Actual behavior:**
The following error message popped up:
```
<size=150%>Connection Failed</size>

Failed to establish connection - no response from remote host
```

**Comment by pamduncan** [comment]
This has been working for those in the discord support channel with this issue, if your issue is caused by the same problem, but while following these steps you can also collect information for the devs.  First make sure that the client servers is correctly building a game.  To do this you need to run the server outside the client  .   If you could close the Eco client down and go to your steamlibrary/steamapps/common/Eco/Eco_data/Server and right click on EcoServer.exe and run as administrator.  A command window will pop up, the console and tell you what the server is doing and if it hits an error.  If you get an error in the console please screenshot and post here.    If it loads completely and creates a new world then the Server UI will open up.  The world it creates will be names "Game".  If it gets to that point leave it the server UI open.. If no error and the server UI is opened, then go into steam and into Eco and click "Join" and in "My Servers" you should see your server in the LAN section.  Click on it and on the right-hand side click "Join".  If it fails the first time, please try a second time.  If it fails at this point please check the following places for errors and if there are any files please post them:  steamlibrary/steamapps/common/Eco/Logs  appdata/LocalLow/StrangeLoopGames/Eco and /Eco/Crashes   (https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/).  Then, make sure that the server and steam are shut down and  if you would delete the Eco folder in appdata.  then start up the server again, manually as before, and go back into steam and use Join and try joining you servers again.  If you can join now then you should be able to shut down the server and load it back up through the client using 'load' and join.  If it will not let you load you can still play by manually starting server and joining the LAN server

**Comment by BlazeGuy2** [comment]
Put out a hotfix.  If issue is still occurring, open another issue.
