### ISSUE TITLE
[7.5.0] No Events on Learning Skills

### ISSUE THREAD

**Issue by Rick86** [StrangeLoopGames/EcoIssues#8183]
Before 7.5 you could make laws based on the Learning Skill event. Now there are only events (in law and also in C#) if you learn the Specialty / **main Skill**, but not any more if you learn a Skill **within** this tree.  We had laws to check, if someone is allowed to learn a Skill in this tree (not the whole tree)... Now the laws are not working, because of the missung event, so why did you removed these events? Everytime there are new features, you remove others which were fine for everyone...................

**Comment by MarjieAVolk** [comment]
I changed this law action in order to make the two existing skill actions comparable to each other (so they could be meaningfully subtracted, etc).  I chose to go with specialties as opposed to skills since the learning and abandoning of specialties seemed more clear and straightforward to me, and I believed this would cover most use cases.  This was all based on requests made by other players.  I'm sorry that this broke your existing laws.

Other than the fact that your existing law changed unexpectedly - Why do you want to refer to individual skills, rather than specialties?  What cases require that?

**Comment by Rick86** [comment]
Mhhh... I understand... Well in this case we have Jobs and some Jobs have not all Skill Trees of a specialty (for balancing reasons). So if some try to learn a Skill, but don't have the needed Job, I prevent this try. Now I know which Specialty / main tree the user tries to skill, but not the Skill itself.

For example: The user is allowd to skill Smelting, but is NOT allowed to learn advanced smelting (just as example). Without the events, I don't know what the user is trying to learn :/ If I choose other events (play event for example), the user could skilled some "forbidden" levels, because we can not send him any messages or prevent the try.

**Comment by SlayksWood** [comment]
This issue is not be occur, because now we don't have specialty trees. We have new triggers for specialty in 0.9.0:
![image](https://user-images.githubusercontent.com/45708377/83009109-e7676f00-a01e-11ea-8a7b-dcb68ba0ed3e.png)
Closed.
