### ISSUE TITLE
USER ISSUE: One Player cant join this server

### ISSUE THREAD

**Issue by eviltek2099** [StrangeLoopGames/EcoIssues#8257]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
He cant Join but can join other servers and other players can join this server. when he tries it crashes his client with no error.

**Expected behavior:**
let him join

**Actual behavior:**
nothing pops up. his client just chashes to windows

**Comment by Gohan0646** [comment]
So for more specifics, we are running game version 7.5.1. Basically when i direct connect to the server it completes the "loading eco" and then on the "Entering World" prompt the game closes. No error Message,, No crash file.

We currently aren't running any mods, or have more than 5 players on at a time.

I am able to join other servers. Sometimes i get that crash on the first attempt but the second attempt allows me to join.

What we have tried in troubleshooting.
1. Uninstalling the entire game and associated folders and reinstalling.
2. Rebooting my router.
3. Running in compatibility mode for windows 7 and 8.
4. Running as administrator.
5. Lowering all settings to barest minimum settings.

None of the above work.

**Comment by Dragon3791** [comment]
since this i have started having some what of the same problem.  ill be on the entering part of logging in or just past it where i can faintly see the world in the back ground when my game will crash. however i am getting crash reports. i will attach them. I've done all the trouble shooting i can as well and nothing changed or help. 

[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2152975/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2152976/error.log)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2152977/error.log)
![eco crash](https://user-images.githubusercontent.com/40740512/42136700-4737adaa-7d26-11e8-891f-7e570a44ef48.JPG)

if it is the same problem maybe these will point it out

**Comment by Firesped** [comment]
I'm also on this server. I just crashed on with this area while trying to use a cart on a uneven surface.

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:4357fb05.

[crash.zip](https://github.com/StrangeLoopGames/EcoIssues/files/2156218/crash.zip)
[error.log](https://github.com/StrangeLoopGames/EcoIssues/files/2156219/error.log)

**Comment by MarjieAVolk** [comment]
I just saw a similar issue the other day.  We found that deleting a certain file fixed it.  Open up local files via steam, and then find and delete Eco_Data\Server\Eco.Mods.dll

Let me know if that works.

**Comment by SeanAtr0n** [comment]
There is a slightly different issue that probably covers @Firesped https://github.com/StrangeLoopGames/EcoIssues/issues/8273

I'm not sure if it covers the original issue here though.

**Comment by Firesped** [comment]
we were able to get me unstuck by removing the ramp and filling in the ground. I've been having issues where the game seems to freeze as it tries to move me into a block of ground instead of on top of it. Eviltek said when he saw my avatar in game, it looked like I was stuck in the crack between the dirt block and the ramp.  This occured while using a cart that put my avatar into the position. It was the same case I believe with at least dragonfire as well. I did try uninstalling and reinstalling the game which had no effect. the local game files are not the issue. it is that players are getting into locations that the unity engine is calling invalid. UnityPlayer.dll needs to be updated to handle this issue and understand it so the game client does not crash. I have a second dump file for it if you need another example as well.

**Comment by WR-BikAir** [comment]
I have proceeded like @MarjieAVolk had written on my computer. But this did not fixed the issue. Do I maybe have to delete the file on the server too? (if there is one)

**Comment by MarjieAVolk** [comment]
@WR-BikAir That is too bad.  You could try deleting the file from your standalone server, but I don't have high hopes.  You might also try deleting the folder C:\Users\\[username]\AppData\LocalLow\Strange Loop Games\ECO

**Comment by WR-BikAir** [comment]
That worked like a charm! Thank you very much.

**Comment by eviltek2099** [comment]
This seems to be fixed now thanks to the patch :)

**Comment by MarjieAVolk** [comment]
Oh, that's great.  Sorry I closed this earlier, I was thinking someone else was the original poster 😅
