### ISSUE TITLE
USER ISSUE: large doors not save state.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8357]
**Version:** 0.7.6.0 beta staging-f5159538
Place large door.
close\open it.
Rejoin.
now door in default "placed" state.

**Comment by keegan-o** [comment]
Messed around to try to fix this with the prefabs, tried using door scripts instead of world object scripts, but that did not do it. It's something in the code/tech tree, not the prefabs. Unless there is a way to fix it with the animation controller that I don't see. 

Having the doors used enabled/disabled seems to be unique to the large doors, not sure how the states would not be saved or be fixed to be saved vs. however it is done for the small doors.

**Comment by seccombew** [comment]
Fixed by SeanAtr0n.
