### ISSUE TITLE
More currency values for laws

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#8362]
Right now you can only check your own currency balance.  You should also be able to check treasury balance, total currency in circulation... maybe others.

**Comment by elfl0rd** [comment]
Yes, i want!

**Comment by pamduncan** [comment]
It appears that you can check the currency balance of other players and I don't think it should be like that.  Yes, being able to see treasury and world balances definitely, but not individuals.  In real life your bank account balances are private and a store or contractor would not be able to view your total balance before they sold you something or agreed to do work etc.  We have had a great deal of problems with players knowing the full amount of currency that a player has in tehir account because server things happen:  1) A person will ask another player to make something for them that takes a while to complete and knows they will be able to earn the money to pay for it by the time its ready so they do not have to order then and wait - but the person he asks checks his balance and says they will not do it because they don;t't have the money in their account,  2) A player builds a item and sells it at a very low price (material cost and a bit extra) to a player without much money, or prices it to the exact amount they find he has but then when asked to make the same thing for someone else that he can see has a lot of currency available charges much, much more because the person has that much available.  This is frustrating if you are trying to get an economy functioning more on supply/demand because it the price will be low enough for anyone to buy it if they have little currency but very expensive if they have a great deal there is no real functioning economics in that model.  It has also caused problems with players monitoring other players balances and sees someone's balance jump up because they either sold things or borrowed from a friend or did a contract and instead they re accused of cheating because of the balance jump.  In real life, if you are doing a cash business you don't need to know what the person's bank balance is,  they just have to pay the 'price' to get the item.  If you are doing other business with them when it would be helpful to know if they will be able to pay or pay you then there are things like credit ratings and business reputations or statements from the bank that says the person is able to cover that amount without giving away a total balance.  But there is always a little risk in business as a total bank balance is private information.  I definitely advocate for those admins/owners who would prefer their server not show people what each individual players currency balance is.  I understand, though, that some admins/owners think everyone should have full information about everyone open to them.  Perhaps there needs to be an "Economic" configuration file where and owner can choose is their server will allow individuals bank balances to be made public and also, if a permitting system is put in that only allows so much lumbering/mining (and leaving debris behind) without renewing it to limit greifers, those that don't want to use that method of limitation could also turn off permits too or set the top amount you would get with the initial permit you get on creation to 'unlimited'

**Comment by Deantwo** [comment]
Pam, I don't see what your huge wall-o-text has to do with currency law additions. I suggest you make a separate issue for this.

That said, all things in Eco are public. Everyone can see when when someone start a crafting job or when they trade with someone. So if anyone thinks that is someone is cheating then they aren't really playing attention.
Being able to see how much money a store has is actually something I find missing a lot. I try to sell something to a store and I am told they don't have the money for it, then I have to open up the economy window and look at how much currency they have so I know how much I can sell. But this is commonly also an issue with the store's owner not accounting for the possibility of people selling them a ton of something they didn't even need a lot of.

I will agree that it could be an interesting thing to make moddable, so someone can make bank information private and the like, but I don't see how it is an issue with the game.

**Comment by MarjieAVolk** [comment]
@Deantwo I agree the store thing is an issue (despite it not really being related to this bug :P ).  I think stores would be much improved if they would put more limitations on the actual + and - buttons etc, rather than making you wait to click trade and see the error message.  Eg. you can no longer click + on something if doing so would make the trade invalid (either because the store is out of stock, out of money, out of space, or you are, etc).
