### ISSUE TITLE
USER ISSUE: Crash

### ISSUE THREAD

**Issue by KiBu07** [StrangeLoopGames/EcoIssues#8366]
**Version:** 0.7.5.1 beta

**Steps to Reproduce:**
I have create a new world, without password, with a size from 4km. I waiting a full hours that the world was charging. After one hours i became "give password from server".. I don't give password and the hours of waiting was for nothing. Whatever i give in from the size of the world, the game doesn't started. 

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
<size=150%>Verbindung fehlgeschlagen</size>

Invalid password.
```

**Comment by elfl0rd** [comment]
Please attach
\Server\Configs\Network.eco

**Comment by pamduncan** [comment]
If you could make a screenshot of the Network tab in the server UI instead of jusrt attaching the Network.eco config file that would help as the config file will not show you if somehow a hashed password has gotten installed but the hashed password would show on the server UI.  We have had a few instances where the server has created a hashed password on servers where no password is in use. But since the hashed password is not written to the Network.eco file you cannot tell if that is the issue or not.  The workaround that has worked is to add a password to the Password field then do a File > Save from the main menu.  Then in the Storage menu item do a a "Flush to disk and" > save.  Then delete the password from the server UI Network Tab config password field and see that the hashed password has disappeared.  Then again do a File > save and then do a Flush to disk > save.  Now log on to the server and see if that error is gone.

If you are on a hosted server and do not have access to a server UI you can do the same steps but with editing the Network.eco config file and shutting the server down and starting up between each step. You won't know for sure if a hashed password got in there but if it solved the problem then I would assume that that was what
