### ISSUE TITLE
!Potential! ussue when 7.5 to 7.6 migration.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#8392]
Lot of empty deed's here.
@MarjieAVolk can you check it?
![20180708132548_1](https://user-images.githubusercontent.com/4980243/42419068-6beb1c3c-82b6-11e8-8d47-be55d6c41d44.jpg)
![20180708132535_1](https://user-images.githubusercontent.com/4980243/42419069-6c0d0d60-82b6-11e8-8dd0-61d5c54897c7.jpg)
![20180708132538_1](https://user-images.githubusercontent.com/4980243/42419070-6c2b8b46-82b6-11e8-89f5-1c530d6fee59.jpg)
![20180708132540_1](https://user-images.githubusercontent.com/4980243/42419071-6c495fcc-82b6-11e8-98dc-6879d0823626.jpg)

**Comment by MarjieAVolk** [comment]
Hm, I saw this on a save once before - they are all deeds that were made for a single vehicle, etc.  I thought that it was a bug in migration at first, but then I wasn't sure if maybe it was a previous bug with vehicle deeds, since we had seen a lot of issues on previous versions where vehicle deeds and vehicles would 'lose' each other.  It might also be possible that all of these are deeds for vehicles that got picked up, and maybe the deed item got deleted but the rest of the deed was just sticking around invisibly in the save.

Do you have a lot of vehicles that suddenly got unclaimed?  If so, I would consider this a serious issue.  If not, I might go ahead and instead delete all these empty deeds on migration.

**Comment by elfl0rd** [comment]
No, all my vehicles save owner, but in my world ~9 vehicles total... I don't know what heppens on a large server.

**Comment by MarjieAVolk** [comment]
Okay, I suspect that these are deeds left over from every time you picked up a vehicle.  I will have migration delete them.

**Comment by elfl0rd** [comment]
Do not lost
1) "Delete deed"
2) "Attach all plots to another deed"
3) "Empty deed stil as ghost"!

**Comment by MarjieAVolk** [comment]
fixed in next build, though you will only get the fix on migration, not for already migrated saves.
