### ISSUE TITLE
USER ISSUE: Electronic Machinist Table requires Electric Power (No Electronic Power the time)

### ISSUE THREAD

**Issue by BillyMantwo** [StrangeLoopGames/EcoIssues#8491]
**Version:** 0.7.6.0 beta

**Steps to Reproduce:**
Electronic Machinist Table requires Electric Power. Electronic Power does not exist at the time. That's what happens when you have Electronics Assembly and Electronic Assemly Line. It is not possible to get electric power.

**Expected behavior:**

**Actual behavior:**

**Comment by vannucci16** [comment]
I am having the same issue also the Pumpjack is made in a table that requires a servo to make that requires fiberglass which needs a pumpjack to make.

**Comment by pamduncan** [comment]
perhaps:  the steam engine should produce electrical power not mechanical power but the steam engine always ran the pumpjack in the past

**Comment by GokouZWAR** [comment]
I agree the steam engine doesn't make sense to make mechanical power. We patched our server so it generates electric power. Problem solved. Took 5 seconds to fix it in the steamengine.cs file.

**Comment by GokouZWAR** [comment]
change line 64:
this.GetComponent<PowerGridComponent>().Initialize(10, new MechanicalPower()); 

to this:
this.GetComponent<PowerGridComponent>().Initialize(10, new ElectricPower());

**Comment by Pankter** [comment]
the robotics assembly line can not be crafted because you need a oil refineri to craft it but the oil refineri is craft in the robotics assembly line

**Comment by vannucci16** [comment]
Thanks for that Gokou ill try that to fix my issue and yea I noticed that too Pankter but fortunately I made some pumpjacks before the update

**Comment by GokouZWAR** [comment]
@vannucci16 Also the new pump jack does not require servos. It requires gearboxes which does not need fiberglass.

**Comment by Pankter** [comment]
For the robotic assembly line you need a electric motor, for the electric
motor you need circuit, for circuit you need substrate, for substrate you
need epoxy and epoxy you make at the oil refinery


GokouZWAR <notifications@github.com> schrieb am So., 15. Juli 2018, 22:27:

**Comment by Pankter** [comment]
But the oil refenery is built in the robotic assemply table and to built
this table i need the oil refenery to built one part (last mail)

So i can not make the robotic assemply tabe without the oil refenery, and i
can not built the oil refenery with out the robotic assemply table

[PS i come from germany so do not wurry if i have some mistakes in the
writing]

vannucci16 <notifications@github.com> schrieb am Mo., 16. Juli 2018, 01:25:

**Comment by GokouZWAR** [comment]
You’d be better off starting a new thread but I see the issue is in the crafting table, not the recipe. 

We moved the pump jack and oil refineries back to the assembly table which resolved our issue. I don’t know what the devs will do in the official release fixes, but that’s what we did on our server. 

Since this topic is related to power issues and not the oil issues, I suggest making a seperate post as these issues are not related.

**Comment by BlazeGuy2** [comment]
Dup of #8452

**Comment by GokouZWAR** [comment]
@blazeGuy2 this issue is not duplicate of that issue! This is the fact that there’s no power for machines that need power. The referenced item is the crafting system problem when you need dependent objects to craft. While this is similar the solutions are different (electric power ca mechanical power) Are you including both solutions into that one pull request item?
