### ISSUE TITLE
Steam is failing to update client

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8560]
A number of users have had their crashes fixed by uninstalling and reinstalling the client.  There is some bug with Steam where it's not fully updating the client.  Need to either

1) Figure out what this is happening in Steam and prevent it
2) Run some kind of validation check so its not running partially updated builds

**Comment by johnkslg** [comment]
Keep an eye out for this one, we shouldnt need to reinstall Eco to make an update work.  Saw several reports from people auto-labeled 7.6 but was showing UI from 7.5.  That would only be possible if it somehow did a partial update.

**Comment by pamduncan** [comment]
Just note,  I have been seeing this since 7.5.0 but its gotten worse over this past weekend.  Given that getting a user to install SLG copy and everything works fine was a real clue.  "Verifying" files does not pick up what is missing or not installed - so its like Steam never knew to install it in the first place.  This is further complicated by server AV programs that are blocking game install through steam - but in that case usually steam will see a missing file but re-acquire does not work as the AV software blocks again.  But if its not the AV issues, steam just does not even seem to know its supposed to have a file that is missing and can even take 2-3 reinstall to get a working copy.  However if they install a SLG copy everything works fine.  Several people have then checked the SLG Eco directory and the Steam Eco directory and reported back things like file counts and checksums are different - not sure of checksums would be expected to be different given that one is on the steam platform but I would assume file counts should be the same?

**Comment by elfl0rd** [comment]
> file counts

 hm... steam need some more .dll to work.

**Comment by johnkslg** [comment]
If anyone is able to repro this, please contact me at discord.gg/eco @johnk before you fix it!

**Comment by elfl0rd** [comment]
okay, after downgrade from bleeding_edge to 7.6.3 i receive rotating gear on starting singleplayer. This?

**Comment by elfl0rd** [comment]
client identical, bug fixed by
> netsh http delete urlacl url=http://+:3001/
