### ISSUE TITLE
Units divider not functioning

### ISSUE THREAD

**Issue by newzealdan** [StrangeLoopGames/EcoIssues#862]
Shift+left-clicking on an item in inventory opens up a divider option, but pressing OK doesn't work. Cancel works, fortunately.

Eco 0.50

![image](https://cloud.githubusercontent.com/assets/6193670/20832101/403ada62-b8ed-11e6-8c2b-e1ce3dd0ff4e.png)

**Comment by fillion07** [comment]
It annoys me a lot when I have 100 planks in a slot and I'm not able to take them on me because of max weight. It took time to the game to figure out how to split correctly the planks to not exceed the max weight. At least the game it's able to split the items in the slot and drop a parts of the items in my inventory  automatically when it reaches the max weight. Where it's annoying it's when you want to separate the items from a slot to only give a specific amount of the object to another person when trading.

**Comment by XerWolf** [comment]
This bug appears to be occuring on [0.5.4]  Can we reopen it?
