### ISSUE TITLE
USER ISSUE: Campsite cannot be crafted

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#8706]
**Version:** 0.7.6.2 beta

![snap2331](https://user-images.githubusercontent.com/29383891/43104073-0ae13480-8ec8-11e8-8546-4360e7017c5d.png)
![snap2332](https://user-images.githubusercontent.com/29383891/43104074-0afe78f6-8ec8-11e8-9957-b65f170ce480.png)

Only found this out as i wanted to make an Area like a Campsite with multiple Tents etc, but seeing as i cannot craft this even though it says we have a recipe

also linking it to this github because with No recipe Old worlds updated to a newer version are stuck being unable to craft campfire and workbench as it needs a campsite
Cant craft Workbench and Campfire since 7.6 #8653

**Comment by pamduncan** [comment]
The only place I know of that a campfire can be created is the starting tent.  The recipe is only available at the tent.  Since they have not made any other place it can be made to work any on existing worlds with existing players  that did not get a starting tent an admin should have a starting tent down set to public so those players have a place to make campfires.  Otherwise anyone with a starter campsite can make their campfires there.   The other option might be to have an admin spawn several in and sell at a store.

**Comment by craig-jong** [comment]
Fixed in above PR.
