### ISSUE TITLE
Trash disappears in Stockpile

### ISSUE THREAD

**Issue by ShaydenMac** [StrangeLoopGames/EcoIssues#8727]
If you're standing in/on a stockpile, and you remove something from your inventory into the Trash Bin, the item will disappear completely.

**Comment by craig-jong** [comment]
Dropping trash on a stockpile only fails when you're in the direct center of it and, if thats the case, it places it back into your inventory. Otherwise it'll end up on one of the edges of the stockpile. I'm going to close this under the assumption that, maybe, the trash was difficult to find if you had stuff in your stockpile already. 

Let me know if this reproduces somehow and I'll reopen/recheck it.

**Comment by SeanAtr0n** [comment]
![image](https://user-images.githubusercontent.com/774628/43733328-1bdfc264-9969-11e8-9821-cf075842852e.png)
