### ISSUE TITLE
Property auth checks are too easily overriden now

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8750]
![image](https://user-images.githubusercontent.com/3536496/43234877-78579e66-9033-11e8-87c6-c45fd8ad851c.png)
This change lets anyone change the text on a distribution station object sign, among other things. It will also cause contracts to let player 'override' lots of actions they shouldn't.

Previously, UseAction was only for opening an object's UI, and so having a contract related to an object would let you open it because the contract would allow override of 'UseAction' types.  With it being used generally like this for any kind of auth check, it opens the door for other interactions to be allowed which should remain restricted.

We'll want to make the authorization use more specific tests, or at least add an 'UnspecifiedAction' so that contracts can not allow overrides in that case

**Comment by johnkslg** [comment]
Also check that the distribution station properly limits how much you can take.  It no longer is doing so.

![image](https://user-images.githubusercontent.com/3536496/43235281-ffbd8b58-9034-11e8-93ce-2cc81c538cab.png)

**Comment by MarjieAVolk** [comment]
It seems unlikely that that change broke the distribution station, since that change is only adding a way to use actions other than the "UseAction" there.  "UseAction" has always been used as the default action in PropertyManager, since before I started the auth rewrite.

**Comment by MarjieAVolk** [comment]
Yeah, the override checks for this are going through AuthorizationInventory, which is specifically using the api added by the change mentioned, allowing it to use an InventoryGameAction instead of a UseAction, so I would say the above change actually fixed this behavior.  The Distribution Station seems to be working for me on staging.  It does have some odd behavior when it is unclaimed, since the error messages in ItemTracker.ShouldOverrideAuth get sent every time auth is checked, which makes a bunch of incorrect error messages get sent when moving stuff around in the Distribution Station while it's on public property.  I assume a Distribution Station on public property isn't intended to actually limit who can remove stuff.

**Comment by MarjieAVolk** [comment]
So leaving this open if we want to fix up those error messages.  This is why things generally should return a Result, rather than returning a bool and sending an error message internally.

**Comment by johnkslg** [comment]
Fixed!
