### ISSUE TITLE
USER ISSUE: ALOE

### ISSUE THREAD

**Issue by ALOE-ALOE** [StrangeLoopGames/EcoIssues#8755]
**Version:** 0.7.6.3 beta

**Steps to Reproduce:**

**Expected behavior:**

**Actual behavior:**
The following error message popped up:
```
A save named 'ALOE' already exists
```

**Comment by pamduncan** [comment]
Have you already named a world "Aloe"?  You would not be able to create another game by that name unless you first deleted the saved file of the world save using that name. Or you can use another name.  If you are trying  to play the world by that name choose 'Load" and pick the world by that name in the list instead of choosing "New".  "New" would only be used for creating a completely new world and you would need to use a name not already in use for a world.
