### ISSUE TITLE
Fall-thru-ground protection a little too eager

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#8819]
Need to address false-positives like this as they are very common.  
![animx](https://user-images.githubusercontent.com/3536496/43545341-812cd4fa-958a-11e8-9b49-3e6c5fc6e3f6.gif)
Would be nice if placing dirt under you for example lerped you to the right position.

**Comment by johnkslg** [comment]
Message @SeanAtr0n on discord to get details on how this works

**Comment by sidjuego** [comment]
The issue lies in here; see the image below.

`this.motor.setPosition(transform.position + Vector3.up)`

![diggingproblem](https://user-images.githubusercontent.com/43029943/46475635-abf1ae80-c803-11e8-8fd6-eb01a78012cf.PNG)

Whenever you're placing dirt and even if you're slightly under the ground, it will always increment your next position with a height of 1 unit up.

I have considered few approaches but they will definitely fail because the ground is uneven.
Let me know on how you would want to proceed with this.
Thanks!

**Comment by johnkslg** [comment]
You could use a raycast to detect the exact position of the ground and put them there. 
And then test if that still collides, and if so move them up until theyre not?  Will take some experimentation.

**Comment by krithikJuego** [comment]
> You could use a raycast to detect the exact position of the ground and put them there.
> And then test if that still collides, and if so move them up until theyre not? Will take some experimentation.

This was my first approach to tackle the issue. However, it is most likely to fail if the user has dug deep into the ground (like a vertical tunnel). As per my best knowledge, I need to understand the working of voxel system that generates the terrain and get the appropriate nearby closest block when the dirt was dug up.

**Comment by sidjuego** [comment]
> You could use a raycast to detect the exact position of the ground and put them there.
> And then test if that still collides, and if so move them up until theyre not? Will take some experimentation.

This was my first approach to tackle the issue. However, it is most likely to fail if the user has dug deep into the ground (like a vertical tunnel). As per my best knowledge, I need to understand the working of voxel system that generates the terrain and get the appropriate nearby closest block when the dirt was dug up.

**Comment by johnkslg** [comment]
Elevating this because its an easy way to add a lot of polish
