### ISSUE TITLE
Admin command or config setting to remove abandoned/incomplete contracts

### ISSUE THREAD

**Issue by pamduncan** [StrangeLoopGames/EcoIssues#8990]
One of the major issues we have in support is what to do about contracts that are accepted and then never completed or just abandoned.  It would help to have an admin command where a server admin could go in and delete a contract that is just hanging there never fulfilled or completed.  If that is not possible perhaps a config setting where a server owner could set a time limit on contracts that removes them if not accepted by someone or completed withing so many game days and the server would automatically clear up those contracts that had gone past a set expiration time.  Many admins have come asking for a means to remove contracts that have never been completed and the player that accepted the contract has either left the server or chooses to not complete the contract.

**Comment by wolfgangmeyers** [comment]
I'm looking at this one

**Comment by johnkslg** [comment]
- Once contracts expire, the client can mark them as failed
- In general, though, it would be nice to allow admins to have control over contracts.  I suggest the following for an approach:
On the contract title, append a new Contract ID int, which is just a serialized unique number starting at 1.  Then add a new chat command that lets you delete contracts by ID, or change their state or otherwise manipulate them.  Make the contract ID display in the tooltip for the contract too, that way any contract ID can be found by anyone.
