### ISSUE TITLE
"EcoServer.exe stopped working"

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9043]
Once every two days or so the server looses connection to all players and shows the error message in the title on my remote desktop. When i press okay, the server just goes on as if nothing happened and all players can connect again instantly - no restart needed.

The only messages in console i got are such as these, but i have them so often i don't think they're causing this: 

[08:17:26] Failed to clean backup: Ein Teil des Pfades "C:\Programme (Server)\Eco\Storage\Backup\Game-2018-08-21-19.17.17" konnte nicht gefunden werden.

Any log files needed?

**Comment by quequiere** [comment]
Same problem for me, can we enable debug logs ? and how ?

**Comment by D3nnis3n** [comment]
We had this happen several more times the last days. Probably once or twice day.

**Comment by BlazeGuy2** [comment]
The output log is stored in C:\Users\Your_Username\AppData\LocalLow\Strange Loop Games\Eco.  That may provide some insight into the issues.

**Comment by BlazeGuy2** [comment]
Also are you running any mods?  If so, I'll need to know if this is happening on Vanilla as well.

**Comment by D3nnis3n** [comment]
No mods for me.

>

**Comment by BlazeGuy2** [comment]
7.7 is currently is close to release.  Once it is out, let me know if this issue is still persisting and include your saves.  Bumping down pri because I can't reproduce this on my machine.

**Comment by D3nnis3n** [comment]
In locallow there is no eco folder, are you sure there should be one?

Walker Mansfield <notifications@github.com> schrieb am Mi., 5. Sep. 2018,
02:15:

**Comment by D3nnis3n** [comment]
Neither a strange loop one.

>

**Comment by D3nnis3n** [comment]
Well, this error has been replaced.

It's no longer "Eco.exe stopped working" but "Unexpected .NET Handler Excecption: arrayList".

Could not get a screen shot of it, but as it happens once or twice every day (but no longer kicking players, yeh!) i should have one soon.

**Comment by D3nnis3n** [comment]
There i got it: 
<img width="1816" alt="gotit" src="https://user-images.githubusercontent.com/25908592/45266065-916f2400-b455-11e8-9fb4-cf3eb86e3a5e.png">

There is a gist of the "Details":
https://gist.github.com/D3nnis3n/e89193c2b936f21b70a94b8e164970cf

**Comment by BlazeGuy2** [comment]
Exception is: 
System.ArgumentOutOfRangeException: The specified argument is outside the valid value range.
Parameter name: arrayIndex

   at System.Collections.Immutable.Requires.FailRange (String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.CopyTo (T [] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor (IEnumerable`1 source)
   at System.Linq.Enumerable. <ReverseIterator> d__75`1.MoveNext ()
   at System.Linq.Enumerable. <TakeIterator> d__25`1.MoveNext ()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext ()
   at System.String.Join (String separator, IEnumerable`1 values)
   at Eco.Server.UI.ServerMainForm.UpdateDisplayText (IDisplayablePlugin displayPlugin, TextBox displayText)
   at System.Windows.Forms.Timer.OnTick (EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc (Message & m)
   at System.Windows.Forms.NativeWindow.Callback (IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by D3nnis3n** [comment]
Is that a note for me, e.g. did i install some prerequisites wrongly or is that a note for you?

**Comment by BlazeGuy2** [comment]
Potential threading bug, will look into unsafe threading functions once I get a chance with my CI task.

**Comment by thereporter42** [comment]
Version: 0.7.8.5 beta Server

Steps to Reproduce:

Just let the server run for a couple of days

Expected behavior:
That the server would properly cleanup the backups
and handle them properly

Actual behavior:

Ok well this is pretty intresting the server has been running now for 
a couple of days and I have not mucked or touched the backup files
in any way but on my console window on the server which is running
Windows 7 

I am getting the message 

[11:20:39] Removed backup - C:\Program Files (x86)\Eco Server\Storage\Backup\Game-2018-12-13-09-26-22

[11:20:39] Failed to clean backup: Could not find a part of the path 'C:\Program Files (x86)\Eco Server\Storage\Backup\Game-2018-12-13-09.26.22'

A screenshot of this error can also be seen at 
https://ibb.co/dGM3PL4

As the path exists i can see other backups in there so what the heck gives?

I checked the properties on the Backup directory and there isn't anything strange
there I thought maybe it got set read only or something goofy like
that but no everything is ok.  The user also has full admin rights 
as well on that machine so that should not be an issue either. 

I checked the security settings to make sure it has the right
permissions and they are fine as well. 

Do you have mods installed? Does issue happen when no mods are installed?:
I have no mods installed.


![eco failed to clean backup 0 7 8 5 server error](https://user-images.githubusercontent.com/38896397/50020775-3ee15e80-ff94-11e8-905b-755b89e67c53.jpg)

![eco failed to clean backup 0 7 8 5 server error 2](https://user-images.githubusercontent.com/38896397/50020976-cf1fa380-ff94-11e8-827b-a7ba622717c1.jpg)

**Comment by D3nnis3n** [comment]
You should open a new issue for this, this is the wrong place to report it.

**Comment by mirasrael** [comment]
Had this on Streamers server multiple times. 
Problem seems related to this issue:  https://superuser.com/questions/859439/what-has-really-happened-when-windows-says-x-has-stopped-working

**Comment by mirasrael** [comment]
Seems fixed
