### ISSUE TITLE
USER ISSUE: steam overlay tooltip overlap UI elements.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9086]
**Version:** 0.7.7.0 beta staging-b938b54c
Steam tooltip position need to be changed.
Current position overlap important UI element.
![2018-08-26 19 10 13](https://user-images.githubusercontent.com/4980243/44630335-40930200-a964-11e8-94d6-a7b40a875948.png)

Ideal position as i see - top right corner.

**Comment by seccombew** [comment]
Possible dupe.

**Comment by elfl0rd** [comment]
not found any open issue.
But as i know - it's easy to fix :)

**Comment by mirasrael** [comment]
This issue was opened:
https://github.com/StrangeLoopGames/EcoIssues/issues/8900
And loading tree was moved to the left corner, but @elfl0rd mentioned a bit different problem: moving load tree is not fixing problem in whole, because steam overlay conflicts with more elements than just loading tree. So he suggests to move steam overlay instead in top-right corner to reduce potential UI overlaps.
