### ISSUE TITLE
USER ISSUE: 7.7 Staging: Missing options from Place and Pick up in Law Creator

### ISSUE THREAD

**Issue by Hydrohawk** [StrangeLoopGames/EcoIssues#9092]
**Version:** 0.7.7.0 beta staging-b938b54c

**Steps to Reproduce:**
Looking at the new laws, it appears that there is not longer the abilty to create a law for road building, as neither Stone nor Asphault roads are options in the Pick-up and Place menus on the law page.  Not sure if this was intended or not.

**Expected behavior:**
Should be able to create laws to encourage players to build roads, while reducing griefing.

**Actual behavior:**
Both roads are "missing" as selectable objects.

**Comment by elfl0rd** [comment]
you are discovered it?
https://github.com/StrangeLoopGames/EcoSuggestions/issues/470

**Comment by MarjieAVolk** [comment]
When you say they're 'missing', do you mean you had an existing law that referenced them and now it doesn't work?

**Comment by Hydrohawk** [comment]
OK.  Gave myself All the skills and every item was unlocked in the laws page.  I'm assuming this is how the laws are intended to work now.  I'll create a new world in 7.6 and see if I can create a road law in that...then see if it translates.

**Comment by MarjieAVolk** [comment]
Cool, thanks.  I believe it has always been this way with the research unlocking stuff in laws, or at least for a long time, but the way the item filters work for pick up/place etc has changed a bit in this release, in order to better support mining, tree debris, and other slightly weird items.  Roads are also kind of weird, so it's possible they were affected.  I think migration should be handled for everybody, but always good to have people checking stuff like that.

**Comment by Hydrohawk** [comment]
Just check it in 7.6...What you say is correct.  The roads aren't an option until the skill is unlocked.
