### ISSUE TITLE
Master key for Web Interface API

### ISSUE THREAD

**Issue by j3fffff** [StrangeLoopGames/EcoIssues#9182]
we would want some sort of key that can be used in lieu of auth as a master key into any API on the server, rather than using the admin user for that

we could add that to get around the needs to login issue(s)
hosted worlds
-> buy a server -> generate a "master" key -> spin up server using master key
-> configuring server -> use master key to call server APIs

instead of relying on an "admin" user for the above
you'd just generate some random string or GUID that hosted worlds would track and use, then you dont need a user ever

**Comment by pamduncan** [comment]
This is an excellent idea. and many games out there do it.  Done right its fantastic,  done a bit odd like a few of them its a disaster for any one hosting multiple servers even on a home PC  :)  still doable but a disaster in the extra time and work that has to go into handling the creation of the keys and registering them and what the key installation process at the server.   

We run some servers that you hardly notice a key is in play and others where the bush must be beat for 15 minutes to obtain the key and sacrifices have to be made to get the server to accept it.  

In many of these they neglected to consider that some of the info the key would contain was by design things the player could change on the go such as a server name, in other words configurable options,  So if a server owner changes anything that is used to generate the key they are then back out beating the bush for a new key.

**Comment by mirasrael** [comment]
Issue here is many API actions requires an user to be correctly executed. I.e. Law API, so we should either limit number of APIs supported with the master key and ensure they don't need any User to proceed or should use surrogate user, but then it doesn't differ much from using pre-created admin user.

Any thoughts @rainfarmer ?

**Comment by rainfarmer** [comment]
Don't see any problems with passing auth token with api calls, like we currently do.

**Comment by j3fffff** [comment]
one issue with depending on a master admin users, is the owner of the world could remove that user, wondering who this extra admin is. then when they need help with the world, we cant access.

**Comment by mirasrael** [comment]
There already APIAuthToken and APIAdminAuthToken which should solve the issue.
