### ISSUE TITLE
Player can't connect to our server - fails after 45% world load

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9217]
See the discord chat - i got now idea, she could play on our last server and we got 20+ players online at the moment at the server. Her ping seems fine compared to people from Australia with 400+ being able to play, too.

<img width="323" alt="joinproblem" src="https://user-images.githubusercontent.com/25908592/45179434-d0fcfc80-b218-11e8-827f-98555cc17182.png">

**Comment by johnkslg** [comment]
Can you ask her to message me discord.gg/eco @johnk

**Comment by D3nnis3n** [comment]
I just asked her to do so.

**Comment by johnkslg** [comment]
Dont see you in there, which discord server?
whats your discord name

**Comment by D3nnis3n** [comment]
Your discord server, #support channel

**Comment by D3nnis3n** [comment]
@D3nnis3n

**Comment by johnkslg** [comment]
Fixed! Will be in next hotfix. Thank you!

**Comment by D3nnis3n** [comment]
You're welcome and thanks to you!

**Comment by pamduncan** [comment]
FYI:  The owner deleted the profile but player was not available to log in so not sure if that resolved for them.  Have had several others since this one and they were told a hotfix was pending they could wait for or they could delete the player profile.  They deleted the profile and it resolved the issue for them

**Comment by johnkslg** [comment]
Fixed
