### ISSUE TITLE
Distribution Station - No Text will be saved

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9221]
I tried to enter text into my distribution station, pressed save and no text was there.

**Comment by johnkslg** [comment]
Invoke /TestDistributionStation to spawn this, then open the object, go to the text tab, and try to enter text.  It should update through the view system, with .changed called on the text field that is 'synctoview', triggering an update on the client, which then updates the text on the object.

**Comment by D3nnis3n** [comment]
Was that directed at me or a internal notice?

**Comment by johnkslg** [comment]
That just means you dont have auth on that object.
So instead place your own.
Give yourself a distribution station (/give distributionstation)
place it, open it, set the text

**Comment by sidjuego** [comment]
@johnkslg 

Apparently, it is happening because of the Null Reference exception.
It is coming from CustomTextComponent.cs 

** this.MaxStringLength value is coming as zero because Initialize is not getting called**
and in CustomTextUI.cs;  this.view.MaxStringLength is coming from WorldObjectView and from there its also coming as 0.
It would be great if you could explain how the WorldObjectView is synced with the view.

**Comment by johnkslg** [comment]
Views synced to the client when they are tagged [SyncToView] and Changed is called on them.
Is the server setting the max string length properly?

**Comment by sidjuego** [comment]
@johnkslg No, the server is not setting the max string length. However, to verify this issue, I had added a break point to this property and the value was always 0.

**Comment by sidjuego** [comment]
@johnkslg Is the Character limit supposed to be zero?Because it is taking max character limit as  zero in the script so it is showing null reference. What value would you like to have for the character limit? 

![capture](https://user-images.githubusercontent.com/43029943/45940541-53e2cd00-bff7-11e8-816b-2c28e0ad334e.PNG)

**Comment by sidjuego** [comment]
@johnkslg We have fixed it and we're keeping the **maxStringLength as 500** for this. Please confirm whether this value would be Okay or do we need to **change it to any other number ?**

**Comment by D3nnis3n** [comment]
The character limit for signs seems to be around 700 (at least i can type 695 characters before it blocks me to write more) - as this is supposed to be some kind of sign, you could set it to the real character limit that Signs like Large Lumber Standing Sign, Large Hewn Log Standing Sign or Large Stone Standing Sign have? (You probably find that in your tool?)

Just a suggestion.

**Comment by sidjuego** [comment]
@D3nnis3n Ahh okay, so would setting it to 700 fulfill the requirement?

**Comment by D3nnis3n** [comment]
It would behave mostly like a sign then, so that would be fine for me as player (e.g. my recommendation). Please note, i am a player. You probably wait for what @johnkslg has to say to this, as i have nothing to decide and he surely knows how it is supposed to be.

**Comment by sidjuego** [comment]
@D3nnis3n Okay, let's wait for @johnkslg then
