### ISSUE TITLE
UI size is a problem

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9257]
It seems like the UI now saves the size of other UIs or something is wrong with the map. I commonly get this when i open the map, several players complained about that behaviour: (If you don't get what i mean: The map appears in a insaneley big windows, sometimes the earth ball is even stretched from one side to the other)

<img width="1666" alt="mapui" src="https://user-images.githubusercontent.com/25908592/45249191-1d7d3080-b31c-11e8-868f-51c4dc6b19c9.png">

**Comment by MarjieAVolk** [comment]
Okay I'm finding several issues with minimap size saving, which are related to the new minimap settings panel.  So I'll assume this is specific to that.

**Comment by D3nnis3n** [comment]
Well all the other UI elements seem to share size, too. As of the tooltip bug i quite often drag up the storage UIs very big so i can somehow move things to other places in order to finally get them where i want in the end and that carries over to other UIs. The map though just opens very big - sometimes from the complete left to the complete right but not very high - so it's not the same size like my storage UIs.

**Comment by MarjieAVolk** [comment]
It is true that all of the windows for objects will share the same size.  For example your workbench and your store will always have the same size window on restart.  Is that what you mean?  That might be confusing or annoying, since you can change the windows separately while playing, but when you reload the game all of the object windows will be the size of the last window that you resized.

What you describe with the minimap though does sound like a problem with the filter panel, since it makes it get wider and wider.  And those I believe I have fixed.

**Comment by D3nnis3n** [comment]
Yeh, probably i only noticed that as i had to make the windows so big to be able to move over items as of that tooltip bug everyone on our server has. But for the map you might be right that this is an issue. I'll report back after the next hotfix.

**Comment by MarjieAVolk** [comment]
Fixed in 8.0
