### ISSUE TITLE
Stairs issue

### ISSUE THREAD

**Issue by dwujcik** [StrangeLoopGames/EcoIssues#9292]
In the build mode. The location of the stairs is rotated.
Should be perpendicularly.
v0.7.7.0 beta

![20180909205342_1](https://user-images.githubusercontent.com/17785084/45267761-3cdaa180-b473-11e8-9665-51196a73cc16.jpg)

**Comment by Nicolausi113** [comment]
I reported this in #9023
The bug is still present for hewn logs, mortared stone and maybe bricks work.

**Comment by keegan-o** [comment]
I really don't know how to fix this, the builders are all super clean, simple, and double checked that they all make sense, and they do. To debug further I need a way to determine which block it's placing down out of the options:
HewnLogStairs
HewnLogStairs90
HewnLogStairs180
HewnLogStairs270

Then I could determine if it's somehow in the builder, or if the selection/building tool code is placing the incorrect block (or displaying a preview of the wrong one).

**Comment by keegan-o** [comment]
Something is real weird about this in placement because it doesn't shift the stairs based on the way it shifts itself when placing. Like in certain situations it will force a particular placement, but then you can add something nearby and it will allow you to place it differently on top of that, and not change back when you remove that block you added.

If it were a problem in the builder, i.e. being placed a certain way to match rules, then the block would also update when things were changed around it. But it doesn't-- so it's something with the placement code I think.

![brokenplacement](https://user-images.githubusercontent.com/14983165/45333349-98b43180-b52a-11e8-9f15-de926dc640b3.gif)

**Comment by keegan-o** [comment]
![image](https://user-images.githubusercontent.com/14983165/45379096-06f10680-b5b4-11e8-9ae1-e0b49355916f.png)
![image](https://user-images.githubusercontent.com/14983165/45379158-2daf3d00-b5b4-11e8-9888-adc673b444b7.png)

Alrighty, confirmed with the soil sampler that the stairs always facing that direction are always the same block-- they're never the wrong block type (always HewnLogStairsBlock, and never HewnLogStairs90Block or another one), so it's the wrong block-type being placed down in the world based on some kind of criteria, not anything in the builder.

**Comment by keegan-o** [comment]
I'm throwing sean and eric on this in case they have a way to check it out better than those of us that have come before.

**Comment by metachronism** [comment]
cant repro

**Comment by SeanAtr0n** [comment]
![stairsbug](https://user-images.githubusercontent.com/774628/51283381-dd4e4e80-199c-11e9-8543-1773a6bb04c7.gif)

**Comment by elfl0rd** [comment]
yes, still happens with vertical ladders too.

**Comment by SeanAtr0n** [comment]
think i found the problem
