### ISSUE TITLE
Can move 10 blocks at a time with shovel

### ISSUE THREAD

**Issue by Nes112** [StrangeLoopGames/EcoIssues#932]
Blocks moved with the shovel (dirt/stone/ore) are meant to be moved one at a time, but when put into a container, the stacks of 10 can be clicked and dragged from the container to the "Carrying" slot in the toolbar. 

This trivializes the transportation system when mining these blocks.

**Comment by ChronosWS** [comment]
The problem here appears to be that InventoryChangeSet.MoveStack does not have a way to recognize the rule suggested above.  In the case of dirt, the max stack size (in any inventory) amount is 1, but for other items (like logs) this amount would be 10.  This value comes from BlockItem.MaxStackSize, an override of Item.MaxStackSize.

To fix this would require managing of stacks to be aware of two possible limits on stack sizes: the limit imposed by the item type, and a further limit imposed by the inventory, parameterized by item type.

**Comment by midn8t** [comment]
when placing the dirt into cart and then from cart into the factory inside building it already takes quit few trips about 8 now if you have 80 blocks it take 80 trips its better quality of life as it is right now.

make up difference they could just have it so more dirt you carry more calories it takes

**Comment by MarjieAVolk** [comment]
My vote for this would be to have a max capacity for carrying (maybe something in between, like 5), and enforce it the same for picking up blocks from the world & from chests.

**Comment by metachronism** [comment]
at its core this has turned into more of a design issue;  stockpiles+linked inventories might make this fine, but needs more input

**Comment by craig-jong** [comment]
if we're fixing this "bug", now is the time to do it, I guess.
