### ISSUE TITLE
Chat sometimes needs to be refreshed manually

### ISSUE THREAD

**Issue by metachronism** [StrangeLoopGames/EcoIssues#942]
Unusure of exact repro conditions, seems to be tied to saving the opened state of the chat window.

Sometimes you just don't get any chat messages so you dont know that anyone is talking.  if you open/close the chat then the messages refresh as normal

**Comment by MarjieAVolk** [comment]
Wasn't able to repro, but noticed a possible race condition for chat initialization that might cause this.  Submitted a pull request with fix for that

**Comment by Hariberu** [comment]
This issue started for me in 5.2, about 3 hours playtime, i decided to take a break and just stand in my house to watch something on the tv while also monitoring the chat, and the chat suddenly stopped "refreshing".
This has only happend once and has not been "Fixed" since.

i tried to fix this myself by doing
- a normal restart of the client
- Reinstall a fresh client
- restarting the computer

The results were the same, Negative.

This happend on the server "Pairidaeza - Friendly & Meteor"

**Comment by MarjieAVolk** [comment]
So you all of a sudden stopped receiving messages, and then reinstalling the client didn't fix it?

**Comment by Hariberu** [comment]
correct.

**Comment by noblackthunder** [comment]
http://ecoforum.strangeloopgames.com/topic/1280/log-messages-are-not-displayed

**Comment by Hariberu** [comment]
after a couple hours of not playing, i decided to log on again and now it works like a charm again.
i have not done anything to Eco since it stopped working.

**Comment by MarjieAVolk** [comment]
Sounds like it's likely a server side issue then

**Comment by Hariberu** [comment]
no one else besides me on the server have had this issue after 5.2, there were 6 others online when i noticed the issue. However, if this issue happends once more i will notify you.
