### ISSUE TITLE
Laws - Hours since last online

### ISSUE THREAD

**Issue by Deantwo** [StrangeLoopGames/EcoIssues#9482]
Missing a law clause for "number of hours since the player was last online".
This would make periodic allocation and tax laws easier to use.

For example to tax everyone that hasn't been online for x number of hours or days.

Technically you can just check the timestamp of the last "Play" action and subtract current day.

**Comment by Deantwo** [comment]
This would also be useful as a where condition for 'number of players'.
See: #8695

**Comment by Deantwo** [comment]
```
If your Play actions where (current time (days) - 1) > 0
```
Can maybe be used to check if the player has done any actions within the last 24 hours, but I have note tested it.
An actual "number of hours since the player was last online" value would still be a lot more useful.

**Comment by D3nnis3n** [comment]
Adding this to my list, Deantwo already has given a great explanation on why.

**Comment by Knigge** [comment]
"bump"

**Comment by Deantwo** [comment]
Also related to: #9039

**Comment by WeaselDog** [comment]
Here is how it looks in 9.0 staging:
![HoursPlayed](https://user-images.githubusercontent.com/47330823/69759898-ffb20c00-1117-11ea-9af8-10d8c668031c.png)

For Action Count it uses hours instead of days:
![actioncounthours](https://user-images.githubusercontent.com/47330823/69760240-d34abf80-1118-11ea-97e4-f3362f5836ed.png)

Citizen Age in Hours = Hours since first login:
![CitizenAgeInHours](https://user-images.githubusercontent.com/47330823/69759977-27a16f80-1118-11ea-8f03-5d902d2cead8.png)


There is no comparison for "number of players where(x)", but all the time comparisons look good.

**Comment by beastyn** [comment]
Need to check every of them, if there is a problem will discuss in a separate issue
