### ISSUE TITLE
The player is unable to obtain a vehicle back to inventory when it has fuel in it.

### ISSUE THREAD

**Issue by vigneshjuego** [StrangeLoopGames/EcoIssues#9507]
Description: If a vehicle is equipped with fuel in the fuel slot and the player uses the hammer to obtain the vehicle in the inventory, the fuel is getting obtained instead.

STR:
1. Start the game.
2. Create/Join a world.
3. Obtain and place a vehicle.
4. Place some fuel in it.
5. Obtain and equip the hammer.
6. Try to left click on the vehicle and observe the issue.

Actual Result: The fuel is getting obtained instead of the vehicle.

Expected Result: The vehicle should get obtained.

Screenshot:
![screenshot 450](https://user-images.githubusercontent.com/43132426/45953401-93c1a880-c027-11e8-9b51-0053494633c5.png)

**Comment by D3nnis3n** [comment]
This is probably no bug. As you can't get the vehicle with fuel inside into your car - as you could otherwise carry around cars with things inside you need to get the fuel out of it first, which is what the hammer does then. As soon as there is no more things stored in the car you can pick it up. I experienced this as intended behaviour until now.

**Comment by seccombew** [comment]
Can't carry oil and truck due to weight limit in inventory.
