### ISSUE TITLE
EcoSim.eco animal HabitabilityComponents are messed up

### ISSUE THREAD

**Issue by SeanAtr0n** [StrangeLoopGames/EcoIssues#9548]
A bunch of species appear not to consume anything when you inspect their Habitability component, but if you debug they have prey listed.

Something is messed up with their serialization

**Comment by craig-jong** [comment]
![image](https://user-images.githubusercontent.com/18184943/46827805-75112080-cd4e-11e8-9056-428e7d26a6c0.png)

They don't show up checked in the reference list, but they do show up in the EcoSim.eco config file. We might want to move this stuff to the species anyway (instead of the layer) but I don't want to do that in a 7.8 hotfix.
