### ISSUE TITLE
Don't allow checkerboard houses

### ISSUE THREAD

**Issue by MarjieAVolk** [StrangeLoopGames/EcoIssues#955]
This shouldn't be a valid house, but it is:

![checkerboard house bug](https://cloud.githubusercontent.com/assets/23460210/21598581/e65af560-d113-11e6-87c2-9a306ddc07c4.png)

**Comment by metachronism** [comment]
room detection ftw!

**Comment by metachronism** [comment]
room detection has laregely made this irrelevant now

**Comment by MarjieAVolk** [comment]
Has it?  I wasn't under the impression that room detection changed this yet

**Comment by metachronism** [comment]
craig can close if he thinks its ok

**Comment by metachronism** [comment]
I think its an aesthetic choice though, checkerboard house seems like its still "technically valid"

**Comment by craig-jong** [comment]
That specific example is not valid anymore - the roof of that building makes it invalid. The walls can still do that. I don't think it's a major issue or something we need to active 'fix' since the only real fix I can think of is limiting the number of empty window blocks which, given a large enough room, could be restrictive.

I guess we could limit the number of windows based on the size of the room or something.
