### ISSUE TITLE
[beta 7.8.0 b7709677] Missing Objects

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9559]
> Missing following objects: APGenObject, ButtonObject, ElkSkypiercerObject, LogicGateObject, SwitchObject, TollObject

**Comment by craig-jong** [comment]
Lowering the priority further since none of these objects are even s'pose to have models. They're all intentionally using the default world object because they're debug/testing objects.

**Comment by craig-jong** [comment]
Also removing Keegan because they dont actually need art.

**Comment by D3nnis3n** [comment]
Just for clarification: This was a task of the QA Sheet, hence i reported this issue.

**Comment by ragaar** [comment]
I'm failing to connect to the public servers and this is the only error I receive.

The client progresses to *"Entering world..."* and gives me an endlessly spinning wheel.

&nbsp;

Allowing the game to sit on this screen, for durations greater than the length of making coffee, may connect me. Only to immediately show that my connection has been dropped, as the "disconnection warning" pulsates above the world map in the bottom-right corner of the UI.

&nbsp;

**Tests:**
I have performed a whole slew of client-side investigations to figure out what is going on.
1. I **can** connect to public servers when physically connected to my friend's network.
2. I cannot connect to public servers from my network.
2. Cannot connect when using public VPN.
3. Cannot connect when using private VPN to friend's network.
4. I have issues connecting to all public servers.

**Observations:**
Ping to the server shows 20-40ms, round-trip.
Packet drop at a rate of roughly 2%. (ping /t)
Tracert is the same as my friend's network but under a different ISP (AT&T instead of Comcast).
At my friend's house, no issues. Everything is working as expected.

**Follow-up:**
Working on downloading Wireshark to check the packets, also looking into whether the ISP might be blocking ports; although I wouldn't expect that to be an issue.

**Comment by ragaar** [comment]
Confirmed, AT&T is not blocking the ports<sup>[[1]](https://about.att.com/sites/broadband/network)</sup>.

REF: https://about.att.com/sites/broadband/network

**Comment by ragaar** [comment]
New internet connection fixed it.

**Comment by D3nnis3n** [comment]
Old issue.
