### ISSUE TITLE
[beta 7.8.0 b7709677] Contract - Not reaching volume gives an error about not having used the building material wanted

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9572]
When you build a house out of bricks, like the contract for it made with /spawncontracts is saying and you did use the needed 7 bricks to do it but did not reach the volume of 65 it will NOT complain about you not having built a room with volume 65, but about you not having used 7 bricks, which you did.

**Comment by johnkslg** [comment]
Need to change this clause to instead check the Tier of the room, rather than specific materials used.

**Comment by Spydarlee** [comment]
Pull request submitted. The original issue was, I think, due to a bug that meant the "No room at requested location" message wasn't being shown correctly. But I've also made the change you requested, @johnkslg so the Build Room clause now looks like this.

![image](https://user-images.githubusercontent.com/553695/46673127-0064a780-cbd1-11e8-9134-3e1b099bfd04.png)
