### ISSUE TITLE
[beta 7.8.0 b7709677] Removing debris contract does not work - probably related to having another contract on the same property

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9573]
Using /spawncontracts, the remove debris contract does not work as it does not grant me permission do so.

Special thing: I still got the building contract that is on the same plot unfinished. Probably it does not give me permission as i have another contract running there that only wants me to build and those two collide?

**Comment by johnkslg** [comment]
Check this when you checkout the other bug

**Comment by Spydarlee** [comment]
Using /spawncontracts doesn't actually generate any tree stumps/debris, so when I attempted to repro I could just click "Job Finished" as soon as I accepted the contract and it completed.

However, when setting up a removal contract manually I did run into a permission issue. Tree stumps work fine but not tree debris. You get permission to perform the chop action (debris highlights green) but the actual removal isn't allowed.

I tracked this down to AxeItem calling ToolItem.PlayerDeleteBlock which performs an authorisation check but doesn't pass along a GameAction which means ActionManager.ShouldOverrideAuth never checks for contract overrides and the auth check fails.

Tree stumps get around this because their interaction goes through the damage system and it just performs the delete without an additional auth check. I suppose we assume that's safe because if it's been allowed to get that far (already performed the chop action) the delete is fair game.

How would you like to fix this one, @johnkslg? I could add a bool to PlayerDeleteBlock to optionally bypass authentication? Or perform the delete manually, although I'd also need replicate the inventory changes and stamina consumption logic that PlayerDeleteBlock currently handles.

**Comment by D3nnis3n** [comment]
Yes, it doesn't, but on the same plot is a tree, that you have to cut in a contract before, so i had debris on that plot. Great that you have found the real issue hiding behind this :)

**Comment by johnkslg** [comment]
Couple things:
1. Can you make the /spawncontracts command spawn some debris on the plot it assigns?  Can make separate plots too. 
2. Make PlayerDeleteBlock create a GameAction and pass it into auth, check PlayerPlaceBlock which does this, will be almost the same. 
Thanks for tracking this down!

**Comment by Spydarlee** [comment]
Done! Had some trouble spawning debris directly (couldn't access TreeDebris from Tests project because it's a mod, etc.) so I went with spawning a tree and then immediately killing it. That's a bit hit-and-miss, too, unfortunately - it (usually) creates a tree stump but no other debris. If you know of a better way to do this I'm happy to alter it.
