### ISSUE TITLE
[beta 7.8.0 b7709677] UI looks wrong on container in which i should put items as of a contract

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9589]
See the screenshot. I can only put the items in by rightclicking and get a weird UI when opening the stockpile with "e". Contract made by /spawncontracts.

<img width="1803" alt="uiwrong" src="https://user-images.githubusercontent.com/25908592/46160062-1f367600-c282-11e8-9ba9-820e74a90b1e.png">

**Comment by D3nnis3n** [comment]
The version of the game i used is in the title of the issues. In this case, bleeding edge once again.

**Comment by Spydarlee** [comment]
Thanks! Still not had any luck reproducing this one, unfortunately. Do you get it reliably, @D3nnis3n? Do you get it with a fresh character/world? Any other steps involved in order to reproduce? 

I've tried using /spawncontracts several times and with different users but all the stockpiles that get generated seem to behave as expected so far.

**Comment by johnkslg** [comment]
@D3nnis3n reopen if you can repro
