### ISSUE TITLE
No Fees or taxes on Repair Station seems to have been missed out

### ISSUE THREAD

**Issue by Conchipedia** [StrangeLoopGames/EcoIssues#9599]
**Version:** 0.7.7.2 beta

as you can see a normal table like a Kiln can be used by another player and be charged for doing so
![snap2983](https://user-images.githubusercontent.com/29383891/46236643-b3ced000-c377-11e8-85be-e803bd0e5d84.png)
but this is missing from a Repair Station
![snap2984](https://user-images.githubusercontent.com/29383891/46236673-d5c85280-c377-11e8-8323-cc8a0a948a15.png)

**Comment by D3nnis3n** [comment]
That has been mentioned several times in the QA Sheet, i linked your issue there.

**Comment by Conchipedia** [comment]
only found this out after setting up the Local Dump where bars and now steel is sold, I wanted to be able to let them buy ingots and steel and repair at same place, otherwise i have to buy broken tools (and sell NEW ones) and then charge them more for me to have to repair them

**Comment by johnkslg** [comment]
This would be a new feature, not a bug fix, but @Quadbro you can add it at your leisure.

**Comment by Quadbro** [comment]
Yeah, nice idea, and can we count the skill requirements for repair station owner (placer) instead of user? That will have more sense, because it's ridiculous to pay smth in a very easy to make repair station...)

**Comment by elfl0rd** [comment]
> repair station owner (placer) instead of user?
In my opinion, this would contradict the logic of workbenches.
Why then the paid workbench does not use the skills of the owner?

this change is overly simplify the game, allowing pumped players do not go for a long time.
Currently, players with a high skill of repair use shops to buy broken and sell repaired.

**Comment by Quadbro** [comment]
> In my opinion, this would contradict the logic of workbenches.
Yeah, you're right didn't think about it..)

**Comment by D3nnis3n** [comment]
I would disagree with elfl0rd here and like your idea. Buying the broken tools and selling them again is something our players do at the moment, too. But they rather would like to be able to sell the needed ingredients for repair and then allowing a fee on the table so the guy can repair it's tools there with the efficiency the tool owner has. 

I don't see (or don't understand what you mean) that this would simplify the game nor allow "pumped players to not go for a long time". I find this change useful and encouragin to repair tools more instead of throwing them away. Most of the tool makers in our server only buy a small amount of broken tools, equivalent to the ones they sell repaired - so you are limited on when you can repair your tool. This is due to people not wanting to buy too many broken tools without getting sold repaired ones. Also most people do like automation for ease of use - that's what a shop does.

**Comment by elfl0rd** [comment]
I can only agree to a new repair machine.
In this case, the current repair table works as it worked, new, much more expensive workbench allows you to use the skills of its owner and not the user when repairing.
