### ISSUE TITLE
Footstep sounds while in vehicles

### ISSUE THREAD

**Issue by goobie** [StrangeLoopGames/EcoIssues#9687]
Eco 7.7.2

**Steps to Reproduce:**
Walk up to a vehicle and enter it while still holding down the forward key. 
Footstep sounds continue to play while you're in the vehicle 

**Expected behavior:**
It should not emit footsteps noises while you're in the vehicle.

**Actual behavior:**
Footstep sounds continue nonstop until you exit the vehicle.

https://www.youtube.com/watch?v=K-YC4xeM5Yw

**Comment by pamduncan** [comment]
Does this happen after you have been online a while or even after you have just logged in?  What is your ping to the server?  The reason I ask is that we have seen this same thing and its turned out to be something like a desync between server and player - if we have that player who is hearing footsteps while driving to do some other things that get weird if the player is desynced and when they do these they have issues that point to them being desynced.  Once they log out and back in and get in the vehicle the footsteps stop as they get in then.  its just a work around and not a cure because after a while they often end up desynced again a few hours later.

**Comment by goobie** [comment]
From what i've said it happens all the time.

The server I was on didn't have the best ping (i think ~300ms). I'll check on a local server tonight.

**Comment by SlayksWood** [comment]
In the version 0.8.1.0  isn't observed. There is another issue #11884

**Comment by goobie** [comment]
This is still happening in 0.8.3.3
https://youtu.be/R5fA6puAPvk
