### ISSUE TITLE
Found some web queries not returning localized

### ISSUE THREAD

**Issue by johnkslg** [StrangeLoopGames/EcoIssues#9708]
![image](https://user-images.githubusercontent.com/3536496/46985916-913ff500-d0a1-11e8-90cb-f85db1e53dfc.png)

Humans, All, and Accept Contract appear to not be localized

**Comment by j3fffff** [comment]
this is on game side

**Comment by gabrielgindridev** [comment]
As this issue is a bit old, confirmed that the get `/dataset/graphs` is not used anymore and will **close**:

![image](https://user-images.githubusercontent.com/65634950/114721736-97b19500-9d0f-11eb-996c-d2b0fd9295ae.png)

the `RebuildGraphs` method does nothing and it's all commented out
`this.graphs` is always empty(also tested with postman), has no references anywhere else

Even in JS
![image](https://user-images.githubusercontent.com/65634950/114722021-d47d8c00-9d0f-11eb-9e39-8eb923e85817.png)

Closing issue!
