### ISSUE TITLE
Balance - reinforced concrete.

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9761]
Now it is too expensive and does not correspond to the real world.
In real life, reinforced concrete requie really, REALLY more concrete then rebars.

Just compare the volumes!
![664](https://user-images.githubusercontent.com/4980243/47059005-1e816780-d1d0-11e8-9b23-ddac96e889d8.jpg)

Maybe - flip rebars and concrete requiments at reinforced concrete reciepe.
e.g. from
![default](https://user-images.githubusercontent.com/4980243/47060987-5a202f80-d1d8-11e8-8574-04e2d6b16fd2.png)
To
10 rebars + 20 concrete, etc.

**Comment by elfl0rd** [comment]
@Conchipedia I think you might be interested in that, too. :)

**Comment by Conchipedia** [comment]
would make sense to have more concrete than rebar ratio, or just call what we have as reinforced concrete Reinforced Rebar 😆 

for more information please see this
https://www.uiet.co.in/downloads/20140911103651-sp.16.1980%20Structural%20Designing%20Practice.pdf

**Comment by Ketrai** [comment]
It doesn't make sense from a game balance perspective either. Flat steel, which is literally solid blocks of stainless rust-free steel. Requires the same amount of steel? The other element being Petroleum, which is a resource constantly produced by oil drills. With maxed efficiencies, you can produce one flat steel with 0.4 steel and 0.2 proxy. which translates into 0.2 petroleum cost for a single block. This doesn't make sense.

Reinforced concrete will always take 1.6 stone, and an average of 0.8 steel. Sure, stone is abundant as hell, but that doesn't change the fact reinforced concrete is effectively more expensive steel-wise than a solid block of steel. 

On top of that, to create reinforced concrete, you're polluting more due to needing more blast furnace. I'm unsure of the rates of cement kiln as opposed to oil refineries.

**Comment by Deantwo** [comment]
As a side note, maybe we could get a recipe to turn Mortared Stone into concert? Hewn Logs have a use, why doesn't Mortared Stone?
