### ISSUE TITLE
Master - loans\bonds broken

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9779]
![default](https://user-images.githubusercontent.com/4980243/47111023-102c5d80-d25b-11e8-9428-b34952037300.png)
![default](https://user-images.githubusercontent.com/4980243/47111047-20dcd380-d25b-11e8-870e-83854eab1544.png)
![default](https://user-images.githubusercontent.com/4980243/47111285-cb54f680-d25b-11e8-91da-77d8990414b4.png)

**Comment by elfl0rd** [comment]
And as i see, it broken on release too (7.7.2)
But different.
You can accept, receive debt, but not receive money, heh.

**Comment by johnkslg** [comment]
Can you check these are working with all the new stuff added?  
Also, can you write a /testdebt chat command, that triggers some loan variations on the server, then makes the client pay them back?  Work with @BlazeGuy2 to make sure it works with the new Continuous Integration system, so that the tests get run on PRs.  Check out /testexchanges for some examples, though that might need fixing as well.
