### ISSUE TITLE
Original text: need add dots, or remove existing. And maybe to correct one phrase

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9790]
![default](https://user-images.githubusercontent.com/4980243/47199412-267d0b00-d37a-11e8-9516-1e00d782ac88.png)
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#47998 - no dot
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50138 - has dot
https://crowdin.com/translate/eco-by-strange-loop-games/24/en-ru#50738 - no dot and confusing "tier of what?" I suggest text like "{0} ({1}) average room tier"

@Nanders

**Comment by elfl0rd** [comment]
![default](https://user-images.githubusercontent.com/4980243/47211133-686b7880-d39d-11e8-806d-1fb61e243e85.png)

**Comment by Conchipedia** [comment]
since we have average room tier added it is **harder** to work it all out, the only way we have found so far is to add blocks of a higher tier and removing the lowest tier in the room, but sometimes we get that nasty bit where someone has built a room, but has forgotten to remove the dirt/sand from the corners and **under** the walls and then cries out for help, and it can take ages tracking down the offending block(s) to actually make the room a solid shape so we have a basis to make a solid room

**Comment by elfl0rd** [comment]
@Conchipedia agree, i have issues about it.
e.g. #9636 #9637

**Comment by Conchipedia** [comment]
i don't want them to go back the the **old** way of a table saying that it needs 10 brick or 5 Hewn logs in a room, but something does need to be made clearer of how the room actually works without having to make a massive rebuild

**Comment by elfl0rd** [comment]
Yep, new system is beautiful but little confusing... Lot of people ignore tutorial :*(
