### ISSUE TITLE
[7.8.0 #79e33fd9] Entering a wrong ip into connect by ip still gives no feedback

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9801]
See this issue: https://github.com/StrangeLoopGames/EcoIssues/issues/9560

Something did change though: Instead of the ui menu where you type in the ip closing, it just stays open and does nothing, but lag heavily for a moment, as you can see in the video (notice the background freezing for several seconds):

https://drive.google.com/open?id=1MNlH061UZEV-D0cpZyy6vv8KXqbHhqtc

**Comment by BlazeGuy2** [comment]
It's being recorded in the unity log correctly, but the pop-up object is null for some reason.

**Comment by johnkslg** [comment]
@Spydarlee Also, separate issue while youre here: make popups in the world connection all use the same one (the one used in the game) and make escape close any popups (currently it can open the escape menu).

**Comment by Spydarlee** [comment]
This is what I get on master when I attempt to reproduce this (it doesn't actually use a separate error popup for this scenario, it just pokes the error into the connection box).

![ecoinvalidipaddress](https://user-images.githubusercontent.com/553695/48495598-43e1af80-e828-11e8-9072-db8a37f07554.gif)

But I've also submitted a PR which removes the custom error message popup and replaces it with the standard Popup, @johnkslg. There's also a custom popup for the loading message, but I've left that one because it has a special spinning icon that the standard popup doesn't.

**Comment by Deantwo** [comment]
"Invalid ip address"? Does that means we can't use domain names?
For example `eco.com` and `eco.com:3000` can't be looked up via DNS?
