### ISSUE TITLE
[7.8.0 #E50965c6] Make road contracts easier

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9929]
Road contracts sometimes don't work very well as the feedback you get is bad. It tells you where the last valid road block is - tell them where road blocks are missing to fulfill the quest, that's easier. I just can't get the roads done correctly of the spawned random contract, but when doing one myself (where the constructions posts are on the same height) it works perfectly. The information what the last valid road block is also doesn't help me at all, to be honest.

**Comment by johnkslg** [comment]
Not sure why it doesnt help, it displays the last block detected on the path between the two points.
You cant tell them where the next road block goes, because it could be anywhere. It depends what route they're building.  But most likely its going to be right next to the last detected road. 

I would like to improve this by making the road length and remaining distance constantly display and update while youre building.  And maybe there are some other ideas we can add.

Closing for now but we can revisit this next time we work on contracts.
