### ISSUE TITLE
7.8.0 Unable to join server after some time

### ISSUE THREAD

**Issue by Nanders** [StrangeLoopGames/EcoIssues#9931]
Server left running, after some time you can no longer join.

Happened on Stuffed Elk

**Comment by pamduncan** [comment]
This has been happening a great deal.  It used to be that if the server was up more then 24 hours it needed a restart on a pretty regular basis but recently it is requiring a reboot 2-4 times a day or players cannot log in   Se have just been setting auto reboots for every 6 hours.  The need to reboot periodically has, off and on shown up since 7.6 but was, at most, once a day.  It did not change for 7.7.0 or 7.7.1 or at first even on 7.7.2 but about the last 10 days its happening that it needs one more and more and it seems to be with servers that have been running the current world for  awhile (not on newly created worlds until they have been played on a while) almost like there is something that shows up after a certain place is reached in the game - like so many objects or a certain save file size or something and then the reboot need starts happening more and more often

**Comment by metachronism** [comment]
Need a repro case

**Comment by johnkslg** [comment]
@mirasrael we havent been able to repro these bugs, but would really like to figure out whats happening, want to take a stab at them?  
@Nanders can you attach stuffed elk save that went OOM

**Comment by johnkslg** [comment]
If mem gets super high should analyze what it is. Dont need it to run out of mem to check it out.

**Comment by johnkslg** [comment]
@mirasrael Getting multiple reports of this one, raising priority.

**Comment by mirasrael** [comment]
@pamduncan @Nanders Do we still have this issue after 7.8.0 release?

**Comment by D3nnis3n** [comment]
Is it this issue?

https://github.com/StrangeLoopGames/EcoIssues/issues/10065

I Added a dump there.
