### ISSUE TITLE
Addition to "door tiers"

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoIssues#9953]
https://github.com/StrangeLoopGames/Eco/pull/3561

1) Door need info about tier and and number of blocks in tooltip
e.g.
Lumber door equal 2 T2 block

Large Lumber door equal 20 T2 block

2) Door "blocks" need to show in room blocks tooltip
![default](https://user-images.githubusercontent.com/4980243/48182070-f7373980-e33a-11e8-950b-2cd686fa61e2.png)

**Comment by Quadbro** [comment]
@johnkslg Do we really need this?
> Door need info about **_number of blocks_** in tooltip

**Comment by Quadbro** [comment]
And about tier in tooltips (for doors, etc) 
I did some research, and found that i need to modify TechTreeGenerator a little to provide Tier info to WorldObjectItem instances instead of worldobjects, because we have no access to worldobject instance that has tier field from WorldObjectItem ...
May I handle that?) Or there is another way, that i missed?
