### ISSUE TITLE
Showing additional information in the currency viewer

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoIssues#9969]
Everyone knows the situation of you driving miles to a shop only to find out the player does either not have enough money to buy what you want to sell or it's storage is full. This can be and is seriously enerving for some players.

I propose to elaborate if you can add these QoL-Changes:

- Show on the economy viewer how much currency the store owner has.
- Show on the economy viewer how much of an item the linked storages of this store can still hold (at least with some colors, red yellow green for example, based on percentage of available room)

**Comment by johnkslg** [comment]
Sounds good, can add Storage Space and Owner Currency to the tracker class, and add columns in the economy viewer.

**Comment by Quadbro** [comment]
Tracking storage space for each trade on unclamped list  (trade  list has no pages) is a performance mess 
(Accessing to a huge amount of linked storage's, and count free space for a carried/not carried item at a single request)
Even if trade list had pages (showing  for ex 30 per page) it's steel a performance problem...

**Comment by D3nnis3n** [comment]
Could at least a warning message be implemented that Shows that inventory is full for this item? E.g. a check if that item could be sold or would Return storage full error and if it would you Show a notice?

**Comment by Deantwo** [comment]
I would rather class this as a player issue. We can't do anything about people making stores that buy unlimited commodities and don't supply unlimited storage.

**Comment by D3nnis3n** [comment]
We can - show a sign it's full. It's one of the most enerving issues i heard of.

**Comment by Deantwo** [comment]
Only way I see it is if each and every store monitored its own storage at whatever interval or whatever, and that simple value is shown on the economy viewer... But even that will be a littke demanding resource-wise.

And we are still talking about differentiating between items and carryed items.

Not to mention that people will still complain when they think they can sell 100 logs AND 100 stone to the same store because both rows said "100 free space".

If the economy viewer had a whole detailed store interface, then you could list details for the specific store rather than per offer. But that would be a lot of work for limited reward.

**Comment by D3nnis3n** [comment]
Couldn't you just try a fake sell trigger and if it fails as of inventory full display that?

**Comment by johnkslg** [comment]
I would put it on a throttle, updates storage capacity once every 5 minutes if flagged dirty, and only updates one tracker per frame or spreads em out.
