### ISSUE TITLE
"tailings" in chat, the tool tip doesn't show.

### ISSUE THREAD

**Issue by Zimgaha** [StrangeLoopGames/EcoIssues#9994]
Slight issue found on 7.8.0 when linking the word "tailings" in chat, the tool tip doesn't show.
![tailings](https://user-images.githubusercontent.com/44818253/48454040-af3a6b80-e7ad-11e8-8b9c-94a8d2dcd1cf.jpg)

**Comment by elfl0rd** [comment]
Discussed with Quadro in Discord. I'm thinking this problem is actually deeper.
This is a linking problem that's no provides choice.

For example, in the case of a user, most likely there was a previously existing _deed_ called Tailings.

You need to add 1) select when linking while writing in the chat 2) a matching list in already in the chat linking.

**Comment by elfl0rd** [comment]
e.g. create deed with name "Log" and car with name "Log" and try to link in chat :)

**Comment by Deantwo** [comment]
Instead of making duplicate links show up in parenthesis ([see](https://user-images.githubusercontent.com/6802030/48601606-00f81700-e9a3-11e8-805c-3249b060ed0d.png)), why not make a "disambiguation" link. Appear with a questionmark icon and maybe multicolored text, then have all the links in the tooltip of that link.

For example I write "Lumber" in chat and it appear as one of these disambiguation links, I mouse over it and the tooltip show me links to the Lumber skill and to the lumber item.

**Comment by WeaselDog** [comment]
The deed names were fixed so it is deleted now after the deed is deleted. 

Chat seems to prioritize non-deeds over deeds now when it comes to Tailings and other items. That is a separate issue we can create if it is still a problem.
